일기장 [STEP 1] Donnie, OneTool
yagom-academy/ios-diary pull request #10
Opened 2022-06-17 03:19 UTC by kimt4580

안녕하세요 또치! @TTOzzi
일기장 STEP1 PR 보냅니다!
STEP1 구현사항이 많지 않네요!
잘 부탁드립니다🙇🏻‍♂️🙇🏻‍

## 🧐 고민했던 점
### 1. JSON견본 파일에 있는 created_At 숫자의 의미를 알아내고, 사용자의 지역에 따라 날짜 포맷을 다르게 하기 위해 고민하였습니다. 

- JSON견본 파일에 있는 createdAt의 숫자의 의미를 알아내기 위해 다른 캠퍼들과 이야기를 나누었고, 어떻게 처리해야 하는가에 고민을 하였습니다.
- 그러면서 사용자가 설정하는 지역에 따라 다르게 포맷을 주어야 했어서 TimeInterval을 확장하였고, 아래와 같은 formattedDate라는 연산 프로퍼티를 만들게 되었습니다.

```swift
extension TimeInterval {
    var formattedDate: String {
        let dateFormatter = DateFormatter()
        let localID = Locale.preferredLanguages.first
        let deviceLocale = Locale(identifier: localID ?? "ko-kr").languageCode
        dateFormatter.dateStyle = .long
        dateFormatter.locale = Locale(identifier: deviceLocale ?? "ko-kr")
        dateFormatter.timeZone = TimeZone.current
        return dateFormatter.string(from: Date(timeIntervalSince1970: self))
    }
}
```

<br>

### 2. 캡슐화를 준수하기 위해 고민하였습니다.

![](https://i.imgur.com/FpnakIj.png)

![](https://i.imgur.com/qSHhmED.png)

![](https://i.imgur.com/T5HPVXU.png)

- 캡슐화를 하기 위해서, `private`을 모두 사용해주려고 하였으나, ViewController에서 Keyboard의 높이를 조정할 때 `mainScrollView`와 `descriptionView`를 사용해야했습니다. 이러한 경우에는 캡슐화를 어떻게 해주는 게 좋을까요? 
>`KeyboardLayoutGuide`를 사용해면 해결되겠지만, iOS 15이상이라서 지양했습니다!

2022-06-19 16:14 UTC, TTOzzi requested changes
안녕하세요~ 도니, 원툴!
코드 확인하고 PR에 남겨주신 질문 포함해서 코멘트로 남겨뒀습니다.
혹시나 제가 놓친 부분이 있거나, 이해하기 어려운 내용이 있다면 말씀해주세요!
고생하셨습니다 🙇

2022-06-19 16:14 UTC, TTOzzi commented on Diary/ViewController/MainViewController.swift
> +        cell.descriptionLabel.text = diaryData[indexPath.row].body
캡슐화의 관점에서 이 로직도 셀 내부 메서드로 만들어주면 더 좋을 것 같습니다.
셀에서 프로퍼티를 꺼내 값을 설정해주는 게 아닌, 값은 넘겨주기만 하고 설정은 셀 내부에서 하도록요.

2022-06-19 16:14 UTC, TTOzzi commented on Diary/ViewController/MainViewController.swift
> +        let detailViewController = DetailViewController(diaryData: diaryData[indexPath.row])
현재 로직에선 엣지 케이스이긴 한데, 배열의 `index`로 데이터에 접근할 땐 항상 배열의 `index`범위를 벗어나서 크래시가 발생할 가능성이 있습니다.
`diaryData` 업데이트 -> `collectionView` 리로드의 흐름이 동기적으로 동작함이 항상 보장되지 않는다면요.

2022-06-19 16:14 UTC, TTOzzi commented on Diary/ViewController/DetailViewController.swift
> +        }
> 캡슐화를 하기 위해서, private을 모두 사용해주려고 하였으나, ViewController에서 Keyboard의 높이를 조정할 때 mainScrollView와 descriptionView를 사용해야했습니다. 이러한 경우에는 캡슐화를 어떻게 해주는 게 좋을까요?

`mainScrollView`와 `descriptionView`를 `private`으로 숨기고 외부에서 필요로 하는 값만 반환하는 `getter`와 값 설정 로직을 대체할 메서드를 구현해주면 될 것 같습니다.

```swift
self.detailView.mainScrollView.contentSize = .init(width: self.detailView.mainScrollView.frame.width, height: self.detailView.mainScrollView.frame.height + keyboardSize.height - 140)
```
작성하신 이 로직은 사용하고 있는 값 `detailView.mainScrollView.frame`이 `detailView` 내부에서 알고 있는 값이라, `keyboardSize.height` 를 넘겨주는 메서드를 만들어 줄 수 있겠네요.

아래의 로직
```swift
if self.detailView.descriptionView.isFirstResponder {
    detailView.mainScrollView.scrollRectToVisible(detailView.descriptionView.frame, animated: true)
}
```
도 사실상 외부 값이 필요없으니 통채로 `detailView` 내부에 넣어줄 수 있을 것 같구요 🤔

2022-06-20 08:48 UTC, kimt4580 commented on Diary/AppDelegate.swift
> +        UINavigationBar.appearance().scrollEdgeAppearance = appearance
넵 메서드 분리를 통하여, 기능 분리 해주었습니다!

2022-06-20 09:00 UTC, kimt4580 commented on Diary/Extension/TimeInterval+extension.swift
> +        dateFormatter.locale = Locale(identifier: deviceLocale ?? "ko-kr")
현재 `deviceLocale`이 `String`을 지원하지 않고, `Locale` 타입 `String`이 필요한데, Suggestion 해주신 방향으로 수정하려고 하였는데 오류가 납니다. 바로 할당이 불가능한 것 같아서요 다른 방법이 있을까요?

2022-06-20 09:02 UTC, kimt4580 commented on Diary/View/Cell/CellMakeable.swift
> +protocol CellMakeable {
프로토콜로 구현해서, 중복되는 코드를 줄이려고 했습니다. 같은 코드의 반복으로 코드가 길어지는 것이 컨벤션적으로 복잡하게 보일 수 있다는 생각이 들었습니다. 프로토콜 없이 코드를 작성하는 방향이 더 나을까요?

2022-06-20 09:10 UTC, kimt4580 commented on Diary/View/Cell/CellMakeable.swift
> +protocol CellMakeable {
현재 프로토콜을 삭제하는 방향으로 수정해주었습니다.

2022-06-20 09:35 UTC, kimt4580 commented on Diary/View/DetailView.swift
> +    private lazy var mainStackView: UIStackView = {
closure 형태라서 mainStackView에 모든 게 add 된 후에 적용되도록 하고 싶어서 lazy var를 사용해주었습니다.

2022-06-20 10:58 UTC, westeastyear commented on Diary/View/DetailView.swift
> +            mainScrollView.centerYAnchor.constraint(equalTo: self.centerYAnchor)
제거해주었습니다!

2022-06-20 10:58 UTC, westeastyear commented on Diary/ViewController/DetailViewController.swift
> +    private var diaryData: DiaryModel
`let` 으로 수정하였습니다

2022-06-20 11:00 UTC, westeastyear commented on Diary/ViewController/MainViewController.swift
> +        cell.descriptionLabel.text = diaryData[indexPath.row].body
updateLabels() 메서드를 만들어 수정하였습니다

2022-06-20 12:18 UTC, TTOzzi commented on Diary/Extension/TimeInterval+extension.swift
> +        dateFormatter.locale = Locale(identifier: deviceLocale ?? "ko-kr")
아! IDE 안쓰고 여기다 바로 코드를 적다보니 실수했네용
```suggestion
        let deviceLocale = Locale(identifier: localID ?? "ko-kr")
        dateFormatter.dateStyle = .long
        dateFormatter.locale = deviceLocale
```
요런 형태를 말씀드리고 싶었습니다!

2022-06-20 12:22 UTC, TTOzzi commented on Diary/View/Cell/CellMakeable.swift
> +protocol CellMakeable {
음 구현하신 코드에선 `CellMakeable`를 만들어 얻는 이점보다, 코멘트로 남겨놓은 몇몇 부분에서 `CellMakeable`로 인해 좋지 않은 구조로 코드가 짜여지는 것이 더 커 보였었어요 🤔

2022-06-20 13:59 UTC, westeastyear commented on Diary/View/MainView.swift
> +}
`MainView` 파일 제거해주었습니다!

2022-06-20 14:05 UTC, kimt4580 commented on Diary/ViewController/DetailViewController.swift
> +        view = detailView
![image](https://user-images.githubusercontent.com/67851501/174619371-05451669-1839-460c-ab6f-c3cd7f70a9cb.png)
view를 먼저 호출 한 후에, viewDidLoad가 호출되므로, viewDidLoad 호출 전 view를 호출하도록 변경해주었습니다.

2022-06-20 14:17 UTC, kimt4580 commented on Diary/ViewController/DetailViewController.swift
> +    }
넵 키보드 `keyboardWillHide`에서 Observer를 제거해주고 `viewDidLoad`에서 NotificationCenter를 등록해주도록 변경해주었습니다.

2022-06-20 14:17 UTC, kimt4580 commented on Diary/ViewController/DetailViewController.swift
> +    @objc func keyboardWillShow(notification: NSNotification) {
private으로 숨겨주었습니다!

2022-06-20 14:30 UTC, kimt4580 commented on Diary/Extension/TimeInterval+extension.swift
> +        dateFormatter.locale = Locale(identifier: deviceLocale ?? "ko-kr")
해당 사항 수정해서 적용해주었습니다!

2022-06-21 03:13 UTC, kimt4580 commented on Diary/ViewController/MainViewController.swift
> +        let detailViewController = DetailViewController(diaryData: diaryData[indexPath.row])
subscript를 사용하여 safety 하도록 변경하였습니다!

2022-06-21 03:13 UTC, kimt4580 commented on Diary/ViewController/DetailViewController.swift
> +            self.detailView.mainScrollView.contentSize = .init(width: self.detailView.mainScrollView.frame.width, height: self.detailView.mainScrollView.frame.height + keyboardSize.height - 140)
contentInset에 따라서, keyboard 높이를 조정하도록 수정하였습니다.

2022-06-21 03:15 UTC, kimt4580 commented on Diary/ViewController/DetailViewController.swift
> +        }
contentInset을 사용하였더니, 값을 받을 필요가 없어졌네요!

2022-06-21 13:19 UTC, TTOzzi approved these changes
고생하셨습니다!
추가로 남겨드린 코멘트는 수정이 필요한 부분이 있다면 다음 스텝 진행하시면서 챙겨보면 될 것 같습니다 🙇

2022-06-21 13:19 UTC, TTOzzi commented on Diary/Model/Parser.swift
> +    func parse() throws -> [DiaryModel] {
무엇을 파싱하는지 명확하게 정해져있으니 객체와 메서드의 이름도 좀 더 명확하게 바꾸면 좋을 것 같아요.
아니면 이름은 그대로 유지하고, 파일명과 디코드할 타입을 인자로 받아 좀 더 제너럴한 유틸 객체로 만들어줘도 될 것 같구요.

2022-06-21 13:19 UTC, TTOzzi commented on Diary/ViewController/DetailViewController.swift
> +        view = detailView
https://developer.apple.com/documentation/uikit/uiviewcontroller/1621454-loadview
요 문서 한 번 읽어보시면 좋을 것 같아요!
뷰컨의 루트뷰를 변경할 땐 `loadView` 시점에 변경해주라고 설명하고 있습니다.

2022-06-21 13:19 UTC, TTOzzi commented on Diary/ViewController/DetailViewController.swift
> +        )
`.zero` 로도 표현할 수 있을 것 같아요.

2022-06-21 13:19 UTC, TTOzzi commented on Diary/ViewController/RegisterViewController.swift
> +        self.view = view
흠 요건 어떤 의미를 가지는 코드인가요? 👀 
`self.view`와 `view`는 같은데 자기 자신에게 자신을 할당하네요 🤔

2022-06-21 13:19 UTC, TTOzzi commented on Diary/ViewController/MainViewController.swift
> +        }
에러 핸들링은 `errorDescription`을 지정해주셨으니 각각 에러를 구분해 다른 메세지를 하드코딩하기 보단 `localizedDescription`을 활용하면 좋을 것 같아요.
추가로 `print` 는 앱 실행 중 유저에게 문제가 생겼음을 인지시켜 줄 수 없으니, 알러트를 띄우거나 에러 화면을 보여주는 등의 처리가 더 좋습니다.
요건 구현 다 하시고 여유되시면 챙겨보아요!

2022-06-21 13:20 UTC, merged

2022-06-21 15:11 UTC, kimt4580 commented on Diary/Model/Parser.swift
> +    func parse() throws -> [DiaryModel] {
제네럴한 유틸 객체로 수정해주었습니다!

2022-06-21 15:11 UTC, kimt4580 commented on Diary/ViewController/RegisterViewController.swift
> +        self.view = view
필요 없는 코드여서 제거해주었습니다!

2022-06-21 15:12 UTC, kimt4580 commented on Diary/ViewController/MainViewController.swift
> +        }
errorDescription으로 처리하도록 변경해주었습니다.