일기장 [STEP 2] 혜모리, kokkilE
yagom-academy/ios-diary pull request #100
Opened 2023-05-03 09:39 UTC by hyemory

@1Consumption
안녕하세요 올라프! 코낄이, 혜모리입니다. 🙇🏻‍♂️🙇🏻‍♀️
코어 데이터를 이용하여 사용자의 데이터를 다루는 것이 처음이라 많이 어려웠습니다.
예외 처리를 위해 많은 고민을 하였습니다. 
이번 리뷰도 잘 부탁드리겠습니다. :smile: 

## 고민했던 점

### 1️⃣ core data 주요 프로퍼티, 메서드

- `var persistentContainer` : 데이터가 저장될 컨테이너로 core data가 필요하지 않을 경우 로드할 필요가 없으므로 lazy var로 선언해 주었습니다.
- `var context` : view context 프로퍼티입니다.
- `func create(contents: Contents)` : 데이터를 생성해주는 메서드입니다. 모델 타입 identifier(UUID) 값은 DiaryDetailViewController에서 createContents() 호출 시 생성해 줍니다.
- `func read() -> [Contents]?` : 모든 코어 데이터를 읽는 메서드입니다. DiaryListViewController viewDidLoad 시 모든 데이터를 패치해 주기 위해 구현했습니다.
- `func update(contents: Contents)` : 코어데이터의 일기장 글 내용을 수정해주는 메서드입니다.
- `func delete(identifier: UUID)` : 코어데이터의 일기장 글을 삭제해주는 메서드입니다.
- `func searchContents(identifier: UUID) -> [ContentsEntity]` : 데이터 수정, 삭제를 위해 UUID로 해당 데이터를 찾을 수 있는 메서드를 구현하였습니다.

### 2️⃣ 예외 처리 및 협의한 내용

스텝 요구사항 외 처리가 필요하다고 생각하는 정책을 팀원 간 협의하여 구현한 내용입니다.

1. 새 글을 create할 때 아무 내용도 입력하지 않은 경우
 → 저장되지 않습니다.
3. 새 글을 create하고 + 자동 저장된 후 글 내용을 전부 삭제한 경우
 → 비어있는 내용이 저장됩니다.
5. 글을 한 줄만 등록한 경우 (title만)
 → title은 입력한 내용이 저장되고 body는 빈 문자열로 저장됩니다.
7. 이미 등록된 글의 내용을 전부 지운 경우 update 여부
 → 비어있는 내용이 저장됩니다.
9. 새 글을 create할 때 더보기 버튼(right bar button) 노출 여부
 → 입력 후 내용을 바로 공유하거나, 자동저장된 내용을 바로 삭제시킬 수 있다고 생각하기 때문에 새 글을 저장할 때도 버튼이 노출됩니다.

### 3️⃣ delegate로 table view load
일기장 화면(`DiaryDetailViewController`)에서 변경한 내용이 리스트 화면(`DiaryListViewController`)에도 반영될 수 있도록 두 가지 방법을 고려하였습니다.

1. 일기장 화면에서 변경된 데이터를 CoreData에만 반영하고, 리스트 화면에서 viewWillAppear 메서드에서 `CoreDataManager.read()`와 `TableView.reloadData` 실행
이 방법은 구현이 간단하지만, 하나의 데이터만 변경되어도 전체 데이터를 fetch한 후 reload를 하는데 오버헤드가 발생하게 됩니다.
2. 일기장 화면에서 변경된 데이터를 delegate를 통해 리스트 화면에 반영
delegate를 통해 변경된 셀의 데이터만 reload하기 때문에 성능상의 이점이 있다고 판단하고 이 방법을 적용하였습니다.

### 4️⃣ Alert으로 에러 처리 (rootVC 관련)
에러가 발생했을 때 사용자에게 Alert을 표시하도록 구현하였습니다. 이 기능은 `AlertManager`가 수행하는데, Alert을 `present`할 주체에 대해 고민하였습니다.

초기에는 VC에서만 Alert이 발생한다고 생각해서 다음과 같이 `target`을 파라미터로 받도록 구현하였습니다.

**수정 전: VC에서만 showErrorAlert 호출**
``` swift
struct AlertManager {
    func showErrorAlert(target: UIViewController, error: Error) {
        let alert = UIAlertController(...)
        ...
        target.present(alert, animated: true)
    }
    ...
}
```
하지만 `CoreDataManager`에서 에러가 발생할 경우 VC에 대한 정보를 모르는 채로 Alert을 표시할 필요가 있었습니다. 따라서 VC의 정보를 파라미터로 넘겨받지 않고도 Alert을 표시할 수 있도록 다음과 같이 수정하였습니다.

**수정 후: VC가 아닌 모델에서도 showErrorAlert 호출**
``` swift
struct AlertManager {
    func showErrorAlert(error: Error) {
        guard let windowScene = UIApplication.shared.connectedScenes.first as? UIWindowScene,
              let target = windowScene.windows.first?.rootViewController else { return }
        
        let alert = UIAlertController(...)
        ...
        target.present(alert, animated: true)
    }
    ...
}
```
위 코드는 현재 VC가 몇개가 생성되어있든, Root VC에서 present 합니다.
<img src="https://i.imgur.com/8vywbGL.png" width=250>

동작에는 문제가 없는것을 확인했지만, 흐름상 `VC 2`가 존재하는 상황이라면 `VC 2`에서 Alert을 `present` 하는것이 더 자연스럽게 느껴지기도 합니다. 저희 코드에서는 `VC 1`에서 Alert을 `present` 하는데, 이 부분에 대해 올라프의 의견을 여쭙고 싶습니다.

2023-05-03 17:50 UTC, 1Consumption requested changes
고생하셨습니다.

고민한 점에 적어주신대로 alert error처리가 조금 이상하네요.
`CoreDataManager`는 로직을 처리하는 곳인데, 여기에서 임의로 view를 띄우는게 이상하다고 생각합니다. 코멘트에도 적었는데, 에러를 던지고 받는 곳에서 처리하면 어떨까 싶습니다.

나머지는 코멘트를 참고해주세요.

2023-05-03 17:50 UTC, 1Consumption commented on Diary/Controller/DiaryDetailViewController.swift
> +
이런 변경사항은 불필요해보여요.

2023-05-03 17:50 UTC, 1Consumption commented on Diary/Controller/DiaryDetailViewController.swift
> +        AlertManager().showErrorAlert(error: DiaryError.initFailed)
지금의 방식과 `showErrorAlert(error:)` 메소드를 static으로 선언하는 방식은 어떤 차이가 있을까요?

2023-05-03 17:50 UTC, 1Consumption commented on Diary/Controller/DiaryDetailViewController.swift
> +    }
super가 누락되었네요~

2023-05-03 17:50 UTC, 1Consumption commented on Diary/Controller/DiaryDetailViewController.swift
> +    private var contents: Contents?
그런데 왜 `contents`가 옵셔널인가요? 상세화면이라면 무조건 `contents`가 있어야할 것 같은데요.

2023-05-03 17:50 UTC, 1Consumption commented on Diary/Controller/DiaryDetailViewController.swift
> +        self.present(alert, animated: true)
여기만 self를 붙인 이유가 있을까요?

2023-05-03 17:50 UTC, 1Consumption commented on Diary/Controller/DiaryDetailViewController.swift
>          }
부등호로 비교하는건 어떨까요? 이러니까 잘 안 읽히는 것 같아요. 어떻게 생각하시나요?

2023-05-03 17:50 UTC, 1Consumption commented on Diary/Controller/DiaryDetailViewController.swift
> +            body = splitedText[1].description
description 프로퍼티를 직접 호출하는 것은 권장되지 않는다고 공식문서에 적혀있습니다. 공식문서를 한번 확인하시면 좋을 것 같아요.

2023-05-03 17:50 UTC, 1Consumption commented on Diary/Controller/DiaryListViewController.swift
> +        let share = UIContextualAction(style: .normal, title: "Share") { _, _, _ in
여기는 [weak self]가 빠져있네요.

2023-05-03 17:50 UTC, 1Consumption commented on Diary/CoreData/ContentsEntity+CoreDataClass.swift
> +public class ContentsEntity: NSManagedObject { }
public은 빼도 좋을 것 같아요. 자동 생성 해주는 파일이라도 한번 더 보면 좋겠습니다.

2023-05-03 17:50 UTC, 1Consumption commented on Diary/CoreData/CoreDataManager.swift
> +    private lazy var context: NSManagedObjectContext = persistentContainer.viewContext
연산 프로퍼티로 제공해도 좋을 것 같아요.

2023-05-03 17:50 UTC, 1Consumption commented on Diary/CoreData/CoreDataManager.swift
> +import UIKit
UIKit을 알아야할까요?

2023-05-03 17:50 UTC, 1Consumption commented on Diary/CoreData/CoreDataManager.swift
> +              let storage = NSManagedObject(entity: entity, insertInto: context) as? ContentsEntity else { return }
```suggestion
        let storage = ContentsEntity(context: context)
```

이렇게 바꿀수도 있을 것 같아요.

2023-05-03 17:50 UTC, 1Consumption commented on Diary/CoreData/CoreDataManager.swift
> +    }
여기서 alert를 직접 띄우지말고 에러를 던지기만 하는건 어떨까요? 에러를 받은 곳에서 알러트를 띄우는거죠. 다른 곳도 마찬가지입니다.

2023-05-03 17:50 UTC, 1Consumption commented on Diary/CoreData/CoreDataManager.swift
> +                try context.save()
이 작업은 왜 필요한걸까요?

2023-05-03 17:50 UTC, 1Consumption commented on Diary/CoreData/CoreDataManager.swift
> +    private lazy var context: NSManagedObjectContext = persistentContainer.viewContext
viewContext는 어떤 역할을 하나요?

2023-05-04 07:30 UTC, hyemory commented on Diary/Controller/DiaryDetailViewController.swift
> +    }
추가하였습니다!

``` swift
override func touchesEnded(_ touches: Set<UITouch>, with event: UIEvent?) {
    super.touchesEnded(touches, with: event)
    
    textView.resignFirstResponder()
}
```

2023-05-04 07:31 UTC, hyemory commented on Diary/Controller/DiaryDetailViewController.swift
> +        self.present(alert, animated: true)
통일성을 위해 해당 부분의 self.도 삭제해 주었습니다 ☺️

2023-05-04 07:33 UTC, hyemory commented on Diary/Controller/DiaryDetailViewController.swift
> +            body = splitedText[1].description
말씀해 주신대로 [description](https://developer.apple.com/documentation/swift/customstringconvertible/description) 공식문서를 확인해보니 권장하지 않는다는 사실을 새롭게 알게 되었습니다. 🙇🏻‍♀️
`String(describing:)`을 사용하여 변경하였습니다~

2023-05-04 07:33 UTC, hyemory commented on Diary/CoreData/ContentsEntity+CoreDataClass.swift
> +public class ContentsEntity: NSManagedObject { }
알겠습니다! public은 불필요하여 제거하였고, final을 추가하였습니다.

2023-05-04 07:34 UTC, hyemory commented on Diary/CoreData/CoreDataManager.swift
> +import UIKit
제거했습니다 👍

2023-05-04 07:35 UTC, kokkilE commented on Diary/Controller/DiaryDetailViewController.swift
> +        AlertManager().showErrorAlert(error: DiaryError.initFailed)
static으로 선언해서 타입 메서드로 구현하면 인스턴스를 생성하지 않고 호출할 수 있다는 장점은 있지만, 앱 실행 중 항상 메모리에 할당된다는 점이 단점으로 생각되었습니다.

`showErrorAlert(error:)`이 호출되는 빈도가 잦지 않다고 생각해서, 메모리에 상주하도록 타입 메서드로 구현하기보다는 필요할 때 인스턴스를 생성하고 호출하는 방식을 선택하였습니다.

2023-05-04 07:36 UTC, hyemory commented on Diary/CoreData/CoreDataManager.swift
> +    }
말씀해 주신대로 `CoreDataManager`에서 alert을 띄우는 것이 어색하다고 판단되어 
에러를 던지기만 하는 것으로 수정했습니다!

2023-05-04 07:39 UTC, kokkilE commented on Diary/Controller/DiaryDetailViewController.swift
> +    private var contents: Contents?
상세화면은 이미 존재하는 일기를 클릭한 경우와 새로 일기를 작성하는 경우 모두 사용되기 때문에 `contents`를 옵셔널로 정의하였습니다.
새로 일기를 작성하는 경우에도 텍스트 프로퍼티가 비어있는 `contents`를 생성하면 `contents`를 옵셔널로 하지 않을수도 있지만, 저희는 옵셔널인 `contents`의 nil 여부로 CoreData 내에 Create할지, Update할지 결정하는 로직으로 구현하였습니다!

``` swift
extension DiaryDetailViewController {
    @objc private func saveContents() {
        guard contents != nil else {
            createContents()
            return
        }
        
        updateContents()
    }
    ...
}
```

2023-05-04 07:42 UTC, kokkilE commented on Diary/Controller/DiaryDetailViewController.swift
>          }
switch 구문의 `default`가 `splitedText.count == 2`인 case를 나타낸다는것이 직관적으로 읽히지 않는 것 같습니다. 😄

다음과 같이 if문을 통해 등호로 비교하도록 수정해보았습니다.

``` swift
        if splitedText.count == 1 {
            title = String(describing: splitedText[0])
        } else if splitedText.count == 2 {
            title = String(describing: splitedText[0])
            body = String(describing: splitedText[1])
        }
```

2023-05-04 07:43 UTC, kokkilE commented on Diary/Controller/DiaryListViewController.swift
> +        let share = UIContextualAction(style: .normal, title: "Share") { _, _, _ in
`[weak self]` 누락 수정하였습니다!

2023-05-04 07:55 UTC, kokkilE commented on Diary/CoreData/CoreDataManager.swift
> +    private lazy var context: NSManagedObjectContext = persistentContainer.viewContext
연산 프로퍼티로 수정하였습니다.
``` swift
private var context: NSManagedObjectContext { persistentContainer.viewContext }
```

그런데 위의 의견을 주신 이유가 궁금합니다! 😃 저희가 이해하기로 두 방법의 차이는 다음과 같았습니다.
- 지연 저장 프로퍼티로 제공할 경우 `context`가 처음 사용된 때부터 메모리에 할당됩니다.
- 연산 프로퍼티로 제공할 경우 `context`가 메모리를 차지하지 않고, 사용될 때 마다 `persistentContainer.viewContext`에 접근해서 가져옵니다.

`context`는 `CoreDataManager` 내에서 빈번하게 사용되기 때문에 연산 프로퍼티로 구현하면 가져올 때 마다 추가적인 작업이 필요할 것이라고 생각했습니다.
물론 연산 프로퍼티로 구현해서 필요한 추가적인 작업이나, 저장 프로퍼티로 구현해서 메모리를 차지하는것은 모두 무시할 수 있을 수준일거라 생각되긴 하지만, 그렇다면 지연 프로퍼티와 연산 프로퍼티 선택 기준을 어떻게 생각하면 좋을지 의견을 여쭤보고 싶습니다. 🙇

2023-05-04 07:59 UTC, kokkilE commented on Diary/CoreData/CoreDataManager.swift
> +              let storage = NSManagedObject(entity: entity, insertInto: context) as? ContentsEntity else { return }
`ContentsEntity`이 저런 생성자를 제공하는것을 몰랐습니다. 😢
`NSManagedObject`에 [init(entity:insertInto:)](https://developer.apple.com/documentation/coredata/nsmanagedobject/1506357-init) 생성자가 구현되어 있네요. 🙇
수정하였습니다!

2023-05-04 07:59 UTC, hyemory commented on Diary/CoreData/CoreDataManager.swift
> +    private lazy var context: NSManagedObjectContext = persistentContainer.viewContext
viewContext는 core data에서 persistent store에 저장해주기 전까지 변경된 managed object의 데이터를 가지고 있는 영역입니다.
또한 viewContext를 사용하여 persistent store 데이터를 추가, 수정, 삭제해 줄 수 있습니다.

2023-05-04 08:02 UTC, kokkilE commented on Diary/CoreData/CoreDataManager.swift
> +                try context.save()
`context.hasChanges`를 통해 변경사항이 있는지 확인한 후 save하는 로직이라고 생각했습니다.

하지만 확인해보니 저희 코드에서 항상 `context`가 변경된 후 `saveContext`가 호출되기 때문에 무의미한 조건 검사라는걸 알게 되었습니다.

따라서 해당 메서드는 삭제하였습니다. 🙇

2023-05-07 17:41 UTC, 1Consumption commented on Diary/CoreData/CoreDataManager.swift
> +    private lazy var context: NSManagedObjectContext = persistentContainer.viewContext
저는 최대한 lazy를 지양합니다. 쓰레드세이프하지 못하기 때문입니다.(하지만 지금은 레퍼런스만 가지고 있으니까 문제가 되지는 않을듯 합니다)

또한 굳이..? 라는 생각이 있어서요. 지금은 위에 말한대로 레퍼런스만 전달하기 때문에 연산프로퍼티로 해도 좋겠다는 생각을 했습니다.

아래 링크를 읽어보시면 좋을듯 합니다.
https://docs.swift.org/swift-book/documentation/the-swift-programming-language/properties/#Lazy-Stored-Properties

2023-05-07 17:45 UTC, 1Consumption approved these changes
고생하셨습니다. 그런데 공유 기능이 빠졌네요. 다음 스텝에서 구현해주세요.

2023-05-07 17:46 UTC, merged