일기장 [STEP 2] Rhode, 무리
yagom-academy/ios-diary pull request #101
Opened 2023-05-04 07:14 UTC by Rhode-park

@forestjae
숲재 안녕하세요~ STEP2 PR 보냅니다.
코어데이터를 처음 써보니... 생각보다 많이 어렵네요🥲...!
그럼 리뷰 기다리고있겠습니다~!

## 고민했던 점
### 1️⃣ Core Data Update&Delete 구현하기
처음에는 Core Data Entity와 Diary 타입을 구성하는데에 있어서 id를 넣지 않았습니다. read를 하는데에 있어서는 다음과 같이 전체의 diary를 read하고 tableView에서 index에 맞춰 넘겨주기 때문에 문제가 없었습니다: 
```swift
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) ->
UITableViewCell {
    guard let cell = tableView.dequeueReusableCell(withIdentifier:
DiaryListCell.identifier) as? DiaryListCell else {
        return DiaryListCell()
    }
    
    cell.accessoryType = .disclosureIndicator
    
    guard let diaries = coreDataManager.readDiary() else { return
DiaryListCell() }
    
    cell.configureContent(data: diaries[indexPath.row])
    
    return cell
}
```

비슷하게 update와 delete에 관한 메서드 역시 index를 통해 업데이트하고 있었습니다. 그러나, detailDiaryView쪽에서 다이어리를 update하고 delete하려니, 각각의 Diary와 Entity를 식별해야할 필요가 있었습니다. 모든 상황에서 diaryListView에서 detailDiaryView쪽으로 넘어가는게 아니고, 그렇기때문에 항상 index를 넘겨받을 수 있는 것은 아니기 때문입니다.

그래서 UUID 타입의 id 프로퍼티를 만들었습니다. 그리고 update와 delete관련 메서드 역시 index를 넘겨받는게 아닌 Diary를 넘겨 받는 로직으로 변경하였습니다. 그리고 id를 통해서 업데이트할 혹은 지울 다이어리를 식별하도록 하였습니다:

```swift
func updateDiary(diary: Diary) {
    let fetchRequest = NSFetchRequest<NSManagedObject>(entityName: "Entity")
    fetchRequest.predicate = NSPredicate(format: "id == %@", diary.id as
CVarArg)
    
    do {
        let objects = try context.fetch(fetchRequest)
        let objectToUpdate = objects[0]
        
        objectToUpdate.setValue(diary.title, forKey: "title")
        objectToUpdate.setValue(diary.body, forKey: "body")
        objectToUpdate.setValue(diary.date, forKey: "date")
        
        do {
            try self.context.save()
        } catch {
            print(error.localizedDescription)
        }
    } catch {
        print(error.localizedDescription)
    }
}
func deleteDiary(diary: Diary) {
    let fetchRequest = NSFetchRequest<NSManagedObject>(entityName: "Entity")
    fetchRequest.predicate = NSPredicate(format: "id == %@", diary.id as
CVarArg)
    
    do {
        let objects = try context.fetch(fetchRequest)
        let objectToDelete = objects[0]
        context.delete(objectToDelete)
        
        do {
            try context.save()
        } catch {
            print(error.localizedDescription)
        }
    } catch {
        print(error.localizedDescription)
    }
}
```

### 2️⃣ initializer이용하여 생성/수정 식별하기
앞의 `ListDiaryView`에서 진입점에 따라 데이터를 생성하는지, 수정하는지 식별할 필요가 있었습니다.
- `addDiary()` : 데이터를 생성
- `tableView(_:didselectRowAt:)` : 데이터를 수정

이를 해결하기 위해 `DiaryListViewController`에서 `initializer`를 만들어 상황마다 다른 값을 주입받도록했습니다. 그 후에 `DetailDiaryListView`의 `isCreateDiary`라는 Bool타입 프로퍼티를 이용하여 생성한 것인지 확인하였습니다.

```swift 
// DiaryListViewController.swift
    // ...
    @objc
    private func addDiary() {
        let detailDiaryViewController = DetailDiaryViewController(isCreateDiary: true,
                                                                  isSaveRequired: true)
        navigationController?.pushViewController(detailDiaryViewController, animated: true)
    }
    // ...
    
extension DiaryListViewController: UITableViewDataSource {     
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
         // ...
        let detailDiaryViewController = DetailDiaryViewController(isCreateDiary: false,
                                                                  isSaveRequired: true)
        navigationController?.pushViewController(detailDiaryViewController, animated: true)
        // ...
    }
    
    // ...
}
```

### 3️⃣ 중복 저장 막기 & 백그라운드 진입 시 저장
현재 저장이 되어야 하는 상황은 세 가지 입니다.
>1. 뒤로가기를 터치하여 리스트 뷰로 돌아갈 때
>2. 사용자가 입력을 멈추고 키보드를 내릴 때
>3. 앱이 백그라운드로 진입 할 때

위와 같은 상황에서 입력을 멈추고 키보드를 내린 후, 뒤로가기를 터치하면 중복으로 저장되는 이슈가 생겨 해당 문제를 해결하기 위해 `isSaveRequired`라는 bool타입의 property를 추가하였습니다.
```swift 
// DetailDiaryViewController.swift

    private var isSaveRequired: Bool = true

    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        // 뒤로가기에서 저장하기 위한 부분
        saveDiary()
    }

    // MARK: - CoreData method
    private func saveDiary() {
        if isSaveRequired {
            if isCreateDiary {
                createDiary()
            } else {
                updateDiary()
            }
            
            isSaveRequired = false
        }
    }

    // MARK: - Notification method
    @objc
    private func enterTaskSwitcher() {
        // 백그라운드로 진입 시 저장하기 위한 부분
        saveDiary()
    }

extension DetailDiaryViewController: UITextViewDelegate {
    func textViewDidEndEditing(_ textView: UITextView) {
        // 사용자가 입력을 멈출 때 저장하기 위한 부분
        saveDiary()
    }
}
```
요구사항에는 `백그라운드`에 진입이라고 해두었지만, 앱 스위쳐 화면에서 앱을 종료하게 되면 작성한 내용이 반영이 안되는 것이 아쉬워 Notification 중 `UIScene.willDeactivateNotification`를 이용해 앱 스위쳐 화면에서도 저장이 될 수 있게 해보았습니다. 

### 4️⃣ 키보드를 위한 레이아웃 변경
기존에는 `bottomConstraint`를 따로 만들어줘 키보드가 textView를 가리지 않도록 해주었습니다. 그런데, 키보드가 내려가는 상황에서 약간의 공백이 생겼습니다. 그래서 기존의 방식을 버리고 iOS 15.0부터 적용되는 `UIKeyboardLayoutGuide` 프로퍼티를 사용해주었습니다. 이를 위해서 프로젝트의 버전을 15.0으로 변경해주었습니다. 그러자 코드는 한결 간결해져 다음과 같은 코드가 되었습니다:
```swift
private func configureConstraint() {
    NSLayoutConstraint.activate([
        diaryTextView.topAnchor.constraint(equalTo:
view.safeAreaLayoutGuide.topAnchor),
        diaryTextView.leadingAnchor.constraint(equalTo:
view.safeAreaLayoutGuide.leadingAnchor),
        diaryTextView.trailingAnchor.constraint(equalTo:
view.safeAreaLayoutGuide.trailingAnchor),
        diaryTextView.bottomAnchor.constraint(equalTo:
view.keyboardLayoutGuide.topAnchor)
    ])
}
```

## 조언을 얻고싶은 점
### 1️⃣ `diaries`를 전역으로 갖고 있어야할까요?
현재 두 메서드에서 readDiary를 해주고 있습니다:

```swift
extension DiaryListViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        guard let diaries = coreDataManager.readDiary() else { return 0 }
        
        return diaries.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: DiaryListCell.identifier) as? DiaryListCell else {
            return DiaryListCell()
        }
        
        cell.accessoryType = .disclosureIndicator
        
        guard let diaries = coreDataManager.readDiary() else { return DiaryListCell() }
        
        cell.configureContent(data: diaries[indexPath.row])
        
        return cell
    }
}

```

`tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int`에서 섹션의 개수를 구하기 위하여 한 번, `tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell`에서 실질적인 내용을 가져오기 위하여 또 한 번입니다. diaries를 전역으로 들고 있고 별도의 메서드를 통해 diaries에 내용을 채워준 후에 그것을 사용하는게 좋을까요? 아님 지금처럼 `readDiary()`를 두 번 호출해도 괜찮은 상황인 걸까요? 숲재의 의견이 궁금해서 여쭤보는 바입니다. 

### 2️⃣ 삼항연산자에서 함수의 호출
코드를 작성하다 보니 if문의 중복을 피하지 못하여... 가독성을 챙기고자 삼항연산자를 사용했습니다.
작성을 하고 보니 Lint에서 아래 사진과 같은 경고를 주어 다시 if문의 중복으로 되돌린 상태입니다...!
![](https://i.imgur.com/jHbb8nO.png)
삼항연산자는 if문을 조금 더 간결하게 혹은 가독성이 좋게 사용하는, 결과적으로는 같은 기능을 한다고 생각했는데 오류를 뱉는 이유가 조금 궁금합니다... 

삼항연산자 내에서 Void function의 호출을 지양해야한다는 린트의 경고에 대해 숲재의 의견은 어떠신가요?

### 3️⃣ 액티비티 뷰 컨트롤러를 통해 보는 일기장 내용
액티비티 뷰 컨트롤러를 통해 일기장 내용을 복사하거나 리마인더에 추가할 수 있습니다.
<img src="https://i.imgur.com/zKkPF85.png" width="300">
그런데, 두 가지 경우에서 내용이 달리 표시가 됩니다.

| <center>`Copy` | <center>`Reminders` | 
| -------- | -------- | 
| <img src="https://i.imgur.com/LBpJvrq.png" width="300"> | <img src="https://i.imgur.com/uMt0S1G.png" width="300"> | 
|Copy를 눌러 새 일기장에 붙여넣기 한 경우입니다. <br/> 개행이 사라진 채로 내용이 작성됩니다.|Reminders에 추가하는 경우입니다. <br/> 개행이 유지가 된 채로 내용이 작성됩니다.|

이렇게 두 가지 경우에서 일기장의 내용이 달라집니다. 제목과 내용 사이의 개행이 어느때는 사라지고, 어느 때는 유지가 됩니다. 이 문제를 어떻게 해결하면 좋을까요?

2023-05-05 04:24 UTC, forestjae requested changes

2023-05-05 04:24 UTC, forestjae commented on Diary/Controller/DetailDiaryViewController.swift
> +import CoreData
불필요한 import입니다.

2023-05-05 04:24 UTC, forestjae commented on Diary/Controller/DetailDiaryViewController.swift
> +    private var isCreateDiary: Bool = false
init 이후 시점에서는 변경되지 않는 값이므로, 변수일 필요가 없는 것 같습니다.
영문법상 네이밍도 어색하니 고려해보세요.

2023-05-05 04:24 UTC, forestjae commented on Diary/Controller/DetailDiaryViewController.swift
> +        self.title = diaryDate
특정 부분에만 self를 사용해주신 이유가 있을까요?

2023-05-05 04:24 UTC, forestjae commented on Diary/Controller/DetailDiaryViewController.swift
> +    private func configureDiary() -> Diary? {
configure보다 좋은 네이밍이 있을 것 같아요.

2023-05-05 04:24 UTC, forestjae commented on Diary/Controller/DetailDiaryViewController.swift
> +        let body = checkValidDiary(diaryContents)
뷰컨트롤러가 Diary 객체를 소유하고 있는데 textView에서 값을 추출해오는것은 어색한것 같아요.

Diary객체를 생성하는 코드와 중복 로직이기도 하구요.

2023-05-05 04:24 UTC, forestjae commented on Diary/Controller/DetailDiaryViewController.swift
> +    }
메서드명만 봐서는 Bool타입을 반환할듯 보이는데, String을 반환해서 어색하네요.

2023-05-05 04:24 UTC, forestjae commented on Diary/Controller/DetailDiaryViewController.swift
> +    private func saveDiary() {
이 메서드가 현재 요구사항에 따라서 3군데에서 사용되고 있는데, 작성중에 공유버튼을 눌렀을때는 저장이 되지 않고 있습니다. 생성중에 공유버튼을 눌렀을 때도 마찬가지구요.(Dairy객체 생성 안됨)

2023-05-05 04:24 UTC, forestjae commented on Diary/Controller/DiaryListViewController.swift
> -    private var diary: [Diary]? {
Detail은 Dairy 객체를 들고있고, 여기선 diary 배열 프로퍼티를 삭제하신 이유가 뭔지 궁금합니다.

2023-05-05 04:24 UTC, forestjae commented on Diary/Controller/DiaryListViewController.swift
> +        guard let diaries = coreDataManager.readDiary() else { return 0 }
위에서도 언급해드렸는데, 데이터를 여기서 가져오는 것 보다는 별도의 프로퍼티에서 들고 있는게 맞지 않을까요?

참고로, FetchedResultsController라는 것을 사용하면 코어데이터에 있는 데이터의 변경을 모니터링해서 자동으로 반영하게끔 구현이 가능합니다. 이번 프로젝트에서는 적용하라는 말씀은 아니고 이런게 있다 정도로만 알아두세요.

2023-05-05 04:24 UTC, forestjae commented on Diary/Controller/DiaryListViewController.swift
> +            self.coreDataManager.deleteDiary(diary: diaryToDelete)
여기서 deleteDiary 메서드가 실패하여 코어데이터의 데이터가 삭제되지 않으면 어떤 문제가 생길까요?

에러를 어디서 catch를 해야하는지에 대한 고민이 필요합니다.

2023-05-05 04:24 UTC, forestjae commented on Diary/Extension/Double+.swift
> +              let result = Double(formattedString) else { return nil }
이건 어떤 의미를 가진 로직인가요?

2023-05-05 04:24 UTC, forestjae commented on Diary/Extension/String+.swift
> +}
현재 구현상 필요한 로직인가요?

2023-05-05 04:24 UTC, forestjae commented on Diary/Model/CoreDataManager.swift
> +class CoreDataManager {
이번 프로젝트에서 가장 중요하게 말씀드리고 싶은 부분인데요.

만약 이 프로젝트에서 또 다른 정보를 코어데이터에 저장해야되는 상황이 생긴다면 어떨까요? CoreDataManager라는 이름은 general한 코어데이터 인터페이스 객체를 암시하는 것 처럼 보이는데, 현재 이 객체는 Diary타입에 한정해서 사용할 수 있네요. 이름만 바꾸고 새로운 매니저를 만든다고 하면 불필요하게 동일한 로직이 많이 발생합니다.

이를 어떻게 범용성 있는 객체로 바꿀 수 있을까요? Generic을 활용해서 general한 코어데이터 매니저를 만들고, Diary에 한정해서 쓸 수 있는 별도의 객체가 있으면 좋겠네요.

이번 프로젝트 기간내에 못하더라도 꼭 개인적으로나 다음 프로젝트에 적용해보시기 바랍니다. 코어데이터에 한정되는게 아닌 데이터 소스를 활용하는 모든 기능들에 공통되는 사항입니다.

2023-05-05 04:24 UTC, forestjae commented on Diary/Model/CoreDataManager.swift
> +        return persistentContainer.viewContext
viewContext와 newBackgroundContext()의 차이에 대해서 공부해보셨나요?

2023-05-05 04:24 UTC, forestjae commented on Diary/Model/CoreDataManager.swift
> +            let objectToUpdate = objects[0]
밑에 다른 메서드도 마찬가지인데, 꼭 fetch를 해야하는 상황인가요?

2023-05-05 04:37 UTC, forestjae commented
> ## 조언을 얻고싶은 점
> ### 1️⃣ `diaries`를 전역으로 갖고 있어야할까요?
> 현재 두 메서드에서 readDiary를 해주고 있습니다:
> 
> ```swift
> extension DiaryListViewController: UITableViewDataSource {
>     func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
>         guard let diaries = coreDataManager.readDiary() else { return 0 }
>         
>         return diaries.count
>     }
>     
>     func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
>         guard let cell = tableView.dequeueReusableCell(withIdentifier: DiaryListCell.identifier) as? DiaryListCell else {
>             return DiaryListCell()
>         }
>         
>         cell.accessoryType = .disclosureIndicator
>         
>         guard let diaries = coreDataManager.readDiary() else { return DiaryListCell() }
>         
>         cell.configureContent(data: diaries[indexPath.row])
>         
>         return cell
>     }
> }
> ```
> 
> `tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int`에서 섹션의 개수를 구하기 위하여 한 번, `tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell`에서 실질적인 내용을 가져오기 위하여 또 한 번입니다. diaries를 전역으로 들고 있고 별도의 메서드를 통해 diaries에 내용을 채워준 후에 그것을 사용하는게 좋을까요? 아님 지금처럼 `readDiary()`를 두 번 호출해도 괜찮은 상황인 걸까요? 숲재의 의견이 궁금해서 여쭤보는 바입니다.

두번 호출하는 방법은 좋지 않은 방법인 것 같습니다. 코멘트에 남겨두었듯이 tableViewDelegate 메서드에서 데이터를 가져오는 것도 좋지 않아보여요. 최초 진입시에 fetch해서 변수에 저장해놓고, 별도로 fetch가 필요한 시점마다 해주는게 좋은 방법인 것 같네요.

> 
> ### 2️⃣ 삼항연산자에서 함수의 호출
> 코드를 작성하다 보니 if문의 중복을 피하지 못하여... 가독성을 챙기고자 삼항연산자를 사용했습니다. 작성을 하고 보니 Lint에서 아래 사진과 같은 경고를 주어 다시 if문의 중복으로 되돌린 상태입니다...! ![](https://camo.githubusercontent.com/d1300e47bd3fc64981c653ce0a14c3465813207499e220ab3c075f01e29eba90/68747470733a2f2f692e696d6775722e636f6d2f6a486262386e4f2e706e67) 삼항연산자는 if문을 조금 더 간결하게 혹은 가독성이 좋게 사용하는, 결과적으로는 같은 기능을 한다고 생각했는데 오류를 뱉는 이유가 조금 궁금합니다...
> 
> 삼항연산자 내에서 Void function의 호출을 지양해야한다는 린트의 경고에 대해 숲재의 의견은 어떠신가요?
> 

단순 if문이 중첩된다는 이유만으로 삼항연산자를 사용하게 되면 오히려 가독성을 더 해칠 수 있다고 생각해요. 특히 3항연산자에서 사용하는게 메서드라면요. 메서드의 분리가 더 낫지 않을까 싶습니다.


> ### 3️⃣ 액티비티 뷰 컨트롤러를 통해 보는 일기장 내용
> 액티비티 뷰 컨트롤러를 통해 일기장 내용을 복사하거나 리마인더에 추가할 수 있습니다. <img alt="" width="300" src="https://camo.githubusercontent.com/213caccf26787e709407baa44b5f6c4f68dd605c3c3670aac7bb002643699c90/68747470733a2f2f692e696d6775722e636f6d2f7a4b6b504638352e706e67"> 그런데, 두 가지 경우에서 내용이 달리 표시가 됩니다.
> 
> `Copy`	`Reminders`
> <img alt="" width="300" src="https://camo.githubusercontent.com/06b32c7ef0e08af667e60f5e969754d410295c92275c85637d556bd2ae7496aa/68747470733a2f2f692e696d6775722e636f6d2f4c42704a7672712e706e67">	<img alt="" width="300" src="https://camo.githubusercontent.com/3d04dc0a09806524dbb71746abe219f7e23a35bb458a375e1dc75548701dc348/68747470733a2f2f692e696d6775722e636f6d2f754d74305331472e706e67">
> Copy를 눌러 새 일기장에 붙여넣기 한 경우입니다.
> 개행이 사라진 채로 내용이 작성됩니다.	Reminders에 추가하는 경우입니다.
> 개행이 유지가 된 채로 내용이 작성됩니다.
> 이렇게 두 가지 경우에서 일기장의 내용이 달라집니다. 제목과 내용 사이의 개행이 어느때는 사라지고, 어느 때는 유지가 됩니다. 이 문제를 어떻게 해결하면 좋을까요?

현재 ActivitiItem으로 String 배열을 넘겨주어서 발생하는 문제 같습니다. UIActivityItemSource 프로토콜을 사용해서 건네줄 데이터를 적절히 만들어주거나, String으로 넘겨주는 시점에 개행문자를 포함하는 방법 등이 있겠네요.

2023-05-05 04:44 UTC, forestjae commented on Diary/Model/CoreDataManager.swift
> +            }
이 로직이 모든곳에서 반복되고 있네요. 
또, do catch 가 중첩되는것은 피하는게 좋을 것 같아요.

2023-05-05 06:04 UTC, Rhode-park commented on Diary/Controller/DetailDiaryViewController.swift
> +import CoreData
[`0114957`](https://github.com/yagom-academy/ios-diary/pull/101/commits/011495720e5384764eb0720f7195f4004c71c523)

제거하였습니다.

2023-05-05 06:04 UTC, Rhode-park commented on Diary/Controller/DetailDiaryViewController.swift
> +    private var isCreateDiary: Bool = false
[`0114957`](https://github.com/yagom-academy/ios-diary/pull/101/commits/011495720e5384764eb0720f7195f4004c71c523)

상수로 바꾸고 네이밍 역시 영문법에 맞게 변경하였습니다.

2023-05-05 06:05 UTC, Rhode-park commented on Diary/Controller/DetailDiaryViewController.swift
> +    private func configureDiary() -> Diary? {
[`0114957`](https://github.com/yagom-academy/ios-diary/pull/101/commits/011495720e5384764eb0720f7195f4004c71c523)

Diary 인스턴스 만드는 부분이 `createDiary`와 기능 분리 될 필요가 없다고 판단하여서 하나로 합쳤습니다.

2023-05-05 06:08 UTC, parkmuri commented on Diary/Controller/DetailDiaryViewController.swift
> +        self.title = diaryDate
```swift
   self.diary = diary
   // ...
   title = diaryDate
```
54번째 줄에서 ViewController의 변수와 매개변수를 분리해주기위해 `self`를 써주면서 가독성을 위해 같은 메서드 내의 `title = diaryDate`에도 작성하게되었습니다🥲.. 하지만 `configureNavigationBar()`메서드 내에서는 self를 붙여 줄 이유가 없기때문에 붙여주지 않았습니다...
가독성을 위해 붙였지만 컨벤션에는 많이 어긋나게되었네요...! 컨벤션을 지키면서 코드를 짤 수 있도록 해보겠습니다😭

011495720e5384764eb0720f7195f4004c71c523

2023-05-05 06:42 UTC, parkmuri commented on Diary/Controller/DetailDiaryViewController.swift
> +        let body = checkValidDiary(diaryContents)
현재 뷰컨트롤러가 들고있는 옵셔널인 Diary객체는 데이터를 읽기 위한 객체로 사용하고있습니다. 만약 일기를 수정해야 하는 상황이라면 사용자가 새로 입력한 값을 기존 저장 값에 업데이트해주어야하기 때문에 textView에서 값을 추출해오는것이 맞다고 생각을 했습니다. 
중복 로직이 있지만  중복된 부분이 분산되어있어그 부분들을 별도의 메서드로 분리하기에는 따로 분리한 메서드가 하나의 기능을 수행 할 지에 대해서는 잘 모르겠습니다....! 

그래서 저희는 `createDiary()`, `updateDiary()`메서드를 각각 유지하는것이 좋다고 생각하였습니다. 저희가 숲재의 생각을 잘못이해했을까요?

2023-05-05 11:21 UTC, parkmuri commented on Diary/Controller/DetailDiaryViewController.swift
> +    }
해당 메서드가 매개변수로 받는 `[String.Subsequenece]`의 갯수에 따라 빈 스트링을 반환하거나, 해당 배열안에 존재하는 string값을 반환하고있습니다. `returnValidBody`와 `validBody` 중 고민을 하다가 return을 명시해주지않아도 충분히 해당 메서드의 기능이 설명된다고 생각하여 `validBody()`로 리네이밍 해주었습니다.

[참고자료-API Design GuideLines](https://www.swift.org/documentation/api-design-guidelines/)
>When the operation is naturally described by a noun, use the noun for the nonmutating method and apply the “form” prefix to name its mutating counterpart.


68027eec0a936f7dbbb580276e280b00db0a6997

2023-05-05 11:33 UTC, Rhode-park commented on Diary/Controller/DetailDiaryViewController.swift
> +    private func saveDiary() {
[`710bedd`](https://github.com/yagom-academy/ios-diary/pull/101/commits/710bedd770a780b9fd85f59333bbee305904c0dc)

작성중이거나 생성중에 공유 버튼을 눌렀을 때 `diary`에 저장이 되도록 로직을 수정해봤습니다.

2023-05-05 11:47 UTC, parkmuri commented on Diary/Controller/DiaryListViewController.swift
> -    private var diary: [Diary]? {
Detail에서는 해당 일기를 읽기 위해 Diary프로퍼티를 들고있고, 해당 뷰컨트롤러에서 `private var diary: [Diary]?`를 삭제한 이유는  각각 내부에서 `coreDatamanager.readDiary()`를 호출해주어 전역으로 둘 필요가 없다고 생각해서였습니다...!
코멘트를 보고 로데와 이야기해본 결과 다이어리를 전역으로 들고 관리를 해주는것이 여러번 호출하는것보다 더 효율적이라고 생각되어서 수정해주었습니다. 

[9fa2b08](https://github.com/yagom-academy/ios-diary/pull/101/commits/9fa2b0825cad6a22197a74815ca45f29924f8a89)

2023-05-05 11:52 UTC, Rhode-park commented on Diary/Extension/Double+.swift
> +              let result = Double(formattedString) else { return nil }
`Date().timeIntervalSince1970`를 해주었을 때 소수점 아래 값이 나오곤 했습니다. 저희가 필요한 것은 년월일에 해당하는 부분이기 때문에 소수점 아래부를 날려주기 위해 해당 메서드를 만들었습니다.

2023-05-05 11:53 UTC, parkmuri commented on Diary/Extension/String+.swift
> +}
일기의 내용에서 제목과 내용을 나누는 공백외에 다른 공백이 생기면 List에서 내용이 표시되지 않아(공백으로 보이기때문에) 추가한 로직입니다. 요구사항에는 없지만 추가해주면 좋을 것 같아서 구현해보았습니다..🥲

2023-05-08 05:43 UTC, Rhode-park commented on Diary/Controller/DiaryListViewController.swift
> +            self.coreDataManager.deleteDiary(diary: diaryToDelete)
일단 다음과 같이 리팩토링 했습니다만, 숲재의 말씀을 잘 이해하진 못했습니다.

**CoreDataManager**
```swift
func deleteDiary(diary: Diary) throws {
    let fetchRequest = NSFetchRequest<NSManagedObject>(entityName: "Entity")
    fetchRequest.predicate = NSPredicate(format: "id == %@", diary.id as CVarArg)
    
    do {
        let objects = try context.fetch(fetchRequest)
        let objectToDelete = objects[0]
        context.delete(objectToDelete)
        
        do {
            try context.save()
        } catch {
            throw error
        }
    } catch {
        throw error
    }
}
```

**DiaryListViewController - tableView**
```swift
do {
    try self.coreDataManager.deleteDiary(diary: diaryToDelete)
} catch {
    let alert = UIAlertController(title: "알림", message: "\(error)", preferredStyle: .alert)
    let okAction = UIAlertAction(title: "확인", style: .default)
    alert.addAction(okAction)
    self.present(alert, animated: true)
}
```
1. 어떤 경우에, deleteDiary메서드가 실패할 수 있을까요?
2. 이렇게 에러를 처리하는 것이 숲재가 생각하시는 적절한 방법일까요?

2023-05-08 05:51 UTC, parkmuri commented on Diary/Controller/DiaryListViewController.swift
> +            self.coreDataManager.deleteDiary(diary: diaryToDelete)
"에러를 어디에서 처리해야 하는가"에 대해서 궁금한 점이 있습니다🥲...
리팩토링 전에는 CoreDataManager 내부 `deleteDiary()`메서드에서 do-catch문으로 에러를 캐치해주고있었는데, 위와같이 테이블뷰쪽에서 catch를 해야하는것이 더 좋은 방법일까요? 
CoreDataManager의 `deleteDiary()`메서드를 사용하는 곳이 테이블뷰와 디테일뷰 두 군데라서 각각 호출하는 부분마다 do-catch문을 사용해주는 것이 코드의 중복이 되는 것 같기도합니다. 각 호출부에서 사용하는 것 보다는 최종적으로 호출되는 CoreDataManager의 `deleteDiary()`메서드 내부에서 처리하는것이 최선인 것 같아 숲재의 의견도 듣고싶습니다...!

2023-05-08 11:53 UTC, Rhode-park commented on Diary/Model/CoreDataManager.swift
> +class CoreDataManager {
## Generic한 CoreDataManager 만들기
### 1️⃣ Generic T 사용 후, struct의 property들에 접근하여 iterate하는 방법

```swift
managedObject.setValue(diary.id, forKey: "id")
managedObject.setValue(diary.title, forKey: "title")
managedObject.setValue(diary.body, forKey: "body")
managedObject.setValue(diary.date, forKey: "date")
```

Generic으로 바꾸는 과정에서 해당 부분을 for문이나 forEach를 돌려서 직접적인 프로퍼티 이름을 사용하지 않으면 좋겠다는 생각이 들었습니다.

그래서 다음과 같이 코드를 짜보았습니다:

```swift
let properties = Mirror(reflecting: diary).children.filter { $0.label != nil }
for property in properties {
    guard let label = property.label else { return }
    managedObject.setValue(property.value, forKey: label)
}
```

이렇게 하게 될 경우, create와 update, delete는 해결할 수 있었습니다. 전체적인 코드를 보여드리겠습니다. (수정 중이라 diary라는 변수명을 쓰기도 하지만.. 타입은 T를 사용하고 있습니다..ㅎㅎ) id는 무조건 첫번째 프로퍼티로 오게 될 것이라고 상정을 하여서 0번 인덱스로 지정하였습니다.

```swift
import CoreData
import Foundation

class CoreDataManager<T> {
//    static var shared: CoreDataManager = CoreDataManager()
    
    lazy var persistentContainer: NSPersistentContainer = {
        let container = NSPersistentContainer(name: "Diary")
        container.loadPersistentStores(completionHandler: { (storeDescription, error) in
            if let error = error as NSError? {
                fatalError("Unresolved error \(error), \(error.userInfo)")
            }
        })
        
        return container
    }()
    
    var context: NSManagedObjectContext {
        return persistentContainer.viewContext
    }
    
    var diaryEntity: NSEntityDescription? {
        return  NSEntityDescription.entity(forEntityName: "Entity", in: context)
    }
    
    func createDiary(_ diary: T) {
        if let entity = diaryEntity {
            let managedObject = NSManagedObject(entity: entity, insertInto: context)
            
            let properties = Mirror(reflecting: diary).children.filter { $0.label != nil }
            
            for property in properties {
                guard let label = property.label else { return }
                managedObject.setValue(property.value, forKey: label)
            }
            
            do {
                try self.context.save()
            } catch {
                print(error.localizedDescription)
            }
        }
    }
    
    func readDiary() -> [Diary]? {
        let fetchRequest = NSFetchRequest<NSManagedObject>(entityName: "Entity")
        var diaries = [Diary]()
        
        guard let diaryData = try? context.fetch(fetchRequest) else { return nil }
        
        for diary in diaryData {
            guard let id = diary.value(forKey: "id") as? UUID,
                  let title = diary.value(forKey: "title") as? String,
                  let body = diary.value(forKey: "body") as? String,
                  let date = diary.value(forKey: "date") as? Double else { return nil }
            
            diaries.append(Diary(id: id, title: title, body: body, date: date))
        }
        
        return diaries
    }
    
    func updateDiary(diary: T) {
        let fetchRequest = NSFetchRequest<NSManagedObject>(entityName: "Entity")
        
        let properties = Mirror(reflecting: diary).children.filter { $0.label != nil }
        
        guard let id = properties[0].value as? any CVarArg else { return }
        
        fetchRequest.predicate = NSPredicate(format: "id == %@", id)
        
        do {
            let objects = try context.fetch(fetchRequest)
            let objectToUpdate = objects[0]
            
            let properties = Mirror(reflecting: diary).children.filter { $0.label != nil && $0.label != "id" }
            
            for property in properties {
                guard let label = property.label else { return }
                objectToUpdate.setValue(property.value, forKey: label)
            }
            
            do {
                try self.context.save()
            } catch {
                print(error.localizedDescription)
            }
        } catch {
            print(error.localizedDescription)
        }
    }
    
    func deleteDiary(diary: T) throws {
        let fetchRequest = NSFetchRequest<NSManagedObject>(entityName: "Entity")
        
        let properties = Mirror(reflecting: diary).children.filter { $0.label != nil }
        
        guard let id = properties[0].value as? any CVarArg else { return }
        
        fetchRequest.predicate = NSPredicate(format: "id == %@", id)
        
        do {
            let objects = try context.fetch(fetchRequest)
            let objectToDelete = objects[0]
            context.delete(objectToDelete)
            
            do {
                try context.save()
            } catch {
                throw error
            }
        } catch {
            throw error
        }
    }
}
```

뷰컨트롤러에서 사용할 때는 다음과 같이 사용하면 됩니다:
```swift
    private var coreDataManager = CoreDataManager<Diary>()
```

그러나 문제는 따로 있습니다. 

```swift
guard let id = diary.value(forKey: "id") as? UUID,
      let title = diary.value(forKey: "title") as? String,
      let body = diary.value(forKey: "body") as? String,
      let date = diary.value(forKey: "date") as? Double else { return nil }

diaries.append(Diary(id: id, title: title, body: body, date: date))
```

read의 경우, 이렇게 타입캐스팅을 한 후, 다이어리 인스턴스를 만들어서 넣어야합니다. 그런데, 범용성을 가지기 위해서 Generic한 아이로 만들면... 인스턴스를 과연 어떻게 만들어야 할까요??ㅠㅠㅠㅠㅠ T에 들어올 아이가 얼마나 많은 프로퍼티를 가지고 있을지 모릅니다. 그리고 어떤 프로퍼티가 몇번째 항목으로 올지도 모르겠구요. `mirror`를 사용하고, 배열에 넣어봤다가 이래저래해도 잘 되지 않네요. 도대체 어떻게 해야할까요?ㅠㅠ 😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭 숲재의 도움이 절실히 필요합니다.


### 2️⃣ Generic한 class/protocol을 만들고 상속/채택을 하는 방법
위의 방법과 함께 시도해본것으로는 상속/채택을 이용하는 것 이었습니다. class 혹은 protocol을 generic하게 만들어 상속/채택을 받고 구현을 해보았습니다.
클래스의 경우 부모클래스에서 구현이 가능한 부분은 구현을 하고, 불가능한 부분은 override를 이용해야했습니다. `CoreDataManager`부모클래스를 상속받는 서로 다른 데이터매니저들의 특정 메서드만 따로 구현을 해야하는 것이 말씀해주신 범용성과는 맞지 않는 것 같았습니다😭 (코드는 위와 같아서 첨부하지 않았습니다.)

프로토콜같은 경우에도 클래스와 비슷하게 직접 구현해주어야하는 부분 (예를 들어 `Diary`의 인스턴스를 만들 때, 혹은 다른 모델의 인스턴스를 만들어야 할 때 모델의 프로퍼티 등을 지정해주어야 한다는 점)에서 재정의를 해야했는데, 어떻게하면 범용적인 방법으로 사용할 수 있는지 궁금합니다🥲....!

2023-05-08 12:30 UTC, parkmuri commented on Diary/Model/CoreDataManager.swift
> +        return persistentContainer.viewContext
숲재의 코멘트를 보고 해당 키워드들에 대해 좀 더 찾아보게되었습니다..
~~공식문서의 내용이 상당히 짧고 어렵네요....!~~

`viewContext`
- 메인큐에서 관리되는 object context
- 앱의 메인 큐와 관련된 persistent container가 생성&소유하는 NSManagedObjectConext에 대한 참조를 포함하고, persistent container의 initialization으로 자동생성 됩니다. 
- 따라서 현재 코드에서는 persistent container를 생성해준 후 persistentContainer.viewContext로 접근하여 반환받고있습니다. 

`newBackgroundContext()`
- private queue에서 실행되는 새로 관리되는 object context를 반환하는 메서드
- 해당 메서드를 호출하게되면 persistent container가 context와 private dispatch queue가 연관되도록 지정한 새 NSManagedObjectContext를 반환합니다. 반환된 context는 NSPersistenStoreCoordinator와 직접 연관되며 NSManagedObjectContextDidSave의 브로드캐스트를 자동으로 사용하도록 설정됩니다. 

공식문서를 읽고도 감이 오지않아 조금 더 찾아보았는데, 백그라운드에서 비동기적인 작업을 요구할 때 사용될 수 있는 메서드라고 이해해보았습니다🥹

2023-05-08 13:32 UTC, parkmuri commented on Diary/Model/CoreDataManager.swift
> +            }
해당 로직은 메서드로 분리하였습니다!

2023-05-10 15:14 UTC, forestjae commented on Diary/Controller/DiaryListViewController.swift
> +            self.coreDataManager.deleteDiary(diary: diaryToDelete)
1. 어떤 경우에, deleteDiary메서드가 실패할 수 있을까요?
구현하신 메서드 안에 답이 있네요. context fetch에 실패할 수 도 있고 save가 실패하는 경우가 생길 수 있습니다.

2. 이렇게 에러를 처리하는 것이 숲재가 생각하시는 적절한 방법일까요?
이 부분에 대해서 제가 코멘트를 단 이유는, delete 메서드가 실패가능한 throw 메서드 임에도 불구하고 그 성공여부와 상관없이 이후의 tableView의 deleteRows를 호출하고 있었기 때문입니다. 그럼 크래시가 발생합니다.

무리가 말씀하신대로 throw 체인이 계속 이어지다가, 마지막에 호출되는 부분에서 처리하는것이 일반적인 방법입니다!

2023-05-10 15:16 UTC, forestjae commented on Diary/Extension/Double+.swift
> +              let result = Double(formattedString) else { return nil }
floor() 메서드를 사용하지 않으신 이유가 궁금해서 여쭤봤어요.

2023-05-10 15:26 UTC, forestjae commented on Diary/Model/CoreDataManager.swift
> +class CoreDataManager {
Mirror까지 써보셨군요 ㅎㅎ
음 간단하게 말씀드리면, 현재 CoreDataManager<T> 라는 제네릭한 클래스를 만들어 주셨는데요, 여기에 한 계층을 추가해서 (예) DiaryStorage 라는 다이어리타입을 전문으로 다루는 타입을 만드는 것이죠. 그렇게 되면 질문에서 말씀을 하신 제네릭하게 해결할 수 없는 부분들을 그 계층에서 담당하면 되기때문에 수월하게 만들 수 있습니다.

https://github.com/forestjae/GIPHY_Search 레포의 CoreDataProvider와 FavoriteStorage 파일을 참고해보세요!

2023-05-10 15:27 UTC, forestjae commented on Diary/Model/CoreDataManager.swift
> +        return persistentContainer.viewContext
네 면접에 자주 나오는 질문이니 잘 공부해놓으시면 좋을 것 같습니다

2023-05-10 15:29 UTC, forestjae commented on Diary/Controller/DetailDiaryViewController.swift
> +        let body = checkValidDiary(diaryContents)
네 납득했습니다.

2023-05-10 15:30 UTC, merged