일기장 [STEP2] 리지, Goat
yagom-academy/ios-diary pull request #102
Opened 2023-05-04 07:23 UTC by yijiye

@uuu1101 태태 안녕하세요! 리지, goat 입니다
일기장 STEP2 PR 잘부탁드립니다 🙇‍♂️

## 구현한 점
- **CoreDataManager** - 작성한 일기 저장 및 삭제, 불러오기 등 CoreData를 관리하는 객체 구현
- **UIActivityViewController** - 일기 공유 창 띄우기
- **AlertManager** - 다양한 곳에 사용할 AlertManager 구현
- **UnitTest** - CoreDataManager UnitTest

## 고민한 점

### 1️⃣ Samplediary -> Diary 형태의 특정 모델 구조 예시로 잡아놓기
Diary형태의 포맷을 파싱하거나 코어데이터에 저장하기때문에 `DiaryProtocol`을 작성하고 `Strcut MyDiary`구조체가 프로토콜을 채택하게함으로써 `MyDiary`에 코어데이터를 저장하는 형태로 구조를 잡았습니다.

```swift
struct MyDiary: DiaryProtocol {
    var title: String
    var body: String
    var createdDate: Double
}
```

<br/>

### 2️⃣ 상황에 따른 VC 분기처리

일기를 새로 추가하는 VC와 이미 작성한 일기 화면의 VC를 하나의 VC로 관리하면서 각각의 상황을 어떻게 분리할지 고민하였습니다.
처음엔 Bool 타입 변수를 선언하여 분기처리를 하였으나, 가독성이 떨어져 enum Mode를 구현하여 case 별로 분기처리를 하였습니다.

```swift
enum Mode {
        case edit
        case create
    }
```

<br/>

### 3️⃣ reloadData

ListVC에 구현된 myDiary에 `setUpMyDiary`메서드를 통해서 코어데이터들이 전부 저장되고 해당 프로퍼티에 접근해서 tableView에 셀을 그리는 방식의 구조였습니다.
뷰가 바뀌었을때 `reloadData`를 해주지않으면 코어데이터의 값만 변경되어서 화면에 즉각적으로 변경된 cell이 올라오지않는 현상이 발생해서, `reloadData`메서드로 해결했습니다.
```swift
 private var myDiary: [DiaryCoreData]?

 override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        setUpMyDiary()
        diaryTableView.reloadData()
    }
    
    private func setUpMyDiary() {
        guard let diary = CoreDataManager.shared.readAll() else { return }
        myDiary = diary
    }
```

<br/>

### 4️⃣ activityView / detailVC - ListVC - detailVC 과정에서 재동작시 activityView 뜨지않는 현상발생

```swift
private var titleText: String?
private var bodyText: String?

// editMode VC
extension DiaryListViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
 let diaryDetailViewController = DiaryDetailViewController(fetchedDiary: fetchedDiary, mode: .edit, titleText: fetchedDiary.title, bodyText: fetchedDiary.body)
        self.navigationController?.pushViewController(diaryDetailViewController, animated: true)
    }
    
// createMode VC  
private func plusButtonTapped() {
        let diaryDetailViewController = DiaryDetailViewController(fetchedDiary: nil, mode: .create, titleText: nil, bodyText: nil)
        navigationController?.pushViewController(diaryDetailViewController, animated: true)
    }

```
titleText, bodyText가 옵셔널값입니다. ListVC에서 detailVC로 다시돌아갈때 옵셔널 전역변수인 두 프로퍼티값이 초기화되는 현상이발생하고 activityView로 할당되지못한채 guard let에서 return 되버린채 activityView가 뜨지않는 현상이 발생했습니다.
- init에 titleText와 bodyText를 넣어주어 화면 전환시 새로운 일기화면에는 nil 값을 주고, tableView를 선택했을 때는 indexPath 값의 title, body를 넘겨주어 오류를 해결하였습니다.

```swift
private func showActivityView() {
        guard let titleText = titleText,
              let bodyText = bodyText else {
            AlertManager.shared.showAlert(target: self,
                                          title: "일기를 작성해주세요!",
                                          message: "비어있는 일기는 공유되지 않습니다.",
                                          defaultTitle: "확인",
                                          destructiveTitle: nil,
                                          destructiveHandler: nil)
            return }

```

추가적으로 **두 프로퍼티가 nil값일때 guard let 구문앞에서 alert경고를 띄워주고 return 시키며 사용자의 입력값을 받는 방식**으로 일기가 비어있을 때, 공유되거나 저장되지 않도록 구현하였습니다.

<br/>

### 5️⃣ swipe delete 시 coreData 업데이트가 되지않아 발생하는 row 관련 에러

일기를 삭제하면 CoreData에 저장된 일기를 지우고, tableView도 삭제되도록 하였습니다.
그런데 CoreData와 tableView가 서로 일치하지 않아 런타임오류가 발생하였습니다.

```swift
func tableView(_ tableView: UITableView, trailingSwipeActionsConfigurationForRowAt indexPath: IndexPath) -> UISwipeActionsConfiguration? {
       ...
        let delete = UIContextualAction(style: .normal, title: "삭제") {
                     ... 
            CoreDataManager.shared.delete(key: title)
            self?.setUpMyDiary()
            tableView.deleteRows(at: [indexPath], with: .fade)
                
            })
            success(true)
        }
      ...
    }
```

원인을 찾아보니, CoreData에서 삭제하고 CoreData의 모든 값을 불러오는 myDiary가 업데이트가 되지 않았던 문제로 삭제 후 다시 업데이트 하여 tableView의 row를 삭제하도록 로직을 수정하였습니다.

<br/>

### 6️⃣ TextView title, body 분리

처음엔 타이틀과 바디를 각각 `textField`와 `textView`로 구현을 하였으나, 명세에 "textView의 첫 번째 줄이 title, 나머지가 body가 되도록 한다는 내용"이 있어 하나의 `textView`로 묶어주고 아래와 같이 title, body로 나뉘게끔 분기처리를 하였습니다.

```swift
  func textViewDidChange(_ textView: UITextView) {
        guard let text = diaryTextView.text else { return }
        self.titleText = text.components(separatedBy: "\n").first
        self.bodyText = text.replacingOccurrences(of: "\(String(describing: titleText)) \n", with: "")
    }
    
```

띄어쓰기를 기준으로 나눠 first 값은 title이 되고, title이 된 부분을 ""으로 바꾼 text가 body가 되도록 구현하였습니다.

### CoreData 저장위치확인

<img src="https://i.imgur.com/qzx6Ppu.png" width="400">

<br/>

저희는 scheme에 위와 같은 argument를 추가하여 CoreData 저장위치를 확인하였습니다. Tool을 이용하여 확인해보니 Application/Support에 저장되어있어 파일 위치를 변경하지 않았습니다.

<img src="https://i.imgur.com/pvVdObz.png" width="400">

## 조언이 필요한 점

### 1️⃣ AlertManager 구현 방법

저희는 Alert를 관리하는 객체인 AlertManager를 만들어 다양한 곳에서 Alert을 띄우는데 활용하였습니다.

그리고 현재는 사용하는 곳에서 맞는 매개변수를 입력하도록 actionSheet, alert style 별로 2가지 메서드를 구현을 하였는데, 이렇게 하다보니 입력해야하는 매개변수가 많아지는 단점이 있었습니다.

매개변수로 넣지 않고 필요한 Alert을 메서드별로 구현해서 관리하는 것이 좋을지 현재처럼 모든 값을 매개변수로 받는게 좋은지, 태태의 의견이 궁금합니다!

```swift
func showAlert(target: UIViewController, title: String, message: String?, defaultTitle: String, destructiveTitle: String?, destructiveHandler: ((UIAlertAction) -> Void)?) {
    ...
}

func showActionSheet(target: UIViewController, title: String?, message: String?, defaultTitle: String, destructiveTitle: String, defaultHandler: ((UIAlertAction) -> Void)?, destructiveHandler: ((UIAlertAction) -> Void)?) {
    ...
}
```

### 2️⃣ 앱이 백그라운드로 이동했을 때 알림

명세에 일기가 자동으로 저장되는 경우 중, 백그라운드로 이동했을 때 조건이 있었습니다. 저희는 Notification을 활용하여 알림을 주는 방법을 선택하였고, 이를 `DiaryDetailViewController` 애서 해주었습니다.

```swift
private func setUpBackgroundNotification() {
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(saveDiary),
            name: UIScene.willDeactivateNotification,
            object: nil
        )
    }
```

이 코드에서 UIScene.willDeactivateNotification을 사용하여 앱이 비활성화 되는 순간을 알려주도록 했는데 이 코드를 VC에서 사용해도 괜찮은지 궁금합니다.

### 3️⃣ JSON 디코딩

이 부분은 간단한 고민인데요..!
현재 저희 코드에서는 SampleDiary를 CoreData에 저장하거나 화면에 띄어주고 있지 않습니다.
sampleDiary라 굳이 필요하지 않다고 생각하여 삭제를 하였는데, 사용하지 않는 파일이 프로젝트에 있는 것도 어색하다고 느껴졌습니다.
프로젝트를 진행하면서 JSON을 구현했어야 하는 이유가 무엇인지 궁금합니다 😂 이번 스텝에서도 기본값으로 sampleDiary를 띄웠어야 했을까요?

2023-05-08 13:53 UTC, uuu1101 requested changes
안녕하세요 @yijiye @Goatt8 
리뷰가 늦어져서 죄송합니다 ㅠㅠ 

조언이 필요한 점
---
1️⃣ AlertManager 구현 방법
- 해당 부분에 대해서는 코드에 피드백을 남겨 두었습니다.
저는 하나의 AlertManager에 ErrorAlert 처럼 용도에 맞는 메서드를 만들어두고 사용합니다.
지금 경우에서는 피드백 드린내용으로도 가능할 것 같습니다!

2️⃣ 앱이 백그라운드로 이동했을 때 알림
앱의 상태를 뭔가 관리해주는 객체가 하나 있으면 더 좋을 것 같습니다.
VewController가 앱의 상태에 대해서 제어하는건 뭔가 어색해보입니다.

3️⃣ JSON 디코딩
- 해당 부분은 JSON을 가지고 모델링을 하는 것에 초점을 둔것 같고 
프로젝트 설명에도 나와있듯이 `주의) 이 JSON 데이터 활용을 위해 너무 많은 시간을 쏟지 마세요, 정말 말그대로 견본 데이터입니다`라고 되어 있습니다.
테스트를 위해서 가지고 있는것도 괜찮아보이구요. Mock을 만들어서 사용하겠다, 필요하지 않다라고 생각되면 삭제 해주시는것도 괜찮아보이네요 ! 
판단은 여러분들이 하시고 충분한 근거가 있으면 될 것 같습니다 ! 

더 궁금하거나 중점적으로 봐주었으면 하는 부분이 있다면 알려주시면 중점적으로 보도록 하겠습니다 ! 
Commit을 따라 가면서 보다 보니 추후에 수정된 부분에 대해서도 피드백이 남을수 있습니다 !

2023-05-08 13:53 UTC, uuu1101 commented on Diary/ViewController/DiaryDetailViewController.swift
> +        textView.text = diary.title + "\n\n" + diary.body
개행이 두번 들어가 있는 이유가 궁금합니다👀

2023-05-08 13:53 UTC, uuu1101 commented on Diary/ViewController/DiaryDetailViewController.swift
> +    @objc internal func keyboardWillHide(_ notification: Notification) {
internal을 여기만 명시해주신 이유가 궁금해요

2023-05-08 13:53 UTC, uuu1101 commented on Diary/ViewController/NewDiaryViewController.swift
> +    func setUpNotification() {
여긴 접근제어자가 불필요한가요?!

2023-05-08 13:53 UTC, uuu1101 commented on Diary/ViewController/DiaryDetailViewController.swift
> +        if isAutomaticKeyboard == true {
`if isAutomaticKeyboard { ` 로 작성하셔도 좋을 것 같습니다 !

2023-05-08 13:53 UTC, uuu1101 commented on Diary/Model/DateFormatterManager.swift
> +    func convertToFomattedDate(of date: Double) -> String? {
`Int`에서 `Double` 로 변경하게 된 배경이 있으신가요?!

2023-05-08 13:53 UTC, uuu1101 commented on Diary/ViewController/DiaryDetailViewController.swift
> +    private lazy var diaryTitleField: UITextField = {
`lazy` 는 어떤 역할을 하나요?!

2023-05-08 13:53 UTC, uuu1101 commented on Diary/ViewController/DiaryDetailViewController.swift
> +    }
placeHolder를 구현하셨네요👍

2023-05-08 13:53 UTC, uuu1101 commented on Diary/Model/Manager/AlertManager.swift
> +    func showAlert(target: UIViewController, title: String, message: String?, defaultTitle: String, destructiveTitle: String?, destructiveHandler: ((UIAlertAction) -> Void)?) {
정말 필요한 파라미터는 title: Stirng 이렇게 작성하시고 
옵셔널인 부분은 _ message: String? 이렇게 작성하시면 사용하는 부분에서 좀 더 편할것 같습니다 :)

2023-05-08 13:53 UTC, uuu1101 commented on Diary/Model/Manager/AlertManager.swift
> +    func showActionSheet(target: UIViewController, title: String?, message: String?, defaultTitle: String, destructiveTitle: String, defaultHandler: ((UIAlertAction) -> Void)?, destructiveHandler: ((
위와 동일합니다 !

2023-05-09 01:30 UTC, yijiye commented on Diary/ViewController/DiaryDetailViewController.swift
> +        textView.text = diary.title + "\n\n" + diary.body
수정 전이라 현재에는 반영되어있지 않습니다!

2023-05-09 01:31 UTC, Goatt8 commented on Diary/ViewController/DiaryDetailViewController.swift
> +    @objc internal func keyboardWillHide(_ notification: Notification) {
이 부분도 수정전입니다 어색해보여서 수정했습니다!

2023-05-09 01:35 UTC, Goatt8 commented on Diary/ViewController/DiaryDetailViewController.swift
> +        if isAutomaticKeyboard == true {
isAutomaticKeyboard 매서드 역시 DetailViewController를 create모드, edit모드로 분기처리하면서 삭제된 분기처리방식입니다. 현재는 반영되어있지 않습니다

2023-05-09 01:40 UTC, yijiye commented on Diary/ViewController/DiaryDetailViewController.swift
> +    private lazy var diaryTitleField: UITextField = {
lazy를 사용하면 diaryTitleField가 필요한 시점에서 초기화됩니다. 현재 titleField를 사용하지는 않지만 구현했을 때, titleField에서 사용하는 프로퍼티 보다 먼저 인스턴스가 생성되는 오류가 있어lazy var로 구현하였습니다.

2023-05-09 01:47 UTC, Goatt8 commented on Diary/Model/Manager/AlertManager.swift
> +    func showAlert(target: UIViewController, title: String, message: String?, defaultTitle: String, destructiveTitle: String?, destructiveHandler: ((UIAlertAction) -> Void)?) {
매개변수에 와일드카드를 붙이는 방식이 매서드를 사용하는곳에서 봤을때 어떤항목이 존재하는지 판별하는데 어색함이 더 있는거 같습니다! 그래서 매개변수는 일단 보이도록 표기하는 방식을 채택하기로 했습니다!

2023-05-09 02:31 UTC, yijiye commented
```swift
func sceneDidEnterBackground(_ scene: UIScene) {
        guard let navigationController = window?.rootViewController as? UINavigationController,
              let diaryDetailViewController = navigationController.viewControllers.last as? DiaryDetailViewController else { return }
        
        diaryDetailViewController.saveDiary()
    }
```

앱 전체의 생명주기를 관리하는 sceneDelegate에 `sceneDidEnterBackground` 앱이 백그라운드로 들어갔을 때 호출되는 메서드를 활용하였습니다.
우선 navigationController 인스턴스를 생성하고 `navigationController.viewControllers.last`를 통해서 navigationController에 쌓여있는 ViewController의 마지막, 현재 띄워져있는 화면을 가져왔습니다.
이렇게 최상위 ViewController를 가져온 후 saveDiary를 호출하여 앱이 백그라운드로 이동했을 시 자동저장되도록 로직을 수정하였습니다.

2023-05-09 02:36 UTC, yijiye commented on Diary/Model/DateFormatterManager.swift
> +    func convertToFomattedDate(of date: Double) -> String? {
Int 타입으로 했을 때, Date 를 변환하면서 'TimeInterval(date)' 로 타입을 변환시켜주는 과정이 필요하였습니다. 그래서 Double로 바꾸고 타입을 변환하는 과정을 삭제하였습니다!

2023-05-09 16:13 UTC, merged