일기장 [STEP 2] kaki, 레옹아범
yagom-academy/ios-diary pull request #103
Opened 2023-05-04 07:45 UTC by kak1x

# 일기장 [STEP 2] kaki, 레옹아범
@havilog
안녕하세요 하비! kaki, 레옹아범 입니다🙂
STEP 2 구현이 완료되어 PR 드려요!! 잘 부탁드립니다🫡

## 구현내용

### Core Data CRUD
- PersistenceManager를 구현하였고 이곳에 CRUD 관련 기능을 구현해두었습니다.
- Read 기능 사용 시 날짜를 기준으로 하여 데이터를 정렬할 수 있게 구현하였습니다.
- Update 및 Delete 기능 사용 시 entity 객체의 objectID를 통해 데이터를 검색하여 이를 작업할 수 있도록 구현하였습니다.

### 백그라운드 진입 시 메모 저장
```swift
NotificationCenter.default.addObserver(self,
                                       selector: #selector(endEditingDiary),
                                       name: UIScene.didEnterBackgroundNotification,
                                       object: nil)
```
* `UIScene.didEnterBackgroundNotification`을 사용하여 백그라운드 진입 시 저장하도록 구현하였습니다.

### 셀 스와이프 시 공유와 삭제 기능 구현
```swift
func tableView(_ tableView: UITableView, trailingSwipeActionsConfigurationForRowAt indexPath: IndexPath) -> UISwipeActionsConfiguration? {
    //....
}
```
* UITableViewDelegate 메서드 중 하나를 사용하여 trailing부분에서 스와이프 할 경우 공유와 삭제가 표시되도록 구현하였습니다.
* 공유와 삭제의 경우 `UIContextualAction`를 통해 해당 기능 및 아이콘과 배경색을 수정하였습니다.
* 버튼 선택 이후 trailingSwipeAction이 종료될 수 있도록 각 버튼의 Action 핸들러 부분에 `completionHandler(true)`를 추가해주었습니다.

## 고민한 점

### 일기 생성 시 키보드가 자동으로 보이게 하는 시점
```swift
if state == .create {
    diaryTextView.becomeFirstResponder()
}
```
* 해당 로직을 어떠한 시점에서 사용해야 될지 고민했습니다.
* `viewDidLoad`, `viewWillAppear`, `viewDidAppear` 세 시점에서 해당 로직을 실행한 결과
* `viewDidLoad`와 `viewWillAppear`은 키보드가 빠르게 표시되지만 `Done`버튼이 존재하는 툴바가 늦게 표시되고 키보드도 부자연스럽게 표시되는 문제가 있었습니다.
* 따라서 `viewDidAppear` 시점에서 조금 늦게 표시되지만 자연스럽게 표시되도록 구현하였습니다.

### Update 시 날짜 업데이트 제외
- date를 업데이트 해주게 되면 옛날에 작성된 일기여도 수정 이후 가장 최신으로 sort 되어집니다.
- 메모가 아닌 일기장 앱이기 때문에 내용을 수정할때 date가 같이 수정되는 것이 부적절하다고 생각되었습니다.
- 이에 Update 시 content 부분만 업데이트 될 수 있도록 구현해주었습니다.

## 조언을 얻고 싶은 부분

### ActivityViewController present 시 콘솔창에 에러 출력
- 공유 버튼을 눌러 ActivityViewController를 띄워줄 경우 항상 에러가 출력되는 것을 볼 수 있었습니다.

```swift
2023-05-04 16:34:11.874055+0900 Diary[18117:1678977] [default] -imageForImageDescriptor: can do IO please adopt -imageForDescriptor: for IO free drawing or -prepareImageForDescriptor: if IO is allowed. (This will become a fault soon.)
2023-05-04 16:34:11.881150+0900 Diary[18117:1676763] [LayoutConstraints] Changing the translatesAutoresizingMaskIntoConstraints property of a UICollectionReusableView that is managed by a UICollectionView is not supported, and will result in incorrect self-sizing. View: <_UIActivityContentFooterView: 0x159f39600; baseClass = UICollectionReusableView; frame = (16 244.333; 361 52); layer = <CALayer: 0x600001997680>>
2023-05-04 16:34:13.860259+0900 Diary[18117:1677413] [ShareSheet] connection invalidated
```

- 레이아웃 관련 에러는 ActivityView 안에 존재하는 CollectionView의 레이아웃 문제로 보이는데, 이를 따로 수정해 줄 방법을 찾을 수가 없었습니다.
- 나머지 오류 관련해서도 정보를 찾을 수가 없어서 이를 해결해주지 못했습니다.
- 혹시 참고할 자료나 어떤 식으로 해결해줄 수 있는지 하비의 조언을 듣고 싶어요!

2023-05-04 08:30 UTC, havilog requested changes
코멘트 달고 보니 좀 많은 거 같은데 ...
화이팅 입니다..! :)

2023-05-04 08:30 UTC, havilog commented on Diary/Model/PersistenceManager.swift
> +    static var shared: PersistenceManager = PersistenceManager()
Q1. singleton을 사용했을 때
1. 단점을 서술하시오. (10점)
2. 장점을 서술하시오. (10점)
3. 어떤 근거를 가지고 사용했는지 서술하시오. (10점)

2023-05-04 08:30 UTC, havilog commented on Diary/Model/PersistenceManager.swift
> +       let container = NSPersistentContainer(name: "Diary")
Diary가 아닌 `Havi`, `KakiAbum` 두 객체를 더 코어데이터에 저장해야할 때 어떻게 확장해야 할지 고려해보셨는지 설명해주세요.

2023-05-04 08:30 UTC, havilog commented on Diary/Model/PersistenceManager.swift
> +                fatalError("Unresolved error \(error), \(error.userInfo)")
코어데이터에 로드를 실패하면 반드시 fatalError로 앱을 죽여야할까요?
안죽이고 다르게 핸들링 할 수 있는 방법도 고려해보셨는지 궁금해요.

2023-05-04 08:30 UTC, havilog commented on Diary/Model/PersistenceManager.swift
> +        }
try만 써도 될 거 같은데, do-catch로 감싸신 이유는 무엇일까요?

2023-05-04 08:30 UTC, havilog commented on Diary/Model/PersistenceManager.swift
> +    func createContent(_ content: String?, _ date: Double) throws -> Diary? {
date를 Double로 저장하신 이유가 무엇인가요?

2023-05-04 08:30 UTC, havilog commented on Diary/Model/PersistenceManager.swift
> +            throw error
코어데이터에서 발생한 에러인지 판단할 일이 있을 때 어떻게 판단하려고 생각하셨나요?

2023-05-04 08:30 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +        endEditingDiary()
뷰의 상태를 가지고 로직을 실행하는 건 위험해보여요.
유저의 액션 (닫기 버튼을 누른다던가...) 으로 endEditing을 실행할 수 있지 않을까요?

2023-05-04 08:30 UTC, havilog commented on Diary/Model/DiaryState.swift
> +    case delete
delete 상태값도 쓰이나요?

2023-05-04 08:30 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +    private var diaryItem: Diary?
non-nil value에서 다시 optional하게 바꾸신 이유는 뭔가요?

2023-05-04 08:30 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +        if diaryTextView.text.isEmpty { return }
요런 경우는 가드 문이 더 문맥에 잘 어울릴거 같아요

2023-05-04 08:30 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
>          }
Create와 Edit로직을 하나로 합칠 수 있을거 같이 생겼는데 (확실하지 않음),
도저히 안되서 이렇게 작성하신 건지, 시도를 안해본건지 궁금합니다~

2023-05-04 08:30 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +        }
> viewDidLoad와 viewWillAppear은 키보드가 빠르게 표시되지만 Done버튼이 존재하는 툴바가 늦게 표시되고 키보드도 부자연스럽게 표시되는 문제가 있었습니다.

ViewDidAppear에서 부르는 것에서는 이견 없습니다.
아래는 질문

1. Discussion은 읽어보셨을까요?
    <img width="484" alt="image" src="https://user-images.githubusercontent.com/57659933/236149835-b1a43009-e7eb-46fe-81b4-65704d0ad305.png">
2. RunLoop에 대해 설명해주세요.
3. ResponderChain에 대해 설명해주세요.

2023-05-04 08:30 UTC, havilog commented on Diary/Controller/DiaryViewController.swift
> +            diaryItems = try manager.fetchContent()
로드 시점에 안하고 윌어피어 시점에 작성하신 이유가 궁금합니다

2023-05-04 08:30 UTC, havilog commented on Diary/Controller/DiaryViewController.swift
> +    func tableView(_ tableView: UITableView, trailingSwipeActionsConfigurationForRowAt indexPath: IndexPath) -> UISwipeActionsConfiguration? {
함수 안에 너무 많은 역할이 있어서 읽기 힘들어요 ㅠㅠ

2023-05-04 08:30 UTC, havilog commented on Diary/Controller/DiaryViewController.swift
> +                self?.tableView.reloadData()
반드시 리로드를 찔러야할까요? 애니메이션을 주려면 어떻게 해야할까요?

2023-05-04 08:30 UTC, havilog commented on Diary/Etc/UIViewControllerExtention.swift
> +    func showFailAlert(error: Error) {
코어데이터와, 서버, 다른 무언가 세 개의 에러가 있을 때 어떻게 알럿을  띄울지도 고려해보시면 좋을 것 같아요

2023-05-04 08:30 UTC, havilog commented on Diary/View/DiaryInfoTableViewCell.swift
> +    private func parseContent(_ content: String) -> (String?, String?) {
튜플에도 레이블 달아주면 좋을거 같아요

2023-05-05 02:40 UTC, kak1x commented on Diary/Controller/DiaryViewController.swift
> +                self?.tableView.reloadData()
`performBatchUpdates` 와 `tableView.deleteRow` 를 사용하여 reloadData를 사용하지 않고 애니메이션이 보여질 수 있도록 수정하였습니다!

2023-05-05 02:40 UTC, fatherLeon commented on Diary/View/DiaryInfoTableViewCell.swift
> +    private func parseContent(_ content: String) -> (String?, String?) {
```swift
private func parseContent(_ content: String) -> (title: String?, body: String?) {
//...
}
```

* 튜플 레이블을 달아주었습니다.

```swift
let parsedContent = parseContent(content)
titleLabel.text = parsedContent.title
bodyLabel.text = parsedContent.body
```

* 레이블을 사용하게끔 `parseContent`메소드 또한 수정하였습니다.

2023-05-05 02:42 UTC, kak1x commented on Diary/Controller/DiaryViewController.swift
> +    func tableView(_ tableView: UITableView, trailingSwipeActionsConfigurationForRowAt indexPath: IndexPath) -> UISwipeActionsConfiguration? {
deleteContextualAction 부분에 있던 delete 관련한 부분을 `deleteTableViewItem` 메서드를 정의하여 나눠주었습니다.

2023-05-05 03:00 UTC, fatherLeon commented on Diary/Controller/DiaryDetailViewController.swift
> +        endEditingDiary()
```swift
NotificationCenter.default.addObserver(self, selector: #selector(endEditingDiary),  name: UIResponder.keyboardWillHideNotification, object: nil)
```

* 키보드 `Notification`으로 인해 뒤로가기 버튼을 누를 시 따로 설정을 안해줘도 저장되는 것을 확인하여 해당 `viewWillDisappear`을 지웠습니다!!

2023-05-05 03:08 UTC, kak1x commented on Diary/Model/PersistenceManager.swift
> +    func createContent(_ content: String?, _ date: Double) throws -> Diary? {
Step1에서 JSON 데이터를 파싱해서 사용했었는데, 이때 JSON에 있던 date가 Int 타입이었기에 이를 Double로 바꿔 이후 Date로 변환해줬습니다.
지금은 그냥 Date 타입으로 저장해줘도 상관없을 것 같아요!
Step3에서 Core Data 모델 변경 및 Migration 작업 진행하면서 이 부분도 Date로 바꿔주도록 하겠습니다.

2023-05-05 10:20 UTC, fatherLeon commented on Diary/Model/PersistenceManager.swift
> +       let container = NSPersistentContainer(name: "Diary")
여러가지 엔티티가 있을 경우 열거형을 사용하여 각 엔티티를 선택할 수 있게 해주고 CRUD부분에서 해당 열거형 객체를 통해 알맞은 엔티티 이름과 키값 등을 설정해 주면 될 것 같습니다.

2023-05-05 10:27 UTC, kak1x commented on Diary/Model/PersistenceManager.swift
> +        }
throws 를 통해 에러를 던져줄 수 있기 때문에 이 부분에선 do-catch문을 사용하지 않아도 되는데 이를 깜빡하고 try를 사용하기에 그냥 do-catch로 감싸줬네요..
수정했습니다!

2023-05-05 10:30 UTC, fatherLeon commented on Diary/Controller/DiaryDetailViewController.swift
> +    private var diaryItem: Diary?
* 따로 모델을 만들어주지 않고 엔티티 모델을 직접 사용함으로 인해 `Diary`객체의 직접적인 생성이 불가능했습니다.
* 일기 생성을 할 경우 빈 `Diary`객체를 넘겨줄 수 없었기 때문에 옵셔널로 변경하였습니다.

2023-05-05 10:33 UTC, kak1x commented on Diary/Controller/DiaryViewController.swift
> +            diaryItems = try manager.fetchContent()
첫번째 뷰컨으로 돌아올때마다 변경된 코어데이터를 조회해주는 과정이 필요한데, 첫 뷰컨은 앱을 실행할때만 로드되기 때문에 첫 뷰컨이 appear 될 때마다 이를 실행해주기 위해 윌어피어 시점에 작성하였습니다.

2023-05-05 10:43 UTC, fatherLeon commented on Diary/Model/DiaryState.swift
> +    case delete
* `keyboardWillHide` 노티피케이션이 존재하지 않을 때는 해당 상태 값에 따른 로직이 필요했었는데
* 현재는 필요하지 않아 삭제했습니다.

2023-05-05 10:54 UTC, kak1x commented on Diary/Model/PersistenceManager.swift
> +    static var shared: PersistenceManager = PersistenceManager()
1. 단점
- 싱글톤 인스턴스는 전역적으로 접근이 가능하기 때문에 다른 객체들과의 의존성이 높아질 수 있고 테스트가 어렵다는 부분이 있습니다.
2. 장점
- 하나의 인스턴스를 앱이 종료될때까지 전역적으로 접근하여 사용할 수 있기 때문에 접근성이 좋으며 여러 곳에서 인스턴스를 생성하는 것보다 메모리의 사용량을 줄일 수 있다는 장점이 있습니다. 뷰컨트롤러에서만 사용되지만, 여러 뷰컨트롤러에서 사용된다고 가정할 경우 뷰컨트롤러의 뎁스가 깊어짐에 따라 메모리에 관한 장점은 더욱 좋아질 것 같습니다.
3. 근거
- 모든 뷰컨트롤러에서 인스턴스를 따로 생성해주는 과정 없이 간단하게 접근하여 사용할 수 있기 때문에 사용했습니다.

2023-05-08 08:10 UTC, fatherLeon commented on Diary/Model/PersistenceManager.swift
> +                fatalError("Unresolved error \(error), \(error.userInfo)")
```swift
    private func getContext(completion: @escaping (Result<NSManagedObjectContext, NSError>) -> Void) {
        guard let container = self.container else {
            let container = NSPersistentContainer(name: "Diary")
            container.loadPersistentStores { _, error in
                if let error = error as NSError? {
                    completion(.failure(error))
                }
            }
            
            self.container = container
            completion(.success(container.viewContext))
            return
        }
        completion(.success(container.viewContext))
    }
```

* 위와 같이 escaping클로저를 받아 에러를 처리하도록 구현하였습니다.

2023-05-08 08:24 UTC, kak1x commented on Diary/Model/PersistenceManager.swift
> +            throw error
`CoreDataError`를 정의해주고 코어데이터에서 에러가 발생할 시 이 에러를 던져주게 변경하였습니다.

2023-05-08 08:27 UTC, fatherLeon commented on Diary/Controller/DiaryDetailViewController.swift
>          }
해당 부분은 `PersistentManager`에서 하나로 합치기에도 역할분리가 애매하고
뷰컨트롤러에서도 상황마다 행동이 다르기 때문에 하나로 합치기 힘들것 같습니다

2023-05-08 08:30 UTC, kak1x commented on Diary/Etc/UIViewControllerExtention.swift
> +    func showFailAlert(error: Error) {
`CoreDataError`의 경우 `LocalizedError` 프로토콜을 채택하여 해당 에러에 맞는 `errorDescription`를 설정해준 후 알럿에서 이 Description을 출력하게 해주었습니다.
다른 에러들의 경우에도 동일하게 `errorDescription`을 설정해주면 같은 알럿이 띄워져도 Description을 통해 어떤 에러인지 확인이 가능할 것 같습니다.

2023-05-08 09:31 UTC, fatherLeon commented on Diary/Controller/DiaryDetailViewController.swift
> +        }
### Discussion
* `becomeFirstResponder`의 경우 해당 뷰가 반응을 하지 못한다면 `Responder Chain`을 타고 상위뷰로 가는것이 아닌 반응이 없을 경우  `false`가 반환됩니다.
* 만약 현재 앱에서 텍스트 뷰가 아닌 `self.view`를 `firstResponder`를 부를 경우 하위 뷰인 텍스트뷰로 안가고 현재 뷰가 반응이 가능한지만 확인하고 불가능하니 `false`를 반환합니다

### RunLoop
* 입력 소스를 관리하는 쓰레드 내의 객체입니다.(+ 타이머)
* 저희 코드에서 입력소스는 키보드로 만약 키보드가 불려진다면 이는 입력소스이며, 비동기 이벤트로 메인쓰레드의 런 루프가 이벤트를 받습니다.
* 메인쓰레드의 런루프가 반응하여 메인쓰레드가 키보드를 그려주어 동작할 수 있게끔 작업 시점을 정해줍니다

### Responder Chain
* 기본적으로 앱은 `Responder` 객체를 통하여 이벤트를 받고 처리합니다.
* `Responder Chain`은 가장 적절한 이벤트를 처리하기 위해 가장 하위뷰부터 응답을 확인하고 적절한 응답이 있을 경우 해당 응답을 리턴해주고 적절한 응답이 없을 경우 상위 뷰로 이동하며 적절한 응답을 확인합니다.

2023-05-09 01:59 UTC, fatherLeon commented on Diary/Controller/DiaryDetailViewController.swift
> +        endEditingDiary()
```swift
extension DiaryDetailViewController: UINavigationControllerDelegate {
    func navigationController(_ navigationController: UINavigationController, willShow viewController: UIViewController, animated: Bool) {
        guard let diaryViewController = viewController as? DiaryViewController else { return }
        
        endEditingDiary()
        diaryViewController.fetchDiary()
    }
}
```

* `UINavigationControllerDelegate`를 통하여 만약 `DiaryViewController`로 이동할 경우 현재 수정중인 다이어리 저장 및 `DiaryViewController`에서 다이어리를 받아오도록 구현해주었습니다.

2023-05-09 10:54 UTC, havilog commented on Diary/Model/PersistenceManager.swift
> +    static var shared: PersistenceManager = PersistenceManager()
사실 개인적인 생각으로는 장점 중에 메모리에 대한 부분은.. 개발/사용에 있어서 크게 와닿는거 같지는 않아요..ㅎㅎ
제 생각에는 '편하다'가 가장 큰거 같아요.
하지만 의존성이 높아지고, 테스트 하기 어려운 코드가 되는 단점이 장점에 비해 크기 때문에 많이 사용안한다고 생각해요.

그래서 우리의 목표는 취업이고, 취업을 위해서는 싱글톤으로 사용하기 보다는,
해당 객체를 추상화해서 객체가 필요한 곳에 의존성 주입으로 넣어주는 방향을 고려해보는게 좋을거 같은데요,
dependency inversion prinsiple과 dependency injection에 대해 공부해보는것도 좋을 것 같아요

2023-05-09 10:58 UTC, havilog commented on Diary/Model/PersistenceManager.swift
> +                fatalError("Unresolved error \(error), \(error.userInfo)")
제가 코어데이터를 많이 사용해본 경험은 없어서 상상코딩이긴 한데요,
저 컨테이너를 CRUD마다 로드하는건 "엄청" 오버헤드가 심할거 같아요...
그래서 맨 처음 필요한 객체에 접근 때 코어데이터에 저장한 container를 한 번 로드하고,
그 컨테이너에 계속 접근해서 CRUD를 진행하는게 맞지 않을까 라는 생각이 드네요.

+ 로드에 실패했을 때는, 메모리가 부족하거나, 뭐 마이그레이션이 제대로 안됐다거나 등등
정말 코어데이터를 사용하지 못하는 상황일텐데요,
해당 경우에는 앱을 사용하지 못하니까 고객센터로 문의하라는 알럿을 띄우고 죽인다거나,
일기장으로 진입하지 못하게 막는 등 기획적인 부분이 필요할거 같아요.
각각의 경우에 어떻게 처리할 지에 대한 고민정도만 해보시면 좋을 것 같습니다.

2023-05-09 11:01 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +        endEditingDiary()
https://developer.apple.com/documentation/uikit/uiadaptivepresentationcontrollerdelegate/3229889-presentationcontrollerdiddismiss

요런 메소드를 사용해서 푸쉬된 화면이 dismiss하는 시점도 파악할 수 있을거 같아요

2023-05-09 11:03 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +    private var diaryItem: Diary?
어떠한 일기에 대한 빈 객체를 생성해주고 -> 저장할 때 객체가 유효하면 -> 해당 객체를 코어데이터에 저장할 모델로 변환한 뒤 -> 저장하는 플로우도 생각해볼 수 있겠네요
presentation layer에서 쓰일 모델과, Data layer에서 쓰일 모델이 반드시 같아야 하는건 아니긴 해서요

그냥 요런 방법도 있다는거고 틀렸다는건 아니니까 생각만 해보셔도 될거 같아요~

2023-05-09 11:06 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +        }
LGTM 👍 
화면을 터치했을 때 어떤 플로우로 액션을 인식해서 어떤 계층을 타고 누구에게 전달되는지에 대한 정리를 한 번 해보는것도 면접에 도움이 많이 될 것 같아요~

2023-05-09 11:09 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
>          }
이게 더 좋은 방법이라는 얘기는 아니구요,
update를 빈객체 혹은 nil인 객체로 찔렀을 때 현재 date를 넣어주면서 생성해줄 수도 있었을 거 같은데,
여러 방법을 비교해보고 근거를 채택해서 선택하는것도 좋을 것 같아요 ㅎㅎ
catch가 중복되니 switch state문을 throwing 함수로 뺄 수도 있겠네요 !

2023-05-10 02:15 UTC, kak1x commented on Diary/Model/PersistenceManager.swift
> +    static var shared: PersistenceManager = PersistenceManager()
알려주신 내용들 추후에 공부해볼게요!
확실히 장점에 비해 단점이 큰 것 같아 싱글톤을 해제해주었습니다.

2023-05-10 02:16 UTC, kak1x commented on Diary/Model/PersistenceManager.swift
> +                fatalError("Unresolved error \(error), \(error.userInfo)")
container를 한 번만 로드하게 변경해주었고 싱글톤을 해제해주며 AppDelegate에 있는 PersistentContainer를사용해주는 방식으로 변경하였습니다.

2023-05-10 02:56 UTC, fatherLeon commented on Diary/Controller/DiaryDetailViewController.swift
> +        endEditingDiary()
* NavigationControllerDelegate의 경우 `DiaryViewController`에 접근할 수 있지만 해당 델리게이트는 `DiaryViewController`에 접근할 수 없고 사용한다면 화면이 보여진 이후에 부자연스럽게 추가되는 문제가 있어서 구현만 따로 해보고 수정은 하지 않았습니다!!

2023-05-11 04:56 UTC, merged