일기장 [STEP 2] Harry, Rowan
yagom-academy/ios-diary pull request #104
Opened 2023-05-04 07:50 UTC by Kyeongjun2

# Step 2
안녕하세요 줄라이!
해리, 로웬 조 Diary Step2 PR 보내드립니다 🙌
학습 내용을 제시해주셔서 더 깊이 공부할 수 있었어요☺️ 
감사합니다! 👍👍👍

사전 학습 내용 - [CoreDataStack / App Life Cycle](https://hackmd.io/@Rowan/HJbrYyF73)

</br>

## 고민한 점
### 🔸 App Life Cycle Method
Scene Manifest가 적용된 프로젝트에서는 AppDelegate의 app life cycle 메서드는 호출되지 않고, SceneDelegate의 app life cycle 메서드가 호출됩니다.

따라서 앱이 백그라운드로 진입하는 경우 일기를 자동 저장하기 위해 SceneDelegate에서 `sceneDidEnterBackground` 메서드를 사용하였습니다.

</br>

### 🔸 SceneDelegate에서 최상단 뷰컨트롤러 얻기
SceneDelegate의 window 프로퍼티를 이용해 `rootViewController`(as UINavigationController) -> `topViewController`(as DiaryContentViewController) 순으로 최상위 뷰컨트롤러를 얻었습니다.

```swift
guard let navigationController = window?.rootViewController as? UINavigationController,
      let topViewController = navigationController.topViewController,
      let diaryContentViewController = topViewController as? DiaryContentViewController
else { return }
```

</br>

## 조언받고 싶은 점
### 🔸 뷰 컨트롤러 사이에서 주고 받는 데이터 타입
``` swift
public class Diary: NSManagedObject
```
현재 첫 번째 화면과 두 번째 화면 사이의 데이터를 위 ManagedObject 타입으로 전달하고 있습니다.

step1에서 갖고 있던 DiaryContents 타입을 중간 객체로 사용하여 두 번째 뷰컨트롤러에서 사용하고 있었는데 큰 의미 없이 Depth만 깊어진다고 생각하여 중간 객체를 삭제하고 직접 ManagedObject 객체를 전달하게 되었습니다.

ManagedObject 객체 자체를 전달하는 것이 일반적으로 사용되는 방법이 맞는지 궁금합니다. 🤔

</br>

### 🔸 updateDiary, createDiary 메서드 파라미터의 타입(코어데이터 매니져)

#### step1에서 사용하던 방식
``` swift
func updateDiary(data: DiaryContents)
func createDiary(data: DiaryContents)
```

#### step2에서 새롭게 바꾼 방식
```swift
func updateDiary(title: String?, body: String?, date: Double, id: UUID)
func createDiary(title: String, body: String, date: Double, id: UUID) -> Diary?
```

위의 [뷰 컨트롤러 사이에서 주고 받는 데이터 타입](#뷰-컨트롤러-사이에서-주고-받는-데이터-타입)에서 말씀드린 것처럼 뷰 컨트롤러에서 주고 받는 데이터의 타입을 **DiaryContents**(구조체)에서 **Diary**(NSManagedObject)로 변경했습니다.

이후 CoreData create / update 메서드를 호출할 때, 뷰 컨트롤러에서 Diary 타입을 직접 생성할 책임이 없다고 생각하였습니다. 따라서, 뷰 컨트롤러에서 NSManagedObject인 Diary 인스턴스를 직접 생성하여 전달하는 것보다 업데이트하거나 생성할 데이터를 하나씩 파라미터로 전달하기로 했습니다. 저희의 생각이 괜찮은 방향인지, 여쭤보고 싶습니다.

</br>

### 🔸 SceneDelegate or Notification
UIScene 클래스의 기본적으로 구현된 Notification에 scene life cycle과 관련된 것들이 있는 것을 확인하고 SceneDelegate 메서드와 UIScene Notification 중 어느 것을 사용해야 할 지 고민했습니다.

App이 백그라운드로 진입하는 경우 일반적으로 자주 사용하는 방법이 어떤 것인지 여쭤보고 싶습니다.

</br>

## 해결되지 않은 점
ActivityView ItemSource(ActivityView 최상단 프리뷰 부분)가 스텝 예제와 다르게 표시되는 부분을 해결하지 못했습니다.

#### 프로젝트 요구사항 이미지
<img src="https://i.imgur.com/HTm9zUT.png" width="300">

#### 프로젝트 요구사항과 다른 점
- "Options > 버튼"이 없는 문제
- "썸네일 이미지"가 기본 이미지인 문제
- "title", "type" 나타내는 문자 위치가 서로 바뀌어서 나는 문제

### 💭 시도한 방법
UIActivityItemSource 프로토콜을 채택하여 서브 클래스를 만들었습니다.
서브 클래스 내에서 아래 메서드를 구현해보았습니다.
``` swift
@available(iOS 13.0, *)
func activityViewControllerLinkMetadata(_: UIActivityViewController) -> LPLinkMetadata? {
   let metadata = LPLinkMetadata()
   metadata.title = title
   metadata.imageProvider = NSItemProvider(contentsOf: tumbnail)
   return metadata
}
```

뷰컨트롤러에서 다음과 같이 ActivityViewController를 초기화했습니다.
``` swift
let title = "My Title"
let thumbnail = UIImage(named: "myImage")
let activityItemSource = MyActivityItemSource(title: title, thumbnail: thumbnail!)
let activityViewController = UIActivityViewController(activityItems: [activityItemSource], applicationActivities: nil)
```

- 결과적으로 이미지와 제목은 잘 바뀝니다.
- 옵션 버튼을 달아주는 방법은 해결하지 못했습니다. 
- 제목과 공유하고자 하는 데이터 타입을 지정하는 것은 가능했으나 위 아래 순서가 뒤바뀌는 문제가 있었습니다.

2023-05-05 07:11 UTC, July911 requested changes

2023-05-05 07:11 UTC, July911 commented on Diary/Controller/DiaryContentViewController.swift
> +    private let alertFactory: DiaryAlertFactoryService = DiaryAlertMaker()
잘 읽히지 않는 것 같습니다. 
DiaryContentViewController 안에서는 alertFactory라고 불리는데 타입은 DiaryAlertFactoryService이고 음 
의도에 대하여 분명하게 설명부탁드립니다.

2023-05-05 07:11 UTC, July911 commented on Diary/CoreData/DiaryCoreDataManager.swift
> +    static var shared: DiaryCoreDataManager = DiaryCoreDataManager()
왜 이렇게 구현하셨을까요 ?
 코어데이터 말고 다른 데이터스토리지를 사용한다면 사용할 수 있을까요 ? 
 싱글톤일 이유는 무엇인가요 ?

2023-05-05 07:11 UTC, July911 commented on Diary/CoreData/DiaryCoreDataManager.swift
> +    private func saveContext() {
위치가 적절할까요 ?

2023-05-05 07:11 UTC, July911 commented on Diary/CoreData/DiaryCoreDataManager.swift
> +        if let diaryEntity {
이런식의 흐름이면 guard문이 더 적절할 것 같습니다.

2023-05-05 07:11 UTC, July911 commented on Diary/CoreData/DiaryCoreDataManager.swift
> +    func updateDiary(title: String?, body: String?, date: Double, id: UUID) {
다이어리말고 다른걸 들어오게 할 순 없을까요 ?

2023-05-05 07:11 UTC, July911 commented on Diary/View/DiaryListCell.swift
> +        guard let title else { return }
너무 복잡합니다. 함수에 옵션이 너무 많이 붙어있습니다. 
인터페이스를 사용하는쪽에서 본다면 title에 nil이 들어가면 나머지 두 값과 관련없이 리턴됩니다. 
조금 더 사용하는쪽에서 명확하게 사용할 수 있게 한다면 어떻게 해야할까요 ?

2023-05-05 07:11 UTC, July911 commented on Diary/Controller/DiaryContentViewController.swift
> +    private func devide(text: String?) -> DiaryText {
내부에서만 사용하는 메서드는 조금 더 친절해도 되지 않을까요 ?

2023-05-05 07:11 UTC, July911 commented on Diary/Controller/DiaryListViewController.swift
> +        let nextViewController = DiaryContentViewController(diary: diary)
nextViewController는 너무 모호한거같습니다.

2023-05-05 07:11 UTC, July911 commented on Diary/Controller/DiaryListViewController.swift
> +
비슷하게 생긴 2개의 action이 있는데 히나로 뺄 수 있을까요 ?

2023-05-05 07:11 UTC, July911 commented on Diary/Model/DiaryContents.swift
> +final class DiaryContents {
어디서 쓰이나요 ?

2023-05-08 08:37 UTC, HarryHyeon commented on Diary/Controller/DiaryContentViewController.swift
> +    private let alertFactory: DiaryAlertFactoryService = DiaryAlertMaker()
저희가 의도치 않은 실수 인것 같습니다... 
뷰컨트롤러에서 alertMaker로 불리도록 수정해주었고,
AlertData와 Alert을 생성해주는 프로토콜 이름을 각각 AlertDataFactory, AlertFactory 라고 변경해주었습니다.

2023-05-08 08:41 UTC, Kyeongjun2 commented on Diary/CoreData/DiaryCoreDataManager.swift
> +    static var shared: DiaryCoreDataManager = DiaryCoreDataManager()
좀 더 범용적으로 사용하기 위해 DataAccessObject, DataTransferObject 프로토콜을 정의하고 ManagedObject Entity가 늘어나도 타입만 명시해주면 사용할 수 있도록 수정했습니다.

이에 따른 변경사항은 아래와 같습니다.

1. DiaryCoreDataManager 타입 이름을 CoreDataManager로 수정
2. CoreDataManager 타입 이름을 CoreDataStack으로 수정

네이밍에 맞는 기능을 하도록 고민하여 수정했습니다.

또한, 코어데이터 이외의 다른 데이터 스토리지를 사용하게 된다면 Respository Protocol을 새로 정의해 CoreDataManager의 인터페이스를 추상화할 수 있을 것 같습니다. 👍

2023-05-08 08:42 UTC, HarryHyeon commented on Diary/CoreData/DiaryCoreDataManager.swift
> +    private func saveContext() {
엔티티와 도메인 모델을 추상화하면서 CoreDataStack에서 기능하도록 수정했습니다 👍🏼

2023-05-08 08:46 UTC, Kyeongjun2 commented on Diary/CoreData/DiaryCoreDataManager.swift
> +        if let diaryEntity {
```swift
func createDAO<DAO: DataAccessObject, Domain: DataTransferObject>(type: DAO.Type, from data: Domain) {
        guard let entityName = DAO.entity().name,
// ...
```

DAO를 추상화하면서 각 타입에 맞는 entity name을 반환할 수 있도록 수정해줬습니다!

2023-05-08 08:48 UTC, HarryHyeon commented on Diary/CoreData/DiaryCoreDataManager.swift
> +    func updateDiary(title: String?, body: String?, date: Double, id: UUID) {
이 부분도 엔티티와 도메인 모델 추상화로 해결했습니다 !

2023-05-08 08:50 UTC, Kyeongjun2 commented on Diary/View/DiaryListCell.swift
> +        guard let title else { return }
Diary 타입을 직접 파라미터의 전달인자로 받을 수 있도록 수정하여 호출 시 좀 더 명확하게 사용할 수 있게 된 것 같습니다 👍

```swift
func configureLabels(with diary: Diary) {
// ...
```

2023-05-08 08:50 UTC, HarryHyeon commented on Diary/Controller/DiaryContentViewController.swift
> +    private func devide(text: String?) -> DiaryText {
줄라이 말씀대로 인터페이스와 내부에서 쓰이는 메서드라는 쓰임새를 고려하여 네이밍 하는 것을 고민했습니다.
devideTitleAndBody로 메서드명을 수정했습니다 !

2023-05-08 08:52 UTC, Kyeongjun2 commented on Diary/Controller/DiaryListViewController.swift
> +        let nextViewController = DiaryContentViewController(diary: diary)
`diaryContentViewController` 로 변경했습니다 😅

2023-05-08 08:52 UTC, HarryHyeon commented on Diary/Controller/DiaryListViewController.swift
> +
UIContextualAction을 리턴해주는
``` swift
private func makeContextualAction(
        style: UIContextualAction.Style,
        imageName: String,
        color: UIColor,
        completion: @escaping () -> Void
    ) -> UIContextualAction
```
메서드를 새롭게 정의했습니다 !

2023-05-08 08:54 UTC, Kyeongjun2 commented on Diary/Model/DiaryContents.swift
> +final class DiaryContents {
Diary로 이름을 변경하여 Domain Model로 사용하였습니다.

2023-05-08 09:57 UTC, merged