다이어리 [STEP 2] 릴라, 송준
yagom-academy/ios-diary pull request #105
Opened 2023-05-04 09:38 UTC by kimseongj

# 다이어리 [STEP 2] 릴라, 송준

@lina0322
안녕하세요 엘림 드디어 두 번째 스텝 완료하여 PR 보냅니다!
이번 스텝도 잘 부탁드립니다 🙏🏻

## 구현한 점 
- ActionSheet / Alert 
    - ActionSheet를 사용하여 삭제 / 공유 기능 삽입
- ActivityViewController
    - ActivityViewController를 사용하여 일기 공유 기능 구현
- CoreData
    - CoreData의 CRUD 기능 구현

## 고민한 점

### 1️⃣Entity 의 모델로 변환 

DataModel의 Entity 를 `NSManagedObject` 를 상속받는 타입으로 관리를 하고있습니다. 
저희의 경우 해당 Entity 를 Model 로 변환해주는 작업을 거치고 있는데 사용을 하다보니 Entity 에도 똑같은 요소들이 있는데 굳이 변환을 해서 사용을 해야하나 라는 고민이 생겼습니다.

```swift
 private func convertToDiaryModel(for entities: [DiaryEntity]) -> [Diary] {
        let diaries = entities.map { entity in
            Diary(id: entity.id,
                  title: entity.title ?? "",
                  body: entity.body ?? "",
                  timeIntervalSince1970: Int(entity.timeIntervalSince1970))
        }
        
        return diaries
    }
```

엘림의 경우 Entity 를 모델로 한번 변환 해주는것에 대해 어떻게 생각하시나요?

### 2️⃣공통 Alert에 대한 관리

`DiaryVC` 와 `DiaryDetailVC` 에서 삭제와 공유에 대한 Alert 을 똑같이 사용을 하고 있습니다. 반복된 코드 작성 없이 Alert 만을 담당하는 객체가 있으면 편하겠다 싶어 AlertManager 객체를 만들게 되었는데요,

별도의 객체로 관리를 하다보니 ViewController 와 data 를 받게되는 형태를 띄게 되었습니다. 

```swift
    static func presentActivityView(diary: Diary?, at viewController: UIViewController?) {
        guard let validDiary = diary else { return }
        let activityViewController = UIActivityViewController(activityItems: [validDiary.sharedText], applicationActivities: nil)
        activityViewController.popoverPresentationController?.sourceView = viewController?.view
        
        viewController?.present(activityViewController, animated: true, completion: nil)
    }
```

여기서 고민인 부분은 Alert을 present 하는건 ViewController가 주체인데 외부에서 ViewController 를 받아와서 present 시키는 것이 적절한 방법인지 고민이 됩니다!

### 3️⃣CoreData의 Create 와 Update 의 병합

CoreData 의 `CRUD` 를 구현하는 과정에서 `Create` 와 `Update` 의 구성이 비슷하다고 생각을 해 하나의 메서드로 같이 사용할 수 있지 않을까 생각을 했고 병합을 해보았습니다.

```swift
    func register(_ diary: Diary) {
        let context = persistentContainer.viewContext
        guard let entity = NSEntityDescription.entity(forEntityName: DiaryKey.EntityName, in: context) else { return }
        let fetchRequest: NSFetchRequest<NSFetchRequestResult> = NSFetchRequest.init(entityName: DiaryKey.EntityName)
        fetchRequest.predicate = NSPredicate(format: "id == %@", diary.id as CVarArg)
        
        let fetchedObject = try? context.fetch(fetchRequest)[safe: 0] as? NSManagedObject ?? NSManagedObject(entity: entity, insertInto: context)
        
        setNSDiaryValue(for: diary, at: fetchedObject)
        
        saveContext()
    }
```

 diary의 id를 기준으로 해당 id 의 저장된 값 유무를 구별해 fetchedObject 에 알맞는 NSManagedObject 를 할당 하도록 했습니다.

- 있는 경우(Update)
```swift
context.fetch(fetchRequest)[safe: 0] as? NSManagedObject
```

- 없는 경우(Create)
```swift
NSManagedObject(entity: entity, insertInto: context)
```

다만 한가지 아쉬운 점은 최대한 병합을 하려다 보니 코드 한줄한줄이 굉장히 길어지게 되었고 가독성이 조금 떨어진 것 같다는 생각이 듭니다.

이 부분에서 혹시 개선할 수 있는 부분이 있다면 엘림 의견을 좀 나눠주세요! 🙇🏻‍♂️

### 4️⃣DiaryDetailViewController 공용 사용

현재 저희의`DiaryDetailViewController`는 새롭게 일기를 쓸 때와 이미 저장되어 있는 일기를 불러올 때, 두가지 형태로 표현되도록 구현되어있습니다. 
`ViewController` 내부에서 분기처리를 통해 두 가지 형태로 표현되는데, 두 개의 ViewController로 구현하는게 좋을지, 여러 분기처리를 통해 하나의 `ViewController`를 재사용성 있게 사용하는게 좋을지 고민되었습니다! 어떤 방식이 좋을까요??

- 두 개의 ViewController로 구현할 경우
    - 코드의 가독성이 비교적 좋아진다.
- 하나의 ViewController로 구현할 경우 
    - 재사용성? 측면에서 두 개의 ViewController를 사용하는 것보다 효율적이다.

### 5️⃣DiaryDetailVC 에서 CoreData로의 저장조건

현재 `새로이 생성하는 일기`와` 기존의 일기`를 보여주는 VC 를 하나의 VC 로 같이 사용을 하고 있습니다. 그래서 어떤 일기냐에 따라 저장 조건 또한 달라졌기에 분기처리를 고민하느라 시간을 많이 잡아 먹었습니다.

저희가 정리한 저장조건은 다음과 같습니다.

- 기존에 있던 일기를 보여주는 VC 는 어떤 변화가 일어나도 CoreData에 저장을 한다.
- 기존에 있던 일기의 내용이 다 지울 경우 마지막으로 지우기 전의 내용을 CoreData에 저장한다.
- 신규 일기는 내용이 하나라도 들어갔다면 CoreData에 저장을 한다.
- 신규 일기가 만약 아무런 내용이 없다면 CoreData에 저장하지 않는다
- 신규 일기의 내용에 공백만 있다면 저장하지 않는다.

하나의 ViewController 에서 모든걸 해결하려다 보니 가독성 부분에서 떨어지는 점을 체감을 하네요,,,!

2023-05-06 15:22 UTC, lina0322 requested changes
고민한 점
---
### 1. Entity
같은 내용이라면, 굳이 따로 들고있을 필요가 있을까요?🤔

### 2. 공통 Alert
코멘트 남겼습니다. 지금 방식이 적절하지 않다기보다는, 더 좋은 방법이 있을 것 같아요! UIViewController와 관련해서..ㅎㅎ

### 3. CoreData의 Create 와 Update 의 병합
개인적으로 이쪽 코드 복잡해서 잘 읽히지 않더라고요. 병합을 해야하는 이유가 있을까요? 따로 가는건 어떨까요.
사실 여러분이 짠 코드이기 때문에 어떻게하면 더 좋은 코드가 될지는 여러분이 더 잘 알 수 있답니다.
다만 복잡해진다고 여러분이 느낀거라면ㅎㅎ 뭔가 개선이 필요할 것 같네요.🤔

### 4. DiaryDetailViewController
두 개로 가면 중복된 코드가 많이 있겠네요? 그래서 하나를 생각하시는 것 같고요ㅎㅎ
저는 요런 화면 예전에 하나로 작업하긴 했었습니당!
근데 지금 생각해보면, 상속이나 protocol 등을 활용하는건 어떨까 싶네요

### 5. DiaryDetailVC 에서 CoreData로의 저장조건
> 하나의 ViewController 에서 모든걸 해결하려다 보니

전 이 말이 참 중요한 부분인 것 같은데요. 어떤 방식으로 해결하면 좋을까요!!!🥹

----

고생하셨습니당! 항상 편하게 메세지 주세용~ 😉

2023-05-06 15:22 UTC, lina0322 commented on Diary/Controller/DiaryDetailViewController.swift
> +        }
saveDiaryToStorage를 호출하고 내부에서 isSave를 가지고 판단하는건 어떨까요?
개인적으로는 창을 닫는 타이밍(창을 닫는 메서드)에 체크하는게 더 맞지 않을까 생각이 들긴해요

2023-05-06 15:22 UTC, lina0322 commented on Diary/Controller/DiaryDetailViewController.swift
> +        }
```suggestion
        writeMode = diary == nil ? .create : .update
```

이런건 어떨까요??

2023-05-06 15:22 UTC, lina0322 commented on Diary/Controller/DiaryDetailViewController.swift
>          }
여전히 self의 사용이 모호해보여요. 명확하게 쓸곳과 안 쓰는 곳을 정하면 좋을거같아요
또 validDiary의 timeIntervalSince1970 호출해서 convertFormattedDate을 다시 한 번 하는 것 보다,
validDiary.titleText, validDiary.formattedDateText 등 한번에 접근할 수 있도록 하는건 어떨까요?

2023-05-06 15:22 UTC, lina0322 commented on Diary/Controller/DiaryDetailViewController.swift
> +        let shareActionSheet = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)
presentActionSheet를 사용하면서 어려움은 없었나요?👀

2023-05-06 15:22 UTC, lina0322 commented on Diary/Controller/DiaryDetailViewController.swift
> +            AlertManager.presentDeleteAlert(diary: self?.diary, at: self) { _ in
여기엔 [weak self] 안붙여도 되나요??

2023-05-06 15:22 UTC, lina0322 commented on Diary/Controller/DiaryDetailViewController.swift
> +        guard let title = components[safe: 0] else { return }
[safe: 0]도 있지만, first나 last를 사용할 수 있는 경우엔 그것을 사용하는게 더 좋아보여요(개인적으로!)

2023-05-06 15:22 UTC, lina0322 commented on Diary/Controller/DiaryViewController.swift
> +        return UISwipeActionsConfiguration(actions: [delete, share])
여기 내부도 함수로 분리해주세요~

2023-05-06 15:22 UTC, lina0322 commented on Diary/Model/Diary.swift
> +    let id: UUID
요거 왜 UUID 생성해주는 거에서 타입으로 하는 걸로만 하셨나용?👀

2023-05-06 15:22 UTC, lina0322 commented on Diary/Model/Diary.swift
> +    var sharedText: String { title + "\n\n" + body }
```suggestion
    var sharedText: String {
        return title + "\n\n" + body 
    }
```

연산 프로퍼티는 한줄로 잘 안쓰는거 같아요!
return 붙이고 안붙이는건 취향차이 같고용ㅎㅎ

2023-05-06 15:22 UTC, lina0322 commented on Diary/Util/CoreData/DiaryEntity+CoreDataClass.swift
> +}
이것은 어떤 기능을 하고있나요?

2023-05-06 15:22 UTC, lina0322 commented on Diary/Util/Extension/Date+Extension.swift
> +        let dateFormatter = DateFormatter()
DateFormatter가 함수가 호출 될 때 마다 생성되기엔 무거운 작업이에요.
지난번에 찾아보라고 말씀드렸었는데ㅎㅎ 제가 원했던 방향은 아니고, 다시 한번 찾아볼까요?!

2023-05-06 15:22 UTC, lina0322 commented on Diary/Util/Extension/Date+Extension.swift
> +        let date = Date()
그리고 지금 그냥 convertDateInterval이 아니라, currentDate 같네용

2023-05-06 15:22 UTC, lina0322 commented on Diary/Util/Extension/String+Extension.swift
> +    }
LGTM👏
그런데 static으로 할 이유가 있나요?🤔

2023-05-06 15:22 UTC, lina0322 commented on Diary/Util/Extra/AlertManager.swift
> +    static func presentActivityView(diary: Diary?, at viewController: UIViewController?) {
static으로 가지않고, 어짜피 해당하는 UIViewController에서 open하는 거라면, UIViewController자체가 들고있는건 어떨까요? 어떤 방식이 있을까요ㅎㅎ

2023-05-06 15:22 UTC, lina0322 commented on Diary/Util/Extra/AlertManager.swift
> +final class AlertManager {
Diary와 관련된 화면이라서, 만약에 이대로 진행한다면 DiaryAlertManager 등으로 가는게 낫겠어요

2023-05-08 13:25 UTC, juun97 commented on Diary/Controller/DiaryDetailViewController.swift
> +        }
saveDiaryToStorage 메서드 내부에서 isSave 를 기준으로 판단하는 식으로 변경햇습니다!

2023-05-08 13:33 UTC, kimseongj commented on Diary/Controller/DiaryDetailViewController.swift
> +        }
삼항연산자를 사용해서 수정했습니다!
a90c01243f4ac39f83d9b02a5587fd013bb46d6e

2023-05-08 13:33 UTC, juun97 commented on Diary/Controller/DiaryDetailViewController.swift
> +            AlertManager.presentDeleteAlert(diary: self?.diary, at: self) { _ in
가장 바깥에 있는 escaping closure 에서 [weak self] 를 한경우
내부에 중첩된 escaping closure 에서 자신을 참조할 때 self 가 옵셔널이었기에 약한참조가 되어있는걸로 생각을 했습니다.

혹시 이런 경우 모든 escaping closure [weak self]  를 호출하지 않으면 강한순환참조가 발생할 수 있을까요?

2023-05-08 13:34 UTC, juun97 commented on Diary/Controller/DiaryDetailViewController.swift
> +        guard let title = components[safe: 0] else { return }
좋은 메서드를 두고 활용을 하지 못하고 있었네요! 저도 그방법이 되게 깔끔하다고 생각해서 수정 했습니다 !

2023-05-08 13:45 UTC, juun97 commented on Diary/Util/Extension/Date+Extension.swift
> +        let dateFormatter = DateFormatter()
fbfee97de2f8717e72c938d1ea2f54ad80b90fe9

[DiaryFormatter 공식문서](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DataFormatting/Articles/dfDateFormatting10_4.html#//apple_ref/doc/uid/TP40002369-SW10) 에서 DateFormatter 의 생성이 저렴한 작업이 아니란걸 알게 되었습니다.

기존 로직에서는 메서드마다  DateFormatter의 인스턴스를 생성하고 있었기에 많은 cost 를 차지하고 있었습니다. 

이를 개선하기 위해  `DateFormatter 의 생성횟수를 단 한번`으로 제한하기 위해 `싱글톤 디자인 패턴`을 사용한 DiaryDateFormatter 타입을 생성했습니다.

2023-05-08 13:46 UTC, kimseongj commented on Diary/Controller/DiaryDetailViewController.swift
>          }
`self`의 경우 메서드 내부에 프로퍼티명이 겹칠 경우, 꼭 필요한 경우(자기 자신을 지칭할 때, Completion Handler에서 프로퍼티 및 메서드가 사용될 때)에만 작성하고, 불필요한 `self`를 전부 삭제하는 방향으로 리팩토링했습니다.

또한, validDiary.formattedDateText으로 수정하였습니다!
3d6e6883fe483343075d5a9629a23ead237c10c2

2023-05-08 13:47 UTC, juun97 commented on Diary/Util/Extra/AlertManager.swift
> +    static func presentActivityView(diary: Diary?, at viewController: UIViewController?) {
fbfee97de2f8717e72c938d1ea2f54ad80b90fe9

UIViewController를 extension 해 공통으로 쓰이는 Alert 메서드를 정의하였습니다! 
이렇게 하니 UIViewController를 외부에서 받아올 필요도 없어지게 되고 모든 UIViewController 에서도 Alert을 사용할 수 있게 되었습니다!

2023-05-08 13:48 UTC, kimseongj commented on Diary/Model/Diary.swift
> +    var sharedText: String { title + "\n\n" + body }
3d6e6883fe483343075d5a9629a23ead237c10c2
`return` 명시하고, 라인을 분리했습니다!

2023-05-08 14:13 UTC, juun97 commented on Diary/Util/Extension/Date+Extension.swift
> +        let date = Date()
메서드의 네이밍과 전달인자 레이블을 활용해 수정했습니다 !

2023-05-08 14:14 UTC, juun97 commented on Diary/Util/Extension/String+Extension.swift
> +    }
static빼고 저희가 정의한 LocalizationKey 의 항목에서 바로 해당 메서드를 이용할 수 있도록 수정했습니다

2023-05-08 14:14 UTC, juun97 commented on Diary/Util/Extra/AlertManager.swift
> +final class AlertManager {
해당 기능을 extension 을 활용하면서 삭제 하게 되었습니다

2023-05-08 14:15 UTC, kimseongj commented on Diary/Util/Extra/AlertManager.swift
> +final class AlertManager {
fbfee97de2f8717e72c938d1ea2f54ad80b90fe9
Alert를 구현하는 메서드들을 UIViewController에 extension해서 AlertManager 클래스는 필요가 없어졌습니다.

2023-05-08 14:15 UTC, juun97 commented on Diary/Controller/DiaryViewController.swift
> +        return UISwipeActionsConfiguration(actions: [delete, share])
a7014b9f2fdd748f1a83a3ae3f7aa39bf7059e85

Action 을 만들어주는 메서드로 분리했습니다

2023-05-08 14:17 UTC, kimseongj commented on Diary/Controller/DiaryDetailViewController.swift
> +        let shareActionSheet = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)
음... 구현하는데 있어 어려움은 없었던거 같습니다! 혹시 유의 깊게 봐야하는 부분이 있을까요?!

2023-05-08 14:21 UTC, juun97 commented on Diary/Model/Diary.swift
> +    let id: UUID
DetailVC 에서 외부 주입받은 Diary 의 유무에 따라 Diary 를 인스턴스화 할 때 새로 생성해서 주거나 받아온 id를 주거나 하게 되어있습니다.

```swift
final class DiaryDetailViewController: UIViewController {
    private var id = UUID()
    //...

    private func configureUI() {

        switch writeMode {
        case .create:
           //...
        case .update:
            //...
            id = validDiary.id
        }
    }
}
```

만약 Diary 내부에서 UUID 를 생성해주게 되면 현재 저희코드에서는 특정 diary 를 식별할 수가 없어서 UUID 를 외부주입 하는식으로 변경했습니다

2023-05-08 14:23 UTC, juun97 commented on Diary/Controller/DiaryDetailViewController.swift
> +        let shareActionSheet = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)
음... 단순하게 Action 들을 만들어주고 추가해준 코드들이었는데.. 엘림이 보셨을 땐 어색함이 있으셨나요?

아직 저희들의 눈이 개안이 되지 않아 잘 보이질 않습니다... 🥲

2023-05-08 14:50 UTC, kimseongj commented on Diary/Util/CoreData/DiaryEntity+CoreDataClass.swift
> +}
Core Data 모델의 동작을 구현하는 클래스로, 엔티티 내부의 프로퍼티와 메서드를 구현합니다!
(`NSManagedObject`클래스를 상속 받음)

2023-05-09 01:37 UTC, juun97 commented
> 1. Entity
같은 내용이라면, 굳이 따로 들고있을 필요가 있을까요?🤔

저희가 생각했을 때 Entity 는 코어데이터의 레이어의 해당하는 쪽이라 코어데이터 영역이 아닌 다른곳에서 Entity 를 접근하는게 코드를 계층적으로 보았을 때 어울리지 않아 보였습니다.

지금은 Diary 만의 추가적인 기능이 존재하지만 코어데이터로 저장하려는 모델과 엔티티가 기능면으로 다른점이 없을 때 엘림의 경우는 엔티티만 사용하시나요?

>2. 공통 Alert
코멘트 남겼습니다. 지금 방식이 적절하지 않다기보다는, 더 좋은 방법이 있을 것 같아요! UIViewController와 관련해서..ㅎㅎ

아래 코멘트를 보며 UIViewController에 extension하여 Alert를 구현하는 방식을 채택하였습니다! UIViewController에  extension을 하게 되었을 때, 장점은 `UIViewController`를 채택하는 모든 ViewController에서 Alert를 구현할 수 있다는 점, ViewController를 파라미터로 받을 필요가 없다는 점 등이 있었습니다. 
>3. CoreData의 Create 와 Update 의 병합
개인적으로 이쪽 코드 복잡해서 잘 읽히지 않더라고요. 병합을 해야하는 이유가 있을까요? 따로 가는건 어떨까요.
사실 여러분이 짠 코드이기 때문에 어떻게하면 더 좋은 코드가 될지는 여러분이 더 잘 알 수 있답니다.
다만 복잡해진다고 여러분이 느낀거라면ㅎㅎ 뭔가 개선이 필요할 것 같네요.🤔

Create 와 Update 를 나눠서 코드가 좀 늘어나더라도 명시적으로 확인할 수 있게 했습니다.

저희가 Create와 Update 를 나눈 큰이유가 사용하는 쪽에서 분기처리가 많아져서 CoreDataMangaer 내부에서 분기처리를 진행하였는데, CoreDataManager 에서 search 라는 특정 ID 의 값 유무를 판단해주는 메서드를 만듬으로 좀 더 가시적인 분기처리를 진행했습니다.

>4. DiaryDetailViewController
두 개로 가면 중복된 코드가 많이 있겠네요? 그래서 하나를 생각하시는 것 같고요ㅎㅎ
저는 요런 화면 예전에 하나로 작업하긴 했었습니당!
근데 지금 생각해보면, 상속이나 protocol 등을 활용하는건 어떨까 싶네요

결국에는 두 화면이 같은 UI 요소를 지니고 있었기에 커스텀뷰를 만들어서 VC에서 각각 해당 View 를 호출 하는방법을 사용해 보려했는데, 생각해보니 공유하는 UI 가 TextView 하나였기에 기존방법처럼 하나의 VC 로 사용하기로 결정했습니다.

>5. DiaryDetailVC 에서 CoreData로의 저장조건
하나의 ViewController 에서 모든걸 해결하려다 보니
전 이 말이 참 중요한 부분인 것 같은데요. 어떤 방식으로 해결하면 좋을까요!!!🥹

지금 저희 VC 같은경우 가독성이 떨어지는 분기처리들이 존재했었기에 저희가 사용한 방법은

1. 메서드의 기능 분리
2. 분기처리 시점 수정
3. Diary의 연산프로퍼티 활용

위와 같은 방법을 사용해 리팩토링을 진행해 보았습니다.

2023-05-09 01:42 UTC, lina0322 commented on Diary/Controller/DiaryDetailViewController.swift
> +        let shareActionSheet = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)
아 혹시 패드도 작업하시나요??

2023-05-09 01:45 UTC, lina0322 commented on Diary/Controller/DiaryDetailViewController.swift
> +            AlertManager.presentDeleteAlert(diary: self?.diary, at: self) { _ in
저도 같은 이유로 사용하지 않고 있습니다ㅎㅎ 알고 계시는지 궁금했습니다!

2023-05-09 01:49 UTC, lina0322 commented on Diary/Util/Extension/Date+Extension.swift
> +        let dateFormatter = DateFormatter()
👏좋습니다!
https://sarunw.com/posts/how-to-use-dateformatter/
이건 글들 참고해보면 좋을 것 같아요!!

2023-05-09 04:38 UTC, lina0322 commented
> Entity
지금은 Diary 만의 추가적인 기능이 존재하지만 코어데이터로 저장하려는 모델과 엔티티가 기능면으로 다른점이 없을 때 엘림의 경우는 엔티티만 사용하시나요?

흠, 저는 같은 모델이라면 같이 사용할 것 같습니다. 만약에 코어데이터와 관련된 부분이 있으면, extension으로 따로 그 부분만 구현해주는 것도 방법일 것 같아요. 하지만 코드엔 항상 정답이 없기 때문에, 하다보니 기능들이 너무 많아서 코어데이터만 분리해야겠다 라고 생각할수도있고, 전체 모델 안에서 코어데이터용 모델을 들고있을 수도 있고, 다양한 방법을 고민해보면 좋을것 같아요

> 공통 Alert
아래 코멘트를 보며 UIViewController에 extension하여 Alert를 구현하는 방식을 채택하였습니다! UIViewController에 extension을 하게 되었을 때, 장점은 UIViewController를 채택하는 모든 ViewController에서 Alert를 구현할 수 있다는 점, ViewController를 파라미터로 받을 필요가 없다는 점 등이 있었습니다.

저는 개인적으로 이렇게 extension으로 사용하고 있습니다. 다만, 모든 viewController가 들고있어야 할 필요가 있느냐?에 대해서는 생각을 또 해보면 좋을 것 같아요. 따로 이런 부분에 대해서 procotol을 사용해서 alert가 필요함을 보여주고, extension에서 where을 사용해서 필요한 부분에만 적용될 수 있도록 할수도 있고요ㅎㅎ 다양한 관점이 있으니 항상 이것이 정답이다! 이런건 아니라는걸 알아주셨으면 해요~

----

이번 스텝도 정말 고생 많으셨습니다~🫡
추가적인 부분은 다음 과제와  함께 개선해봅시다

2023-05-09 04:38 UTC, lina0322 approved these changes

2023-05-09 04:39 UTC, merged