일기장 [STEP2] sehong
yagom-academy/ios-diary pull request #106
Opened 2023-05-05 03:31 UTC by sehoong0429

# 일기장 step2 
@havilog 
안녕하세요 하비! 세홍입니다.
step 2 구현 마무리가 늦어져서 이제 제출합니다.
이해해야하는 부분이 너무 많아서 힘들었던 스탭이었습니다.🥲
이번에 commit을 처음부터 단위별로 나눠서 진행하지 못했습니다. 
이부분 신경써서 진행하도록 하겠습니다. 죄송합니다ㅠㅠ

미리 감사드립니다..! 🙇🏻‍♀️

## 구현한 내용 
- 코어데이터 모델 생성
- 일기장 CRUD 구현
- 리스트 화면에서 + 버튼 누르면 일기생성
- 리스트 화면의 기존 데이터 선택시 일기편집
- 일기 자동저장구현 
    1. 사용자 입력 멈추는경우(키보드 사라지는 경우)
    2. 백그라운드 진입시
    3. 이전화면으로 이동시
- 더보기 버튼 누르면 공유-삭제 액션시트 보여주기
- 리스트 셀 스와이프시 공유 및 삭제 기능 표시

## 🔗 참고링크
- [Core Data](https://developer.apple.com/documentation/coredata)
- [Making Apps with Core Data](https://developer.apple.com/videos/play/wwdc2019/230/)
- [UITextViewDelegate](https://developer.apple.com/documentation/uikit/uitextviewdelegate)
- [UISwipeActionsConfiguration](https://developer.apple.com/documentation/uikit/uiswipeactionsconfiguration)
- [How to implement "share button" in Swift](https://stackoverflow.com/questions/37938722/how-to-implement-share-button-in-swift)
- [Activity View Controller](https://www.zehye.kr/ios/2020/03/12/12iOS_activity_view_controller/)
- [DeleteAllCoreData](https://stackoverflow.com/questions/24658641/ios-delete-all-core-data-swift)
- [UISwipeActionsConfiguration](https://developer.apple.com/documentation/uikit/uiswipeactionsconfiguration)
- [Alert,ActionSheet](https://velog.io/@chan33344/Alert-ActionSheet-%EB%9E%80)
- [coreData이해하기](https://80000coding.oopy.io/72aca705-64d9-4be6-aaf5-34c1def4223a)

2023-05-05 04:21 UTC, havilog requested changes
어쩌다보니 코멘트 폭탄이 되었는데 .. 주말은 기니까 ..ㅎ
잠죽자 화이팅

2023-05-05 04:21 UTC, havilog commented on Diary/App/SceneDelegate.swift
> +    }
이 로직을 SceneDelegate에서 구현하도록 설계하신 이유가 궁금합니다~
DiaryDetailViewController에서 로컬하게 가지고 있을 수 있을거 같아서요!

2023-05-05 04:21 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +}
요건 사소한건데 .. 보통 이런 Constant는 DiaryDetailViewController안에 Nested Enum으로 많이 넣더라구요 ㅎㅎ

2023-05-05 04:21 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +    private let coreDataManager = CoreDataManager.shared
Q. singleton을 사용했을 때

1. 단점을 서술하시오. (10점)
2. 장점을 서술하시오. (10점)
3. 어떤 근거를 가지고 사용했는지 서술하시오. (10점)

2023-05-05 04:21 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +    private var diaryData: Diary?
```suggestion
    private var diary: Diary?
```

2023-05-05 04:21 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +    private var diaryData: Diary?
처음에는 optional이 아니었다가, optional로 변경하신 이유가 궁금해요~

2023-05-05 04:21 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +        saveOrUpdateDiary()
뷰의 라이브사이클을 기점으로 로직이 생성되어서 `isDeleted` 변수가 생긴거 같은데,
라이프사이클에 의존하지 않고 유저 인터렉션으로 로직을 처리할 수는 없을까요?

2023-05-05 04:21 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +        print(#function)
print는 #if DEBUG로 감싸거나, 제거해주세요~

2023-05-05 04:21 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +        view.endEditing(true)
터치이벤트를 오버라이드 하는것 보다, 원하는 영역(현재로써는 텍스트 뷰)에 터치이벤트를 추가해보는건 어떨까요?

2023-05-05 04:21 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillHide), name: UIResponder.keyboardWillHideNotification, object: nil)
요것도 함수로 빠지면 더 깔끔할거 같아요

2023-05-05 04:21 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +    private func tappedDetailButton() {
```suggestion
    private func detailButtonTapped() {
```

2023-05-05 04:21 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +        [shareAction, deleteAction, cancelAction].forEach(actionSheet.addAction(_:))
```suggestion
        [shareAction, deleteAction, cancelAction].forEach(actionSheet.addAction)
```

파라미터 없는 함수를 인자로 넘겨줄 때는 이게 깔끔하더라구요 ㅎㅎ

2023-05-05 04:21 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +        let bodyText = bodyTextView.text
뷰의 상태값에 의존하기 보다는, 뷰에 인풋값이 들어왔을 때 그 값을 바인딩해서 관리할 객체(여기서는 DiaryDetailViewController)가 title, body를 프로퍼티로 들고 있으면 어떨까요?
그렇게 되면 titleText이 optional이 아니게 되고, 뷰와 로직의 역할도 분리될거 같아요

2023-05-05 04:21 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +            coreDataManager.saveDiaryData(titleText: titleText, bodyText: bodyText) { [weak self] diary in
saveDiaryData의 completion이 escaping이 아닌데, [weak self]로 캡쳐해주셨네요 ㅎㅎ

1. escaping closure의 정의와, 언제 실행되고 왜 필요한지 설명하시오 (10점)
2. [weak self]는 항상 필요할까요? (15점)
3. guard로 self를 unwrapping해줬을 때 118번 라인에서 다시 escaping closure가 있다면 어떻게 될까요? (20점)

당장 다 대답하기 힘드시겠지만.. 반드시 알아야하는 개념이에요 :)

2023-05-05 04:21 UTC, havilog commented on Diary/Extension/UIViewController+Share.swift
> +    func shareText(_ textToShare: String?) {
```suggestion
    func share(someText: String) {
```

아 그리구 suggestion은 정말 제안이지 고치라는 의미는 아닙니다~
제 취향 강요임 ㅎㅎ..

2023-05-05 04:21 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +        coreDataManager.deleteDiaryData(data: diaryData)
일기를 삭제하는데 실패하면 어떻게 될까요?
일부러 삭제를 실패시켜보셨을까요??

2023-05-05 04:21 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +            }
```suggestion
        let deleteAction = UIAlertAction(
            title: ButtonConstant.deleteActionTitle,
            style: .destructive
        ) { [weak self] _ in
            guard let self else { return }
            self.deleteDiary()
            self.navigationController?.popViewController(animated: true)
        }
```

2023-05-05 04:21 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +            titleTextView.becomeFirstResponder()
뷰가 로드되는 시점에 Responder가 있을까요 ..?
제가 알기로 키보드는 새로운 윈도우를 띄우는거라 로드 시점에 하기 애매하다고 기억하고 있는데 이 부분 확인해주세요~

또한 추가 질문 
1. ResponderChain에 대해 설명해주세요
2. hitTest에 대해 설명해주세요

답변이 필수는 아닙니다 ㅎㅎ..

2023-05-05 04:21 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +        }
오히려 이런 부분에서는 고차함수를 사용하는 것 보다, 그냥 선언적인 문법이 더 읽기 쉬운거 같아요 ㅎㅎ..

2023-05-05 04:21 UTC, havilog commented on Diary/Extension/Notification.Name+.swift
> +    static let coreDataChanged = Notification.Name("coreDataChanged")
코어데이터 매니저와, 그걸 사용하는 객체의 전달방식을 Notification으로 정하신 이유가 뭘까요?
노티로 전달하는 방식과, delegate로 전달하는 방식, closure를 주입해주는 방식 등의 장단점에 대해 설명해주세요

2023-05-05 04:21 UTC, havilog commented on Diary/Model/CoreDataManager.swift
> +    lazy var context = appDelegate?.persistentContainer.viewContext
context가 존재하지 않으면, 이 앱은 모든 동작이 안될텐데,
코어데이터의 로드가 실해하면 어떻게 처리하실 지 고민해보셨을까요?

2023-05-05 04:21 UTC, havilog commented on Diary/Model/CoreDataManager.swift
> +    let modelName: String = "Diary"
요 아이는 상수의 느낌인데 
위쪽에서는 Constant.modelName으로 static하게 선언해주시고,
여기에서는 프로퍼티로 가지고 있는 기준이 궁금해요~

2023-05-05 04:21 UTC, havilog commented on Diary/Model/CoreDataManager.swift
> +    let appDelegate = UIApplication.shared.delegate as? AppDelegate
weak_delegate 워닝이 뜨는데 혹시 확인해보셨을까요?

2023-05-05 04:21 UTC, havilog commented on Diary/Model/CoreDataManager.swift
> +            if let fetchedDiaryList = try? context.fetch(request) {
try?에서 실패했을 때, 유저는 내 일기를 왜 못가져왔는지 알 수 없게 될거 같아요!
에러 처리에 대해 고민해주세요 :)

2023-05-05 04:21 UTC, havilog commented on Diary/Model/Diary.swift
> +//}
모델을 안쓴다면 지워야할거 같아요~

2023-05-05 04:21 UTC, havilog commented on Diary/Model/Entity+CoreDataProperties.swift
> +}
다른 파일에 작성하신 이유가 무엇일까요?
Entity+CoreDataClass과 다른 파일에 있어 Diary모델의 명세를  한눈에 알아보기 힘들어요 ㅠㅠ

2023-05-05 04:21 UTC, havilog commented on Diary/Controller/DiaryListViewController.swift
> +        diaryListTableView.reloadData()
전체를 리로드하지 않고, 추가, 수정, 삭제 된 일기만 수정할 방법은 없을까요?

2023-05-05 04:21 UTC, havilog commented on Diary/Controller/DiaryListViewController.swift
> +        guard let diaryData else { return }
요 가드문은 여기가 아니라 실행하는 쪽에 있어야할 거 같네요

2023-05-05 04:21 UTC, havilog commented on Diary/Controller/DiaryListViewController.swift
> +    private func deleteDiary(diaryData: Diary?) {
```suggestion
    private func delete(diary: Diary) {
```

2023-05-05 04:21 UTC, havilog commented on Diary/Controller/DiaryListViewController.swift
> +        diaryData[safe: indexPath.row].map {
아까도 느낀건데.. 흠 이게 함수형 프로그래밍이 좋긴 한데,
이런 부분에서는 함수형프로그래밍의 장점보다는 단점이 부각되는거 같아요 ㅎㅎ ㅠㅠ
오히려 그냥 작성하는것보다 가독성이 떨어진다고 느껴지네요

2023-05-05 04:21 UTC, havilog commented on Diary/Controller/DiaryListViewController.swift
> +
함수가 너무 길어서 읽기가 힘드네요 ㅠㅠ
액션을 만드는 trailing closure가 분리되면 좋을 것 같아요

2023-05-06 14:33 UTC, sehoong0429 commented on Diary/Controller/DiaryDetailViewController.swift
> +            coreDataManager.saveDiaryData(titleText: titleText, bodyText: bodyText) { [weak self] diary in
self를 사용하게 되면 저도 모르게 weak self를 달아버리는 습관이 생겨서 작성된 것 같습니다ㅠ
실수하지 않고 정확히 알고 사용할 수 있도록 하겠습니다. 

> escaping closure의 정의와, 언제 실행되고 왜 필요한지 설명하시오 (10점)

함수의 실행이 종료된 이후에도 호출되거나 외부로 전달될 수 있는 클로저를 의미합니다. 
일반적으로 비동기 작업이나 나중에 실행되는 작업에 대해 사용되고 호출 시점에 처리할 수 없는 작업들을 나중에 처리할 수 있게해줍니다. 

> [weak self]는 항상 필요할까요? (15점)

항상 필요한건 아니라고 생각합니다. 클로저 내에서 self를 사용할때 클로저와 self에 강한 참조가 발생할 수 있고 메모리 누수와 순환참조가 발생할 수 있는데 이때 순환참조를 방지하기 위해서 사용합니다. 클로저내에서 self를 사용하지 않거나 순환참조의 위험이 없는 경우에는 사용할 필요가 없을 것 같습니다. 

> guard로 self를 unwrapping해줬을 때 118번 라인에서 다시 escaping closure가 있다면 어떻게 될까요?

다시 escaping closure가 있으면 다시 self를 참조하게 될 것 같습니다. 
그렇게 되면 [weak self]를 사용해서 약한참조로 캡처할 수 있게 해줘야한다고 생각합니다.

2023-05-06 14:37 UTC, sehoong0429 commented on Diary/Model/CoreDataManager.swift
> +    let appDelegate = UIApplication.shared.delegate as? AppDelegate
저한테는 weak_delegate 워닝이 뜨지 않는데ㅠ 어떻게 확인할 수 있을까요?

2023-05-06 15:04 UTC, sehoong0429 commented on Diary/Model/Entity+CoreDataProperties.swift
> +}
Entity 생성해준 뒤에 Create NSManagedObject Subclass...를 선택해서 생성해주었고, 그걸 그대로 놔뒀습니다. 말씀해주신 것처럼 굳이 따로 작성할 필요가 없을 것 같아서 합쳐주었습니다.

2023-05-06 15:23 UTC, sehoong0429 commented on Diary/Controller/DiaryDetailViewController.swift
> +    private let coreDataManager = CoreDataManager.shared
>단점을 서술하시오. (10점)

- 앱 전체에서 전역 인스턴스로 사용되어 코드가 의존성을 가지게 되면서 테스트랑 디버깅이 어려워 질 수 있습니다. 
- 코드 간 결합도가 높아서 유지보수가 어려워질 수 있습니다. 
- 하나의 인스턴스만 생성하기때문에 프로젝트가 커지면 확장하기 어려워질 것 같습니다. 

>장점을 서술하시오. (10점)

- 전역변수처럼 앱에서 하나의 인스턴스만 생성하기때문에 메모리 사용량이 줄어듭니다. 
- 모든 클래스들이 동일한 인스턴스를 공유하고 있어서 동시접근에 대해서 제어할 수 있습니다.
(singleton 객체의 생성 시점을 한번만하면서 초기화 시점에 대한 제어가능) 

>어떤 근거를 가지고 사용했는지 서술하시오. (10점)

CoreDataManager는 앱 내에서 사용되는 관리 객체로 공유리소스를 하나로 관리해야하는 특성이 있다고 생각했습니다. 그래서 데이터베이스에 대한 일관된 처리와 동시성 제어를 가능하게 할 수 있다고 생각하여 사용해보았습니다.

2023-05-06 15:28 UTC, sehoong0429 commented on Diary/App/SceneDelegate.swift
> +    }
프로젝트 요구사항에 일기는 자동으로 저장해야하는 3가지 조건이 있었습니다. 
   1. 사용자가 입력을 멈추는 경우(키보드가 사라지는 경우)
   2. 앱이 백그라운드로 진입하는 경우
   3. 이전 화면(리스트 화면)으로 이동하는 경우
       
1,3번의 경우는 사용자 인터랙션에 관련된 로직이라고 생각해서 detailViewController에서 구현을 해주었고, 2번의 경우는 이벤트 발생 시점이 앱 전체에 영향을 주는 앱 생명주기와 관련된 이벤트라고 생각하여 SceneDelegate에서 처리해주었습니다..!

2023-05-06 15:52 UTC, sehoong0429 commented on Diary/Controller/DiaryDetailViewController.swift
> +    private var diaryData: Diary?
초기화시에 diaryData에 값을 제공하지 않아도 되어서 그렇게 설정하게 되었습니다.

2023-05-06 16:06 UTC, sehoong0429 commented on Diary/Controller/DiaryDetailViewController.swift
> +        saveOrUpdateDiary()
유저 인터렉션으로 로직을 어떻게 처리할 수 있을까요ㅠ

2023-05-06 16:25 UTC, sehoong0429 commented on Diary/Controller/DiaryDetailViewController.swift
> +            titleTextView.becomeFirstResponder()
뷰가 로드되는 시점에 UIResponder 객체를 첫번째 응답자로 설정해서 키보드를 활성화 시킬 수 있다고 생각해서 사용하게 되었습니다. https://developer.apple.com/documentation/uikit/uiresponder/1621113-becomefirstresponder
더 자세한 부분은 어디서 확인할 수 있을지 모르겠습니다ㅠ,, 

> ResponderChain에 대해 설명해주세요
- 사용자의 이벤트에 응답할 수 있는 객체의 계층구조입니다. UIResponder객체가 속하고 이벤트를 처리할 수 있는 객체를 찾기 위해 체인을 따라 상위 객체로 전달되는 이벤트를 처리할 수 있습니다. First Responder부터 시작해서 상위 응답자로 전달되고 처리되면 더 이상 전달되지 않습니다. 

> hitTest에 대해 설명해주세요
- 해당 메서드는 특정포인트에 위치한 가장 위의 뷰를 찾기 위해서 사용됩니다. 주어진 포인트에 해당하는 최상위 뷰를 반환하고 터치이벤트와 같은 사용자 입력이 발생한 위치에 있는 뷰를 찾아서 곤련된 동작을 수행할 수 있습니다.

2023-05-06 16:27 UTC, sehoong0429 commented on Diary/Controller/DiaryDetailViewController.swift
> +        coreDataManager.deleteDiaryData(data: diaryData)
삭제를 실패하면 데이터가 삭제되지 않고 그대로 남게됩니다. 
일부러 삭제시켜보진 않았습니다ㅠ

2023-05-06 16:39 UTC, sehoong0429 commented on Diary/Extension/Notification.Name+.swift
> +    static let coreDataChanged = Notification.Name("coreDataChanged")
> 코어데이터 매니저와, 그걸 사용하는 객체의 전달방식을 Notification으로 정하신 이유가 뭘까요?
- 객체들이 코어데이터의 변경사항을 관찰하고 업데이트 할 수 있도록 하기 위해서 사용했습니다. 또한 여러객체들이 동시에 이벤트를 수신하고 반응해야하는 경우에 유용하다고 생각했습니다.  

> 노티로 전달하는 방식과, delegate로 전달하는 방식, closure를 주입해주는 방식 등의 장단점에 대해 설명해주세요
1. NotificationCenter 
- 장점
객체들이 동일한 이벤트를 수신할 수 있습니다.  
코드의 결합도가 낮습니다.

- 단점 
코드의 실행흐름을 추적하기 어려울 수 있습니다. 

2. Delegate 
- 장점 
특정 객체 간의 명확한 커뮤니케이션을 제공해줍니다.

- 단점 
1:1 통신이기 때문에 여러 객체들이 동시에 이벤트를 수신하고 반응하기 어렵습니다.

3. Closure
- 장점 
코드를 간결하게 작성할 수 있습니다. 

- 단점 
클로저를 사용하면 메모리 관리에 주의해줘야합니다.

2023-05-06 17:56 UTC, sehoong0429 commented on Diary/Model/CoreDataManager.swift
> +    lazy var context = appDelegate?.persistentContainer.viewContext
각각의 기능에 맞춰서 에러타입을 만들고 에러처리를 해주었습니다

2023-05-06 17:59 UTC, sehoong0429 commented on Diary/Model/CoreDataManager.swift
> +    let modelName: String = "Diary"
기준없이 작성해준것같습니다ㅠ 
modelName은 Diary는 변경되지 않아서 static으로 선언해주었습니다.

2023-05-07 13:35 UTC, havilog commented on Diary/App/SceneDelegate.swift
> +    }
음.. 현재 요구사항에서는 세홍처럼 생각할 수도 있을거 같아요!

다만 앱이 커지고 요구사항이 많아진다면,
sceneDidEnterBackground에서 처리할 일은 신이 백그라운드로 갔을 때 앱 전역적으로 처리할 일을 여기서 구현하고,
지역적인 작업에 대해서는 해당 피쳐에서 처리하는게 자연스러워 보여요!
따라서 백그라운드에 진입할 수 있는 Controller에서 노티를 등록하여 처리하는게 나을거 같습니다 :)

2023-05-07 14:04 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +    private let coreDataManager = CoreDataManager.shared
사실 싱글톤이 작은 앱에서는 더 효율적이고, 사용하기도 쉬운데요,
말씀하신 단점대로 테스트가 어려워지고, 결합도가 높아져서 하나 바꿀려면 다바꿔야하는 일들이 생겨요.
세홍이 사용하신 근거에도 동의하는데, 우리의 목표는 취업이니까
코어데이터가 필요한 곳에서만 의존성을 주입을 하도록 연습해보고,
의존성을 주입해줬을때와 싱글톤의 차이를 비교해보는게 좋아보여요.
따라서 SOLID원칙 중 D에 대해 공부해보시는걸 추천드려요.

2023-05-07 14:05 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +    private var diaryData: Diary?
흠 저는 처음에 빈 객체를 생성해주고, 저장할 때 빈 객체가 유효하지 않으면 저장하지 않는 방식도 좋아보였는데,
뭐 정답이 있는건 아니라 고런 부분도 고려해보면 좋을거 같네요 :)

2023-05-07 14:06 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +        saveOrUpdateDiary()
"네비게이션 백 버튼이 눌러졌을 때" 로 판단할 수는 없을까요?

2023-05-07 14:10 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +            coreDataManager.saveDiaryData(titleText: titleText, bodyText: bodyText) { [weak self] diary in
사실 escaping 클로저가 아니라도, weak로 잡는게 나쁜 습관은 아닌거 같아요 ㅎㅎ

다른 부분들은 잘 알고 계신가 같습니다 : )

2023-05-07 14:11 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +        coreDataManager.deleteDiaryData(data: diaryData)
삭제를 실패했을 때, 유저가 왜 실패했는지, 그래서 어떻게 해야하는지에 대한 이유를 알고 처리할 수 있어야할 거 같아요!

2023-05-07 14:12 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +            titleTextView.becomeFirstResponder()
그 히트테스트랑 리스폰더체인 그림 있는데, 그거 보면서 
"유저가 터치했을 때 어떻게 반응해서 누가 처리하는지"
도 공부해보시면 좋을 것 같습니다~

2023-05-07 14:15 UTC, havilog commented on Diary/Extension/Notification.Name+.swift
> +    static let coreDataChanged = Notification.Name("coreDataChanged")
말씀하신대로, 노티를 사용하면 여러 객체들이 노티를 수신할 수 있는 대신,
어디에서 노티를 수신하고 있는지 추적하기 힘들고, 메모리도 관리해줘야해요.

제 생각에는 코어데이터매니저를 사용하고 있는 객체에서, 요청을 보냈을 때
해당 객체가 노티를 받아서 처리해주는게 자연스러운거 같아요.

2023-05-07 14:17 UTC, havilog commented on Diary/Model/CoreDataManager.swift
> +    lazy var context = appDelegate?.persistentContainer.viewContext
어떻게 처리해주셨는지에 대한 커밋로그를 달아주시면 컴이 더 쉬울거 같아요

2023-05-07 14:18 UTC, havilog commented on Diary/Model/CoreDataManager.swift
> +    let appDelegate = UIApplication.shared.delegate as? AppDelegate
린트에서 뜬거 같던데요??
저도 왜뜨는지 까지는 확인해보지는 않았지만, 결론적으로 여기서 앱델이 필요하지는 않을거 같아요!

2023-05-08 10:36 UTC, sehoong0429 commented on Diary/Model/CoreDataManager.swift
> +    let appDelegate = UIApplication.shared.delegate as? AppDelegate
제 프로젝트에서는 워닝이 하나도 뜨지않아서ㅜㅜ 어떤걸 수정해야하는지 모르겠습니다..! 
16번줄을 지우라는 말씀이신가요?? 
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/67987230/236802571-6e3cdc66-3958-4aed-afbf-207f1a98e068.png">

2023-05-08 12:55 UTC, sehoong0429 commented on Diary/App/SceneDelegate.swift
> +    }
detailViewController에서 didEnterBackgroundNotification를 사용해서 백그라운드 진입시 저장하는 로직을 구현해주었습니다. 
```swift
 deinit {
        NotificationCenter.default.removeObserver(self, name: UIApplication.didEnterBackgroundNotification, object: nil)
    }
    
NotificationCenter.default.addObserver(self, selector: #selector(appDidEnterBackground), name: UIApplication.didEnterBackgroundNotification, object: nil)

@objc func appDidEnterBackground() {
        saveOrUpdateDiary()
    }
```

2023-05-08 12:57 UTC, sehoong0429 commented on Diary/Controller/DiaryDetailViewController.swift
> +        coreDataManager.deleteDiaryData(data: diaryData)
삭제, 업데이트, 등록시에 유저가 실패했을때 에러메세지와 함께 다시 시도해주세요 하는 메세지를 추가해주었습니다. 
```swift 
   private func deleteDiary() {
        guard let diaryData = diary else { return }
        let result = coreDataManager.deleteDiaryData(data: diaryData)
        switch result {
        case .success:
            print("삭제 성공")
            diary = nil
            isDeleted = true
        case .failure(let error):
            let errorTitle = "삭제 실패"
            let errorMessage = error.userErrorMessage + "\n다시 시도해주세요."
            showAlertWithMessage(errorTitle, errorMessage)
        }
    }
```

2023-05-09 01:38 UTC, sehoong0429 commented on Diary/Controller/DiaryDetailViewController.swift
> +    private let coreDataManager = CoreDataManager.shared
> SOLID원칙 중 D
-  고수준의 모듈이 저수준의 모듈에 의존하지 않도록 설계, 모두가 추상화에 의존하는 방식 이렇게 하면 결합도를 낮출 수 있고 코드의 유연성을 증가 시킬 수 있습니다. 

> 의존성을 주입해줬을때와 싱글톤의 차이 
- 싱글톤: CoreDataManager.shared를 사용하면 CoreDataManager의 구체적인 구현에 의존하게 되어서 변경 될때 영향을 받는 모든 코드를 수정하게 될 수 있습니다. 하지만 하나의 인스턴스를 앱 전체에서 공유할 수 있기 때문에 전역상태를 관리하는 데 편합니다. 
-  의존성 주입: 객체가 필요로 하는 의존성을 외부에서 주입 받는 패턴입니다. 객체간의 결합도를 낮출 수 있습니다. 또한 말씀해주셨던 것처럼 테스트할때 사용성이 증가합니다. 

[c216156](https://github.com/yagom-academy/ios-diary/pull/106/commits/c216156db783da78e4528fe597fdf4bbb5f13530)
찾아본 것을 바탕으로 싱글톤과 의존성 주입의 장점을 활용하여 해당 부분에 대해서 코드 수정해보았습니다. 
프로젝트에서 coreDataManager 인스턴스를 유지하면서 테스트와 특정 상황에서는 다른 설정이나 다른 상태를 가진 CoreDataManager를 사용할 수 있도록 의존성 주입 패턴을 사용하여 구현했습니다.

2023-05-09 02:17 UTC, sehoong0429 commented on Diary/Controller/DiaryDetailViewController.swift
> +        saveOrUpdateDiary()
didMove(toParent) 메서드를 사용하여 뷰 컨트롤러의 부모 뷰 컨트롤러가 변경되었을 때 호출하는 방법을 사용해주었습니다. [76bf65b](https://github.com/yagom-academy/ios-diary/pull/106/commits/76bf65b72053da9d9b6c594972d6dbef19821239)
 
```
    override func didMove(toParent parent: UIViewController?) {
        super.didMove(toParent: parent)
        
        if parent == nil {
            saveOrUpdateDiary()
        }
    }
```

2023-05-09 02:55 UTC, sehoong0429 commented on Diary/Controller/DiaryDetailViewController.swift
> +            titleTextView.becomeFirstResponder()
뷰가 화면에 완전히 표시된 후에 키보드를 활성화 시키는게 맞다고 생각하여 
viewDidAppear 메서드 내에서 다이어리 data가 없을때 becomeFirstResponder을 호출할 수 있도록 해주었습니다. [62db6a8](https://github.com/yagom-academy/ios-diary/pull/106/commits/62db6a8205d9a4a975f25d04720a8bcf0ffb053a)

2023-05-09 11:13 UTC, sehoong0429 commented on Diary/Model/CoreDataManager.swift
> +    let appDelegate = UIApplication.shared.delegate as? AppDelegate
appdelegate는 앱이 실행하는 동안 계속 존재하기때문에 메모리 누수를 걱정하지 않아도 된다고 생각합니다. weak 선언할 필요가 없습니다. 
또한 persistentContainer가 appdeleagate에 있어서 접근해서 사용하고 있는 상태입니다!

2023-05-09 11:26 UTC, sehoong0429 commented on Diary/Extension/Notification.Name+.swift
> +    static let coreDataChanged = Notification.Name("coreDataChanged")
[a252df8](https://github.com/yagom-academy/ios-diary/pull/106/commits/a252df8a839a5527a1d83a099734661c5ab6b006)
해당 부분 수정해주었습니다.

2023-05-09 11:59 UTC, sehoong0429 commented on Diary/Controller/DiaryListViewController.swift
> +        diaryListTableView.reloadData()
reloadrows, deleterows, insertrows를 활용하여 수정할 수 있습니다

2023-05-09 23:11 UTC, havilog commented on Diary/Model/CoreDataManager.swift
> +    let appDelegate = UIApplication.shared.delegate as? AppDelegate
앱델이 필요하지 않을 거 같다고 생각했던 이유는,
persistentContainer를 코어데이터매니저가 가지고 있는게 자연스럽다고 생각해서 였어요!
앱델은 앱의 생명주기를 관장하는 역할을 하는 아이인데, 코어데이터의 컨테이너 까지 가지고 있으면 너무 역할이 많아지는 느낌이 들어서요~
스탭3 진행하시고 나중에 다시 고민해보시져~

2023-05-09 23:12 UTC, havilog commented on Diary/Controller/DiaryDetailViewController.swift
> +        saveOrUpdateDiary()
https://developer.apple.com/documentation/uikit/uiadaptivepresentationcontrollerdelegate/3229889-presentationcontrollerdiddismiss
요런거나
네비게이션에 델리게이트 달아주는 것두 있어서 한 번 고민해보셔도 좋을 것 같아요~

2023-05-09 23:13 UTC, merged