일기장 [STEP 2] vetto, Christy
yagom-academy/ios-diary pull request #108
Opened 2023-05-05 08:59 UTC by christy-hs-lee

@AppleCEO 
안녕하세요 도미닉!
다이어리 STEP2 PR 보냅니다. 이번에도 잘 부탁드리겠습니다!🙇🏻‍♂️🙇🏻‍♀️

## 고민했던 부분
### 키보드가 사라지는 방법
이번 스텝 요구사항에는 일기 자동 저장에 관한 조건이 있었습니다. 해당 조건 중 `키보드가 사라지는 경우`라는 문구가 애매했습니다. 처음에는 아래의 코드를 사용하여 사용자가 일기를 작성하다 뷰를 드래그할 경우 키보드가 사라지도록 구현했습니다.

```swift
    textView.keyboardDismissMode = .onDrag
```

하지만 화면 드래그를 사용하여 키보드를 사라지게 하는 방법이 사용성 측면에서 자연스러운지 의문이 들었습니다. 비슷한 사용 방식을 가지고 있는 아이폰의 메모 앱의 방식을 참고하게 되었습니다. 메모 앱의 경우 완료 혹은 뒤로가기 버튼을 터치 할 경우 키보드를 사라지게 해주고 있었습니다. 저희도 해당 방식을 차용하여 네비게이션의 `backButton`과 `rightBarButton`을 터치할 경우 키보드가 사라지도록 구현했습니다.

```swift
    private func configureUI() {
        let navigationRightButton = UIBarButtonItem(image: image,
                                                    style: .plain,
                                                    target: self,
                                                    action: #selector(ellipsisButtonTapped))
        ...
    }
```

`rightBarButton`의 `action`에 `#selector`를 사용하여 버튼을 터치하는 상황을 처리할 수 있는 메서드를 호출시켜 줬습니다.

```swift
    @objc
    private func ellipsisButtonTapped() {
        textView.resignFirstResponder()
        
        ...
    }
```
`resignFirstResponder()`을 통해 키보드가 내려가도록 설정 했습니다.

</br>

## 조언이 필요한 부분
### 개행 컨벤션
처음에는 저희의 컨벤션을 정하여 코드를 작성하였습니다. 이후 공백이 많은 것 같다는 코멘트를 의식하여 원래는 개행 처리를 하기로 했던 선언구문과 실행구문을 붙이는 식으로 코드를 작성하였습니다. 하지만 그렇게 한 결과 코드의 가독성이 나빠지는 것을 볼 수 있었습니다. 
도미닉이 말한 부분이 이러한 부분일까요? 아니면 메서드의 매개변수에 공백을 주는 것을 말하는 것일까요?

#### 수정한 컨벤션
```swift
let title // 선언구문
print(title) // 실행구문
```

#### 메서드의 매개변수에 공백을 준 상태
```swift
func method(int: Int,
            string: String,
            double: Double)
```
또한 도미닉이 보통 사용하는 개행 컨벤션도 궁금합니다!

</br>

### coredata형 데이터
현재는 `CoreData`의 Entity인 `DiaryData`만 가지고 코드를 작성할 수 있다고 판단하여 기존의 `DiaryItem`을 삭제하고 `DiaryData`를 프로퍼티로 가지고 있는 형태로 코드를 작성하였습니다. 
하지만 coreData의 데이터를 그대로 사용하는 것은 위험하다는 이야기를 들었습니다. 데이터에 대한 권한을 직접적으로 가지고 있다면 문제가 발생할 수 있을 것 같습니다. 하지만 이런 주장의 근거를 뒷받침하는 문서를 찾지 못하여 해당 방식에 조언이 필요합니다. 다리역할을 해주는 `DiaryItem`같은 객체를 만들고 이용하는 것이 더 안전한 방법일까요? 도미닉은 보통 어떻게 하시나요?

</br>

### 빈 제목
저희는 현재 줄바꿈을 기준으로 title과 body를 구분하고 있습니다.
다만 이렇게 구분하는 만큼 빈 제목이 들어가는 경우가 있습니다.
이런 경우 제목 자리를 채워주는 것(빈 제목, 제목 없음)이 좋은 지 아니면 빈칸으로 해주는 것이 좋은지 궁금합니다.

</br>

### 요구사항에 없는 규칙
처음에는 요구사항의 내용을 준수하여 코드를 작성했습니다. 하지만 다양한 예외가 발생했고 이를 처리하기 위해 저희끼리 임의로 규칙을 정하여 코드로 적었습니다.

- +를 누르고 아무 입력이 없어도 일기 저장
- 기존의 일기장 수정시 수정한 날짜로 변경

이러한 예시처럼 요구사항에 나오지 않은 규칙들을 정해서 코드에 반영해도 괜찮은지 궁금합니다.

2023-05-07 13:57 UTC, AppleCEO requested changes
안녕하세요. @christy-hs-lee @vetto
도미닉입니다.
이번 코드도 깔끔한 느낌이 많이 듭니다!
실력이 좋으신 것 같아요

몇가지 개선하면 좋을 점들 코멘트 남겨놨습니다. 휴일이라 리뷰가 조금 늦어져서 죄송해요.

# 조언이 필요한 부분

2023-05-07 13:57 UTC, AppleCEO commented on Diary/Application/AppDelegate.swift
> -        let context = persistentContainer.viewContext
사용하지 않는 코드를 제거해준 것 좋습니다!

2023-05-07 13:57 UTC, AppleCEO commented on Diary/Controller/DiaryEditViewController.swift
> +        }
여기 else 를 쓰지 않고 if 문에 들어가지 않았을 때 아래 코드가 동작하도록 같은 로직을 구현해 볼 수 있을까요?

2023-05-07 13:57 UTC, AppleCEO commented on Diary/Controller/DiaryEditViewController.swift
> +    @objc
여기 @objc 를 붙이면 어떤 동작을 하게 될까요?

2023-05-07 13:57 UTC, AppleCEO commented on Diary/Utility/DateManager.swift
> +    private init() { }
여기 공백을 추가한 이유는 무엇인가요?

2023-05-07 13:57 UTC, AppleCEO commented on Diary/View/DiaryTableViewCell.swift
> +
prepareForReuse 메소드에서 재사용 시 초기화해주는 것 너무 좋습니다! 🥇 
super.prepareForReuse() 가 text 초기화 밑에 있는 것이 좋을 것 같기도 한데요.
어떻게 생각하실까요?

2023-05-07 13:57 UTC, AppleCEO commented on Diary/View/DiaryTableViewCell.swift
> +        contentView.addSubview(diaryInfoStackView)
self. 를 지워준 이유는 무엇일까요?
self 를 붙이고 안 붙이고는 어떤 차이가 있을까요 ㅎㅎ

2023-05-08 07:47 UTC, gzzjk159 commented on Diary/Controller/DiaryEditViewController.swift
> +        }
else 문을 쓰지 않고 if문에 들어가지 않았을 때가 생각나는 게  guard문을 사용하였을 때로 생각하였습니다. 따라서 if else 구문을 guard 문으로 처리하여 코드를 작성하였습니다.
a7385d005a806097413e1777890549bebc1fc93b

2023-05-08 07:59 UTC, gzzjk159 commented on Diary/View/DiaryTableViewCell.swift
> +        contentView.addSubview(diaryInfoStackView)
컨벤션을 정할 때 self를 꼭 붙여야하는 상황을 제외하고는 붙이지 않도록 정했습니다.
따라서 그 결과 붙이지 않아도 판단되어 삭제해주었습니다.

self는 클래스와 구조체의 인스턴스 자신을 가리키는 키워드입니다. 명시적으로 보여주는 것 외에는 어떤 차이가 있는지 찾아봐야 할 거 같습니다.

2023-05-08 08:07 UTC, christy-hs-lee commented on Diary/Controller/DiaryEditViewController.swift
> +    @objc
`swift`는 컴파일 시점에 메서드를 바인딩하는데 `Objective-C`는 런타임에 메서드를 바인딩합니다.
해당 키워드를 통해 `swift`로 작성된 코드를 `Objective-C`의 방식으로 컴파일할 수 있습니다.

2023-05-08 08:09 UTC, christy-hs-lee commented on Diary/View/DiaryTableViewCell.swift
> +
해당 방법으로 수정했습니다!

2023-05-08 08:15 UTC, gzzjk159 commented on Diary/Utility/DateManager.swift
> +    private init() { }
일반적으로 쓰이는 컨벤션이 빈 중괄호에 띄어쓰기 한칸을 넣는 것이라고 생각했습니다.
혹시 도미닉이 사용하는 컨벤션이나 일반적으로 사용하는 컨벤션이 있을까요?

2023-05-08 13:46 UTC, AppleCEO commented on Diary/Controller/DiaryEditViewController.swift
> +        }
저는 ealry return 을 선호합니다.
```swift
if let body = diaryData?.body {
  textview.text = "\(title)\n\(body)"
  return
}
textView.text = title
```
이렇게 작성하는 방법도 있다는 것 아시면 좋겠어서 해당 코멘트 남겼습니다~

2023-05-08 13:47 UTC, AppleCEO commented on Diary/Utility/DateManager.swift
> +    private init() { }
흐음; 저는 이런 상황을 거의 안 만들기는 하는데요.
공백이 있는 것 보다는 {}가 더 좋아보이네요!

2023-05-08 13:49 UTC, AppleCEO commented on Diary/View/DiaryTableViewCell.swift
> +
super 의 코드를 호출할 때의 순서가 있는데요. 
init 일 때는 super 의 함수를 나중에 호출하고 deinit 일 때는 super 의 함수를 먼저 호출하는 등의 방식이 있었습니다.
이런 내용을 한번 조사하고 습득해보길 원했어요~

2023-05-08 13:50 UTC, AppleCEO commented on Diary/View/DiaryTableViewCell.swift
> +        contentView.addSubview(diaryInfoStackView)
명시적으로 보여주는 것이 거의 주된 차이라고 보시면 되겠습니다.
스타일쉐어의 스위프트 스타일 가이드에서는 자신의 프로퍼티에 접근할 때는 self. 를 꼭 붙여주는 규칙도 있더라고요.
어떤 차이가 있는지 고민해보면 좋겠다고 생각했습니다 ㅎㅎ

2023-05-08 13:57 UTC, merged