일기장 [STEP 3] Harry, Rowan
yagom-academy/ios-diary pull request #112
Opened 2023-05-11 08:21 UTC by HarryHyeon

안녕하세요 줄라이!
해리, 로웬 조 Diary Step3 PR 보내드립니다 🙌
중간에 피드백 주신 부분에 대해서는 적당히 고민/수정 해봤는데 부족한 부분에 대해서는 코멘트 달아주시면 감사드리겠습니다! 🫡
이번 리뷰도 잘 부탁드립니다~~

사전 학습 내용 - [STEP 3사전학습](https://hackmd.io/@Vb2d_yXZSoyaNGLxdwowWg/S1FaNXfNh)

</br>

## 🔶 고민한 점
### 🔸 CoreData ManagedObjectModel
- Diary Entity의 attribute에 weather API에서 받아온 main, icon을 추가하기 보다는 해당 정보를 포함하는 Weather Entity를 추가했습니다.
- 두 entity의 relationship을 설정해 Diary 삭제 시, 연결된 Weather를 같이 삭제할 수 있도록 하였습니다.
- Lightweight Migration으로 모델의 변경사항을 반영할 수 있도록 version을 추가했습니다.

</br>

### 🔸 DiaryDataManager
- DiaryDAO 인스턴스를 만들 때, WeatherDAO 객체를 함께 생성할 수 없었습니다.
- CoreDataManager를 프로퍼티로 갖고 있는 DiaryDataManager를 정의하여 DiaryDAO와 WeatherDAO의 CRUD를 묶어서 관리할 수 있도록 하였습니다.

</br>

### 🔸 NetworkError 처리
OpenWeatherAPI 네트워크 통신이 실패할 경우 던져진 error를 처리할 때, request를 다시 보낼 수 있도록 Alert를 띄워주었습니다.
해당 Alert의 retry Action completion에 `loadWeather` 메서드를 캡처하고 있습니다.
escaping closure로 캡처하기 때문에 재귀함수가 아니라는 생각으로 이렇게 작성해봤습니다.
```swift
private func loadWeather(coordinate: CLLocationCoordinate2D) {
    weatherHelper.loadData(latitude: coordinate.latitude,
                               longitude: coordinate.longitude) { [weak self] result in
        guard let self else { return }

        switch result {
        case .success(let currentWeather):
            guard let weather = currentWeather.weather.first else { return }

            self.diary?.weather?.updateContents(main: weather.main, icon: weather.icon)
        case .failure(let error):
            print(error.localizedDescription)

            let alertData = self.alertDataMaker.reloadAlertData {
                self.loadWeather(coordinate: coordinate)
            }
            let alert = self.alertFactory.reloadAlert(for: alertData)

            DispatchQueue.main.async {
                self.present(alert, animated: true)
            }
        }
    }
}
```

</br>

## 🔶 조언받고 싶은 점

### 🔸 Core Data Entity의 구조
``` swift
class DiaryDAO {
    @NSManaged public var body: String?
    @NSManaged public var date: Double
    @NSManaged public var id: UUID
    @NSManaged public var title: String?
    @NSManaged public var weather: WeatherDAO?
}
```

``` swift
class WeatherDAO {
    @NSManaged public var main: String?
    @NSManaged public var icon: String?
    @NSManaged public var id: UUID
    @NSManaged public var diary: DiaryDAO?
}
```

- 코어데이터에서 두 가지 엔티티를 사용하고 있습니다.
- 1:1 관계의 relationship을 가지고 있도록 했는데, 엔티티 생성 과정에서 relationship 때문에 조금 복잡해진 느낌이 있는 것 같습니다.
- DiaryDAO 엔티티 객체를 생성하고 attribute들을 초기화 할 때, WeatherDAO도 같이 생성하여 DiaryDAO의 weather가 참조하도록 해주는 방식으로 구현했습니다.
    - 이 부분은 CoreDataManager, DiaryDataManager에서 각 타입의 setValues, updateValues를 호출해 값을 초기화하고 업데이트 해주고 있습니다.
- 따라서 DiaryDAO가 또 다른 엔티티와 relationship이 생기게 되면 수정해야 할 코드가 많아서 너무 확장성이 떨어진다는 생각이 듭니다.
- 관계가 있는 엔티티를 관리하는 방법에 대한 조언이 있을까요?

</br>

### 🔸 Weather 인스턴스의 두 번 생성(DTO)
- 일기장을 새로 작성할 때(+ 버튼을 누를 때) Weather의 인스턴스를 생성하고 코어데이터에도 업데이트 하도록 해주고 있습니다.
    - Weather의 인스턴스를 생성한 이유: id가 optional type이 아닌데 DB에는 nil로 저장되어 fetch할 때 crash가 발생했기 때문
- CLLocationManager Delegate 메소드 중 didUpdateLocations에서 비동기로 Weather 객체를 서버로부터 값을 받아 생성해주는데 여기서 인스턴스 자체를 교체하지 않고, 값만 이전에 생성해놓은 인스턴스에 교체해주고 있습니다.
- 서버에 요청해 얻은 인스턴스는 값만 사용하고 인스턴스 자체는 사용하지 않고 있습니다. 사용하지 않는 인스턴스를 괜히 한번 더 생성하는 것 같아서 좋은 방법이 없을지 궁금합니다..

</br>

### 🔸 File Tree
프로젝트 폴더 - 파일 관리가 아직도 생소한 것 같습니다.
피드백에 따라 폴더를 나누는 것을 고민하다보니 타입의 이름도 더 고민해봐야겠다고 생각했습니다.
시간을 너무 투자하지 않아도 되는 선에서 수정하다보니 부족한 부분이 많을 것 같아요 😅
실제로 사용하시거나 일반적인 폴더링 방법에 대해 간략히 답변 부탁드립니다🙏

참고해서 잘 적용해보도록 하겠습니다~!

2023-05-11 09:09 UTC, July911 requested changes

2023-05-11 09:09 UTC, July911 commented on Diary/Controller/DiaryContentViewController.swift
> +    private let weatherHelper = OpenWeatherHelper()
이름이 조금 어색한거같네요 :) 
API 콜로 날씨를 받아오는 객체를 헬퍼라고 부를 수 있을까요 ? 
날씨를 받아오는 객체의 이름이 weatherHelper 라면 다른 정보를 받아오는 객체 이름도 
Helper라고 지으실건지 궁금합니다 !

2023-05-11 09:09 UTC, July911 commented on Diary/Controller/DiaryContentViewController.swift
> +        diary.updateContents(title: currentContents.title,
다이어리가 updateContents를 스스로 하는게 맞나요 ? 
update를 의도한건가요 아니면 Cell 처럼 configure를 의도하신건가요 ? 
여기서 읽으니 모호한거같습니다 
차라리 생성자로 다이어리를 만들어서 다이어리 매니저에 넘겨주는게 좋아보입니다.

2023-05-11 09:09 UTC, July911 commented on Diary/Controller/DiaryContentViewController.swift
> +            self.diary?.weather = Weather()
직접접근말고 넘기는방법은 없을까요 ?

2023-05-11 09:09 UTC, July911 commented on Diary/Controller/DiaryContentViewController.swift
> +    func locationManagerDidChangeAuthorization(_ manager: CLLocationManager) {
extension 자체를 외부에서 알아야할까요 ?

2023-05-11 09:09 UTC, July911 commented on Diary/Controller/DiaryContentViewController.swift
> +            print(coordinate)
??????!!!

2023-05-11 09:09 UTC, July911 commented on Diary/Controller/DiaryListViewController.swift
> +            case .success(let icon):
릭이 안나나요 ?

2023-05-11 09:09 UTC, July911 commented on Diary/CoreData/CoreDataManager.swift
> +    let storage = CoreDataStack.shared
여신 이유는 무엇일까요  ?

2023-05-11 09:09 UTC, July911 commented on Diary/Model/Weather.swift
> +        let container = try decoder.container(keyedBy: CodingKeys.self)
오 무엇을 위해 필요한 
    init(from decoder: Decoder) throws { 
    인가요 ? 공부하신 내용을 설명해볼까요 ?

2023-05-11 09:09 UTC, July911 commented on Diary/View/DiaryListCell.swift
> +
contentmode같은 설정은 필요없을까요 ?

2023-05-11 09:09 UTC, July911 commented on Diary/View/DiaryListCell.swift
> +    private let iconView: UIImageView = {
iconView는 UIView같은 느낌이 듭니당 :)

2023-05-11 09:09 UTC, July911 commented on Diary/Controller/DiaryContentViewController.swift
> +                self.diary?.weather?.updateContents(main: weather.main, icon: weather.icon)
함수호출은 상관없지만 값 할당은 nil처리되면 bad access로 터질수도 있어용

2023-05-11 09:29 UTC, July911 requested changes

2023-05-11 09:29 UTC, July911 commented on Diary/Controller/DiaryContentViewController.swift
> +    private func loadWeather(coordinate: CLLocationCoordinate2D) {
이 부분에는 delegate 콜만 담겨있는게 좋을 것 같습니다.

2023-05-11 09:29 UTC, July911 commented on Diary/Controller/DiaryContentViewController.swift
> +    private let locationManager = CLLocationManager()
VC에 없으면 더 좋을 것 같습니다. 이런게 헬퍼로 있으면 좋을 것 같아요

2023-05-12 02:49 UTC, July911 commented
두 분 다 매일같이 노력하는 모습에 저도 즐거웠던 3주였습니다 ! 고생하셨습니다  ! 


### 1 

사전 학습 내용 - [STEP 3사전학습](https://hackmd.io/@Vb2d_yXZSoyaNGLxdwowWg/S1FaNXfNh)
 
 -> 링크가 안열려요 ... 

### 🔸 NetworkError 처리
OpenWeatherAPI 네트워크 통신이 실패할 경우 던져진 error를 처리할 때, request를 다시 보낼 수 있도록 Alert를 띄워주었습니다.
해당 Alert의 retry Action completion에 loadWeather 메서드를 캡처하고 있습니다.
escaping closure로 캡처하기 때문에 재귀함수가 아니라는 생각으로 이렇게 작성해봤습니다.

-> 이 부분이 명확하게 이해가 안됩니다. 다시 한번 설명해주세요. 

### 🔸 Core Data Entity의 구조

이 부분은 CoreDataManager, DiaryDataManager에서 각 타입의 setValues, updateValues를 호출해 값을 초기화하고 업데이트 해주고 있습니다.
따라서 DiaryDAO가 또 다른 엔티티와 relationship이 생기게 되면 수정해야 할 코드가 많아서 너무 확장성이 떨어진다는 생각이 듭니다.
관계가 있는 엔티티를 관리하는 방법에 대한 조언이 있을까요?

-> 사실은 이번이 조금 특수한 경우라고 보여집니다. 아무리 두개가 연관이 있어도 이렇게 관련을 지어서 relationship 을 만드는 경우는 없었던 것 같습니다. 
'관계가 있는 엔티티를 관리하는 방법에 대한 조언이 있을까요?' 에 대한 답은 특별한 방법이 없다 입니다 .. ㅎㅎ 

### 🔸 Weather 인스턴스의 두 번 생성(DTO)

-> 사실 이부분은 저는 괜히 라고 생각이 들지 않습니다. 업데이트를 새로운 Weather로 해주는건데 머징한다고 생각하시면 간단할 것 같습니다. 
사실은 값타입이면 더 좋았을 것 같지만요 .. ㅎㅎ 

어제 말씀주신 SwiftUI 역시도 계속해서 View를 찍어내는 형태입니다. 
지금 코멘트와는 크게 상관없지만 COW에 대해서도 공부해보시면 좋을 것 같습니다. 

🔸 File Tree
프로젝트 폴더 - 파일 관리가 아직도 생소한 것 같습니다.
피드백에 따라 폴더를 나누는 것을 고민하다보니 타입의 이름도 더 고민해봐야겠다고 생각했습니다.
시간을 너무 투자하지 않아도 되는 선에서 수정하다보니 부족한 부분이 많을 것 같아요 😅
실제로 사용하시거나 일반적인 폴더링 방법에 대해 간략히 답변 부탁드립니다🙏

-> 어제 이야기 나눴던 것 처럼 2가지 방법이 있을 것 같아요. 
각 뷰별로 나누거나 VC, VM 별로 나누거나 
저는 개인적으로는 뷰 별로 나누는걸 선호합니다. 제가 조금 문제가 있다고 느낀 부분은 폴더링이 특별한 기준없이 되어있는 것 같아서 말씀드린 거고 지금은 조금 개선된 모습입니다 .. :) 
단지 path처럼 각각의 뎁스에 맞는 이름을 가지는게 좋을 것 같습니다. 지금은 너무 .. 상위 폴더만 생각하는 이름 같아요 !

2023-05-12 07:02 UTC, HarryHyeon commented on Diary/Controller/DiaryContentViewController.swift
> +    private let weatherHelper = OpenWeatherHelper()
OpenWeatherService라고 이름을 변경해주었습니다!

2023-05-12 07:36 UTC, HarryHyeon commented on Diary/Controller/DiaryContentViewController.swift
> +            self.diary?.weather = Weather()
Diary 타입에 updateWeather 메서드를 열어두어 새롭게 받은 날씨 정보를 수정할 수 있도록 했습니다 👍🏼

2023-05-12 07:37 UTC, HarryHyeon commented on Diary/Controller/DiaryContentViewController.swift
> +            print(coordinate)
??!!! 이런.. 실수가 있었네요!

삭제했습니다😎

2023-05-12 07:38 UTC, HarryHyeon commented on Diary/CoreData/CoreDataManager.swift
> +    let storage = CoreDataStack.shared
음 여러가지 테스트를 하다보니 private을 지우고 커밋을 한 것 같습니다!
다시 접근 제어자를 붙여주었습니다👍🏼

2023-05-12 07:39 UTC, Tediousday93 commented on Diary/Controller/DiaryContentViewController.swift
> +        diary.updateContents(title: currentContents.title,
정말 네이밍에서 어색한 부분이 아직도 많이 보이네요 ... 💦
init을 기존에 있던 데이터의 id를 받아올 수 있도록 수정했습니다!
```swift
init(title: String?, body: String?, updatedDate: Double, id: UUID = UUID()) {
    self.title = title
    self.body = body
    self.updatedDate = updatedDate
    self.id = id
}
```

60번 line은 이렇게 수정되었어요 😊
```swift
let updatedDiary = Diary(title: currentContents.title,
                         body: currentContents.body,
                         updatedDate: updatedDate,
                         id: diary.id)

diaryDataManager.update(data: updatedDiary)
```

2023-05-12 07:58 UTC, Kyeongjun2 commented on Diary/Controller/DiaryContentViewController.swift
> +    func locationManagerDidChangeAuthorization(_ manager: CLLocationManager) {
일단 Delegate 프로토콜을 채택한 extension에서는 프로토콜에 정의된 인터페이스의 접근제어에 따라 달라질 것 같습니다.

protocol 인터페이스의 접근제어와 동일한 수준의 접근제어를 갖지 않으면 프로토콜을 준수할 수 없게 됩니다.
따라서 Delegate 메서드의 접근제어 수준이 internal인 경우 extension도 internal이 되어야 합니다!

하지만 기능에 따라 타입의 익스텐션을 나눈 경우, 접근제어를 붙여줄 수 있었습니다.
```swift
private
extension DiaryListViewController {
```

extension은 file scope에서만 정의할 수 있으니 위 접근제어자는 fileprivate처럼 동작한다고 생각했습니다.🤔

2023-05-12 07:59 UTC, HarryHyeon commented on Diary/Model/Weather.swift
> +        let container = try decoder.container(keyedBy: CodingKeys.self)
decoder를 통해 객체가 생성 될 때 불리는 이니셜라이져 입니다!

Weather 객체는 원격 서버로부터 데이터를 받아, JSON Decoder를 통해 생성됩니다. 
서버로부터 받는 JSON에서 id가 없기 때문에 오류가 발생하는데, 이때 Decoder를 통한 이니셜라이져를 직접 정의해주게 되면 각각의 프로퍼티에 어떤 식으로 값을 담을지 설정할 수 있습니다.

2023-05-12 08:16 UTC, HarryHyeon commented on Diary/View/DiaryListCell.swift
> +    private let iconView: UIImageView = {
좀 더 네이밍에 신경써야할 것 같네요.. iconImageView로 변경해주었습니다 !

2023-05-12 08:17 UTC, Kyeongjun2 commented on Diary/Controller/DiaryListViewController.swift
> +            case .success(let icon):
`cell` 을 캡처하고 있어서 [weak cell] 캡처리스트를 추가했습니다.

```swift
openWeatherService.loadIcon(code: diary.weather?.icon) { [weak cell] result in
```

2023-05-12 08:20 UTC, Kyeongjun2 commented on Diary/Model/Weather.swift
> +        let container = try decoder.container(keyedBy: CodingKeys.self)
decoding할 때, UUID 타입으로 사용하고 싶은 id 프로퍼티도 같이 decoding 되는 문제가 있었습니다.
decoder를 통해 초기화됐을 때  id 프로퍼티만 디코딩이 되지 않도록 하기 위해 `init(from:)` 이니셜라이저를 정의해 주었습니다!

2023-05-12 08:20 UTC, HarryHyeon commented on Diary/Controller/DiaryContentViewController.swift
> +                self.diary?.weather?.updateContents(main: weather.main, icon: weather.icon)
넵 조언 감사합니다 !

추가로 이 부분을
``` swift
let updatedWeather = Weather(main: weather.main,
                                             icon: weather.icon,
                                             id: weatherId)
                
                diary.setWeather(data: updatedWeather)
```
다이어리의 프로퍼티에 접근해서 내용을 수정하기보다 위에서 말씀해주신 Weather의 인스턴스 생성을 하고 다이어리에 넘겨주는 방식으로 수정해보았습니다.

2023-05-12 08:23 UTC, Kyeongjun2 commented on Diary/View/DiaryListCell.swift
> +
기본값도 명시해주는 것이 좋다는 피드백을 염두에 두지 못한 것 같네요 😓
앞으로는 명시해줄 수 있도록 해보겠습니다!!

```swift
private let iconImageView: UIImageView = {
    let imageView = UIImageView()
    
    imageView.contentMode = .scaleToFill
    
    return imageView
}()
```

2023-05-12 08:26 UTC, HarryHyeon commented on Diary/Controller/DiaryContentViewController.swift
> +    private let locationManager = CLLocationManager()
조언감사합니다. `locationHelper`라는 클래스로 빼주어서 위치를 업데이트하고, 위치를 업데이트 했을때 서버로부터 좌표값을 이용해 새로운 데이터를 받아오는 역할을 하도록 했습니다 👍🏼

2023-05-12 08:32 UTC, Tediousday93 commented on Diary/Controller/DiaryContentViewController.swift
> +    private func loadWeather(coordinate: CLLocationCoordinate2D) {
CLLocationManager 인스턴스를 Helper 내부로 옮겨주면서 해결 되었습니다~!
`loadWeather`메서드는 DiaryContentViewController의 private 메서드들과 동일한 위치로 옮겨주었습니다👍

2023-05-12 08:40 UTC, July911 commented on Diary/Controller/DiaryContentViewController.swift
> +        diary.updateContents(title: currentContents.title,
LGTM :)

2023-05-12 08:41 UTC, merged