일기장 [STEP 1] Jusbug, yyss99
yagom-academy/ios-diary pull request #120
Opened 2023-08-30 08:41 UTC by JusBug

@SungPyo 
안녕하세요 웨더! 저스버그와 와이입니다!!!
이번 프로젝트 처음으로 PR 보내드립니다!!!
꼼꼼한 리뷰 잘 부탁드립니다!!! 🙏

### 고민했던 점
#### 1. <키보드 가림 이슈>

🤯 **문제상황**
`textField`에 쓰는 글이 길어지다 보면 키보드에 의해 가려지는 현상이 발생했습니다. 

🔥 **해결방법**
키보드의 높이 만큼 `textView`의 `bottomInset`을 올라가도록 만들었습니다. 그래서 글이 쓰여지는 동안에 키보드에 의해 가려지 않고 화면에 보여지게 만들었습니다.

```Swift
@objc func keyboardWillShow(_ sender: Notification) {
    if originalFrame == nil {
        originalFrame = view.frame
    }
        
    if let keyboardFrame = (sender.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue)?.cgRectValue {
        let keyboardHeight = keyboardFrame.height
        let safeAreaBottom = view.safeAreaInsets.bottom
        let contentInsets = UIEdgeInsets(top: 0, left: 0, bottom: keyboardHeight - safeAreaBottom, right: 0)
            
        bodyTextView.contentInset = contentInsets
    }
}
    
@objc func keyboardWillHide(_ sender: Notification) {
    if originalFrame != nil {
        bodyTextView.contentInset = UIEdgeInsets.zero
    }
}
```
- - -
#### 2. <TextView Placeholder 구현>

🤯 **문제상황**
기본적으로 `UITextView`에서는 `placeholder` 기능을 제공하지 않아서 직집 구현해야 하는 문제가 있었습니다. 참고로 `placeholder`는 사용자에게 입력하라는 힌트를 주는 메시지 역할로 사용자 입장에서 보다 편리한 UI 경험을 제공하기 위해서 구현하게 되었습니다.

🔥 **해결방법**
`titleTextView`, `bodyTextView`에서 둘다 사용할 수 있도록 `placeHolderText` 문자열을 전역으로 두고 `UITextViewDelegate`의 `textViewDidBeginEditing` `textViewDidEndEditing` 메서드 즉, 텍스트 뷰의 편집의 시작과 종료 시점에서 호출되는 메서드 안에 텍스트와 컬러를 정의함으로서 직접 placeholder기능을 구현하였습니다.

```Swift
let placeHolderText = "Input Text"
...
extension NewDiaryViewController: UITextViewDelegate {
    func textViewDidBeginEditing(_ textView: UITextView) {
        if titleTextView.text == placeHolderText {
            titleTextView.text = nil
            titleTextView.textColor = .black
        }
        
        if bodyTextView.text == placeHolderText {
            bodyTextView.text = nil
            bodyTextView.textColor = .black
        }
    }
    
    func textViewDidEndEditing(_ textView: UITextView) {
        if titleTextView.text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            titleTextView.text = placeHolderText
            titleTextView.textColor = .lightGray
        }
        
        if bodyTextView.text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            bodyTextView.text = placeHolderText
            bodyTextView.textColor = .lightGray
        }
    }
}
```
<Img src = "https://hackmd.io/_uploads/rkFAu_2ph.gif" width="300" height="600">

- - -
#### 3. <touchesBegan 메서드>
🤯 **문제상황**
`TextViewDelegate`의 `textViewDidEndEditing()`가 호출되기 위해서는 텍스트 뷰의 편집이 종료되어야 하는데 다른 터치이벤트를 이용하여 처리를 해주어야만 편집에서 벗어날 수 있었습니다.

🔥 **해결방법**
`touchesBegan()`는 터치 이벤트가 발생했을 때 호출되는 메서드로 뷰 안에서 편집중인 키보드를 찾아 닫을 수 있도록 해결하였습니다.
```Swift
override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
    self.view.endEditing(true)
}
```
<Img src = "https://hackmd.io/_uploads/H1T32O2T2.gif" width="300" height="600">

- - -
#### 4. <DateFormatterManager 구현>
🤯 **문제상황**
`DateFormatter`를 여러번 생성해서 사용해야 하는 상황이 발생 했습니다. 같은 역할을 하는 인스턴스를 여러번 만들어 사용하는 것이 비효율적이었습니다.

🔥 **해결방법**
`static`을 사용하여 `DateFormatter`를 한번만 생성하여 여러 곳에서 쓸 수 있도록 `CustomDateFormatter` 구조체를 만들었습니다.
```Swift
struct CustomDateFormatter {
    static let customDateFormatter: DateFormatter = {
        let todayDateFormatter = DateFormatter()
        todayDateFormatter.locale = Locale(identifier: "koKR")
        todayDateFormatter.dateFormat = "yyyy년 MM월 dd일"

        return todayDateFormatter
    }()

    static func formatTodayDate() -> String {
        let today = Date()
        let formattedTodayDate = customDateFormatter.string(from: today)

        return formattedTodayDate
    }

    static func formatSampleDate( sampleDate: Int) -> String {
        let timeInterval = TimeInterval(sampleDate)
        let inputDate = Date(timeIntervalSince1970: timeInterval)
        let formattedDate = customDateFormatter.string(from: inputDate)

        return formattedDate
    }
}
```

- - -
### 조언을 얻고 싶은 점
- 캠핑사이트 예시화면에서는 텍스트 뷰 개수가 1개인지 2개인지 분간이 어려워서 저희는 `title`과 `body`를 편집하는 텍스트 뷰를 따로 구성하였습니다. 혹시 본래 프로젝트의 요구사항이 어떤 건지 자세히 알 수 있을까요?

2023-08-31 18:48 UTC, SungPyo commented
> @SungPyo 안녕하세요 웨더! 저스버그와 와이입니다!!! 이번 프로젝트 처음으로 PR 보내드립니다!!! 꼼꼼한 리뷰 잘 부탁드립니다!!! 🙏
> 
> ### 고민했던 점
> #### 1. <키보드 가림 이슈>
> 🤯 **문제상황** `textField`에 쓰는 글이 길어지다 보면 키보드에 의해 가려지는 현상이 발생했습니다.
> 
> 🔥 **해결방법** 키보드의 높이 만큼 `textView`의 `bottomInset`을 올라가도록 만들었습니다. 그래서 글이 쓰여지는 동안에 키보드에 의해 가려지 않고 화면에 보여지게 만들었습니다.
> 
> ```swift
> @objc func keyboardWillShow(_ sender: Notification) {
>     if originalFrame == nil {
>         originalFrame = view.frame
>     }
>         
>     if let keyboardFrame = (sender.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue)?.cgRectValue {
>         let keyboardHeight = keyboardFrame.height
>         let safeAreaBottom = view.safeAreaInsets.bottom
>         let contentInsets = UIEdgeInsets(top: 0, left: 0, bottom: keyboardHeight - safeAreaBottom, right: 0)
>             
>         bodyTextView.contentInset = contentInsets
>     }
> }
>     
> @objc func keyboardWillHide(_ sender: Notification) {
>     if originalFrame != nil {
>         bodyTextView.contentInset = UIEdgeInsets.zero
>     }
> }
> ```
> 
> #### 2. <TextView Placeholder 구현>
> 🤯 **문제상황** 기본적으로 `UITextView`에서는 `placeholder` 기능을 제공하지 않아서 직집 구현해야 하는 문제가 있었습니다. 참고로 `placeholder`는 사용자에게 입력하라는 힌트를 주는 메시지 역할로 사용자 입장에서 보다 편리한 UI 경험을 제공하기 위해서 구현하게 되었습니다.
> 
> 🔥 **해결방법** `titleTextView`, `bodyTextView`에서 둘다 사용할 수 있도록 `placeHolderText` 문자열을 전역으로 두고 `UITextViewDelegate`의 `textViewDidBeginEditing` `textViewDidEndEditing` 메서드 즉, 텍스트 뷰의 편집의 시작과 종료 시점에서 호출되는 메서드 안에 텍스트와 컬러를 정의함으로서 직접 placeholder기능을 구현하였습니다.
> 
> ```swift
> let placeHolderText = "Input Text"
> ...
> extension NewDiaryViewController: UITextViewDelegate {
>     func textViewDidBeginEditing(_ textView: UITextView) {
>         if titleTextView.text == placeHolderText {
>             titleTextView.text = nil
>             titleTextView.textColor = .black
>         }
>         
>         if bodyTextView.text == placeHolderText {
>             bodyTextView.text = nil
>             bodyTextView.textColor = .black
>         }
>     }
>     
>     func textViewDidEndEditing(_ textView: UITextView) {
>         if titleTextView.text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
>             titleTextView.text = placeHolderText
>             titleTextView.textColor = .lightGray
>         }
>         
>         if bodyTextView.text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
>             bodyTextView.text = placeHolderText
>             bodyTextView.textColor = .lightGray
>         }
>     }
> }
> ```
> 
> <img alt="" height="600" src="https://camo.githubusercontent.com/0fe5435709ea1ed29a7643c619dd77621ccb2cbd9fd1d02dc26048649cce213d/68747470733a2f2f6861636b6d642e696f2f5f75706c6f6164732f726b4641755f3270682e676966"> [ <img alt="68747470733a2f2f6861636b6d642e696f2f5f75706c6f6164732f726b4641755f3270682e676966" height="600" src="https://camo.githubusercontent.com/0fe5435709ea1ed29a7643c619dd77621ccb2cbd9fd1d02dc26048649cce213d/68747470733a2f2f6861636b6d642e696f2f5f75706c6f6164732f726b4641755f3270682e676966"> ](https://camo.githubusercontent.com/0fe5435709ea1ed29a7643c619dd77621ccb2cbd9fd1d02dc26048649cce213d/68747470733a2f2f6861636b6d642e696f2f5f75706c6f6164732f726b4641755f3270682e676966) [ ](https://camo.githubusercontent.com/0fe5435709ea1ed29a7643c619dd77621ccb2cbd9fd1d02dc26048649cce213d/68747470733a2f2f6861636b6d642e696f2f5f75706c6f6164732f726b4641755f3270682e676966)
> 
> #### 3. <touchesBegan 메서드>
> 🤯 **문제상황** `TextViewDelegate`의 `textViewDidEndEditing()`가 호출되기 위해서는 텍스트 뷰의 편집이 종료되어야 하는데 다른 터치이벤트를 이용하여 처리를 해주어야만 편집에서 벗어날 수 있었습니다.
> 
> 🔥 **해결방법** `touchesBegan()`는 터치 이벤트가 발생했을 때 호출되는 메서드로 뷰 안에서 편집중인 키보드를 찾아 닫을 수 있도록 해결하였습니다.
> 
> ```swift
> override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
>     self.view.endEditing(true)
> }
> ```
> 
> <img alt="" height="600" src="https://camo.githubusercontent.com/b5fe0a2002d7468058a1ef0c633e7cb3b526347d14cfabb12237aedcb8bfceb5/68747470733a2f2f6861636b6d642e696f2f5f75706c6f6164732f48315433324f3254322e676966"> [ <img alt="68747470733a2f2f6861636b6d642e696f2f5f75706c6f6164732f48315433324f3254322e676966" height="600" src="https://camo.githubusercontent.com/b5fe0a2002d7468058a1ef0c633e7cb3b526347d14cfabb12237aedcb8bfceb5/68747470733a2f2f6861636b6d642e696f2f5f75706c6f6164732f48315433324f3254322e676966"> ](https://camo.githubusercontent.com/b5fe0a2002d7468058a1ef0c633e7cb3b526347d14cfabb12237aedcb8bfceb5/68747470733a2f2f6861636b6d642e696f2f5f75706c6f6164732f48315433324f3254322e676966) [ ](https://camo.githubusercontent.com/b5fe0a2002d7468058a1ef0c633e7cb3b526347d14cfabb12237aedcb8bfceb5/68747470733a2f2f6861636b6d642e696f2f5f75706c6f6164732f48315433324f3254322e676966)
> 
> #### 4. <DateFormatterManager 구현>
> 🤯 **문제상황** `DateFormatter`를 여러번 생성해서 사용해야 하는 상황이 발생 했습니다. 같은 역할을 하는 인스턴스를 여러번 만들어 사용하는 것이 비효율적이었습니다.
> 
> 🔥 **해결방법** `static`을 사용하여 `DateFormatter`를 한번만 생성하여 여러 곳에서 쓸 수 있도록 `CustomDateFormatter` 구조체를 만들었습니다.
> 
> ```swift
> struct CustomDateFormatter {
>     static let customDateFormatter: DateFormatter = {
>         let todayDateFormatter = DateFormatter()
>         todayDateFormatter.locale = Locale(identifier: "koKR")
>         todayDateFormatter.dateFormat = "yyyy년 MM월 dd일"
> 
>         return todayDateFormatter
>     }()
> 
>     static func formatTodayDate() -> String {
>         let today = Date()
>         let formattedTodayDate = customDateFormatter.string(from: today)
> 
>         return formattedTodayDate
>     }
> 
>     static func formatSampleDate( sampleDate: Int) -> String {
>         let timeInterval = TimeInterval(sampleDate)
>         let inputDate = Date(timeIntervalSince1970: timeInterval)
>         let formattedDate = customDateFormatter.string(from: inputDate)
> 
>         return formattedDate
>     }
> }
> ```
> 
> ### 조언을 얻고 싶은 점
> * 캠핑사이트 예시화면에서는 텍스트 뷰 개수가 1개인지 2개인지 분간이 어려워서 저희는 `title`과 `body`를 편집하는 텍스트 뷰를 따로 구성하였습니다. 혹시 본래 프로젝트의 요구사항이 어떤 건지 자세히 알 수 있을까요?


첫 PR이네요 잘 부탁드립니다.

> ### 조언을 얻고 싶은 점
> * 캠핑사이트 예시화면에서는 텍스트 뷰 개수가 1개인지 2개인지 분간이 어려워서 저희는 `title`과 `body`를 편집하는 텍스트 뷰를 따로 구성하였습니다. 혹시 본래 프로젝트의 요구사항이 어떤 건지 자세히 알 수 있을까요?
ㄴ `본래 프로젝트의 요구사항은 저도 모릅니다. 개인의 자유에 맡긴것 같아요. 저에게 이런 요구사항이 왔다면 하나로 합칠 것 같긴 합니다. 굳이 따로 만들어야 하는 이유가 있을까? 라는 생각이 들어서요!`

2023-08-31 18:52 UTC, SungPyo commented on Diary/ViewController/DetailViewController.swift
> +    @IBOutlet weak var bodyTextView: UITextView!
@IBOutlet에도 접근 제한자를 달 수 있습니다.

2023-08-31 18:52 UTC, SungPyo commented on Diary/ViewController/DetailViewController.swift
> +    private var originalFrame: CGRect?
originalFrame의 진짜 용도를 모르겠습니다.

2023-08-31 18:53 UTC, SungPyo commented on Diary/ViewController/DetailViewController.swift
> +    private var sample: Sample?
1. smaple은 init에서 받는데 var일 이유가 있나요? 
2. sample이 없을 수 없는것 같은데 옵셔널로 하신 이유 또한 궁금합니다.

2023-08-31 18:54 UTC, SungPyo commented on Diary/ViewController/DetailViewController.swift
> +    }
touchesBegan이 최선이었나요? 다른 방법은 없을까요?
어느 부분을 터치해야 하는지 상세한 스펙이 없다는게 문제라면 문제지만요 :)

2023-08-31 18:55 UTC, SungPyo commented on Diary/ViewController/DetailViewController.swift
> +        bodyTextView.layer.borderWidth = 1
self. 를 붙인 부분도 있고 붙이지 않은 부분도 있습니다.
self. 를 붙이는 본인들만의 기준이 있나요?

2023-08-31 18:58 UTC, SungPyo commented on Diary/ViewController/NewDiaryVIewController.swift
> +        super.viewDidLoad()
Detail과 하나로 합치지 않은 이유가 있으신가요?

화면의 구성은 비슷하다고 보여져서요.

2023-08-31 19:00 UTC, SungPyo requested changes
코멘트 확인해주시고, 수정이 필요하다고 생각되는 부분은 해당 pr에 수정을, 아닌 경우에는 답변 부탁드릴게요. Step2와는 별개로 Step1에서 수정해주시면 됩니다. (작업중이신 Step2에는 Step1의 수정사항이 반영되게 해주세요)

고생하셨습니다.

2023-09-01 04:10 UTC, JusBug commented on Diary/ViewController/DetailViewController.swift
> +    @IBOutlet weak var bodyTextView: UITextView!
`private`으로 은닉화 처리를 해주었습니다.

2023-09-01 04:23 UTC, JusBug commented on Diary/ViewController/DetailViewController.swift
> +    private var sample: Sample?
- init을 한 이후에 사용자에 의해 편집된 새로운 값을 할당 받을 수 있어야 되기 때문에 var로 선언해주었습니다. 
- 특별한 이유는 아니고 init으로 받아오기에 앞서 미리 선언해뒀던 부분입니다. 웨더 말씀대롤 불필요한 부분이라 옵셔널과 바인딩 처리 부분은 다시 제거하여 수정했습니다.

2023-09-01 04:28 UTC, JusBug commented on Diary/ViewController/DetailViewController.swift
> +    }
이 부분에 대해서도 저희가 고민을 했는데, 키보드의 `Return`키를 `Done`으로 수정하여 해당 키를 클릭했을 때 반환이 아닌 편집이 종료되도록 수정하려고 했습니다. 하지만 실제 아이폰의 노트 앱에서는 리턴키로 적용하고 있었기 때문에 기존과 같게 유지하였고 터치이벤트 메서드를 활용했습니다.

2023-09-01 04:35 UTC, JusBug commented on Diary/ViewController/NewDiaryVIewController.swift
> +        super.viewDidLoad()
처음에는 저희도 말씀해주신 것처럼 전체적인 구성은 동일하여 함께 처리를 하려고 했으나, 기존에 저장된 일기장 데이터를 불러오는 것과 새롭게 일기장을 생성하여 편집하는 것은 별도로 관리하는 것이 보다 가독성과 유지보수 측면에서 유리하다고 판단했습니다.

2023-09-01 04:50 UTC, JusBug commented on Diary/ViewController/DetailViewController.swift
> +        bodyTextView.layer.borderWidth = 1
기준을 정해두지는 않았고 암묵적으로 UI클래스의 메서드를 사용할 때는 `self`를 명시해주고 있고 이외에 직접 생성한 접근이 제한된 메서드는 따로 명시해주지 않고 있습니다. 이 부분은 추후에 논의를 통해서 기준을 잡도록 하겠습니다.

2023-09-01 05:18 UTC, yy-ss99 commented on Diary/ViewController/DetailViewController.swift
> +    private var originalFrame: CGRect?
처음 `frame`을 계산해주기 위해 추가했던 코드였는데 필요없는게 맞는거 같습니다! 삭제했습니다!!

2023-09-01 07:06 UTC, SungPyo commented on Diary/ViewController/DetailViewController.swift
> +    private let sample: Sample?
DetailVC에서는 Sample이 무조건 필요한 데이터가 아닌가요? 없을 수 없는 데이터일 것 같은데 말이죠..🫠

2023-09-01 07:07 UTC, SungPyo approved these changes
고생하셨습니다.

2023-09-01 07:14 UTC, yy-ss99 commented on Diary/ViewController/DetailViewController.swift
> +    private let sample: Sample?
저희가 답변 수정 하는것을 잊었습니다! 🥹 서로 이야기 해본 결과 Detail뷰를 하나로 합치는 쪽으로 변경하였습니다. 그래서 Sample 데이터가 없는 경우(nil일 때)는 새로운 일기를 추가하고 sample 데이터가 있는 경우에는 원래 있던 데이터를 띄워줄 수 있도록 하기 위해서 Sample를 옵셔널 타입으로 지정해 주었습니다!!!

2023-09-12 11:25 UTC, merged