일기장 [STEP 1] Erick
yagom-academy/ios-diary pull request #122
Opened 2023-08-31 02:17 UTC by h-suo

@1Consumption
안녕하세요 올라프 3주 동안 리뷰를 받게 된 Erick입니다! 잘 부탁드립니다! 🙇‍♂️
객체 분리와 프로토콜의 활용을 중점적으로 생각하고 코드를 작성했습니다. 
많은 조언 부탁드립니다. 😊

## 🤔 고민했던 점
### 1️⃣ 객체 분리
프로젝트의 기본적인 틀은 `MVC 패턴`으로 `Model`, `View`, `Controller`로 분리했습니다.
그리고 객체를 하나의 부품으로 생각하여 하나의 역할만 할 수 있도록 분리하였습니다.
간단하게 `Model` 객체를 나눈 기준을 설명하겠습니다.

**Model**
- DTO : `JSON` 데이터를 변환하기 위한 객체입니다.
    - DiaryEntry : 실제로 사용하는 개체이고, `DTO` 타입인 `Diary`의 `diaryEntry`를 통해 변환됩니다.
- Storage : `DiaryEntry` 타입을 저장하고 반환하는 객체입니다.
- LocaleDateFormatter : 특정 `locale`과 `timeZone`의 정보를 가지고 있고 포멧도 가지고 있는 객체입니다.
    - DateFormatManager : `LocaleDateFormatter`와 `timestamp`를 받아 원하는 `locale` 포멧으로 날짜 정보를 반환합니다.

**Controller**
`View`를 사용자 입력에 맞게 컨트롤하고, `Model`과 상호작용할 수 있도록 하는 객체입니다.
하나의 `Scene`에 많은 `View` 객체가 있다면 `View`와 `Controller`를 분리하지만, 하나의 `View` 객체만 있다면 `Controller`와 분리하지 않고 `View`를 그리는 역할도 `Controller`가 하도록 했습니다.

**View**
사용자에게 보이는 `View`에 관한 객체입니다.

### 2️⃣ 프로토콜의 활용
프로토콜을 이용해 객체를 추상화하여 다른 객체와 소통할 때 실제 객체와 소통하는 것이 아닌 추상화된 프로토콜을 통해 소통할 수 있도록 했습니다.

**DiaryStorageProtocol**
```swift
protocol DiaryStorageProtocol {
    func diaryEntrys() -> [DiaryEntry]
    func storeDiary(_ diary: DiaryEntry)
}
```
- `DiaryStorageProtocol`은 `DiaryEntry`를 저장하고 불러올 수 있는 타입입니다.
- 현재는 `AssetData`를 가져오기만 하지만 추후 `CoreData`나 다른 저장방법을 사용하게 된다면 `DiaryEntry`를 저장하거나 불러와야 한다고 생각하여 생성하였습니다.

**LocaleDateFormatterProtocol**
```swift
protocol LocaleDateFormatterProtocol {
    var dateFormatter: DateFormatter { get }
    
    func string(from date: Date) -> String
}

extension LocaleDateFormatterProtocol {
    func string(from date: Date) -> String {
        return dateFormatter.string(from: date)
    }
}
```
- `LocaleDateFormatterProtocol`는 특정 `locale` 정보를 가진 `dateFormatter`를 가지고 있고 `Date`를 이용해 포맷하는 기능만을 제공하는 타입입니다.
- 현재는 사용자의 `locale`을 가져와 날짜를 포맷하지만 다른 `locale`로 포맷하고 싶을 때 `LocaleDateFormatterProtocol`을 채택하는 객체를 만들어 `DateFormatManager`에서 주입받아 사용할 수 있도록 했습니다.

### 3️⃣ 코드 재사용
일기를 보여주고 작성하는 `DiaryViewController`에서 키보드가 보였을 때 `textView`가 가려지지 않도록 하는 코드가 있었습니다.
이 코드를 `ViewController`가 직접 가지고 있다면, 다른 `ViewController`에서 같은 기능을 사용하고 싶을 때 똑같은 코드를 다시 작성해 중복 코드가 늘어날 수 있다고 생각하였습니다.
따라서 `UITextView`를 확장하여 이 코드를 가지고 있고 `UITextView`를 가지고 있는 객체는 언제든 메서드를 이용해서 기능을 사용할 수 있도록 했습니다.

```swift
extension UITextView {
    
    func addObserveKeyboardNotification() {
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillShow(_:)), name: UIResponder.keyboardWillShowNotification, object: nil)
    }
    
    @objc private func keyboardWillShow(_ notification: Notification) {
        if let keyboardFrame = notification.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? CGRect {
            let keyboardHeight = keyboardFrame.height
            
            self.contentInset = UIEdgeInsets(top: .zero, left: .zero, bottom: keyboardHeight, right: .zero)
        }
    }
}
```
- `addObserveKeyboardNotification`를 이용해 키보드가 보이기 직전에 오는 노티를 관찰하는 옵져버를 추가할 수 있도록 했습니다.
    - 노티가 발생했을 때 `keyboardWillShow`가 실행될 수 있도록 했습니다.
- `keyboardFrameEndUserInfoKey`을 키로 노티의 `userInfo`에서 키보드의 프레임을 받아와 그 높이로 `UITextView`의 `Inset`의 `bottom`을 설정하여 키보드가 올라온 높이만큼 뷰도 올라가도록 했습니다.

## 🙇‍♂️ 조언을 얻고싶은 점
### 1️⃣ 뷰컨의 재사용
현재 프로젝트에서 일기를 보여주는 뷰와 일기를 작성하는 뷰가 크게 다르지 않다고 생각하여 하나의 `DiaryViewController`를 재사용하였습니다.
추후 일기를 저장하는 기능이 생긴다면 `diaryEntry`의 유무로 `Button`의 `hidden`을 결정하도록 해서 하나의 `DiaryViewController`를 두 가지 경우에 모두 사용할 수 있다고 생각했습니다.
이렇게 `ViewController`를 재사용하는 것이 괜찮을지, 실제로도 이렇게 재사용하는 경우가 있는지 올라프의 조언을 얻고 싶습니다.

---
### 📚 참고 링크
- [Apple: locale](https://developer.apple.com/documentation/foundation/dateformatter/1411973-locale)
- [Apple: setLocalizedDateFormatFromTemplate](https://developer.apple.com/documentation/foundation/dateformatter/1417087-setlocalizeddateformatfromtempla)
- [Apple: timezone](https://developer.apple.com/documentation/foundation/dateformatter/1411406-timezone)
- [Apple: keyboardWillShowNotification](https://developer.apple.com/documentation/uikit/uiresponder/1621576-keyboardwillshownotification)
- [Apple: keyboardFrameEndUserInfoKey](https://developer.apple.com/documentation/uikit/uiresponder/1621578-keyboardframeenduserinfokey)

2023-08-31 11:46 UTC, 1Consumption requested changes
고생하셨습니다.
이번은 스텝이 작아서 별다른 코멘트는 없습니다.

그런데 테스트 타겟을 테스트별로 분리한 이유가 궁금합니다.

2023-08-31 11:46 UTC, 1Consumption commented on Diary/Controller/DiaryListViewController.swift
> +            cell.setupContent(title: item.title, creationDate: item.creationDate, body: item.body)
그냥 item만 넘기는건 어떨까요? 굳이 풀어서 넘길 이유는 없어보입니다.

2023-08-31 11:46 UTC, 1Consumption commented on Diary/Controller/DiaryListViewController.swift
> +        tableView.dataSource = dataSource
혹시 DiffableDataSource의 공식문서를 꼼꼼하게 읽어보셨을까요?
https://developer.apple.com/documentation/uikit/uitableviewdiffabledatasource

<img width="984" alt="image" src="https://github.com/yagom-academy/ios-diary/assets/37682858/ce42eb31-cc81-420d-a7b6-74d04e51b43c">

2023-08-31 11:46 UTC, 1Consumption commented on Diary/Controller/DiaryListViewController.swift
> +        setupContentTableView()
UI가 그려지기 전에 이 메소드가 호출되는 것은 순서가 맞지 않다고 생각합니다.

2023-08-31 11:46 UTC, 1Consumption commented on DateFormatManagerTests/DateFormatManagerTests.swift
> +    }
이 테스트는 어떤 의미를 가지나요? 호스트앱에 있는 코드를 테스트하는 것이 아니라, 테스트 타겟에 있는 코드를 테스트하는 것 같은데요.

2023-08-31 11:46 UTC, 1Consumption commented on Diary/Model/Storage/AssetDiaryStorage.swift
> +        }
이런 경우는 빈 배열을 보내면 의미가 모호해지니까, error를 throw하는게 좋을 것 같습니다.

2023-08-31 12:37 UTC, h-suo commented on Diary/Controller/DiaryListViewController.swift
> +            cell.setupContent(title: item.title, creationDate: item.creationDate, body: item.body)
`setupContent`가 `DiaryEntry` 타입을 받도록 수정하였습니다! 😊

2023-08-31 12:40 UTC, h-suo commented on Diary/Controller/DiaryListViewController.swift
> +        tableView.dataSource = dataSource
문서를 꼼꼼하게 확인하지 못한 것 같습니다..🥲
`tableView.dataSource`를 변경하는 코드는 제거하였습니다!

2023-08-31 12:45 UTC, h-suo commented on Diary/Controller/DiaryListViewController.swift
> +        setupContentTableView()
UI가 그려진 이후에 호출될 수 있도록 순서를 변경해주었습니다!

2023-08-31 12:55 UTC, h-suo commented on DateFormatManagerTests/DateFormatManagerTests.swift
> +    }
테스트는 객체를 시험하는 것뿐만 아니라 문서의 역할도 할 수도 있다고 생각하였습니다.
`DateFormatManager `가 `LocaleDateFormatterProtocol`을 파라미터로 받아 특정 `Locale`의 포맷으로 `Date`를 변환할 수 있다는 것을 보여주기에는 `UserDateFormatter`만을 이용한 테스트는 부족한 것 같아 `LocaleDateFormatterProtocol`을 채택하는 객체를 추가하여 진행한 테스트입니다.

2023-08-31 12:57 UTC, h-suo commented on Diary/Model/Storage/AssetDiaryStorage.swift
> +        }
`StorageError`를 만들어 `loadDataFailed` 에러를 `throw` 하도록 수정했습니다!

2023-09-01 01:08 UTC, 1Consumption commented on DateFormatManagerTests/DateFormatManagerTests.swift
> +    }
글쎄요.. 그렇다면 에릭이 만들어주신 JapanDateFormatter는 어떻게 제대로된 값을 줄거라고 확신할 수 있을까요? 테스트 코드를 위한 테스트를 작성해야할까요?

2023-09-01 01:10 UTC, 1Consumption commented on Diary/Controller/DiaryListViewController.swift
> +            presentFailAlert()
alert를 띄워 사용자에게 에러가 발생했음을 인지시켜주는 것은 좋습니다.
그런데 prtin문은 제거해주세요~

2023-09-01 01:57 UTC, h-suo commented on DateFormatManagerTests/DateFormatManagerTests.swift
> +    }
말씀해주신 대로 테스트 코드를 위한 테스트는 적절하지 않은 것 같아 `JapanDateFormatter`와 테스트 코드를 삭제했습니다.
https://github.com/yagom-academy/ios-diary/pull/122/commits/20633bf5f6690224c3b2402f808b003ec386ed1b

2023-09-01 01:58 UTC, h-suo commented on Diary/Controller/DiaryListViewController.swift
> +            presentFailAlert()
넵! print문 제거했습니다! 🫡
https://github.com/yagom-academy/ios-diary/pull/122/commits/59d4f2ac4fce1aa569864e4b9bb6178d4dac32dc

2023-09-01 01:59 UTC, merged