일기장 [STEP 1] hoon, karen
yagom-academy/ios-diary pull request #123
Opened 2023-08-31 18:40 UTC by Hoon94

안녕하세요. `July!`(@July911)😊
이번 일기장 리뷰를 받게 된 `hoon`🐝, `keren`🦦입니다.
첫 `Step01 PR` 보냅니다. 천천히 보시고 리뷰 남겨주시면 감사하겠습니다.
3주 동안 잘 부탁드립니다.🙇🏻‍♀️

## 🤔 고민한 부분
### 1️⃣ 지역별 현지화
- `JSON` 파일에서 받아온 날짜를 디바이스의 지역에 맞는 형식으로 표현해 주기 위해 아래와 같이 `Locale`을 사용하였습니다.

    ```swift
    extension DateFormatter {
        static let diaryFormatter = {
            let formatter = DateFormatter()
            formatter.dateStyle = .long
            formatter.locale = Locale.current

            return formatter
        }()
    }

    // 적용
    let date = Date(timeIntervalSince1970: diaryModel[indexPath.row].date)
    let formattedDate = DateFormatter.diaryFormatter.string(from: date)
    ```

    지역에 맞게 날짜의 형식을 변경해 주는 `diaryFormatter`를 사용하여 `JSON` 데이터를 디코딩 한 값인 `date`(`Double` 타입)을 매개변수로 전달하였습니다.

<br>

## 🙇🏻‍♀️ 조언을 얻고 싶은 부분
### 1️⃣ 일기장 상세 화면 레이아웃 구성
- 현재 `DiaryDetailViewController`의 레이아웃 구성은 `UITextView`인 `titleTextView`, `bodyTextView`로 이루어져 있습니다. 각각 일기의 제목과 본문 내용을 나타냅니다. 이렇게 레이아웃을 구성하는 경우 제목과 본문을 작성하거나 수정할 때 특정 영역만 선택할 수 있다는 장점이 있다고 생각하였습니다. 하지만 본문을 스크롤 하여 내리는 경우에 제목은 계속 상단에 위치하고 있다는 점에서 레이아웃 구성을 어떻게 하면 좋을지 궁금합니다.

### 2️⃣ 추상화 레벨
- 코드의 전반적인 추상화 레벨을 맞추기 위하여 메서드를 구분하였습니다.

    ```swift
    override func viewDidLoad() {
        super.viewDidLoad()
        configure()
        parseData()
    }

    func configure() {
        configureRootView()
        configureNavigation()
        configureTableView()
        registerCell()
        configureSubviews()
        configureConstraints()
    }
    ```

    이렇게 메서드를 구분하기 위해서 각각의 기능에 맞게 메서드를 세분화하여 구현하였습니다. 추가적으로 추상화 레벨을 맞추려다 보니 불필요하게 메서드가 많아지는 경우도 생길 것 같은데 이런 부분은 어떻게 해결하면 좋을지 궁금합니다.
 
### 3️⃣ 키보드 제약조건
- 키보드가 올라왔을 때 `textView`가 가려지지 않게끔 제약조건을 걸어주려고 할 때 `keyboardLayoutGuide.topAnchor`를 활용하려고 할 경우에 `iOS` 버전을 15.0으로 올려주어야 적용이 가능합니다.

    ```swift
    contentStackView.bottomAnchor.constraint(equalTo: view.keyboardLayoutGuide.topAnchor)
    ```

    짧고 간결하게 코드를 적용하기에는 적합한 방법이지만 구 버전에서는 적용이 되지 않는 부분이 발생합니다. 구 버전 모델들에서도 적용되게 구현하는 방법으로 선택을 해서 하는 것이 좋을까요? 아니면 현재 적용돼 있는 방법으로 구현하는 게 좋을까요?

2023-09-01 07:47 UTC, July911 requested changes

2023-09-01 07:47 UTC, July911 commented on Diary/Controller/DiaryDetailViewController.swift
> +private extension DiaryDetailViewController {
이렇게 하니까 더 보기 깔끔한 것 같네요 !

2023-09-01 07:47 UTC, July911 commented on Diary/Controller/DiaryViewController.swift
> +            self.navigationController?.pushViewController(diaryDetailViewController, animated: true)
순환 참조 문제는 없을까요 ?

2023-09-01 07:47 UTC, July911 commented on Diary/Controller/DiaryViewController.swift
> +        tableView.register(DiaryCell.self, forCellReuseIdentifier: "cell")
forCellReuseIdentifier: "cell" 이렇게 해주신 이유가 있을까요 ? 
추후 다른 셀이 생긴다면 어떻게 대응하실건가요 ?

2023-09-01 07:47 UTC, July911 commented on Diary/View/DiaryCell.swift
> +
지금 굳이 필요할까 싶긴 하지만, prepareForReuse 가 뭔지 알아보고 말씀주세요 :)

2023-09-01 07:47 UTC, July911 commented on Diary/Controller/DiaryViewController.swift
> +            title: diaryModel[indexPath.row].title,
[indexPath.row] 이걸 하나의 상수로 뺄 거 같네요 :)

2023-09-01 07:47 UTC, July911 commented on Diary.xcodeproj/project.pbxproj
> +				78274D9D2A9E31AA00AD4F50 /* Controller */,
화면단위가 아니라  layer단위로 나눈 이유가 있으신가요 ? 단순한 질문입니다 !

2023-09-01 07:47 UTC, July911 commented on Diary/Application/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
왜 사용하는거고 어떤 동작을 하나요 ?

2023-09-01 07:47 UTC, July911 commented on Diary/Controller/DiaryDetailViewController.swift
> +    init(title: String = "", body: String = "", date: Date = Date()) {
기본값을 주신 이유는 무엇인가요 ? 공백으로 만들어질 수 있게 하기 위함일까요 ?

2023-09-01 07:47 UTC, July911 commented on Diary/Controller/DiaryViewController.swift
> +            return
따로 처리는 안해주나요?

2023-09-01 07:47 UTC, July911 commented on Diary/Controller/DiaryViewController.swift
> +extension DiaryViewController: UITableViewDataSource, UITableViewDelegate {
개인적인 생각(취향)이지만, 프로토콜을 하나식 extension으로 나누는게 보기 편한 것 같습니다 !

2023-09-01 07:47 UTC, July911 commented on Diary/Controller/DiaryViewController.swift
> +    private var diaryModel: [DiaryModel] = []
1. model 이라는 표현이 조금 어색한거같습니다. 
2. 복수도 아니구요 !

2023-09-01 07:47 UTC, July911 commented on Diary/Controller/DiaryViewController.swift
> +        guard let cell = tableView.dequeueReusableCell(withIdentifier: "cell") as? DiaryCell else {
"cell" 이라는 표현이 맞을까요 ?

2023-09-01 07:47 UTC, July911 commented on Diary/View/DiaryCell.swift
> +            contentStackView.topAnchor.constraint(equalTo: contentView.layoutMarginsGuide.topAnchor),
layoutMarginsGuide 는 무엇일까요 ? 
VC에서 쓰셨던거랑 어떤게 다른가요 ?

2023-09-01 12:50 UTC, Hoon94 commented on Diary/Controller/DiaryDetailViewController.swift
> +private extension DiaryDetailViewController {
감사합니다 줄라이😊

2023-09-01 13:21 UTC, karenyang835 commented on Diary/Controller/DiaryViewController.swift
> +        tableView.register(DiaryCell.self, forCellReuseIdentifier: "cell")
https://github.com/yagom-academy/ios-diary/pull/123/commits/aaef2b9d599cad77282bdd76cc45378d42e49b1b

`CellIdentifier`를 사용하여 매직리터럴을 대체해 주었습니다. 추후 다른 `Cell`이 생긴다면 `NameSpace`에 추가하여 사용할 수 있을 것 같습니다.

2023-09-01 13:31 UTC, Hoon94 commented on Diary/Controller/DiaryViewController.swift
> +            title: diaryModel[indexPath.row].title,
[591f436](https://github.com/yagom-academy/ios-diary/pull/123/commits/591f436fcb4d845f619d737b5dbef59996b12d6d)

`index` 상수로 수정하였습니다.😆

2023-09-01 14:18 UTC, karenyang835 commented on Diary/Controller/DiaryViewController.swift
> +            return
https://github.com/yagom-academy/ios-diary/pull/123/commits/7cbe063fdb1ed98f403aa68b4049b775ab97e233

`Data`를 받아오지 못했을 경우에 `Alert`를 띄워서 확인할 수 있도록 수정해주었습니다.

2023-09-01 14:24 UTC, Hoon94 commented on Diary/Controller/DiaryViewController.swift
> +extension DiaryViewController: UITableViewDataSource, UITableViewDelegate {
https://github.com/yagom-academy/ios-diary/pull/123/commits/7f832b37f413b2aaa8ae905abda370c15bb6caee

`UITableViewDelegate`와 `UITableViewDataSource` `extension`을 각각 분리하였습니다.

2023-09-01 14:32 UTC, karenyang835 commented on Diary/Controller/DiaryViewController.swift
> +    private var diaryModel: [DiaryModel] = []
https://github.com/yagom-academy/ios-diary/pull/123/commits/984f7e38e321ce0af820a481f1015007722c73a8

`diaryList`로 네이밍을 변경해 주었습니다.

2023-09-01 14:34 UTC, Hoon94 commented on Diary/Controller/DiaryViewController.swift
> +        guard let cell = tableView.dequeueReusableCell(withIdentifier: "cell") as? DiaryCell else {
https://github.com/yagom-academy/ios-diary/pull/123/commits/aaef2b9d599cad77282bdd76cc45378d42e49b1b

`CellIdentifier`를 사용하여 매직리터럴을 대체해 주었습니다.☺️

2023-09-01 14:43 UTC, karenyang835 commented on Diary.xcodeproj/project.pbxproj
> +				78274D9D2A9E31AA00AD4F50 /* Controller */,
`MVC`패턴에 맞추어 `layer` 단위로 나누어주었습니다.

`July`께서 말씀해주시는 화면단위로 나누는 것은 혹시 어떤걸 말씀하시는 걸까요?

2023-09-01 14:48 UTC, Hoon94 commented on Diary/Controller/DiaryDetailViewController.swift
> +    init(title: String = "", body: String = "", date: Date = Date()) {
셀을 선택하여 다음 화면으로 넘어가는 경우와 `+` 버튼을 사용하여 다음 화면으로 넘어가는 경우 모두 같은 `DiaryDetailViewController`를 사용합니다. 두 가지 방법에서 사용하는 레이아웃은 같지만 전달인자로 넘겨주는 값이 다르기 때문에 `+`의 경우에는 기본값을 사용하여 `DiaryDetailViewController`를 초기화하였습니다.😊

2023-09-01 15:07 UTC, Hoon94 commented on Diary/View/DiaryCell.swift
> +            contentStackView.topAnchor.constraint(equalTo: contentView.layoutMarginsGuide.topAnchor),
`VC`에서 사용한 `safeAreaLayoutGuide`는 전체 화면에서 [특정 부분](https://developer.apple.com/documentation/uikit/uiview/2891102-safearealayoutguide)을 제외한 화면을 나타냅니다.
`layoutMarginsGuide`는 `view`에서 `inset`의 크기만큼 떨어진 거리를 제외한 영역을 표현합니다.😁

참고 링크: [layoutMarginsGuide](https://woozzang.tistory.com/147)

2023-09-02 12:43 UTC, karenyang835 commented on Diary/View/DiaryCell.swift
> +
`UITableView`는 매번 셀을 새로 만들지 않고 이전에 표시된 셀을 재사용하여 메모리 사용량을 줄이고 성능을 향상시키는데 이때 재사용되는 셀의 상태를 초기화하고 새로운 데이터를 셀에 설정하는 메서드입니다.

2023-09-02 12:43 UTC, karenyang835 commented on Diary/Application/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
- 스토리보드를 활용하여 진행하면 `UIWindow`객체를 새로 만들 필요가 없지만 코드베이스로 진행을 하기 위해 `mainstoryboard`를 없애면 어떤 화면을 보여줄지 모르는 상태가 됩니다.
- 코드로 새로운 `UIWindow`를 생성하고 `window`와 초기 `View controller`를 인스턴스화 해주고 새 `viewController`를 `root view controller`의 프로퍼티에 할당하고 `window`를 표시해 주는 코드입니다. (현재 프로젝트 파일에서는 `storyBoard`가 그대로 존재하는데 테스트를 위해 아직 삭제하지 않은 상태일 뿐 스토리보드로 프로젝트를 진행하지는 않았습니다.)
- window?.makeKeyAndVisible() : `keyWindow`를 보이게 해주는 메소드입니다.

2023-09-02 14:07 UTC, Hoon94 commented on Diary/Controller/DiaryViewController.swift
> +            self.navigationController?.pushViewController(diaryDetailViewController, animated: true)
클로저 코드 블럭 내부에서 생성한 `diaryDetailViewController`를 사용하여 매개변수를 넘기기 때문에 현재 클로저의 캡처에서는 순환 참조에 대한 문제가 없다고 생각하였습니다.🤔

2023-09-04 00:28 UTC, merged