일기장 [STEP 1] MINT, BMO
yagom-academy/ios-diary pull request #124
Opened 2023-09-01 06:23 UTC by mint3382

@1Consumption
안녕하세요 올라프!
이번 프로젝트에서 리뷰이가 된 MINT😈, BMO🤖입니다!
일기장 프로젝트 STEP 1 PR 보냅니다.
잘 부탁드립니다 🙇‍♂️

---

## 고민했던 점
### 1️⃣ Swift Lint 규칙변경
`Pod`을 통해 `SwiftLint`를 설치하고 프로젝트에 적용했습니다. `Lint`는 프로젝트 빌드 시 코드 컨벤션에 대한 경고를 띄워주었고, 경고를 모두 없애면 전체적으로 읽기 좋은 코드가 되었습니다.
하지만 `Lint`를 모두 따르기에는 어색한 부분이 있었는데, 줄바꿈에 대한 부분이었습니다.
> `SwiftLint`가 경고를 띄우는 부분
```swift
struct 구조체 {
    let 프로퍼티1
    let 프로퍼티2
    // Trailing Whitespace Violation: Lines should not have trailing whitespace (trailing_whitespace) 
    func 메서드1() {}
    func 메서드2() {}
    // Trailing Whitespace Violation: Lines should not have trailing whitespace (trailing_whitespace)
    enum 열거형 {
        case 경우1
        case 경우2
    }
}
```
저희 팀은 줄바꿈은 `SwiftLint`의 제안을 받아들이기보다 저희의 컨벤션을 지키고 싶었으나, `XCode`의 `Issue Navigator`에 `Lint`로 인한 경고가 많이 누적되는것을 보고싶지 않았습니다.

그러던 중 `SwiftLint`의 기본 옵션을 변경할 수 있다는 것을 알게 되었습니다.
[SwiftLint Rule](https://realm.github.io/SwiftLint/rule-directory.html)에 따르면 경고에 계속 노출되었던 `trailing_whitespace`는  줄 뒤에 공백이 있어서는 안 됨을 의미합니다.
프로젝트 `root` 경로에 `.swiftlint.yml` 파일을 만들고 내부에 다음 내용을 작성했습니다.
```yml
# 기본 활성화된 룰 중에 비활성화할 룰을 지정
disabled_rules:
    - trailing_whitespace
```
`disabled_rules`에 `trailing_whitespace`를 추가함으로써 `Lint`가 줄바꿈 관련된 경고를 띄우지 않도록 변경했습니다.

### 2️⃣ 일기 작성 및 수정 시 textView 개수 선택
제목과 본문의 구현을 어떻게 해야할지에 대한 고민이 있었습니다. 제목 `textView`와 본문 `textView`를 나누고 `stackView`에 넣어줄 경우 여러가지 문제점이 생겼습니다. 
1. 제목에 특정한 제약을 주지 않아 길어지게 되서 한 화면을 전부 차지하게 될 경우 본문 `textView`로 넘어갈 수가 없다.
2. 본문 `textView`를 스크롤 할 경우 제목은 올라가지 않고 계속 남아있게 된다.

위 문제들로 인해 `textView`를 제목과 본문으로 나누지 않고 `contentTextView`라는 하나의 `textView`에서 제목과 본문을 모두 입력받을 수 있게 변경하여 처리했습니다.

---

## 해결하지 못한 점
### 1️⃣ textView 조건 처리
요구사항에 있는 일기장 하나의 페이지가 스크롤 된 짤이 없어서 본문을 스크롤 하여 올릴 때 제목도 같이 올라가는지에 대한 여부가 불분명했습니다. 때문에 저희는 같이 올라간다고 가정하고, 하나의 textView로 처리하였습니다. 다만 이 경우에 제목과 본문을 구분하는 것에 있어서 추후에 수정하면 불분명해질 수 있다는 문제점이 있었는데, 두번째 줄을 항상 공백으로 두는 방법을 찾지 못했습니다.

---

## 조언을 얻고 싶은 점
### 1️⃣ iOS 타겟 버전 변경 - UIKeyboardLayoutGuide
키보드를 사용할 때 글자를 가리는 일이 생겨 `textView`도 같이 올려주는 방법에 대한 고민이 있었습니다. 그 중에서도 두가지 방법을 찾을 수 있었습니다.
1. `Notification`을 사용하여 키보드가 올라올 때마다 키보드의 `contentInset`을 빼주는 방법
2. `keyboardLayoutGuide`를 제약 조건에 적용하는 방법

간단하기는 2번이 간단했지만 `iOS 15.0` 부터 사용할 수 있어 고민이 있었습니다.

1번의 방법을 사용할 때 `keyboardFrameEndUserInfoKey`을 사용합니다. 그런데 [keyboardFrameEndUserInfoKey](https://developer.apple.com/documentation/uikit/uiresponder/1621578-keyboardframeenduserinfokey) 공식문서를 보면 다음 내용이 있었습니다.
> Important
>
> Instead of using this key to track the keyboard’s frame, consider using UIKeyboardLayoutGuide, which allows you to respond dynamically to keyboard movement in your app. For more information, see [Adjusting Your Layout with Keyboard Layout Guide](https://developer.apple.com/documentation/uikit/keyboards_and_input/adjusting_your_layout_with_keyboard_layout_guide).
> 
> 이 키를 사용하여 키보드 프레임을 추적하는 대신 앱의 키보드 움직임에 동적으로 반응할 수 있는 UIKeyboardLayoutGuide를 사용하는 것이 좋습니다. 자세한 내용은 [키보드 레이아웃 가이드로 레이아웃 조정](https://developer.apple.com/documentation/uikit/keyboards_and_input/adjusting_your_layout_with_keyboard_layout_guide)을 참조하세요.
 
[UIKeyboardLayoutGuide](https://developer.apple.com/documentation/uikit/uikeyboardlayoutguide)는 `iOS 15.0` 이후로 지원하기 때문에 2번의 방법을 선택하여 진행했습니다.

올라프라면 이 경우에 어떤 방법을 선택하실지 의견을 듣고 싶습니다.

2023-09-01 11:27 UTC, 1Consumption requested changes
안녕하세요 @mint3382 @bubblecocoa 
고생하셨습니다.

스텝이 작아 코멘트가 많지는 않습니다.

먼저, 해결하지 못한 점에 적어주신 부분이 어떤 말인지 잘 이해하지 못했습니다.
조금 더 자세히 설명해주시면 감사하겠습니다.

조언을 얻고싶은 점에 적어주신 부분에 대해서는
`현재 프로덕트의 버전을 따라간다`로 말씀을 드릴 수 있겠습니다.
토이프로젝트라면 버전 상관 없이 쓰고싶은 것을 쓰겠지만, 회사 프로젝트의 버전은 마음대로 올리지 못하니까요.

추가적으로.. Pods에 해당하는 파일들은 깃헙에 올리지 말아주세요. 어차피 Podfile에 다 명시가 되어있고, pod install을 통해 받을 수 있는 정보입니다.

혹시나 수정사항이 발생하면 코멘트에 커밋 링크를 같이 첨부해주세요.

나머지는 코멘트를 참고해주세요.

2023-09-01 11:27 UTC, 1Consumption commented on Diary/App/AppDelegate.swift
> +import CoreData
필요한 import 인가요?

2023-09-01 11:27 UTC, 1Consumption commented on Diary/Error/DataLoadError.swift
> +enum DataLoadError: Error {
LocalizedError에 대해 알아보세요.

2023-09-01 11:27 UTC, 1Consumption commented on Diary/View/DiaryTableViewCell.swift
> +    }
불필요한 오버라이드 같습니다.

2023-09-01 11:27 UTC, 1Consumption commented on Diary/View/DiaryTableViewCell.swift
> +    }
여기도요.

2023-09-01 11:27 UTC, 1Consumption commented on Diary/ViewController/DiaryListViewController.swift
> +            }
이런 구체적인 로직을 다른 객체로 빼면 좋겠습니다. view에서 너무 많은 정보를 알고 있어요.

2023-09-01 11:27 UTC, 1Consumption commented on Diary/ViewController/DiaryListViewController.swift
> +    }
이런 오류는 사용자가 알 수 있을까요?

2023-09-01 11:27 UTC, 1Consumption commented on Diary/ViewController/DiaryListViewController.swift
> +        }
여기는 weak self를 안붙여줘도 될까요?

2023-09-01 11:27 UTC, 1Consumption commented on Diary/ViewController/DiaryViewController.swift
> +        if titleLine == false && text == "\n" {
titleLine이 뭘 뜻하는 변수인지 잘 모르겠습니다.

2023-09-01 15:10 UTC, mint3382 commented on Diary/ViewController/DiaryListViewController.swift
> +        }
addDiary 내부에는 self를 참조하는 내용이 없어서 순환 참조가 일어나지 않을 것이기에 weak self를 붙이지 않았습니다.

2023-09-01 15:28 UTC, mint3382 commented on Diary/ViewController/DiaryListViewController.swift
> +    }
alert을 사용하여 사용자에게 표시하도록 하였습니다!

2023-09-01 16:03 UTC, bubblecocoa commented on Diary/ViewController/DiaryViewController.swift
> +        if titleLine == false && text == "\n" {
https://github.com/yagom-academy/ios-diary/pull/124/commits/45e1231422009b1595367954b62303c4acae7b0e
해당 프로퍼티 명을 `hasTitleLine`으로 변경했습니다.

2023-09-01 16:03 UTC, mint3382 commented on Diary/App/AppDelegate.swift
> +import CoreData
CoreData는 불필요한 import라 삭제하였습니다.

관련 커밋: https://github.com/yagom-academy/ios-diary/pull/124/commits/c51cdfe8ab6fee9e80fb346ebd545ef378c727ff

2023-09-01 16:05 UTC, mint3382 commented on Diary/Error/DataLoadError.swift
> +enum DataLoadError: Error {
LocalizedError를 사용하여 Error와 관련한 메세지를 지정해 한번에 에러를 찾아서 메세지를 띄울 수 있게 추가 구현 하였습니다.

관련 커밋: https://github.com/yagom-academy/ios-diary/pull/124/commits/46c1102b1515ba78371f2f96bbaae60717447f64

2023-09-01 16:05 UTC, mint3382 commented on Diary/View/DiaryTableViewCell.swift
> +    }
삭제하였습니다!

관련 커밋: https://github.com/yagom-academy/ios-diary/pull/124/commits/7efc69e1d044ca91a2030818d6cd2615d3eb47e3

2023-09-01 16:05 UTC, bubblecocoa commented on Diary/ViewController/DiaryListViewController.swift
> +            }
https://github.com/yagom-academy/ios-diary/pull/124/commits/d69733f9dff9d272aba5d8d1d98ad84d3d5435da, https://github.com/yagom-academy/ios-diary/pull/124/commits/41f76ad7a051bb1be585101f7f3269e17541cbc7, https://github.com/yagom-academy/ios-diary/pull/124/commits/16ffa092db880e5f483a290176d20165c145931d
해당 로직을 `DiaryService`가 가지고 있도록 분리했습니다.
`DiaryService`는 의존성 주입을 통해 사용하도록 했습니다.

2023-09-01 16:05 UTC, mint3382 commented on Diary/View/DiaryTableViewCell.swift
> +    }
삭제하였습니다! 

관련 커밋: https://github.com/yagom-academy/ios-diary/pull/124/commits/7efc69e1d044ca91a2030818d6cd2615d3eb47e3

2023-09-01 16:39 UTC, 1Consumption commented on Diary/ViewController/DiaryViewController.swift
> +        if titleLine == false && text == "\n" {
title line이 뭘 말하는걸까요...?

2023-09-01 16:40 UTC, merged

2023-09-02 02:22 UTC, bubblecocoa commented on Diary/ViewController/DiaryViewController.swift
> +        if titleLine == false && text == "\n" {
`contentTextView`의 첫번째 줄을 `title line`으로 생각했습니다.