일기장 [STEP 2] Max, Hemg
yagom-academy/ios-diary pull request #128
Opened 2023-09-06 05:35 UTC by hemg2

> 일기장 [STEP 2] Hamg, maxhyunm

안녕하세요 그린!(@GREENOVER)
일기장 STEP 2 PR 올려드립니다.
코어 데이터 처리로 많이 헤맸던 것 같습니다😂
이번 스텝도 리뷰 잘 부탁드립니다!🙇‍

## 고민했던 점
### 🔹 Core Data 처리용 로직 위치
처음에는 `SceneDelegate` 또는 `AppDelegate`에 `PersistentContainer`와 `saveContext` 메서드를 두려고 했습니다. 하지만 이 두 가지 내용을 포함하여, CRUD 작업 전반과 관련된 내용을 별개의 타입으로 분리하여 `CoreDataManager`를 만들면 좀 더 깔끔히 관리할 수 있을 것 같다는 생각이 들었습니다. 이에 따라 아래와 같이 새로운 타입을 생성하였습니다.
Manager 타입은 하나의 인스턴스를 앱 전체가 공통적으로 사용하므로 싱글톤 처리를 하였습니다.
```swift
class CoreDataManager {
    static let shared = CoreDataManager()
    private init() {}
        
    func fetchDiary() throws -> [Diary] {
        ...
    }
    
    func createDiary() -> Diary {
        ...
    }
    
    func deleteDiary(_ diary: Diary?) {
        ...
    }
    
    // MARK: - Core Data stack
    lazy var persistentContainer: NSPersistentContainer = {
        ...
    }()

    func saveContext () {
        ...
    }
}
```

### 🔹 일기 생성/수정 처리 방식
일기 신규 생성과 기존 일기 수정 작업은 모두 `CreateDiaryViewController`를 통해 구현됩니다.
이때 신규/수정 여부를 구분하기 위해, 수정 작업인 경우에는 `init`을 통해 수정할 일기 인스턴스를 전달해줄 수 있도록 새로운 생성자를 추가하였습니다. 또한 신규 작업인 경우에는 `init`에서 uuid, 날짜만 입력된 새로운 `diary` 객체를 생성하도록 하였습니다.
```swift
 init() {
     self.diary = CoreDataManager.shared.createDiary()
     self.isNew = true
     super.init(nibName: nil, bundle: nil)
 }
 
 init(_ diary: Diary) {
     self.diary = diary
     self.isNew = false
     super.init(nibName: nil, bundle: nil)
 }
```

### 🔹 일기 자동저장 구현 방식
요구사항에 따른 자동저장 시기는 다음과 같았습니다.
- 사용자가 입력을 멈추는 경우(키보드가 사라지는 경우)
- 앱이 백그라운드로 진입하는 경우
- 이전 화면(리스트 화면)으로 이동하는 경우

이에 따라 `UITextViewDelegate`의 `textViewDidEndEditing` 메서드를 활용하여 다음과 같이 구현하였습니다.
```swift
func textViewDidEndEditing(_ textView: UITextView) {
    let contents = textView.text.split(separator: "\n")
    guard !contents.isEmpty else { return }

    CoreDataManager.shared.saveContext()
}
```
위의 작업을 통해 키보드 비활성화와 화면 뒤로가기 작업시에는 자동으로 내용을 title / body 로 분리하여 저장할 수 있었습니다.
하지만 앱이 백그라운드에 진입하는 경우는 `SceneDelegate`의 `sceneDidEnterBackground` 메서드를 통해 작업하는 것으로 알고 있어, `CreateDiaryViewController` 내부의 textView 내용에 접근하는 방법을 찾기가 어려웠습니다. 싱글톤으로 만들어진 `CoreDataManager`의 `saveContext`메서드를 통해 해당 일기 객체를 코어데이터에 저장할 수는 있었지만, 현재 작성된 일기 내용을 title과 body로 나누어 업데이트하는 작업이 불가능했습니다. 
이를 해결하기 위해 처음에는 `CreateViewController`의 `viewWillDisappear` 메서드에서 저장처리를 진행할 수 있도록 구현해 보았습니다.
```swift
override func viewWillDisappear(_ animated: Bool) {
    super.viewWillDisappear(animated)
    saveDiary()
}
```
하지만 이렇게 하니 일기 삭제 처리를 한 뒤 뷰컨트롤러를 pop할 때에도 저장처리를 거치게 되어, 오류를 피하려다 보니 오히려 로직이 복잡해졌습니다.
때문에 저희는 `TextView`가 수정될 때마다 뷰컨트롤러가 가지고 있는 일기 객체의 내용을 바꿔주고, 저장이 필요한 순간에 `saveContext` 처리만 진행할 수 있도록 아래와 같이 구현하였습니다.
```swift
func textViewDidChange(_ textView: UITextView) {
    let contents = textView.text.split(separator: "\n")
    guard !contents.isEmpty,
          let title = contents.first else { return }

    let body = contents.dropFirst().joined(separator: "\n")

    diary.title = "\(title)"
    diary.body = body
}
```

### 🔹 alert과 swipe 코드 분리
반복적인 alertController 생성 작업, 그리고 swipe 코드를 뷰컨트롤러에서 조금이라도 분리하면 좋을 것 같아 protocol과 extension을 활용하였습니다.
- `Alert` 분리전 코드
```swift
private func showDeleteConfirmation() {
    let alertController = UIAlertController(title: "진짜요?", message: "정말로 삭제하시겠습니까?", preferredStyle: .alert)
    
    let cancelAction = UIAlertAction(title: "취소", style: .cancel, handler: nil)
    alertController.addAction(cancelAction)
    
    let deleteAction = UIAlertAction(title: "삭제", style: .destructive) { [weak self] _ in
        guard let self else { return }
        self.performDelete()
    }
    alertController.addAction(deleteAction)
    
    present(alertController, animated: true, completion: nil)
}
```

- 분리 후 코드
```swift
protocol AlertDisplayable {
    func showAlert(title: String?, message: String?, actions: [UIAlertAction])
}

extension AlertDisplayable where Self: UIViewController {
    func showAlert(title: String?, message: String?, actions: [UIAlertAction]) {
        let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
        actions.forEach { alertController.addAction($0) }
        present(alertController, animated: true, completion: nil)
    }
}
```
- 구현부 코드
```swift
private func showDeleteConfirmation() {
        let cancelAction = UIAlertAction(title: "취소", style: .cancel, handler: nil)
        let deleteAction = UIAlertAction(title: "삭제", style: .destructive) { [weak self] _ in
            self?.performDelete()
        }
        
        showAlert(title: "진짜요?", message: "정말로 삭제하시겠습니까?", actions: [cancelAction, deleteAction])
    }
```

### 🔹 일기 리스트 새로고침 시점
처음에는 `DiaryListViewController`와 `CreateDiaryViewController`를 `delegate`로 연결하여 생성화면이 pop될 때 리스트 화면의 `readCoreData` 메서드를 호출하도록 구현하였습니다. 하지만 이보다는 뷰의 생명주기를 활용하는 편이 더 깔끔할 것 같다는 생각이 들었습니다. 이에 따라 `viewWillAppear` 메서드에서 아래와 같이 처리해주었습니다.
```swift
override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)

    readCoreData()
}
```

## 조언을 얻고 싶은 점
### 빈 화면에서 뒤로가기를 눌렀을 때의 처리방법
요구사항에 따르면, 일기장의 + 버튼을 눌러 새 일기장을 생성했을 경우 키보드가 자동으로 올라오게 됩니다. 그리고 뒤로가기 처리를 하거나 백그라운드 상태로 변환되는 등 현재 화면에서 벗어나면 작업중인 내용이 자동으로 저장이 되어야 합니다. 그렇다면 + 버튼을 눌렀다가 아무런 내용을 작성하지 않은 채 뒤로가기를 눌러도 제목/내용이 없는 빈 일기가 생성되는 것이 맞을까요? 저희는 이 부분이 조금 어색한 것 같아서 아예 비어있는 내용은 context에서 save처리를 하지 않도록 만들어두었습니다. 그린의 의견이 궁금합니다😭

---

2023-09-06 07:49 UTC, GREENOVER requested changes
@maxhyunm @hemg2 
두분 스텝 2도 고생 많으셨습니다!!
너무 잘 구현해주셔서 사실 이번에는 크게 리뷰 드릴건 없고 조금 보완해볼수 있거나 여러분들의 의견이 궁금한 부분들 위주가 많습니다ㅎㅎ
***
### 칭찬 드리고 싶은 부분
- 프로토콜 활용 너무 좋아요 💯
- 코드 가독성은 점점 발전하는군요 💯
- 기능면에서 너무 잘 구현되어 있어요! 💯
***
### 궁금하신 부분에 대한 저의 의견
- 우선 저는 애플 기본 메모장을 사실 잘 활용합니다!
물론 이런것들은 기획 의도와 프로젝트 성향마다 다르겠지만, 저는 아무 텍스트도 입력되어 있지 않다면 뒤로가기 시 아예 저장하지 않는 여러분들이 말씀하신 방향이 더 좋다고 생각해요!
***
### 기획적으로 한번 더 생각되면 좋을 부분
- 일기장 작성 시 뒤로가기나 백그라운드 갈때만 저장되는것 같은데, 해당 일기 작성 화면에서 완료 같은 버튼을 두어 저장 시키는것도 하나의 친절한 방법일거라 생각합니다!
몇몇 분들은 그런 UI/UX에 익숙하실거라 생각이 들어서 하나 의견을 드려봅니다ㅎㅎ
물론 프로젝트 기획 요구사항이 아니기에 그냥 하나의 의견으로 생각해보셔도 좋습니다!
***
두분 다시 한번 고생 많으셨습니다 ㅎㅎ
지금 상태에서 바로 어프 후 머지해도 요구사항이나 앱 동작에서 전혀 문제는 없지만 한번 점검 차 Request Change로 드리겠습니다!
언제든 재리뷰나 머지 요청해주세요!

2023-09-06 07:49 UTC, GREENOVER commented on Diary+CoreDataClass.swift
> +import Foundation
Foundation이 꼭 필요한 import 인지 궁금합니다 🙋🏻
만약 여기서 Foundation 프레임워크 import가 필요하지 않다면 왜 그럴까요!?

2023-09-06 07:49 UTC, GREENOVER commented on Diary+CoreDataClass.swift
> +public class Diary: NSManagedObject {
NSManagedObject가 어떤 역할을 하는 클래스이기에 상속을 받는지 간단히 알려주실 수 있을까요~? 🙋🏻

2023-09-06 07:49 UTC, GREENOVER commented on Diary+CoreDataProperties.swift
> +
개행을 해주신 이유가 궁금합니다 🙋🏻
다른 부분들과 개행 스타일이 다른것 같아서 여러분들이 개행을 해주시는 기준이 궁금해요..!

2023-09-06 07:49 UTC, GREENOVER commented on Diary+CoreDataProperties.swift
> +extension Diary: Identifiable {}
실제로 필요한 코드인지 없을때 현재 코드에서 어떤 문제가 발생하나요~? 🙋🏻

2023-09-06 07:49 UTC, GREENOVER commented on Diary/App/SceneDelegate.swift
> +        CoreDataManager.shared.saveContext()
GOOOOD!

2023-09-06 07:49 UTC, GREENOVER commented on Diary/Protocol/ShareDiary.swift
> +protocol ShareDiary {
크... 프로토콜 적극 사용 너무 좋네요 👍
단지 궁금증은 AlertDisplayable은 뭔가 형용사의 느낌으로 네이밍을 하셨는데 ShareDiary 프로토콜은 어떤 의도로 네이밍이 되었나요~?

2023-09-06 07:49 UTC, GREENOVER commented on Diary/Protocol/ShareDiary.swift
> +        let shareText = "제목: \(title)\n작성일자: \(date)\n내용: \(body)"
만약 shareText에 담아야하는 String이 더 무수히 길어지면 어떻게 표현하는게 가독성이 좋을까요!?

2023-09-06 07:49 UTC, GREENOVER commented on Diary/Protocol/AlertDisplayble.swift
> +        let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
preferredStyle도 만약 파라미터로 Style을 받아올 수 있다면 더 확장성 있지 않을까 싶습니다 🙋🏻

2023-09-06 07:49 UTC, GREENOVER commented on Diary/DataManager/CoreDataManager.swift
> +    func deleteDiary(_ diary: Diary?) {
두 메서드에서는 에러가 발생될 일이 없는지 궁금합니다 🙋🏻

2023-09-06 07:49 UTC, GREENOVER commented on Diary/DataManager/CoreDataManager.swift
> +                fatalError("Unresolved error \(error), \(error.userInfo)")
파탈에러를 사용하신 이유가 궁금해요..!
꼭 필요한건가요? 🙋🏻

2023-09-06 07:49 UTC, GREENOVER commented on Diary/Controller/DiaryListViewController.swift
> +extension DiaryListViewController: UITableViewDelegate, ShareDiary {
LGTM 👍👍

2023-09-06 07:49 UTC, GREENOVER commented on Diary/Controller/CreateDiaryViewController.swift
> +        textView.text = "\(title)\n\(body)"
현재 코드라면 만약 제가 일기장 기록 시
```
Title


Body
```
로 타이틀 후 여러번 개행하고 본문을 입력하여 일기가 저장될때 다시 해당 일기를 들어오면 
```
Title
Body
```
로 의도적으로 줄바꿈한것이 사라질 수 있을것 같은데요.
일반 애플 기본 메모장처럼 구현하는건 어떨까요~?
사용자가 의도를 갖고 있을 수도 있지 않을까해서요..!

2023-09-06 07:49 UTC, GREENOVER commented on Diary/Controller/CreateDiaryViewController.swift
> +        showAlert(title: "진짜요?", message: "정말로 삭제하시겠어요?", actions: [cancelAction, deleteAction])
이런 문자열 같은 텍스트는 하드코딩으로 실수를 범할 수도 있는 경우가 다분하여 네임스페이스를 이용해보는건 어떨까요!?
유지보수성도 좋아질거라 생각이 듭니다 🙋🏻

2023-09-06 07:49 UTC, GREENOVER commented on Diary/Controller/CreateDiaryViewController.swift
> +    func textViewDidChange(_ textView: UITextView) {
만약 다이어리를 작성 혹은 수정하는 도중 앱이 갑자기 종료되거나 오류가 발생하면 변경사항이 저장될지 궁금합니다 🙋🏻
간단히 작성 중 시뮬레이터를 강종하면서 확인해봐도 좋을것 같아요!
이건 사실 기획 의도도 포함되어 있기에 정답은 없긴합니다 ㅎㅎ

2023-09-06 07:49 UTC, GREENOVER commented on Diary/Controller/CreateDiaryViewController.swift
> +final class CreateDiaryViewController: UIViewController, AlertDisplayable, ShareDiary {
생성만 일어나는 VC인지 궁금해요!
실제 일기를 수정하거나 할때 사용되면 조금 더 나은 네이밍이 있지 않을까 싶습니다 🙋🏻

2023-09-10 07:38 UTC, maxhyunm commented on Diary+CoreDataClass.swift
> +import Foundation
CoreData에서 자체적으로 Foundation을 import하고 있기 때문에 지워도 상관없습니다! 이 부분 삭제처리했습니다.

2023-09-10 07:38 UTC, maxhyunm commented on Diary+CoreDataClass.swift
> +public class Diary: NSManagedObject {
NSManagedObject는 CoreData 모델을 사용하게 될 경우 상속을 진행해야하는 기본 클래스입니다. 엔티티명, 어트리뷰트명, 어트리뷰트 간의 관계 등을 포함한 (NSObject 객체들의)메타정보를 갖고 있습니다.

2023-09-10 07:38 UTC, maxhyunm commented on Diary+CoreDataProperties.swift
> +
Diary에 코드를 추가보려다가 삭제하면서 실수로 남긴 것 같습니다. 개행 삭제했습니다!

2023-09-10 07:38 UTC, hemg2 commented on Diary/Controller/CreateDiaryViewController.swift
> +final class CreateDiaryViewController: UIViewController, AlertDisplayable, ShareDiary {
- 두 가지 다른 작업을 진행하는 뷰컨트롤러의 네이밍을 정하기가 쉽지 않아서 고민이 있었습니다😭 결과적으로 List라는 이름에 대비되는 Detail이라는 명칭을 활용하였습니다.

2023-09-10 07:39 UTC, maxhyunm commented on Diary+CoreDataProperties.swift
> +extension Diary: Identifiable {}
Identifiable은 해당 프로토콜을 채택한 타입에서 Hashable 값으로 id 프로퍼티를 만들도록 강제합니다. 이를 통해 모든 객체를 id로 구분할 수 있도록 하기 위함입니다. 만약 id로 구분할 수 있는 값이 없을 경우 데이터를 특정할 수 없어 문제가 생기는 것으로 알고 있습니다. 저희의 Diary는 uuid로 id 프로퍼티를 갖고 있기에, 기능상 문제는 발생하지 않는 것 같습니다. 하지만 Identifiable의 성질을 명시적으로 보여주는 것이 좋은 것 같아서 삭제하지 않고 그대로 두었습니다!

2023-09-10 07:39 UTC, hemg2 commented on Diary/Controller/CreateDiaryViewController.swift
> +    func textViewDidChange(_ textView: UITextView) {
- SceneDelegate의 applicationWillTerminate 메서드에 저장 내용을 추가해 보았는데, 시뮬레이터 자체를 강제종료시키는 식으로 테스트를 진행했더니 앱만 강제종료될 경우에 대한 테스트가 제대로 이루어지지 않는 것 같습니다😭 확인이 어려워서 해당 내용은 다시 원복해 두었습니다.
    ```swift
    func applicationWillTerminate(_ application: UIApplication) {
        CoreDataManager.shared.saveContext()
    }
    ```

2023-09-10 07:39 UTC, hemg2 commented on Diary/Controller/CreateDiaryViewController.swift
> +        showAlert(title: "진짜요?", message: "정말로 삭제하시겠어요?", actions: [cancelAction, deleteAction])
- 네임스페이스를 쓰면 관리의 용이성은 올라가지만 코드의 가독성이 오히려 떨어지는 단점도 함께 오는 것 같아서, 처음에는 네임스페이스 없이 작업을 했었습니다...! 그린의 의견을 듣고 고민을 해보다가 일단 매직 리터럴들을 네임스페이스로 구분하여 옮겨보았습니다. (다만 오류와 관련된 alert 내용을 모두 오류 타입으로 옮겼더니 네임스페이스의 구분이 다소 애매해진 것 같네요😭)

2023-09-10 07:39 UTC, maxhyunm commented on Diary/Protocol/ShareDiary.swift
> +protocol ShareDiary {
두 가지 네이밍을 비슷하게 맞추는 편이 좋았을 것 같네요...!! 수정 진행하였습니다!

2023-09-10 07:39 UTC, hemg2 commented on Diary/Controller/CreateDiaryViewController.swift
> +        textView.text = "\(title)\n\(body)"
- 말씀 듣고 보니 의도적인 개행은 유지하는 것이 좋을 것 같아서 수정 진행하였습니다!

2023-09-10 07:39 UTC, hemg2 commented on Diary/DataManager/CoreDataManager.swift
> +                fatalError("Unresolved error \(error), \(error.userInfo)")
- persistentContainer의 경우 싱글톤 객체 내부 프로퍼티 형식으로 되어 있어, 추가 오류처리가 어렵다고 판단되어 fatalError를 사용하였습니다. 해당 부분에서 오류가 난다면 저장소 자체를 불러오지 못한 케이스라서 정상적으로 앱이 작동하지 못할 것이라고 생각되었습니다. 반면 saveContext에 있던 fatalError의 경우는 자체적으로 save 실패 오류를 만들어 뷰컨트롤러로 throw해주면 앱을 강제종료시키는 대신 얼럿 처리로 대체할 수 있을 것 같아서 수정 진행했습니다!

2023-09-10 07:39 UTC, maxhyunm commented on Diary/Protocol/ShareDiary.swift
> +        let shareText = "제목: \(title)\n작성일자: \(date)\n내용: \(body)"
그린께서 말씀하신 수정점이 어딜까에 대하여 많은 고민을 하였습니다 😢 처음에는 share할 항목을 따로 정리해두어야 하나? 라는 생각도 했는데, 고민 끝에 '가독성'에 초점을 맞추는 것으로 결론을 내렸습니다.(혹시 의도하신 바가 이게 아니시라면 추가로 말씀 부탁드려요!!) 이에 따라 기존에는 한 줄로 작성되었던 부분을 여러 줄 String 형식으로 변경하여 작성하였습니다.
  ```swift
  let shareText = "제목: \(title)\n작성일자: \(date)\n내용: \(body)"
  ```
  ```swift
   let shareText = """
                   제목: \(title)
                   작성일자: \(date)
                   내용: \(body)
                   """
  ```

2023-09-10 07:40 UTC, hemg2 commented on Diary/DataManager/CoreDataManager.swift
> +    func deleteDiary(_ diary: Diary?) {
- create 시에는 단순히 객체를 생성만 하는 것이라 오류가 나지 않지만, delete 시에는 오류가 날 수 있을 것 같아서 에러타입을 추가하였습니다.

2023-09-10 07:40 UTC, maxhyunm commented on Diary/Protocol/AlertDisplayble.swift
> +        let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
코드 추가 후 변경 완료 했습니다 감사합니다!!

2023-09-10 23:45 UTC, GREENOVER commented on Diary/Protocol/ShareDiary.swift
> +        let shareText = "제목: \(title)\n작성일자: \(date)\n내용: \(body)"
요걸 의도해서 말씀드린게 맞습니다ㅎㅎ
역시 찰떡같이 알아들으셨군요!

2023-09-10 23:49 UTC, GREENOVER approved these changes
@hemg2 @maxhyunm 
스텝2 리팩토링 수고 많으셨습니다!!
어프로브 및 머지 하겠습니다ㅎㅎ
다음 스텝도 화이팅이에요 🙌

2023-09-10 23:49 UTC, GREENOVER commented on .swiftlint.yml
> -- line_length
제외된 이유가 궁금합니다 🙋🏻

2023-09-10 23:49 UTC, merged

2023-09-11 02:48 UTC, maxhyunm commented on .swiftlint.yml
> -- line_length
요거 STEP 1때 대신 개행을 써보면 어떠냐는 의견 주셨어서, 해당 내용 참고하여 린트에서는 제외하고 개행으로 진행 중입니다!