일기장 [STEP 2] Erick
yagom-academy/ios-diary pull request #130
Opened 2023-09-10 10:01 UTC by h-suo

@1Consumption 
안녕하세요 올라프 Erick입니다!
Core Data와 코드의 재사용 측면에서 많이 헤맨 스텝이었던 것 같습니다.
이번에도 잘 부탁드립니다! 🙇‍♂️

## 🤔 고민했던 점
### 1️⃣ CoreData CRUD
`CRUD` 기능을 추상화하여 `DiaryStorageProtocol`이 요구사항으로 가지고 있고, 이를 채택한 `CoreData`의 `CRUD` 기능을 전담하는 `CoreDataDiaryStorage` 객체를 생성하였습니다.
또한 `persistentContainer`를 `CoreDataDiaryStorage`가 `private` 하게 가지고 있어 외부에서 접근하지 못하도록 은닉화하였습니다.

```swift
final class CoreDataDiaryStorage: DiaryStorageProtocol {
    
    private lazy var persistentContainer: NSPersistentContainer = {
        // ...
    }()
    
    // READ
    func diaryEntrys() throws -> [DiaryEntry] {
        // ...
    }
    
    // Create
    func storeDiary(title: String, body: String?) {
        // ...
    }
    
    // Update
    func updateDiary(_ diary: DiaryEntry) {
        // ...
    }
    
    // delete
    func deleteDiary(_ diary: DiaryEntry) {
        // ...
    }
}
```

### 2️⃣ Notification
초기에는 `CoreData`의 `CRUD` 메서드가 에러를 던지도록 했습니다. 하지만 `Controller`에서 메서드를 사용할 때마다 `do-catch`문으로 에러 처리를 하니 코드가 길어지고 가독성이 좋아지지 않았습니다.
또한 READ를 제외한 작업을 수행했을 때는 데이터를 다시 읽어와 화면을 업데이트하는 작업도 해줘야 했습니다.

이를 해결하기 위해 `saveContext()`에서 `context.save()`가 성공했을 때는 `coreDataUpdateSuccessNotification` 노티를 게시하고 실패했을 때 `coreDataUpdateFailNotification` 노티를 게시하여 `Controller`에서 이를 관찰하여 실패 `alert`을 띄우거나 화면을 업데이트할 수 있도록 했습니다.

**saveContext**
```swift
// CoreDataDiaryStorage.swift
func saveContext() {
    if context.hasChanges {
        do {
            try context.save()
            NotificationCenter.default.post(name: .coreDataUpdateSuccessNotification, object: nil)
        } catch {
            NotificationCenter.default.post(name: .coreDataUpdateFailNotification, object: nil)
        }
    }
}
```

`Controller`에서는 `CoreDataUpdatable`를 채택하여 기본 구현된 `addObserve...` 메서드를 호출하여 `observer`를 쉽게 추가할 수 있도록 했습니다.

**CoreDataUpdatable**
```swift
protocol CoreDataUpdatable {
    func addObserveSuccessUpdate(observer: Any, selector: Selector)
    func addObserveFailUpdate(observer: Any, selector: Selector)
}

extension CoreDataUpdatable {
    func addObserveSuccessUpdate(observer: Any, selector: Selector) {
        NotificationCenter.default.addObserver(observer, selector: selector, name: .coreDataUpdateSuccessNotification, object: nil)
    }
    
    func addObserveFailUpdate(observer: Any, selector: Selector) {
        NotificationCenter.default.addObserver(observer, selector: selector, name: .coreDataUpdateFailNotification, object: nil)
    }
}
```

### 3️⃣ Alert & Activity 재사용
`AlertController`와 `ActivityViewController`의 코드를 재사용하기 위해 `Manager`를 만들어 `Controller`에서 메서드를 호출하는 것만으로 `Alert`와 `ActivityView`를 보여줄 수 있도록 했습니다.

**AlertManager**
```swift
enum AlertManager {
    
    static func presentFailAlert(to controller: UIViewController, with message: String) {
        let alertAction = UIAlertAction(title: "확인", style: .cancel)
        let alert = UIAlertController.customAlert(alertTile: "실패", alertMessage: message, preferredStyle: .alert, alertActions: [alertAction])
        
        controller.present(alert, animated: true)
    }
    
    static func presentDeleteAlert(to controller: UIViewController, with action: ((UIAlertAction) -> Void)?) {
        let alertAction = UIAlertAction(title: "삭제", style: .destructive, handler: action)
        let cancelAction = UIAlertAction(title: "취소", style: .cancel)
        let alert = UIAlertController.customAlert(alertTile: "진짜요?", alertMessage: "정말로 삭제하시겠어요?", preferredStyle: .alert, alertActions: [alertAction, cancelAction])
        
        controller.present(alert, animated: true)
    }
}
```

**ActivityViewManager**
```swift
enum ActivityViewManager {
    
    static func presentActivityView(to controller: UIViewController, with diary: DiaryEntry) {
        let diaryText = String(format: "%@\n%@", diary.title, diary.body)
        let activity = UIActivityViewController(activityItems: [diaryText], applicationActivities: nil)
        activity.popoverPresentationController?.sourceView = controller.view
        
        controller.present(activity, animated: true)
    }
}
```

## 🙇‍♂️ 조언을 얻고싶은 점
### 1️⃣ Notification
실패 상황을 처리하거나 앱이 백그라운드로 전환될 때 `Notification`을 활용하여 처리했습니다. 이렇게 `Notification`을 활용하는 게 괜찮은 방법인지 조언을 얻고 싶습니다.
그리고 현업에서 `Notification`을 활용한다면 주로 언제 사용하는지도 궁금합니다!

---
### 📚 참고 링크
- [Apple: Core Data](https://developer.apple.com/documentation/coredata)
- [Apple: NSManagedObjectContext](https://developer.apple.com/documentation/coredata/nsmanagedobjectcontext)
- [Apple: UISwipeActionsConfiguration](https://developer.apple.com/documentation/uikit/uiswipeactionsconfiguration)
- [Apple: UIActivityViewController](https://developer.apple.com/documentation/uikit/uiactivityviewcontroller)
- [Apple: didEnterBackgroundNotification](https://developer.apple.com/documentation/uikit/uiapplication/1623071-didenterbackgroundnotification)

2023-09-11 10:56 UTC, 1Consumption requested changes
고생하셨습니다.

노티피케이션 관련 내용은 코멘트에 같이 남겼습니다.

2023-09-11 10:56 UTC, 1Consumption commented on Diary/Controller/DiaryListViewController.swift
> +        addObserveFailUpdate(observer: self, selector: #selector(presentFailAlert))
notification은 코드의 흐름이 끊기기 때문에 정말로 필요한 경우가 아니면 사용하지 않는 것이 좋겠습니다.

2023-09-11 10:56 UTC, 1Consumption commented on Diary/Controller/DiaryListViewController.swift
> +        }
여기는 weak self를 안해줘도 될까요?

2023-09-11 10:56 UTC, 1Consumption commented on Diary/Controller/DiaryListViewController.swift
> +
여기도 weak self가 필요 없을까요?

2023-09-11 10:56 UTC, 1Consumption commented on Diary/Controller/DiaryViewController.swift
> +        let diaryContents = textView.text.components(separatedBy: NameSpace.enter).filter { !$0.isEmpty }
저는 ! 붙이는 것을 선호하지 않습니다. 역순으로 읽어야하는 느낌이랄까요. 이부분은 개인의 취향이니 한번 생각해보시죠.

2023-09-11 10:56 UTC, 1Consumption commented on Diary/Controller/DiaryViewController.swift
> +        }
guard문에는 긍정문이 들어가는게 읽기 좋습니다.
지금의 경우는 `isEmpty가 아닌게 아니라면`이라는 이중 부정으로 해석이 되어 가독성이 떨어지네요.

2023-09-11 10:56 UTC, 1Consumption commented on Diary/Error/ConversionError.swift
> +    public var errorDescription: String? {
public인 이유가 있을까요?

2023-09-11 10:56 UTC, 1Consumption commented on Diary/Model/Storage/AssetDiaryStorage.swift
>      }
이 펑션들은 왜 있는건가요?

2023-09-11 10:56 UTC, 1Consumption commented on Diary/Model/Storage/CoreDataDiaryStorage.swift
> +
NSManagedObject를 바로 반환하지 않고 변환해서 반환한건 좋습니다 👍

2023-09-11 10:56 UTC, 1Consumption commented on Diary/Model/Storage/CoreDataDiaryStorage.swift
> +    }
이 두개의 메소드를 외부에서 구분해서 호출해야할까요?
저는 하나의 메소드로 통일하고, 내부적으로 fetchRequest() 결과에 따라 저장이든, 업데이트든 하는게 좋을 것 같습니다.

2023-09-11 10:56 UTC, 1Consumption commented on DiaryTests/CoreDataDiaryStorageTests.swift
> +    }
직접 persistentStore에 저장하지 말고, persistentStoreType을 변경해보는건 어떨까요?
https://developer.apple.com/documentation/coredata/nspersistentstore/persistent_store_types

2023-09-11 10:56 UTC, 1Consumption commented on DiaryTests/CoreDataDiaryStorageTests.swift
> +    }
최초에는 아무것도 없는데, 의미있는 테스트가 맞을까요?

2023-09-11 10:56 UTC, 1Consumption commented on DiaryTests/CoreDataDiaryStorageTests.swift
> +    }
DiaryEntry 자체를 비교하는건 어떨까요? 정말 body만 같으면 같은건가요?

2023-09-12 03:32 UTC, h-suo commented on Diary/Controller/DiaryListViewController.swift
> +        addObserveFailUpdate(observer: self, selector: #selector(presentFailAlert))
에러를 `throw` 하고 `do-catch`문으로 에러를 처리하도록 수정했습니다!

https://github.com/yagom-academy/ios-diary/pull/130/commits/831d09ce777ff9500c19d5cea395546c9394992d

2023-09-12 03:34 UTC, h-suo commented on Diary/Controller/DiaryListViewController.swift
> +        }
메모리 누수 방지를 위해 `[weak self]`를 사용하여 클로져가 `Controller`를 약한 참조할 수 있도록 했습니다!

https://github.com/yagom-academy/ios-diary/pull/130/commits/a8c6a02a266e091a1ba5be6253732b0937aefd75

2023-09-12 03:36 UTC, h-suo commented on Diary/Controller/DiaryViewController.swift
> +        let diaryContents = textView.text.components(separatedBy: NameSpace.enter).filter { !$0.isEmpty }
가독성의 차이가 있을 수 있겠네요! 조언해 주신 대로 !를 사용하는 대신 `== false`로 수정했습니다!

https://github.com/yagom-academy/ios-diary/pull/130/commits/ee4c2b8053ccf973290edf4a82f93fb61718769c

2023-09-12 03:38 UTC, h-suo commented on Diary/Controller/DiaryViewController.swift
> +        }
`if`문으로 분리하여 `isEmpty일 경우`라는 조건이 쉽게 읽히도록 수정했습니다!

https://github.com/yagom-academy/ios-diary/commit/ee4c2b8053ccf973290edf4a82f93fb61718769c

2023-09-12 03:44 UTC, h-suo commented on Diary/Error/ConversionError.swift
> +    public var errorDescription: String? {
다른 모듈에서 `errorDescription`으로 접근할 필요가 없기 때문에 접근 레벨을 `public`에서 `internal`로 수정했습니다!

https://github.com/yagom-academy/ios-diary/pull/130/commits/dd8bbe6d4104ec40b9a86ca93885e0a7912fd7dc

2023-09-12 04:57 UTC, h-suo commented on Diary/Controller/DiaryListViewController.swift
> +        addObserveFailUpdate(observer: self, selector: #selector(presentFailAlert))
일기의 업데이트가 성공했을 경우에는 `Delegate` 패턴을 이용해 `diaryViewController(_ diaryViewController: DiaryViewController, updateDiary isSuccess: Bool)`가 호출되었을 때 `tableView`를 업데이트 시켜주었습니다!

https://github.com/yagom-academy/ios-diary/pull/130/commits/5c62c0cf9ec210b5f3672f862a3fc706c414a9dc

2023-09-12 04:59 UTC, h-suo commented on Diary/Model/Storage/CoreDataDiaryStorage.swift
> +    }
하나의 메서드로 통일했습니다!

https://github.com/yagom-academy/ios-diary/pull/130/commits/7fbe731a31ac63a732f2fff70d1d365759663c39

2023-09-12 06:30 UTC, h-suo commented on DiaryTests/CoreDataDiaryStorageTests.swift
> +    }
`storeDiary`로 예상 `DiaryEntry`를 저장한 후 `DiaryEntrys`로 받아온 배열의 첫 번째 요소와 비교하도록 수정하였습니다!

https://github.com/yagom-academy/ios-diary/pull/130/commits/2d2dcadcc59efd9ee8bce4ff71bf69b2ac934a2f

2023-09-12 06:30 UTC, h-suo commented on DiaryTests/CoreDataDiaryStorageTests.swift
> +    }
`DiaryEntry`를 비교하도록 수정했습니다!

https://github.com/yagom-academy/ios-diary/pull/130/commits/2d2dcadcc59efd9ee8bce4ff71bf69b2ac934a2f

2023-09-12 12:48 UTC, 1Consumption commented on Diary/Controller/DiaryListViewController.swift
> +        }
음 정말로 메모리 누수가 발생하나요? AlertManager.presentDeleteAlert는 static 펑션인데 rc를 올리나요?

2023-09-12 13:01 UTC, h-suo commented on Diary/Model/Storage/AssetDiaryStorage.swift
>      }
`DiaryStorageProtocol`에 요구사항에는 있지만 사용하지 않는 함수라 `DiaryReadable`과 `DiaryManageable`로 프로토콜을 분리하여 `AssetDiaryReader`은 `DiaryReadable`만 채택하도록 수정했습니다!

https://github.com/yagom-academy/ios-diary/pull/130/commits/1e4b4310a21ee87f7368ca144d70eface55c1538

2023-09-14 02:54 UTC, h-suo commented on Diary/Controller/DiaryListViewController.swift
> +        }
`static function`이라도 파라미터로 클로져를 받고 있고 그 클로져에서 `self`를 캡쳐하고 있기 때문에 `controller`의 `rc`가 증가하게 됩니다.
또한 `presentDeleteAlert` 내부에서 파라미터로 받은 `controller.present`로 `alert`를 `present`하고 있기 때문에 `controller -> alert -> action -> controller` 순으로 참조를 하게 되어 순환 참조가 발생할 수 있습니다.

2023-09-14 13:20 UTC, h-suo commented on DiaryTests/CoreDataDiaryStorageTests.swift
> +    }
`CoreDataDiaryStorage`가 `PersistentStore`를 파라미터로 받도록 수정하여 `InMemory Store`를 활용하도록 테스트 코드를 수정했습니다!

https://github.com/yagom-academy/ios-diary/pull/130/commits/ed4fa49a7299ba8c2d9f6a137183652759c6479c

2023-09-15 02:41 UTC, merged