일기장 [STEP 2] hoon, karen
yagom-academy/ios-diary pull request #131
Opened 2023-09-10 17:28 UTC by karenyang835

안녕하세요. `July!`(@July911)😊
`hoon`🐝, `keren`🦦입니다.

예정보다 조금 많이 늦어진`Step02 PR` 보냅니다.

천천히 보시고 리뷰 남겨주시면 감사하겠습니다.

--- 
<br>

## 🤔 고민한 부분
### 1️⃣ 오토레이아웃
- `Hierarchy`로 확인을 했을 때 해당 오류가 발생됐습니다.

    ![](https://hackmd.io/_uploads/rJpIedsR2.png)

    확인을 해보니 날짜를 받아오는 `label`의 사이즈가 변동이 되면서 발생된 문제점이라 `Hugging`을 주어서 해결했습니다.
    
    ```swift
    private let dateLabel = {
            let label = UILabel()
            label.font = .preferredFont(forTextStyle: .body)
            label.setContentHuggingPriority(.defaultHigh, for: .horizontal)

            return label
        }()
    ```

### 2️⃣`CoreData` 사용
- `CoreData`를 활용하는데 어려움이 많았습니다. 그중에서 새 일기장을 만들고 아무것도 입력하지 않은 상태로 다시 나오거나 입력을 하다가 다 지우고 나오면 생성되지 않아야 된다고 생각을 하였는데 생성이 되는 문제점이 발생했습니다.

    <img src="https://hackmd.io/_uploads/B1LKSOsRh.gif" style="zoom:70%;">
    
    `textView`의 내용이 비어있으면 `delete`를 해주어 해결했습니다.
    
    ```swift
     func saveDiary() {
            guard !contentTextView.text.isEmpty else {
                CoreDataManager.shared.deleteDiary(item: diary)
                return
            }

            let contents = contentTextView.text.split(separator: "\n")
            let title = String(contents[0])
            let body = contents.dropFirst().joined(separator: "\n")

            if contents.isEmpty {
                saveContents(title: "", body: "")
            } else {
                saveContents(title: title, body: body)
            }
        }
    ```

### 3️⃣ `Diary` 생성 위치
- `Diary`를 `Creat`하는 위치에 따라 `tableView`에 `cell`이 추가되는 시점이 달랐습니다. 두 번째 화면인 `DiaryDetailViewController`에서 `Diary`를 생성하고 저장하는 경우 이전 화면으로 돌아와 `tableView`를 확인하면 목록에 없는 문제가 발생하였습니다. 다음 화면으로 넘어갔다가 다시 돌아오면 그제야 `cell`이 `tableView`에 추가되었습니다. `tableView`에 `cell`이 그려지는 시점이 문제였습니다. 이를 해결하기 위해 `Diary`를 첫 화면인 `DiaryViewController`에서 생성하여 다음 화면인 `DiaryDetailViewController`로 넘겨주는 작업을 수행하였습니다.

    ```swift
    let action = UIAction { _ in
        let diary = CoreDataManager.shared.createDiary()
        let diaryDetailViewController = DiaryDetailViewController(diary: diary, isUpdate: false)
        self.navigationController?.pushViewController(diaryDetailViewController, animated: true)
    }
    ```
    
    생성한 `Diary`에 입력을 하는 경우 `save` 또는 `update` 동작을 분리하기 위하여 `isUpdate`를 통해 구분하였습니다.

--- 

<br>

## 🙇🏻‍♀️ 조언을 얻고 싶은 부분
### 1️⃣ 프로젝트 구조 설계
- `CoreDataManager`는 현재 사용하고 있는 두 화면 모두에서 사용하고 있습니다. 이를 위해 싱글톤 객체를 활용하여 `CoreData`에 접근할 수 있도록 설계하였습니다. 또한 `Shareable` 프로토콜을 선언하여 공유 기능을 사용할 때 `Shareable`에 선언한 `showActivityView` 메서드를 활용하면 반복적인 코드 없이 쉽게 `UIActivityViewController`를 `present` 할 수 있도록 작성하였습니다. 이러한 코드 작성을 통하여 사용성을 높일 수 있었다고 생각합니다. 지금과 같은 구조로 프로젝트를 설계하는 것이 좋은 방식일지 궁금합니다.

### 2️⃣ `Shareable` 프로토콜 사용
- `Shareable` 프로토콜에 선언한 메서드인 `showActivityView` 메서드는 다음과 같습니다.

    ```swift
    func showActivityView(data: Any, viewController: UIViewController) {
        var shareObject = [Any]()
        
        shareObject.append(data)
        
        let activityViewController = UIActivityViewController(activityItems: shareObject, applicationActivities: nil)
        
        activityViewController.popoverPresentationController?.sourceView = viewController.view
        viewController.present(activityViewController, animated: true)
    }
    ```
    
    매개변수로 `UIViewController`를 입력받아 사용하고 있습니다. 현재 사용하고 있는 `ViewController`를 전달받기보다는 `UITableView`에서 사용하는 `UITableViewDelegate`와 같은 형태로 프로퍼티에 현재의 `ViewController`를 전달하고 싶었습니다.
    
    ```Swift
    tableView.delegate = self
    
    extension DiaryViewController: UITableViewDelegate { }
    ```
    
    `UITableView` 코드를 살펴보면 `Class` 타입으로 `delegate`를 프로퍼티를 가집니다. 저희가 작성한 `Shareable` 프로토콜에서는 연산 프로퍼티를 통해 `delegate`처럼 `self`를 받는 방법을 찾지 못하였습니다. 이러한 부분은 어떻게 해결할 수 있을까요?

2023-09-11 01:55 UTC, July911 requested changes

2023-09-11 01:55 UTC, July911 commented on Diary/CoreData/CoreDataManager.swift
> +final class CoreDataManager {
다른 타입의 데이터를 저장 혹은 불러오기를 하고싶다면 어떻게 해줘야할까요 ? 
createDiary, readDiary 처럼 하나씩 만드실 계획인가요 ?

2023-09-11 01:55 UTC, July911 commented on Diary/Extension/UITextView+.swift
> +            self.endEditing(true)
순환참조에서 안전한가요 ? 안전하다면 혹은 아니라면 이유는 무엇일까요 ?

2023-09-11 01:55 UTC, July911 commented on Diary/Controller/DiaryDetailViewController.swift
> +import CoreData
빼볼 수 있을까요 ?

2023-09-11 01:55 UTC, July911 commented on Diary/Controller/DiaryViewController.swift
> +        let diary = diaryList[indexPath.row]
다이어리 리스트는 여러분들이 관리하고있어서 혹여 delete를 잘못해준다면 크래시가 날 것 같습니다. 
diaryList[indexPath.row] 를 안전하게 조회해볼까요 ?

2023-09-11 01:55 UTC, July911 commented on Diary/Controller/DiaryViewController.swift
> +            title: diary.value(forKeyPath: "title") as? String ?? "",
최선일까요 ...? 조금 복잡해보이네요

2023-09-11 01:55 UTC, July911 commented on Diary/CoreData/CoreDataManager.swift
> +    func deleteDiary(item: Diary) {
전체를 받아야할까요 ?

2023-09-11 01:55 UTC, July911 commented on Diary.xcodeproj/project.pbxproj
> +				C739AE2D284DF28600741E8F /* Diary.xcdatamodeld */,
LocalDB/CoreData/XCDataModel 
순이 맞지 않을까요 ? 여러분들 생각은 어떠신가요 ?

2023-09-11 01:55 UTC, July911 commented on Diary/Controller/DiaryDetailViewController.swift
> +    private let isUpdate: Bool
수동태가 맞는거같습니다 :)

2023-09-11 01:55 UTC, July911 commented on Diary/Controller/DiaryDetailViewController.swift
> +            self.present(alert, animated: true)
아래와 같은 코멘트입니다. 순환참조에서 안전한가요 ?

2023-09-11 01:55 UTC, July911 commented on Diary/Protocol/Shareable.swift
> +protocol Shareable {
Any Ojbect는 무엇일까요 ?

2023-09-12 10:02 UTC, karenyang835 commented on Diary/CoreData/CoreDataManager.swift
> +final class CoreDataManager {
제네릭 타입을 사용하는 `DataManager`을 생성하였습니다.
`CoreDataManager`가 `DataManager`를 상속 받아 `entity`를 초기화하여 원하는 타입에 맞춰 저장 또는 불러오도록 수정해주었습니다.

2023-09-12 10:03 UTC, Hoon94 commented on Diary/Controller/DiaryDetailViewController.swift
> +import CoreData
수정하였습니다.😊

2023-09-12 10:08 UTC, Hoon94 commented on Diary/Controller/DiaryDetailViewController.swift
> +    private let isUpdate: Bool
https://github.com/yagom-academy/ios-diary/pull/131/commits/0111b310faac77a5d68c478d77fcc08522d77c90

`isUpdated`로 수정하였습니다.😊

2023-09-12 10:43 UTC, karenyang835 commented on Diary/Controller/DiaryViewController.swift
> +        let diary = diaryList[indexPath.row]
https://github.com/yagom-academy/ios-diary/pull/131/commits/1996059c7c2a4c2a3b07fc1ab363d8d746b72c08

`Array Extension`으로 `subscript`문법을 사용하여 안전하게` index`에 접근하도록 수정하였습니다.

2023-09-12 10:50 UTC, Hoon94 commented on Diary/CoreData/CoreDataManager.swift
> +    func deleteDiary(item: Diary) {
객체 전체를 넘겨주기 보다는 객체가 가지고 있는 고유값을 사용할 수 있습니다.

추후 STEP 3의 추가 기능 구현에서 검색 기능이 요구사항에 있습니다.
다음 STEP을 진행하면서 추가적으로 수정해보도록 하겠습니다.🤔

2023-09-13 05:56 UTC, Hoon94 commented on Diary/Extension/UITextView+.swift
> +            self.endEditing(true)
https://github.com/yagom-academy/ios-diary/pull/131/commits/b35ea088cbee1efcfbb0712641fd44503d5b1831

클로저 내부에서 다시 `self`인 `UITextView`를 참조하고 있습니다. 이런 경우에는 서로 참조를 하기 때문에 순환 참조가 발생할 수 있습니다. 이를 방지하기 위해 `weak self`를 사용하여 순환 참조를 해결하였습니다.

참고 자료 : [Strong Reference Cycles for Closures](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/automaticreferencecounting/#Strong-Reference-Cycles-for-Closures)

2023-09-13 05:57 UTC, Hoon94 commented on Diary/Controller/DiaryDetailViewController.swift
> +            self.present(alert, animated: true)
https://github.com/yagom-academy/ios-diary/pull/131/commits/b35ea088cbee1efcfbb0712641fd44503d5b1831

클로저 내부에서 다시 `self`인 `UITextView`를 참조하고 있습니다. 이런 경우에는 서로 참조를 하기 때문에 순환 참조가 발생할 수 있습니다. 이를 방지하기 위해 `weak self`를 사용하여 순환 참조를 해결하였습니다.

참고 자료 : [Strong Reference Cycles for Closures](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/automaticreferencecounting/#Strong-Reference-Cycles-for-Closures)

2023-09-13 05:59 UTC, Hoon94 commented on Diary.xcodeproj/project.pbxproj
> +				C739AE2D284DF28600741E8F /* Diary.xcdatamodeld */,
추후 `LocalDB` 생성시 말씀해주신 내용을 참고하여 수정하도록 하겠습니다. 감사합니다.🙏🏼

2023-09-13 06:21 UTC, karenyang835 commented on Diary/Protocol/Shareable.swift
> +protocol Shareable {
https://github.com/yagom-academy/ios-diary/pull/131/commits/f9bb6a32ca3365a6b3b1ad59e99971b3cef57394

`Any`는 모든 타입을 저장할 수 있고 `AnyObject`는 모든 클래스타입을 저장할 수 있습니다. `AnyObject`로 명시했을 경우 클래스 타입을 제외한 구조체, 열거형, `Reference Type`인 클로저도 저장할 수 없습니다.

제네릭 타입인 `Contents`를 만들어서 기존 `Any`타입에서 특정 타입을 지정하도록 수정하였습니다.

2023-09-13 06:32 UTC, Hoon94 commented on Diary/Controller/DiaryViewController.swift
> +            title: diary.value(forKeyPath: "title") as? String ?? "",
https://github.com/yagom-academy/ios-diary/pull/131/commits/c2f208f026b6581c420a49bb56ac1a754cb0ec7b

수정하였습니다.😊

2023-09-13 06:57 UTC, merged