일기장 [Step1] Hisop, Kiseok
yagom-academy/ios-diary pull request #142
Opened 2024-01-04 08:57 UTC by Hi-sop

@havilog
안녕하세요! 일기장 STEP1 PR보냅니다. 잘부탁드립니다.

## 고민이 되었던 점

#### 키보드가 올라올 때 텍스트를 가리는 문제 
- 키보드 팝업시 notification을 통해 키보드 높이만큼 TextView.bottom.contentInset을 더해주는 방식을 쓰려고 했으나
코드를 더 간결하게 작성하여 동일한 동작을 구현할 수 있는 keyboardlayoutguide(최소 버전 15)를 활용하여 오토레이아웃을 정해주는 방식으로 변경하였습니다.

<details>
<summary>수정 전(notification + contentInset)</summary>
    
```swift=
@objc private func keyboardWillShow(_ notification: Notification) {
    guard let userInfo = notification.userInfo as NSDictionary?,
          var keyboardFrame = (userInfo[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue)?.cgRectValue else {
        return
    }
    
    textView.contentInset.bottom = keyboardFrame.size.height
    textView.scrollIndicatorInsets = textView.contentInset
}

```
</details>

<details>
<summary>수정 후(keyboardlayoutguide)</summary>

```swift=
self.view.keyboardLayoutGuide.topAnchor.constraint(equalTo: textView.bottomAnchor)
```
keyboardLayoutGuide.topAnchor는 키보드가 팝업되지 않았을 때  
safeAreaLayoutGuide.bottomAnchor과 같다는 점을 활용해 오토레이아웃을 지정해주었습니다.
</details>

## 조언을 얻고 싶은 점
#### HomeVC에서 다음VC의 인스턴스를 프로퍼티로 가지고 있는 형태
- private let diaryDetailViewController = DiaryDetailViewController()

테이블뷰의 선택에 따라 새로운 DiaryDetailViewController를 생성하고 push하는 것이 VC의 생성과 해제를 여러번 반복하는 것이라 생각하여 HomeVC가 DiaryDetailViewController를 프로퍼티로 가질 수 있도록 해보았습니다.

이렇게 구현하는 것이 다른 문제를 발생시킬 가능성이 있을지 궁금합니다.

## 다음 스텝에서 수정할 부분들

#### JSON 파일을 받아올 모델과 decode하는 메서드
해당 부분은 sample data파일을 활용해보라는 요구 사항 때문에 구현한 부분인데 이 부분은 Core Data 사용 시 사용하지 않을 부분들이라 현재는 간단하게 작성해놓은 상태입니다.
다음 스텝부터 삭제할 예정입니다.

#### TextView에서 Diary 데이터의 제목과 내용사이에 개행을 넣어 띄우는 방식
아직 제목과 본문을 어떤 방식으로 나눠서 표현할지 정하지 않았고, 현 스텝에서는 데이터를 어떻게 저장할지 정해진 것이 없어서 단순히 받아온 Diary 데이터를 띄워주기 위해 구현한 방식입니다.
다음 스텝에서 수정할 예정입니다.

2024-01-04 15:32 UTC, havilog requested changes
두 분 모두 수고하셨어요~!
코멘트 확인해주세요~!

2024-01-04 15:32 UTC, havilog commented on Diary/Diary.swift
> +class Diary: Codable {
1. 모델의 역할을 하는 아이로 보이는데, class로 선언하신 이유가 뭘까요?
2. Encodable, Decodable 둘 다 필요하다고 생각하셔서 Codable로 하신건지 궁금합니다.
3. Equatable, Sendable, Identifiable 같은 프로토콜은 고려하셨는지 궁금합니다~

2024-01-04 15:32 UTC, havilog commented on Diary/DiaryDetailViewController.swift
> +class DiaryDetailViewController: UIViewController {
상속이 되지 않는 class는 final 키워드를 default로 붙여주세요.
static dispatch와 dynamic dispatch의 차이점에 대해 공부하시고, 코멘트로 달아주시면 좋을 것 같습니다.

2024-01-04 15:32 UTC, havilog commented on Diary/DiaryDetailViewController.swift
> +    private var textView = UITextView()
textView는 바뀔 수 있는 아이라 variable일까요?

2024-01-04 15:32 UTC, havilog commented on Diary/DiaryDetailViewController.swift
> +        configureUI()
UI를 viewWillAppear 시점에 그려주는 이유는 무엇일까요?

2024-01-04 15:32 UTC, havilog commented on Diary/DiaryDetailViewController.swift
> +    private var diaryDetail: Diary?
일기의 상세 내용을 보여주는 뷰컨으로 보여지는데, 일기가 없는 경우가 있나요?
아니라면 initializer로 주입받아 콘크리트 타입으로 가지고 있는게 좋아보여요

2024-01-04 15:32 UTC, havilog commented on Diary/DiaryItemCell.swift
> +    static let reuseIdentifier: String = "DiaryItemCell"
reuseIdentifier의 경우 프로토콜을 만들어 모든 테이블뷰 셀이 적용할 수 있게 하는게 좋아보입니다.

2024-01-04 15:32 UTC, havilog commented on Diary/DiaryItemCell.swift
> +    private var titleLabel: UILabel = {
셀도 마찬가지로 variable일 이유가 없어보여요!

2024-01-04 15:32 UTC, havilog commented on Diary/DiaryItemCell.swift
> +        dateLabel.translatesAutoresizingMaskIntoConstraints = false
요 아이들은 프로퍼티를 선언하는 부분에서 해도 좋아보이네용~

2024-01-04 15:32 UTC, havilog commented on Diary/DiaryItemCell.swift
> +    private lazy var mainStackView: UIStackView = {
요 아이도, 굳이 lazy로 만들기 보다는 UI를 그려주는 시점에 self의 프로퍼티를 참조해서 넣어주면 let으로 사용할 수 있을거 같네용

2024-01-04 15:32 UTC, havilog commented on Diary/DiaryItemCell.swift
> +class DiaryItemCell: UITableViewCell {
Cell에 reuse를 위해 처리해주는 부분이 안보이네요!
셀이 어떻게 재사용되는지, 언제 보여지는지, 재사용하기 위해선 어떤 처리를 해야하는지 설명해주세요

2024-01-04 15:32 UTC, havilog commented on Diary/Base.lproj/LaunchScreen.storyboard
런치스크린은 있어야 할거 같은데, 지워졌네요!

2024-01-04 15:32 UTC, havilog commented on Diary/HomeViewController.swift
> +    private let diaryDetailViewController = DiaryDetailViewController()
고민되는 점에 이 아이를 계속 생성하는게 불필요하다고 적어주셨는데요,

새 인스턴스를 만들고 그에 맞는 일기를 할당해주는게,
하나의 인스턴스를 공유하며 일기를 갈아끼워주는것 보다
안전하다고 생각해요.

또한 새 뷰컨을 생성하는게 큰 오버헤드는 아니라고 생각하구요!

SOLID원칙에서 Open Closed Principle 같은 경우를 고려해보시면 좋을 듯 합니다~

2024-01-04 15:32 UTC, havilog commented on Diary/HomeViewController.swift
> +    }
에셋에서 일기를 들고와서 반환해주는 디코더를 만든 뒤, 해당 객체를 의존성으로 뷰컨에서 들고 있으면 기능이 더 분리되지 않을까요?
추후에 에셋 -> API로 연동할 때도 뷰컨쪽의 로직이 안바뀔 가능성도 있을거 같구요!

2024-01-04 15:32 UTC, havilog commented on Diary/HomeViewController.swift
> +            animated: false
animation은 왜 끄신건지 궁금합니다~!

2024-01-04 15:32 UTC, havilog commented on Diary/HomeViewController.swift
> +        cell.configureLabelName(diaryData: diaryData[indexPath.row])
1. diaryData에서 데이터를 꺼낼 때는 safe 키워드로 안전하게 꺼내면 좋을 듯 합니다.
2. cell.configure(with: diary) 정도로 써보는건 어떨까요?

2024-01-05 05:40 UTC, Hi-sop commented on Diary/Diary.swift
> +class Diary: Codable {
1. [Diary]를 HomeViewController의 프로퍼티로 소유하고 있고, DiaryDetailViewController에 전달해 편집할 의도로 클래스로 선언해보았습니다.
2. 당장은 Decodable만 사용해도 충분할 것 같습니다.
3. 지금은 고려하지 않고 작성했습니다. 필요하다면 해당 프로토콜 추가하겠습니다.

2024-01-05 05:41 UTC, carti1108 commented on Diary/DiaryDetailViewController.swift
> +class DiaryDetailViewController: UIViewController {
미처 신경쓰지 못했던 부분인 것 같습니다.
final 키워드를 추가해주는 것으로 수정 완료하였습니다!

static dispatch는 컴파일 시점에 해당 메서드의 실제 코드의 위치를 안다면 바로 해당 코드 주소로 점프가 가능합니다(메서드 인라이닝) 따라서 컴파일러의 최적화가 가능합니다.
dynamic dispatch는 런타임 시점에 해당 코드 주소로 찾아가기 때문에 컴파일러 최적화가 불가합니다.

2024-01-05 05:45 UTC, Hi-sop commented on Diary/DiaryDetailViewController.swift
> +    private var textView = UITextView()
내용이 바뀐다고 생각하여 var로 지정해놓고 넘어간 부분인 것 같습니다.  
class타입은 내부 프로퍼티의 값이 변경되는 것은 관계가 없으므로 let으로 변경하였습니다.

2024-01-05 06:06 UTC, Hi-sop commented on Diary/HomeViewController.swift
> +    private let diaryDetailViewController = DiaryDetailViewController()
diaryDetailViewController를 프로퍼티로 가지는 방식에서 실행시마다 diaryDetailViewController를 생성하여 push하도록 변경하였습니다.

2024-01-05 06:09 UTC, Hi-sop commented on Diary/DiaryDetailViewController.swift
> +        configureUI()
diaryDetailViewController를 프로퍼티로 가지는 방식을 사용하여 초기화 메서드를 viewWillAppear에 위치시켰습니다.

실행시마다 diaryDetailViewController를 생성하여 push하도록 변경했으므로 viewDidLoad로 초기화 메서드를 호출하도록 했습니다.

2024-01-05 06:14 UTC, carti1108 commented on Diary/HomeViewController.swift
> +            animated: false
애니메이션이 구태여 필요할 것 같지는 않아서 false로 해두었는데 비교해보니 애니메이션을 넣어주는게 더 나을 것 같다라고 판단하여 true로 변경 해주었습니다!

2024-01-05 06:21 UTC, carti1108 commented on Diary/DiaryItemCell.swift
> +    static let reuseIdentifier: String = "DiaryItemCell"
수정 완료하였습니다!

2024-01-05 06:24 UTC, carti1108 commented on Diary/Base.lproj/LaunchScreen.storyboard
main 스토리보드를 삭제하면서 같이 해버렸습니다ㅠㅠ
런치스크린 추가하여 수정 완료했습니다!

2024-01-05 06:34 UTC, carti1108 commented on Diary/DiaryItemCell.swift
> +        dateLabel.translatesAutoresizingMaskIntoConstraints = false
수정 완료했습니다!

2024-01-05 06:34 UTC, carti1108 commented on Diary/DiaryItemCell.swift
> +    private var titleLabel: UILabel = {
수정 완료했습니다!

2024-01-05 06:34 UTC, carti1108 commented on Diary/DiaryItemCell.swift
> +    private lazy var mainStackView: UIStackView = {
수정 완료했습니다!

2024-01-05 06:59 UTC, carti1108 commented on Diary/HomeViewController.swift
> +        cell.configureLabelName(diaryData: diaryData[indexPath.row])
1,2
모두 수정 완료하였습니다!

2024-01-05 07:21 UTC, Hi-sop commented on Diary/DiaryItemCell.swift
> +class DiaryItemCell: UITableViewCell {
화면에 표시될 셀만큼 생성하게 됩니다.
보이지 않게 된다면 큐로 들어가고, 새로 보여지게 되는 셀은 dequeueReusableCell을 통해 큐에서 가져와 사용하게 됩니다.
재사용 전 호출되는 prepareForReuse() 메서드를 통해 초기화가 필요한 부분을 처리해줄 수 있습니다.

일단 Cell에 prepareForReuse를 추가했습니다. 
당장 저희 코드에서는 cell.configure(with: diaryData)를 호출하여 값을 설정해주고 있어 prepareForReuse를 활용한 초기화가 필요하지 않다고 생각합니다.
그럼에도 명시적으로 초기화해주는 것이 좋을까요?

2024-01-05 07:32 UTC, carti1108 commented on Diary/DiaryDetailViewController.swift
> +    private var diaryDetail: Diary?
현재 Diary 타입은 decodable이 채택이 되어있어 Diary를 init을 통해 생성하는 것이 어려워 옵셔널로 두었습니다.
다음 스텝에서 core data로 전환하여 Diary타입에서 decodable을 제거한다면 해결이 될 부분 같습니다.

2024-01-05 07:52 UTC, carti1108 commented on Diary/HomeViewController.swift
> +    }
반환해주는 디코더 모델을 따로 만들어 기능 분리 해주었습니다!

2024-01-05 08:56 UTC, havilog commented on Diary/Diary.swift
> +class Diary: Codable {
model이 struct일지 class일지에 대한 논란은 조금 있는편이긴 한데요,

프로퍼티를 들고있게 하기위해서라기 보다는 데이터베이스에서 같은 아이디를 가진 일관성 있는 값을 보장하기 위함이라고 하면 클래스로 사용해도 될 거 같긴 해요

프로토콜의 경우 준수해야한다 / 아니다 로 나눠져서 제가 정답을 알려주는 느낌은 아니구요,
해당 모델이 어떻게 쓰일지 예상해서 확장성 있게 설계했나에 대한 질문이었습니다!
판단은 기석과 히섭이 하시면 될 듯 해요!

2024-01-05 08:58 UTC, havilog commented on Diary/DiaryDetailViewController.swift
> +    private var diaryDetail: Diary?
decodable과 init의 관련성이 무엇일까요?
diary의 initializer를 하나 더 생성해주면 일기를 만들 수 있을거 같고, 
일기를 생성하는 의미가 아닌,
디테일 뷰컨을 생성하는 시점에서 필요한 일기를 디테일 뷰컨의 이니셜라이저에 전달하면 좋을 것 같다는 의미였습니다!

2024-01-05 09:00 UTC, havilog commented on Diary/DiaryItemCell.swift
> +class DiaryItemCell: UITableViewCell {
실제로는 셀의 갯수는 화면 보다 조금 더 그려지게 되구요,
한 번 configure해줬으면
안보여지게 됐을 때 ui프로퍼티들의 초기화는 필수라고 생각합니다.
구현해주었을 경우 휴먼에러를 방지할 수 있다는 장점 대비 단점이 없다고 생각되어서요!

2024-01-05 09:01 UTC, havilog commented on Diary/HomeViewController.swift
> +            animated: false
iOS에서 애니메이션은 엄청 중요한 역할을 하고 있어요!
사용자 친화적인 애니메이션, 인터렉션, 트랜지션에 신경을 반드시 써야 ux친화적인 잘하는 개발자라고 생각합니다 ㅎㅎ

2024-01-05 09:07 UTC, havilog approved these changes

2024-01-05 09:07 UTC, merged