일기장 [STEP 2] Safari, Eddy
yagom-academy/ios-diary pull request #16
Opened 2022-06-21 15:28 UTC by Siwon-L

# 📒 일기장 [STEP 2] Safari, Eddy

@Monsteel
안녕하세요 토니! 
일기장 STEP2 PR 보냅니다!
잘부탁드립니다!! 🙇🙇‍♂️

## 🤔 해결한 방법
### Builder 패턴 이용

빌더 패턴을 사용해서 공통적으로 계속 사용되는 Alert, Swipe를 만들었습니다.

먼저 내부에 필요한 요소들을 구조체로 선언해주고
```swift
struct AlertAction {
    let title: String
    let style: UIAlertAction.Style
    let completion: (() -> Void)?
}

```
Builder class를 만들어서 어떤 action를 넣을 것인지, 
어떻게 alert를 보여줄 지에 대한 공통 요소들을 넣어서 만들었습니다.
```swift
func addAction(_ title: String, style: UIAlertAction.Style, action: (() -> Void)? = nil) -> Self {
    let alertAction = AlertAction(title: title, style: style, completion: action)
    alertActions.append(alertAction)

    return self
}

func show(_ title: String? = nil, message: String? = nil, style: UIAlertController.Style) {
    let alertController = UIAlertController(title: title, message: message, preferredStyle: style)
    alertActions.forEach { action in
        let alertAction = UIAlertAction(title: action.title, style: action.style) { _ in
            action.completion?()
        }
        alertController.addAction(alertAction)
    }
    viewController?.present(alertController, animated: true)
}
```
이렇게 만들어서 실제 사용처에서 간단하게 만들어서 사용하도록 구현했습니다.
```swift
// DiaryListViewController.swift
private func configureDataSource() {
    dataSource = makeDataSource()

    do {
        try dataSource?.makeData()
    } catch {
        AlertBuilder(target: self).addAction("확인", style: .default)
            .show("데이터를 읽어오지 못했습니다", message: nil, style: .alert)
    }
}
```

### DataSource 역할 분리 

DataSource가 모든 Data저장 및 읽어오는 기능을 할 수 있도록 CustomDataSource를 만들어 역할을 분리하였습니다.

```swift
final class DiaryListDataSource: UITableViewDiffableDataSource<Section, Diary> {
    private typealias Snapshot = NSDiffableDataSourceSnapshot<Section, Diary>
    
    private let persistentManager = PersistentManager(entityName: "DiaryEntity")
    private var items: [Diary] = [] {
        didSet {
            applySnapshot(items: items)
        }
    }
    
    private func applySnapshot(items: [Diary]) {
        var snapShot = Snapshot()
        snapShot.appendSections([.main])
        snapShot.appendItems(items)
        self.apply(snapShot, animatingDifferences: false)
    }
    
    func makeData() throws {
        items = try persistentManager.fetch()
    }
    
    func saveData(_ diary: Diary) throws {
        try persistentManager.register(diary)
        items.append(diary)
    }
    // ...중략
}
```
위 처럼 직접 만든 `DiaryListDataSource`가 `persistentManager` 가지고, Coredata에 data 저장 밎 `Snapshot` 관리를 할 수 있도록 구현하였습니다.

- 안전한 배열 접근 방법

배열의 index 범위를 넘기더라도 앱이 crush가 나지 않도록 안전하게 접근하는 것을 구현했습니다.
범위를 넘지 않으면 만든 배열을 반환하고 그게 아니라면 nil를 반환해서 crush나지 않고 앱이 계속 실행되도록 만들었습니다.
```swift
private extension Array {
    subscript (safe index: Int) -> Element? {
        return self.indices ~= index ? self[index] : nil
    }
```

### Coredata 및 Snapshot 중복 data 저장

키보드가 내려갔을 때, Navigation의 뒤로가기 버튼을 눌렀을 때, 백그라운드로 진입했을 때 TextView에 작성한 내용이 CoreData로 자동 저장 되도록 구현하였습니다. 하지만, 세 가지 상황에서 중복적으로 저장되는 문제가 발생했습니다(`finishTask` 메서드가 중복 호출). 때문에, 

```swift
//diary가 nil이면, addButton을 통한 일기장 새로 생성
private var diary: Diary?

//작업이 끝나고 데이터를 CoreData에 저장하기 위한 코드
private func finishTask() {
    if let diary = diary {
        delegate?.update(updateDiary(diary))
    } else {
        diary = makeDiary()
        delegate?.save(diary ?? makeDiary())
    }
}
```
위 처럼 일기장을 만드는 상황에서(`diary`가 `nil`이면 Create) `diary`에 새로 생성한 data를 주입하여, 다음 `finishTask` 메서드가 호출되었을 땐, `update`로 간주되도록 구현하였습니다.

## 😢 조언받고 싶은 부분
### DiaryTextView 은닉화로 인한 메서드 문제
DiaryDetailView에 diaryTextView 만드는 곳을 `private`으로 만들었습니다. 
```swift
// DiaryDetailView.swift
private let diaryTextView: UITextView = {
    let textView = UITextView()
    textView.translatesAutoresizingMaskIntoConstraints = false

    return textView
}()
```
그리하여 DiaryDetailViewController에서 필요하게 되면 메서드를 만들어서 직접 diaryTextView에 접근하지 않고 메서드를 호출하는 방식으로 해결했습니다.

하지만 호출하는 메서드가 종류가 다양해서 여러 개가 만들어지다보니 이렇게 많은 메서드로 만드는게 맞는지 의문이 들었습니다.
```swift
// DiaryDetailView.swift
func setFirstResponder() {
    self.diaryTextView.becomeFirstResponder()
}

func relinquishFirstResponder() {
    self.diaryTextView.resignFirstResponder()
}

func readText() -> String {
    return diaryTextView.text
}

func setTextViewAccessory(button: UIToolbar) {
    self.diaryTextView.inputAccessoryView = button
}
```

들었던 생각에는 `private`를 푸는 것보다 메서드가 많아지더라도 이 방법이 낫다고 생각했었습니다.

TextView를 은닉화함에 따라 여러 메서드가 만들어지는데, 이 상황에서 메서드가 계속 늘어나니 TextView의 `private`를 풀고 사용하는 것이 더 나은 방법일까요?

### Keyboard 버튼으로 내리는 문제
키보드를 내리는 기능를 위해서 UIToolBar를 이용하여 버튼을 만들어 주었습니다. 하지만,

<img src="https://i.imgur.com/01wYqWy.gif" width="300">

위와 같이 터치 포인트가 키보드에 닿았을 때 터치 포인트와 같이 키보드가 쓸려 내려가는 기능을 구현하고 싶은데 수많은 서치와 실험을 해보았지만, 해답을 얻지 못했습니다. 위 gif 처럼 기능을 구현할 수 있는 키워드를 알고 싶습니다.ㅠㅠ 

### PersistentManager 추상화

저번에 디스코드에서 조언을 한번 받았던 PersistentManager 추상화를 결국 성공하지 못하였습니다.
이 부분은 글보단 토니와 지금까지 시도했던 코드를 보며 같이 이야기 해보고 싶습니다. 목요일 또는 금요일날 토니가 시간이 있으시면, 한번 이야기 해보고싶습니다.

### background 진입 시 자동 저장

처음 background 진입 시 자동 저장할 수 있는 방법에 대해서는 2가지를 생각했습니다. 

`SceneDelegate`에서 NotificationCenter 또는, Delegate 활용

NotificationCenter 같은 경우 broadcast이고 계속 바라보고 있기 떄문에 성능상 효율적이지 않다고 생각했습니다.

그리하여 delegate를 활용해서 background 진입 시 데이터를 자동 저장하도록 구현했습니다.

하지만, Delegate 패턴을 사용하게 되면, `SceneDelegate`이 `delegate`라는 프로퍼티를 가져야 한다는 단점과 `ViewController`에서 `SceneDelegate`에 접근해야 한다는 단점이 있다고 생각했습니다.

첫 번쨰 궁금한 점으로는 저희가 위에 말한 요점을 통해 Delegate를 선택했는데 이러한 포인트로 선택한 것이 맞는지 궁금합니다. 또한, 토니는 두가지 방법중 어떠한 방법을 선택할것 같은지 궁금합니다.

두 번쨰 궁금한점으로는 저희가 생각하고 찾아본 방법은 위의 2가지뿐인데, 혹시 다른 방법이 있을지도 궁금합니다..! 만약 있다면 힌트만 주신다면 저희가 찾아보겠습니다!!!!

2022-06-23 12:31 UTC, Monsteel requested changes
안녕하세요 사파리 에디~~ :)
이번 Step2도 수고 많으셨습니다!

우선 조언이 필요하신 부분에 대한 답변먼저 드립니다!
### `DiaryTextView` 은닉화로 인한 메서드 문제
음 이 부분 같은 경우에는 내부 value를 외부에서 접근하지 못하도록 은닉화를 하게 되면 당연히, 필연적으로 필요한 처리방식이라 `문제`라고 정의하기에는 어려움이 있어 보입니다.
만약 이와 비슷하게 은닉화로 인해서 캡슐화 한 메서드가 많이 만들어지는 등의 형태가 만들어지게 된다면, 은닉화를 해야하는 value인지 다시한번 점검해볼 필요성은 있을것 같습니다.

이쯤에서, 사파리와 에디가 `diaryTextView`를 은닉화 해서 얻으려고 하시는 효용은 어떤 부분인가요?

### Keyboard 버튼으로 내리는 문제
이 부분은 UIScrollView의 [KeyboardDismissMode](https://developer.apple.com/documentation/uikit/uiscrollview/keyboarddismissmode)를 조정해서 구현할 수 있습니다. 해당 화면 같은 경우에는 [interactive](https://developer.apple.com/documentation/uikit/uiscrollview/keyboarddismissmode/interactive) 타입이 적절해 보이네요. 프로젝트에 어떻게 적용할지 등, 더 자세한 내용은 사파리와 에디가 한번 찾아보시면서 공부해보시면 좋을 것 같아요.

### PersistentManager 추상화
좋습니다. 연이어 제가 계속 바쁜 일정으로 살아가고 있다보니 😇 내일 시간이 괜찮을지 잘 모르겠습니다 😭
시간은 한번 조율해 보도록 하고, 만약 시간이 안된다면 따로 서면으로 리뷰를 드릴 수 있도록 할게요.
저도 그런 시간을 가지는것에 대해서는 굉장히 동의합니다.
(리뷰도 디코로 양방향 소통으로 진행하면 더 좋을텐데 말이죠 ㅠ)

### background 진입 시 자동 저장

음 우선 NotificationCenter가 성능적으로 비효율적이라고 생각하신 배경이 있으신가요?
성능때문에 NotificationCenter 사용을 지양한다는 내용은 아직 들어본 적이 없어서요! 🙋🏻‍♂️

저는 가장 중요하게 생각하는 부분이 별도의 모듈 형태로 분리해서 결합도를 낮추는 것이라 생각해요.
그런 기조에서 잘 분리해주셨다고 생각합니다!

추가로, 

![스크린샷 2022-06-23 오후 9 24 35](https://user-images.githubusercontent.com/52942409/175297946-caeb1a27-f850-4628-9a06-4e6d66f5185b.png)

warring이 뜨는 부분이 있는데요, 이부분 개선 부탁드리겠습니다~!

수고하셨습니다 :)

2022-06-23 12:31 UTC, Monsteel commented on Diary/Application/SceneDelegate.swift
> +    weak var delegate: CoreDataSceneDelegate?
weak 아주 좋습니다! 다만, delegate라는 네이밍은 너무 포괄적인것 같아요 👀
해당 SceneDelegate만의 delegate가 아니다보니, 중복된 다른 delegate가 더 생길수도 있을것 같아요.
조금 더 적절한 네이밍을 찾아보는건 어떨까요?!

2022-06-23 12:31 UTC, Monsteel commented on Diary/Utils/AlertBuilder/AlertAction.swift
> +struct AlertAction {
AlertAction을 따로 분리하신 이유가 있나요? AlertBuilder 파일 내에 함께 선언해도 괜찮을 것 같아서요 🙋🏻‍♂️

2022-06-23 13:25 UTC, kimkyunghun3 commented on Diary/Model/Diary.swift
>      private enum CodingKeys: String, CodingKey {
사용하지 않는 것인데 남겨두었었네요! 삭제했습니다!

2022-06-23 13:27 UTC, saafaaari commented on Diary/Utils/AlertBuilder/AlertAction.swift
> +struct AlertAction {
처음엔 파일 내부에 하나의 타입만 둔다는 생각으로 각 분리해서 선언했습니다. 이유는 나중에 해당 타입을 수정할 때 좀더 빠르게 찾아가기 위해서 입니다.

2022-06-23 13:36 UTC, saafaaari commented
## 추가 코멘트

### DiaryTextView 은닉화로 인한 메서드 문제
사실 은닉화가 무조건 필요하다고, 생각하지는 않습니다. 
왜냐하면, 은닉화를 하는 이유는 값의 보호라고 생각합니다. 하지만, 해당 값은 상수(let)으로 선언되어 있기 때문에 해당 값이 외부에서 변질될 수 없는 구조라고 생각해 은닉화가 필연적이라고 생각하지 않습니다.

하지만, 서로 의논을 한 결과 코드의 수정은 하지 않았습니다.

### background 진입 시 자동 저장
상황에 따라 broadcast로 해야한다면 NotificationCenter를 사용하는 것도 좋은 방법같습니다.

하지만 현재에서는 아래와 같은 이유로 지양해야하지 않나 생각했습니다.

첫 번쨰로는,
이 이벤트로 저장을 관리하면 전역적으로 이벤트가 받는 형태라 앱 전반적으로 저장을 알리는 것이 되는 것 같습니다. 그러므로 이는 불필요하게 모든 곳에 알리는 것이기 때문 지양해야 한다고 생각합니다.

두 번째로는,
실제로 코드를 돌려보지는 못했지만, 예시가 있기에 성능 상으로 delegate가 더 우세하다는 것을 볼 수 있었습니다. 하지만 미세할 수 있는 차이라고 생각할 수도 있으므로 성능상의 이유로 선택하지 않았다고 하기에는 조금 미흡했던 것 같습니다.

https://stackoverflow.com/questions/17921155/nsnotificationcenter-vs-delegation-which-is-faster

2022-06-24 01:00 UTC, Monsteel approved these changes
수고하셨습니다 :)
이유있는 코드를 잘 짜고 계신것 같아요!

추가로, pod관련한 warning이 제거되지 않았는데요, 다음 스텝에서는 반영 부탁드립니다.

2022-06-24 01:00 UTC, merged