일기장 [STEP 2-1] Lingo, Minseong
yagom-academy/ios-diary pull request #19
Opened 2022-06-22 15:39 UTC by Minseong-yagom

@innocarpe

## 배경
>일기장 데이터를 위한 코어데이터 모델을 생성합니다
코어 데이터의 영구 저장소 위치는 Application Support 디렉터리 내부로 합니다
일기의 CRUD를 구현합니다

위 요구사항을 구현하고자 하였습니다.

---

## 작업 내용
- `PersistentManager` 클래스를 구현하였습니다.
- `PersistentManager` 클래스에 아래의 메서드(CRUD)를 구현 하였습니다.
    - `create()`: coreData에 일기장데이터를 저장합니다.
    - `fetchAll()`: coreData에 있는 데이터들을 가져옵니다.
    - `update()`: 수정할 데이터와 coreData에 있는 데이터의 id가 일치하면 coreData에 있는 데이터를 수정합니다.
    - `delete()`: 삭제하고자 하는 데이터만 삭제합니다.
    - `deleteAll()`: coreData에 있는 데이터를 전부 삭제합니다.
    
---

### 리뷰 노트
- Core Data를 사용한 PersistentManager만 구현하여 UI적인 변화가 없었기 때문에 스크린샷 및 영상에는 CRUD 코드를 첨부했습니다.

---

### 스크린샷 및 영상

**Create: 일기장 데이터 생성 메서드**

```swift
func create(diary: Diary) {
    let diaryEntity = DiaryEntity(context: context)
    diaryEntity.setValue(diary.title, forKey: "title")
    diaryEntity.setValue(diary.body, forKey: "body")
    diaryEntity.setValue(diary.createdAt, forKey: "createdAt")
    diaryEntity.setValue(diary.uuid, forKey: "uuid")

    self.saveContext()
}
```

**Fetch All: 모든 일기장 데이터를 가져오는 메서드**

```swift
func fetchAll() -> [Diary] {
    guard let diaryEntities = try? context.fetch(DiaryEntity.fetchRequest()) else { return [] }

    let diaries = diaryEntities.map {
      Diary(title: $0.title ?? "", body: $0.body ?? "", createdAt: $0.createdAt)
    }

    return diaries
}
```

**Update: 일기장 특정 데이터 수정 메서드**

```swift
func update(diary: Diary) {
    guard let diaryEntities = try? context.fetch(DiaryEntity.fetchRequest()) else { return }
    guard let diaryEntity = diaryEntities.first(where: { $0.uuid == diary.uuid }) else { return }

    diaryEntity.setValue(diary.title, forKey: "title")
    diaryEntity.setValue(diary.body, forKey: "body")

    self.saveContext()
}
```

**Delete: 특정 일기장 데이터 삭제 메서드**
```swift
func delete(diary: Diary) {
    guard let diaryEntities = try? context.fetch(DiaryEntity.fetchRequest()) else { return }
    guard let diaryEntity = diaryEntities.first(where: { $0.uuid == diary.uuid }) else { return }

    context.delete(diaryEntity)

    self.saveContext()
}
```

**Delete All: 모든 일기장 데이터 삭제 메서드**
```swift
func deleteAll() {
    guard let diaryEntities = try? context.fetch(DiaryEntity.fetchRequest()) else { return }

    diaryEntities.forEach { entity in
      context.delete(entity)
    }

    self.saveContext()
}
```

2022-06-22 15:41 UTC, llingo commented on Diary/Util/PersistentManager.swift
> +  static let shared = PersistentManager()
PersistentManager 클래스를 구현할 때 같은 인스턴스를 참조하도록 싱글톤으로 구현했습니다.

2022-06-22 15:45 UTC, Minseong-yagom commented on Diary/Model/Diary.swift
> +  var body: String
다이어리 내용 수정을 위해 title과 body를 var로 바꿔주었습니다.
coreData의 데이터와 수정할 다이어리 데이터가 일치할 때 만 수정을 할 수 있도록 구현하기 위해
uuid를 생성해주었습니다.

2022-06-24 02:49 UTC, innocarpe commented on Diary/Util/PersistentManager.swift
> +        fatalError("Unresolved error \(error), \(error.userInfo)")
`fatalError` 는 앱을 강제로 종료시킵니다. 개발 단계에서 최대한 빨리 아는게 좋지 않냐는 의견도 있는데, 모바일 앱에서 강제 종료는 크리티컬하기 때문에 Non-fatal 에러 로깅을 넣거나 우회할 수 있는 방법을 보통 고민하곤 합니다. 

이 에러가 있으면 앱을 강제종료 시킬 정도로 크리티컬 건이려나요? 그렇지 않다면 앱이 종료되지 않는 선에서 다르게 처리하시는게 좋지 않을까 싶어요.

2022-06-24 02:49 UTC, innocarpe commented on Diary/Util/PersistentManager.swift
> +    if context.hasChanges {
[P4] `self.` 가 빠진 것 같습니다.

2022-06-24 02:50 UTC, innocarpe commented on Diary/Util/PersistentManager.swift
> +        try context.save()
[P4] `self.` 가 빠진 것 같습니다.

2022-06-24 02:50 UTC, innocarpe commented on Diary/Util/PersistentManager.swift
> +        fatalError("Unresolved error \(nserror), \(nserror.userInfo)")
[P1] 여기도 fatalError 를 쓰셨네요. [위 코멘트](https://github.com/yagom-academy/ios-diary/pull/19/files#r905675059) 와 동일합니다.

2022-06-24 02:55 UTC, innocarpe requested changes

2022-06-24 02:55 UTC, innocarpe commented on Diary/Util/PersistentManager.swift
> +final class PersistentManager {
[P1] 내부 코드를 보니 Diary 데이터를 핸들링하는 클래스로 보이는데 그렇다면 그에 맞는 이름으로 리네이밍해주세요. 이 이름으로는 이 클래스가 어떤 역할을 하는지 추측이 불가합니다.

2022-06-24 02:55 UTC, innocarpe commented on Diary/Util/PersistentManager.swift
> +    context.delete(diaryEntity)
[P4] `self.` 가 빠졌습니다.

2022-06-24 02:55 UTC, innocarpe commented on Diary/Util/PersistentManager.swift
> +      context.delete(entity)
[P4] `self.` 가 빠졌습니다.

2022-06-24 02:55 UTC, innocarpe commented on DiaryTests/PersistentManagerTests.swift
> +    XCTAssertEqual(diaries.count, expectedValue)
[P4] given-when-then 사이가 붙어있는데, 사실 여기 `then` 부분처럼 각 요소들은 개행을 하나씩 해 주는게 가독성이 훨씬 좋습니다.

2022-06-24 02:55 UTC, innocarpe commented on Diary/Application/SceneDelegate.swift
> +    PersistentManager.shared.saveContext()
[P3] Singleton 은 모바일에서 가장 대표적인 안티 패턴이자 사용을 지양해야 하는 것 중 하나입니다. 싱글톤은 모듈 내라면 어디서든 사용할 수 있고 프로젝트 규모가 커질수록 점점 문제가 되어 관리가 불가능해지기도 하구요. 이렇게 쉽게 사용이 가능하니 여전히 많이 사용하는 것으로 보이지만, 의존성으로 주입받아 사용하는 방향을 고려해 보시면 좋을 것 같네요.

이번에 바로 수정은 안 하셔도 좋지만 이 부분은 앞으로 고민해보시면 좋겠습니다.

2022-06-24 05:10 UTC, llingo commented on Diary/Util/PersistentManager.swift
> +    if context.hasChanges {
프로젝트 초기에 팀 컨벤션을 정할 때 다음과 같은 고민이 있었습니다.

1. `self`를 명시할 지
2. `self`를 생략하고 필요한 곳에서만 사용
3. 기본적으로 `self`를 명시하되 파라미터, if / for문 등 앞에 다른 키워드가 있을 시 `self`를 생략

세 가지 사안 중 3번을 사용하는 것으로 팀 컨벤션을 결정하여 위와 같이 `self`를 생략하게 되었습니다.

> 팀 컨벤션은 팀 별로 자유롭게 정할 수 있습니다.

2022-06-24 05:11 UTC, llingo commented on Diary/Util/PersistentManager.swift
> +        try context.save()
https://github.com/yagom-academy/ios-diary/pull/19#discussion_r905721422 와 동일합니다!

2022-06-24 05:25 UTC, llingo commented on Diary/Util/PersistentManager.swift
> +        fatalError("Unresolved error \(error), \(error.userInfo)")
fatalError를 제거한 후 print로 에러를 출력하도록 변경했습니다. 
이외의 방법으로는 Logger 객체를 구현하여 에러 로그를 저장하는 방법도 있을 것 같습니다!

2022-06-24 05:26 UTC, llingo commented on Diary/Util/PersistentManager.swift
> +        fatalError("Unresolved error \(nserror), \(nserror.userInfo)")
https://github.com/yagom-academy/ios-diary/pull/19#discussion_r905726944 와 동일합니다!

2022-06-24 05:28 UTC, llingo commented on Diary/Util/PersistentManager.swift
> +final class PersistentManager {
Diary 데이터를 핸들링하기 때문에 DiaryPersistentManager로 네이밍을 변경했습니다! [85c6679](https://github.com/yagom-academy/ios-diary/pull/19/commits/85c667946b431c191c81b14b06cd16528d5371c9)

2022-06-24 05:30 UTC, llingo commented on Diary/Util/PersistentManager.swift
> +    context.delete(diaryEntity)
`self`를 명시하여 수정했습니다

2022-06-24 05:30 UTC, llingo commented on Diary/Util/PersistentManager.swift
> +      context.delete(entity)
self를 명시하여 수정했습니다!

2022-06-24 05:33 UTC, llingo commented on DiaryTests/PersistentManagerTests.swift
> +    XCTAssertEqual(diaries.count, expectedValue)
given-when-then 사이에 줄바꿈을 추가하여 [17b7359](https://github.com/yagom-academy/ios-diary/pull/19/commits/17b73593290123fbbc74981eea5c49468f205009) 와 같이 수정했습니다!

2022-06-24 05:37 UTC, Minseong-yagom commented on Diary/Application/SceneDelegate.swift
> +    PersistentManager.shared.saveContext()
앗 넵 추후 싱글톤을 사용할 시 말씀해주신 의존성주입에 대해 고려해보겠습니다! 🙏

2022-06-24 05:43 UTC, innocarpe commented on Diary/Util/PersistentManager.swift
> +    if context.hasChanges {
> 프로젝트 초기에 팀 컨벤션을 정할 때 다음과 같은 고민이 있었습니다.
> 
> 1. `self`를 명시할 지
> 2. `self`를 생략하고 필요한 곳에서만 사용
> 3. 기본적으로 `self`를 명시하되 파라미터, if / for문 등 앞에 다른 키워드가 있을 시 `self`를 생략
> 
> 세 가지 사안 중 3번을 사용하는 것으로 팀 컨벤션을 결정하여 위와 같이 `self`를 생략하게 되었습니다.
> 
> > 팀 컨벤션은 팀 별로 자유롭게 정할 수 있습니다.

@llingo 컨벤션이었군요. 그러면 3번에서 if/for 문 앞에 다른 키워드가 있을 때 self 가 제거하기로 한 의도를 알 수 있을까요? 키워드가 없는 것과는 어떻게 달라서 여기만 빼도록 결정하셨는지를 잘 모르겠어서요~

2022-06-24 05:47 UTC, innocarpe commented on Diary/Util/PersistentManager.swift
> +final class PersistentManager {
> Diary 데이터를 핸들링하기 때문에 DiaryPersistentManager로 네이밍을 변경했습니다! [85c6679](https://github.com/yagom-academy/ios-diary/pull/19/commits/85c667946b431c191c81b14b06cd16528d5371c9)

@llingo `PersistentManager` 라는 말이 여전히 어떤 의미인지 잘 모르겠어요. 형용사 + Manager 로 클래스 이름을 지으신 것인데, 해석이 불가합니다. 예컨대 `DiaryStrongManager` 나 `DiaryHappyManager` `DiaryContinuousManager` 와 같은 느낌이라서 무엇을 하는 Manager 인지 정의가 없는 상태입니다. 

그렇기에 클래스 이름은 명사로 역할을 명시하도록 네이밍을 해 주셔야 합니다.

2022-06-24 05:48 UTC, innocarpe commented on Diary/Util/PersistentManager.swift
> +      context.delete(entity)
> self를 명시하여 수정했습니다!

@llingo  어떤 곳은 `self.` 를 넣고, 어떤 곳은 `self.` 를 안 넣는 컨벤션인 것 같은데 이 부분은 swiftlint 로 체크가 어려울 것 같습니다. 그렇다면 사람이 리뷰를 통해서만 컨벤션이 지켜지고 있는지 아닌지를 케이스별로 알아야만 판별이 가능한 상태가 아닌가 하는 생각이 들어요.

2022-06-24 05:49 UTC, innocarpe commented on Diary/Application/SceneDelegate.swift
> +    PersistentManager.shared.saveContext()
> 앗 넵 추후 싱글톤을 사용할 시 말씀해주신 의존성주입에 대해 고려해보겠습니다! 🙏

싱글톤을 원천적으로 사용하지 않는 방향으로 생각하시는 걸 더 추천드립ㄴ디ㅏ.

2022-06-24 06:01 UTC, llingo commented on Diary/Util/PersistentManager.swift
> +    if context.hasChanges {
3번 컨벤션처럼 한 의도는

만약, UIView를 상속받는 경우에서 backgroundColor를 변경하기 위해서는 다음과 같은 문제가 있었습니다.
```swift
class LingoView: UIView {
  // ...
  private func initializeUI() {
    backgroundColor = .red
  }
}
```
위의 경우에서는 self 를 명시하지 않으면 backgroundColor만 있기 때문에 프로퍼티인지 속성인지 구분하기 힘들다는 느낌을 받았습니다. (프로퍼티인지 아닌 지를 찾아야하는 문제)

다른 경우에서
```swift
private func initializeUI() {
  // ...
  NSLayoutConstraints.activate([
    self.baseView.topAnchor.constraints(equalTo: self.view.topAnchor) // self 를 명시한 경우
    baseView.topAnchor.constraints(equalTo: view.topAnchor)  // 키워드, 파라미터 내부 (생략한 경우)
  ])
}
```
처럼 self를 무조건 명시하는 경우에서는 코드가 복잡한 느낌이 들었지만 후자의 경우에는 깔끔한 느낌이 들었기 때문에

위와 같은 3번을 선택하게 되었습니다.

2022-06-24 06:05 UTC, llingo commented on Diary/Util/PersistentManager.swift
> +      context.delete(entity)
말씀하신대로 케이스 별로 self 여부를 구분하면 팀 규모가 커졌을 때 관리하기 어려울 것 같습니다. 따라서, 3번은 좋지 않다고 생각했고 다음의 두 가지 경우 중 하나로 컨벤션을 수정해보겠습니다!

1. self를 무조건 명시한다.
2. self를 생략하되 필요한 경우에서만 사용한다.

2022-06-24 06:09 UTC, llingo commented on Diary/Util/PersistentManager.swift
> +final class PersistentManager {
클래스 이름을 "일기를 저장하는 저장소를 관리한다" 는 의미로 DiaryStorageManager 로 변경했습니다! [2400476](https://github.com/yagom-academy/ios-diary/pull/19/commits/240047628f7c3f61551275b465fad78d74e1e04b)

2022-06-24 06:18 UTC, llingo commented on Diary/Util/PersistentManager.swift
> +      context.delete(entity)
[c25a6e2](https://github.com/yagom-academy/ios-diary/pull/19/commits/c25a6e20b8ddc1247585ac19c6e49680008ffa7f) self 키워드 컨벤션을 무조건 명시하는 방향으로 수정했습니다.

2022-06-24 06:20 UTC, llingo commented on Diary/Util/PersistentManager.swift
> +    if context.hasChanges {
https://github.com/yagom-academy/ios-diary/pull/19#discussion_r905750311 아래와 같이 명시하는 방향으로 변경했습니다!

2022-06-24 06:37 UTC, innocarpe commented on Diary/Util/PersistentManager.swift
> +final class PersistentManager {
넵 좋습니다!!

2022-06-24 06:38 UTC, innocarpe approved these changes
STEP 2-1 고생하셨습니다!!

2022-06-24 06:38 UTC, merged