일기장 [STEP 2] 쿼카, Taeangel
yagom-academy/ios-diary pull request #20
Opened 2022-06-23 14:38 UTC by Quokkaaa

@wonhee009 
안녕하세요 라쟈냐!!!! 😄 
이번에 처음 CoreData를 접하다보니 CRUD 학습하는데 시간이 오래 걸렸던 것 같습니다. 그리구 예상치 못한 삽질과 에러를 만나 고귀한 삽질의 시간도 가져보았습니다 🤪🤪
STEP2 PR 잘 부탁드립니다. 🙏🏻

# 해결하지 못한점 🤔
- 키보드를 내리고 list화면으로 이동하면 두번이 저장이된다. 이를 어떻게 해결할 수 있을까 ??
CoreDataManager내 특정 Diary값만 가져와주는 메서드를 만들어서 키보드내릴때 마다 identifier가 존재하는지 확인주면 해결할 수 있을 것 같다. -> 리펙토링 예정

- DetailViewController에서 더보기에서 글 삭제한 후 MainViewController로 화면이동하면서 업데이트 해줄때
현재 viewDidDisappear 메서드내에 readContext메서드를 계속 실행해준다. 근데 하나의 데이터만 업데이트 하면 되는데 모든 데이터업데이트를 할 경우 오버헤드가 발생할 수 있어 Delegate 로 업데이트해야할 Diary값만 전달해 주면 될것같다. -> 리펙토링 예정

# 질문할점 🤔
- Background로 진입했을때의 @objc 메서드 네이밍에 설정에 관하여
특정상황에서만 notification을 쓴다고 가정했을때 notification관련 메서드 네이밍에 특정상황에 대한 내용을 추가 해주어야 할까요? 예를 들어 다음코드의 notification은 ScenDelegate의 SceneDidEnterBackground 메서드에서 사용 중인데 메서드명에 Background의 내용을 추가해주어야 해야 할까요? 아니면 추가하지않아도 괜찮을까요?
(아래 주석에 1번과 2번의 코드예시가 있습니다.)

```swift
// MARK: saveDiaryData Notification

private extension WriteViewController {
  // SceneDidEnterBackground
  func addSaveDiaryObserver() {
    NotificationCenter.default.addObserver(
      self,
      selector: #selector(diarDataSave),
      name: Notification.Name("saveDiaryData"),
      object: nil)
  }
  
  func removeSaveDiaryObserver() {
    NotificationCenter.default.removeObserver(self)
  }
	// 1
  @objc func diarDataSave() {
    self.saveDiaryData()
  }
}
	// 2
  @objc func diarDataSaveDidEnterBackground() {
    self.saveDiaryData()
  }
```

- CRUD 메서드 구현시 Diary 데이터를 저장할때 발생하는 에러
오류해결은 했으나 원인을 발견하지 못 했습니다.
### [Error]
![](https://i.imgur.com/8V4yaRO.png)

### [Before]

![](https://i.imgur.com/inHPQAn.png)

### [After]
![](https://i.imgur.com/8oNM1AI.png)

- 더보기에서 글 삭제 후 MainVC의 TableViewCell 뒤섞임 오류를 해결하였으나 원인을 모르겠습니다.

이전에는 deleteContext메서드에서 viewContext.save를 해주지않았었지만 아래와 같이 저장 코드 추가하여 해결했는데 왜 이렇게 하면 cell을 삭제하여도 섞이지 않는지 모르겠습니다.

```swift
      guard viewContext.hasChanges else {
        return []
      }
      
      try viewContext.save()
```

2022-06-24 12:32 UTC, wonhee009 requested changes
스텝2 수고하셨습니다~
코멘트 남겨두었으니 확인 부탁드려요 :)

<img width="40%" alt="image" src="https://user-images.githubusercontent.com/30456206/175526975-b379d873-e926-4392-9fd6-a83718f6eaa7.png">
- 폴더를 보면 `-Scene`, `Scene` 이렇게 존재하는데요. 의도가 헷갈릴거 같습니다. `Scene` 하위에 `Main`, `Detail`, `Write`라는 폴더가 존재하는게 맞을거 같고 `App/SceneDelegate`는 `Scene`이라는 폴더와는 무관한 아이들일거 같습니다.

#### 질문

- 어떤 역할을 하는지 메서드에 잘 들어난다면 추가하지 않아도 될거 같습니다:)
- 에러에 `DiaryModel`의 `description`이 키-밸류 타입이 아녔다고 하네요.
- [공식 문서](https://developer.apple.com/documentation/coredata/nsmanagedobjectcontext/1506866-save)를 확인해보면 save를 통해 변경 사항을 저장한다고 하는데요. save 해주지 않으면 context를 일정하게 유지할 수 없어서 아닐까 생각합니다.

2022-06-24 12:32 UTC, wonhee009 commented on Diary/MainScene/Controller/MainViewController.swift
> +      self.diarys = CoredataManager.sherd.deleteContext(identifier: diary)
`CoredataManager.sherd.deleteContext` 메서드가 CoreData에서 diary를 삭제한 후 다시 diary를 읽어서 반환하는거로 이해했는데요.
```swift
self.diarys?.remove(at: indexPath.row)
```
이렇게 deleteAction에서 배열을 삭제하는 방식은 어떤가요?
이후 diary가 많아지게 된다면 `delete -> read`에 부하가 있지 않을까요?

2022-06-24 12:32 UTC, wonhee009 commented on Diary/Model/CoreDataModel/Diary+CoreDataProperties.swift
> +}
```suggestion
extension Diary : Identifiable {}
```

2022-06-24 12:32 UTC, wonhee009 commented on Diary/Scene/SceneDelegate.swift
> +  }
[이런 것도](https://developer.apple.com/documentation/uikit/uiapplication/1623071-didenterbackgroundnotification) 사용해 볼 수 있을거 같습니다.
현재는 SceneDelegate를 통해 앱 전반적으로 "saveDiaryData"에 대한 Notification이 post 될거 같은데요.
`didEnterBackgroundNotification` 해당 NotificationName을 통해 WriteVC에 해당 Notification observe한다면 좀 더 역할이 명확할거 같습니다.

2022-06-24 12:32 UTC, wonhee009 commented on Diary/Utils/Extension/UIViewController+Extension.swift
> +    let shareText = text
모든 VC에서 해당 메서드를 호출할 수 있는데 `shareText`는 공유하기에 관련한 변수명이지 않나 싶습니다 :)

2022-06-24 12:32 UTC, wonhee009 commented on Diary/Utils/Extension/UIViewController+Extension.swift
> +  ) {
파라미터가 많은 경우 하나의 struct 혹은 class로 정의해 두고 사용하는 것도 하나의 방법입니다.

2022-06-24 12:32 UTC, wonhee009 commented on Diary/Utils/Sington/CoreDataManager.swift
> +  }
해당 메서드들은 `Diary`와 관련한 CRUD로 보이는데요.
`CoreDataManager`라는 이름의 파일인만큼 `CoreData`와 관련한 일을 해야한다고 생각합니다.
현재는 `Diary`와 관련한 일을 하고 있다고 생각되구요.
`CoreDataManager`는 CoreData의 CRUD만 수행하고, `Diary` CRUD를 수행하는 레이어를 하나 더 두는건 어떨까요?
```swift
class DiaryData {
   func createDiary(...) { CoreDataManager.createContext(...) }
}
```

2022-06-24 12:32 UTC, wonhee009 commented on Diary/WriteScene/Controller/WriteViewController.swift
> +    self.addSaveDiaryObserver(action: #selector(diarDataSave))
```suggestion
    self.addSaveDiaryObserver(action: #selector(diaryDataSave))
```

2022-06-24 12:32 UTC, wonhee009 commented on Diary/WriteScene/View/WriteView.swift
> +}
사용하지 않는 뷰일까요?

2022-06-27 11:42 UTC, Quokkaaa commented on Diary/MainScene/Controller/MainViewController.swift
> +    self.baseView.tableView.delegate = self
필요한 곳에서만 self를 써주는게 구분하기 좋을것같아서 조언주신대로 수정하였습니다.
https://github.com/yagom-academy/ios-diary/pull/20/commits/ac0d598a58279b2848c88c6addda46bd1f4c2b3d

2022-06-27 11:50 UTC, Quokkaaa commented on Diary/MainScene/Controller/MainViewController.swift
>      }
저희가 99자를 초과할시 줄바꿈을 해주는 컨벤션을 따르고 있기때문에 이렇게 작성했습니다.
다음에 적용해볼게요! 👍

2022-06-27 12:01 UTC, Taeangel commented on Diary/MainScene/Controller/MainViewController.swift
> +          let diary = self.diarys else {
`let diary = diarys?[indexPath.row]`로 변경하였습니다!

2022-06-27 12:03 UTC, Taeangel commented on Diary/MainScene/Controller/MainViewController.swift
> +      }
```swift
 guard let identifier = self.diarys?[indexPath.row].identifier else {
      return
    }
```
로 변경하였습니다!

2022-06-27 12:17 UTC, Taeangel commented on Diary/MainScene/Controller/MainViewController.swift
> +      self.diarys = CoredataManager.sherd.deleteContext(identifier: diary)
```swift
let deleteAction = UIContextualAction(style: .normal, title: "삭제") { _, _, completion in
  guard let identifier = self.diarys?[indexPath.row].identifier else {
    return
  }

  CoredataManager.sherd.deleteContext(identifier: identifier)
  self.diarys?.remove(at: indexPath.row)
  completion(true)
}
```
```swift
func deleteContext(identifier: String) {
  let request = Diary.fetchRequest()
  request.predicate = NSPredicate(format: "identifier == %@", identifier)
  
  if let diary = try? viewContext.fetch(request).first {
    viewContext.delete(diary)
  }
  save()
}
```
이렇게 쓰니 @discardableResult도 안해도 되고 삭제할때마다 read를 안해도 되서 기능적으로 많은 향상이 있는것 같습니다.

2022-06-27 12:26 UTC, Quokkaaa commented on Diary/Model/CoreDataModel/Diary+CoreDataProperties.swift
> +}
불필요한 들여쓰기가 있었네요 ㅎㅎ 제거했습니다!
https://github.com/yagom-academy/ios-diary/pull/20/commits/5b39efcb9991cf91eb75f0f9ace7b319985fd84b

2022-06-27 12:38 UTC, Quokkaaa commented on Diary/Scene/SceneDelegate.swift
> +  }
공문을 꼼꼼히 살펴보도록 하겠습니다. ㅠㅠ
조언해주신 바와같이 사용하는것이 역할의 명확성이 분명한 것 같아서 수정하였습니다!
https://github.com/yagom-academy/ios-diary/pull/20/commits/a353b764af8569325fc5db2710dc449d5e066a2a

2022-06-27 12:48 UTC, Quokkaaa commented on Diary/Utils/Extension/UIViewController+Extension.swift
> +    let shareText = text
네이밍을 짓는데 꼼꼼하지 못했던 것 같습니다. 그리고 불필요한 변수로 판단하여 제거해주었습니다.
https://github.com/yagom-academy/ios-diary/pull/20/commits/1efea780518d6be0d3bfd13d71510df4fcaab050

2022-06-27 14:13 UTC, Quokkaaa commented on Diary/Utils/Sington/CoreDataManager.swift
> +  }
말씀해주신대로 역할분리하는게 좋을 것으로 판단해서 아래 커밋과 같이 수정하였는데 의도하신대로 구현됬을까요 ?
https://github.com/yagom-academy/ios-diary/pull/20/commits/2bd4b3c7cbe52b47d6b92bc8e0e42766b8a1439a

2022-06-27 14:15 UTC, Taeangel commented on Diary/WriteScene/Controller/WriteViewController.swift
> +    self.addSaveDiaryObserver(action: #selector(diarDataSave))
ㅠㅠ 수정하였습니다

2022-06-27 14:21 UTC, Taeangel commented on Diary/WriteScene/View/WriteView.swift
> +}
WriteView와 DetailView두가지를 상속해주는 DiaryBaseView를 만들고 상속을 해주었는데 WriteView는 현재와 같이 빈뷰가 되었습니다 이렇게 한 이유는 좀더 가독성이 있고 나중에 WriteView에만 있는 수정사항이 생길 경우를 대비하여 빈뷰로 만들었는데 이런 경우는 현재처럼 빈 뷰를 사용하는 편이 좋을까요 아니면 WriteView를 DetailView에게 상속을 해주는 편이 좋을까요

2022-06-28 06:46 UTC, Quokkaaa commented on Diary/Utils/Extension/UIViewController+Extension.swift
> +  ) {
https://github.com/yagom-academy/ios-diary/pull/20/commits/f8d4e98a800401ab5e65f8c15a40870f96bcdd77
위 커밋과 같이 수정하였습니다.

2022-06-28 11:06 UTC, wonhee009 commented on Diary/WriteScene/View/WriteView.swift
> +}
상속을 받아야하나요?
동일한 view로 처리 가능할거 같은데요.
내용이 있다면 textView에 text를 채워주고 없다면 없는채로 TextView를 띄워주면 될거 같은데요.
(textView에서 떠났을 때 저장되는 점, 첫번째는 제목인 점이 모두 동일하므로....)

2022-06-28 11:07 UTC, wonhee009 commented on Diary/Utils/Sington/CoreDataManager.swift
> +  }
넵 맞습니다. 다만 `CoreData`보다는 다이어리에 관련한 사항임을 알 수 있으면 좋을거 같습니다 :)

2022-06-28 11:29 UTC, Taeangel commented on Diary/Utils/Sington/CoreDataManager.swift
> +  }
DiaryData으로 변경하고 내부 메서드들은 creat, read, update, delete으로 변경하였습니다

2022-06-28 11:35 UTC, wonhee009 approved these changes
남은 리뷰는 스텝3에서 반양해주세요 :) 수고하셨습니다!

2022-06-28 11:35 UTC, merged