일기장 [STEP 3] mmim, mino, grumpy
yagom-academy/ios-diary pull request #23
Opened 2022-06-24 08:48 UTC by JoSH0318

안녕하세요 올라프!⛄️@1Consumption
일기장 프로젝트 STEP3 PR보냅니다!
잘 부탁드립니다🙇🏻‍♂️🙇🏻‍🙇

## 🧐 고민했던 점
### Open API 통신할 때, 모든 response data를 가져와야 하는가 
- 이번 프로젝트에서는 유저에게 날씨 정보를 표현할 때, 날씨 icon만을 사용합니다.
- 모든 response data를 가져와야 하는가에 대해서 고민을 했습니다. 
- open API는 불특정 다수가 사용하기 때문에 모든 데이터를 가지고 있는 것이고, 사용자에 따라서 필요로하는 정보만을 가져오는 것이라 판단했습니다.
- 따라서 통신 response data를 파싱하는 모델을 설계할 때 icon만을 파싱할 수 있도록 했습니다.
```swift
struct Weather: Decodable {
    let weather: [WeatherElement]
}

struct WeatherElement: Decodable {
    let icon: String
}
```

### 코어데이터에서 날씨정보를 어떻게 저장할 것인가
- Core Data의 모델을 변경하면서 어떤 데이터를 저장할지 고민했습니다.
    - icon(String)을 갖는 방법
    - 날씨 icon image에 해당하는 URI를 갖는 방법
    - 다운로드받은 이미지 자체를 갖는 방법
- 결과적으로 첫 번째 방법을 선택했고, 이미지 캐싱을 통해 동일한 이미지를 다운로드 받는 과정을 방지하였습니다.

### Requesting Authorization for Location Services에 대한 고민
- 위치 정보에 대한 사용자 권한을 받을 때, 어떤 방법으로 할 것인지 고민했습니다.
- 사용자 권한 동의를 앱의 첫 실행화면에서 할 것인지, 위치 정보를 얻어야 하는 순간에 할 것인지 고민했다.
    - 첫 실행화면에서 할 경우: 사용자의 모든 일기에 위치정보가 추적됩니다. 만약 사용자가 경우에 따라 특정 일기에는 이 기능을 사용하고 싶지 않을 수도 있다는 생각을 했습니다.
    - 새로운 일기를 작성하는 화면에서 할 경우: 일기를 작성할 때마다 동의를 해야하는 번거로움이 있지만, 사용자에게 더 폭넓은 선택권을 줄 수 있다고 판단했습니다.
- 이러한 근거로 새로운 일기를 작성하는 화면에서 할 때, 위치 정보에 대한 사용자 권한을 받는 것을 선택했습니다.

### Authorization for Location Services 거절 시 어떻게 처리할 지에 대한 고민
- 위치 정보에 대한 사용자 권한을 거절했을 때 어떻게 처리할지 고민했습니다.
- 만약 사용자가 거절하게 된다면 해당 사항에 대한 알럿을 띄워주고, 디바이스 설정화면으로 이동하여 사용자가 직접 설정해주도록 유도하게끔 했습니다.

## 📌 질문사항
### TopViewController
> 이런 뷰 계층을 무시해버리는 코드는 좋지 못하다고 생각합니다. 적어도 어떤 뷰컨에서 알러트를 띄우는지는 알아야죠.
알러트를 띄우는 코드에 어떤 뷰컨에서 띄우는지를 명시적이게 매개변수로 넘기면 좋겠습니다.

- 해당 부분의 경우 현재 로직에서 알럿을 띄울 ViewController를 아는 방법을 찾지 못했습니다😭
- 최상위 뷰를 구하여 알럿을 띄우는 것이 아닌, CoreData 로직에서 최상위에 있는 persistentContainer부터 
- throw나 Result타입을 활용해서 ViewController까지 에러를 가져와서 알럿을 띄우는 것이 더 나은 방향일까요?

감사합니다!

2022-06-26 15:14 UTC, 1Consumption requested changes
고생하셨습니다~ 👍👍👍 

코멘트를 달긴 했는데, 디코에서 한번 더 얘기해보면 좋을 거 같아요.

아래는 고민한 점에 대한 제 코멘트입니다.

----------------------------------------------------------------


해당 부분의 경우 현재 로직에서 알럿을 띄울 ViewController를 아는 방법을 찾지 못했습니다😭
최상위 뷰를 구하여 알럿을 띄우는 것이 아닌, CoreData 로직에서 최상위에 있는 persistentContainer부터
throw나 Result타입을 활용해서 ViewController까지 에러를 가져와서 알럿을 띄우는 것이 더 나은 방향일까요?

> 알럿을 띄우는 메소드의 매개변수로 ViewController를 받으면 되지 않을까요?
그리고 저는 대부분의 에러 처리는 최상단에서 사용자에게 알려야한다고 생각해요.

2022-06-27 12:05 UTC, grumpy-sw commented on Diary/Common/Network/RequestManager.swift
> +        }
클로저 내부에서 `self.verifyError`로 참조가 발생하고 있기 때문에 `[weak self]`를 붙여주었습니다. 감사합니다.

2022-06-27 12:25 UTC, Mino777 commented on Diary/Scene/Detail/View/RegistrationViewController.swift
> +    private let locationManager = CLLocationManager()
locationManager를 ViewModel로 옮겼습니다.
감사합니다!

2022-06-27 12:29 UTC, Mino777 commented on Diary/Common/Util/ImageCacheManager.swift
> +}
https://developer.apple.com/documentation/foundation/nscache

You can add, remove, and query items in the cache from different threads without having to lock the cache yourself.

NSCache의 경우에 공식문서에 따로 처리를 해주지 않아도 thread safe 하다는 글을 보고 작성한 코드입니다!
혹시 저희가 모르는 문제가 있을까요?😭

만약 thread safe 하지 않다면 저희도 올라프가 말씀해주신 방안들로 수정할 것 같습니다!
감사합니다!

2022-06-27 12:33 UTC, Mino777 commented on Diary/Common/Extension/UIImageView.swift
> +}
해당 로직은 view의 역할이 아닌것이 확실하지만, 이미지를 다운 받고 그 후에 셀을 만드는 작업을 진행하는 경우에 셀을 만드는 시간이 오래걸릴 수 있다는 생각에 해당 역할을 cell이 가지도록 진행하였습니다.

그럼에도 viewModel로 빼주는것이 좋을까요?
감사합니다!

2022-06-29 15:34 UTC, 1Consumption commented on Diary/Infrastructure/Network/Endpoint/Endpoint.swift
> +}
얘는 왜 클래스인가요?

2022-06-29 15:36 UTC, 1Consumption commented on Diary/Infrastructure/Network/Endpoint/Requestable.swift
> +        }
여기는 왜 decodeError인가요? 에러를 던지는 부분이 encode말고는 없어보이는데요.

2022-06-29 15:37 UTC, 1Consumption commented on Diary/Infrastructure/Network/Endpoint/Requestable.swift
> +}
이걸 별도의 객체로 만드는게 아니라 protocol의 extension으로 선언해준 이유가 있을까요?
그리고 이건 NetworkManager의 역할 같습니다.

2022-06-29 15:37 UTC, 1Consumption commented on Diary/Infrastructure/Network/NetworkManager/NetworkManager.swift
> +import UIKit
중복되는 모듈 같습니다

2022-06-29 15:43 UTC, 1Consumption commented on Diary/Infrastructure/Network/NetworkManager/NetworkManager.swift
> +    }
NetworkManager의 역할이 아닌듯합니다. 저는 NetworkManager에서 `Data` 타입을 넘겨주고, 가공은 다른 레이어에서 해야한다고 생각합니다.

2022-06-29 15:44 UTC, 1Consumption commented on Diary/Infrastructure/Network/NetworkManager/NetworkManager.swift
> +}
extension으로 뺀 이유가 있을까요? 항상 Data가 알아야하나요?

2022-06-29 15:45 UTC, 1Consumption commented on Diary/Infrastructure/Network/NetworkManager/NetworkManager.swift
> +    ) -> URLSessionDataTask? {
Result의 Error가 구체타입이면 좋겠습니다. 그래야 받는 곳에서도 에러의 범위를 특정할 수 있어요.

2022-06-29 15:48 UTC, 1Consumption commented on Diary/Scene/Detail/View/DetailViewController.swift
> +    }
이벤트를 보낼 뿐인데 try를 해야하나요? View에서는 이벤트를 전달만 할 뿐이고,이런건 바인딩된 Observable의 값 변경을 통해 에러처리가 되면 좋겠습니다.

2022-06-29 15:50 UTC, 1Consumption commented on Diary/Scene/Detail/View/RegistrationViewController.swift
> +    private lazy var viewModel = RegistrationViewModel(delegate: self)
여기 넘기는 delegate는 CLLocationManagerDelegate인데, 이걸 View에서 알아야하나요?
ViewModel 내부로 은닉화 되었으니 이는 ViewModel 내부에서 처리해야하는거 아닐까요?
ViewModel이 delegate를 채택하면 어떨까요?

2022-06-29 15:50 UTC, 1Consumption commented on Diary/Scene/Detail/View/RegistrationViewController.swift
> +        }
여기도 마찬가지로 Observable의 값 변경을 통해 에러처리가 이루어지면 좋겠습니다.

2022-06-29 15:50 UTC, 1Consumption commented on Diary/Scene/Detail/View/RegistrationViewController.swift
>          @unknown default:
이 코드가 모두 ViewModel 내부로 들어가야할 거 같아요.

2022-06-29 15:52 UTC, 1Consumption commented on Diary/Scene/Detail/ViewModel/DetailViewModel.swift
> +    }
제가 예시로 들어드렸던 throws 코드는 스트림을 사용하지 않는다는 전제하였는데, 이미 커스텀 Observable을 만드셔서 예시와는 맞지 않는 상황 같습니다.

2022-06-29 15:53 UTC, 1Consumption commented on Diary/Scene/Detail/ViewModel/RegistrationViewModel.swift
> +        networkManager.requestAPI(with: endpoint) { [weak self] (result: Result<Weather, Error>) in
이거도 ViewModel이 UseCase같은 레이어를 가지고 메소드를 호출만 하면 좋겠어요. endpoint 정보는 UseCase가 아는거죠. ViewModel은 View의 로직에만 집중할 수 있도록 말이죠.

2022-06-29 15:54 UTC, 1Consumption commented on Diary/Scene/Main/ViewModel/DiaryCellViewModel.swift
> +import UIKit
중복되는 코드네요.

2022-06-29 15:54 UTC, 1Consumption commented on Diary/Scene/Main/ViewModel/DiaryCellViewModel.swift
> +    private(set) var task: URLSessionDataTask?
이걸 외부에서 알아야하나요?

2022-06-29 15:54 UTC, 1Consumption commented on Diary/Scene/Main/ViewModel/DiaryCellViewModel.swift
> +    private(set) var image = Observable(UIImage())
이 옵저버블도 private(set)인 이유가 궁금하네요. 그리고 항상 초기값을 가져야하는지도 의문입니다.

2022-06-29 15:55 UTC, 1Consumption commented on Diary/Scene/Main/ViewModel/DiaryCellViewModel.swift
> +        }
이거도 한번 layer로 감싸주면 좋겠습니다.

2022-07-01 06:50 UTC, grumpy-sw commented on Diary/Common/Extension/UIViewController.swift
>      }
편의성을 위한 extension 구현이었다고 생각합니다. `Alertable` 프로토콜을 구현하고 이를 채택한 뷰컨에서 alertController를 사용하도록 변경했습니다!

2022-07-01 06:50 UTC, grumpy-sw commented on Diary/Common/Util/Observable.swift
> +    var listener: ((T) -> Void)?
작성 시 접근제어자를 빠뜨린 부분 같습니다. private 키워드 붙여주었습니다!

2022-07-01 06:54 UTC, JoSH0318 commented on Diary/Common/Util/Observable.swift
> +    }
HotObservable로 의도한 메소드입니다! ㅎㅎ

2022-07-01 06:55 UTC, JoSH0318 commented on Diary/Infrastructure/Network/Endpoint/Endpoint.swift
> +}
struct로 수정했습니다! 감사합니다 ㅎㅎ

2022-07-01 06:55 UTC, grumpy-sw commented on Diary/Common/Util/Observable.swift
> +    }
UI에 Image를 나타낼 때 UIImageView에 뿌려주는 HotObservable을 구현하기 위한 클로저 실행 라인입니다. 이후에 ColdObservable도 따로 구현할 필요가 생겨 이 부분에서 차이를 두었습니다!

2022-07-01 06:59 UTC, grumpy-sw commented on Diary/Scene/Main/ViewModel/DiaryCellViewModel.swift
> +        }
DiaryCellViewModel에서 필요한 이미지를 얻기 위해 ImageDownloader라는 새로운 계층을 넣어주었습니다. 이 곳에서 이미지 캐시 관리(ImagaCacheManager)와 이미지 다운로드(APIProvider)를 모두 알고 있어 각각의 기능을 수행합니다.

2022-07-01 06:59 UTC, JoSH0318 commented on Diary/Scene/Main/ViewModel/DiaryCellViewModel.swift
> +        }
ImageDownloader layer를 추가하여 해당 코드를 옮기는 것으로 수정했습니다 ㅎㅎ

2022-07-01 07:13 UTC, grumpy-sw commented on Diary/Infrastructure/Network/Endpoint/Requestable.swift
> +        }
encodeError로 변경했습니다!

2022-07-01 07:14 UTC, grumpy-sw commented on Diary/Infrastructure/Network/NetworkManager/NetworkManager.swift
> +import UIKit
삭제했습니다!

2022-07-01 07:17 UTC, grumpy-sw commented on Diary/Infrastructure/Network/NetworkManager/NetworkManager.swift
> +    }
네트워크 통신을 담당하는 곳에서는 request 메서드를 통해 data 타입을 전달하고, 캐시 확인 및 데이터 가공은 ImageDownloader라는 새로운 레이어에서 담당하도록 수정했습니다!

2022-07-01 07:18 UTC, Mino777 commented on Diary/Infrastructure/Network/Endpoint/Requestable.swift
> +}
원래 기존의 코드에서는 Requestable과 Responsable 프로토콜이 나누어져 있었어서 protocol의 역할을 나누는 과정이 있었습니다.
그래서 API를 요청하는 메서드에 Requestable 프로토콜 타입만 받을 수 있도록 진행하면서 프로토콜의 extension으로 해당 기능을 구현했던 것 같습니다!

현재는 해당 프로토콜은 아예 삭제하고, 로직들을 모두 NetworkManager로 이동하였습니다!
감사합니다!

2022-07-01 07:19 UTC, Mino777 commented on Diary/Infrastructure/Network/NetworkManager/NetworkManager.swift
> +}
해당 부분 삭제 후 decode를 사용하는 Repository 객체만 해당 메서드를 가질 수 있도록 수정하였습니다!
감사합니다!

2022-07-01 07:19 UTC, grumpy-sw commented on Diary/Infrastructure/Network/NetworkManager/NetworkManager.swift
> +}
decode 메서드를 내부로 이동시켜 네트워크 통신의 결과로 받은 data타입을 내부 메서드 호출을 통해 decode하도록 수정했습니다.

2022-07-01 07:19 UTC, grumpy-sw commented on Diary/Infrastructure/Network/NetworkManager/NetworkManager.swift
> +    ) -> URLSessionDataTask? {
NetworkError타입으로 변경했습니다!

2022-07-01 07:22 UTC, grumpy-sw commented on Diary/Scene/Detail/View/DetailViewController.swift
> +    }
디코에서 말씀해주신대로 관찰중인 값 'error'의 변경을 통해 Alert을 출력하도록 에러처리를 수정하였습니다!

2022-07-01 07:24 UTC, Mino777 commented on Diary/Scene/Main/ViewModel/DiaryCellViewModel.swift
> +    private(set) var task: URLSessionDataTask?
해당 Task는 ImageDownloader로 이동하였습니다!
감사합니다!

2022-07-01 07:26 UTC, grumpy-sw commented on Diary/Scene/Detail/View/RegistrationViewController.swift
> +    private lazy var viewModel = RegistrationViewModel(delegate: self)
NSObject 클래스를 상속시켜 ViewModel이 CLLocationManagerDelegate을 채택하도록 수정하였습니다. 
```swift
final class RegistrationViewModel: NSObject
```
👍

2022-07-01 07:27 UTC, grumpy-sw commented on Diary/Scene/Detail/View/RegistrationViewController.swift
> +        }
수정했습니다!

2022-07-01 07:28 UTC, grumpy-sw commented on Diary/Scene/Detail/View/RegistrationViewController.swift
>          @unknown default:
viewModel 내부로 이동했습니다!

2022-07-01 07:28 UTC, Mino777 commented on Diary/Scene/Detail/ViewModel/RegistrationViewModel.swift
> +        networkManager.requestAPI(with: endpoint) { [weak self] (result: Result<Weather, Error>) in
올라프 말씀대로 UseCase 레이어를 두어 ViewModel의 역할을 나누어주었습니다!
감사합니다!!

2022-07-01 07:29 UTC, grumpy-sw commented on Diary/Scene/Detail/ViewModel/DetailViewModel.swift
> +    }
throws와 try를 제거하고, saveDiary()와 deleteDiary()에서 try로 인해 에러가 발생하는 경우 Observable값인 error의 값을 변경시켜 뷰에서 에러처리를 하도록 변경하였습니다!

2022-07-01 07:31 UTC, grumpy-sw commented on Diary/Scene/Detail/ViewModel/RegistrationViewModel.swift
> +        networkManager.requestAPI(with: endpoint) { [weak self] (result: Result<Weather, Error>) in
새로운 계층이 WeatherUseCase를 생성하여 useCase의 requestWeather 메서드에서 API 요청을 하도록 수정했습니다! 감사합니다.

2022-07-01 13:50 UTC, 1Consumption requested changes
고생하셨습니다.
여러 레이어를 둬서 각자의 역할에 집중 할 수 있게 되었네요!
코드가 한결 읽기 좋아졌네요. 

다음 프로젝트도 화이팅입니다.

2022-07-01 13:50 UTC, 1Consumption commented on Diary/Common/Util/Observable.swift
> +    }
왜 onNext인가요...? rx를 참고하신건가요? 
rx에서 onNext는 subscribe 메소드의 매개변수 이름으로 들어가지 않나요?

2022-07-01 13:50 UTC, 1Consumption commented on Diary/Common/Util/ImageCacheManager.swift
> -
왜 싱글톤을 사용하지 않으셨나요? 이러면 ImageCacheManager가 메모리에서 없어지면 캐시도 다 날아가지 않나요?

2022-07-01 13:50 UTC, 1Consumption commented on Diary/Infrastructure/Network/APIProvider/ImageDownloader.swift
> +    }
API의 뜻은 뭔가요?

2022-07-01 13:50 UTC, 1Consumption commented on Diary/Repository/WeatherRepository.swift
> +            }
self를 언래핑해준 이유가 있을까요? 
https://medium.com/@almalehdev/you-dont-always-need-weak-self-a778bec505ef
특별한 이유가 없다면 이 아티클을 참고해보세요. 중간에 weak self를 언래핑하면 발생하는 일에 대해 적혀있습니다.

2022-07-01 13:50 UTC, 1Consumption commented on Diary/Scene/Main/ViewModel/DiaryCellViewModel.swift
> +    private let imageDownloader = ImageDownloader()
ViewModel이 deinit되면 ImageDownloader안에 있는 ImageCache도 deinit이 되겠군요. 그러면 cache의 역할을 제대로 할까요?

2022-07-05 02:03 UTC, closed without merging