일기장 [STEP 1] Finnn, 수꿍
yagom-academy/ios-diary pull request #34
Opened 2022-08-17 06:47 UTC by Jeon-Minsu

안녕하세요, 그린! @GREENOVER 
이번 일기장 프로젝트 STEP1 PR을 드리는 Finnn과 수꿍입니다!
잘 부탁드립니다!! 🙇🙇‍♂️

---

## 🗂 폴더 구조

```
.
└── Diary
    ├── AppDelegate
    ├── SceneDelegate
    ├── Models
    │   ├── DiarySampleData
    │   ├── JSONData
    │   ├── Namespaces
    │   ├── Section
    │   └── Extension
    │       ├── Date+Extension
    │       └── Int+Extension
    ├── Views
    │   ├── CustomCell
    │   ├── DiaryContentView
    │   └── DiaryView
    └── Controllers
        ├── DiaryContentsViewController
        └── DiaryViewController
```
    
## 📝 기능설명

**작성한 일기장 목록을 보여주는 TableView 구현**
    
    - JSON 샘플 데이터 파싱 구현
    - UITableView 구현
    - TableView의 CustomCell 구현 및 JSON 데이터 연동
    - Text font가 Dynamic Size에 대응하도록 구현
    - DateFormatter를 활용한 localize된 날짜 표기형식 구현
   
**새로운 일기장 작성을 위한 TextView 구현**
    
    - UITextView를 활용한 메모 작성 페이지 구현
    - UITextView에 내용 작성시 소프트웨어 키보드가 작성중인 글을 가리지 않도록 수정

## 🚀 TroubleShooting

### STEP 1
#### T1. `KeyBoard` 숨김 기능 감지 방법
- 일기장 생성 화면으로 이동하였을 때, `textView`의 `keyboardDismissMode` 프로퍼티를 `interactive`로 설정하니, 드래그가 가능한 상황에서는 화면을 위로 일정 정도 스크롤을 해보니, 키보드가 정상적으로 사라질 수 있었습니다.
- 그러나, 일기장에 아무것도 입력하지 않은 초기 화면인 경우, 입력한 내용이 없기 때문에 스크롤이 불가능하여 키보드가 사라질 수 없었습니다.
- 이에 대하여 고민해본 결과, `textView`의 `alwaysBounceVertical` 프로퍼티를 `true`로 설정하여, 초기 화면에서도 수직 스크롤을 가능하게 하여, 일정 정도 스크롤을 하면 키보드가 정상적으로 사라질 수 있었습니다.

## 1️⃣ STEP 1

### STEP 1 Questions & Answers

#### Q1. `View`와 `ViewController` 분리로 인한 
- `ViewController`의 기본 `view`를 `DiaryView`로 교체를 하였는데, `diaryView`를 사용하기 위하여, 이를 사용하는 모든 메서드에서 `guard let`을 통한 다운캐스팅이 필요하였습니다. 
- 이 때문에 동일한 코드가 중복적으로 발생하여, 해당 문제를 해결하기 위해 코드의 유연성을 높일 수 있는 방법이 무엇이 있을지 질문드리고 싶습니다.

2022-08-17 23:57 UTC, GREENOVER requested changes
@Jeon-Minsu @finnn1 
안녕하세요 Finnn, 수꿍🙇🏻
이번 일기장 프로젝트를 여러분들과 같이 참여하게 되어 영광이고 잘 부탁드려요ㅎㅎ
3주의 길지만 짧게 느껴질 시간동안 많은 것을 배워가며 프로젝트 완성 시켜봐요!!

우선 두분 스텝 1 아주 빠르고 잘 해주셔서 너무 고생 많으셨습니다🥳🥳
특히 코드들을 잘 관심사별로 잘 나눠서 가독성이 좋아 리뷰하기 편했습니다👍

앞으로 제가 드리는 리뷰들은 정말 정답이 아닌 하나의 다른 관점에서의 의견이니 여러분들의 의견과 비교해서 더 효율적이고 스타일이 맞는것을 채택해보는 방식이 좋다는걸 꼭 명심해주세요🙌

그럼 리뷰 시작하겠습니다🏃🏻
***
### 칭찬 드리고 싶은 부분
- 기능 구현이 전체적으로 깔끔하고 군더더기가 없네요 💯
- 전반적으로 프로퍼티 및 메서드등의 네이밍이 적절해서 가독성이 좋았어요 💯
- 커밋의 세부적인 관리 및 커밋 메시지도 적절해요 💯
- 코드 베이스 기반의 뷰 구현이 아주 깔끔하네요 💯
***
### 궁금하신 부분에 대한 저의 의견
1. View와 ViewController 분리로 인한
- 요 부분은 리뷰 코멘트에서 그 코드에서 살짝 의견은 남겨보았지만 여기도 정리해볼꼐요..!
여러 방법이 있겠지만 저는 해당 DiaryView를 loadView 메서드에서가 아닌 해당 클래스에서 전역적으로 사용할 수 있도록 프로퍼티로 뺄서 주입할것 같습니다!
즉 해당 클래스를 생성할때 DiaryView 타입의 diaryView 같은 프로퍼티를 클래스가 가질 수 있도록 주입받거나 내부에서 정의 및 생성해주고,
그 뒤 loadView에서 view = diaryView와 같은 형태로 해당 클래스에서의 view 값을 넣어주는것도 방법일것 같아요🙋🏻
이정도만 하더라도 바인딩 및 다운 캐스팅은 하지 않아도 되기에 코드 중복은 피할 수 있긴합니다!
***
### 보완되면 좋을 부분들
1. cell에 대한 deselect 처리 관련
- 현재는 셀을 클릭하게 되면 클릭된 셀의 배경이 회색으로 계속 남아 있게 됩니다.
+ 버튼으로 다른 뷰를 갔다와도 마찬가지겠구요..!
이 부분이 어색해보이는데 셀의 deselect 처리를 적절히 해주는건 어떨까요~?🙋🏻
![Simulator Screen Shot - iPhone 11 - 2022-08-17 at 19 18 50](https://user-images.githubusercontent.com/72292617/185263120-a8d2aa4b-67e7-40f1-ab2c-b6a11e8bcdfd.png)
2. 에러 처리
- 현재는 에러 처리라고 할게 크게 없지만 데이터 파싱 시 에러 발생했을 경우 사실 print 디버깅문만 찍힐 뿐 사용자에게 에러 상황이라는걸 감지 할 수 있는것은 없어보여서요🥲
물론 이 부분은 기획에 없기에 나~중에 기회되시면 해보셔도 됩니다!
다만 중요한건 저희는 클라이언트 개발자이고 현업에서 가장 중시되는것중 하나는 에러 처리에 대한 것일거에요.
즉, 사용자가 앱을 사용하면서 데이터 파싱이 이뤄지지 않았을때 이게 어떤 상황인지 얼럿이나 토스트 메시지 같은 에러 상황을 인지시켜주고 후속 처리를 해줄 수 있는것이 일반적인 앱의 사용성일것 같아요🙋🏻
그렇기에 지금 생각난김에 간단히 말씀드립니다..!
지금 이 부분은 리팩토링 시 포함되지 않아도 무방합니다~
요런것도 추후에는 고려해야하겠구나🤔로 해석해주시면 감사하겠습니다🙌
(물론 이 부분도 리팩토링 하는게 제일 베스트지만 시간을 많이 뺏기지 않는 다는 선에서 해보시길 권장드려요. 필수 경험 사항이 아니기에 여기에 많은 시간을 투자하면 다른걸 놓칠 수도 있으니까요.)
***
두분 다시 한번 고생 많으셨어요ㅎㅎ
기능 구현 및 필수 핵심사항에 어긋나는게 없어 바로 어프로브 해도 되지만 사용성에서 조금 더 보완할 수 있을것 같아 우선 Request Changes로 남겨둘께요!
언제든 리팩토링 하셔도되고 다음 스텝에서 고치거나 지금 코드가 적절하다 생각하시면 머지 요청 부탁드립니다🙋🏻
화이팅이에요🥳

2022-08-18 07:29 UTC, finnn1 commented on Diary/AppDelegate.swift
> -
감사힙니다 🙏🙏

2022-08-18 07:32 UTC, Jeon-Minsu commented on Diary.xcodeproj/project.pbxproj
>  				IPHONEOS_DEPLOYMENT_TARGET = 14.0;
https://developer.apple.com/library/archive/featuredarticles/XcodeConcepts/Concept-Targets.html

위의 애플 공식문서를 살펴본 결과, 프로젝트는 하나 이상의 타겟을 가질 수 있습니다. 

그리고 배포 최소버전은 Project와 Target의 수준에서 설정할 수 있는데, 
프로젝트 수준에서의 배포 최소 버전은 프로젝트 전반, 즉 여러 타겟의 배포 최소 버전을 관장하고, 
타겟 수준에서의 배포 최소버전은 해당 타겟 수준의 배포 최소 버전만을 관장합니다. 

주의할 점은 Diary 타겟의 배포 최소 버전은 Diary 프로젝트의 배포 최소 버전을 override 합니다. 
즉, 프로젝트보다 타겟의 배포 최소 버전이 높을 경우, 타겟의 배포 최소 버전이 기준이 됩니다!

2022-08-18 07:32 UTC, finnn1 commented on Diary/Models/JSONData.swift
> +            print(error)
해당 부분에서 단순 `print`만 하는 것이 아닌, `Result Type`을 활용해서 외부에서 에러를 처리할 수 있도록 리팩토링 했습니다.
결과적으로 외부에서 해당 에러를 활용해서 사용자가 인지할 수 있도록 `Alert`를 띄워주는 방식으로 구현했습니다 ☺️

2022-08-18 07:34 UTC, finnn1 commented on Diary/Models/JSONData.swift
> +            let data = try jsonDecoder.decode(T.self,
말씀해주신 컨벤션으로 변경한 결과 코드의 가독성이 훨씬 좋아졌습니다 ☺️
감사합니다 🙏🙏

2022-08-18 07:40 UTC, Jeon-Minsu commented on Diary.xcodeproj/project.pbxproj
>  		C739AE27284DF28600741E8F /* SceneDelegate.swift in Sources */ = {isa = PBXBuildFile; fileRef = C739AE26284DF28600741E8F /* SceneDelegate.swift */; };
AppDelegate, SceneDelegate, info.plist, Assets, LaunchScreen, Diary Core Data는 프로덕트를 지원하기 위한 파일이기 때문에, Resources 폴더를 생성하여 그룹핑 작업을 진행하였습니다.

2022-08-18 07:41 UTC, finnn1 commented on Diary/Models/Extension/Date+Extension.swift
> +//  Date+Extension.swift
생각해보니 Model의 역할로 묶기에는 어색함이 있었던 것 같습니다 😢
Extension을 Model 밖으로 빼주었습니다! ☺️🙏

2022-08-18 07:44 UTC, Jeon-Minsu commented on Diary/Models/JSONData.swift
> +struct JSONData {
성능 관점에서 고려를 해보았을 때, 참조 타입인 class 보다는 값 타입인 struct로 타입을 지정하였을 때, 이점이 있는 것으로 알고 있습니다.
또한, 상속 기능을 필요로 하지 않기 때문에, class를 타입 고려 대상으로 인식하지 않았습니다.
Apple은 기본적으로 값 타입 사용을 권장하고 있기 때문에, 참조 기능이 필요하지 않은 이상 이번 프로젝트에서는 기본적으로 struct 사용을 지향하는 것이 좋다고 판단하였습니다.
값 타입이지만, enum을 사용하지 않은 이유는 열거형 구조를 필요로 하지 않는다고 판단하였기 때문입니다.

2022-08-18 07:45 UTC, finnn1 commented on Diary/AppDelegate.swift
> -        // Override point for customization after application launch.
Looks Good to Me 라는 말을 처음 알았네요 ☺️
앞으로도 좋은 습관 유지하도록 노력하겠습니다 👍
감사합니다 🙏🙏

2022-08-18 07:47 UTC, finnn1 commented on Diary/Models/Namespaces.swift
> +//  Namespaces.swift
모델의 역할에 대해서 더욱 고민을 많이 해봐야할 것 같습니다 😢
해당 Namespace 들을 Model 외부로 빼주었습니다!

2022-08-18 08:00 UTC, Jeon-Minsu commented on Diary/Models/Namespaces.swift
> +}
enum 안에 static let 사용은 인스턴스화시 컴파일 에러가 발생하기 때문에, case 사용에 비하여 뜻하지 않는 초기화를 막을 수 있습니다. 
이는, 불필요한 초기화 없이 순수히 namespace로서의 역할을 수행하기에 적합하다고 판단하였습니다.

2022-08-18 08:01 UTC, Jeon-Minsu commented on Diary/Models/Section.swift
> +}
Section 열거형 구조는 DiaryListViewController에서만 사용되기 때문에, 해당 파일로 이동하였습니다!

2022-08-18 08:27 UTC, Jeon-Minsu commented on Diary/Models/Extension/Date+Extension.swift
> +    func formatToStringDate() -> String? {
예외 사항에 대하여 throw를 요구하지 않고, 계산 비용이 저렴하며, 사용자 입장에서 프로퍼티라고 직관적으로 인식이 필요할 때, 연산 프로퍼티를 활용하고,
이와 반대로, 예외 사항에 대한 throw 처리를 요구하고, 계산 비용이 저렴하지 않으며, 프로퍼티임을 직관적으로 인식할 필요가 없을 때는 메서드를 사용하는 것이 좋다고 생각합니다.

이에, 저희도 다시 생각해보니, Date를 현지화된 String Date를 반환하는 것은 복잡한 계산을 요구하지 않고, 프로퍼티라고 직관적으로 인식을 필요로 한다 생각하여, 연산 프로퍼티 방식으로 코드를 수정하였습니다.

2022-08-18 08:43 UTC, Jeon-Minsu commented on Diary/Models/Extension/Date+Extension.swift
> +              let deviceLocale = Locale(identifier: localeID).languageCode else { return nil }
저희가 locale과 timezone에 대하여 다시 토의해본 결과, 프레젠테이션용 데이터 형식 지정에 사용하기 위한 언어, 문화 및 기술 컨벤션에 대한 정보를 나타내는 로케일의 경우에는 사용자가 선호하는 언어를 따라가는 것이 적절하다고 생각합니다. 다만, timeZone의 경우에는 현재 거주중인 지역의 시간을 사용하는 것이 옳다고 생각했습니다.

예를 들어, 한국에 살지만 영어를 선호하는 언어로 설정한 사용자의 경우, locale은 영어를 기준으로 표현하고, timezone의 경우는 미국 시간을 필요로 하지 않고, 본인이 거주중인 지역을 기준으로 표현하는 것이 자연스러운 표현이라고 생각합니다.

2022-08-18 08:43 UTC, Jeon-Minsu commented on Diary/Models/Extension/Date+Extension.swift
> +        dateFormatter.timeZone = TimeZone.current
위에서 밝힌 바와 같이, timeZone의 경우는 현재 사용자의 지역을 따라가는 것이 옳다고 생각합니다!

2022-08-18 08:47 UTC, finnn1 commented on Diary/Views/CustomCell.swift
> +class CustomCell: UITableViewCell {
좋은 참고 자료 감사합니다! 🙏🙏
해당 클래스가 별도로 상속을 하지 않아 `final` 키워드 붙여주었습니다 ☺️

2022-08-18 08:49 UTC, finnn1 commented on Diary/Views/DiaryView.swift
> +class DiaryView: UIView {
`DiaryListView` 네이밍 너무 좋은 것 같아요! 감사합니다 🙏
네이밍을 잘 짓는 연습이 더 필요할 것 같습니다.. 😢
수정 완료했습니다!

2022-08-18 08:49 UTC, finnn1 commented on Diary/Views/DiaryContentView.swift
> +        configureUI()
`DiaryListCell` 로 네이밍 변경해주었습니다~🙏

2022-08-18 08:49 UTC, finnn1 commented on Diary/Views/CustomCell.swift
> +class CustomCell: UITableViewCell {
DiaryListCell 로 네이밍 변경해주었습니다~🙏

2022-08-18 08:51 UTC, finnn1 commented on Diary/Views/DiaryContentView.swift
> +        configureUI()
거기까지 미처 생각하지 못한 것 같습니다 😢
해당 부분 수정했습니다 🙏

2022-08-18 08:52 UTC, finnn1 commented on Diary/Views/DiaryContentView.swift
> +    }()
`configureTextView()` 메서드 내부로 해당 코드들을 통합해주었습니다 🙏

2022-08-18 08:52 UTC, finnn1 commented on Diary/Controllers/DiaryContentsViewController.swift
> +class DiaryContentsViewController: UIViewController {
`final` 키워드 붙여주었습니다! 감사합니다 🙏

2022-08-18 08:53 UTC, finnn1 commented on Diary/Controllers/DiaryContentsViewController.swift
> +        view.backgroundColor = .white
사용자 설정에 따라 동적으로 대응할 수 있도록 `.systemBackground` 로 변경해주었습니다!

2022-08-18 08:55 UTC, finnn1 commented on Diary/Controllers/DiaryContentsViewController.swift
> +        view = DiaryContentView()
`DiaryContentView` 를 별도의 프로퍼티로 분리해주었습니다. ☺️
상세한 코드 예시까지... 감사합니다! 🙏👍

2022-08-18 08:55 UTC, finnn1 commented on Diary/Controllers/DiaryViewController.swift
> +class DiaryViewController: UIViewController {
`final` 키워드 및 `DiaryListViewController` 으로 네이밍 수정해주었습니다 ☺️

2022-08-18 08:56 UTC, finnn1 commented on Diary/Controllers/DiaryViewController.swift
> +    var dataSource: UITableViewDiffableDataSource<Section, DiarySampleData>?
감사합니다 🙏🙏

2022-08-18 08:56 UTC, finnn1 commented on Diary/Controllers/DiaryViewController.swift
> +    let diarySampleData: [DiarySampleData]? = JSONData.parse(name: AssetData.sample)
앗 그러네요! 해당 프로퍼티들 private을 붙여 은닉화 헤주었습니다 🙏

2022-08-18 08:57 UTC, finnn1 commented on Diary/Controllers/DiaryViewController.swift
> +        configureDataSource()
메서드들을 순서에 맞도록 재정렬 했습니다 ☺️

2022-08-18 08:58 UTC, finnn1 commented on README.md
> +# 일기장
응원 감사합니다!!
꼼꼼한 리뷰 감사드립니다 ☺️
👍👍👍

2022-08-18 08:59 UTC, finnn1 commented on Diary/Controllers/DiaryViewController.swift
> +        title = "일기장"
앗 그렇군요! 해당 리터럴 문자열을 별도의 네임스페이스로 분리해주었습니다 ☺️

2022-08-18 09:01 UTC, finnn1 commented on Diary/Controllers/DiaryViewController.swift
> +    private func goToDiaryContentsViewController() {
`moveTo` 로 변경해주었습니다 ☺️ 섬세한 리뷰 감사합니다 👍

2022-08-18 09:07 UTC, finnn1 commented on Diary/Controllers/DiaryViewController.swift
> +    @objc private func plusButtonDidTapped() {
저희도 영알못이지만 `Tapped`가 맞는 것 같습니다 😅 세심한 리뷰 감사힙니다 🙏🙏

2022-08-19 00:32 UTC, GREENOVER approved these changes
@Jeon-Minsu @finnn1 
두분 리팩토링 너무 잘해주셨어요! 고생 너무 많으셨습니다ㅎㅎ
스텝1에서 필수사항들을 넘어서서 더 사용성이 극대화되어 바로 다음 스텝으로 넘어가시죠~
간단하게 아주 나중에라도 생각해보면 좋을 포인트 하나 코멘트 남겼습니다..!
추가로, VC에서 title에 들어갈 날짜 문자열등과 같은것들을 최대한 VC의 프로퍼티로 정의하고 이니셜라이저를 통해 해당 VC를 생성할때 의존성 주입하는 방향으로 가면 추후에 기획이 변경되어도 편하게 대응할 수 있지 않을까합니다🙋🏻
다시 한번 수고 많으셨고 다음 스텝도 화이팅입니다!🥳🥳🥳

2022-08-19 00:32 UTC, GREENOVER commented on Diary/Controllers/DiaryListViewController.swift
>          )
추후에 얼럿들이 공통적으로 다른곳에서도 많이 호출되고 사용된다면 별도로 빼고 커스텀하게 파라미터만 바꿔
호출 시켜 사용하는것도 좋아보이네요🙌

2022-08-19 00:33 UTC, merged