일기장 [STEP1] Unchain, 웡빙
yagom-academy/ios-diary pull request #36
Opened 2022-08-17 07:49 UTC by wongbingg

안녕하세요 쿠마! @leejun6694  언체인과 웡빙입니다!  @wongbingg @unchain123
이번 프로젝트 첫번째 PR을 보냅니다 ! 잘 부탁드립니다 ☺️☺️

# 일기장 STEP 1 PR
###### tags: `PR`

## FileTree
```
.
└── Diary  
    ├── .swiftlint
    └── Diary
        ├── Extensions
        │   └── TimeInterval+Extension
        ├── DiaryList
        │   ├── DiaryListCell
        │   ├── DiaryListView
        │   └── DiaryListViewController
        ├── Diary
        │   ├── DiaryView
        │   └── DiaryViewController
        ├── Model
        │   ├── DiaryModel
        │   ├── JsonParser
        │   └── NameSpace
        ├── AppDelegate
        ├── SceneDelegate
        ├── Info.plist
        └── Diary.xcdatamodeld
```
## 구현사항
### 공통
**- SwiftLint 적용** O
**- 가로/세로 모드 모두 대응가능** O
**- UI는 모두 코드를 통해 구현** O
### STEP 1-1
**- 일기장 리스트 화면 구현**
- tableView 를 기반으로 list 형식으로 cell을 볼 수 있도록 화면 구현
    - DiaryList를 볼 수 있는 "DiaryListView" 생성
    - "DiaryListView" 를 제어하는 "DiaryListViewController" 생성
    - 테이블뷰에 들어갈 "DiarylistCell" 생성
- "sample" json 파일을 JsonParser에서 디코딩 후 셀에 데이터 표현
    - CodingKeys를 통해 snake_case를 표현
    - "creat_at" 프로퍼티는 timeInterval을 나타내는 Double 값으로 판단되어, 받아온 timeInterval 을 DateFormatter를 통해 형식변경과 locale 설정, timezone 설정
- 네비게이션바 버튼 "+" 터치 시, 다음 뷰로 이동

### STEP 1-2
**- 일기장을 새로 작성하는 화면 구현**
- "DiaryView" 생성
- "DiaryView"를 제어하는 "DiaryViewController" 생성
- 화면에서 네비게이션바 타이틀을 현재 시간으로 지정
- textView에 내용작성 시 
    - place holder를 통해 입력칸임을 표시
    - 첫 줄이 제목이 되도록 title 크기를 차별화 (UITextViewDelegate 이용)
    - 키보드가 작성중인 내용을 가리지 않도록 처리
    - 키보드에 닫기버튼을 추가

## Trouble Shooting
1. 시간표현 오류
- 처음 JSON데이터를 받아와서 시간으로 표현해 주기 위해 decoding을 Date타입으로 받아서 처리했더니 다음과 같이 2051년으로 나왔습니다.
- Date타입의 이니셜라이저가 `timeIntervalSinceReferenceDate`를 기준으로 되면 저희가 받아오는 JSON데이터의 값이 약 50년을 나타내서 이 날짜가 나오는 것처럼 보였습니다
- Date의 디폴트가 `timeIntervalSinceReferenceDate`여서 이렇게 표현 됐다고 판단하고 timeInterval을 extension하여 `timeIntervalSince1970`로 변환하여 해결하였습니다.

| 실제시간보다 30년 후로 나온 사진 |
| -------- |
| <img src=https://i.imgur.com/XnC0clw.png width=300> |

2. 파일의 위치 변경에서 오류 
- xcode상에서가 아닌, 실제 파일을 직접 다른 폴더로 옮겨주었는데, 원래 위치에 있던 파일이 없어졌다고 파일이름이 빨간색으로 바뀌기만 하고 실제 옮겨진 파일을 인식하지 못했다. 그래서 해당 커밋을 revert 시키고 이번엔 xcode상에서 파일위치를 옮겨주니 잘 동작을 하였다. 앞으로 파일을 옮길 일이 있으면 꼭 xcode상에서 옮겨야 겠따

## 질문사항

1. 폴더정리
- 원래 폴더정리를 할 때 controller는 controller끼리 묶고 view면 view끼리 묶는 것처럼 동일한 타입위주로 정리를 했었는데

- 이전 리뷰에서 각각의 뷰컨트롤러 별로 파생되는 기능들이나 관련 비즈니스 로직이 함께 정리 되어있는게 좋다고 하셔서 이번에는 각 뷰컨트롤러에 대해 함께 기능하는 파일들을 모아서 정리해 보았습니다.

- 이런 정리 방법이 괜찮은건지 저희가 정리한 부분이 맞는지 알고 싶습니다.

2022-08-18 08:37 UTC, leejun6694 requested changes
Unchain, 웡빙 안녕하세요 : )
step 1 코드를 확인하고, 몇 가지 포인트에 리뷰를 남겼는데 확인 부탁드립니다!

2022-08-18 08:37 UTC, leejun6694 commented on Diary/Diary/DiaryView.swift
> +    init(_ rootViewController: UIViewController) {
DiaryView 를 띄우는 곳에서 addSubview + set constraint 를 하는 것이 아닌, DiaryView 에서 rootViewController 을 받아서 설정해주는 이유가 있을까요?
view 를 재활용할 때, 상황에 따라 constraint 가 바뀌는 경우는 어떨까요?

2022-08-18 08:37 UTC, leejun6694 commented on Diary/Diary/DiaryViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillAppear), name: UIResponder.keyboardWillShowNotification, object: nil)
적절한 위치에서 줄바꿈을 해주면 가독성이 더 올라갈 것 같습니다~!

2022-08-18 08:37 UTC, leejun6694 commented on Diary/Diary/DiaryViewController.swift
> +extension DiaryViewController: UITextViewDelegate {
DiaryView 가 아닌, ViewController 에서 delegate method 를 정의해준 이유가 있을까요?
textView 를 갖고 있는 DiaryView 에서 정의하는게 자연스럽지 않을까 생각되네요 : )

2022-08-18 08:37 UTC, leejun6694 commented on Diary/DiaryList/DiaryListCell.swift
> +
UITableViewCell 의 경우, 재사용에서 문제가 될 수도 있으므로 `prepareForReuse` 를 정의해서 사용하는 것을 추천드립니다ㅎㅎ

2022-08-18 08:37 UTC, leejun6694 commented on Diary/DiaryList/DiaryListViewController.swift
> +extension DiaryListViewController: UITableViewDelegate {
불필요한 코드로 보이네요 @.@

2022-08-18 08:37 UTC, leejun6694 commented on Diary/Model/JsonParser.swift
> +        var diaryModel: [DiaryModel]?
배열이므로 복수형으로 `diaryModels` 는 어떨까요?

2022-08-18 08:37 UTC, leejun6694 commented on Diary/Model/JsonParser.swift
> +                print("타입이 \(type) 가 아닙니다. \(descriptionList[descriptionList.count - 2]) 타입을 사용 해주세요.")
`descriptionList.count - 2` 은 다른 개발자가 확인할 때 이해가 어려울 수도 있고, 위험할 수도 있는 배열 접근으로 생각됩니다.

2022-08-18 08:40 UTC, leejun6694 commented
> 폴더정리

네, 저도 기능별로는 나누는걸 더 선호하긴합니다ㅎㅎ

예)
DiaryList
       ├── View
        │   ├── DiaryListCell
        │   ├── DiaryListView
       ├── ViewController
        │   └── DiaryListViewController
       ├── Model
        │   ├── SomeModel

2022-08-19 01:43 UTC, unchain123 commented on Diary/Diary/DiaryView.swift
> +
MARK주석으로 구분해주었습니다

2022-08-19 01:44 UTC, unchain123 commented on Diary/DiaryList/DiaryListViewController.swift
> +extension DiaryListViewController: UITableViewDelegate {
넵 미리 만들어 뒀다가 까먹었습니다. 바로 삭제 했습니다.

2022-08-19 01:48 UTC, wongbingg commented on Diary/Diary/DiaryViewController.swift
> +        self.view.backgroundColor = .systemBackground
self. 이 필요하지 않은 부분들 모두 지워주었습니다! ㅎㅎ

2022-08-19 02:42 UTC, unchain123 commented on Diary/Diary/DiaryViewController.swift
> +    private var diaryView: DiaryView?
특별한 이유는 없었습니다. 뷰의 삽입 방식을 바꾸는 과정에서 변경해주었습니다.

2022-08-19 02:43 UTC, unchain123 commented on Diary/Diary/DiaryView.swift
> +    init(_ rootViewController: UIViewController) {
view의 재활용을 위해 view의 constraint는 viewConstraint에서 설정할 수 있도록 변경하였습니다.

2022-08-19 02:46 UTC, wongbingg commented on Diary/Diary/DiaryViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillAppear), name: UIResponder.keyboardWillShowNotification, object: nil)
파라미터가 많은 경우 줄바꿈으로 분리를 해주었습니다 ! ㅎㅎ

2022-08-19 03:08 UTC, wongbingg commented on Diary/Diary/DiaryViewController.swift
> +extension DiaryViewController: UITextViewDelegate {
말씀주신데로 UITextViewDelegate 채택을 View 에서 해주고, UITableViewDatasource 도 마찬가지로 View 에서 채택 해주었습니다 ㅎㅎ 조언 감사합니다 ! 👍👍

2022-08-19 03:08 UTC, wongbingg commented on Diary/Model/JsonParser.swift
> +        var diaryModel: [DiaryModel]?
항상 이부분을 잊어버리네요..ㅜㅜ 수정 하였습니다! ㅎㅎ

2022-08-19 03:10 UTC, wongbingg commented on Diary/Model/JsonParser.swift
> +                print("타입이 \(type) 가 아닙니다. \(descriptionList[descriptionList.count - 2]) 타입을 사용 해주세요.")
쿠마 말씀에 동감합니다! 해당 부분은 다른부분과 통일 시켜주었습니다 🧐🧐

2022-08-19 03:16 UTC, unchain123 commented on Diary/DiaryList/DiaryListCell.swift
> +
이번 스탭에서는 재사용을 할 일이 없다고 생각하여 정의 하지 않았었습니다. 다음 스탭을 위해 미리 정의해 놓도록 하겠습니다.

2022-08-21 07:32 UTC, leejun6694 approved these changes
리뷰 내용을 잘 반영해주셨네요~~!
step 2 에서도 잘 부탁드립니다 : )

2022-08-21 07:32 UTC, leejun6694 commented on Diary/Diary/DiaryView.swift
> +
여기도 
`// MARK: - UITextViewDelegate`
요렇게 넣어줄 수 있습니다 : )

2022-08-21 07:32 UTC, leejun6694 commented on Diary/Diary/DiaryViewController.swift
> +    // MARK: - Methods
저는 property 와 life cycle 외 method 들은 각각의 특성에 맞게 extension 으로 묶어주는 방식을 선호하고 있습니다.
이런 방법도 있다는걸 참고로 말씀드려요~!

2022-08-21 07:33 UTC, merged

2022-08-22 05:04 UTC, wongbingg commented on Diary/Diary/DiaryView.swift
> +
앗 그렇군요 ! ㅎㅎ 이 부분도 수정해야겠네요 ㅎㅎ