일기장 [STEP1] Derrick, Hugh
yagom-academy/ios-diary pull request #37
Opened 2022-08-17 11:05 UTC by derrickkim0109

안녕하세요! 콘 @protocorn93 

Step01 PR 올립니다.!

   
## 📝 기능설명

**일기장 UI 구현**
- TableView
- StackView
- TextView

**화면 전환시 데이터 전달**
- 변수를 사용해 데이터 전달
    
**일기장 화면의 Text View & 키보드**
- 현재 커서로 textView를 클릭하는 위치가 키보드에 가려지지 않도록 구현
- 현재 사용자가 작성하는 부분은 화면에 보이도록 구현

## 🚀 TroubleShooting
    
### STEP 1

#### T1. `UITableViewDiffableDataSource`의 사용방법
    - 데이터를 snapshot에서 받아 UI Update가 작동해야하는 상황이나 데이터를 받지 못해서 발생한 문제
    
```swift 
    private func fetchData() {
    let fileName = "diarySample"
    let result = jsonManager.checkFileAndDecode(dataType: [DiaryContent].self, fileName)

    switch result {
    case .success(let contents):
        diaryContents = contents
        updateDataSource(data: contents)
    case .failure(_):
        break
    default:
        break
    }
}

private func updateDataSource(data: [DiaryContent]) {
    var snapshot = NSDiffableDataSourceSnapshot<Section, DiaryContent>()
    snapshot.appendSections([.main])
    snapshot.appendItems(data)

    dataSource?.apply(snapshot)
}
```
- 데이터를 먼저 받아온 후 snapshot을 업데이트 하는 방식을 사용하였습니다.
    
    
#### T1. TextView의 스크롤뷰 
    - Text View의 heigth가 클 경우 제목이 사라지는 현상 발생
```swift!
extension UITextView {
    func focusTop() {
        let contentHeight = self.contentSize.height
        let offSet = self.contentOffset.y
        let contentOffset = contentHeight - offSet
        self.contentOffset = CGPoint(x: 0, y: -contentOffset)
    }
}
```
## 궁금한점
- Label의 text에 대한 처리를 DiaryViewModel에서 해주고 있습니다. MVVM 패턴에서 이런 처리를 ViewModel에서 처리하는 게 맞다고 생각하였는데 제대로 처리한 것일까요?

2022-08-18 14:56 UTC, protocorn93 requested changes
두 분 모두 고생하셨어요! 👏 두 분이 생각하시는 MVVM이 어떤 구조인지 궁금하네요. 현재 구조는 단순히 ViewModel이라는 네이밍을 가진 객체를 사용하고만 있는 것이고 구조적으로 MVVM의 어떤 이점도 가져가고 있지 못한 것 같아요! 

## 궁금한 점 

> Label의 text에 대한 처리를 DiaryViewModel에서 해주고 있습니다. MVVM 패턴에서 이런 처리를 ViewModel에서 처리하는 게 맞다고 생각하였는데 제대로 처리한 것일까요?

네 맞아요. MVVM에서 뷰모델의 역할 중 하나죠! `화면에 보여주는 형태로의 데이터 가공` 하지만 단순히 이 정도로만 사용되고 있기에 MVVM에 대한 학습이 좀 더 필요해보여요! 

기본적으로 왜 MVVM이라는 아키텍처가 나오게 되었고 이를 통해 기존 MVC의 어떤 문제를 해결할 수 있는지에 대해서 학습해보시면 좋을 것 같아요. 사실 이 안에는 굉장히 많은 개념들이 들어가는데 천천히 학습해보시는걸 권장해드려요. 

MVVM도 그 형태가 다양할 수 있지만 아키텍처를 사용하는 목적은 동일하기에 다양한 MVVM 코드를 살펴보시는 것도 좋아요. 그리고 MVVM 이외에도 다양한 아키텍처가 있는데 이들에 대해서는 이후에 천천히 학습해보시는게 좋을 것 같아요.

2022-08-18 14:56 UTC, protocorn93 commented on Diary/Extensions/Date+Extensions.swift
> +    }
이 변수의 목적이 무엇인가요? 

1. 현재 날짜를 반환한다. 
2. 현재 날짜를 특정 포멧으로 반환한다. 

어느쪽에 더 무게가 실려있을까요? 포맷터가 사용되는것을 보니 포맷팅에 무게가 더 실린 것 같은데 그게 더 잘 들어날 수 있는 네이밍을 가져가는게 좋을 것 같아요. 이를 사용하는 동료가 변수명만 보고 어떤 용도로 사용될 수 있는지 쉽게 알 수 있도록 하는게 좋을 것 같네요.

2022-08-18 14:56 UTC, protocorn93 commented on Diary/JSON/JSONManager.swift
> +    func checkFileAndDecode<T: Decodable>(dataType: T.Type, _ fileName: String) -> Result<T, JSONError> {
제네릭을 사용해서 구현한 점 훌륭해요! 👍 다만 궁금한 점은 `throws`를 하지 않고 `Result` 타입을 반환한 이유가 궁금해요!

2022-08-18 14:56 UTC, protocorn93 commented on Diary/JSON/JSONManager.swift
> +        jsonDecoder.keyDecodingStrategy = .convertFromSnakeCase
`JSONDecoder`를 변수로 받도록 하는건 어떨까요? 외부에서 `JSONDecoder`를 생성하고 원하는 strategy를 지정해서 넣어주는게 좀 더 유연하게 사용될 수 있을 것 같아서요

2022-08-18 14:56 UTC, protocorn93 commented on Diary/Model/DiaryContent.swift
> +    let id = UUID()
`UUID`를 통해 식별할 때 주의해야할 점은 서버에서는 같은 컨텐츠라고 내려주어도, 이렇게 클라이언트에서 생성되는 `UUID`가 다르면 다른 데이터소스로 인지할 수 있어요. 최대한 식별값은 고유해야하고, 왠만해선 변하지 않는 값이 되면 좋아요. 그래서 최대한 서버에서 내려주는 식별값을 사용하곤 해요. 하지만 이렇게 사용해도 무방한 경우도 있기에, 잘 선택해서 사용해보시면 될 것 같아요.

2022-08-18 14:56 UTC, protocorn93 commented on Diary/View/DiaryContent/DiaryContentViewController.swift
> +    private var diaryViewModel: DiaryViewModel?
생성 시점에 외부에서 주입해주면 옵셔널도 제거될 수 있지 않을까요? (+ `private let` ) setupDefault 메서드를 보면 뷰모델을 생성해주고 있는데, 뷰모델은 외부에서 생성해서 의존성으로 주입해주는게 유연한 구조로 가는 바람직한 방향이라고 생각해요

2022-08-18 14:56 UTC, protocorn93 commented on Diary/View/DiaryContent/DiaryContentViewController.swift
> +        self.view.addSubview(diaryDescriptionTextView)
개인적으론 `diaryDescriptionTextView`를 `addSubview` 하는 코드는 아래 `configureTextView`에 함께 있는게 보다 응집도 높은 코드라고 생각해요. 이후 코드들도 모두 동일하게 적용되는 코멘트에요.

2022-08-18 14:56 UTC, protocorn93 commented on Diary/View/DiaryList/DiaryListViewController.swift
> +    private var dataSource: UITableViewDiffableDataSource<Section, DiaryContent>?
보통 데이터소스 타입은 뷰컨트롤러 상단에 typealias 해서 사용하곤해요.

`typealias DataSource = UITableViewDiffableDataSource<Section, DiaryContent>`

2022-08-18 14:56 UTC, protocorn93 commented on Diary/View/DiaryList/DiaryListViewController.swift
> +    private var dataSource: UITableViewDiffableDataSource<Section, DiaryContent>?
또한 보통 dataSource 선언 코드는 아래와 같이 작성하곤 해요. (제가 속한 팀에서도 그렇구요!)

```swift 
private lazy var dataSource = self.makeDataSource()

...

private func makeDataSource() -> DataSoruce { 
  return ... 
}
```

2022-08-18 14:56 UTC, protocorn93 commented on Diary/View/DiaryList/DiaryListViewController.swift
> +    private var diaryListViewModel: DiaryViewModel?
여기도 마찬가지로 생성시점에 외부에서 뷰모델을 주입해주는게 바람직해요.

2022-08-18 14:56 UTC, protocorn93 commented on Diary/View/DiaryList/DiaryListViewController.swift
> +    private var diaryListViewModel: DiaryViewModel?
사실 현재 구조는 MVVM이라고 할 수는 없다고 생각해요. `-ViewModel`이라는 이름만 사용하고 있고, 전혀 뷰모델스럽지 않거든요. 일반적인 MVVM 구조에선 뷰컨트롤러는 어떤 상태값도 알고있지 않아요. 최대한 멍청하게 만드는게 핵심이거든요! 

비즈니스 로직은 전부 뷰모델이 직/간접적으로 처리합니다. 뷰컨트롤러는 단순히 요청(뷰모델 메서드 호출)을 하고 응답(데이터 바인딩 or 클로저 or delegate 등을 통해)을 받을 뿐이죠

제가 직/간접적이라고 말한 이유는 현재 `DiaryListVIewController`를 예로 들면 뷰모델이 `JSONManager`를 갖게 되는거죠. 뷰컨트롤러가 뷰모델에게 요청을 하면 뷰모델은 다시 `JSONManager`에게 요청을 하고 `JSONManager`가 준 응답을 다시 뷰컨트롤러에게 전달해주는 그런 처리를 간접적이라고 표현한거에요. 직접은 말그대로 뷰모델 안에 비즈니스 로직 코드가 존재하겠죠? 

ViewController ↔️ ViewModel ( ↔️ Business logic object )

2022-08-18 14:56 UTC, protocorn93 commented on Diary/View/DiaryList/DiaryListViewController.swift
> +        }
> 뷰컨트롤러가 뷰모델에게 요청을 하면 뷰모델은 다시 JSONManager에게 요청을 하고 JSONManager가 준 응답을 다시 뷰컨트롤러에게 전달해주는 그런 처리를 간접적이라고 표현한거에요. 직접은 말그대로 뷰모델 안에 비즈니스 로직 코드가 존재하겠죠?

이게 위에서 언급한 부분에 해당하겠네요

2022-08-18 14:56 UTC, protocorn93 commented on Diary/View/DiaryList/DiaryListViewController.swift
> +        var snapshot = NSDiffableDataSourceSnapshot<Section, DiaryContent>()
저는 보통 DiffableDataSource를 사용할 때 위에서 언급했던 것 처럼 typealias를 사용해요. 

```swift
typealias DataSource = UITableViewDiffableDataSource<Section, DiaryContent>
typealias Snapsnot = NSDiffableDataSourceSnapshot<Section, DiaryContent>
```

2022-08-18 14:56 UTC, protocorn93 commented on Diary/View/DiaryList/DiaryListViewController.swift
> +        self.navigationController?.pushViewController(diaryContentViewController, animated: true)
여기도 마찬가지로 뷰모델에게 특정 인덱스의 데이터를 요청할 수 있겠죠? 

```swift 
let diaryContent = self.viewModel.diaryContent(at: indexPath)
```

2022-08-18 14:56 UTC, protocorn93 commented on Diary/View/DiaryList/DiaryTableViewCell.swift
> +final class DiaryTableViewCell: UITableViewCell {
셀이 재사용되는 것을 고려한 코드가 들어가야 하지 않을까요~?

2022-08-18 14:56 UTC, protocorn93 commented on Diary/View/DiaryList/DiaryTableViewCell.swift
> +    }
이를 구현한 것은 이후에 스토리보드로 개발될 수 있다는 여지를 열어두신걸까요?

2022-08-18 14:56 UTC, protocorn93 commented on Diary/ViewModel/DiaryViewModel.swift
> +}
두분이 생각한 뷰모델은  어떤 역할인가요? 단순히 주어진 데이터를 화면에 보여주는 용도로 변환만 해주는 역할인가요?

2022-08-18 14:56 UTC, protocorn93 commented on DiaryTests/DiaryTests.swift
> +        }
전체적으로 given, when, then 구조로 테스트 코드를 작성하는 습관을 가져가시면 좋을 것 같아요. 어떤 상황에 어떤 것을 테스트하고자 하는바가 코드로 좀 더 명확해지거든요.  제가 속한 팀에선 주석으로 이에 대한 구분은 모두 하고 있어요. 

```swift 
func test_어떤_테스트_코드() { 
  // given
  ... 

  // when 
  ... 

  // then 
  ... 
}
```

2022-08-18 14:56 UTC, protocorn93 commented on Podfile
> +pod 'SwiftLint'
들여쓰기가 누락된 것 같아요.

2022-08-18 14:56 UTC, protocorn93 commented on Diary/Extensions/Date+Extensions.swift
> +    }
그리고 보통 이런 변수는 static하게 많이 사용해요 

```swift 
Date.currentFormattedDate // 네이밍은 가제
```

2022-08-19 00:44 UTC, derrickkim0109 commented on Diary/Extensions/Date+Extensions.swift
> +    }
`2.현재 날짜를 특정 포멧으로 반환한다`에 비중을 두고 만들었습니다. 
해당내용은 타입 프로퍼티로 수정하였습니다.

2022-08-19 00:56 UTC, derrickkim0109 commented on Diary/JSON/JSONManager.swift
> +    func checkFileAndDecode<T: Decodable>(dataType: T.Type, _ fileName: String) -> Result<T, JSONError> {
`Result` 타입을 사용하면 switch를 사용하여 .success / .failure 케이스로 분리할 수 있는 장점이 있고 Error의 타입을 특정할 수 있기 때문에 컴파일 시점에 알 수 있게 만들 수 있습니다.

2022-08-19 01:11 UTC, Hugh-github commented on Diary/Model/DiaryContent.swift
> +    let id = UUID()
서버에서 받아오는 값의 타입이 정해져 있는데 지금 같은 경우에는 DiaryContent를 DiffableDataSource의 Data로 사용하기 위해서 UUID를 사용했습니다. 이런 경우에는 서버에서 보내주는 데이터와 매핑할 타입과 Mock 데이터와 매핑할 타입을 분리해 주는게 좋을지 궁금합니다.

2022-08-19 01:13 UTC, Hugh-github commented on Diary/JSON/JSONManager.swift
> +        jsonDecoder.keyDecodingStrategy = .convertFromSnakeCase
JSONDecoder를 외부에서 변수로 생성해 주었습니다.

2022-08-19 01:24 UTC, Hugh-github commented on Diary/View/DiaryList/DiaryListViewController.swift
> +        var snapshot = NSDiffableDataSourceSnapshot<Section, DiaryContent>()
typealias를 이용해 수정했습니다!!

2022-08-19 01:32 UTC, derrickkim0109 commented on Diary/View/DiaryList/DiaryTableViewCell.swift
> +    }
아닙니다. fatalError 작성된 부분을 피하기 위해 작성하였습니다. 스토리보드로 작성하지 않는다는 표현식 `@available(*, unavailable)`을 작성하였습니다.

2022-08-19 04:10 UTC, Hugh-github commented on Diary/View/DiaryContent/DiaryContentViewController.swift
> +    private var diaryViewModel: DiaryViewModel?
수정했습니다!!

2022-08-19 04:10 UTC, Hugh-github commented on Diary/View/DiaryContent/DiaryContentViewController.swift
> +        self.view.addSubview(diaryDescriptionTextView)
수정했습니다!!

2022-08-19 04:10 UTC, Hugh-github commented on Diary/View/DiaryList/DiaryListViewController.swift
> +    private var dataSource: UITableViewDiffableDataSource<Section, DiaryContent>?
수정했습니다!!

2022-08-19 04:12 UTC, Hugh-github commented on Diary/View/DiaryList/DiaryListViewController.swift
> +    private var diaryListViewModel: DiaryViewModel?
저희가 아직 MVVM에 대한 이해가 부족한 것 같아 추가적으로 공부를 진행하고 코드에 적용해보겠습니다.

2022-08-19 04:30 UTC, Hugh-github commented on Diary/View/DiaryList/DiaryListViewController.swift
> +        }
DiaryViewModel에서 직접 JSONManager에 대한 로직을 처리하도록 수정했습니다!!

2022-08-19 04:31 UTC, Hugh-github commented on Diary/ViewModel/DiaryViewModel.swift
> +}
현재는 그렇습니다. 저희가 MVVM에 대해 더 공부하면서 코드를 추가할 예정입니다.

2022-08-20 00:48 UTC, protocorn93 commented on Diary/Model/DiaryContent.swift
> +    let id = UUID()
서버에서 내려오는 고유값으로 식별해주는게 좋긴해요! 이 부분에 대해서는 유의해서 다음 스탭 진행해보시면 좋을 것 같아요!

2022-08-21 08:00 UTC, merged