일기장 [STEP1] Kiwi, Brad
yagom-academy/ios-diary pull request #38
Opened 2022-08-18 05:39 UTC by kiwi1023

안녕하십니까~! @ehgud0670
STEP1 PR보냅니다 잘부탁드립니다ㅎㅎ 
더운 여름에도 화이팅 하시고
오늘도 좋은 하루되시길 바라겠습니다~

## 🗒 기능설명 
- 작성한 일기장의 목록을 보여주는 Table View 구현
- UITextView를 활용하여 일기장 작성기능 구현
- Json Parsing을 통한 Cell과의 Data 연동
- Notification Center를 활용하여 키보드가 작성중인 화면을 가리지 않도록 기능 구현

## 🚀 TroubleShooting
    
### 🚀 STEP 1

#### T1. 키보드 레이아웃 문제

`UITextView`에 많은 내용이 있을 때 키보드를 사용하게 되면 `UITextView` 내용을 가리는 문제가 발생되었습니다. 해당 문제는 `NotificationCenter` 활용해서 `UITextView` 오토레이아웃 `Bottom`에 키보드 높이에 대한 제약(AutoLayout)을 설정해서 해결했습니다. 하지만 적용 후 다시 테스트 해보니 내용에 대한 `UITextView` 크기는 적용이 되었지만 키보드가 내려갈 시 `UITextView`가 원래 크기로 돌아가지 않았습니다.
해당 문제에 대해서는 `NotificationCenter`에서 `UIResponder.keyboardWillShowNotification`만 사용했었는데 추가적으로 `UIResponder.keyboardWillHideNotification`을 사용해서 해결할 수 있었습니다.

|||    
|:---:|:---:|
|<image src = "https://user-images.githubusercontent.com/45350356/185300529-7dcbab92-6590-478c-b738-ed6fb90837e7.gif" width="300" height="500">| <image src = "https://user-images.githubusercontent.com/45350356/185299935-59383093-8510-4b6d-bf79-206faef6340a.gif" width="300" height="500">
|적용 전|적용 후| 

## 궁금한점🤔

- 이번 프로젝트 요구 사항에 SwiftLint를 사용한 코드 스타일의 일관성 유지가 있었는데, 현업에서는 코드 컨벤션의 일관성을 유지하기 위해 어떠한 방법을 사용하고 계신지 궁금합니다~!

2022-08-20 18:33 UTC, ehgud0670 commented
## 궁금한 점 

회사에서도 SwiftLint를 사용하고 있고, 필요없는 부분은 disable로 없애며 룰을 만들고 있습니다.
또 기본적으로 [API Design Guideline](https://www.swift.org/documentation/api-design-guidelines/) 을 참고하며 스타일 가이드 라인을 지키고 있습니다.

2022-08-20 19:18 UTC, ehgud0670 reviewed
고생하셨습니다 :)
피드백 확인 부탁드릴게요.

2022-08-20 19:18 UTC, ehgud0670 commented on Diary/View/MainTableViewCell.swift
> +    func fetchJsonData(data: SampleJson) {
모델 네이밍이 SampleJson이라고 하니 JSON 관련 객체처럼 보이지 모델 객체처럼 보이지 않네요.
예를 들어 Content 라는 식으로 네이밍을 바꿔도 될 것 같아요.

2022-08-20 19:18 UTC, ehgud0670 commented on Diary/View/MainTableViewCell.swift
> +        let date = Date(timeIntervalSince1970: TimeInterval(data.createdAt)).formatted("yyyy년 MM월 dd일")
이런 처리는 모델의 메소드나 연산프로퍼티로 이동시키는 게 나을 것 같아요. 이 모델값을 사용할 뷰에서도 간편하게 해당 모델의 메소드를 재사용할 수 있기 때문입니다 :)

2022-08-20 19:18 UTC, ehgud0670 commented on Diary/View/DiaryView.swift
> +class DiaryView: UIView {
많이 들으셨겠지만 final 키워드를 모두 일관성있게 적어주시면 더 좋을 것 같아요 :)

2022-08-20 19:18 UTC, ehgud0670 commented on Diary/Controller/MainViewController.swift
> +    private let sampleDiary: [SampleJson]? = JSONDecoder.decodedJson(jsonName: "sample")
1) sampleDiary 라는 객체를 만들고 안에 배열을 두면 나중에 모델과 관련된 메소드들도 만들 수 있고 좀 더 객체지향적으로 구현할 수 있습니다.
2) JSONDecoder를 통해 바로 모델을 생성하는 형식이 아니라 모델데이터를 jsonDecoder를 통해 생성하고 SampleDiary라는 모델객체에서 전달하는 형식으로 코드를 짜는 건 어떨까요? 이런 식으로 만들면 나중에 서버 데이터를 받는 입장이 될 때도 유연하게 대처가 가능합니다. 
* 로컬 json 파일로 모델값을 만든다 -> SampleDiary가 해당 모델값을 전달받는다 -> 뷰컨트롤러는 SampleDiary의 모델 데이털 변화를 감지하고 뷰를 업데이트 한다. 
* 서버로부터 데이터를 받아 모델값을 만든다 -> SampleDiary가 해당 모델값을 전달받는다 -> 뷰컨트롤러는 SampleDiary의 모델 데이털 변화를 감지하고 뷰를 업데이트 한다. 
3) 2번이 되려면 SampleDiary의 모델 변화를 감지하기 위해 SampleDiary는 노티피케이션센터을 이용해 노티를 쏴야하고 MainVC가 노티를 등록해 해당 노티를 받아 뷰를 업데이팅해야 합니다(기본적으로 모델의 변화는 NotificationCenter, Rx, Combine등을 사용합니다.

2022-08-20 19:18 UTC, ehgud0670 commented on Diary/View/MainTableViewCell.swift
> +    func fetchJsonData(data: SampleJson) {
fetch 가 아니라 view를 꾸미는 것이므로 `configure(with content: Content)` (예를 들어서요!)라고 네이밍하는 건 어떨까요~?

2022-08-22 05:49 UTC, bradheo65 commented on Diary/Controller/DiaryViewController.swift
> +    private func setNavigationbar() {
넵! `setNavigationbar`를 `setupNavigationbar`로 변경했습니다.

2022-08-22 06:05 UTC, bradheo65 commented on Diary/View/DiaryView.swift
> +        self.diaryTextViewBottomConstraint = diaryTextView.bottomAnchor.constraint(equalTo: safeAreaLayoutGuide.bottomAnchor, constant: -keyboardHeight)
한번 반영해 보았습니다!

2022-08-22 06:09 UTC, bradheo65 commented on Diary/Controller/DiaryViewController.swift
> +    @objc private func keyBoardShow(notification: NSNotification) {
넵 objc 메소드가 먼저 작성해 주는 습관이 있어 작성했습니다.. 제이슨의 의견 반영했습니다!

2022-08-22 06:11 UTC, bradheo65 commented on Diary/View/DiaryView.swift
> +    private lazy var diaryTextViewBottomConstraint = diaryTextView.bottomAnchor.constraint(
lazy 키워드에 대해 알아보겠습니다!

2022-08-22 06:26 UTC, bradheo65 commented on Diary/View/MainTableViewCell.swift
> +    static var identifier: String {
참고 자료 참고해서 작업해 보았습니다. 제이슨이 의도하신 방향과 맞을 까요??

[7cfa90d](https://github.com/yagom-academy/ios-diary/pull/38/commits/7cfa90d48517cbb70306d421f8effa421b997c7d)

2022-08-22 06:30 UTC, kiwi1023 commented on Diary/View/MainTableViewCell.swift
> +    func fetchJsonData(data: SampleJson) {
`configureContent`로 수정하였습니다!

2022-08-22 06:31 UTC, kiwi1023 commented on Diary/View/DiaryView.swift
> +class DiaryView: UIView {
수정하였습니다!

2022-08-22 06:31 UTC, kiwi1023 commented on Diary/View/MainTableViewCell.swift
> +    func fetchJsonData(data: SampleJson) {
`SampleDiaryContent`로 변경하였습니다!

2022-08-22 13:09 UTC, bradheo65 commented on Diary/Controller/DiaryViewController.swift
> +        self.registerForKeyboardNotification()
키보드 노티 등록하는 부분을 viewDidAppear로 변경해주었습니다.

[4020346](https://github.com/yagom-academy/ios-diary/pull/38/commits/40203464d501e680b2d02310fb9e169044544b46)

2022-08-23 06:58 UTC, bradheo65 commented on Diary/Controller/MainViewController.swift
> +    private let sampleDiary: [SampleJson]? = JSONDecoder.decodedJson(jsonName: "sample")
Notification Center를 사용해서 모델 업데이트 시 발생되는 기능 구현해보았습니다!!
제이슨이 의도하신 방향이 맞는지 궁금합니다!

추가적으로 질문드리고 싶은 점이 있는데, 모델 변화에 대한 Noti를 해제시켜줄때 해당 모델 안에서 deinit을 사용해서 Noti를 해제시켜주었는데 적절하게 해주었는지 궁금합니다.

[44a68d4](https://github.com/yagom-academy/ios-diary/pull/38/commits/44a68d422e7834604866a2b500faf5275f0529f2)

2022-08-23 09:27 UTC, ehgud0670 requested changes
고생하셨습니다 :) 
한번만 더 반영부탁드려요 👍

2022-08-23 09:27 UTC, ehgud0670 commented on Diary/Model/DiaryManger.swift
> +    func loadData() {
데이터를 로드하는 것은 모델이 다른 객체가 따로 하는 것이 좋습니다 :)
DiaryManager 가 loadData라는 메소드가 있어도 되는데 호출이 될때 안에 다른 객체가 결국 역할을 하면 역할이 분리된다는 점에서 더 좋을 듯 해요. 

> example 

```swift
func loadData() {
  self.dbManager.loadData() { response in
    self. sampleDiaryContent = response
  }
}
```

그리고 해당 객체는 DiaryManager가 생성될때 의존성 주입하면 더욱 좋습니다.

2022-08-23 09:27 UTC, ehgud0670 commented on Diary/Model/DiaryManger.swift
> +class DiaryManger {
DiaryManager

2022-08-23 09:27 UTC, ehgud0670 commented on Diary/Model/DiaryManger.swift
> +    deinit {
애초에 옵저버를 등록하지 않았기 때문에 remove 안해줘도 될 것 같네요 🧐
해당 객체는 노티만 보낼 뿐입니다.

2022-08-23 09:27 UTC, ehgud0670 commented on Diary/Model/Extension/Notification.Name + Extension.swift
> +    static let mockdataUpload = Notification.Name("mockdataUpload")
1) `diaryModelDataDidChanged` 라는 네이밍(예를 들어서요)이 더 유연할 듯 합니다. 지금은 가데이터를 사용해서 mockDataUpload 라는 노티를 사용하다가 실데이터를 사용할 때 실데이터를 쓴다는 것을 알리는 노티를 사용하기 보다는 애초에 노티는 단지 모델값이 변했다는 것만 알려주는 구조가 나중에 코드도 변경할 필요가 없어 더 유연할 듯 합니다 :)
2) 제가 말씀드린대로 노티 네이밍을 바꾼다면 해당 노티는 지금 파일 보다는 DiaryManager 구조체에 위치하는 게 더 자연스러울 듯 합니다. 왜냐하면 해당 노티는 이제 diaryManager의 모델값이 바뀔 때만 사용되기 때문입니다.

2022-08-23 09:27 UTC, ehgud0670 commented on Diary/Model/DiaryManger.swift
> +    func loadData() {
의존성 주입할때는 물론 프로토콜을 이용하시는게 더 좋습니다. 

> example

```swift
protocol DBMangerable {
   func loadData(//...) 
}

final class DBManager: DBMangerable {
   func loadData(//...)  {

   }
}

final class StubDBManager: DBMangerable {
   func loadData(//...)  {

   }
}
```

2022-08-24 05:37 UTC, bradheo65 commented on Diary/Model/DiaryManger.swift
> +    func loadData() {
제이슨 의견 반영해서 수정해 보았습니다!!

[3a5251a](https://github.com/yagom-academy/ios-diary/pull/38/commits/3a5251ac60bd9f38ee3b53a6e3e6b01468ee982c)

2022-08-24 05:37 UTC, bradheo65 commented on Diary/Model/DiaryManger.swift
> +class DiaryManger {
오타 수정했습니다!

2022-08-24 05:38 UTC, kiwi1023 commented on Diary/Model/Extension/Notification.Name + Extension.swift
> +    static let mockdataUpload = Notification.Name("mockdataUpload")
해당 리뷰 이해 하였고 `diaryModelDataDidChanged`로 수정하였습니다 ㅎㅎ

2022-08-24 05:38 UTC, bradheo65 commented on Diary/Model/DiaryManger.swift
> +    deinit {
MainViewController이라 따로 remove 해주지 않았습니다!!

2022-08-24 07:55 UTC, ehgud0670 approved these changes
고생하셨습니다 👍

2022-08-24 07:55 UTC, merged