일기장 [STEP1] 민쏜, 보리사랑
yagom-academy/ios-diary pull request #41
Opened 2022-08-19 01:34 UTC by minsson

@ryan-son 

안녕하세요, 라이언! ☺️
민쏜과 보리사랑입니다!

일기장 STEP 1 PR 보냅니다!
잘 부탁드립니다! 😁

감사합니다!

---

# 1. 폴더 구조 🗂
```
.
└── Diary/
    ├── info.plist
    └── Resources/
        ├── Assets.xcassets
        ├── Diary.xcdatamodeld
        └── Sources/
            ├── AppDelegate.swift
            ├── SceneDelegate.swift
            └── Common/
                ├── Extensions/
                │   ├── TimeInterval+Extensions.swift
                │   └── CALayer+Extensions.swift
                ├── Models/
                │   ├── DiaryItems.swift
                │   └── DataManager.swift
                ├── Views/
                │   └── DiaryListCollectionViewCell.swift
                └── Controllers/
                    ├── DiaryListViewController.swift
                    └── DiaryDetailViewController.swift
```

# 2. 구현 내용 🛠
| 폴더                 | 파일명(타입)                | 핵심 구현 내용                                          |
|:------------------: |:------------------------:|:---------------------------------------------------:|
| Sources             | SceneDelegate            | UIWindow를 이용하여 스토리보드 없이 화면 구현                |
| Common - Extensions | TimeInterval+Extensions  | 사용자의 Locale에 맞추어 작성일자를 표시해주는 메서드 구현       |
|          -          | CALayer+Extensions       | 일기 ListView에서 각 Cell의 Border를 커스터마이징 (간격 조절) |
| Models              | DiaryItem                | 일기 JSON 데이터를 매핑하기 위한 모델                       |
|          -          | DataManager              | 모델 데이터 관리 및 디코딩                                |
| Views               | DiaryTableViewCell       | 일기 리스트뷰에 쓰일 컬렉션뷰 셀 구현                        |
| Controllers         | DiaryListViewController  | 일기 리스트뷰를 구성하는 뷰컨트롤러                          |
|          -          | DiaryDetailViewController| 하나의 일기를 작성/수정/조회하는 뷰를 구성하는 뷰컨트롤러         |

# 3. 기능설명 📝
- 가로/세로 모드에 대응하도록 `AutoLayout`적용
- 라이트 모드/다크모드에 대응하도록 `System Background`의 `Color` 설정
- 사용자의 `Locale`에 맞추어 작성일자를 표시
- `Json` 데이터를 디코딩 하는 `Parse` 메서드와 샘플 데이터를 갖는 `DataManager` 타입 구현

## 3.1 일기장 목록 화면 구현
- 제공된 `SampleDataset`을 기반으로 `Hashable`한 `DiaryItem` 데이터 타입 구현
- `DiffableDataSource`와 `CompositionalLayout`을 활용하여 `List` 스타일의 컬렉션 뷰 구현
- `Cell`을 탭했을 경우와, `RightBarButton`을 탭할 경우 두가지에 따라 `DiaryItem`을 적절히 주입하도록 Push해주는 메서드 구현

## 3.2 일기 상세 화면 구현
- `NavigationItem`의 `title`이 작성날짜로 보이도록 구현
- textView를 활용하여 일기의 `title`과 `body`를 작성/수정
- 일기장 화면 하단부의 텍스트를 편집할 경우에도 키보드가 커서를 가리지 않도록 구현
- 키보드 상단을 쓸어내릴시 자연스럽게 키보드가 `dismiss` 되도록 구현

# 4. 고민한 점 🤔

## 4.1 키보드가 텍스트를 가리는 문제
일기 작성/수정/조회 화면에서 화면 하단 쪽에 위치한 텍스트를 탭할 경우 키보드가 올라오면서 커서가 가려지는 문제가 있었습니다. 구글링 결과 이를 해결하기 위한 여러가지 방법이 있었습니다. 그 중 가장 간단하다고 생각한 방법이 `UIResponder.KeyboardWillShowNotification`을 추가 후, 감지되면 기기의 텍스트 뷰의 `contentInset.bottom`을 키보드 높이만큼 할당하는 것이었습니다. 라이언은 어떻게 생각하시는지 궁금합니다.

## 4.2 키보드를 dismiss하는 방법
작성할 내용을 다 작성하고 나면 키보드가 없어져야 하는데 없앨 방법이 없었습니다.
처음에는 `UIPanGestureRecognizer`를 활용해, 키보드를 쓸어내리면 키보드를 `dismiss`하려고 했습니다.
그런데 사용중인 앱 중 하나에서 본문을 쓸어내리면서 키보드까지 쓸어내리면 키보드가 너무나 자연스러운 애니메이션 효과와 함께 내려가는 것을 볼 수 있었고, 대부분의 앱에서 그런 경험을 했던 것이 떠올랐습니다. 

그 후 검색 도중 `textView.keyboardDismissMode = .interactive`를 볼 수 있었고, 해당 API를 활용하니 문제가 해결되었습니다.

## 4.3 작성일자 표시 형식 지정
사용자의 Locale에 따라 작성일자 표시 형식을 지정하고자 했습니다.
`NSLocale.autoupdatingCurrent`을 이용하여 아래와 같이 코드를 작성했습니다.
```swift=
    func localizedFormat() -> String {
        let formattedDate = Date(timeIntervalSince1970: self)

        let dateFormatter: DateFormatter = {
            let dateFormatter = DateFormatter()
            dateFormatter.locale = NSLocale.autoupdatingCurrent
            dateFormatter.dateStyle = .long

            return dateFormatter
        }()
        
        return dateFormatter.string(from: formattedDate)
    }
```

시뮬레이터로 빌드시 한국어로 잘 표시되어 정상 작동한다고 생각했으나, 아이폰 기기를 연결하여 빌드시 언어 및 지역 설정과는 관계 없이 영어로 표시되는 것을 확인할 수 있었습니다. 이 부분을 해결하지 못해 혹시 어떤 해결책이 있는지 질문 드리고 싶습니다.

## 4.4 컬렉션 뷰
### 4.4.1 AutoResizingMask와 Constraints
`DiffableDataSource`와 `CompositionalLayout`을 활용하여 콜렉션뷰를 구현하면서 애플의 `ModernCollectionView` 예제를 참고해보았습니다.

애플의 공식 예제 코드에서는 콜렉션뷰의 레이아웃을 다음과 같이 지정하고 있습니다.

```swift 
collectionView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
```

저희는 아래와 같이 직접 `collectionView의` `Constraint`를 지정하는 방향으로 레이아웃을 잡아 주었는데 공식 예제에서 `AutoResizingMask`를 사용하는 이유가 궁금했습니다.

```swift 
NSLayoutConstraint.activate([
    diaryCollectionView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
    diaryCollectionView.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor),
    diaryCollectionView.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor),
    diaryCollectionView.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor)
])
```
`AutoLayout`을 잡기 위해 기존에 `AutoResizingMask`가 존재했으나, 이를 개발자가 더욱 상세하고 명료하게 설정할 수 있도록 `Constraint` 또한 사용할 수 있게된 것으로 알고 있습니다.
그런 의미에서 **상하 좌우를 UIScreen에 맞춰주는 작업만 할 것이기 떄문에 코드를 간결하게 사용하기 위해서 AutoResizingMask를 사용한 것 같다**는 생각이 들었는데, 라이언은 어떻게 생각하시나요?

### 4.4.2 CollectionView Initializer
위와 비슷하게 애플의 `ModernCollectionView` 예제코드를 보니 다음과 같이 콜렉션뷰를 인스턴스화 하고있었습니다.
```swift
collectionView = UICollectionView(frame: view.bounds, collectionViewLayout: createLayout())
```

`UIScreen`의 크기에 맞춰주기 때문에 전달인자인 `frame`부분에 `view.frame`이 들어가도 동일하게 동작할 것 같은데, 코드를 읽는 차원에서 `frame`을 넣는 부분에 `bounds`를 넣는게 어떤 이유인지 궁금했습니다. 라이언은 어떻게 생각하시나요?

### 4.4.3 DiffableDataSource의 CellProvider 클로저 수행 시점
저희는 현재 DiffableDataSource를 다음과 같이 인스턴스화 하여 전역 프로퍼티에 주입하고 있습니다.
```swift
self.diaryListDiffableDataSource = UICollectionViewDiffableDataSource<Section,DiaryItem> 
(
    collectionView: self.diaryCollectionView,
    cellProvider: 
    { collectionView, indexPath, itemIdentifier in
        guard let diaryCell = collectionView.dequeueReusableCell(
                    withReuseIdentifier: "DiaryListCell",
                    for: indexPath) as? DiaryListCollectionViewCell else {
        return UICollectionViewCell()
    }
    diaryCell.setupCellData(diary: itemIdentifier)
    return diaryCell
})
```
`DiffableDataSource`의 사용이 익숙치 않아서 LLDB를 사용하여 동작하는 방식을 확인해보던 중, `CellProvider`에 주입해준 클로저가 `viewWillAppear`와 `viewDidAppear` 메서드 사이에 사용되는것을 확인했습니다. 다만 저희는 뷰가 drawing 되는 시점에서는 내부 데이터가 정해져 있어야 한다고 생각해서 Snapshot을 Apply 하는 과정에서 셀을 정의하는 클로저가 실행 될 것이라고 생각했었습니다.

이렇게 동작한다면 `viewDidload`에서 데이터를 가져와 `UILabel`의 Text를 변경하거나 `UIImageView`의 이미지를 지정하는 코드 등, 저희가 UIComponent들에 주입한 데이터들은 `viewWillAppear`가 호출되고 Appear되는 시점에서 동작한다고 이해해도 괜찮을까요?

2022-08-21 19:08 UTC, ryan-son requested changes
보리사랑, 민쏜, STEP 1 수행하시느라 고생 많으셨습니다.

질문해주신 것부터 먼저 다루겠습니다.

> ## 4.1 키보드가 텍스트를 가리는 문제
> 일기 작성/수정/조회 화면에서 화면 하단 쪽에 위치한 텍스트를 탭할 경우 키보드가 올라오면서 커서가 가려지는 문제가 있었습니다. 구글링 결과 이를 해결하기 위한 여러가지 방법이 있었습니다. 그 중 가장 간단하다고 생각한 방법이 `UIResponder.KeyboardWillShowNotification`을 추가 후, 감지되면 기기의 텍스트 뷰의 `contentInset.bottom`을 키보드 높이만큼 할당하는 것이었습니다. 라이언은 어떻게 생각하시는지 궁금합니다.

가장 간단하고 보편적으로 이용되는 방법입니다. 현업에서도 사용할만큼 검증된 방식이니 그대로 적용하시면 됩니다.

>## 4.2 키보드를 dismiss하는 방법
>작성할 내용을 다 작성하고 나면 키보드가 없어져야 하는데 없앨 방법이 없었습니다.
처음에는 `UIPanGestureRecognizer`를 활용해, 키보드를 쓸어내리면 키보드를 `dismiss`하려고 했습니다.
>그런데 사용중인 앱 중 하나에서 본문을 쓸어내리면서 키보드까지 쓸어내리면 키보드가 너무나 자연스러운 애니메이션 효과와 함께 내려가는 것을 볼 수 있었고, 대부분의 앱에서 그런 경험을 했던 것이 떠올랐습니다. 
>그 후 검색 도중 `textView.keyboardDismissMode = .interactive`를 볼 수 있었고, 해당 API를 활용하니 문제가 해결되었습니다.

👍 궁금하신 점이 있으시거나 추가로 구현하고 싶으신 내용이 있으시면 말씀해주세요.

>## 4.3 작성일자 표시 형식 지정
>사용자의 Locale에 따라 작성일자 표시 형식을 지정하고자 했습니다.
>`NSLocale.autoupdatingCurrent`을 이용하여 아래와 같이 코드를 작성했습니다.
>시뮬레이터로 빌드시 한국어로 잘 표시되어 정상 작동한다고 생각했으나, 아이폰 기기를 연결하여 빌드시 언어 및 지역 설정과는 관계 없이 영어로 표시되는 것을 확인할 수 있었습니다. 이 부분을 해결하지 못해 혹시 어떤 해결책이 있는지 질문 드리고 싶습니다.

앱에서 지원하는 언어도 중요합니다. 사용자가 기기 설정을 한국어로 해두었더라도 앱에서 한국어를 지원하지 않으면 `Locale`은 `en_KR`과 같이 표현됩니다. 현재 앱에서 한국어를 지원하고 있는지 확인해보세요.

>## 4.4 컬렉션 뷰
>### 4.4.1 AutoResizingMask와 Constraints
>`DiffableDataSource`와 `CompositionalLayout`을 활용하여 콜렉션뷰를 구현하면서 애플의 `ModernCollectionView` 예제를 참고해보았습니다.
>애플의 공식 예제 코드에서는 콜렉션뷰의 레이아웃을 다음과 같이 지정하고 있습니다.
>저희는 아래와 같이 직접 `collectionView의` `Constraint`를 지정하는 방향으로 레이아웃을 잡아 주었는데 공식 예제에서 `AutoResizingMask`를 사용하는 이유가 궁금했습니다.
>`AutoLayout`을 잡기 위해 기존에 `AutoResizingMask`가 존재했으나, 이를 개발자가 더욱 상세하고 명료하게 설정할 수 있도록 `Constraint` 또한 사용할 수 있게된 것으로 알고 있습니다.
>그런 의미에서 **상하 좌우를 UIScreen에 맞춰주는 작업만 할 것이기 떄문에 코드를 간결하게 사용하기 위해서 AutoResizingMask를 사용한 것 같다**는 생각이 들었는데, 라이언은 어떻게 생각하시나요?

`AutoLayout` 뿐만 아니라 `AutoresizingMask`를 이용해서도 충분히 레이아웃을 잡을 수 있습니다. 특히 `Superview`에 따라 레이아웃이 유동적으로 변해야할 경우 `AutoresizingMask`도 충분히 강점을 가지고 있는데, 이런 이유로 사용했을거라 판단되네요. `AutoresizingMask`가 무엇이고 왜 사용되는지는 아래 문서를 통해 확인해보세요.

- [`autoresizingMask`- Apple Developer](https://developer.apple.com/documentation/uikit/uiview/1622559-autoresizingmask)

>### 4.4.2 CollectionView Initializer
>위와 비슷하게 애플의 `ModernCollectionView` 예제코드를 보니 다음과 같이 콜렉션뷰를 인스턴스화 하고있었습니다.
>`UIScreen`의 크기에 맞춰주기 때문에 전달인자인 `frame`부분에 `view.frame`이 들어가도 동일하게 동작할 것 같은데, 코드를 읽는 차원에서 `frame`을 넣는 부분에 `bounds`를 넣는게 어떤 이유인지 궁금했습니다. 라이언은 어떻게 생각하시나요?

여러분들이 이미 아시겠듯이, view의 frame과 bounds는 superview와의 관계를 고려한 origin을 가지느냐의 여부 이외에 중요한 차이가 있습니다. frame은 해당 뷰를 `감싸는` 영역을 표현하고,  bounds는 해당 뷰 자체의 영역을 표현합니다. 여러분들께서 말씀하신 예시에서는 view의 frame과 bounds의 영역이 동일하므로 어떤 것을 사용해도 관계없으나, view가 회전 등으로 변형된 상태라면 고유 영역을 표현하기에 bounds가 더 적합할 수 있습니다. 더 자세한 내용을 알아보시려면 아래 문서를 참고하세요.

- [`frame` - Apple Developer](https://developer.apple.com/documentation/uikit/uiview/1622621-frame)
- [`bounds` - Apple Developer](https://developer.apple.com/documentation/uikit/uiview/1622580-bounds)

>### 4.4.3 DiffableDataSource의 CellProvider 클로저 수행 시점
>저희는 현재 DiffableDataSource를 다음과 같이 인스턴스화 하여 전역 프로퍼티에 주입하고 있습니다.
>`DiffableDataSource`의 사용이 익숙치 않아서 LLDB를 사용하여 동작하는 방식을 확인해보던 중, `CellProvider`에 주입해준 클로저가 `viewWillAppear`와 `viewDidAppear` 메서드 사이에 사용되는것을 확인했습니다. 다만 저희는 뷰가 drawing 되는 시점에서는 내부 데이터가 정해져 있어야 한다고 생각해서 Snapshot을 Apply 하는 과정에서 셀을 정의하는 클로저가 실행 될 것이라고 생각했었습니다.
>이렇게 동작한다면 `viewDidload`에서 데이터를 가져와 `UILabel`의 Text를 변경하거나 `UIImageView`의 이미지를 지정하는 코드 등, 저희가 UIComponent들에 주입한 데이터들은 `viewWillAppear`가 호출되고 Appear되는 시점에서 동작한다고 이해해도 괜찮을까요?

UIKit은 오픈소스가 아니라 내부 구현을 확인하기 어렵지만, 실제로 그렇게 작동하니 그대로 이해하셔도 무방할 것으로 판단됩니다.

도움이 필요하시거나 이해가 되지 않는 피드백이 있다면 언제든지 말씀해주세요. 😄

2022-08-22 07:32 UTC, minsson commented on Diary.xcodeproj/project.pbxproj
> +				FD8ED62A28AB7A0400F631F2 /* Controllers */,
좋은 자료 감사합니다! 😲

우선 결론을 말씀드리자면, 확장에 더 유리한 구조는 `Group by Feature`라고 생각합니다!

프로젝트를 진행하면서 폴더 구조에 대한 고민을 종종 했었고, 유명한 개발자 분들의 레포에서 폴더구조를 찾아 프로젝트에 적용하기도 했습니다. 그런데 `Group by Feature` 방식은 처음 보네요! 제 검색이 부족했나봅니다 😅

`Group by Function` 방식으로 폴더를 정리하면서 늘 궁금했던 게 `나중에 프로젝트 규모가 확장되면 뭐가 어디에 있는지 어떻게 기억하고, 찾아갈 수 있을까? 매번 "Jump to Definition"을 눌러가며 찾아야 하는 건가?`였는데, 이에 대한 해답이 `Group by Feature`가 될 수 있을 것 같습니다!

이 키워드로 검색해보니, 이와 관련해 스택오버플로우에 너무 좋은 답변이 있어 인용합니다.

답변의 글을 짧게 요약하자면 아래와 같습니다!
> - 대규모 프로젝트에서는 Group by Feature 방식으로 정리한다
> - 프로젝트의 기능에 따라 팀을 나누며, 하나의 팀은 하나의 기능을 작업한다. 이 기능에 관련된 단일 폴더 혹은 파일 그룹에만 초점을 맞추면 된다
> - 이 경우 git으로 작업할 때 merge 및 rebase시 충돌 가능성이 줄어든다


### [Best practice for an Xcode project groups structure? 글의 세 번째 답변](https://stackoverflow.com/questions/39945727/best-practice-for-an-xcode-project-groups-structure) 일부 원문
#### Organizing code by feature (intent)

Organizing code by feature (intent) is the best practice for big projects and big teams. You put everything related to the feature in a folder, and while you work on that feature, you don't have to open all other folders (groups).

Cause usually teams work on a single feature, and they focus only on a single folder or group of files. They don't necessarily have to know about other features and files.

_It looks something like this:_

-   AppDelegate
-   Features
    -   Feature 1
        -   View Controllers
        -   Models
        -   Views
        -   Logic
    -   Feature 2
        -   View Controllers
        -   Models
        -   Views
        -   Logic
-   Networking
    -   Models
    -   Logic
    -   Extensions
-   Resources

Also, to mention, this practice and technique (organizing project by feature) are implemented by the biggest companies around the world. So, they divide their teams by the features of the project, each team works on a specific feature. Besides that, when you work with `git`, it reduce the chance of conflicts when merging and rebasing.

2022-08-22 07:44 UTC, yusw10 commented on Diary/Resources/Sources/Common/Extensions/TimeInterval+Extensions.swift
> +            dateFormatter.locale = NSLocale.autoupdatingCurrent
1.`Locale`과 `NSLocale`은 각각 **struct**와 **class**로 타입이 다르며(`NSLocale`을 참조 할 때 같은 인스턴스를 접근하여 동일한 시간대를 사용할 것이라고 공부하며 추측해보았습니다) `NSLocale`내부 프로퍼티에 약간의 차이가 있음을 문서에서 비교하여 확인했습니다.

저희의 현재 코드 상에서는 사용자의 현재 환경 설정에 맞춰진 지역값을 반환하는`autoupdatingCurrent`만을 사용하고 있습니다. 때문에 코멘트 남겨주셔서 곰곰히 생각해보니`Locale`로 사용하나 `NSLocale`로 사용하나 차이는 없다고 생각이 들었습니다. 

2. `current`와 `autoupdatingCurrent` 모두 사용자 기기의 지역 설정값을 가져온다는 점에서 초기값은 같습니다. 하지만 `autoupdatingCurrent`은 사용자가 어플리케이션 빌드 후 이 지역 설정값을 변경할 경우 자동으로 이 Locale값을 수정해줍니다. 

"**작성일자는 사용자의 지역 포멧에 맞게 표현해야합니다**" 라는 프로젝트 요구사항에 따라서 Locale값이 업데이트 되는 상황을 고려해 보았을 때 autoupdatingCurrent가 더 적합하다고 생각하여 사용하게 되었습니다.

2022-08-22 08:16 UTC, minsson commented on Diary/Resources/Sources/Controllers/DiaryDetailViewController.swift
> +final class DiaryDetailViewController: UIViewController {
가독성과 성능 두 가지 이유에서 사용했습니다.

### 가독성 측면
`final` 키워드는 해당 클래스는 다른 클래스에 의해 상속되지 않을 것임을 의미합니다. 
만약 이러한 경우에 해당하는데 `final` 키워드가 붙어있지 않다면 `다른 클래스에서 이 클래스를 상속하는구나. 어디에서 쓰이는 거지?`와 같은 혼동을 줄 수 있다고 생각합니다.

따라서 `final` 키워드를 붙일 수 있는 경우에는 잊지 않고 붙이려고 노력하는 편입니다.

### 성능 측면
final 키워드가 적용된 클래스의 메서드들은 성능 상 이점을 가진다는 정도로만 알고 있었습니다. 

검색해보니 Apple이 작성해놓은 좋은 글이 있었습니다.
[Advice: Use 'final' when you know the declaration does not need to be overridden](https://github.com/apple/swift/blob/main/docs/OptimizationTips.rst#id17)

정리하자면, `final` 키워드를 붙일 경우 컴파일러가 `vtable`을 거치지 않는 direct function call을 내보낼 수 있게 됩니다. 런타임에 `vtable`을 거치는 과정을 거치지 않으므로 런타임 성능이 향상됩니다... 정도로 이해했습니다!

다만 이 개념을 확실하게 이해하기 위해서는 `vtable`, `Dynamic Dispatch`, `Static Dispatch`의 개념을 확실하게 이해해야 할 것 같습니다..! 🥲

2022-08-22 08:16 UTC, minsson commented on Diary/Resources/Sources/Controllers/DiaryDetailViewController.swift
> +final class DiaryDetailViewController: UIViewController {
가독성과 성능 두 가지 이유에서 사용했습니다.

### 가독성 측면
final 키워드는 해당 클래스는 다른 클래스에 의해 상속되지 않을 것임을 의미합니다.
만약 이러한 경우에 해당하는데 final 키워드가 붙어있지 않다면 다른 클래스에서 이 클래스를 상속하는구나. 어디에서 쓰이는 거지?와 같은 혼동을 줄 수 있다고 생각합니다.

따라서 final 키워드를 붙일 수 있는 경우에는 잊지 않고 붙이려고 노력하는 편입니다.

### 성능 측면
final 키워드가 적용된 클래스의 메서드들은 성능 상 이점을 가진다는 정도로만 알고 있었습니다.

검색해보니 Apple이 작성해놓은 좋은 글이 있었습니다.
[Advice: Use 'final' when you know the declaration does not need to be overridden](https://github.com/apple/swift/blob/main/docs/OptimizationTips.rst#id17)

정리하자면, final 키워드를 붙일 경우 컴파일러가 vtable을 거치지 않는 direct function call을 내보낼 수 있게 됩니다. 런타임에 vtable을 거치는 과정을 거치지 않으므로 런타임 성능이 향상됩니다... 정도로 이해했습니다!

다만 이 개념을 확실하게 이해하기 위해서는 vtable, Dynamic Dispatch, Static Dispatch의 개념을 확실하게 이해해야 할 것 같습니다..! 🥲

2022-08-22 09:14 UTC, yusw10 commented on Diary/Resources/Views/DiaryListCollectionViewCell.swift
> +    }
1. `UIView`, `UICollectionView`는 `NSCoding` 프로토콜을 채택하고 있습니다. `NSCoding` 프로토콜에는 required로 선언된 initializer가 선언되어 있기 때문에 항상 정의 해야하는 것으로 알고 있습니다. 저희는 기존의 부모 이니셜라이저가 아닌 셀의 레이아웃등을 변경하는 로직을 수행하는 커스텀 initializer를 사용하고 있기 때문에 부모의 `NSCoding` initializer가 아닌 현재 셀에서 명시를 해주어야 하는것으로 이해했습니다. 다만 어째서 required로 명시가 되어있는지에 대해서는 아직 잘 모르겠습니다...
 
2. `NSCoder`를 파라미터로 받는 initializer는 `xib`와 같은, 즉 스토리 보드 기반으로 initializing을 할 때 사용하는 것으로 알고 있습니다. 다만 현재 코드에서는 코드 베이스로 셀을 구현 하였기에 이 initializer로는 인스턴스화 될 수 없습니다. 그래서 자동완성으로 생성되는 `fatalError`를 그대로 채택하여 사용하였습니다(에러 확인 후 디버깅을 하기 위해)

3. 저희는 스토리보드를 사용하지 않고 코드 베이스로 구현중입니다. 따라서 추후에 셀을 스토리보드 기반으로 리팩토링 하지 않는 한 호출되지 않을 것 같습니다. 

항상 무의식적으로 에러가 떠서 아무 기능없는 이니셜라이저를 구현해왔는데 코멘트 달아주셔서 처음으로 찾아봤습니다. 혹시 잘못 이해한 내용있다면 조언 부탁드립니다...!

2022-08-22 11:49 UTC, yusw10 commented on Diary/Resources/Sources/Models/DataManager.swift
> +        let jsonDecoder = JSONDecoder()
`JSONDecoder` 타입에 지정해줄 수 있는 옵션을 찾기 위해 공식문서를 확인 해보았습니다. [문서](https://developer.apple.com/documentation/foundation/jsondecoder) 
다만 `JSONDecoder().assumesTopLevelDictionary = true` 와 같이 직접적으로 속성에 접근하여 변경시켜주는 것 외에 사용할 옵션을 주입시켜줄 적절한 방법에 대해서 찾기가 어려웠습니다.

다만 디코더 자체가 아닌 디코더를 거쳐갈 데이터 자체에 옵션을 주는 방법을 찾긴 했는데 코멘트 주신 의도가 이것을 이용하도록 하는것이 맞을까요...? 저희가 라이언의 의도를 잘 이해한건지 모르겠습니다😢

```swift 
let optionableData = try? JSONSerialization.data(
    withJSONObject: temporarySampleData!.data, 
    options: [.prettyPrinted]
)
```

추가로 현재는 json타입의 샘플 데이터를 사용하기 위해 `JSONDecoder`를 사용중인데 `Core Data`로 기능을 추가하면 JSON 타입을 디코드 해주는 `parse`메서드도 삭제 될 것같습니다...!

2022-08-22 11:52 UTC, yusw10 commented on Diary/Resources/Sources/Controllers/DiaryListViewController.swift
> +    private let dataManager = DataManager()
현재는 JSON 타입의 데이터 디코딩 및 샘플 데이터를 관리해주는 타입으로 사용중에 있었습니다. 다만 말씀주신대로 여러 데이터타입이 존재한다면 모호한 네이밍이라고 생각이 들어 `DiaryDataManager`로 변경해보았습니다. 추후 `CoreData`구현을 완료한 뒤 한번 더 네이밍에 대해서 재고해보겠습니다.
[6c41dae](https://github.com/yagom-academy/ios-diary/pull/41/commits/6c41daee1b8eed17b2c0dc2fd6bb39ff4c845d64)

2022-08-22 12:04 UTC, yusw10 commented on Diary.xcodeproj/project.pbxproj
> +				FD8ED62C28AB7A3600F631F2 /* Resources */,
앗... 폴더 계층구조를 초반에 설정하고 코드를 작성했는데 그 당시 미처 확인하지 못했던것 같습니다...
Source와 Resources가 대등한 계층에 존재하도록 수정했습니다...!

[e2dad8a](https://github.com/yagom-academy/ios-diary/pull/41/commits/e2dad8a9a315ce866865423c8452a6f9b087969c)

2022-08-22 12:08 UTC, minsson commented on Diary/Resources/Sources/Controllers/DiaryDetailViewController.swift
> +private extension DiaryDetailViewController {
현재 기준으로는 `private` 메서드들만 해당 extension에 모아두었습니다.
지금까지는 보통 아래와 같이 나누었습니다.

1) `delegate`를 위한 extension
2) `private` 접근 수준의 메서드들이 모여있는 private extension
3) `internal` 접근 수준의 메서드들이 모여있는 extension

라이언이 코멘트 남겨주신 부분은 2번에 해당합니다.

다만 메서드가 위의 기준으로 나누기에는 너무 많아지면 같은 extension 안에서도 `UI`를 구성하는 메서드와 `Logic`을 구성하는 메서드의 영역을 분리하기도 했습니다. 이 경우 보통 MARK 주석을 사용하는 편입니다.

혹시 더 좋은 방법이 있을까요? 조언 부탁 드립니다..!! 🥲
정확한 기준 없이 그때그때 임기응변으로 하는 느낌이 들어, 라이언의 코멘트를 받고 이번 기회에 정립하고 싶다는 생각이 들었습니다.

2022-08-22 12:35 UTC, minsson commented on Diary/Resources/Sources/Common/Extensions/CALayer+Extensions.swift
> +                break
1. `.init`을 사용하지 않는 방향으로 통일했습니다!
2. `break` 구문의 경우 필요하지 않습니다. 코드를 작성하는 과정 중 오류가 발생하는 것을 막기 위해 작성했던 `break`들을 제거하지 않은 것 같습니다. 모두 제거해주었습니다!

2022-08-22 12:36 UTC, minsson commented on Diary/Resources/Sources/Models/DataManager.swift
> +    let temporarySampleData = NSDataAsset.init(name: "sample modify")
`.init`을 사용하지 않는 방식으로 통일했습니다.

2022-08-22 12:40 UTC, yusw10 commented on Diary/Resources/Sources/Controllers/DiaryListViewController.swift
> +    private lazy var diaryCollectionView: UICollectionView = {
lazy var와 let으로 선언하는것 두가지를 고민 했었습니다.
먼저 let으로 선언한다면 다음과 같이 구현하고자 했습니다.
```swift 
private let diaryCollectionView: UICollectionView = {
    let collectionView = UICollectionView(
        frame: .zero,
        collectionViewLayout: UICollectionViewLayout()
    )
    collectionView.translatesAutoresizingMaskIntoConstraints = false
    return collectionView
}()
```
collectionView의 레이아웃을 리턴해주는 createListLayout 메서드는 콜렉션뷰와 같은 시기에 메모리에 올라가기 때문에 let으로 collectionView를 선언할 시 클로저 내부에서 사용이 불가하다고 판단했습니다. 그리고 위의 인스턴스화 해준 UICollectionView는 다음과 같을 수 있다고 생각했습니다.
```swift
private lazy var diaryCollectionView: UICollectionView = {
    let collectionView = UICollectionView()
    collectionView.translatesAutoresizingMaskIntoConstraints = false
    return collectionView
}()
...
// viewDidload 또는 viewWill Appear 또는 레이아웃을 주입하는 메서드에서
diaryCollectionView.collectionViewLayout = createListLayout() // 주입
```

위와같이 let으로 선언하고 레이아웃 인스턴스를 메모리 load 후에 주입하는방법과, 현재처럼 collectionView를 지연 저장 프로퍼티로 생성하여 생성 클로저 내부에 바로 createListLayout() 메서드를 사용하는 방법 두가지를 고민했었습니다.

lazy 키워드를 사용하여 collectionView를 선언한 이유는 "**UICollectionView를 정의하는 시점에서 frame이나 Layout과 같은 전체적인 틀과 관련된 정보는 선언 시점에서 제공하는게 가독성 면에서 좋지 않을까**" 라고 생각했기 때문입니다. 
코드를 읽는 사람의 시점을 생각해 보았을때 frame은 다른 UI요소들과 함께 Layout을 잡는게 읽기 편할것 같았고, 내부의 요소들의 레이아웃은 이 코드를 읽는사람이 "아 자체적인 레이아웃을 사용한 콜렉션뷰겠구나" 라고 자연스럽게 읽힐 것이라고 생각했습니다.

민쏜과 코드를 작성하면서 프로퍼티를 최대한 let으로 선언하려고 신경썻으나 collectionView에서는 이러한 이유로 커스텀한 리스트레이아웃을 적용한것을 보여주고자 lazy를 사용했습니다.

라이언은 UI요소를 선언하고 사용하실 때 어떤 흐름으로 하시는지도 궁금합니다...!🤥

2022-08-22 13:03 UTC, minsson commented on Diary/Resources/Sources/SceneDelegate.swift
> -        // This delegate does not imply the connecting scene or session are new (see `application:configurationForConnectingSceneSession` instead).
` SceneDelegate`와 `AppDelegate`쪽에서도 불필요한 주석은 제거했습니다.

2022-08-22 13:05 UTC, minsson commented on Diary/Resources/Sources/Common/Extensions/TimeInterval+Extensions.swift
> +        let dateFormatter: DateFormatter = {
넵, 그럼 Step 2 진행하면서 이번 주중으로 읽어보고 저희 생각을 정리해 말씀드리겠습니다! ☺️

2022-08-22 13:05 UTC, minsson commented on Diary/Resources/Sources/Common/Extensions/TimeInterval+Extensions.swift
> +        let dateFormatter: DateFormatter = {
넵, 좋은 자료 공유 감사합니다!! 🙏
그럼 Step 2 진행하면서 이번 주중으로 읽어보고 저희 생각을 정리해 말씀드리겠습니다! ☺️

2022-08-22 13:33 UTC, yusw10 commented on Diary/Resources/Sources/Controllers/DiaryDetailViewController.swift
> +        contentTextView.text = textViewContent
넵 데이터의 생성과, 컨텐츠 세팅 작업까지 두가지 기능이 있는것 같아 분리해보았습니다. 추가로 `viewDidload` 에서 분리해준 두가지를 같이 실행시키면 추상화 레벨이 맞지 않을것 같아 이 두가지를 묶어 실행시키는 `setupContentViewData()` 를 추가해보았습니다.

[0d40036](https://github.com/yagom-academy/ios-diary/pull/41/commits/0d40036c2bc6ba776e6233d30731c195773e1f02)

2022-08-22 13:35 UTC, minsson commented on Diary/Resources/Sources/Controllers/DiaryDetailViewController.swift
> +        let keyboardFrame = sender.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue
키보드의 높이를 구하는 과정에서 잘 알지 못해 구글링 했습니다. 
많은 곳에서 `NSValue`로 캐스팅하고 있어, 그렇게 해야하는지 알고 `NSValue`로 캐스팅하니, 키보드 높이를 구하는 과정에서 아래와 같이 지저분한 코드가 생겼습니다.

```swift
let keyboardHeight: CGFloat = keyboardFrame.cgRectValue.height + 50
```

하지만 라이언 덕분에 `CGRect` 타입으로도 캐스팅 가능하다는 것을 알게 되어, 위의 코드를 아래와 같이 깔끔하게 바꿀 수 있게 되었습니다. 감사합니다!!

```swift
let keyboardHeight: CGFloat = keyboardFrame.height + 50
```

참고로 이곳의 `50`은 
참고로 키보드 높이에 딱 맞게 올리면 커서가 키보드 바로 위에 있어 답답한 인상을 주기 때문에 `50`을 더해주어 커서 밑에도 몇 줄이 보이도록 만들었습니다.

이런 매직넘버는 추후에 네임스페이스로 관리하려고 합니다.


### 그리고 한 가지 질문이 있습니다! 🙋
`sender.userInfo?[UIResponder.keyboardFrameEndUserInfoKey]`을 캐스팅하지 않고 타입을 살펴보면 `Any?` 타입으로 나옵니다. 그걸 저희가 본 자료에서는 `NSValue`로 캐스팅했고, 라이언은 `CGRect`로도 캐스팅할 수 있다고 말씀해주셨습니다.

어떤 타입으로 캐스팅하든, 이걸 어떻게 알 수 있었는지 궁금합니다. 앞으로 이렇게 잘 모르는 걸 타입캐스팅해야할 때, 어디서 이런 걸 찾아볼 수 있나요?

2022-08-22 13:45 UTC, yusw10 commented on Diary/Resources/Sources/Controllers/DiaryListViewController.swift
> +        self.diaryListDiffableDataSource?.apply(snapshot)
초기에 ViewController의 프로퍼티에 접근할 때는 `self`를 사용하지 않는것으로 정하였는데, 이부분은 구현하면서 미처 확인하지 못한것 같습니다. 사용하지 않는것으로 수정하였습니다...!😱

[65d97eb](https://github.com/yagom-academy/ios-diary/pull/41/commits/65d97ebf81d6fab7e6e40509c94c708ce069a5b6)

2022-08-22 13:54 UTC, minsson commented on Diary/Resources/Sources/SceneDelegate.swift
> +        )
[StyleShare Swift style guide](https://github.com/StyleShare/swift-style-guide)의 내용 일부를 차용해서 쓰고 있습니다. 
줄바꿈 관련, `한 줄은 최대 99자를 넘지 않아야 합니다.`라는 문장이 나옵니다.

따라서 대부분의 경우 파라미터의 개수와 상관없이 99자를 넘으면 줄바꿈하고 있습니다.

단, 아래 내용과 같이 현재 이 규칙을 지키지 않는 부분이 있어 고민입니다. 

### 경우 1
```swift
private var diaryListDiffableDataSource: UICollectionViewDiffableDataSource<Section, DiaryItem>?
```
한글자 초과하는데, 나누려고 하니 어디서 개행을 해야할지 감이 오지 않습니다.

### 경우 2
```swift
NSLayoutConstraint.activate([
    diaryCollectionView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
    diaryCollectionView.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor),
    diaryCollectionView.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor),
    diaryCollectionView.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor)
])
```
규칙에 의해 나눈다면 아래와 같이 되어 오히려 가독성이 안 좋아지는 것 같아 고민입니다.

```swift
NSLayoutConstraint.activate([
    diaryCollectionView.topAnchor.constraint(
        equalTo: view.safeAreaLayoutGuide.topAnchor
    ),
    diaryCollectionView.leadingAnchor.constraint(
        equalTo: view.safeAreaLayoutGuide.leadingAnchor
    ),
    diaryCollectionView.trailingAnchor.constraint(
        equalTo: view.safeAreaLayoutGuide.trailingAnchor
    ),
    diaryCollectionView.bottomAnchor.constraint(
        equalTo: view.safeAreaLayoutGuide.bottomAnchor
    )
])
```

### 경우 3
```swift
func configureLayout() {
    NSLayoutConstraint.activate([
        contentTextView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
        contentTextView.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor, constant: 12),
        contentTextView.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor, constant: -12),
        contentTextView.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor)
    ])
}
```

경우 2와 유사합니다.

---

### 질문이 있습니다! 🙋
라이언은 이렇게 99자라는 길이 단위로 개행하는 컨벤션에 대해 어떻게 생각하시나요?
그리고 지금 저희 코드에서 이 규칙을 지키지 않는 부분이 있는 점에 대해 조언해주실 수 있나요?

2022-08-22 14:46 UTC, minsson commented on Diary/Resources/Sources/Controllers/DiaryListViewController.swift
> +        diaryCollectionView.register(DiaryListCollectionViewCell.self, forCellWithReuseIdentifier: "DiaryListCell")
아래와 같이 네임스페이스를 만들어 제거해주었습니다.

```swift
private enum LogicNameSpace {
    static let diaryCellIdentifier = "DiaryListCell"
}
```
### 질문 있습니다! 🙋
1) 늘 네임스페이스의 네이밍이 고민인데요, 라이언은 이런 네임스페이스를 만들 때 네이밍을 어떻게 하시는지 궁금합니다.
2) 네임스페이스를 만들지 않고 `private let diaryCellIdentifier = "DiaryListCell"`과 같이 선언하는 것도 생각했습니다. 라이언은 어떤 방식이 더 낫다고 보시나요?

2022-08-22 14:54 UTC, minsson commented on Diary/Resources/Sources/Controllers/DiaryListViewController.swift
> +        fetchData()
`fetchData()`를 `fetchDiaryItemData()`로 변경해주었습니다!

2022-08-22 15:07 UTC, yusw10 commented on Diary/Resources/Sources/Controllers/DiaryListViewController.swift
> +    }
초기에 List 스타일의 CollectionViewCell을 구현할 시기에는 기본적으로 제공되는 `list(using:)` 를 사용하고자 했습니다. 다만 이렇게 구현할 경우 추후에 이 콜렉션뷰가 grid 형태로 리팩토링이 필요할시 `createListLayout()` 코드 전체를 수정해야 한다고 생각했습니다.
그래서 현재와 같이 사용할 경우 subitem등의 숫자와 셀의 오토레이아웃만을 변경하면 되기에 확장성을 고려하여 이렇게 구현해보았습니다. 
저희가 생각한대로를 생각한다면 기본 리스트 형태의 API와 커스텀 콜렉션뷰 레이아웃을 별도로 생성하는게 더 나은 방향일까요?

2022-08-22 16:04 UTC, minsson commented
라이언, 세세한 리뷰 감사합니다! ☺️

각 코드별 코멘트에 대해 보리와 함께 답변을 남겨놓았습니다! 

혹시 저희가 잘못 이해한 게 있다면, 혹은 잘 이해하고 답변한 것이라도 라이언이 덧붙여주실 말이 있다면 답변 부탁 드립니다!
코멘트가 정말 많은 도움이 됩니다! 많은 조언 부탁드립니다! 🤩 
 
또, 여러 코멘트에서 추천해주신 문서는 잘 읽고, 그래도 해결되지 않는 의문은 별도로 질문하겠습니다! 😁
감사합니다!

2022-08-23 15:28 UTC, ryan-son commented on Diary/Resources/Sources/Common/Extensions/CALayer+Extensions.swift
> +            case UIRectEdge.bottom:
이러한 표현 방식이 있다는 것을 알고 눈에 익혀두시면 필요한 경우에 적절히 사용하실 수 있으실거에요.

2022-08-23 15:42 UTC, ryan-son commented on Diary/Resources/Sources/Controllers/DiaryDetailViewController.swift
> +    }
[removeObserver(_:)](https://developer.apple.com/documentation/foundation/notificationcenter/1413994-removeobserver) 문서에 따르면 타겟 iOS가 9.0 이후 버전인 경우 옵저버를 제거해주지 않아도 된다고 기술하고 있습니다. 명시적으로 옵저버를 제거할 필요가 있는 경우 일반적으로 `deinit` 시점에 호출하는 편입니다.

2022-08-23 15:44 UTC, ryan-son commented on Diary/Resources/Sources/Controllers/DiaryDetailViewController.swift
> +        let keyboardFrame = sender.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue
그것이 딕셔너리의 단점입니다. 그래서 이런 키값을 타입캐스팅할 때 공식문서를 참고합니다.
- [keyboardFrameEndUserInfoKey - Apple Developer](https://developer.apple.com/documentation/uikit/uiresponder/1621578-keyboardframeenduserinfokey)

2022-08-23 15:51 UTC, ryan-son commented on Diary/Resources/Sources/Controllers/DiaryListViewController.swift
> +    private lazy var diaryCollectionView: UICollectionView = {
타당한 이유가 있고 의도한대로 동작한다면 어떤 방식으로 선언하셔도 괜찮습니다. 저는 개인적으로 인스턴스의 요소를 사용하기만을 위한 목적으로만 `lazy` 키워드를 사용하는 것은 지양하고, 사용 여부가 확실치 않지만 복잡한 연산이 필요한 경우 사용하자라는 생각을 가지고 있습니다.

2022-08-23 16:08 UTC, ryan-son commented on Diary/Resources/Sources/Controllers/DiaryListViewController.swift
> +        diaryCollectionView.register(DiaryListCollectionViewCell.self, forCellWithReuseIdentifier: "DiaryListCell")
첫번째 방법은 민쏜이 언급하신 것과 같이 타입 프로퍼티를 정의하여 사용할 수 있습니다. 나머지 방법이 몇 가지 있는데, 회의실에서 만나서 이야기 나누도록 해요.

2022-08-23 16:14 UTC, ryan-son commented on Diary/Resources/Sources/Models/DataManager.swift
> +        let jsonDecoder = JSONDecoder()
제가 표현이 부족했던 것 같네요. 커스텀 `JSONDecoder`를 사용하고자 하는 경우 어떻게 이용하게 해줄 수 있을까에 대한 질문이었습니다. 예를들어 어떤 경우에는 `DataManager`의 디코더가 대상의 키값을 스네이크케이스에서 카멜케이스로 변경하여 인식하도록 할 수 있도록 방법을 제시해주는 것이 더 좋을 수 있습니다.

```swift
let decoder: JSONDecoder = {
    let decoder = JSONDecoder()
    decoder.keyDecodingStrategy = .convertFromSnakeCase
    return decoder
}()

let dataManager = DataManager(decoder: decoder)
```

2022-08-23 16:28 UTC, ryan-son commented on Diary/Resources/Sources/Controllers/DiaryListViewController.swift
> +    private var diaryListDiffableDataSource: UICollectionViewDiffableDataSource<Section, DiaryItem>?
Xcode 상의 Definition에서는 명시적으로 `Sendable` 채택을 요구하고 있지는 않네요. `Sendable` 프로토콜은 Swift Concurrency과 함께 도입된 프로토콜로 concurrent 환경에서 shared mutable state의 접근을 동기화하여 data race를 방지할 수 있습니다. 따라서 Value type인 구조체의 경우 기본적으로 Sendable을 채택 가능하나, 저장 프로퍼티가 모두 Sendable을 준수하여야 채택할 수 있습니다. `Sendable` 채택이 불가능하다면 내부의 저장 프로퍼티가 `Sendable`을 준수하는지 확인해보세요. 하지만 현재는 그럴 필요는 없어보입니다.

![image](https://user-images.githubusercontent.com/69730931/186210837-2b3ba4e6-e608-4c1d-82bf-a9a02a8011f9.png)

2022-08-23 16:38 UTC, ryan-son commented on Diary/Resources/Sources/SceneDelegate.swift
> +        )
글자수를 기준으로 개행 여부를 결정할 수 있으나 저는 개인적으로 글자수에 연연하지 않고 개행 조건에 일치하는 경우 개행하고 있습니다. 글자수를 기준으로 개행하면 어떤 것은 개행하고 어떤 것은 개행하지 않아 형태가 일정하지 않게되므로 글자수 기준을 모르면 개행이 이상하다고 판단할 수 있기 때문입니다. 기준에 해당하면 무조건 개행하는 경우 글자수로 인해 고통받는 경험은 줄이실 수 있으실 것입니다.

1. 콜론 뒤 혹은 제네릭 요소를 개행할 수 있겠으나 저라면 프로젝트가 초기인만큼 제한 글자수를 조금 더 늘리는 방향으로 논의해보지 않을까 생각합니다.
2, 3. 개행 후 가독성이 좋지 않아 보일 수 있으나 보기에 익숙하느냐의 여부일 뿐이라고 생각합니다. 약속한 형태에 익숙해지시면 괜찮으실겁니다.

2022-08-23 16:44 UTC, ryan-son commented on Diary/Resources/Views/DiaryListCollectionViewCell.swift
> +    }
회의실에서 논의해보도록 합시다~!

2022-08-23 16:47 UTC, ryan-son approved these changes
정성스런 피드백 잘 읽어보았습니다. 고생 많으셨습니다. 이야기가 길어질 것 같은 내용은 가능한 날짜에 회의실에서 만나 이야기 나누어보도록 해요. 추가로 남겨둔 피드백은 읽어보시고 필요하다면 다음 스텝에서 반영해보시면 됩니다. 피드백 관련하여 궁금하신 점이 있으시면 말씀해주세요. 다음 스텝도 화이팅입니다~!

2022-08-23 16:48 UTC, merged