일기장 [STEP 2] Finnn, 수꿍
yagom-academy/ios-diary pull request #44
Opened 2022-08-24 08:04 UTC by finnn1

안녕하세요, 그린! @GREENOVER 
수꿍, Finnn입니다! ☺️
일기장 프로젝트 STEP2 PR 드립니다!
이번 스탭도 잘 부탁드립니다!! 🙇🙇‍♂️

---

## 📝 기능설명
    
### STEP 2    

**각 Cell을 터치 할 경우 해당 메모를 불러오는 기능**
    
    - `UITableViewDelegate`의 `didSelectRowAt` 메서드 사용
    - 해당 `cell`의 `indexPath`에 해당하는 `diary` 데이터 추출 
    - 네비게이션 컨트롤러를 이용하여 프로퍼티 주입
    
**메모 작성 및 수정시 자동 저장 기능 구현**
    
    - `TableView` 리스트로 이동 시
    - 키보드가 내려갈 경우
    - 앱이 `ResignActive` 상태로 넘어갈 경우

**메모 작성중 우측 상단 버튼을 터치하면 Share 및 Delete 가 가능하도록 구현**
    
    - `UIAlertController`(`ActionSheet`) 사용
    - `Share` 시, `UIActivityViewController Present`
    - `Delete` 시, `Alert` 띄우기
        - 삭제 액션 클릭 시, 이전 뷰로 이동 및 코어데이터 내 해당 일기 삭제
    
**TableView 리스트에서 Swipe Gesture를 통해 Share 및 Delete가 가능하도록 구현**
    
    - UITableViewDelegate 내 trailingSwipeActionsConfigurationForRowAt 메서드 사용
    - UISwipeActionsConfiguration 내 share 및 delete 메서드 구현
        - 각 기능 메서드는 위의 메모 작성중 우측 상단 버튼에 사용된 메서드와 유사
    
**TableView 에서 원하는 일기를 검색할 수 있도록 SearchBar 구현**
    
    - `UISearchController` 생성 후, `navigationItem`에 적용
    - `UISearchResultsUpdating` 내 `updateSearchResults` 메서드 사용
        - 원하는 일기 검색 시, `title`과 `body`에 해당 내용이 포함되어 있는 일기만을 `Core Data`에서 `fetch`
        - 일기 검색 초기화 시, 다시 모든 일기를 `Core Data`에서 `fetch`

## 🚀 TroubleShooting

### STEP 2
#### T1. TableView snapShot 업데이트 에러

- 아래와 같이, `NSFetchedResultsControllerDelegate`를 채택하여 `NSFetchedResultsController`에 변화가 감지될 때, `controllerWillChangeContent` 메서드 내에서 `tableView`의 `beginUpdates` 메서드를 시작으로, `controllerDidChangeContent` 메서드 내 `tableView`의 `endUpdates` 메서드에 다다를 때까지, 감지한 `insert`, `delete`, `update`에 대한 내용을 `snapShot`에 적용하고, `dataSource`에서 `snapShot`을 `apply`를 하고자 하였습니다.
    
- **기존 코드 :**
    ```swift
    extension DiaryListViewController: NSFetchedResultsControllerDelegate {
        func controllerWillChangeContent(_ controller: NSFetchedResultsController<NSFetchRequestResult>) {
            diaryView.tableView.beginUpdates()
        }
        
        func controller(_ controller: NSFetchedResultsController<NSFetchRequestResult>, didChange anObject: Any, at indexPath: IndexPath?, for type: NSFetchedResultsChangeType, newIndexPath: IndexPath?) {
            
            ...
            
            switch type {
            case .insert:
                
                ...
                
                snapShot.insertItems([diaryData], beforeItem: lastDiaryData)
            case .delete:
                snapShot.deleteItems([diaryData])
            case .update:
                snapShot.reloadSections([.main])
            default:
                break
            }
            
            dataSource?.apply(snapShot)
        }
        
        func controllerDidChangeContent(_ controller: NSFetchedResultsController<NSFetchRequestResult>) {
            diaryView.tableView.endUpdates()
        }
    }
    ```
- 하지만, 위의 경우 `DiaryListViewController`에서는 아무 문제가 없었지만, 다음 뷰컨트롤러인 `DiaryContentViewController`에서 `DiaryListViewController`로 돌아올 때, `DiaryListViewController`에서는 화면이 표시되기 전에, `tableView`의 `UI`에 관한 내용에 영향을 미쳐 콘솔로그에 에러 메시지가 나타났습니다.
    
- 해당 문제상황을 `tableView`를 다시 그리는 과정이 `DiaryListViewController`로 돌아온 이후에 수행되어야 하는데, 돌아오기 전에 수행되어 에러 메시지가 나온 것이라 판단을 내렸습니다. 이에, 영향을 주는 메서드를 확인해본 결과, `beginUpdate`, `endUpdates`, `dataSource`의 `apply` 메서드가 영향을 미치고 있었습니다.
    
- `beginUpdate`, `endUpdates`의 경우 `tableView`를 변경하는 메소드들을 여러번 호출해야 하는 경우 필요한 메서드였습니다. 하지만 일기장의 경우, 일기장 저장, 업데이트, 삭제가 각각 독립적으로 호출되고 있기 때문에 해당 메서드를 사용할 필요가 없었습니다. 이에 해당 메서드를 제거하였습니다.
    
- 다음으로, `dataSource`의 `apply` 메서드는 일기장 저장 및 업데이트의 경우는 결국 `DiaryListViewController`로 돌아오니, `viewDidDisappear`에서 `apply` 메서드를 호출하였고, 삭제의 경우는 `DiaryListViewController` 내 `swipeConfiguration`을 통해서도 이루어지므로, `viewDidDisappear`을 호출하지 않기 때문에, `deleteDiary` 메서드가 호출될 때, 바로 `apply` 메서드를 사용하여 문제를 해결하였습니다.

- **수정 코드 :**
    
    ```swift
    final class DiaryListViewController: UIViewController {
    		override func viewDidAppear(_ animated: Bool) {
    				super.viewDidAppear(animated)
            
            dataSource?.apply(snapshot)
    		}
    
    		private func deleteDiary(createdAt date: Date) {
            do {
                try CoreDataManager.shared.delete(createdAt: date)
                dataSource?.apply(snapshot)
            } catch {
                presentErrorAlert(error)
            }
        }
    }
    
    extension DiaryListViewController: NSFetchedResultsControllerDelegate {
        func controller(_ controller: NSFetchedResultsController<NSFetchRequestResult>, didChange anObject: Any, at indexPath: IndexPath?, for type: NSFetchedResultsChangeType, newIndexPath: IndexPath?) {
            
            switch type {
            case .insert:
                
                ...
                
                snapShot.insertItems([diaryData], beforeItem: lastDiaryData)
            case .delete:
                snapShot.deleteItems([diaryData])
            case .update:
                snapShot.reloadSections([.main])
            default:
                break
            }
    
    	// dataSource?.apply(snapShot) 메서드 삭제
        }
    }
    ```

#### T2. SearchBar에서 검색시 올바르게 뜨지 않는 문제
- `SearchBar`에서 일기장을 검색 할 경우 검색된 내용의 개수는 맞았지만, 검색된 데이터가 다르게 뜨는 문제가 발생했습니다.

- 원인을 분석해 본 결과 현재 프로젝트에서 `NSFetchedResultsController`를 사용하고 있는데, `dataSource` 내부에서 `Cell`을 `dequeue`하는 과정에서도 `NSFetchedResultsController` 내부의 `fetch`를 하는 메서드를 사용했기 때문이었습니다.

- 결과적으로 `dataSource` 내부에서는 `snapshot`으로부터 전달받은 `item`을 할당해주니 정상적으로 해결되었습니다.
    
- **기존 코드 :**
```swift
private func configureDataSource() {
    configureSnapshot()
    
    let tableView = diaryView.tableView
    
    dataSource = UITableViewDiffableDataSource<Section, DiaryData>(
        tableView: tableView,
        cellProvider: { tableView, indexPath, item in
            guard let cell = tableView.dequeueReusableCell(
                withIdentifier: DiaryListCell.identifier,
                for: indexPath
            ) as? DiaryListCell else {
                return nil
            }
            
            let diary = self.fetchResultsController.object(at: indexPath)
            cell.titleLabel.text = diary.title
            cell.dateLabel.text = diary.createdAt?.localizedString
            cell.bodyLabel.text = diary.body
            cell.accessoryType = .disclosureIndicator
            
            return cell
        }
    )
}
```
- **수정 코드 :**
```swift
private func configureDataSource() {
    let tableView = diaryView.tableView
        
    dataSource = UITableViewDiffableDataSource<Section, Diary>(
        tableView: tableView,
        cellProvider: { tableView, indexPath, item in
            guard let cell = tableView.dequeueReusableCell(
                withIdentifier: DiaryListCell.identifier,
                for: indexPath
            ) as? DiaryListCell else {
                return nil
            }
            
            cell.titleLabel.text = item.title
            cell.dateLabel.text = item.createdAt?.localizedString
            cell.bodyLabel.text = item.body
            cell.accessoryType = .disclosureIndicator
            
            return cell
        }
    )
    
    dataSource?.apply(snapshot)
}
```
    
## 2️⃣ STEP 2
    
### STEP 2 Questions & Answers

#### Q1. NSFetchResultsController 메서드 현업 사용 여부
- `Core Data`를 활용하는 방법으로, 단독으로 `Core Data`의 `persistentContainer`나 `viewContext`를 이용하여 `CRUD` 작업을 수행할 수 있지만, `NSFetchResultsController`로도 처리가 가능하다는 것을 배웠습니다.
    
- `NSFetchResultsController`는 코어 데이터 `fetch` `request`의 결과를 관리하고 사용자에게 데이터를 표시하는 데 사용하는 컨트롤러로, `Core Data`만 단독으로 사용할 땐 데이터를 추가 또는 삭제를 한 뒤 데이터가 사용되는 `TableView` 등에 직접 `reloadData()`를 호출해서 수동으로 `UI` 업데이트를 해줘야 하지만, `NSFetchedResultsController`를 사용하면 `NSFetchedResultsControllerDelegate`를 활용하여 `Core Data`의 `context`를 본인이 모니터링해서 `saveContext()`가 호출될 때마다 대신 업데이트를 합니다.
    
- 이에 저희는 `TableView`를 활용할 때는, `NSFetchResultsController`를 사용하는 것이 더욱 편리하다고 생각하여 이를 이번 프로젝트에 적용해보았습니다. 현업에서는 코어 데이터를 사용할 때, `NSFetchResultsController`를 적극적으로 사용하는지 여쭈어보고 싶습니다.

#### Q2. `appDelegate.persistentContainer.viewContext.save()` vs `appDelegate.saveContext()`
- `CoreDa [...]

2022-08-24 13:04 UTC, GREENOVER requested changes
@finnn1 @Jeon-Minsu 
두분 이번 스텝2도 너무 고생 많으셨습니다!
역시... 실력자들... 이번에도 프로젝트 완성도가 아주 임팩트 있네요👍
특히 요구사항에 없는 기능 구현까지 해줌으로 보다 더 일기장다워 졌네요🙌
이번에도 너무 잘해주셔서 크게 리팩토링 할 부분은 딱히 없을것 같고 의견을 공유해보는 리뷰가 될것 같아요ㅎㅎ
그럼 리뷰 하겠습니다!
***
### 칭찬 드리고 싶은 부분
- 검색 기능을 통해 더욱 편리한 UX 💯
- 커밋 메시지 이력 관리가 너무 철저하고 세분화되어서 아주 좋네요 💯
- 네임 스페이스를 통한 매직 스트링의 철저한 관리 💯
- 전체적인 코드 컨벤션 및 네이밍 기조가 통일되어 가독성이 너무 좋아요 💯
- 메서드의 관심사 그룹 별 마크 주석을 잘 달아주셔서 파악하기 너무 용이하네요 💯
***
### 궁금하신 부분에 대한 저의 의견
1.  NSFetchResultsController 메서드 현업 사용 여부
- 우선 너무 잘 사용해주셨습니다!
그 다음 현업에서 사용 여부를 물어보시면 두괄식으로 먼저 말씀드리면 조건이 있는 예쓰입니다.
지금처럼 로컬 DB를 활용해야 하는 경우에서 CoreData를 사용한다고 치면 지금 같은 상황에서는 이미 잘 만들어놓은 NSFetchResultsController라는 API를 사용하지 않을 이유가 없습니다.
그 이유는 여러분들이 스텝2를 진행하며 느꼈던 장점이 답이 될 수 있겠습니다.
그럼 왜 조건이 있는 예쓰라고 했는지 의문이 드실 수 있을거에요😀
거기에 대한 대답은 일단 당연히 이건 모든 조직마다 현업마다 다르겠지만 저는 CoreData 대신 주로 Realm이라는 라이브러리를 사용합니다!
좀 더 편리하고 직관적으로 사용할 수 있어서요ㅎㅎ..
그렇기에 현업에서 CoreData를 사용한다면 NSFetchResultsController를 상황에 맞게 활용하겠지만 애초에 다른 로컬 DB 라이브러리를 활용한다면 사용하지 않게 되겠죠..!?
너무 당연한 말이긴하네요🥲
결국 여러분들이 궁금했던건 CoreData 사용 시 일테니까 예쓰가 될것 같습니다!
시간이 되신다면 다른 로컬 DB 라이브러리들의 구현도 보시면 도움이 많이 될것 같습니다🙌
(Realm, SQLite 같은)
2. appDelegate.persistentContainer.viewContext.save() vs appDelegate.saveContext()
- 저는 가령 이 부분 뿐만 아니라 최대한 커스텀하게 처리해주는걸 선호합니다!
이유는 에러 처리를 명확하게 우리가 원하는 방식으로 해주는게 더 적절하다고 생각해요.
fatalError 자체는 기본적으로 애플에서 흔히 뭐 없을때 그냥 박아놓는 느낌으로 사용될때가 많아요.
사실 앱 크래쉬를 내지 않아도 되는것인데도 약간 관습처럼 넣는 경우가 많죠ㅠ
그렇기에 애플의 기본 API를 그렇게 많이 신뢰하면서 따르지는 않습니다.
그렇기에 답은 직접 필요한 메서드를 호출해 fatalError 대신 원하는 방식에 맞게 에러를 별도로 처리해주는 방법이 더 적절하다고 생각합니다🙋🏻
3. 튜플 조건문 가독성 향상 고민
- 요 대답은 리뷰 코멘트에도 간단히 남겼는데 한번 더 정리해보겠습니다!
우선 일단 저는 이정도에서는 해당 튜플 switch case의 가독성이 나쁘지 않고 오히려 조금 더 함축적이고 이해가 잘 간다고 생각은 합니다..!
근데 만약 여러분들이 이게 가독성을 해친다고 고민한다면 굳이 fetchSuccess와 isDeleted를 튜플로 묶을 필요는 없을것 같아요.
분기처리를 나눠서 가져가도 가독은 더 좋아질 수 있을거라 생각합니다🙋🏻
4. UISearchController 내부의 obscuresBackgroundDuringPresentation 프로퍼티 사용시 정상적으로 나타나지 않는 문제
- 음 여러분들이 정상적이라고 생각한 서치바는 흰색이고 그 밑에 리스트만 딤드처리 되는것이 `obscuresBackgroundDuringPresentation = true`일때 즉 obscuresBackgroundDuringPresentation이 기대하는 설정이라는걸 학습하신 문서가 있으실까요?
제가 알기론 해당 설정은 백그라운드 그러니까 해당 서치바까지 감싸져 있는 배경에 적용되는걸로 알고 있어요.
즉 아래처럼 뷰 디버깅을 해보시면 서치바가 올려져 있는 배경 전체가 딤드된걸 볼 수 있습니다.
![스크린샷 2022-08-24 오후 9 59 14](https://user-images.githubusercontent.com/72292617/186424581-8d707deb-e4e8-4c44-bccb-ed8631609caf.png)
그렇기에 저 설정이 서치바는 그대로 흰색인데 그 밑에 리스트만 자동으로 구현해주는건 아닐것 같고 여러분들이 첨부해준 연락처와 같은 예시는 별도 처리가 더 이뤄져있을거라 생각듭니다.
아마 여러분들이 원하시는게 이런거 아닐까요?
![Simulator Screen Shot - iPhone 11 Pro - 2022-08-24 at 21 58 06](https://user-images.githubusercontent.com/72292617/186424812-f11b2001-4ab1-4395-a0c7-11ce4e45d9be.png)
현재 서치바나 특정 네비게이션 부분의 background 색상을 특별히 지정해주지 않았기에 시스템을 따라갈거에요.
즉 이것들이 올려진 백그라운드를 따라가게 되죠..!
그렇기에 저런 처리를 해주려면 처리를 원하는 컴포넌트들에 기본 색상을 지정해줘야될것 같습니다.
위 이미지도 단순히 서치바 구성 시 서치바의 백그라운드 색상을 white로 지정해준것일 뿐입니다🙌
혹시 이런 구현을 원하신건지 아니라면 의견 남겨 주시면 감사하겠습니다
***
### 보완 되면 좋을 부분
- 디코에서 한번 말씀드린 부분이긴 하지만 여기도 또 다시 남겨놓겠습니다~!
현재 일기 작성 시 body가 들어가지 않으면 저장이 되지 않는 이슈가 있어 픽스 되면 좋겠습니다🙌
***
여러분 너무 고생 많으셨어요 ㅎㅎ
신속 정확하네요👍
이슈 사항이 있어 우선 Request Changes로 남겨두겠습니다!
언제든 수정이 되면 리뷰 재요청을 해주세요~
화이팅입니다🥳🥳🥳

2022-08-26 05:55 UTC, finnn1 commented on Diary/Models/CoreDataManager.swift
> +final class CoreDataManager {
앗.. 그러네요! `CoreDataManager` 클래스 및 `CoreData ` 그룹을 `Resources` 그룹으로 빼주었습니다 🙏🙏

2022-08-26 05:56 UTC, finnn1 commented on Diary/Models/CoreDataManager.swift
> +    let persistentContainer: NSPersistentContainer = {
`private` 접근제어자 설정 완료하였습니다! ☺️

2022-08-26 06:01 UTC, finnn1 commented on Diary/Models/CoreDataManager.swift
> +    }
`CoreDateManager`는 현재 앱에서 전역적으로 사용되고 있기 때문에 싱글톤 패턴을 활용해서 정의했습니다.
`shared` 프로퍼티외에 다른 인스턴스의 생성을 막기 위해서 외부에서 `CoreDateManager` 클래스를 직접 초기화할 수 없도록 이니셜라이져에 `private` 키워드를 붙였습니다 🙏

2022-08-26 06:24 UTC, finnn1 commented on Diary/Models/CoreDataManager.swift
> +            return nil
`guard let`이 실패할 경우 `error`를 발생시켜 `throw`로 던진 후 외부 VC에서 처리할 수 있도록 수정했습니다 ☺️

2022-08-26 06:26 UTC, finnn1 commented on Diary/Extension/UIViewController+Extension.swift
> +extension UIViewController {
감사합니다 🙏🙏

2022-08-26 06:28 UTC, finnn1 commented on Diary/CoreData/Diary+CoreDataClass.swift
> +import CoreData
앗.. 미처 확인하지 못했네요 😢
`import Foundation` 제거했습니다 ☺️
감사합니다 🙏

2022-08-26 06:28 UTC, finnn1 commented on Diary/CoreData/Diary+CoreDataProperties.swift
> +import Foundation
삭제했습니다 🙏

2022-08-26 06:30 UTC, finnn1 commented on Diary/CoreData/Diary+CoreDataProperties.swift
> +
불필요한 개행 제거해주었습니다 👍👍
꼼꼼한 리뷰 감사합니다 ☺️

2022-08-26 06:31 UTC, finnn1 commented on Diary/Namespaces/Alert.swift
> +enum Alert {
감사합니다 🙏🙏

2022-08-26 07:08 UTC, Jeon-Minsu commented on Diary/CoreData/Diary+CoreDataProperties.swift
> +}
```swift
@available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
public protocol Identifiable {

    /// A type representing the stable identity of the entity associated with
    /// an instance.
    associatedtype ID : Hashable

    /// The stable identity of the entity associated with this instance.
    var id: Self.ID { get }
}

@available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
extension Identifiable where Self : AnyObject {

    /// The stable identity of the entity associated with this instance.
    public var id: ObjectIdentifier { get }
}
```

Identifiable 프로토콜을 살펴보니 클래스의 경우 Identifiable 프로토콜을 채택할 시, id 기본 구현이 제공되어 있었습니다.
의견을 나누어본 결과, 더 강력한 ID 개념을 사용하고자 기본 id가 아닌 UUID를 사용하기로 결정하였습니다. 
이에 따라 Identifiable 프로토콜 채택을 준수하는 부분을 삭제하였습니다.

2022-08-26 07:35 UTC, finnn1 commented on Diary/Controllers/DiaryListViewController.swift
> +        swipeActionCongifuration.performsFirstActionWithFullSwipe = false
저희도 이 부분에 대해서 고민하던 중, 애플 기본 메모 어플에서 스와이프가 끝까지 되지 않고, 직접 삭제 버튼을 눌러야 그때 삭제가 되도록 구현되어있는 것을 확인했습니다.
사용자가 스와이프를 하다가 실수로 메모가 삭제되는 것을 방지하고자 함이라는 생각이 들어 사용성의 측면에서 저희도 Cell 스와이프 후 직접 삭제 버튼을 누른 다음에 삭제가 되도록 구현했습니다. 🙏🙏

2022-08-26 07:53 UTC, finnn1 commented on Diary/Models/CoreDataManager.swift
> +    func delete(createdAt: Date) throws {
`Date`보다 더 고유한 값을 가진 `UUID`를 사용해서 구분해주는 방식으로 변경했습니다 ☺️

2022-08-26 08:11 UTC, finnn1 commented on Diary/Namespaces/SystemImage.swift
> +    static let share = "square.and.arrow.up"
저렇게 바로 `UIImage` 타입을 할당하면 사용시 따로 변환해줄 필요가 없겠네요! ☺️
좋은 방법을 알려주셔서 감사합니다 🙏🙏

2022-08-26 08:16 UTC, Jeon-Minsu commented on Diary/Controllers/DiaryListViewController.swift
> +        configureFetchResultsController(from: fetchAllDiaryRequest())
DiaryListViewController 익스텐션으로 UISearchResultsUpdating 프로토콜을 채택하는 부분 중,
updateSearchResults 메서드 내부에서 configureFetchResultsController가 각기 다른 파라미터를 받고 있습니다.
이는, 검색 기능을 사용할 때는, 해당 글자를 포함하는 일기장 데이터만을 가져와야 했기 때문에, 다른 인자를 받았습니다!

```swift
extension DiaryListViewController: UISearchResultsUpdating {
    func updateSearchResults(for searchController: UISearchController) {
        snapshot.deleteAllItems()
        
        guard isFiltering,
            let searchBarText = searchController.searchBar.text else {
            configureFetchResultsController(from: fetchAllDiaryRequest())
            configureSnapshot()
            dataSource?.apply(snapshot)
            return
        }
        
        let fetchRequest = fetchDiaryRequest(from: searchBarText)
        configureFetchResultsController(from: fetchRequest)
        fetchResultsController?.delegate = self
        configureSnapshot()
        dataSource?.apply(snapshot)
    }
}
```

2022-08-26 08:22 UTC, finnn1 commented on Diary/Controllers/DiaryListViewController.swift
> +        navigationItem.hidesSearchBarWhenScrolling = false
생각해보니 hide 되는 것이 훨씬 이점이 있을 것 같습니다!
스크롤시 hide 되도록 변경했습니다 ☺️

2022-08-26 08:29 UTC, finnn1 commented on Diary/Controllers/DiaryListViewController.swift
> +        ) { [weak self] action, view, completion in
현재 코드상으로는 Strong Reference Cycle이 발생할 것 같진 않지만
불필요한 Strong Reference Count를 올리는 일을 방지하고자 `weak self`를 사용했습니다 ☺️

2022-08-26 08:46 UTC, finnn1 commented on Diary/Controllers/DiaryListViewController.swift
> +        shareAction.image = UIImage(systemName: SystemImage.share)
별도의 메서드로 분리해주었습니다 🙏

2022-08-26 08:50 UTC, finnn1 commented on Diary/Controllers/DiaryContentsViewController.swift
> +        actionSheet.addAction(cancelAction)
그러네요! 말씀하신대로 해당 코드들이 configure 하고있다는 느낌이 들어 별도의 메서드로 분리해주었습니다 ☺️
섬세한 리뷰 감사합니다 🙏👍👍

2022-08-26 09:12 UTC, finnn1 commented on Diary/Controllers/DiaryContentsViewController.swift
> +    private func handleCRUD() {
메서드 이름을 `renewCoreData`로 변경했습니다 ☺️

2022-08-26 09:17 UTC, finnn1 commented on Diary/Controllers/DiaryContentsViewController.swift
> +        switch (fetchSuccess, isDeleted) {
그린의 말씀을 듣고 해당 코드를 수정하지 않는 방향으로 결정했습니다 ☺️
감사합니다 🙏

2022-08-26 09:18 UTC, finnn1 commented on Diary/Controllers/DiaryContentsViewController.swift
> +    private func extractTitleAndBody() -> (String, String)? {
body가 없어도 저장에 문제가 없도록 수정했습니다 ☺️

2022-08-26 09:20 UTC, finnn1 commented on Diary/Controllers/DiaryContentsViewController.swift
> +    private func determineDataProcessingFor(_ title: String, _ body: String, _ creationDate: Date) throws {
`For` 전치사 대신 `~을 가지고`, `~을 가진채` 라는 의미를 가진 `With`로 변경했습니다 🙏

2022-08-26 15:19 UTC, GREENOVER approved these changes
수고 많으셨습니다!
전체적으로 아주 잘 리팩토링이 되어 다음 스텝으로 넘어가도 충분할것 같습니다ㅎㅎ
다만 하나 사용자 UX적인 측면에서 고려해보면 좋을 부분이 있습니다🙋🏻
타이틀 입력 후 바디를 한 라인 개행하고 입력한다면 메모 리스트에서 해당 메모를 볼떄 아무 바디가 없어 보이는 즉 해당 빈 라인만 입력되는데 기본 메모앱와 다른 느낌이 드는데 보완해보면 좋을것 같습니다🙋🏻
예를들어 body 부분을 한 라인 뛰고 "abc" 넣었다면
실제 메모 리스트에서 해당 메모는 타이틀만 입력되고 body는 abc가 보이는게 아닌 빈 라인이 보입니다..!
정말 마이너하고 그렇지만 참고해보면 좋을 부분이라 언급드립니다!
다음 스텝도 화이팅입니다 여러분!

2022-08-26 15:19 UTC, merged