일기장 [STEP2] Derrick, 휴
yagom-academy/ios-diary pull request #47
Opened 2022-08-25 09:37 UTC by derrickkim0109

안녕하세요! 콘 @protocorn93

Step02 PR 올립니다.!

## 📝 기능설명
**일기장 데이터 저장**
- 백그라운드 진입시 
- Content View에서 뒤로가기
- 사용자가 입력을 멈추는 경우(키보드가 사라지는 경우) - 완료 버튼 클릭시

## 🚀 TroubleShooting

#### T1. title과 body를 분리하는 로직
- 일기장을 생성하는 `DiaryPostViewController`에서 `TextView` 내에 텍스트를 입력시 처리해줘야 하는 문제들이 있었습니다.
    1. 제목을 작성하고 한칸 띄워쓰기("\n\n")를 하고 내용을 작성
    2. 바로 아래라인("\n")으로 내용을 작성하는 상황

```swift

var data = text.split(separator: "\n", maxSplits: 2).map{ String($0) }
let title = data.remove(at: 0)
let body = data.count >= 1 ? data.joined(separator: "\n") : ""

```
- TextView의 텍스트를 모두 받아와 Title 부분과 분리하여 처리할 수 있도록 하였습니다. 
 
#### T2. CoreData Update
- 해당 Cell을 통해 text를 수정해도 수정이 제대로 반영되지 않고, 다른 Cell이 update되는 걸 확인 생성 시간을 기준으로 원하는 해당 Cell의 정확한 데이터를 불러오도록 수정
```swift
request.predicate = NSPredicate(format: "createdAt = %@", "\(data.createdAt)")
```

## 궁금한점
1. MVVM 패턴 적용을 위해 NotificationCenter를 사용해 보았습니다. 하지만 이게 과연 필요한 것인가? 하는 생각을 하게 되었습니다. 해당 부분은 그냥 데이터를 간단히 넘겨주는 방식으로 바꿔야 할까요?

## 스크린 샷
|일기장 생성|일기장 수정|키보드 사라짐|
|:--:|:--:|:--:|
|![](https://i.imgur.com/PulaOBC.gif)|![](https://i.imgur.com/4G7BY6L.gif)|![](https://i.imgur.com/Ampe36t.gif)|
    

|Shared|Delete|Swipe Delete|백그라운드 저장|
|:--:|:--:|:--:|:--:|
|![](https://i.imgur.com/LkU2vHk.gif)|![](https://i.imgur.com/ia4ZKUB.gif)|![](https://i.imgur.com/qEBa0vo.gif)|![](https://i.imgur.com/9PhyqAa.gif)|

2022-08-26 23:44 UTC, protocorn93 requested changes
두 분 모두 수고하셨어요! 데이터 저장을 다루는 것은 굉장히 민감한 작업일 수 있는데요. 현재는 동시성에 대해서 고려가 되어있지 않은걸로 보여져요. 다수의 스레드에서 데이터 저장을 시도하는 상항도 고려해보시면 좋을 것 같아요. 

## 질문

> MVVM 패턴 적용을 위해 NotificationCenter를 사용해 보았습니다. 하지만 이게 과연 필요한 것인가? 하는 생각을 하게 되었습니다. 해당 부분은 그냥 데이터를 간단히 넘겨주는 방식으로 바꿔야 할까요?

개인적으로 NotificationCenter를 통한 MVVM 구현은 바람직하지 않다고 생각해요. 오히려 클로저가 좀 더 적합할 것 같아요.

```swift
viewModel.someClosure = { [weak self] in
  ...
}
```

2022-08-26 23:44 UTC, protocorn93 commented on Diary/Extensions/Date+Extensions.swift
> +        }
이런 케이스에선 nil을 반환해주는 것이 바람직하지 않을까 싶어요~ 빈 문자열과 nil은 엄연히 전달하는바가 다르다고 생각하거든요. 말 그대로 값이 없음을 의미하는 것이니 nil이 좀 더 적합해보여요

2022-08-26 23:44 UTC, protocorn93 commented on Diary/Extensions/TimeInterval+Extensions.swift
> +        }
`Date+Extension`과 마찬가지에요

2022-08-26 23:44 UTC, protocorn93 commented on Diary/Model/CoreDataManager.swift
> +final class CoreDataManager {
데이터를 저장하는 행위를 추상화해보는 것은 어떨까요?

```swift 
protocol DataManageLogic { 
  func save()
  func remove()
  ...
}

final class CoreDataManager: DataManagerLogic {
  ...
}
```

메서드 이름도 단순하게 `save`, `update`, `fetch` 등으로 가져가면 좋을 것 같아요. 그리고 이를 채택해서 구현하는 곳에선 내부적으로 Core Data를 사용하던, Realm을 사용하던 각자 구현하는 것이죠!

2022-08-26 23:44 UTC, protocorn93 commented on Diary/Model/CoreDataManager.swift
> +        let result = try? context.fetch(request)
저장된 데이터를 다루는 메서드이기 때문에 에러를 외부로 `throws` 해주는게 중요하다고 생각해요. 매니저의 모든 메서드는 에러를 던지고 이를 외부에서 처리하도록 수정해보시면 좋을 것 같아요

2022-08-26 23:44 UTC, protocorn93 commented on Diary/Model/CoreDataManager.swift
> +    lazy var persistentContainer: NSPersistentContainer = {
내부에서만 사용하는 것으로 보여지는데 접근제어자가 필요해보여요

2022-08-26 23:44 UTC, protocorn93 commented on Diary/Model/CoreDataManager.swift
> +    func deleteContext(title: String) {
타이틀이 동일한 게시글이 있다면 어떻게 처리되나요?

2022-08-26 23:44 UTC, protocorn93 commented on Diary/View/DiaryContent/DiaryContentViewController.swift
> +        }
공유를 위한 텍스트라면 뷰모델로부터 받아오는 것이 좋을 것 같네요. 현재는 뷰모델이나 텍스트뷰나 모두 동일한 raw한 text이지만 이후 뷰모델에서 어떤 가공이 일어날지 모르니 뷰모델로부터 공유할 컨텐츠를 받아오는 것이 더 적절해보여요

2022-08-26 23:44 UTC, protocorn93 commented on Diary/View/DiaryContent/DiaryContentViewController.swift
> +        diaryViewModel.update(text: diaryDescriptionTextView.text, date: diaryContent.createdAt)
뷰모델로부터 데이터를 받아와서 다시 뷰모델에 전달하는데 이건 불필요해보여요.

2022-08-26 23:44 UTC, protocorn93 commented on Diary/View/DiaryContent/DiaryContentViewController.swift
> +        diaryViewModel.update(text: diaryDescriptionTextView.text, date: diaryContent.createdAt)
저는 이런 인터페이스를 가져갈 것 같아요.

```swift
// ViewController
@objc private func didEnterBackground() { 
  viewModel.didEnterBackground()
}

// ViewModel
func didEnterBackground() { 
  // update
}
```

일단 기본적으로 텍스트뷰 델리게이트 메서드를 통해 지속적으로 텍스트에서 입력되는 값을 뷰모델에게 전달해주고 뷰모델에선 항상 회신 텍스트 값을 갖고 있어야겠지요!

2022-08-26 23:44 UTC, protocorn93 commented on Diary/ViewModel/DiaryViewModel.swift
> +    static let diaryContent = Notification.Name("DiaryContent")
`diaryContentDidChanged`가 좀 더 명확한 네이밍일 것 같아요.

2022-08-26 23:44 UTC, protocorn93 commented on Diary/ViewModel/DiaryViewModel.swift
>  final class DiaryViewModel {
뷰모델을 사용한다면 프로토콜로 추상화는 필수로 구현해주시면 좋을 것 같아요.

2022-08-26 23:44 UTC, protocorn93 commented on Diary/ViewModel/DiaryViewModel.swift
> +        let body = data.count >= 1 ? data.joined(separator: "\n") : ""
텍스트 편집이라는 특수한 목적을 갖고 있는 화면이기에 "\n", ""와 같은 문자열들은 네임스페이스로 관리하는게 이후 개발에 용이하지 않을까 싶어요. 

```swift
private enum Const { 
  static let emptyString = ""
  static let nextLineString = "\n"
  ...
}
```

2022-08-26 23:44 UTC, protocorn93 commented on Diary/ViewModel/DiaryViewModel.swift
> +        }
compactMap을 활용해볼 수 있을 것 같아요.

2022-08-26 23:44 UTC, protocorn93 commented on Diary/ViewModel/DiaryViewModel.swift
> +    static let diaryContent = Notification.Name("DiaryContent")
그리고 반복되는 문자열(`"DiaryContent"`)이 있다면 이 역시 네임스페이스로 분리해주시면 관리가 더 용이할 것 같네요.

2022-08-26 23:44 UTC, protocorn93 commented on Diary/View/DiaryPost/DiaryPostViewController.swift
> +    private let diaryViewModel = DiaryViewModel()
뷰모델도 생성자를 통해 주입해주면 좋을 것 같아요.

2022-08-26 23:44 UTC, protocorn93 commented on Diary/View/DiaryPost/DiaryPostViewController.swift
> +    }()
텍스트를 입력하다가 멈추고 일정시간이 흐르면 자동으로 백업해줄 수 있도록 구현해보면 좋을 것 같아요. 그러기 위해선 텍스트뷰 델리게이트 메서드를 구현할 필요가 있겠네요

2022-08-27 13:56 UTC, derrickkim0109 commented on Diary/View/DiaryPost/DiaryPostViewController.swift
> +    }()
수정했습니다.

2022-08-27 13:57 UTC, derrickkim0109 commented on Diary/View/DiaryPost/DiaryPostViewController.swift
> +    private let diaryViewModel = DiaryViewModel()
수정했습니다.

2022-08-27 13:57 UTC, Hugh-github commented on Diary/Extensions/Date+Extensions.swift
> +        }
수정했습니다 ☺️

2022-08-27 13:57 UTC, Hugh-github commented on Diary/Extensions/TimeInterval+Extensions.swift
> +        }
수정했습니다 ☺️

2022-08-27 13:57 UTC, derrickkim0109 commented on Diary/ViewModel/DiaryViewModel.swift
> +        }
수정했으나 맞는 방법인지는 모르겠습니다..!

2022-08-27 13:57 UTC, derrickkim0109 commented on Diary/ViewModel/DiaryViewModel.swift
> +        let body = data.count >= 1 ? data.joined(separator: "\n") : ""
추가하였습니다!

2022-08-27 13:58 UTC, derrickkim0109 commented on Diary/ViewModel/DiaryViewModel.swift
>  final class DiaryViewModel {
추상화 하였습니다.!

2022-08-27 13:58 UTC, Hugh-github commented on Diary/Model/CoreDataManager.swift
> +final class CoreDataManager {
CoreDataManager를 추상화해주었습니다. 
메서드의 이름을 단순한 게 변경했습니다.

2022-08-27 13:58 UTC, derrickkim0109 commented on Diary/ViewModel/DiaryViewModel.swift
> +    static let diaryContent = Notification.Name("DiaryContent")
해당 부분은 삭제하였습니다.

2022-08-27 13:58 UTC, derrickkim0109 commented on Diary/View/DiaryContent/DiaryContentViewController.swift
> +        }
해당 부분은 삭제하였습니다.

2022-08-27 13:59 UTC, Hugh-github commented on Diary/Model/CoreDataManager.swift
> +        let result = try? context.fetch(request)
에러를 ViewModel에서 처리하도록 수정했습니다.

2022-08-27 13:59 UTC, derrickkim0109 commented on Diary/Model/CoreDataManager.swift
> +    func deleteContext(title: String) {
삭제되지 않을 것입니다. 해당 부분은 createdAt 프로퍼티를 통해 삭제되도록 처리하였습니다.

2022-08-27 13:59 UTC, derrickkim0109 commented on Diary/Model/CoreDataManager.swift
> +    lazy var persistentContainer: NSPersistentContainer = {
수정했습니다.

2022-08-27 13:59 UTC, Hugh-github commented on Diary/Model/CoreDataManager.swift
> +    lazy var persistentContainer: NSPersistentContainer = {
접근제어가 추가했습니다.

2022-08-27 13:59 UTC, derrickkim0109 commented on Diary/Model/CoreDataManager.swift
> +        let result = try? context.fetch(request)
수정하였습니다.

2022-08-27 14:00 UTC, Hugh-github commented on Diary/Model/CoreDataManager.swift
> +    func deleteContext(title: String) {
createdAt이 고유한 값이라 판단하여 해당 키워드를 이용해 delete 하도록 수정했습니다.

2022-08-27 14:09 UTC, Hugh-github commented on Diary/View/DiaryContent/DiaryContentViewController.swift
> +        diaryViewModel.update(text: diaryDescriptionTextView.text, date: diaryContent.createdAt)
뷰모델로부터 데이터를 받아와 다시 뷰모델에 전달하는 로직은 수정했습니다.
delegate를 사용하는 부분에 대해서는 저희가 만든 ViewModel에서 어떻게 처리해야 하는지 감이 잡히질 않아 수정을 못했습니다.

2022-08-27 14:12 UTC, Hugh-github commented
ViewModel을 전체적으로 새롭게 작성했습니다. 새로운 ViewModel을 추상화하는 과정에서 Spy ViewModel처럼 구현하러 하셨는데 Spy란 상태와 행동을 둘 다 테스트 가능하도록 추상화를 하는 게 맞을까요?
이 부분에 대해서 좀 더 조언을 얻고 싶습니다.

2022-08-28 11:35 UTC, protocorn93 commented
> ViewModel을 전체적으로 새롭게 작성했습니다. 새로운 ViewModel을 추상화하는 과정에서 Spy ViewModel처럼 구현하러 하셨는데 Spy란 상태와 행동을 둘 다 테스트 가능하도록 추상화를 하는 게 맞을까요?
> 
> 이 부분에 대해서 좀 더 조언을 얻고 싶습니다.

네네 맞아요. 스파이 객체를 만들면 대충 아래와 같을거에요. 

```swift
final class SomeViewModelSpy: SomeViewModelLogic {
 
  var someMethodCalled: Int = 0
  var someMethodParams: String?

  func someMethod(_ param: String) { 
    self.someMethodCalled += 1 
    self.someMethodParams = param
  }
}


class SomeViewControllerTests: XCTestCase {

  var viewModel: SomeViewModelSpy
  var sut: SomeViewController!

  override func setUp() { 
    self.viewModel = SomeViewModelSpy()
    self.sut = SomeViewController(viewModel: self.viewModelSpy)
  }
}
```

이렇게 해당 뷰모델 메서드가 잘 호출되고 인자를 제대로 넘겼는지를 확인해볼 수 있겠지요

2022-08-28 11:53 UTC, merged