일기장 [STEP2] hyeon2, yeton
yagom-academy/ios-diary pull request #48
Opened 2022-08-26 07:24 UTC by yeeton37

@jryoun1

안녕하세요 제이크🧑🏻‍💻
일기장 프로젝트 STEP2 PR 보냅니다!
이번 리뷰도 잘 부탁드립니다🙇🏻‍♀️

## 폴더 구조
```swift
.
└── Diary/
    ├── info.plist
    ├── Resources/
    │   ├── LaunchScreen
    │   └── Assets
    └── Sources/
        ├── AppDelegate
        ├── SceneDelegate
        ├── Util/
        │   ├── Common/
        │   │   └── Protocol/
        │   │       ├── ReuseIdentifying
        │   │       ├── SendDataDelegate
        │   │       └── CoreDataProcessing
        │   └── JSONData
        ├── Controllers/
        │   ├── DetailDiaryViewController
        │   └── DiaryListTableViewController
        ├── Views/
        │   └── DiaryTableViewCell
        └── Models/
            ├── DiaryContents + CoreDataClass
            ├── DiaryContents + CoreDataProperties
            └── DiarySample
```

## 🔧구현 내용
|구현 위치(파일명)|핵심 구현 내용|
|:--|:--|
|`CoreDataError`|`CoreData` 관련 에러 타입 구현|
|`ReuseIdentifying`|`Identifier` 네임스페이스 처리를 위한 프로토콜 구현|
|`SendDataDelegate`| 뷰컨트롤러간 데이터 전달해주는 프로토콜 구현|
|`CoreDataProcessing`| `CoreData` 관련 메서드 구현|
|`DetailDiaryViewController`|일기 생성 및 업데이트 기능, 액티비티뷰, 알림창 구현|
|`DiaryListTableViewController`|스와이프 시 일기 삭제되는 기능 구현|
|`SceneDelegate`|백그라운 진입 시 자동 저장되는 기능 구현|
|`Diary`|`DiaryContents` Entities 구현|

## 😲고민했던 점

### 1. 데이터 삭제 시 UI에 바로 적용되지 않는 문제
- 구현하고자 했던 기능
    - 두 번째 뷰컨의 일기장 작성 화면에서 일기장을 `delete`하면 두 번째 뷰컨이 `pop` 되고, `pop`이 되어 첫 번째 뷰컨으로 돌아왔을 때 일기장이 바로 삭제가 되어있어야 합니다.
- 구현 실패 과정
    - 첫 번째 뷰컨으로 돌아왔을 때 삭제가 된 화면이 바로 나타나지 않았고, 다시 앱을 재실행할 때만 삭제된 것이 제대로 나타났습니다.
- 저희가 생각한 실행 흐름
    -  삭제 버튼을 누를 시 `Core Data`의 `context`에서 삭제가 되고 ➡️ 바뀐 내용을`context`에 저장하고 ➡️ `fetch`를 통해 삭제된 데이터를 가져오고 ➡️ 이를 `snapshot`에 `append`해주고 ➡️ `dataSource`에 `snapshot`을 `apply` 해줍니다.
    - 하지만, 위의 순서로 코드를 구현하니 제대로 작동되지 않았습니다. 이유를 찾아보니 데이터 삭제시 스냅샷에서도 `deleteItems` 메서드를 통해 데이터를 삭제해주는 과정이 추가로 더 필요한 것을 알게되었습니다. 
- 해결 방법
    - 위의 이유를 통해 다음과 같은 코드를 추가해 줌으로서 UI에 바로 적용되지 않는 문제를 해결했습니다.
    ```swift
    snapshot.deleteAllItems()
    snapshot.appendSections([.main])
    ```
  
## 🙏🏻조언얻고 싶은 점

### 1. create와 update 구분 방법

- 일기 생성과 수정 모두 `DetailDiaryViewController` 에서 처리하고 있습니다.
- `textView`에서 키보드가 내려갈 때나(`textView`아래로 스크롤 할 경우) 이전 화면으로 갈 때 생성 또는 수정을 진행하고 있습니다.
- 이 때, `isExist`라는 프로퍼티를 통해 이 값이 True이면 `update` 메서드가 호출되고, 반대면 `create` 메서드가 호출되도록 해주었습니다. (즉, 이미 데이터가 존재한다면 그걸 update 해주고, 아무런 데이터가 없다면 새로 create를 해주는 과정을 구현하고자 함이었습니다.)
- 또한 `textView`에 아무런 내용이 없으면 저장이 되지 않게 `saveDiaryContents()`메서드에 코드를 작성했습니다.
- `isExist` 라는 전역 변수를 사용하지 않고도 create와 update를 구분하는 좋은 방법이 있을까요?😲

- 코드
```swift
@objc func saveDiaryContents() {
        if textView.text.isEmpty == false && isExist == false {
            create(content: getProcessedContent()) { error in 
                DispatchQueue.main.async {
                    self.showErrorAlert(error: error)
                }
            }
        } else if textView.text.isEmpty == false && isExist == true {
            update(
                entity: content ?? DiaryContents(),
                content: getProcessedContent(),
                errorHandler: { error in
                    DispatchQueue.main.async {
                        self.showErrorAlert(error: error)
                    }
                })
        }
    }
```

### 2. title과 body 구분 방법
- 요구서의 예시 화면을 참고하여, `textView`에서 `\n\n`을 기준으로 `title`과 `body`를 구분해주었습니다.
- `textView`에 `\n\n`이 없는 경우 CoreData에 제대로 저장되지 않는 오류가 발생했습니다.
- 이 오류를 해결하기 위해 `\n\n`으로 `components` 해 주었을 경우, 배열의 개수가 2개 이상인지 확인하는 코드를 추가하여, 2개 미만이면 임의로 데이터를 넣어주도록 했습니다.
- 또한 title에 `\n`이 들어간 경우 셀에서 제목이 잘리는 현상이 발생해 `\n` 대신 `" "` 공백으로 바꿔주었습니다.
- 사용자 입력을 임의로 바꿔줌으로써 사용자가 원하는 결과를 충족시켜주지 못할 수도 있을 것 같아 좋은 코드라는 생각이 들지 않습니다,,😓
- 더 나은 방식으로 title과 body를 구분하고, 예외처리를 해 주고 싶은데 어떤 아이디어로 접근해보면 좋을지 궁금합니다!

- 코드 
```swift
func getProcessedContent() -> [String] {
    var content = textView.text.components(separatedBy: "\n\n")
        
    if content.count >= 2 {
        return content
    }
        
    if content[0] == "\n" {
        content[0] = " "
    }
        
    content.append("")
        
    return content
}
```

### 3. 앱 백그라운드 진입 시 자동 저장되는 기능 구현
- 앱이 백그라운드로 진입 시 자동 저장이 되는 기능을 노티피케이션센터를 활용해서 구현하고자 하였습니다.
- 먼저, 앱이 백그라운드로 진입시 호출되는 SceneDelegate의 sceneDidEnterBackground 메서드 내부에 아래와 같이 코드를 작성해주었습니다. 
- 이는 이 메서드가 호출될 시 post해주기 위한 코드입니다.

- 코드

```swift
NotificationCenter.default.post(name: Notification.Name("백그라운드진입"), object: nil)
```

- 또한, 아래와 같이 NotificationCenter를 두 번째 뷰컨트롤러에 옵저버로 등록해주었습니다. 
- 이후에 NotificationCenter가 post를 하면 test 메서드를 호출하도록 구현했습니다.
```swift
NotificationCenter.default.addObserver(self, selector: #selector(test), name: Notification.Name("백그라운드진입"), object: nil)

@objc func test() {
    print("이 print문이 출력되야 함...")
}
```

- 하지만 test 메서드 자체가 호출이 되지 않더군요.... 이유가 뭔지 잘 모르겠습니다. 다른 동기분들과 의견을 나누어보았는데 다른 분의 코드에서는 위와 동일하게 작성해줄 시 정상적으로 test 메서드가 호출되더군요. 저희 코드의 문제일까요....? 혹은 xcode의 버그일까요..?🤔

---
이상입니다! 잘 부탁드려요 ✨

2022-08-29 13:37 UTC, jryoun1 requested changes
@yeeton37 @seohyeon2 
step2 정말 잘 작성해주셨네요! 고생하셨습니다 👏👍🏻

코드가 깔끔하게 작성되어 읽기에 아주 좋았던 것 같습니다. 💯👍🏻
또한 정리도 잘해주셔서 어떤 부분들을 고민하시고 공부하셨는지 확인할 수 있었습니다. 
다만 몇 가지 에러와 수정해야할 부분들이 있어서 request change를 요청드립니다.

아래 부분에 대해서 코멘트와 함께 고민해보시면 좋을 것 같아요. 
1. body가 항상 저장되어야하는가 
  - 현재 title만 있고 body가 없는 경우에는 문제가 발생하게 됩니다. 
  - 사용자가 title만 적고 뒤로가거나 백그라운드로 가는 경우에 강제로 body를 만들어주는 것이 좋은 UX인지?

조언을 얻고 싶은 점 2번도 위와 연관이 되어있는 것 같아요! 해당 부분은 아래 코멘트에 남겨드렸습니다.

## 조언받고 싶은 부분에 대한 답변
1, 2번 아래 코멘트에 남겨드렸습니다. 확인부탁드려요 🙏🏻
3번의 경우에는 말씀하신대로 테스트를 진행해봤는데 저는 잘 동작하는 것 같습니다. 
혹시 어떻게 작성하셨는지 브랜치를 따로 파서 알려주시거나 코드를 첨부해주시면 더 자세하게 봐드릴 수 있을 것 같아요 🙂

코멘트에서 이해가 안가거나 하는 부분이 있다면 편하게 dm주세요 🙏🏻

2022-08-29 13:37 UTC, jryoun1 commented on Diary/Sources/Controllers/DetailDiaryViewController.swift
> +    }
말씀하신 부분이 바로 여기군요 🙂
title과 body의 구분을 하는 방법에 대해서는 기획서에 아래와 같이 나와있던 것 같아요!
- `일기의 맨 첫 줄은 일기의 제목이 되고, 그 다음 줄부터 본문이 됩니다` 

만약 기획서를 읽고 애매한 케이스가 있는 것 같다면, 해당 기획서를 작성한 사람에게 이러한 케이스에는 어떻게 동작하는 것을 의도했는지 물어보고 해당 의도에 맞게 구현을 해주면 좋을 것 같네요.  
예를 들어 일기장에 `\n\n\n\n\n 예톤과 현이의 일기장 \n 입니다.` 라고 할 때 
- list에서 보여져야하는 제목 
    - \n이 리스트에서 해당 일기장의 제목으로 보여져야하는지
    - 예톤과 현이의 일기장이 제목으로 보여져야하는지
- 일기장 상세에 들어왔을 때 
     - \n\n\n\n\n 들이 보여지고 예톤과 현이의 일기장이 나와야하는지

<br>

개인적인 의견으로는 가장 좋은 UX는 `\n\n\n\n\n 예톤과 현이의 일기장 \n 입니다.`라고 할 때
- list에서 보여져야하는 제목은 `예톤과 현이의 일기장`
- 일기 상세로 들어왔을 때는 \n\n\n\n\n이 나타난 이후 예톤과 현이의 일기장이 보여지는 것

이 사용자가 가장 기대하는 UX가 아닐까 싶습니다. 
만약 위와같이 구현한다면 아래와 같이 coreData에 저장할 수 있을 것 같네요. 
- title: 맨 처음부터 첫번째 글자 이후 \n이 나타나기 전까지의 모든 내용
- body: \n이 나타난 이후의 모든 내용

이렇게 된다면 표시하는 부분에서 \n을 ""로 치환해주어야하는데 해당 부분은 이미 해주고 계신것 같네요 
```swift
        diaryTitleLabel.text = item.title?.replacingOccurrences(
            of: "\n",
            with: ""
        )
```

2022-08-29 13:37 UTC, jryoun1 commented on Diary/Sources/Controllers/DetailDiaryViewController.swift
> +    }
body값이 없다면 아예 값이 보여지지 않을 것 같은데 title만 있고 body는 없는 경우도 있지 않을까요? 🤔

2022-08-29 13:37 UTC, jryoun1 commented on Diary/Sources/Controllers/DetailDiaryViewController.swift
> +        }
위의 코멘트에서도 한 번 언급했지만 배열의 index로 직접 접근은 최대한 지양하시는게 좋습니다.
indexoutofArray가 발생할 가능성이 크고 그렇게 된다면 크래시가 발생하게 될 것 입니다 🚨

2022-08-29 13:37 UTC, jryoun1 commented on Diary/Sources/Controllers/DetailDiaryViewController.swift
> +        self.isExist = isExist
말씀하신 첫번째 고민이 여기군요!
지금 해주신 것 처럼 `isExist`라는 프로퍼티를 protocol에서 같이 넘겨주는 방법도 좋은 방법이 될 수 있다고 생각합니다.

다만 isExist 값을 DiaryListTableViewController에서 꼭 알아야할 필요가 있을까요
DetailDiaryViewController 내부에 아래와 같이 연산프로퍼티로 값을 가지고 있어도 될 것 같아요. 
```swift
    private var isExist: Bool {
        return content != nil
    }
```

또 다른 방법들은 실제 내용을 저장, 업데이트하는 시점에 coredata에서 검색을 해서 값이 있는지 확인해본다던지, diaryContents 모델에 isFirstWritten과 같은 값을 가지고 있다던지 등 여러 가지 방법이 있을 것 같긴하네요. 🙂

2022-08-29 13:37 UTC, jryoun1 commented on Diary/Sources/Controllers/DetailDiaryViewController.swift
> +final class DetailDiaryViewController: UIViewController, CoreDataProcessing {
네이밍이 DiaryListViewController와 동일한 패턴이 아닌것 같아요!
둘이 비슷하게 맞추는것이 좋을 것 같아요🙏🏻

- DiaryListVC, DiaryDetailVC
- ListDiaryVC, DetailDiaryVC

2022-09-01 12:05 UTC, yeeton37 commented on Diary/Sources/Views/DiaryTableViewCell.swift
> +    private let diaryTitleLabel: UILabel = {
변경해주었습니다! 😁

2022-09-01 12:13 UTC, yeeton37 commented on Diary/Sources/Views/DiaryTableViewCell.swift
> +    private func setConstraint() {
변경해주었습니다🙏🏻🙏🏻

2022-09-01 12:13 UTC, yeeton37 commented on Diary/Sources/Views/DiaryTableViewCell.swift
> +    func setComponents(item: DiaryContents) {
오, 그렇군요!🙏🏻
저희는 설정하다의 의미로 쓴 것이기 때문에 setupComponents로 변경해주었습니다! 감사합니다

2022-09-01 12:14 UTC, yeeton37 commented on Diary/Sources/Util/Common/Extension/UIViewController + extension.swift
> +        self.present(
앗, 그러네요! 지워주었습니다 😅

2022-09-01 12:17 UTC, yeeton37 commented on Diary/Sources/Models/DiarySample.swift
> +
오..그러게요 🥲 하하 꼼꼼히 확인하는 습관을 들여야겠습니다

2022-09-01 12:23 UTC, yeeton37 commented on Diary/Sources/Controllers/DiaryListTableViewController.swift
> +        view.addSubview(diaryTableView)
옮겨주었습니다 감사합니다!🙏🏻

2022-09-01 12:32 UTC, yeeton37 commented on Diary/Sources/Controllers/DetailDiaryViewController.swift
> +        textView.alwaysBounceVertical = true
앗ㅎㅎ.. 옮겨주었습니다. 정신이 없었네요..🤣

2022-09-01 12:33 UTC, yeeton37 commented on Diary/Sources/Controllers/DetailDiaryViewController.swift
> +        self.present(
특별한 이유는 없습니다... 저희의 불찰일뿐✨ 변경해주었습니다..!

2022-09-01 12:37 UTC, yeeton37 commented on Diary/Sources/Controllers/DetailDiaryViewController.swift
> +        view.addSubview(textView)
오! DetailDiaryViewController도 DiaryListTableViewController와 같은 컨벤션을 적용해주는 것이 좋겠네요, 감사합니다 고쳐주었습니다!

2022-09-01 12:39 UTC, yeeton37 commented on Diary/Sources/Controllers/DetailDiaryViewController.swift
> +final class DetailDiaryViewController: UIViewController, CoreDataProcessing {
`DiaryListVC, DiaryDetailVC` 패턴으로 수정해주었습니다!🙏🏻

2022-09-01 13:14 UTC, seohyeon2 commented on Diary/Sources/Util/Common/Error/CoreDataError.swift
> +enum CoreDataError: Error {
제이크 덕분에 새로운 프로토콜에 대해서 알게되었네요!!ㅎㅎㅎ
공부 후에 저희 프로젝트에 바로 적용해보았습니다ㅎㅎㅎ

2022-09-01 13:17 UTC, yeeton37 commented on Diary/Sources/Views/DiaryTableViewCell.swift
> +    private let diaryTitleLabel: UILabel = {
cell 이름을 통해 유추할 수 있어서 제이크가 말씀해주신 `titleLabel, dateLabel, previewLabel`와 같이 변경해주었습니다 😁

2022-09-01 13:17 UTC, yeeton37 commented on Diary/Sources/AppDelegate.swift
> +    }
저희가 따로 saveContext 메서드를 만들어 주었기에, 불필요한 메서드라고 생각되어 지워주었습니다. 감사합니다!

2022-09-01 13:42 UTC, seohyeon2 commented on Diary/Sources/Controllers/DiaryListTableViewController.swift
> +    override func viewWillAppear(_ animated: Bool) {
super를 호출해야 합니다..!
기존에는 아래와 같은 이유로 호출 하지 않아도 생각했었는데,
제이크의 피드백을 받고 다시 공식문서를 찾아보니 다음과 같은 구절이 있었네요...!
> [If you override this method, you must call super at some point in your implementation.](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621510-viewwillappear/)

앞으로는 더 꼼꼼하게 공식문서를 보도록 하겠습니다!!!!

---

**호출을 하지 않았던 이유**
`UIViewController`의 바로 밑인 하위 뷰에서는 `super`를 호출해 주지 않아도 된다고 알고 있었습니다,,! 
(참고한 링크: [Stack Overflow](https://stackoverflow.com/questions/51816848/remove-super-viewdidload-from-viewdidload-function))
`UIViewController`를 상속받는 VC들은 `final` 키워드를 붙여 상속을 방지해주고 있기도 했고,
Xcode에서도 `super`를 호출해주지 않아도 큰 이슈가 나지않아 호출하지 않았습니다.🥲

2022-09-01 15:13 UTC, seohyeon2 commented on Diary/Sources/Controllers/DiaryListTableViewController.swift
> +        configureSnapshot()
dataSource와 snapshot을 싱글톤으로 변경함에 따라 해당 부분 수정했습니다!

`configureDataSource()`와 `configureSnapshot()`모두 앱이 실행될 때 초기 구성을 하는 로직만 담아놨기 때문에
함수명 그대로`viewDidLoad()`에서 호출되게 위치 변경만 진행했습니다!

2022-09-01 15:13 UTC, seohyeon2 commented on Diary/Sources/Controllers/DiaryListTableViewController.swift
> +        configureDataSource()
넵! 수정했습니다!

2022-09-01 15:16 UTC, seohyeon2 commented on Diary/Sources/Controllers/DiaryListTableViewController.swift
> +        snapshot.deleteAllItems()
제이크 말씀에 동의합니다..!
첨부해주신 링크를 참고하여 해당 코드 삭제했습니다!

참고할 수 있는 링크 주셔서 감사합니다!

2022-09-01 15:23 UTC, seohyeon2 commented on Diary/Sources/Controllers/DiaryListTableViewController.swift
> +            let removableContent = self.snapshot.itemIdentifiers[indexPath.item]
넵! 수정했습니다!!

2022-09-01 15:23 UTC, seohyeon2 commented on Diary/Sources/Controllers/DetailDiaryViewController.swift
> +    override func viewWillAppear(_ animated: Bool) {
수정했습니다!

2022-09-01 15:23 UTC, seohyeon2 commented on Diary/Sources/Controllers/DetailDiaryViewController.swift
> +    }
수정했습니다,,🥲

2022-09-02 01:36 UTC, seohyeon2 commented on Diary/Sources/Controllers/DiaryListTableViewController.swift
> +    }
헉 바로 수정했습니다😭

2022-09-02 04:23 UTC, seohyeon2 commented on Diary/Sources/Controllers/DetailDiaryViewController.swift
> +        }
넵 수정했습니다!

2022-09-02 04:27 UTC, seohyeon2 commented on Diary/Sources/Controllers/DetailDiaryViewController.swift
> +    }
그럴 경우를 대비해서 body에 `textView.text` 내용 전체를 넣어주었습니다.
그래서 189번째 줄을 `textView.text = body` 와 같이 수정했습니다.

2022-09-02 04:32 UTC, seohyeon2 commented on Diary/Sources/Controllers/DetailDiaryViewController.swift
> +    }
알려주신 예시를 참고하여 전반적인 로직을 수정했습니다.
덕분에 좋은 케이스도 알고, UX에 대해 깊이 고민해 볼 수 있었습니다. 감사합니다☺️

2022-09-02 04:34 UTC, seohyeon2 commented on Diary/Sources/Util/Common/Protocol/CoreDataProcessing.swift
> +        diaryContents.body = content[1]
알려주셔서 감사합니다! 
직접 접근 대신 프로퍼티 사용해서 수정했습니다ㅎㅎㅎ

2022-09-02 04:34 UTC, seohyeon2 commented on Diary/Sources/Util/Common/Protocol/CoreDataProcessing.swift
> +        diaryContents.body = content[1]
수정했습니다~

2022-09-02 04:43 UTC, seohyeon2 commented on Diary/Sources/Util/Common/Protocol/CoreDataProcessing.swift
> +protocol CoreDataProcessing { }
따로 인스턴스를 생성하지 않고 바로 프로토콜에 구현된 메서드를 사용하려고 POP 방식을 이용하여 CoreDataProcessing 프로토콜을 구현했습니다!

2022-09-02 04:46 UTC, yeeton37 commented on Diary/Sources/Controllers/DetailDiaryViewController.swift
> +        )
큰 이유 없이 써주었네요...🤔
다른 곳과 컨벤션 통일해주기 위해서 아래와 같이 변경해주었습니다! 
```swift
navigationItem.rightBarButtonItem = UIBarButtonItem(
            image: UIImage(systemName: "ellipsis.circle"),
            style: .plain,
            target: nil,
            action: #selector(showActionSheet)
        )
```

2022-09-02 04:51 UTC, seohyeon2 commented on Diary/Sources/Controllers/DetailDiaryViewController.swift
> +        self.isExist = isExist
`isExist`를 연산 프로퍼티로 수정했습니다!

추가로 다양한 방법 알려주셔서 감사합니다!
다음에 도전해보겠습니다!!

2022-09-03 09:45 UTC, jryoun1 reviewed
@yeeton37 @seohyeon2

수정을 잘 해주셨네요 👍🏻💯
다만 몇가지 궁금한 점이 있습니다.

아래 코멘트에도 남겨두었지만, 제가 생각했을 때는 snapshot, dataSource는 현재 DiaryListTableViewController에서만 사용하고 있기 때문에 해당 vc의 내부에만 존재해도 될 것 같다고 생각하는데, snapshot과 dataSource가 싱글톤이 된 이유가 궁금합니다.

나머지 부분들은 잘 수정해주신 것 같아요 👏

2022-09-03 09:45 UTC, jryoun1 commented on Diary/Sources/Models/DataManager.swift
> +}
싱글톤으로 생성하신 이유가 궁금합니다 🤔
구현하신대로라면 CoreDataProcessing을 준수하면 해당 싱글톤 클래스를 가지게 될 것 같은데 의도하신것이 맞을까요? 

추가로 다른 화면에서 DiaryListTableViewController의 tableView와 동일한 dataSource, snapshot을 공유해야하는 화면이 있는 걸까요? 🤔

2022-09-03 09:45 UTC, jryoun1 commented on Diary/Sources/Controllers/DiaryListTableViewController.swift
> +        let shareAction = UIContextualAction(style: .normal, title: "Share") {  [weak self] _, _, _ in
121번째와는 다른 convention인 것 같아요 🙏🏻

2022-09-06 07:24 UTC, seohyeon2 commented on Diary/Sources/Controllers/DiaryListTableViewController.swift
> +        let shareAction = UIContextualAction(style: .normal, title: "Share") {  [weak self] _, _, _ in
수정햇씁니다..!

2022-09-06 07:24 UTC, seohyeon2 commented on Diary/Sources/Controllers/DiaryDetailViewController.swift
> +        }
수정했습니다..!

2022-09-06 07:25 UTC, yeeton37 commented on Diary/Sources/Controllers/DiaryDetailViewController.swift
> +        view.backgroundColor = .white
저희가  `configureAttributes` 메서드가 불필요하다고 생각되어 제거해주어서 불가피하게 `view.backgroundColor`를 그대로 `configureLayout` 메서드 내부에 쓰게 되었습니다. ㅠㅠ 참고하여 다음 프로젝트때부터는 분리시키도록 하겠습니다!

2022-09-06 07:26 UTC, seohyeon2 commented on Diary/Sources/Util/Common/Protocol/CoreDataProcessing.swift
> +    var dataManager: DataManager { return DataManager.shared }
현재 CoreDataProcessing을 채택하는 VC 모두 dataManager가 필요해서 중복을 없애주기 위해 프로토콜로 넣어주었습니다..!

2022-09-06 07:31 UTC, seohyeon2 commented on Diary/Sources/Util/Common/Protocol/CoreDataProcessing.swift
> +    var dataManager: DataManager { return DataManager.shared }
원래는 CoreDataProcessing이 모든 코어데이터 엔티티에서 사용할 수 있도록 코드를 작성하려고 했는데,

2022-09-06 14:01 UTC, jryoun1 commented on Diary/Sources/Models/DataManager.swift
> +}
🤔 말씀하신대로 DiaryDetailViewController에서도 snapshot에 바로 적용해 줄 수 있을 것 같긴합니다.

그러나 앞으로 모든 CoreDataProcessing을 준수하는 클래스에서 DiaryListTableViewController내부 tableview의 snapshot의 변화를 줄 수 있게 된다면 나중에 오류가 발생했을 때 데이터를 수정할 수 있는 부분이 많기 때문에 찾기 어려울 것 같습니다. 

따라서 CoreData에 create, update는 DiaryDetailViewController에서 해주고, 
DiaryListTableViewController가 매번 나타나는 시점에 CoreData에서 데이터를 fetch해와서 snapshot을 적용시켜준다면 지금과 같이 싱글톤으로 구현하지 않고 DiaryListViewController가 보여질 때마다 최신 데이터를 잘 보여줄 수 있을 것 같네요 🙏🏻

해당 부분은 위에서 말씀하신 
> 나중에 CoreDataProcessing이란 이름에 걸맞게 프레임워크화 시켜보고 해당 프로퍼티도 분리시켜보겠습니다🥲

를 진행하시면서 적용해보시면 좋을 것 같아요 👍🏻

2022-09-06 14:02 UTC, merged