일기장 [STEP 3] Finnn, 수꿍
yagom-academy/ios-diary pull request #52
Opened 2022-08-30 09:03 UTC by Jeon-Minsu

안녕하세요, @GREENOVER!
벌써 마지막 PR이네요 🥲🥲
궁금한 사항에 대하여 아래와 같이 정리해보았습니다!!
이번 스텝도 잘 부탁드립니다!! 🙇‍♂️🙇

---

### STEP 3
    
**현재 사용자의 위치(Core Location)를 기반으로 현재 날씨정보(Open Weather API) 가져오기**
    
    - Open Weather API 데이터를 fetch해오는 WeatherDataAPIManager 정의
    - CLLocationManager 인스턴스를 생성하여 requestLocation 메서드 호출
    - CLLocationManagerDelegate 프로토콜을 통한 Location 업데이트 시
        - WeatherDataAPIManager를 통해 Weather Data 가져오기
        - diary의 main, icon 프로퍼티 할당
   
## 🚀 TroubleShooting

### STEP 3
#### T1. 일기의 `Title`과 `Body` 구분 로직
- `Title`과 `Body`를 구분하는 이전 로직을 검토해본 결과, `Body`가 없이 `Title`로만 일기를 구성하였을 때도, 일기가 저장되는 것이 옳은 일기장 어플리케이션 구현이라고 판단하였습니다. 이러한 생각을 바탕으로, 로직을 수정하던 중, `Body`의 경우 개행이 2번된 경우, 일기장 리스트 화면에서 `Body`의 내용물이 아닌, 개행으로 인한 빈 내용이 표시되는 문제가 발생하였습니다.
    
- 이를 해결하기 위하여 다음과 같이 코드를 수정해보았습니다. 먼저, `diaryContentView` 내 `textView`의 `text`를 옵셔널 바인딩 후, 개행을 기준으로 `split`을 진행하였습니다. 그리고 `split`된 문자열 배열의 첫번째 구성요소는 `title`에 해당할 것이므로, `title`에 담았고, `title` 값이 없을시, `textView`의 값은 유의미한 글자가 없는 값이므로 `nil` 처리를 하여 일기를 `save`하지 않도록 처리하였습니다. 그리고 만일 `splitText`의 `count`가 1보다 크지 않으면, 선행 조건에서 이어진 경우이기에, `count`가 1인 경우이므로, `title`만 있는 경우이기에 `(String(title), DiaryCoreData.emptyBody)`로 타이틀과 빈 바디를 반환하였습니다. 그리고 전체 `diaryConentViewText`에서 `body`가 시작되는 인덱스부터를 범위로 삼아 `body`를 추출하였습니다.

- 코드
```swift
private func extractTitleAndBody() -> (String, String)? {
    guard let diaryConentViewText = diaryContentView.textView.text else {
        return nil
    }
    
    let splitedText = diaryConentViewText.split(separator: NewLine.lineFeed)
    
    guard let title = splitedText.first else {
        return nil
    }
    
    guard splitedText.count > 1 else {
        return (String(title), DiaryCoreData.emptyBody)
    }
    
    let body = diaryConentViewText[splitedText[1].startIndex...]
    
    return (String(title), String(body))
}
```

## 3️⃣ STEP 3
    
### STEP 3 Questions

#### Q1. 시뮬레이터에서 Location 변경시 정상적으로 적용되지 않는 문제
- 이번 프로젝트를 진행하면서 `CoreLocation`으로 사용자에게 위치 정보를 받아오는 요구사항이 있었습니다.
- 위치가 제대로 들어가는지 확인하기 위해서 `Simulator`에서 `location`을 변경해봤지만, 변경된 위치가 들어가지 않고, 이 전에 설정했던 위치가 계속 들어갔습니다.
- 그런데 정말 이상하게도 아이폰 기본 지도 앱을 한번 실행한 후 다시 테스트를 했을때는 `Location`을 변경해줬을때 바로바로 적용이 되었습니다.

![](https://i.imgur.com/oAmI4Ea.png)

![](https://i.imgur.com/QxV7koj.png)

- ⬆️ 해당 메뉴에서 위치를 변경해도 `Simulator`에서는 바로 적용되지 않는 문제가 발생했습니다.
- 단순히 애플 기본 지도 앱을 실행 후 종료해주는 것 만으로 해결되었습니다.
- 올바른 해결방법이 아니라는 생각이 들어 혹시 원인을 아시는지 궁금합니다 🤔
    
#### Q2. 서버에서 데이터를 받아오고 있는 중인지 체크하는 법
- save 기능이 구현된 메서드가 호출되면 `Weather` 아이콘을 인터넷에서 받아오고 있습니다.
- 하지만 이전 프로젝트 구현 사항으로 일기장의 저장 경우의 수는 일기장 목록으로 되돌아갈 때, 백그라운드에 들어갈 때, 키보드가 내려갈 때로, 총 3가지 경우입니다.
- 그런데 일기장 목록으로 되돌아가면 이미 show 되고 있는 키보드 또한 자동으로 hide되기 때문에 중복하여 메서드가 호출됩니다. 
- 이전에는 분기 처리를 통하여 해결하였는데, 이번에는 이 과정에서 서버와의 지연으로 인해 분기 처리가 정상적으로 이루어지지 않아 두 세번 저장 메서드가 호출되는 현상이 발생하였습니다.
- 이로 인한 중복 저장을 막기 위해서 `isFetching` 프로퍼티를 정의해서 현재 데이터를 받아오고 있는 중인지 아닌지 확인할 수 있도록 했습니다.
- 다만, 이렇게 확인하는 방식이 효율적인지에 대한 의문이 들어, 혹시 데이터가 현재 통신중인지 여부를 체크할 수 있는 더 좋은 방법이 있는지 알고 싶습니다. ☺️

- **기존 코드:**
```swift
WeatherImageAPIManager(icon: icon)?.requestImage(id: id) { [weak self] result in
    switch result {
    case .success(let image):
        do {
            try CoreDataManager.shared.saveDiary(
                title: title,
                body: body,
                createdAt: creationDate,
                id: id,
                main: main,
                icon: icon,
                image: image
            )
        } catch {
            self?.presentErrorAlert(error)
        }
    case .failure(let error):
        self?.presentErrorAlert(error)
    }
}
```

- **수정 코드:**
```swift
if isFetching == false {
    isFetching = true
    WeatherImageAPIManager(icon: icon)?.requestImage(id: id) { [weak self] result in
        switch result {
        case .success(let image):
            do {
                try CoreDataManager.shared.saveDiary(
                    title: title,
                    body: body,
                    createdAt: creationDate,
                    id: id,
                    main: main,
                    icon: icon,
                    image: image
                )
            } catch {
                self?.presentErrorAlert(error)
            }
        case .failure(let error):
            self?.presentErrorAlert(error)
        }
        self?.isFetching = false
    }
}
```

2022-08-30 10:51 UTC, GREENOVER commented
@Jeon-Minsu @finnn1 
혹시 시뮬레이터 캐시를 다 날리고 테스트 해보실 수 있나요~?
우선 코드 리뷰 전에 저는 클린한 상태에서 QA를 해보는데 아래와 같이 일기 저장이 되지 않습니다😭
https://user-images.githubusercontent.com/72292617/187418454-20af27db-6997-483c-8b70-e6a1130e5ead.mp4

2022-08-30 10:53 UTC, GREENOVER commented
영상 크기가 커 디코로 공유드리겠습니다!

2022-08-31 08:26 UTC, GREENOVER requested changes
@Jeon-Minsu @finnn1 
두분 이번 스텝3도 고생 많으셨습니다!
제출 후 중간중간 변경 사항이 많았는데 빠르고 아주 잘 처리해주셨어요👍
전체적으로 빠듯한 일정에 잘 달려오셔서 보너스 스텝 제외하고 마무리를 앞두고 계신 여러분 아주 대단합니다ㅎㅎ
그럼 유종의 미를 거두기 위해 빠르게 리뷰를 드려보고 욕심을 내 보너스 스텝까지 한번 가보면 좋겠네요🙌
***
### 칭찬 드리고 싶은 부분
- 전체적인 파일 구조가 너무 좋아졌습니다 💯
- 사용자 경험에 친화적인 얼럿 모달을 적절히 체크하여 노출 시키는 점 💯
- 적절하고 세밀한 작은 단위의 커밋 이력 관리를 통해 흐름 파악에 용이한 점 💯
- 객체지향적인 코드 구현을 위해 메서드의 소통을 최대한으로 구현 해주신 점 💯
***
### 궁금하신 부분에 대한 저의 의견
1. 시뮬레이터에서 Location 변경시 정상적으로 적용되지 않는 문제
- 음 우선 저는 해당 말씀하신것의 문제를 겪지 않았어요.
즉 겪은 문제가 애플 지도 앱하고는 관련이 없지 않을까 싶어요!
만약 문제가 있었다면 두가지로 추정해볼 수 있을것 같습니다.
첫번째는 시뮬레이터 오류일것 같은데 시뮬레이터가 완벽하지 않고 너무... 네.. 문제가 많습니다.
두번째는 해당 Location 변경은 바로 되겠지만 위치를 가지고 날씨 데이터를 수집 동의를 묻거나 이후 실제로 통신하는 구현들이
정상적으로 호출되고 진행되는지 의심해볼 수 있을것 같아요.
이 부분도 의심이 된다면 디버깅 해보면 어떨까요?
그런데 저는 아마 첫번째의 느낌이 강해요..!
완전 클린한 상태에서 여러분들이 안되었던 문제 스텝대로 진행해봤는데 아래 화면처럼 정상적이였어서 한번 여러분들도 클린한 상태에서 다시 시도해보시면 좋을것 같습니다🙌
![test](https://user-images.githubusercontent.com/72292617/187629244-4d51ecaf-4dce-462d-869d-1f2b389e81ff.gif)
2. 서버에서 데이터를 받아오고 있는 중인지 체크하는 법
- 요 부분은 현재 사용되는 기술 스택 및 구조에서는 좋은 방법이라고도 생각합니다!
다른 방법에 대해 생각해본다면 Semaphore나 Notification도 하나의 방법이 될 수 있겠는데 이 부분도 모두 하나의 프로퍼티를 두긴 해야되서 관심사 분리는 잘 될 수 있겠지만 오버 엔지니어링이 될 수 있지 않을까 생각이 들어요🥲
그럼으로 현재 방법 저는 좋은데 리팩토링 하시는 동안 더 괜찮은 방법을 같이 고민해볼께요!
***
### 보완되면 좋을 부분들
1. 일기 타이틀 상단이 절삭되어 보이는 현상
- 한글로 일기 타이틀 작성 후 확인 시 아래와 같이 Title 부분이 정상적이지 않고 잘려보여요🥲
어떤 문제인지 확인 해보고 수정되면 좋을것 같습니다!
![1](https://user-images.githubusercontent.com/72292617/187630488-cbdf4c4e-b85c-4930-a725-738263c2fd13.png)
2. 위치 정보가 없어 날씨를 못받아 오는 상황에서 일기 작성이 되는 현상
- 제목과 같이 위치 정보 수신이 안된다는 실패 얼럿이 노출되고 확인 시 뒤로 나가지는게 아닌 일기 작성을 이어서 할 수 있게 됩니다.
그런 상황에서 작성 후 뒤로 가기 클릭 시 아래와 같이 얼럿이 뜨고 나가지지 않습니다.
이에 아예 위치 정보 수신이 되지 않는다는 얼럿이 노출되면 아예 일기 작성이 이뤄질 수 없도록 뒤로 빠져나가거나 아니면 날씨는 옵셔널하게 가져가서 날씨가 꼭 입력 되지 않더라도 일기가 작성 되는데 문제가 없다면 어떨까요?
저는 개인적으로 날씨는 옵셔널한게 사용자 경험에 더 좋지 않을까 해요.
위치를 못받아서 날씨 아이콘은 제공되지 않아도 일기는 작성되는게 보통적인 앱이 아닐까 생각이 듭니다🤔
![Simulator Screen Shot - iPhone 11 - 2022-08-31 at 16 55 53](https://user-images.githubusercontent.com/72292617/187631502-9a420fe6-97f6-4045-90de-debc1210c61f.png)
***
다시 한번 수고 많으셨습니다!
정말 조금의 완성도를 위해 많은 작업을 하는게 힘드실텐데 아주 잘 해주고 계세요ㅎㅎ
우선 아주아주 조금의 완성도를 끌어올리기 위해 마지막 리팩토링을 할 수 있도록 Request Changes로 남기겠습니다!
사용자 측면에서 기능적인 완성도만 보완되면 좋겠습니다🙌
언제든 재 리뷰 요청해주세요..!
화이팅입니다😃

2022-08-31 08:26 UTC, GREENOVER commented on Diary/Resources/URLComponentsBuilder.swift
> +    init() { }
어떨때 필요한 코드인가요~?🙋🏻

2022-09-01 07:21 UTC, Jeon-Minsu commented on Diary/Resources/API/APIProtocol/GETProtocol.swift
> +            case .failure(_):
해당 변수를 사용하는 것이 아니면 차이가 없다고 생각합니다!
이에 `case .failure:`로 수정완료하였습니다!

2022-09-01 07:22 UTC, finnn1 commented on Diary/Resources/API/APIProtocol/GETProtocol.swift
> +    func requestAndDecodeWeather<T: Decodable>(using client: APIClient = APIClient.shared,
해당 메서드명을 `requestWeather`으로 변경해주었습니다!
감사합니다 🙏

2022-09-01 07:25 UTC, finnn1 commented on Diary/Controllers/DiaryContentsViewController.swift
> +    private var icon: String?
앗 그렇네요..!
`main`을 `weatherMainData`로, `icon`을 `weatheIcon`으로 변경해주었습니다 ☺️

2022-09-01 07:25 UTC, finnn1 commented on Diary/Namespaces/HTTPMethod.swift
> +}
감사합니다 🙏🙏

2022-09-01 07:28 UTC, finnn1 commented on Diary/Resources/CoreData/Diary+CoreDataProperties.swift
> +    @NSManaged public var image: UIImage
이 부분도 `main`을 `weatherMainData`로, `icon`을 `weatherIcon`으로, `image`를 `weatherIconImage`로 변경해주었습니다! ☺️

2022-09-01 07:39 UTC, Jeon-Minsu commented on Diary/Resources/API/APIConfiguration.swift
> +
컨벤션 통일했습니다!

2022-09-01 08:04 UTC, Jeon-Minsu commented on Diary/Error/APIError.swift
> +    var errorDescription: String {
해당 APIError 관련하여 GETProtocol의 requestWeather 메서드와 requestImage 메서드의 failure 경우에 사용해보았습니다!

2022-09-01 08:17 UTC, Jeon-Minsu commented on Diary/Error/APIError.swift
> +    var errorDescription: String {
추가로, localizedDescription을 재정의하기 위해서, LocalizedError 프로토콜을 준수하고 errorDescription 연산 프로퍼티 정의하여야 한다고 알고 있습니다. 이에 errorDescription이 아닌 localizedDescription으로 실제 호출을 하고 있습니다! 혹시 잘못 이해한 부분이 있으면 알려주실 수 있을까요?? 🥹🥹

2022-09-01 08:18 UTC, Jeon-Minsu commented on Diary/Error/GPSError.swift
> +    var errorDescription: String? {
위의 답변에서 언급한 바와 같이, localizedDescription을 재정의하기 위해서, LocalizedError 프로토콜을 준수하고 errorDescription 연산 프로퍼티 정의하였습니다!!

2022-09-01 08:24 UTC, Jeon-Minsu commented on Diary/Resources/API/APIProtocol/GETProtocol.swift
> +protocol GETProtocol: APIProtocol { }
Get만을 명시하면 직관적으로 이해하기 어렵다고 판단하여, Protocol이란 접미사를 활용해보았습니다. 하지만 이를 다시 생각해본 결과, protocol 접미사를 사용하는 것이 best option일 가능성이 현저히 적을 수 있다는 이슈를 발견하였습니다. 이에, 명사형 네이밍과 형용사형 네이밍을 고려해보아, GETProtocol -> Getable, APIProtocol -> API로 수정해보았습니다!

2022-09-01 08:24 UTC, finnn1 commented on Diary/Controllers/DiaryContentsViewController.swift
>      private func extractTitleAndBody() -> (String, String)? {
감사합니다 🙏

2022-09-01 08:27 UTC, finnn1 commented on Diary/Controllers/DiaryContentsViewController.swift
> +        if isFetching == false {
느낌표를 붙이는 것이 가독성이나 이해도 측면에서 좋지 않다는 이야기를 들어서 `isFetching == false` 로 명시해주었던 것인데, 혹시나 상관이 없다면 `!isFetching`처럼 사용하는 것도 크게 상관없다면 코드가 간결하고 깔끔해져서 더 좋은 것 같습니다! ☺️👍

2022-09-01 08:32 UTC, finnn1 commented on Diary/Controllers/DiaryContentsViewController.swift
> +            isFetching = true
`isFetching == false`로 검사가 되기때문에 바로 아래에서는 `toggle`로 줄 수 있겠네요!
`toggle`을 사용하는 방식으로 변경했습니다 ☺️
`isFetching`이 사용되고 있는 다른 부분은 서버로부터 네트워킹과 같은 다양한 상황이 있기 때문에 사이드이펙트가 우려되어 `toggle`보다는 확실한 값이 대입되는 것을 보장할 수 있도록 직접 `true` or `false` 값을 대입해주는 방식으로 유지했습니다.
감사합니다! 🙏

2022-09-01 08:35 UTC, finnn1 commented on Diary/Controllers/DiaryContentsViewController.swift
> +    private func determineDataProcessingWith(_ title: String, _ body: String, _ creationDate: Date, _ id: UUID, _ main: String, _ icon: String) throws {
개행을 줌으로써 가독성을 높히고, 언더스코어를 삭제해서 사용하는 쪽에서 헷갈리지 않도록 해주었습니다 ☺️

2022-09-01 08:37 UTC, finnn1 commented on Diary/Resources/URLComponentsBuilder.swift
> +    init() { }
`urlComponents` 를 직접 생성해서 할당해주기 때문에 이니셜라이저는 필요없을 것 같습니다!
해당 라인 삭제해주었습니다 ☺️

2022-09-01 09:12 UTC, finnn1 commented
안녕하세요 그린! 말씀해주신 부분 리팩토링 완료했습니다 ☺️
확인해주시면 감사하겠습니다..! 🙏

## 일기 타이틀 상단이 절삭되어 보이는 현상
해당 부분은 `Title String` 값 끝에 공백(" ")이 없을 경우 잘리는 현상이 발생하는 것을 확인했습니다.
당장은 `Title String` 값 뒤에 공백을 넣어주는 것으로 해결했지만, 정상적인 해결방법이 아니라는 생각이 들었습니다.
저희 한계로 인해 공백 여부 때문에 글씨가 잘리고 안잘리는 현상이 왜 발생하는지 알지 못해 혹시 원인을 아시는지 궁금합니다... 🥲🙏

## 위치 정보가 없어 날씨를 못받아 오는 상황에서 일기 작성이 되는 현상
해당 부분은 그린이 말씀해주신대로 위치 정보가 없을 경우 날씨 데이터를 제외하고 저장하는 방식으로 변경했습니다!
감사합니다 🙏

2022-09-01 10:42 UTC, GREENOVER commented on Diary/Error/APIError.swift
> +    var errorDescription: String {
@Jeon-Minsu 
앗 아닙니다! 잘 이해하셨고 제가 놓친 부분이네요ㅠㅠ
번거롭게 오해를 하게 해드려 죄송합니다🙇🏻

2022-09-01 11:16 UTC, GREENOVER approved these changes
두분 너무 고생 많으셨어요 스텝3까지 아주 잘 완주하셨네요👍👍👍
이번 스텝3도 특히 더 요구사항은 물론이고 여러 에러 케이스들까지 잘 처리하면서 아주 완벽해졌네요!
당연히 어프로브 > 머지 하겠습니다ㅎㅎ
이후 보너스 스텝의 선택은 정말 자유입니다~!
부담 갖지 않고 편하게 하셔도 되고 아니면 다른 밀렸던 프로젝트나 학습에 몰입해보셔도 좋을것 같아요🙌
검색 기능도 사실 보너스 스텝에 있는건데 이미 해주셔서 아주 최고네요!
그럼 하나 정도 리뷰를 드리면서 질문하신 사항에 대한 답변도 해보겠습니다..!
***
- 타이틀만 존재 시 절삭되는 현상
  - 요 부분은 뷰 디버깅을 해보시면 text를 감싼 textContainer의 영역에 글자가 딱 붙어 실제로는 네비게이션바에 가리는게 아닌 최상단에 붙어버려서 절삭되어 보이는걸로 나타납니다.
  이 부분은 textContainerInset을 학습해보셔서 적용하시면 정상적으로 노출될거에요😃
***
다시 한번 3주간 너무 프로젝트를 퀄 좋게 수행해주셔서 저도 많이 배웠습니다!
이제는 현업에서 곧 뵙겠네요!ㅋㅋ
리뷰어가 아니더라도 편하게 자주 소통해요ㅎㅎ
다음 프로젝트도 화이팅입니다🥳🥳

2022-09-01 11:17 UTC, merged