일기장 [Step3] unchain, 웡빙
yagom-academy/ios-diary pull request #56
Opened 2022-09-02 06:54 UTC by unchain123

@leejun6694 @wongbingg
안녕하세요 쿠마 마지막 pr입니다.
잘부탁드릴게요 !!

# 일기장 STEP 3 PR
###### tags: `PR`

## 📁 FileTree
```
└── Diary
    ├── Network
    │   ├── NetworkManager
    │   └── URLData
    ├── CoreData
    │   ├── Diary+CoreDataClass
    │   ├── Diary+CoreDataProperties
    │   └── CoreDataManager
    ├── DiaryList
    │   ├── DiaryListView
    │   ├── DiaryListViewController
    │   └── DiaryListCell
    ├── Diary
    │   ├── DiaryView
    │   ├── DiaryViewController
    │   ├── AlertManager
    │   └── MyActivityItemSource
    ├── Model
    │   ├── DiaryModel
    │   ├── JsonPaser
    │   ├── NameSpace
    │   └── PageMode
    ├── Extensions
    │   ├── TimeInterval+Extension
    │   ├── Notification.Name+Extension
    │   └── UIImageView+Extension
    ├── AppDelegate
    ├── SceneDelegate
    ├── Info.plist
    └── Diary.xcdatamodeld
```
## 💻 구현사항

### 구동화면

| 새로운 일기생성 | 새로운 일기생성2 | 
|:---:|:---:|
|<img src = "https://i.imgur.com/IAIGOOl.gif" width="250" height="500">|<img src = "https://i.imgur.com/ZpEvaQG.gif" width="250" height="500">|

### 공통
**- SwiftLint 적용** O
**- 가로/세로 모드 모두 대응가능** O
**- UI는 모두 코드를 통해 구현** O

### STEP 3
**- OpenWeatherAPI와 네트워크 통신**
- 네트워킹 모델 WeatherModel 구현
    - main, iconId 값을 받아오도록 설정
- CLLocationManager를 이용하여 현위치의 위도, 경도값 파악
    - 위도, 경도값을 쿼리아이템으로 사용하여 네트워킹 요청
- light 마이그레이션
    - 기존의 entity에 attribute가 추가된 새로운 데이터모델 생성
    - 새로운 Diary 2 코어데이터를 추가하여 기존의 데이터에 맵핑
    - NSManagedObject 프로퍼티에 추가
- 받아온 iconId값을 이용하여 icon 이미지를 받아오는 네트워킹 코드 작성
    - 받아온 이미지를 dateLabel 과 previewLabel 사이에 imageView로 추가

## 🛠 Trouble Shooting
### 코어데이터 마이그레이션 했을 때 문제
- 코어데이터 모델에서 날씨 아이콘을 추가 시키기 위해서 코어데이터 마이그레이션을 사용했습니다.
- 마이그레이션으로 Diary2로 맵핑모델도 만들어주니 날씨 아이콘을 사용할 수 는 있었지만 다음과 같이 이전 버전에서 만들어 주었던 코어데이터에 저장되어 있던 셀에 오류가 생겼습니다. 이전의 데이터들이 무작위로 섞이기도하고 문제1 처럼 없어지기도 했습니다.
- 또 발견된 사항으로는 첫번째 데이터는 저장이 되지 않고 그 다음부터 저장이 되기도 했습니다. 마이그레이션 과정에서 어떤 문제가 있었던건지 마이그레이션을 하게 되면 원래 여러 문제가 발생할 가능성이 있는건지 궁금합니다. 이 오류를 아직 확실하게 해결하지 못했습니다.

|문제 1|문제 2|
|:--:|:--:|
|<img src = "https://i.imgur.com/tMg8O3Q.png" width=200, height=400>|<img src = "https://i.imgur.com/XGm5geJ.png" width=250, height=400>|

### AlertController 분리

DiaryViewController에 AlerController 생성 코드가 차지하는 비중이 높아 가독성을 떨어뜨린다고 판단하여, 파일을 AlertManager로 따로 분리 해주었습니다. 이렇게 분리하여 사용하게 되면 AlertManager가 파라미터로 DiaryViewController를 받게되는데 바람직한 구조인지 궁금합니다 !!

### textView.text 가 mainThread에서 ?

textView.text를 가져오는 과정이 mainThread에서 실행되어야 한다는 오류가 떳는데, 이유를 모르겠어서 스택오버플로우 검색 결과 신경쓰지 않아도 된다는 내용이 있었습니다! 이 경우가 어떤 경우인지 궁금하여 질문 드립니다!
![](https://i.imgur.com/oQ4P8YN.jpg)

2022-09-03 16:05 UTC, leejun6694 commented on Diary/CoreData/CoreDataManager.swift
> +    private(set) var fetchedDiaries: [Diary] = []
적절한 줄바꿈은 가독성에 도움이 될 것 같습니다 : )

2022-09-03 16:05 UTC, leejun6694 commented on Diary/CoreData/CoreDataManager.swift
> +protocol CoreDataManagerDelegate: AnyObject {
delegate 로 처리하는 방법을 참고한 자료가 있으실까요??

2022-09-03 16:08 UTC, leejun6694 commented on Diary/CoreData/CoreDataManager.swift
> +            DispatchQueue.main.async { [weak self] in
main thread 에서 처리해야하는 이유가 있을까요?

2022-09-03 16:17 UTC, leejun6694 commented on Diary/Diary/AlertManager.swift
> +    private func generateDeleteAlertAction(in viewController: DiaryViewController ) -> UIAlertAction {
띄어쓰기..!

2022-09-03 16:19 UTC, leejun6694 commented on Diary/Diary/AlertManager.swift
> +        showAlertController(title: nil,
alert view controller 을 만드는 부분을 분리하고 싶었다면, 만들고 전달해주면 어떨까요?
completion 이 중첩되고 있어서 조금은 난해한 코드가 되지 않았나 싶습니다.

2022-09-03 16:20 UTC, leejun6694 commented on Diary/Diary/DiaryViewController.swift
> +            navigationItem.rightBarButtonItem = UIBarButtonItem(image: UIImage(systemName: SystemName.moreViewIcon),
요렇게 줄바꿈이 뒤에서 발생하는 케이스들이 있어서, 저는 첫번째 파라미터부터 줄바꿈을 해주는 편입니다ㅎㅎ
참고만 해주세요!

2022-09-03 16:22 UTC, leejun6694 commented on Diary/Diary/DiaryViewController.swift
> +        switch diary == nil {
boolean 처리가 switch 로 되어있는 것은 생소하네요ㅎㅎ

2022-09-03 16:23 UTC, leejun6694 commented on Diary/Diary/DiaryViewController.swift
> +            let diaryModel = self.makeDiaryModel(with: data.weather[0].icon)
self 가 없다면 어떤 일이 발생할까요?

2022-09-03 16:24 UTC, leejun6694 commented on Diary/Diary/DiaryViewController.swift
> +            location["lat"] = String(coordinate.latitude)
lat, lon 이 자주쓰이는 string 값인데, 한곳에서 정의해서 사용하면 어떨까요?

2022-09-03 16:26 UTC, leejun6694 commented on Diary/Extensions/UIImageView+Extension.swift
> +    func requestWeatherImage(iconId: String) {
requestWeatherImage method 의 사용 범위가 모든 UIImageView 를 대상으로 해야할까요?
View 에서 network 로직이 진행되는 것도 어색한 것 같습니다 : )

2022-09-03 16:27 UTC, leejun6694 requested changes
안녕하세요 unchain, 웡빙!
step 3 도 구현하느라 고생 많으셨습니다 : )
network 관련 코드는 일반적인 manager 가 아닌, 이번 프로젝트만을 위한 코드로 간단하게 구현한 것인지 궁금합니다~!

2022-09-03 16:32 UTC, leejun6694 commented
> 코어데이터 마이그레이션 했을 때 문제

요건 같이 확인을 해봐야할 것 같네요...!

> AlertController 분리

따로 분리해주신 것은 좋지만, 생성만 하고 리턴 값으로 넘겨주는 방법도 있을 것 같습니다ㅎㅎ
(지금처럼 view controller 를 넘겨주는 방법도 사용하는 예시를 봤었습니다~!)
리뷰드린 것처럼 completion 이 여러번 사용되는 부분은 확인 부탁드려요~

> textView.text 가 mainThread에서 ?

makeDiaryModel method 가 불리는 곳이 어떤 곳인지 다시 한번 확인이 필요할 것 같습니다.
음.. 문제가 되는 부분을 parameter 로 받는 것은 어떨까요?

2022-09-04 13:18 UTC, wongbingg commented on Diary/CoreData/CoreDataManager.swift
> +protocol CoreDataManagerDelegate: AnyObject {
따로 참고한 자료없이 배웠던 대로 구현을 해보았습니다! 네이밍이나 기능적으로 혹시 더 나은 방법이 있을까요 ?!

2022-09-04 13:19 UTC, unchain123 commented on Diary/CoreData/CoreDataManager.swift
> +    private(set) var fetchedDiaries: [Diary] = []
계산프로퍼티와 저장프로퍼티 사이에 줄바꿈을 줬습니다. 이 부분이 생각하신 부분이 맞으실까요?

2022-09-04 13:19 UTC, unchain123 commented on Diary/Diary/AlertManager.swift
> +    private func generateDeleteAlertAction(in viewController: DiaryViewController ) -> UIAlertAction {
아..Lint에게 배신을 당했습니다. 바로 삭제했습니다.

2022-09-04 13:21 UTC, wongbingg commented on Diary/Diary/DiaryViewController.swift
> +        switch diary == nil {
불필요하게 들어간 부분이 있었군요! ㅎㅎ if 문으로 처리를 해주도록 수정했습니다 !

2022-09-04 13:26 UTC, wongbingg commented on Diary/Diary/DiaryViewController.swift
> +            location["lat"] = String(coordinate.latitude)
해당 클래스 내에 private enum으로 네임스페이스를 생성해주어 처리 했습니다!ㅎㅎ

2022-09-04 13:31 UTC, wongbingg commented on Diary/CoreData/CoreDataManager.swift
> +            DispatchQueue.main.async { [weak self] in
delegate를 통해 실행되는 메서드가 tableView.reload() 인데, UI가 업데이트 되는 작업은 mainThread 에서만 실행이 가능하다고 알고 있어서 이렇게 처리를 해 주었습니다!

2022-09-04 13:57 UTC, unchain123 commented on Diary/Extensions/UIImageView+Extension.swift
> +    func requestWeatherImage(iconId: String) {
requestWeatherImage 메서드가 UIImageView에 범용적으로 적용시키기 위해 작성했었습니다. 다시 보니 어색한 것 같아서 다시 Networkmanger의 메서드로 변경해주었습니다.

2022-09-04 13:59 UTC, wongbingg commented on Diary/Diary/DiaryViewController.swift
> +            let diaryModel = self.makeDiaryModel(with: data.weather[0].icon)
[weak self]로 캡쳐하지 않을 경우는 
1. 클로저 안에서 암시적 self 를 명시해주기 위해 캡쳐리스트로`[self] in`표현해주거나, 
2. 클로저 안에서 self 참조를 통해 `self.` 으로 접근하는 방식
두개 중 하나만 써도 된다는 것을 알았습니다 ! 하지만 이런 경우에도 [weak self ] 처리를 해주는 것이 좋을까요 ?

2022-09-04 14:05 UTC, wongbingg commented on Diary/Diary/AlertManager.swift
> +        showAlertController(title: nil,
어떤 말씀이신지 아직 이해가 잘 되지 않습니다..ㅎㅎ 혹시 이부분 다시 설명 해주실 수 있을까요 !?🥲🥲

2022-10-06 09:00 UTC, closed without merging