다이어리 [STEP 1] 썸캣, 솜
yagom-academy/ios-diary pull request #59
Opened 2022-12-20 13:57 UTC by dev-summer

안녕하세요, 올라프(@1Consumption)! 
다이어리 Step 1 구현이 완료되어 PR 보냅니다.
(리뷰 강도는 5로 부탁드립니다 ㅎㅎ - 솜)

## 고민했던 점

### 1. 제목 텍스트뷰의 intrinsic content size에 제목 텍스트뷰 크기 맞추기
`titleTextView`와 `bodyTextView`를 mainStackView에 추가했을 때, `titleTextView`만 크기가 상위 뷰의 전체 크기만큼 나오는 오류가 있었습니다. textView 크기 설정 관련으로 서치하여 `isScrollEnabled` 프로퍼티의 값을 `false`로 설정해 `titleTextView`의 크기가 해당 뷰의 intrinsic content size와 동일한 크기를 갖도록 설정할 수 있었습니다. [참고 블로그](https://medium.com/macoclock/auto-resizing-dynamic-uitextview-97d151e59ca0)

### 2. 텍스트뷰에 입력할 때 키보드가 텍스트뷰를 가리지 않도록 하기

요구사항 중 `편집중인 텍스트가 키보드에 의해 가리지 않도록 합니다`를 구현할 수 있는 방법은 크게 두가지가 있습니다.
1. 키보드의 높이를 계산해서 키보드가 나타났을 때 키보드의 높이만큼 뷰의 `origin`을 위로 올리는 방법
2. `UIKeyboardLayoutGuide`를 사용하는 방법 (iOS 15 이후 버전에서 지원)

저희는 새로운 기능을 사용해보기 위해 Deployment Target을 15.2로 설정하고, 2번 방법을 채택했습니다.

### 3. 뷰의 마진 설정하기

기존에는 각 뷰의 anchor에 constant 값을 주는 방법을 활용해서 각 뷰 바깥의 여백을 설정했습니다. 이번 프로젝트에서는 캠핑 사이트의 참고자료 [WWDC18 - UIKit: Apps for Every Size and Shape](https://developer.apple.com/videos/play/wwdc2018/235/)를 보고, 뷰에 마진을 주는 방법을 활용해보았습니다.
기존 방식과 다른 점은 뷰의 크기 자체가 줄어드는 것이 아니라, 뷰 내에서 콘텐트를 표현하는 부분의 크기가 마진만큼 줄어든다는 차이점이 있습니다 (뷰 경계에서 시작해서 뷰 안쪽으로 마진이 생기는 개념).
ViewController의 rootView에는 safeArea가 있기 때문에 rootView에 직접 설정한 마진의 값이 UIKit이 safeArea를 잡기 위해 설정한 마진보다 작을 경우, layoutMargin의 값이 적용되지 않고 safeArea의 마진의 값이 적용됩니다. 그래서 `RegisterVC`의 경우 `mainStackView`에 마진을 적용해서 `titleTextView`와 `bodyTextView`에 바깥쪽 여백을 주었습니다.

---

## 조언을 얻고 싶은 부분

1. **프로젝트 폴더 정리 (MVC 역할별 정리 vs 화면별 정리)**
    - `LaunchScreen`은 view 폴더에 넣어야 할까요?
    - 향후 앱의 규모가 커진다면 MVC 역할별로 폴더를 나누는 게 편리할지, 화면별로 폴더를 나누는 것이 편리할지 올라프의 의견이 궁금합니다.

2. **콘텐트 바깥에 여백을 주고 싶을 경우, 해당 뷰에 constant 설정하기 vs 상위 뷰에 layoutMargin 또는 edgeInset 설정하기**
    - 가독성 측면에서는 상위 뷰에 layoutMargin을 설정하는 것이 좋아보이지만, 기능적으로는 어느 방법이 더 좋을까요?

---

## 참고링크

### 공식문서
[DateFormatter](https://developer.apple.com/documentation/foundation/dateformatter)

### 블로그/기타
[Move a View Up Only When the Keyboard Covers the Input Field - StackOverflow](https://stackoverflow.com/questions/28813339/move-a-view-up-only-when-the-keyboard-covers-an-input-field)
[UIKeyboardLayoutGuide - Zedd 블로그](https://zeddios.tistory.com/1282)
[UITableView Register Cell Identifier - StackOverflow](https://stackoverflow.com/questions/29282447/unable-to-dequeue-a-cell-with-identifier-cell-must-register-a-nib-or-a-class-f)
[Safe Area와 Layout Margin](https://woozzang.tistory.com/147)
[UIStackView layoutMargin 적용하기](https://velog.io/@dvhuni/UIStackView-Margin-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0)
[How to add leading padding to view added inside an UIStackView - StackOverflow](https://stackoverflow.com/questions/32551890/how-to-add-leading-padding-to-view-added-inside-an-uistackview)

2022-12-20 16:38 UTC, 1Consumption requested changes
고생하셨습니다 @dev-summer @jsa0224 
전반적으로 컨벤션이 일정하고 가독성이 좋은 코드였습니다.
또한 고민한 흔적이 보여서 좋았습니다.

다만 아직 커밋을 나누는 부분이 아쉽다고 느껴집니다.
커밋은 한번에 하나의 역할만 해야합니다. 그런데 지금은 하나의 커밋이 종종 여러개의 역할을 하고있어요.
또한 커밋 메세지도 아쉽습니다. 커밋 메세지에는 `~~를 했다` 뿐만 아닌 `왜`가 간략하게 들어가면 좋겠어요.

아래는 고민하신 점에 대한 제 코멘트입니다.

> `LaunchScreen`은 view 폴더에 넣어야 할까요?

왜 이 고민을 했는지 궁금합니다. 이부분에 대한 답변을 해주시면 그 답변에 대한 제 생각을 말씀드릴게요.

> 향후 앱의 규모가 커진다면 MVC 역할별로 폴더를 나누는 게 편리할지, 화면별로 폴더를 나누는 것이 편리할지 올라프의 의견이 궁금합니다.

왜 이 고민을 했는지 또한 궁금합니다. 질문에는 배경이 있으면 좋겠어요.
저는 화면별로 나누는 편입니다. 보여주고싶은 데이터와 그 로직은 결국 화면에 종속된다고 생각하기 때문입니다.

> **콘텐트 바깥에 여백을 주고 싶을 경우, 해당 뷰에 constant 설정하기 vs 상위 뷰에 layoutMargin 또는 edgeInset 설정하기**
    - 가독성 측면에서는 상위 뷰에 layoutMargin을 설정하는 것이 좋아보이지만, 기능적으로는 어느 방법이 더 좋을까요?

가독성 측면에서는 왜 상위뷰에 margin을 주는게 낫나요?
저는 이 고민을 조금 다르게 생각합니다. 전자는 하위뷰가 상위뷰의 margin과 관련이 없어 개별적으로 조절이 가능한 반면 후자는 모든 하위뷰가 상위뷰의 margin에 영향을 받습니다. 따라서 용도에 따라 선택을 해야한다고 생각합니다.

------------------------------------------------------------------------------------------------------------

나머지는 코멘트를 참고해주세요.

2022-12-20 16:38 UTC, 1Consumption commented on Diary/Resource/Common/DateFormatterManager.swift
> +    }()
외부에서 알아야하는 프로퍼티인가요?

2022-12-20 16:38 UTC, 1Consumption commented on Diary/Resource/Controller/DiaryListViewController.swift
> +class DiaryListViewController: UIViewController {
상속이 되는 클래스일까요? 상속되지 않는다면 어떤 키워드를 붙일 수 있을까요? 그리고 그 키워드의 역할은 무엇인가요?

2022-12-20 16:38 UTC, 1Consumption commented on Diary/Resource/Controller/DiaryListViewController.swift
> +        self.view = diaryListTableView
`viewDidLoad` 메소드는 말 그대로 `view가 메모리에 올라가고 난 후`인데, 여기서 다시 `view`를 교체해주는 이유가 있을까요?
https://developer.apple.com/documentation/uikit/uiviewcontroller/1621454-loadview 이 라이프 사이클에 대해 공부해보세요.

2022-12-20 16:38 UTC, 1Consumption commented on Diary/Resource/Controller/DiaryListViewController.swift
> +    }
Json 디코딩 하는 코드를 `view`에서 알아야 할까요? 그전에, `ViewController`는 `view` 일까요?

2022-12-20 16:38 UTC, 1Consumption commented on Diary/Resource/Controller/DiaryListViewController.swift
> +extension DiaryListViewController {
이 `extension` 자체를 `private`으로 바꾸는건 어떨까요?

2022-12-20 16:38 UTC, 1Consumption commented on Diary/Resource/Controller/DiaryListViewController.swift
> +    }
사실 이 정보도 view에서 알아야하나 싶네요. 저는 view는 어떤 정보를 알고 있으면 안되고, 어디선가 받은 정보를 반영만 한다고 생각하거든요.

2022-12-20 16:38 UTC, 1Consumption commented on Diary/Resource/Controller/Extension/UIViewController+.swift
> +    func showAlertController(title: String, message: String) {
action이 눌렸을 때 어떤 동작을 수행하고 싶으면 어떻게 해야하나요?

2022-12-20 16:38 UTC, 1Consumption commented on Diary/Resource/Controller/RegisterViewController.swift
> +    }()
전부 외부에서 몰라도 되는 프로퍼티 같습니다.

2022-12-20 16:38 UTC, 1Consumption commented on Diary/Resource/Controller/RegisterViewController.swift
> +        self.view.addSubview(mainStackView)
모두 같은 멤버 변수 같은데 어디는 self를 붙이고 어디는 안 붙이네요. 컨벤션을 통일하면 더 좋겠습니다.

2022-12-20 16:38 UTC, 1Consumption commented on Diary/Resource/Controller/RegisterViewController.swift
> +        ])
지금 메소드는 한번에 너무 많은 역할을 하고 있다고 생각합니다. 메소드로 나눠보는건 어떨까요?
저는 view 단위로 메소드를 나누는 편입니다.

2022-12-20 16:38 UTC, 1Consumption commented on Diary/Resource/Controller/RegisterViewController.swift
> +    }()
각 view에 들어가는 상수 값을 매직넘버로 넣게 되면 추후에 수정하기 어렵습니다. 따라서 여기 들어가는 값들도 `NameSpace enum` 처럼 상수로 관리가 되면 좋겠습니다.

2022-12-20 16:38 UTC, 1Consumption commented on Diary/Resource/Model/DiaryForm.swift
> +    }
`JsonDecoder`의 `keyDecodingStrategy` 프로퍼티를 변경하면 snake case를 camel case로 변경하기 위한 `CodingKeys` enum은 필요없습니다.
https://developer.apple.com/documentation/foundation/jsondecoder/2949119-keydecodingstrategy

2022-12-20 16:38 UTC, 1Consumption commented on Diary/Resource/View/DiaryListTableViewCell.swift
> +    }
외부에서 직접 할당하지 말고 메소드를 통해 할당하면 좋겠습니다. 지금은 이 변수에 읽기 / 쓰기 모두 가능하네요.

2022-12-20 16:38 UTC, 1Consumption commented on Diary/Resource/Controller/RegisterViewController.swift
> +    }()
이 view들은 왜 `translatesAutoresizingMaskIntoConstraints`를 `false`로 주지 않았나요?

2022-12-20 16:38 UTC, 1Consumption commented on Diary/Resource/Controller/RegisterViewController.swift
> +            view.keyboardLayoutGuide.topAnchor.constraint(equalTo: mainStackView.bottomAnchor)
`titleTextView`에 개행을 많이 포함하고 `bodyTextView`에 텍스트를 입력하면 `bodyTextView`가 키보드에 가려질까요? 안 가려질까요?

2022-12-21 06:35 UTC, jsa0224 commented on Diary/Resource/Common/DateFormatterManager.swift
> +    }()
아닙니다! 놓쳤던 부분이라, private 접근제어자 설정 관련 리팩토링 진행했습니다! [6fa2f39](https://github.com/yagom-academy/ios-diary/pull/59/commits/6fa2f39cc87784165165a0f61742156935700399)

2022-12-21 06:41 UTC, jsa0224 commented on Diary/Resource/Controller/DiaryListViewController.swift
> +    }
저희가 의견을 나눠보았을 때, 뷰컨트롤러에서 직접 알아야 하는 정보는 아닐 수 있지만, 다른 뷰컨트롤러에서 필요한 정보도 아니기에 같은 파일 내에 `fileprivate`으로 선언해주는 것으로 변경하였습니다. 혹시 다른 좋은 방법이 있을까요? [6fa2f39](https://github.com/yagom-academy/ios-diary/pull/59/commits/6fa2f39cc87784165165a0f61742156935700399)

2022-12-21 06:41 UTC, jsa0224 commented on Diary/Resource/Controller/RegisterViewController.swift
> +    }()
이 부분도 놓쳤던 부분이라, private 접근제어자 설정 관련 리팩토링 진행했습니다! [6fa2f39](https://github.com/yagom-academy/ios-diary/pull/59/commits/6fa2f39cc87784165165a0f61742156935700399)

2022-12-21 07:07 UTC, dev-summer commented on Diary/Resource/Controller/RegisterViewController.swift
> +        self.view.addSubview(mainStackView)
꼭 필요한 경우 외에는 `self`를 붙이지 않는 것으로 컨벤션을 통일했습니다. [0b37f8b](https://github.com/yagom-academy/ios-diary/pull/59/commits/0b37f8b3bb09b5c6ce8719065b0f2e1ba41bdd2a)

2022-12-21 07:08 UTC, dev-summer commented on Diary/Resource/Controller/RegisterViewController.swift
> +        ])
루트뷰/텍스트뷰/메인스택뷰 기준으로 메서드를 분리해 주었습니다. [0b37f8b](https://github.com/yagom-academy/ios-diary/pull/59/commits/0b37f8b3bb09b5c6ce8719065b0f2e1ba41bdd2a)

2022-12-21 07:51 UTC, jsa0224 commented on Diary/Resource/Controller/DiaryListViewController.swift
> +    }
뷰컨에서 구현하는 것보다 따로 타입을 만들어서 메서드를 호출하는 방향으로 수정했습니다! [1ad68f5](https://github.com/yagom-academy/ios-diary/pull/59/commits/1ad68f5088561b64df05abfb2712f1ef3b0eded1)

2022-12-21 07:55 UTC, jsa0224 commented on Diary/Resource/Controller/DiaryListViewController.swift
> +        self.view = diaryListTableView
해당 loadView() 문서를 읽어보니, 뷰컨트롤러가 관리하는 뷰를 만드는 기능을 하고 있어, 해당 메서드에서 루트 뷰를 테이블 뷰로 설정하였습니다. [d024928](https://github.com/yagom-academy/ios-diary/pull/59/commits/d0249280441a2f67f41e5b8d92c2eaf5c6979078)

2022-12-21 08:19 UTC, dev-summer commented on Diary/Resource/Controller/Extension/UIViewController+.swift
> +    func showAlertController(title: String, message: String) {
`UIAlertAction`의 이니셜라이저의 매개변수인 `handler` 코드 블록에 해당 `action`을 선택했을 때 수행할 동작을 정의할 수 있습니다.
현재 저희 코드의 경우 JSON 데이터를 변환하는 데 실패했을 경우 앱에서 더 이상 할 수 있는 동작이 없다고 생각해 앱을 종료하는 동작을 수행하도록 작성해 보았습니다.

2022-12-21 09:02 UTC, jsa0224 commented on Diary/Resource/Controller/RegisterViewController.swift
> +    }()
넵 해당 부분 수정했습니다~ [95327b0](https://github.com/yagom-academy/ios-diary/pull/59/commits/95327b068029f0211f3b45dedca661cb637903de)

2022-12-21 09:15 UTC, dev-summer commented on Diary/Resource/Model/DiaryForm.swift
> +    }
적용하여 수정 완료입니다 [4a8a90e](https://github.com/yagom-academy/ios-diary/pull/59/commits/4a8a90e9e93ff018d353913e921a2bcf8e05e8fb)

2022-12-21 09:25 UTC, jsa0224 commented on Diary/Resource/View/DiaryListTableViewCell.swift
> +    }
`diaryForm`의 데이터를 매개변수로 받아오는 방법으로 수정했습니다! [4df2d33](https://github.com/yagom-academy/ios-diary/pull/59/commits/4df2d3393badebbe3cb657c629504ca46bf39827)

2022-12-21 12:57 UTC, dev-summer commented on Diary/Resource/Controller/RegisterViewController.swift
> +    }()
스택뷰는 `.axis`, `.alignment`, `.distribution` 및 `.spacing` 프로퍼티와 스택뷰의 프레임(또는 margin)을 기반으로 자신의 arrangedSubviews의 레이아웃을 결정할 수 있기 때문에, 각 서브뷰의 오토레이아웃을 직접 설정하지 않고도 레이아웃을 지정할 수 있습니다. [출처 - 공식문서](https://developer.apple.com/documentation/uikit/uistackview)
위 view들은 별도의 margin, spacing 외에 별도의 제약조건이 필요하지 않다고 생각해 `translatesAutoresizingMaskIntoConstraints`를 기본값인 `true`로 두어 스택뷰의 프로퍼티에 맞게 서브뷰가 autoresize될 수 있도록 했습니다. 

**오토리사이징에 의해 자동으로 생성된 제약**
![](https://i.imgur.com/NI9YZDG.png)

2022-12-21 15:00 UTC, dev-summer commented on Diary/Resource/Controller/RegisterViewController.swift
> +            view.keyboardLayoutGuide.topAnchor.constraint(equalTo: mainStackView.bottomAnchor)
`titleTextView`가 일정 높이가 될 때까지는 텍스트뷰의 콘텐트 사이즈에 맞추어 높이가 늘어나고, 일정 높이에 도달하면 더 이상 높이가 늘어나지 않고 스크롤이 되도록 변경해 주었습니다.
`textViewDidChange(_:)` 메서드를 활용해서 사용자가 텍스트뷰에 작성을 시작할 때, 스크롤 가능 여부에 대한 조건문과 그에 따라 레이아웃이 동적으로 실행되도록 구현하고자 했습니다. 
[사이즈/스크롤 로직 참고 자료 - StackOverflow](https://github.com/mattneub/Programming-iOS-Book-Examples/blob/master/bk2ch10p531selfSizingTextView/ch23p811selfSizingTextField/ViewController.swift)

위의 기능을 구현하는 과정에서 `titleTextView`, `bodyTextView`의 스크롤을 내리기 전과 후의 텍스트뷰 바깥 공간과의 여백이 다른 점을 발견했습니다. 스크롤을 내렸을 때  각 텍스트뷰의 첫 줄의 위에 공간이 존재하고, 스크롤을 내리면 그 공간이 사라진다는 것을 뷰 디버거를 통해 알게 되었습니다. 

| 스크롤을 내리지 않았을 때 | 스크롤을 내렸을 때 |
| --- | --- |
| ![](https://i.imgur.com/iaV7HOn.png) | ![](https://i.imgur.com/XMeEX2w.png) |

텍스트뷰 자체에 첫째줄에만 적용되는 padding 같은 개념이 존재할 수도 있다고 생각해 UITextView의 프로퍼티들을 확인해서 [`textContainerInset`](https://developer.apple.com/documentation/uikit/uitextview/1618619-textcontainerinset)이라는 프로퍼티가 존재하며, 기본값이 `(8, 0, 8, 0)`이라는 것을 알게 되었습니다.
각 텍스트뷰의 스크롤을 내려도 텍스트뷰 바깥 공간과의 여백을 일정하게 유지하기 위해 `textContainerInset`을 `(0, 0, 0, 0)`으로 설정했습니다.

| 스크롤을 내리지 않았을 때 | 스크롤을 내렸을 때 |
| --- | --- |
| ![](https://i.imgur.com/g8XXybD.png) | ![](https://i.imgur.com/ZSSgcIH.png) |

2022-12-21 15:15 UTC, jsa0224 commented on Diary/Resource/Controller/DiaryListViewController.swift
> +class DiaryListViewController: UIViewController {
`final` 키워드는 더 이상 해당 클래스에서 하위 클래스로의 전체 클래스 또는 일부가 상속 또는 상속에 따른 재정의가 될 필요가 없다고 판단한 경우에 각 클래스 앞에 추가하여 상속을 방지합니다 (메서드, 프로퍼티 등에도 사용 가능). 
`final`로 선언된 요소들은 직접 호출하는 반면, 그렇지 않은 요소들은 `vtable`을 통해 간접 호출되어 직접 호출되는 경우보다 느리게 작동하게 됩니다. `vtable`이란 메서드 오버라이딩에 따라 실행 시점에 어떤 메서드를 실행할 지 결정하는 동적 디스패치를 지원하기 위해 사용하는 메커니즘입니다.
다시 말해, `final` 키워드가 적용된 메서드는 컴파일 시전에 어떤 메서드를 실행할 지 결정할 수 있어(해당 메서드는 더 이상 오버라이딩 되지 않을 것임이 보장되기 때문에) 성능상 이점을 가지게 됩니다. `vtable`에 대해서는 좀 더 공부가 필요할 거 같습니다.

[WWDC16 - Understanding Swift Performance](https://developer.apple.com/videos/play/wwdc2016/416/)

2022-12-21 15:38 UTC, jsa0224 commented
- `LaunchScreen`은 `view` 폴더에 넣어야 할까요?
> 왜 이 고민을 했는지 궁금합니다. 이부분에 대한 답변을 해주시면 그 답변에 대한 제 생각을 말씀드릴게요.

프로젝트 파일링을 하면서, `LaunchScreen` 파일이 어느 폴더에 들어가는 것이 적합할지에 대한 고민이 생겼습니다.
`storyboard`가 존재한다는 점과 `main storyboard`와의 유사한 점이 있어 처음에는 `view` 폴더에 넣어야겠다고 생각했습니다. `LaunchScreen`은 사용자가 앱을 실행했을 때 앱의 시작 화면을 담당하는데, 이것의 개념을 뷰와 뷰컨트롤러 중 어느 것으로 생각해야 할 지 고민이 생겨 올라프께 질문하게 되었습니다.
그런데 고민하다 보니 스토리보드 자체가 뷰 또는 뷰컨트롤러 어느 것도 아니라는 것을 깨닫게 되었습니다...🙃

2022-12-22 13:14 UTC, 1Consumption commented on Diary/Resource/Controller/Extension/UIViewController+.swift
> +    func showAlertController(title: String, message: String) {
어떤 경우에도 앱은 죽으면 안됩니다. 알러트를 보여주는 정도가 좋겠어요.

2022-12-22 13:19 UTC, 1Consumption commented
> `LaunchScreen`은 `view` 폴더에 넣어야 할까요?

저는 굳이 따지자면 view라고 생각해요. 제가 생각하는 view의 역할은 다음과 같아요.
1. 유저에게 모델을 시각화해서 보여줌.
2. 유저의 액션을 받음.

런치타임 중에(런치스크린이 보이는 도중에) 유저 액션을 받지는 않지만, 유저에게 무언가를 보여주고 있다는 점에서 view라고 생각했어요.

--------------------------------
코멘트 반영하시느라 고생하셨습니다.
그런데 위에서도 드린 코멘트인데, 아직 커밋 나누기가 잘 안된다고 생각합니다. 한번에 하나의 역할만 하도록 해주세요.

여기서 머지하겠습니다. 다음 스텝을 진행해주세요.

2022-12-22 13:19 UTC, merged