일기장 [STEP 1] 애종, 애쉬
yagom-academy/ios-diary pull request #62
Opened 2022-12-21 07:45 UTC by ash-youu

안녕하세요, havi(@havilog)
애종와 애쉬 입니다!
Step1 구현이 끝나서 PR 보내봅니다. 🙃

## 💻 코드 개요
#### Model
- Diary: 디코딩된 JSONData를 담을 타입 입니다.
  `Hashable`을 채택함으로써 UUID 프로퍼티를 추가하였습니다.

#### View
- ListCollectionViewCell: CollectionViewCell의 UI 프로퍼티를 정의하고, 오토레이아웃 제약을 설정하는 타입입니다.
- AddDiaryView: 일기를 추가하는 화면의 UI 프로퍼티를 정의하고, 오토레이아웃 제약을 설정하는 타입입니다.

#### Controller
- ViewController: collectionView를 표시하는 메인 화면의 ViewController입니다.
- AddDiaryViewController: 일기를 추가하는 화면의 ViewController입니다.

---

## 🥲 조언이 필요한 점
### 1. 사용자의 지역포멧에 따라 날짜 표현하기
- 선호하는 언어에 따라 변경은 가능한데 지역에 따라 변경하는 방법이 있는지 궁금합니다!
```swift
// 언어를 기준으로 접근하는 방법
let localeLanguage = Locale.preferredLanguages.first
DateFormatter().locale = Locale(identifier: localeLanguage ?? "ko-kr")
```
- 명세서에서는 `작성일자는 사용자의 지역 포멧에 맞게 표현해야합니다` 라고 써져있어 지역에 따라 날짜를 표현하는 방법을 찾아봤지만 실패해 위처럼 사용자가 선호하는 첫 번째 언어에 따라 날짜가 표현되도록 구현했습니다. **사용자의 지역에 접근하여 localization 할 수 있는 방법**이 있는지 궁금합니다!

## 🧐❓ 고민한 점
### 1. textView에서 사용자가 입력하는 부분이 키보드에 가려지지 않도록 할 방법
 - 총 3가지 방법을 시도해보았습니다.
     - **view의 frame.y 를 이동시키기**
         - 첫 번째 view의 frame을 올라가도록 변경하니 textView의 text가 네비게이션 바를 가려 이 방법은 적합하지 않다고 생각했습니다.
     - **keyboardLayoutGuide 적용하기**
         - ```swift
            view.scrollView.bottomAnchor.constraint(equalTo: view.keyboardLayoutGuide.topAnchor, constant: -10)
            ```
        - 위의 방법으로 비교적 간단하게 구현할 수 있었지만 `iOS15버전부터 사용가능`하기 때문에 다른 방법을 통해서도 해당기능을 구현할 줄 알아야 된다고 생각했습니다.
     - **textView의 contentInset 변경하기**
         - `현재 저희 코드`에서 사용한 방법입니다. notification center를 통해 키보드가 나타날 때 키보드의 높이를 구하고, textView아래에 키보드의 높이만큼 여백을 추가해줬습니다.
 

### 2. JSON 데이터가 `Hashable` 할 수 있도록 `UUID` 사용
- sample JSON 데이터에는 모든 프로퍼티가 동일한 데이터가 존재해서 `Hashable` 하지 않아 데이터를 디코딩할 때 런타임 에러가 발생했었습니다.
- 해당 문제를 해결하기 위해 아래와 같이 UUID를 프로퍼티로 가지는 id 프로퍼티를 `Diary` 타입에 정의해 `Hashable` 프로토콜을 준수할 수 있도록 했습니다.
```swift
struct Diary: Decodable, Hashable {
    let id = UUID()
    let title: String
    let body: String
    let createdAt: Int
    
    enum CodingKeys: String, CodingKey {
        case title, body
        case createdAt = "created_at"
    }
}
```

### 3. 일기 추가 화면으로 전환시 textView 상단의 일부가 가려져서 보이는 문제에 대한 고민
- 기존에는 아래 이미지와 같이 일기 추가 화면으로 전환했을 때, textView의 상단이 가려진 채로 전환되는 문제가 있었습니다.
<img width=200px, src="https://i.imgur.com/mVa5WfY.png">

- 해당 문제에 대해 확인해보니 UITextView는 기본값으로 마진을 가지고 있다는 것을 공식문서에서 확인할 수 있었습니다.
```This property provides text margins for text laid out in the text view. By default the value of this property is (8, 0, 8, 0).```

- 마진을 제거하기 위해 아래의 코드를 사용해 문제를 해결했습니다.
```swift
self.textView.textContainerInset = .zero
```

2022-12-21 11:41 UTC, havilog requested changes
안녕하세요 애종 애쉬 :)
앞으로 이주간 잘 부탁드려요 ㅎㅎ

전체적으로 열심히 구현하신 거 같아요! 조금만 다듬으면 더 좋은 코드가 될 것 같습니다 :)

> 사용자의 지역포멧에 따라 날짜 표현하기

요거는 제가 로컬라이제이션을 많이 안해봐서 답변드리기가 조금 어렵네요 ㅠㅠ
해결 안되시면 디코에서 같이 고민해봐요!

2022-12-21 11:41 UTC, havilog commented on .swiftlint.yml
> +  - closure_parameter_position
요건 회바회 부바부 팀바팀인데요,
보통 린트 파일은 프로젝트에 포함하지 않는거로 알고있어요!

2022-12-21 11:41 UTC, havilog commented on Diary/Controller/AddDiaryViewController.swift
> +        self.view = addDiaryView
1. self의 view를 바꿔주도록 설계하신 이유가 뭘까요?
2. viewDidLoad시점에 self.view를 바꿔주면 어떻게 동작할지 고민해보셨을까요?
3. viewController의 역할은 뭐라고 생각하시나요?

2022-12-21 11:41 UTC, havilog commented on Diary/Controller/AddDiaryViewController.swift
> +    }
protocol로 빼볼수도 있을거 같은데 혹시 고민해보셨을까요? ㅎㅎ

2022-12-21 11:41 UTC, havilog commented on Diary/Controller/ViewController.swift
> +final class ViewController: UIViewController {
요 아이는 이름이 `ViewController`인가요..? ㅎㅎ;

2022-12-21 11:41 UTC, havilog commented on Diary/Controller/ViewController.swift
> +    enum Section: Hashable {
요건 개인 취향인데, 그냥 `Section`보다는 `DiarySection`으로 쓰는걸 전 더 선호합니다 ㅎㅎ

2022-12-21 11:41 UTC, havilog commented on Diary/Controller/ViewController.swift
> +        configureListContents()
어디에는 self가 붙어있고, 어디에는 안붙어있는데,
요거는 컨벤션이 통일되면 더 보기 좋을거 같아요!

2022-12-21 11:41 UTC, havilog commented on Diary/Controller/ViewController.swift
> +    private var collectionView: UICollectionView?
이 collectionView는 무조건 있어야할 아이처럼 생겼는데, 없어도 되는 아이라서 옵셔널인걸까요??

2022-12-21 11:41 UTC, havilog commented on Diary/Controller/ViewController.swift
> +        guard let collectionView = collectionView else { return }
위 질문과 연관된건데 요 collectionView가 옵셔널이라서 가드로 꺼내주는게 희안해보이네요..!

2022-12-21 11:41 UTC, havilog commented on Diary/Controller/ViewController.swift
> +        self.view.addSubview(collectionView)
오잉 collectionView의 constraint를 잡아주는 코드는 어디있는거죠..?!

2022-12-21 11:41 UTC, havilog commented on Diary/Controller/ViewController.swift
> +        return UICollectionViewCompositionalLayout.list(using: config)
요거 저도 딮하게 파보진 몰라서 잘 모르긴 하는데,
ListConfiguration을 사용하면, 해당 컬렉션 뷰를 커스텀하기 힘들다고 알고있는데요,
요거 사용하신 이유가 있을까요?

2022-12-21 11:41 UTC, havilog commented on Diary/Controller/ViewController.swift
> +    }
diaryData가 비어있을 경우 어떻게 되는지 고민해보셨을까요??
해당 함수가 self에 있는 diary를 보고있게하신 이유도 궁금합니다!

2022-12-21 11:41 UTC, havilog commented on Diary/Errors/ErrorType.swift
> +enum ErrorType: Error {
이 에러가 어떤 에러인지 `DiaryError`라던가 하는 프리픽스가 있어야할 거 같아요!
아니면 
```swift
enum DiaryNameSpace {
    enum Error: Error {
    }
    struct Model {
    }
}
```
이런식으로 네임스페이스를 잡아줄 수도 있어요.

2022-12-21 11:41 UTC, havilog commented on Diary/Extensions/JSONDecoder+Extension.swift
> +}
이 함수는 비동기일 필요가 없어보이는데,,, completion 파라미터가 있는 이유는 뭘까요??

2022-12-21 11:41 UTC, havilog commented on Diary/Extensions/UIViewController+Extension.swift
> +}
확인이나 취소도 커마할 수 있음 좋을거 같아요 ㅎㅎ
알럿 익스텐션이나 객체를 탬플릿으로 만들어서 다른 곳들에서도 재사용하실 수 있도록 하는것도 좋을거 같아요

2022-12-21 11:41 UTC, havilog commented on Diary/Model/Diary.swift
> +    enum CodingKeys: String, CodingKey {
코딩키 private이면 더 좋을거 같아용

2022-12-21 11:41 UTC, havilog commented on Diary/Model/Diary.swift
> +    let id = UUID()
요 id는 왜때문에 필요한 아이인지 설명해주실 수 있으실까요?

2022-12-21 11:41 UTC, havilog commented on Diary/SceneDelegate.swift
>          // This delegate does not imply the connecting scene or session are new (see `application:configurationForConnectingSceneSession` instead).
안쓰이는 주석은 지워주세용 ㅎㅎ

2022-12-21 11:41 UTC, havilog commented on ListCollectionViewCell.swift
> +    }()
이 아이들은 왜때문에 variable일까요??

2022-12-21 11:41 UTC, havilog commented on Podfile
> +end
린트 brew로 깔아서 쓰는 방법도 있는데 혹시 알고 계신가용?

2022-12-22 09:51 UTC, jonghancha commented on .swiftlint.yml
> +  - closure_parameter_position
#### 현재 저희 diary 폴더 모습입니다. 린트파일이 포함되어있는 상태입니다. 프로젝트에 포함시키지 않는다는 건 이 폴더 바깥에 위치시켜야 하는 걸까요??
<img width="700" alt="image" src="https://user-images.githubusercontent.com/73284068/209106960-4ab32311-345c-4fd0-babe-7ce5c8dfffea.png">

#### 또 SwiftLint ReadMe에 안내된 사항으로는 디렉터리 안에 위치해야한다고 적혀있어서, `보통 린트 파일은 프로젝트에 포함되지 않는다`는 말씀이 잘 이해가 되지 않습니다. 다시 한번 설명해주실 수 있을까요??
![image](https://user-images.githubusercontent.com/73284068/209106678-725ec09f-3704-479f-9426-d887ee11bce4.png)

2022-12-22 10:08 UTC, ash-youu commented on Diary/Controller/AddDiaryViewController.swift
> +        self.view = addDiaryView
1. AddDiaryView라는 커스텀 뷰의 UI요소와 오토레이아웃 제약 설정을 View 내에서 진행하고, ViewController는 Controller의 역할을 할 수 있도록 분리하고 싶어서 이와 같이 설계하였습니다.
2. 이건 View Life Cycle을 고려하는 것을 놓친 것 같습니다! viewDidLoad 시점에 self.view를 바꿔주면 자신의 뷰를 다 로드한 뒤에 또 다시 뷰를 바꾸는 것으로 읽힐 수 있어 잘못 설계된 코드인 것 같습니다. 😅 
자신의 뷰를 로드하는 loadView 메서드에서 self.view를 설정할 수 있도록 리팩토링 했습니다!
3. 뷰를 관리하는 역할로 뷰 위에 보여질 데이터 관리 + 발생하는 이벤트에 따른 상호 작용 관리 등의 역할을 한다고 생각합니다.
즉, 화면에 보여질 데이터의 변경사항(모델 데이터의 변화)가 발생했을 때 이것이 View에 반영될 수 있도록 변경된 사항을 전달하는 역할을 한다고 생각합니다.

2022-12-22 10:43 UTC, jonghancha commented on Diary/Controller/AddDiaryViewController.swift
> +    }
아뇨 전혀생각하지 못했었습니다  ...ㅠ 하지만 하비 말씀을 듣고 생각해보니 addObserver 작업을 프로토콜화 한다면 재사용성이 높아질 것이라는 생각이 들어서 수정해봤습니다. selector에서 @objc 함수를 호출해야 하는데 objc 함수는 @objc protocol 을 사용해 구현해주었습니다.

2022-12-22 10:45 UTC, ash-youu commented on Diary/Controller/ViewController.swift
> +final class ViewController: UIViewController {
좀 더 명시적으로 표현할 수 있도록 `DiaryListViewController` 로 리네이밍 하였습니다.

2022-12-22 10:47 UTC, jonghancha commented on Diary/Controller/ViewController.swift
> +    enum Section: Hashable {
저희도 좋다고 생각합니다! 수정했습니다 ㅎㅎ

2022-12-22 10:49 UTC, ash-youu commented on Diary/Controller/ViewController.swift
> +        configureListContents()
저희의 컨벤션으로는 ViewController의 프로퍼티는 self를 붙여서 해당 뷰컨의 프로퍼티임을 명시적으로 나타낼 수 있도록 하였고, 메서드의 경우에는 붙이지 않는 것으로 컨벤션을 통일하여 작성하기는 했습니다! 
혹시 하비의 경우에는 self의 코딩 컨벤션을 어떻게 가져가시는 조언 주실 수 있을까요? 🙃

2022-12-22 11:06 UTC, jonghancha commented on Diary/Controller/ViewController.swift
> +    private var collectionView: UICollectionView?
처음에는 전역변수에 무언가 많은 작업을 두면 안된다는 생각과, 어차피 configureCollectionView라는 메서드로 collectionView를 구성한다고 생각했던것 같습니다. 하지만 하비 말씀대로 optional인 collectionView를 사용할 때마다 바인딩하는 것은 좀 어색해보였습니다. 그래서 lazy var로 전역변수 collectionView를 정의해주었습니다.
[51ecbb2](https://github.com/yagom-academy/ios-diary/pull/62/commits/51ecbb2bc98d385dc33851fc9b6580aa1ff52acd)

2022-12-22 11:06 UTC, jonghancha commented on Diary/Controller/ViewController.swift
> +        guard let collectionView = collectionView else { return }
위 질문에 함께 답변드렸습니다!

2022-12-22 11:32 UTC, ash-youu commented on Diary/Controller/ViewController.swift
> +        self.view.addSubview(collectionView)
오토 리사이징 마스크를 통해 너비와 높이에 유연성을 주어 제약을 주는 방법을 택했습니다! 오토 레이아웃과 비교하기 위해 오토레이아웃 제약도 사용해보았습니다. 

비교해보니 오토레이아웃은 SafeArea와 동일하게 제약을 걸기 때문에 SafeArea를 침범하지 않았고, 오토 리사이징 마스크는 SafeArea까지 UI 요소가 나타나는 것을 확인했습니다.
그래서 오토레이아웃을 활용하는 것으로 리팩토링 하였습니다!

[8a54f46](https://github.com/yagom-academy/ios-diary/pull/62/commits/8a54f46a6bb930d14e3f6ec63c0ae2c7a5fd73da)

2022-12-22 11:43 UTC, jonghancha commented on Diary/Controller/ViewController.swift
> +        return UICollectionViewCompositionalLayout.list(using: config)
table 형태의 list section만 있는 collectionView라고 생각해서 ListConfiguration을 사용했습니다! 다른 layout이라 함은 [compositional layout 공식문서](https://developer.apple.com/documentation/uikit/uicollectionviewcompositionallayout) 에 있는 이 내용일까요??

2022-12-22 11:59 UTC, jonghancha commented on Diary/Controller/ViewController.swift
> +    }
비어있는 경우에는 일기장을 하나도 쓰지 않은 상태라고 생각합니다. placeholder나 비간섭레이블을 통해 새로운 일기를 추가해주세요 라는 메세지를 띄우거나, 메모 앱과 같이 하단에 일기 없음 or n 개의 일기 처럼 표현해주는 방법도 가능하다고 생각합니다! 

self.diary를 가져다 쓰면 되는데 굳이 바라보게 한 것 같아서 매개변수를 없애주었습니다!

2022-12-22 12:09 UTC, ash-youu commented on Diary/Errors/ErrorType.swift
> +enum ErrorType: Error {
`ErrorType`이라는 네이밍이 어떤 에러인지 명확하게 나타내지 못하는 것 같아 제시해주신 `DiaryError`로 리네이밍 하였습니다!
[dc3d440](https://github.com/yagom-academy/ios-diary/pull/62/commits/dc3d440272af1ff66ff857e5545742858537f08f)

추가로 코멘트주신 `DiaryNameSpace`는 아래와 같이 리팩토링을 제안해주신 것이 맞을까요? 예시로 적어주신 struct Model이 어떤 것을 의미하는지 궁금합니다!😀
```swift
enum DiaryNameSpace {
    enum DiaryError: Error {
        case decodeFailed
        case dataAssetLoadFailed
        
        var alertTitle: String {
            switch self {
            case .decodeFailed:
                return "데이터 디코딩 실패"
            case .dataAssetLoadFailed:
                return "데이터 에셋 로딩 실패"
            }
        }
        
        var alertMessage: String {
            switch self {
            case .decodeFailed:
                return "데이터 디코딩 에러가 발생했습니다."
            case .dataAssetLoadFailed:
                return "해당하는 데이터 에셋이 존재하지 않습니다."
            }
        }
    }
}
```

2022-12-22 12:30 UTC, jonghancha commented on Diary/Extensions/JSONDecoder+Extension.swift
> +}
저희는 Result 타입을 사용해 디코딩의 결과에 따른 작업을 completion 클로저에서 이루어지도록 하고싶었습니다. escaping closure를 통해 함수를 호출할 때 함수의 결과에 따른 작업을 한번에 적고자 했습니다. 비동기작업이 아니라면 completion을 사용하는게 부적절한가요?? 🥲

2022-12-22 12:45 UTC, jonghancha commented on Diary/Model/Diary.swift
> +    enum CodingKeys: String, CodingKey {
enum에 private이 되는지 몰랐네요 수정했습니다!

2022-12-22 12:46 UTC, jonghancha commented on Diary/SceneDelegate.swift
>          // This delegate does not imply the connecting scene or session are new (see `application:configurationForConnectingSceneSession` instead).
넵 지웠습니다 !!

2022-12-22 12:48 UTC, jonghancha commented on ListCollectionViewCell.swift
> +    }()
저희가 놓친부분인것 같습니다. 변하지 않으니 상수로 변경했습니다!

2022-12-22 12:48 UTC, jonghancha commented on Podfile
> +end
알고는 있지만 사용은 해보지 않았습니다! brew의 장점이 더 많은가요??

2022-12-22 12:50 UTC, ash-youu commented on Diary/Extensions/UIViewController+Extension.swift
> +}
알럿을 싱글톤 패턴을 사용하는 별도의 클래스 타입으로 정의해보았습니다.
또한, 확인이나 취소도 커스터마이징할 수 있도록 매개변수를 추가했습니다! 🙃

[5849ce8](https://github.com/yagom-academy/ios-diary/pull/62/commits/5849ce8b3938c34147411c8e411458a0fc7fa324)

알럿 익스텐션으로도 리팩토링 해보려고 시도했습니다.
하지만 연산 프로퍼티로 정의해 반환 하기에는 매개변수를 받을 수 없고, 메서드로 반환하는 것은 동일하게 싱글톤 패턴으로 인스턴스를 만든 후에 반환해야 할 것 같아 객체를 만드는 것으로 리팩토링 하였습니다!
혹시 알럿 익스텐션으로 리팩토링하는 것 중에 저희가 생각하지 방법이 있다면.. 힌트를 부탁드립니다 🤣

2022-12-22 12:52 UTC, ash-youu commented on Diary/Model/Diary.swift
> +    let id = UUID()
Diary 타입이 Hashable을 준수하고 있는데, 모든 프로퍼티의 데이터가 동일한 JSON 데이터가 sample 파일에 존재하고 있었습니다!
해당 데이터로 인해 디코딩 시 에러가 발생해 id 프로퍼티를 추가하였습니다.
PR에 기재한 내용 리마인드차 첨부 드립니다 😀
```
sample JSON 데이터에는 모든 프로퍼티가 동일한 데이터가 존재해서 Hashable 하지 않아 데이터를 디코딩할 때 런타임 에러가 발생했었습니다.
해당 문제를 해결하기 위해 아래와 같이 UUID를 프로퍼티로 가지는 id 프로퍼티를 Diary 타입에 정의해 Hashable 프로토콜을 준수할 수 있도록 했습니다.
```

2022-12-22 12:53 UTC, havilog commented on .swiftlint.yml
> +  - closure_parameter_position
폴더의 디렉토리에서 제거하라는 뜻은 아니었구,
xcodeproj파일에서 참조를 안잡고 있어도 된다는 뜻이었어요!ㅎㅎ
delete -> remove references

2022-12-22 12:55 UTC, havilog commented on Diary/Controller/AddDiaryViewController.swift
> +        self.view = addDiaryView
loadView에서 super를 안불러주고 있네요~
또한 역할을 분리하려고 하신 시도는 좋지만, 각 객체간의 커뮤니케이션을 어떻게 할지, 분리함으로써 얻는 이점이 뷰컨 내부에서 전부 처리하는 것보다 과연 무조건 이득일지? 등에 대한 명확한 근거를 조금 더 고민해보시면 좋을거 같습니다 :)

2022-12-22 12:58 UTC, havilog commented on Diary/Controller/ViewController.swift
> +    enum Section: Hashable {
그리고 해당 뷰컨 내부에서만 사용한다면 private이어도 될거 같아요!

2022-12-22 13:00 UTC, havilog commented on Diary/Controller/ViewController.swift
> +        configureListContents()
그런 컨벤션이었군요 ..!
요런건 회바회 부바부 사바사라 정답은 없는데,
보통은 다 self를 붙이거나,
저같은 경우는 안 붙일 수 있는 경우는 다 안붙이고, self를 캡쳐해줘야할 때만 사용하고 있어요!

2022-12-22 13:02 UTC, havilog commented on Diary/Controller/ViewController.swift
> +    private var collectionView: UICollectionView?
요것도 잘못된건 아니긴 한데요..!
lazy var라는 키워드는 나중에 생성될 수도 있고, 안 생성될 수도 있다
라는 의미로 사용할 수도 있고,
variable이라서 잘못해서 collectionView를 다른 collectionView로 바꿔버릴 수도 있어서,
저는 let으로 설정해 주는걸 좋아해요 ㅎㅎ

2022-12-22 13:03 UTC, havilog commented on Diary/Controller/ViewController.swift
> +        self.view.addSubview(collectionView)
오토 리사이징 마스크로 레이아웃 잡아주는 처음봤네요 ..!
저렇게도 짤수 있군요..! 신기 신기
덕분에 새로운 지식을 알았네요 ㅎㅎ

2022-12-22 13:04 UTC, havilog commented on Diary/Controller/ViewController.swift
> +        return UICollectionViewCompositionalLayout.list(using: config)
어떤 레이아웃을 선택할지는 개발자 선택의 영역이라고 생각하는데요,
선택하신 거에 대한 뚜렷한 이유가 있는지가 궁금했습니다 ㅎㅎ

2022-12-22 13:06 UTC, havilog commented on Diary/Errors/ErrorType.swift
> +enum ErrorType: Error {
NameSpace를 잡아주는 이유는,
Diary 네임스페이스 안에 Diary와 관련된 모델, API, 에러, 등등을 정의해주기 위함이라,
안에 에러만 있을거면 잡아주는 의미는 없을거 같아요~

2022-12-22 13:08 UTC, havilog commented on Diary/Extensions/JSONDecoder+Extension.swift
> +}
```swift
func decode<T: Decodable>(data: Data) -> Result<T, ErrorType> { ... }
```
이렇게 작성할 수도 있었을 텐데,,

result타입을 사용하는 것과, completion을 사용하는 것의 연관성을 잘 모르겠네용 ,,
해당 클로져가 왜 @escaping할거라고 생각하셨나요?

2022-12-22 13:09 UTC, havilog commented on Podfile
> +end
취향차이긴 한데 저는 프로젝트에 린트 넣으면 무거워져서 별로더라구요 ㅎㅎ

2022-12-22 13:11 UTC, havilog commented on Diary/Model/Diary.swift
> +    let id = UUID()
Identifiable이 아니다 단순히 hashable을 위해서라면, 프로퍼티를 하나 더 안만들고

```swift
static func == (_ lhs: Diary, _ rhs: Diary) -> Bool {
        return (
            lhs.title == rhs.title &&
            lhs.body == rhs.body &&
            lhs.createdAt == rhs.createdAt
        )
    }
```

요렇게 처리할 수도 있을거 같아서 말씀드렸습니다 ㅎㅎ

2022-12-22 13:13 UTC, havilog commented on Diary/Extensions/UIViewController+Extension.swift
> +}
```swift
func presentAlert(title: String?, subTitle: String?, message: String?, buttons: [UIButton], cancelButtonText: String?, action: ((ButtonType) -> Void)?) -> SomeAlertController { ... }
```

요런식으로 다른 옵션들도 커스터마이징 할 수 있는 함수를 만드는건 어떨지 정도의 커멘트였습니다 ㅎㅎ

2022-12-23 06:56 UTC, jonghancha commented on Diary/Controller/ViewController.swift
> +    private var collectionView: UICollectionView?
VC의 인스턴스가 없는 상태에서 어떻게 let으로 설정해줄까 고민하다가 아래와 같이 연산프로퍼티로 구현해주었습니다.
```swift
private let collectionView: UICollectionView = {
  let config = UICollectionLayoutListConfiguration(appearance: .plain)
  let collectionViewLayout = UICollectionViewCompositionalLayout.list(using: config)
  let collectionView = UICollectionView(frame: .zero, collectionViewLayout: collectionViewLayout)
  
  return collectionView
}()
```

2022-12-23 07:01 UTC, ash-youu commented on .swiftlint.yml
> +  - closure_parameter_position
저렇게 참조를 제외해도 문제가 없는줄 몰랐습니다! swiftLint 파일의 참조를 제외했습니다 :)

2022-12-23 07:04 UTC, ash-youu commented on Diary/Controller/AddDiaryViewController.swift
> +        self.view = addDiaryView
loadView의 공식문서를 확인해보니 해당 메서드를 override해서 류트뷰를 view속성에 할당하는 경우에는 super 메서드를 호출하지 말라고 기재된 것으로 이해해서 호출하지 않았습니다!
혹시 저희가 잘못 이해한 부분이 있다면 말씀 부탁드리겠습니다 🥲

![스크린샷 2022-12-23 오후 4 00 16](https://user-images.githubusercontent.com/101683977/209288310-bed6d026-a69e-4abb-9aed-6b376c1a198b.png)

2022-12-23 07:05 UTC, jonghancha commented on Diary/Controller/ViewController.swift
> +    enum Section: Hashable {
네 수정했습니다!

2022-12-23 07:15 UTC, ash-youu commented on Diary/Controller/ViewController.swift
> +        configureListContents()
오 감사합니다! 하비의 코멘트를 보고 저희는 self를 모두 붙여주는 것으로 컨벤션을 수정해보았습니다👍

[a06809c](https://github.com/yagom-academy/ios-diary/pull/62/commits/a06809ce376f2b8185ad6040542a1f0aca1b40ee)

2022-12-23 07:27 UTC, jonghancha commented on Diary/Extensions/JSONDecoder+Extension.swift
> +}
처음 생각했을 때에는 Result 타입을 리턴했을 때, 호출부분에서 할당을 해줘야 하기 때문에 completion을 사용하는 것이 좀 더 효율적일 수 있다고 생각했었습니다. 하지만 코드의 진행상 escaping을 통해 작업이 끝나길 기다려야하는 것이 아니기 때문에 `completion은 굳이 필요하지 않았다`고 생각이 바뀌었습니다...!

```swift
let decodingResult: Result<[Diary], DiaryError> = JSONDecoder().decode(data: dataAsset.data)
        
switch decodingResult {
case .success(let decodedDiary):
    self.diary = decodedDiary
case .failure(let error):
    let errorAlert = ErrorAlert.shared.showErrorAlert(title: error.alertTitle,
                                                      message: error.alertMessage,
                                                      actionTitle: "확인")
    self.present(errorAlert, animated: true)
}
```

2022-12-23 07:39 UTC, ash-youu commented on Diary/Extensions/UIViewController+Extension.swift
> +}
오 이런 방식의 메서드를 구현하는 것은 생각해보지 못했습니다 감사합니다!
추가로 궁금한 점이 혹시 매개변수인 buttons 저희 코드에서 사용한다면  UIAlertAction 타입을 받아 사용하는 것으로 이해하면 될까요?

저희가 이해하기에는 아래와 같이 생각했는데, 혹시 잘못 이해한 점이 있다면 말씀 부탁드리겠습니다 😅
- buttons: UIAlertController에 추가될 UIAlertAction들
- cancelButtonText: UIAlertAction의 title 값
- action: UIAlertAction의 handler 값

2022-12-23 08:11 UTC, jonghancha commented on Diary/Model/Diary.swift
> +    let id = UUID()
말씀해주신 방법대로 처리해보기도 했습니다. 하지만 title, body, createdAt 셋 모두가 같은 case에는 HashValue가 같기 때문에 runtime error가 발생했습니다.
제목과 내용 그리고 createdAt이 같은 경우가 있을 수 있기 때문에 각각의 item을 구분지을 UUID가 필요하다고 생각합니다!!!

havi는 이렇게 프로퍼티가 모두 동일할 수 있는 경우에는 어떻게 구현하시는지 궁금합니다 !!

2022-12-23 08:12 UTC, jonghancha commented on Podfile
> +end
오 그렇군요 ! brew로 까는 방법도 한번 찾아보겠습니다 감사합니다 ㅎㅎ

2022-12-23 08:13 UTC, ash-youu commented on Diary/Model/Diary.swift
> +    let id = UUID()
추가적인 질문으로는 하비가 제안해주신 메서드를 활용해서 리팩토링 한다면 아래의 코드를 추가해줘서 작동하는 방식이 맞을까요?
저희가 아래의 방식으로 처리하는 방법에 대해 오래 고민해봤는데 쉽게 답이 나오지 않아 질문 드립니다!

1. 해당 연산자를 사용해 모든 프로퍼티가 동일한 데이터 인지 확인
2. 동일한 데이터라면 1개의 데이터만 컬렉션뷰 데이터 소스에 추가

2022-12-23 09:29 UTC, merged