일기장 [STEP-1] 하모, 미니
yagom-academy/ios-diary pull request #63
Opened 2022-12-21 08:43 UTC by lxodud

@junbangg
안녕하세요 알라딘
Step1 PR드립니다.
잘부탁드립니다 🙇🏼‍♂️🙇🏼‍♂️🙇‍♂️

## 📝 STEP 진행 중 경험하고 배운 것
- `UITableViewDiffableDataSource`
- `DateFormatter`를 통한 `Localization`
- scheme를 편집하여 시뮬레이터의 언어 및 지역 변경
- `UIFontDescriptor` 

## 💭 고민한 부분

### `UITableViewDiffableDataSource`를 왜 사용해야 하는가?
기존의 `DataSource`를 사용했을 때 삭제나 삽입 동작을 수행하였을 때 UI의 `truth`와 `DataSource`의 역할을 하는 컨트롤러의 `truth`가 일치하지 않아서 오류가 발생하기 쉽습니다. 또한, 사용자와의 상호작용하는 과정에서 `reloadData` 메서드를 자주 호출하게 됩니다. 위와 같은 행위들은 사용자의 UX를 손상시킬 수 있습니다. 다이어리 앱 같은 경우에는 사용자와의 상호작용이 많은 앱이라고 생각하였고, 위와 같은 문제들을 해결하기 위해서 `DiffableDataSource`를 활용하였습니다.

### `Custom`한 `UIContentConfiguration`을 사용해야 하는가?
커스텀한 셀을 구현하기 위해서 클래스를 상속하여서 구현하게 되면, 새로운 데이터가 생성되거나 셀의 데이터를 변경될 때마다 셀을 다시 업데이트하도록 메서드를 통해서 업데이트 해야 합니다. 하지만, 업데이트를 위해서 메서드를 지속적으로 호출하는 것이 셀에게 데이터를 주는 것이라고 생각하였습니다. 추가적으로 사용자 이벤트에 대한 상태 변경을 더욱 쉽고 유연하게 할 수 있고, 데이터소스가 직접적으로 셀의 컨텐츠 뷰에 접근하지 않도록 할 수 있는 장점이 있어서 사용하게 되었습니다.

### `UIView`의 `Constraint` 메서드가 길어지는 것
뷰의 `constraint`를 걸어주기 위한 보일러플레이트 코드가 지속적으로 발생하였습니다. 이에 대해서 줄일 수 있는 방법에 대해서 고민해보았습니다. `UIView`를 확장하여 하나의 메서드로 구현하였습니다.
```swift
func anchor(
    top: NSLayoutYAxisAnchor? = nil,
    leading: NSLayoutXAxisAnchor? = nil,
    bottom: NSLayoutYAxisAnchor? = nil,
    trailing: NSLayoutXAxisAnchor? = nil,
    paddingTop: CGFloat = 0,
    paddingLeading: CGFloat = 0,
    paddingBottom: CGFloat = 0,
    paddingTrailing: CGFloat = 0
) {
    if let top = top {
        topAnchor.constraint(equalTo: top, constant: paddingTop).isActive = true
    }
    
    if let leading = leading {
        leadingAnchor.constraint(equalTo: leading, constant: paddingLeading).isActive = true
    }
    
    if let bottom = bottom {
        bottomAnchor.constraint(equalTo: bottom, constant: -paddingBottom).isActive = true
    }
    
    if let trailing = trailing {
        trailingAnchor.constraint(equalTo: trailing, constant: -paddingTrailing).isActive = true
    }
}
```

### 일기 작성 화면에서 제목 `TextField`와 본문 `TextView`의 `inset` 맞추기
`DiaryWriteViewController`의 `TextField` `TextView`의 텍스트가 시작하는 `inset`이 일치하지 않아서 둘을 일치시키는 방법에 대해서 고민하였습니다. `TextView`의 경우 `inputTextView`를 `textContainer`가 감싸고 있는 구조였고 `textContainer`의 `lineFragmentPadding`이라는 `text`의 `padding` 값을 담고있는 프로퍼티의 기본값이 5이기 때문에 일치하지 않은 문제가 있었습니다.
해당 프로퍼티를 0으로 할당하여 문제를 해결하였습니다.

## 🤔 조언을 얻고 싶은 부분
### `Massive`한 `ViewController`에 대한 고민과 궁금한점

APPLE이 ViewController를 개발하는 과정에서 View + Controller의 개념으로 ViewController가 생성된 것으로 알고 있습니다. 이로 인해서 다양한 문제점들이 있지만, 저희가 맞닥들인 문제는 ViewController가 비대해진다는 문제였습니다. ViewController가 View의 전환, DataSource의 역할 등을 수행하면서 비대해지는 것을 느끼게 되었습니다. 이를 해결하기 위해서 궁금한 점들이 발생하였습니다.
1. ViewController의 딜리게이트 메서드를 다른 타입으로 구현하여서 역할을 줄이는 방법을 사용하는 것도 방법이 될 수 있나요?
2. ViewController가 화면을 전환하는 역할을 가지고 있는 것이 적절한지 궁금합니다.
3. 만약, ViewController가 화면을 전환하는 역할을 가지고 있을 필요가 없다면, 다른 패턴을 활용하여서 구현하는 것도 괜찮을까요?
4. MVC 패턴의 단점을 보완하기 위해서 다른 패턴들을 활용하는 방법 외 에는 Massive한 Controller를 변경할 수 있는 방법이 없나요?

2022-12-22 14:18 UTC, junbangg requested changes
수고많으셨습니다!! 전반적으로 코드가 아주 깔끔하게 잘 정리 되어있고 가독성도 좋다는 느낌을 많이 받았습니다:) 
리뷰 내용 확인해주세요! 

그리고 질문 주신 내용에 대해 제 생각을 답변 드리자면

```
ViewController의 딜리게이트 메서드를 다른 타입으로 구현하여서 역할을 줄이는 방법을 사용하는 것도 방법이 될 수 있나요?
```
> 다른 타입으로 구현하여 역할을 줄이는건 좋게 들리는데 `딜리게이트 메서드를 다른 타입으로` <- 이걸 잘 이해 못한것 같습니다 제가 ㅜ
```
ViewController가 화면을 전환하는 역할을 가지고 있는 것이 적절한지 궁금합니다.
만약, ViewController가 화면을 전환하는 역할을 가지고 있을 필요가 없다면, 다른 패턴을 활용하여서 구현하는 것도 괜찮을까요?
```
오 혹시 생각하고 계신 패턴이 있는걸까요??? :)
`뷰컨트롤러는 화면 전환하는 역할을 갖으면 안된다? -> ___ 패턴을 쓰자` 
이렇게 생각하는것 보다는 그 패턴의 장점이 뭔지, 그리고 그게 구현하려는 앱 또는 아키텍쳐에 필요한건지를 생각해보는게 더 좋은 순서(?) 일것 같습니다. 
왜냐하면 제 생각에 뷰컨이 화면 전환 역할을 가져도 되는 경우가 있고 안되는 경우가 있을것 같아서요! 너무 케바케?

```
MVC 패턴의 단점을 보완하기 위해서 다른 패턴들을 활용하는 방법 외에는 Massive한 Controller를 변경할 수 있는 방법이 없나요?
```
MVC 도 MVC지만 기본적인 OOP만 생각해봐도 하나의 타입이 너무 많은 일을 하는거는 안좋으니까 Massive 한 Controller는 역할분리로 어느정도는 줄일 수 있을것 같은데..그걸로는 한계가 있다면 그땐 아예 다른 아키텍쳐를 생각해보는게 맞는것 같습니다 ~ 너무 애매한 대답이려나요ㅎㅎ
아무튼 저는 특정 아키텍쳐의 단점들이 분명하게 느껴진다면..그때부턴 그럼 다른 아키텍쳐를 생각하는게 맞다고 생각하는 편입니다:) 
두분은 좋은 아키텍쳐가 뭐라고 생각하는지 궁금하네요!

2022-12-22 14:18 UTC, junbangg commented on Diary/Sources/Controller/DiaryWriteViewController.swift
> +    let contentTextView: UITextView = {
요 두 녀석들은 private 이 불가한가요??

2022-12-22 14:18 UTC, junbangg commented on Diary/Sources/Controller/DiaryWriteViewController.swift
> +        view.backgroundColor = .systemBackground
이 친구는 왜 개별 메서드 안에 없나요??? (틀렸다는건 아닙니다)

2022-12-22 14:18 UTC, junbangg commented on Diary/Sources/Controller/DiaryListViewController.swift
> +        let safeArea = view.safeAreaLayoutGuide
요렇게 하시는 배경? 이유?가 무엇인지 궁금합니다(틀렸다는거 아닙니다 오히려 좋아요)

2022-12-22 14:18 UTC, junbangg commented on Diary/Sources/Controller/DiaryWriteViewController.swift
> +        )
`removeObserver` 코드가 안보이는군요??
일부러 안해주신걸까요?? 우리는 `removeObserver` 를 언제 그리고 왜 사용해야될까요??

2022-12-22 14:18 UTC, junbangg commented on Diary/Sources/View/DiaryListViews/DiaryContentConfiguration.swift
> +    }
오 요 메서드는 무슨 일을 해주는건가요?

2022-12-22 14:18 UTC, junbangg commented on Diary/Sources/View/DiaryListViews/DiaryListCell.swift
> +        accessoryType = .disclosureIndicator
이 부분은 왜 해당 메서드에 포함된건가요??

2022-12-22 14:18 UTC, junbangg commented on Diary/Sources/View/DiaryListViews/DiaryListCellContentView.swift
> +        appliedConfiguration = configuration
요거 로직 좀 설명해주실 분!
새로운 configuration으로 갈아끼우는?게 맞나요?

2022-12-22 14:18 UTC, junbangg commented on Diary/Sources/View/DiaryListViews/DiaryListCellContentView.swift
> +    }
apply 라는 메서드가 너무 많은 일을 하고 있는게 아닌가 라는 느낌이 조금 드네요!

2022-12-22 14:18 UTC, junbangg commented on Diary/Sources/View/DiaryListViews/DiaryListCellContentView.swift
> +        }
오👍

2022-12-22 14:18 UTC, junbangg commented on Diary/Sources/View/DiaryListViews/DiaryListCellContentView.swift
> +    private func setupInternalViews() {
여기 메서드명에 있는 인터널뷰즈 가 무얼 의미하는건가요??

2022-12-22 14:18 UTC, junbangg commented on Diary/Sources/Model/Diary.swift
> +    var createDate: String? {
흠 `createdDate` 는 어떠신가요??

2022-12-22 14:18 UTC, junbangg commented on Diary/Sources/Controller/DiaryWriteViewController.swift
> +// MARK: Business Logic
마크 주석을 통해 코드 정리를 잘 해주셨는데 나누는 기준? 같은게 있었을까요???

2022-12-22 14:18 UTC, junbangg commented on Diary/Sources/Extensions/Date+.swift
> +extension Date {
전반적으로 extension을 많이 사용해주셨는데 어떤 기준으로 사용하기로 하셨는지 궁금합니다 (틀렸다는거 절대 아닙니다🙅‍♂️)

2022-12-23 02:13 UTC, lxodud commented on Diary/Sources/View/DiaryListViews/DiaryListCellContentView.swift
> +        }
감사합니다 ㅎㅎㅎㅎ

2022-12-23 02:34 UTC, lxodud commented on Diary/Sources/Controller/DiaryWriteViewController.swift
> +        )
일부러 안해준 부분은 아니고, 잘 몰랐습니다 😓😓😓
removeObserver를 뷰가 사라질 때 제거해 줘야 합니다. 그 이유는 Observer를 제거하지 않는 상황에서 다시 뷰가 나타났을 때  노티피케이션이 중복해서 등록됩니다. 이때 NotificiationCenter가 전역으로 노티를 보내게 되면 해당되는 알림을 중복해서 잡기때문에 메서드가 중복해서 불리게 되는 문제가 있습니다.
이를 방지하기 위해서 viewWillDisappear에서 Observer를 제거하는 작업을 추가하였습니다.

2022-12-23 02:37 UTC, leegyoungmin commented on Diary/Sources/Controller/DiaryWriteViewController.swift
> +        view.backgroundColor = .systemBackground
한줄의 메서드를 개별적인 함수로 빼는 것이 코드를 읽는 사람에 입장에서 생각해보았을때, 더 가독성이 낮아 질 수 있다고 생각하였습니다.
가령, 예를 들어서, 한 줄의 메서드를 함수로 감싸져 있다면, 읽는 사람의 입장에서는 어떤 역할을 하는 함수인지를 알기 위해서 다시 함수를 타야 하는 점에서 가독성이 낮아진다고 생각하였습니다.

2022-12-23 02:59 UTC, leegyoungmin commented on Diary/Sources/Controller/DiaryListViewController.swift
> +        let safeArea = view.safeAreaLayoutGuide
화면을 회전시켰을때, View에 결려있는 것과 safeArea에 걸려있는 것은 시각적으로 다르다고 알고 있습니다.
view에 직접적으로 제약사항을 주었을 때에는 노치가 있는 부분에 제약사항이 생성되기 때문에 작성하는 글과 다양한 부분들이 잘리게 됩니다. 

그렇기 때문에 safeArea에 제약을 걸어 주었고, 추가적으로 반복적으로 사용하는 코드를 줄이기 위해서 상수로 선언후, 메서드 수행 후 없어질 수 있도록 하였습니다.

2022-12-23 03:04 UTC, lxodud commented on Diary/Sources/View/DiaryListViews/DiaryContentConfiguration.swift
> +    }
`updated(for state:)` 메서드의 역할은 지정된 상태에 대한 구성을 생성합니다.
즉, 사용자와의 상호작용을 통해서 변경된 상태에 대해서 업데이트된 구성을 반환하는 메서드 입니다.
아직은 상태변화가 없기 때문에 다른 처리를 하지 않았습니다!!

2022-12-23 03:21 UTC, lxodud commented on Diary/Sources/View/DiaryListViews/DiaryListCell.swift
> +        accessoryType = .disclosureIndicator
해당 메서드는 cell의 configuration을 업데이트하는 메서드인데 저희가 잘못이해해서 cell 전체에 대한 업데이트를 담당하는 메서드로 생각하였습니다. 해당 작업을 dataSource에서 해주었습니다.

2022-12-23 03:45 UTC, leegyoungmin commented on Diary/Sources/View/DiaryListViews/DiaryListCellContentView.swift
> +        appliedConfiguration = configuration
새로운 구성이 들어왔을 때, 변화가 없는데 데이터를 다시 설정하는 것은 필요없는 작업을 하는 것이라고 생각했습니다.
그래서, 구성을 저장해두고 있다가 새로운 구성이 들어왔을 때 같은 구성인 경우에는 데이터를 변경하지 않고 바로 리턴을 시키는 로직입니다.

저희가 실험을 해본 결과, 상태가 변경되어서 state에 따른 변화를 주었을 때에만 데이터를 업데이트 할 수 있도록 구성하기 위해서 다음과 같은 로직을 작성했습니다.

예를 들어서, 상태 변경에 따라 데이터가 변경되면 데이터를 업데이트 해야 하지만, 상태가 변경된 후에도 데이터가 바뀌지 않았다고 하면 데이터를 업데이트 할 이유가 없습니다.

2022-12-23 03:56 UTC, leegyoungmin commented on Diary/Sources/View/DiaryListViews/DiaryListCellContentView.swift
> +    }
configureDynamicFont 메서드가 init에서 수행 할 수 있도록 변경하였습니다.

2022-12-23 03:59 UTC, lxodud commented on Diary/Sources/View/DiaryListViews/DiaryListCellContentView.swift
> +    private func setupInternalViews() {
컨텐츠뷰 내부에 뷰를 설정한다는 의미입니다!!
혹시 네이밍에서 어떤 역할을 하는지 명확하지 않았나요 ㅠㅠㅠ

2022-12-23 04:02 UTC, lxodud commented on Diary/Sources/Model/Diary.swift
> +    var createDate: String? {
저희가 놓친 부분인 것 같네요 ㅠㅠ
createdDate로 수정하였습니다!!

2022-12-23 04:06 UTC, leegyoungmin commented on Diary/Sources/Controller/DiaryWriteViewController.swift
> +// MARK: Business Logic
뷰를 구성하는 부분과 비즈니스 로직을 중점적으로 구분하고, 양쪽에 포함되기 힘든 로직 같은 경우에는 따로 extension으로 구분하였습니다.
또한, 마크를 작성하는 부분은 로직이 담겨있는 것은 Logic이라는 명칭으로 표현하였고, 구성하는 함수들 같은 경우에는 Configuration이라는 단어로 표현하였습니다.

정확하게 마크를 다는 기준 같은 것이 있을까요?

2022-12-23 04:08 UTC, lxodud commented on Diary/Sources/Extensions/Date+.swift
> +extension Date {
전역적으로 사용하는 메서드의 경우 extension으로 구현해 주었습니다!!
알라딘은 어떠한 기준으로 extension을 사용하시는지 궁금합니다 🤔🤔🤔

2022-12-23 04:11 UTC, lxodud commented on Diary/Sources/Controller/DiaryWriteViewController.swift
> +    let contentTextView: UITextView = {
다른 로직 신경쓰다가 깜빡했네요 ㅠㅠㅠ
private 붙여서 수정 완료했습니다 👍👍👍

2022-12-23 04:53 UTC, leegyoungmin commented
### Delegate 메서드를 다른 타입으로 구현하기??
글을 잘 못써서 명확하게 전달이 되지 않은 것 같아서 다시 한번 작성해봅니다.
저희가 위에 말씀드린 부분은 ViewController가 UITableViewDelegate의 역할을 하고 있는 상황에서 다른 타입이 UITableViewDelegate를 채택하고, ViewController가 해당 타입의 인스턴스를 생성하여 TableView의 Delegate를 해당 인스턴스로 선언해 주는 것이 역할을 줄일 수 있는지에 대해서 궁금했었습니다.
예를 들어서 아래와 같은 코드를 작성하는 경우입니다.

```swift
class CustomDelegate: UITableViewDelegate {
    ...
}

class CustomViewController: UIViewController {
    let customDelegate = CustomDelegate()
    let tableView = UITableView()
    
    override func viewDidLoad() {
        tableView.delegate = customDelegate
    }
    ...
}
```

### 고려해본 패턴
깊게 생각한 패턴은 아직 없습니다. 하지만, ViewController가 NavigationController에게 일을 시키는 것이 적절한지에 대한 의문에서 생각해보게 되었습니다. 단일 책임 원칙에서 ViewController가 NavigationController의 역할을 침범하고 있다는 생각이 들었습니다. 그래서 추가적으로 공부를 하면서, Coordinator 패턴을 활용하여서 ViewController가 자신의 역할만 수행할 수 있도록 하는 것은 어떤지에 대해서 생각해보게 되었습니다.

알라딘이 말씀해주신 것처럼 어떤 패턴을 쓰자로 생각하는 것은 좋지 않다고 생각합니다. 알라딘이 생각하시기에는 Coordinator 패턴을 사용하는 것이 적절한지 궁금합니다. 

### 좋은 아키텍처에 대한 고찰...?
역할 분리가 잘 되어 있는 것이 좋은 아키텍쳐의 부분 중 하나일 것이라고 생각합니다. 하지만, 명확하게 어떤 것이 좋은 아키텍쳐 인지는 알지 못하였습니다. 꾸준히 고민해봐야 하는 문제라고 생각이 듭니다. 혹시 이와 관련된 서적같은 것이 있을 까요? (클린 아키텍쳐는 너무 길어요... ㅋㅋㅋㅋ)

2022-12-25 15:01 UTC, junbangg commented on Diary/Sources/Controller/DiaryWriteViewController.swift
> +        )
공부를 지대로 하셨군요!!! 굳굳!👍

2022-12-25 15:05 UTC, junbangg commented on Diary/Sources/View/DiaryListViews/DiaryContentConfiguration.swift
> +    }
아 그럼 추후에 로직이 추가될 수 있는건가요???
추후에 추가될 로직이 분명히 있는거면 `TODO: ` 주석 추가해놓는것도 나쁘지 않은것 같아요!

2022-12-25 15:11 UTC, junbangg commented on Diary/Sources/View/DiaryListViews/DiaryListCellContentView.swift
> +    private func setupInternalViews() {
역할은 명확했는데 `Internal` 이라는 표현이 조금 어색하게 느껴진것 같아요!!
`Internal` 이라는 표현이 (물론 전혀 다른 개념이긴 하지만) 접근제어 관련 용어 이기도 해서 차라리 `setupViews` , `setupSubviews` 같은 메서드명은 어떨까라는 생각을 하긴 했습니다:)

2022-12-25 15:12 UTC, junbangg commented on Diary/Sources/Controller/DiaryWriteViewController.swift
> +// MARK: Business Logic
아뇨! 그냥 궁금해서 여쭤봤습니다~~~

2022-12-25 15:13 UTC, junbangg commented on Diary/Sources/Extensions/Date+.swift
> +extension Date {
저도 비슷해요! 전역적으로 사용될 수 있고, 특정한 비즈니스 로직에 대한 디펜던시가 없다면(여러 상황에서 재사용될 수 있으면) 사용하는것 같아요~

2022-12-25 15:13 UTC, merged

2022-12-25 15:26 UTC, junbangg commented
```
저희가 위에 말씀드린 부분은 ViewController가 UITableViewDelegate의 역할을 하고 있는 상황에서 다른 타입이 UITableViewDelegate를 채택하고, ViewController가 해당 타입의 인스턴스를 생성하여 TableView의 Delegate를 해당 인스턴스로 선언해 주는 것이 역할을 줄일 수 있는지에 대해서 궁금했었습니다.
```

> 음.. 저는 개인적으로는 불필요한거 같아요!
`Delegate` 패턴이 여러가지 이점을 주지만.. 코드를 읽을때 끊긴다는 느낌을 가끔 받아보셨을거라고 생각합니다:) 물론 필요할때는 타입간의 결합도도 낮출 수 있고 정말 좋죠! 하지만 지금 같은 경우에는`CustomDelegate` 이라는 친구가 `TableViewDelegate` 랑 다를게 없다면..?즉, 별 다른 역할 없이 오로지 역할 분리를 위해 하나의 `Delegate` 를 사이에 끼워 넣는 느낌이라면 코드 흐름만 끊어놓는게 아닌가 라는 개인적인 의견입니다:)

```
알라딘이 생각하시기에는 Coordinator 패턴을 사용하는 것이 적절한지 궁금합니다.
```

> Coordinator 패턴! 필요하다고 느끼고 채택하는 근거만 있다면 아주 좋습니다:) 

```
역할 분리가 잘 되어 있는 것이 좋은 아키텍쳐의 부분 중 하나일 것이라고 생각합니다. 하지만, 명확하게 어떤 것이 좋은 아키텍쳐 인지는 알지 못하였습니다. 꾸준히 고민해봐야 하는 문제라고 생각이 듭니다. 혹시 이와 관련된 서적같은 것이 있을 까요? (클린 아키텍쳐는 너무 길어요... ㅋㅋㅋㅋ)
```

> 클린 아키텍쳐 정말 어렵고 길죠 책이... 저도 근데 그거 밖에 읽어본 책이 없습니다...ㅋㅋㅋㅋ

좋은 아키텍쳐가 무엇인지 저도 고민을 많이 해봤는데요..
개인적으로는 **어떤 아키텍쳐를 사용하지?** 보다는 **아키텍쳐로 해결하려고 하는 문제들이 뭐지?** 가 더 중요한 이야기인것 같아요!

2022-12-26 01:11 UTC, leegyoungmin commented on Diary/Sources/View/DiaryListViews/DiaryListCellContentView.swift
> +    private func setupInternalViews() {
STEP2 진행하기 전에 같이 수정할 수 있도록 하겠습니다.