일기장 [STEP 1] inho, Dragon
yagom-academy/ios-diary pull request #64
Opened 2022-12-21 09:46 UTC by FlameYG

안녕하세요, 쿠마(@leejun6694)🙇‍🙇‍♀️!
[inho🐶](https://github.com/inho-98), [Dragon🐉](https://github.com/FlameYG)입니다!
이번 스텝에서는 코드로 UI구성 하는 것을 제외하면 이전 프로젝트에서 다뤄본 내용이 많아서 수월하게 진행할 수 있었습니다!
그래도 보완했으면 하는 부분이 있다면 코멘트 마구마구 달아주세요🔥 리뷰 잘부탁드리겠습니다😁

## 📍고민했던 부분 
### `DateFormatter`를 재사용하는 방법
- `DateFormatter`를 사용하려고 찾아보던 중에 해당 객체가 사용할때 비용이 많이 들어서 효율적으로 사용하는 방법을 적용했습니다.
- 타입 프로퍼티로 저희 코드에 사용될 한글형식으로 날짜를 나타내는 `koreanDateFormatter`를 구현하여, 한번만 인스턴스를 만들고 그 뒤에 재사용하는 식으로 구현하였습니다.

### 일기장 추가 화면 및 편집 화면의 구성 방법
- 일기장 앱의 화면 중에 +버튼을 눌렀을때 보이는 추가 화면과, 기존의 일기장 목록을 눌러 편집할때의 화면 구성이 동일하다고 판단하였습니다. 그래서 일기를 입력하는 양식을 나타내는 `DiaryFormView`와 해당 뷰를 담는 `DiaryFormViewController`를 구현하였고, 추후에는 두 클래스를 재사용하는 방식으로 구현할 예정입니다. 
- 재사용을 위해 구현하다보니 두 클래스의 네이밍이 포괄적으로 작성되어서, 이런 모호성은 추후에 일기장 수정 화면을 구현할때 구체적인 네이밍으로 변경하거나, 분리하여 구현하도록 수정될 수도 있을것 같습니다!

### 일기장 추가 화면시 화면 전환 방법
- 일기를 추가하기 위해 +버튼을 눌렀을때 모달 형식으로 화면이 전환되어야 한다고 생각했습니다. 그런데 애플의 기본 메모장 앱을 참고해 보니, 새로운 메모를 작성할때 `push`로 화면이 전횐되는걸 확인할 수 있었습니다. 
- 결과적으로 저희도 같은 방식인 `push`로 화면을 전환하도록 구현하였습니다.
기본앱에서 그렇게 구현되어 있는 이유를 고민했을때, 기존의 메모를 수정하는것과 새로 작성하는 기능이 동일하여 전체 로직과 비슷한 화면을 보여주기 때문이라고 생각하였습니다.🤔

## 📍조언을 얻고싶은 부분

### `ContentOffset`으로 키보드 높이 처리시 `Return`키 제어
- `DiaryFormView-diaryTextView`에서 키보드로 입력을 할 경우 화면에 올라오는 키보드 높이를 어떻게 처리해줘야할지 고민해봤었습니다. 
- 저희가 조사해본 결과 아래 2가지 방법을 알게 되었고 현재 코드에는 `ContentInset`을 사용하였습니다.
    - `ContentInset`을 사용한 동작은 키보드가 올라오는 속도가 다소 느리게 확인되었습니다.
    - 그러하여, 이 부분을 개선하고자 `ContentOffset`을 사용하길 원했지만 커서를 키보드가 올라올 위치에 두고 키보드를 올려 return키를 누르면 키보드가 올라와 있지만 키보드가 내려간 것처럼 인식되어 오작동이 발생하는 것을 확인하였습니다.
        - `ContentOffset`을 사용할 경우 `return`키를 어떻게 제어해줘야할지 조언 부탁드립니다🧐

### `Present` 화면전환시 `BackBarButton` 구현 방법
- `MainViewController <-> DiaryFormViewController`간의 화면전환시 `Present`방식으로 화면 전환을 하고자 하였습니다.
- 그런데 `DiaryFromVC -> MainViewVC`로 이동시 `BackBarButton` 적용이 되지않고, `LeftBarButton`으로 `Dismiss`를 하고자할 때, `<` 표시가 기본적으로 없는 것을 확인하였습니다.
    - `title`에서 문자보간법으로 `<` 를 사용하는 것이 아닌 `leftBarButtomItems`를 사용하여 `<`와 `일기장` 두가지의 버튼을 모두 추가하는 방법을 사용했었지만, 두 버튼 사이에 정해진 간격이 의도하는 길이와 달랐고, 이 간격을 줄이는 문제를 해결하지 못하였습니다...
    - 최종적으로는 고민했던 부분에 작성한 `일기장 추가 화면시 화면 전환 방법`을 통해 push 화면전환시에 나타나는 `BackBarButton`을 사용하였습니다.
        - 혹시 `Present` 화면전환방식에서 `<(BackBarButton)`를 구현하는 방법을 아신다면 조언 부탁드립니다🧐

2022-12-22 16:26 UTC, leejun6694 requested changes
@inho-98 @FlameYG 안녕하세요~!
전체적으로 코드를 깔끔하게 작성해주셔서, 편하게 읽으면서 리뷰할 수 있었습니다.
몇 가지 코멘트를 남겼는데, 확인 부탁드립니다 : )

2022-12-22 16:26 UTC, leejun6694 commented on .swiftlint.yml
> +included:
👍 👍

2022-12-22 16:26 UTC, leejun6694 commented on Diary/Source/Controller/DiaryFormViewController.swift
> +    }
쭉 코드를 나열하는 것도 좋지만, 호흡을 쉬기도 하고 역할을 구분해주는 의미에서 주석을 추가해보는건 어떨까요?
```
final class DiaryFormViewController: UIViewController {
     // MARK: Properties

     private let diaryFormView = DiaryFormView()

     // MARK: Life Cycle

     override func viewDidLoad() {
          ...
     }

     // MARK: Private Methods
     private func configureDiaryViewLayout() {
          ...
     }
}
```

2022-12-22 16:26 UTC, leejun6694 commented on Diary/Source/Controller/DiaryFormViewController.swift
> +    }
저는 ViewController 에는 properties 와 life cycle method 만 두고, 나머지는 extension 으로 만들어서 구분해주는 편입니다 ㅎㅎ (참고만 해주세요~)

2022-12-22 16:26 UTC, leejun6694 commented on Diary/Source/Controller/DiaryFormViewController.swift
> +        let date = Date()
굳이 변수로 만들어야할까..? 라는 생각은 드네요 ㅎㅎ

2022-12-22 16:26 UTC, leejun6694 commented on Diary/Source/Controller/MainViewController.swift
> +        view = mainDiaryView
view 에 `subView` 로 추가하지 않고, view 자체를 교체해준 이유가 궁금합니다 : )

2022-12-22 16:26 UTC, leejun6694 commented on Diary/Source/Controller/MainViewController.swift
> +        navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .add,
소괄호 이후 첫번째 parameter 앞에서 줄바꿈을 해주는 케이스가 있는데, 여기는 두번째 parameter 에서 줄바꿈하고 있네요.
한가지 컨벤션으로 통일했으면 합니다~!
(개인적으로는 줄을 짧게하기 위해 첫번째 parameter 에서 줄바꿈하고 있습니다.)

2022-12-22 16:26 UTC, leejun6694 commented on Diary/Source/Controller/MainViewController.swift
> +private enum NameSpace {
👍

2022-12-22 16:26 UTC, leejun6694 commented on Diary/Source/Extension/DateFormatter + Extension.swift
> +    static let koreanDateFormatter: DateFormatter = {
🥇

2022-12-22 16:26 UTC, leejun6694 commented on Diary/Source/View/CustomDiaryCell.swift
> +
`cell` 은 재사용될 수 있습니다.
이를 위해서 우리는 어떤 준비를 해주어야할까요?

2022-12-23 01:29 UTC, inho-98 commented on Diary/Source/Controller/DiaryFormViewController.swift
> +    }
extension에만 주석을 추가했었는데, 프로퍼티와 라이프 사이클 코드에도 추가하는 방식을 짚어주셔서 적용했습니다 😁

2022-12-23 01:29 UTC, inho-98 commented on Diary/Source/Controller/DiaryFormViewController.swift
> +        let date = Date()
수정했습니다! 🙂

2022-12-23 01:33 UTC, inho-98 commented on Diary/Source/Controller/MainViewController.swift
> +        view = mainDiaryView
이전에는 매번 `addSubview`의 방식을 사용하다가 뷰컨의 `view`를 교체할 수 있다는 점을 알게 됐고,
`MainDiaryView`를 구현할때, 해당 화면의 모든 뷰를 구현해서 자연스럽게 `view`를 교체해도 된다고 생각했습니다..! 🧐

2022-12-23 01:33 UTC, inho-98 commented on Diary/Source/Controller/MainViewController.swift
> +        navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .add,
첫번째 파라미터에서 개행하는 식으로 컨벤션 통일하였습니다! 🙂

2022-12-23 01:34 UTC, inho-98 commented on Diary/Source/View/CustomDiaryCell.swift
> +
힌트 주신 그대로 `prepareForReuse`메서드를 재정의하였습니다! 🙂

2022-12-24 10:25 UTC, leejun6694 approved these changes
LGTM
크리스마스 잘 보내시고, 다음 주에 궁금한 점들 얘기 나눠봐요~~!
고생하셨습니다 : )

2022-12-24 10:25 UTC, merged