일기장 [STEP 1] 애런, 로빈, 건디
yagom-academy/ios-diary pull request #65
Opened 2022-12-21 11:27 UTC by yuvinrho

![](https://i.imgur.com/FZ21nXs.png)

@ryan-son
안녕하세요 라이언~ 애런, 로빈, 건디입니다!
디스코드 방에 와주셔서 반가웠습니다~ 
이번 프로젝트 잘 부탁드립니다!!

## 🤔 고민했던 점
### 테이블 뷰 vs 콜렉션 뷰 선택
ios 14 버전부터 콜렉션 뷰에서도 리스트 셀 구현이 가능하도록 틀을 제공해주어서 메인화면 일기장 리스트를 테이블뷰를 사용할지 콜렉션 뷰를 사용할지 고민했습니다. 아래 HIG에 컨텐츠가 텍스트인 경우 테이블뷰를 사용하라고 해서 최종적으로 테이블 뷰를 사용하여 구현하였습니다.

![](https://i.imgur.com/RyVS78B.png)
[HIG - Lists and tables](https://developer.apple.com/design/human-interface-guidelines/components/layout-and-organization/lists-and-tables)

### Diffable Data source 사용 여부
`table View`를 사용하면서 `data source` 부분을 무엇으로 사용할 지 고민했습니다.
```swift
private func configureDataSource() {
        dataSource = DiaryDataSource(tableView: diaryListTableView, cellProvider: { tableView, indexPath, diary in
            guard let cell = tableView.dequeueReusableCell(withIdentifier: DiaryListCell.reuseIdentifier,
                                                           for: indexPath) as? DiaryListCell else {
                return DiaryListCell()
            }

            cell.titleLabel.text = diary.title
            cell.subtitleLabel.attributedText = self.configureSubtitleText(diary.createdDate, diary.body)
            
            return cell
        })
    }
```

`Diffable DataSource`는 `Cell`에 어떤 종류의 데이터가 들어갈지만 정해놓고, 데이터를 `Snapshot` 형태로 사진을 찍어서 `View`에 반영 하는 방식입니다.
- `View`를 다시 그릴 때 `Snapshot`의 변화를 스스로 파악하고 애니메이션으로 자연스럽게 연결되기 때문에 유저 경험적 측면을 위함
- 데이터 동기화 문제나 예외 충돌 상황 등을 커버 할 수 있음

다음과 같은 이유로 Diffable Data를 사용하였습니다.

### KeyboardLayoutGuide 사용
- 이전 프로젝트에는 노티피케이션과 딜리게이트를 이용하여 키보드가 컨텐츠를 가리지 않도록 구현하였습니다.
- 구글링 중 iOS 15버전부터 KeyboardLayoutGuide가 나와서 새롭게 나왔다고 해서 이번에 사용해보았습니다.

### Diary 타입 Class vs Struct 선택
- JSON 파일에 맞게 Diary 타입을 구현할 때, class를 사용할지 struct를 사용할지 고민했습니다.
- [애플 문서](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes)에서 기본적으로 구조체를 사용하지만 모델링중인 데이터의 ID를 제어해야 하는 경우 클래스를 사용하라고 되어있었습니다.
- 이번 프로젝트에서 일기 데이터를 코어데이터에 저장, 수정, 삭제가 필요하기에 데이터의 ID를 제어한다고 생각해서 최종적으로 Class를 선택하였습니다.

### 최후의 한마디
이번 스텝에서는 샘플 일기데이터를 리스트에 뿌려주는 것을 테스트하기 때문에 아래와 같이 snapshot()설정하는 부분에 json을 뜯어서 데이터소스에 적용하도록 하였습니다. 추후 step2가 공개되면 그에 따라 구현할 예정입니다~
```swift
private func configureSnapshot() {
    let jsonDecoder = JSONDecoder()
    guard let data = NSDataAsset.init(name: "sample")?.data,
          let items = try? jsonDecoder.decode([Diary].self, from: data) else {
        return
    }
    
    sampleDiaryList = items
    
    snapshot.appendSections([0])
    snapshot.appendItems(items)
    
    dataSource.apply(snapshot)
}
```

## 🧑‍🏫 조언을 얻고 싶은 부분
### iOS 버전 타겟
<img src="https://i.imgur.com/rFGOPgN.png" height="400"/>
이번에 Keyboard Layout Guide를 사용하면서 저희가 생각해본 부분입니다. Apple에서 제공하는 위 통계에 따르면 2022년 5월 31일 기준 지난 4년간의 기기중 89%가 iOS 15버전 이상을 사용합니다. 저희는 이번 프로젝트 타겟을 iOS 15.0으로 선택했는데, 이정도로 높은 버전을 타겟으로 삼는 것은 지양해야 하는 것일까요? 개발자가 타겟 버전을 바라볼 때 가져야할 태도에 대해서 라이언은 어떻게 생각하시는지 궁금합니다.

### Keyboard Layout Guide 사용시 inset
```swift!
 private func configureLayout() {
        NSLayoutConstraint.activate([
            ...
            scrollView.bottomAnchor.constraint(equalTo: view.keyboardLayoutGuide.topAnchor),
            ...
        ])
    }
```
위와 같이 `keyboardLayoutGuide`를 사용했는데
<img src = "https://i.imgur.com/2iAAJ9S.gif" height=500> 
다음과 같이 화면에서 줄바꿈을 계속 진행하다보면 현재 입력중인 커서의 위치가 키보드에 가려지는 문제가 있었습니다.

```swift!
scrollView.contentInset = UIEdgeInsets(top: 0, left: 0, bottom: 20, right: 0)
```
다음과 같이 `contentInset`을 사용해 해결했지만 왜 이런 문제가 발생하는지 잘 모르겠습니다.
그리고 `contentInset`을 사용하는 방식은 `notification`을 사용하는 방식과 차이가 없어 올바른 해결 방법인지 궁금합니다.

### modal 스타일
새로운 diary를 만들기 위해 + 버튼을 눌렀을 때 화면 전환되는 방식에 대해서 기능 명세에는 나와있지 않았기 때문에 저희는 네비게이션으로 이를 처리할지 모달로 처리할지 고민하였습니다. 기존의 리스트와는 전혀 흐름이 다른 새로운 흐름이라고 판단해 모달로 뷰를 띄우는 것이 적절하다고 생각했습니다. 화면에 대한 이미지나 가이드라인이 없지만 `일기장 화면의 제목 부분에는 일기 생성 날짜를 표기합니다`의 문구를 단서로 삼아 네비게이션 컨트롤러는 필요하다고 생각했고, 네비게이션 바가 있기 때문에 처음엔`modalPresentationStyle`을 `fullScreen`으로 사용해서 전부 덮었습니다. 하지만 모달의 특성을 생각해보고, 비슷한 경우로 보이는 기본 알람 앱을 예시로 삼아 modalPresentationStyle을 수정하였습니다.

<img src="https://i.imgur.com/Z5xTNna.png" height="400"/>

혹시 라이언께서는 이런 상황에서 어떤 modalPresentationStyle이 적절하다고 생각하시나요? 그리고 fullScreen인 경우는 보통 어떤 때에 쓰는지도 궁금합니다.

2022-12-22 08:42 UTC, ryan-son requested changes
건디, 로빈, 애런, 고생 많으셨습니다. 아무래도 한 번은 다뤄본 요소들이라 어느정도 친숙했죠?

코드의 컨벤션은 여러분 나름대로 정해서 잘 적용하고 계신 것 같고, UI 구성에 관련된 코드가 대부분이라 코멘트 드릴 부분은 많지 않았습니다. 질문하신 것만 짚어볼게요.

> ### iOS 버전 타겟
> 이번에 Keyboard Layout Guide를 사용하면서 저희가 생각해본 부분입니다. Apple에서 제공하는 위 통계에 따르면 2022년 5월 31일 기준 지난 4년간의 기기중 89%가 iOS 15버전 이상을 사용합니다. 저희는 이번 프로젝트 타겟을 iOS 15.0으로 선택했는데, 이정도로 높은 버전을 타겟으로 삼는 것은 지양해야 하는 것일까요? 개발자가 타겟 버전을 바라볼 때 가져야할 태도에 대해서 라이언은 어떻게 생각하시는지 궁금합니다.

개발자가 타겟 버전에 대해서 바라보는 태도가 하나라고 생각하지 않습니다. 예를 들어 아래 요소들에 따라 종합적으로 판단해야 할 문제입니다.

1. 기존에 앱스토어에 등록되어 운영되던 서비스인가?
2. 사용자의 연령층의 분포는 어떤가?
3. 현재 사용자들의 OS 분포는 어떤가?
4. 새로운 API를 사용해야 현재 직면한 문제를 해결할 수 있는가?
5. 현재 마케팅이 잘 이루어져서 이용자 수가 적지 않은 수준인가(조직별 상대적임)?
6. App Store Featured를 받을 수 있는 서비스인가(폐쇄형 서비스는 어려움)?
7. 최근 1~2년 내 WWDC에서 소개된 신기능을 적용해 사용자를 만족시킬 수 있는가?
...

그래도 항상 업계에는 `통상적`인 경우가 존재하기는 하죠. 이 기준은 위의 요소들을 종합적으로 판단해봤을 때 이 정도면 적당하다..하는 수준입니다. 한국에서는 주로 2년 전에 도입된 OS를 타겟으로 잡는 경우가 많습니다(카카오톡의 정책). 카카오톡은 지난 11월 7일에 타겟 OS를 iOS 14.0으로 올렸습니다.

![image](https://user-images.githubusercontent.com/69730931/209088936-1b29db08-d75b-449d-be67-b94842bf7ac0.png)


>### Keyboard Layout Guide 사용시 inset
>다음과 같이 화면에서 줄바꿈을 계속 진행하다보면 현재 입력중인 커서의 위치가 키보드에 가려지는 문제가 있었습니다.
>다음과 같이 `contentInset`을 사용해 해결했지만 왜 이런 문제가 발생하는지 잘 모르겠습니다.
>그리고 `contentInset`을 사용하는 방식은 `notification`을 사용하는 방식과 차이가 없어 올바른 해결 방법인지 궁금합니다.

`containerStackView`의 크기가 변경 됐지만 UIScrollView는 뷰를 업데이트 해야한다고 판단하지 않기 때문에 이런 현상이 발생합니다. 여러분이 View drawing cycle이라고 알고 계신 것이죠. `UITextView`에 변경이 생길 때마다 `UIScrollView`를 다시 그려달라고 메시지를 보내면 문제를 해결할 수 있지만, 강제로 뷰를 업데이트하는 동작은 에너지 소모가 적지 않기 때문에 권장드리지는 않습니다. 말씀해주신 방안으로 해결하는 것은 괜찮은 해결 방법입니다. 생각해보신 것에서 dynamic type을 지원하게 되었을 때 inset도 여전히 20으로 충분할지, 반응해서 값을 변경해줄 수 있을지 생각해보시면 더 좋을 것 같네요.

>### modal 스타일
>새로운 diary를 만들기 위해 + 버튼을 눌렀을 때 화면 전환되는 방식에 대해서 기능 명세에는 나와있지 않았기 때문에 저희는 네비게이션으로 이를 처리할지 모달로 처리할지 고민하였습니다. 기존의 리스트와는 전혀 흐름이 다른 새로운 흐름이라고 판단해 모달로 뷰를 띄우는 것이 적절하다고 생각했습니다. 화면에 대한 이미지나 가이드라인이 없지만 `일기장 화면의 제목 부분에는 일기 생성 날짜를 표기합니다`의 문구를 단서로 삼아 네비게이션 컨트롤러는 필요하다고 생각했고, 네비게이션 바가 있기 때문에 처음엔`modalPresentationStyle`을 `fullScreen`으로 사용해서 전부 덮었습니다. 하지만 모달의 특성을 생각해보고, 비슷한 경우로 보이는 기본 알람 앱을 예시로 삼아 modalPresentationStyle을 수정하였습니다.
>혹시 라이언께서는 이런 상황에서 어떤 modalPresentationStyle이 적절하다고 생각하시나요? 그리고 fullScreen인 경우는 보통 어떤 때에 쓰는지도 궁금합니다.

- 화면을 어떤 방식으로 표현할지와 꽉 채울지 말지는 기획 의도에 따라 달라질 수 있습니다(회사에는 기획자가 별도로 있을 수 있지만 캠프에서는 여러분이 기획자가 될 수 있죠. 물론 기본 기획이 있기는 하지만..).
- 알람이나 미리 알림을 등록하는 동작은 현재 컨텍스트에서 잠깐 벗어나서 끝낼 수 있는 동작이지만, 일기 작성은 그렇지 않을 수 있습니다.
- 예를들어, 아이폰 메모앱을 들 수 있습니다. 메모 작성은 금방 끝날 수도 있지만, 그렇지 않을 수도 있습니다. 현재 컨텍스트를 유지하기 보다는 `글을 쓴다. 그리고 그 행동에 집중한다`라는 의미로 작성 페이지를 push 방식으로 전환하고, 더 넓은 쓰기 영역을 제공하여 집중할 수 있도록 하는 것입니다. push는 `기존 화면의 상세`라는 인식이 있기 때문에 `새 메모를 추가한다`라는 동작과 괴리는 없습니다.
- 모달은 앞서 말씀드렸던 것처럼 기존의 컨텍스트를 유지하는 것이 중요하거나 잠시동안 끝낼 수 있는 행동인 경우에 유효합니다. 음악앱을 떠올려보면 음악을 들으면서도 새로운 음악을 찾아다닐 수 있죠. 이런 경우 push보다는 modal이 어울립니다. 유튜브 앱에서도 화면을 아래로 내리는 동작으로 아래에 재생 상태의 화면을 유지하면서 새로운 컨텐츠를 찾으시죠?
- 정답은 없습니다. iOS 개발자이시기도 하지만 애플이 의도한 디자인을 오래 사용해오신 여러분이 자연스럽다면 고려해볼 수 있는 옵션입니다.

# 개별 피드백 P 태그 안내
각 코멘트에는 P1 ~ P5까지의 태그가 포함되어있습니다. 태그의 의미는 아래와 같으니 참고하세요. [뱅크샐러드 개발 문화](https://blog.banksalad.com/tech/banksalad-code-review-culture/)에서 차용하였습니다.

<img width="786" alt="image" src="https://user-images.githubusercontent.com/69730931/176375527-04436d3c-bb00-4abd-a1d9-224b1c65b9eb.png">

도움이 필요하시면 언제든지 말씀해주세요~

2022-12-22 08:42 UTC, ryan-son commented on .gitignore
> +Pods/
CocoaPods를 이용하셨는데.. Podfile이 어디갔을까요? 
1. [`Podfile`](https://guides.cocoapods.org/using/the-podfile.html)과 [`Podfile.lock`](https://guides.cocoapods.org/using/using-cocoapods.html#what-is-podfilelock)에 대해 알아봅시다.
2. Pods를 git에 포함하지 않으시는 이유는 무엇인가요? [Pods를 git으로 관리할 때의 장단점](https://guides.cocoapods.org/using/using-cocoapods.html#what-is-podfilelock)을 알아봅시다.

2022-12-22 08:42 UTC, ryan-son commented on .swiftlint.yml
> +  - trailing_whitespace
`trailing_whitespace`를 비활성화하는 경우가 많지만, Xcode 설정으로 손쉽게 이 규칙을 지킬 수 있습니다. 이 사실을 논의하기 전에, `trailing_whitespace` 규칙을 어기는 경우는 어떤 경우인지 알고 계신가요~?

![image](https://user-images.githubusercontent.com/69730931/209051329-d6063db5-e061-473a-b3bc-433d9a711c2c.png)

2022-12-22 08:42 UTC, ryan-son commented on .swiftlint.yml
> +  - trailing_comma
배열이나 딕셔너리에 새 요소를 추가할 때 diff를 줄일 수 있어서 저도 disabled_rules에 추가해서 사용하는 편이에요. 여러분은 어떤 의도가 있으셨나요?

2022-12-22 08:42 UTC, ryan-son commented on .swiftlint.yml
> +  - Diary/SceneDelegate.swift
`AppDelegate.swift`와 `SceneDelegate.swift` 모두 여러분의 관리 범위에 있으니 린트 무시 대상에 포함하는 것보다 린트를 맞추는 게 좋아보이는데, 이렇게 결정하신 이유는 무엇이었나요?

2022-12-22 08:42 UTC, ryan-son commented on Diary/App/Assets.xcassets/sample.dataset/Contents.json
> +}
샘플/프리뷰 데이터가 앱에 포함되면 의도치 않게 앱 크기를 늘릴 수 있습니다. 이런 파일을 관리하는 방법을 회의실에서 이야기 나눠봐요~

2022-12-22 08:42 UTC, ryan-son commented on Diary/App/Info.plist
> -					<string>Main</string>
코드로 UI 작업하시는 것을 선호하시나보군요~ 스토리보드와 코드 기반으로 UI 작업하는 것의 장단점을 생각해보셨나요?

2022-12-22 08:42 UTC, ryan-son commented on Diary/Controller/DiaryListViewController.swift
> +    typealias DiarySnapShot = NSDiffableDataSourceSnapshot<Int, Diary>
타입 별칭의 적절한 사용례네요. 길고 복잡한 이름을 목적에 맞는 이름으로 잘 표현하셨습니다. 👍

2022-12-22 08:42 UTC, ryan-son commented on .gitignore
> +Pods/
[P1] Podfile을 git으로 관리해볼까요? Podfile.lock을 git에 포함할지 여부를 논의해보는 것도 재밌겠네요.

2022-12-22 08:42 UTC, ryan-son commented on Diary/Controller/DiaryListViewController.swift
> +    }()
self 인스턴스를 사용하기 위한 용도로 lazy 키워드를 사용하셨네요. Swift Programming Language Guide에 소개된 유용한 사용법 중에 하나죠. 또 달리 lazy 키워드를 사용할만한 경우가 있을까요?

- [Properties/Lazy Stored Properties - Swift Programming Language Guide 5.7](https://docs.swift.org/swift-book/LanguageGuide/Properties.html#ID257)

2022-12-22 08:42 UTC, ryan-son commented on Diary/Controller/DiaryListViewController.swift
> +    private var dataSource: DiaryDataSource!
아무리 확신이 있어도 암시적 옵셔널 해제는 사용하지 않는 편이 좋아요. 출시된 앱에서 런타임 에러를 관찰하다보면 이렇게 확신을 가지고 옵셔널 해제를 한 경우가 의외로 많거든요.

2022-12-22 08:42 UTC, ryan-son commented on Diary/Controller/DiaryListViewController.swift
> +    private var sampleDiaryList: [Diary] = []
앞으로도 sample이라는 의미가 유효할까요?

2022-12-22 08:42 UTC, ryan-son commented on Diary/Controller/DiaryListViewController.swift
> +    }
[P3]
구현을 살펴보면 `다이어리 추가하기` 보다는 `다이어리 추가 페이지 표시하기`를 수행하고 있는 것 같아요. 동료 개발자는 메서드 이름만으로 어떤 기능을 할지 추측하기 때문에 혼동을 주지 않는 이름을 짓는 편이 좋습니다.

2022-12-22 08:42 UTC, ryan-son commented on Diary/Controller/DiaryListViewController.swift
> +    }
[P3]
Navigation 기능을 구성하는 것처럼 보일 수 있으니 확실하게 View와 관련된 작업이라는 것을 알려주면 좋겠어요.

2022-12-22 08:42 UTC, ryan-son commented on Diary/Controller/DiaryListViewController.swift
> +            }
앞으로 TableView를 작성할 때 아래와 같은 패턴이 반복될 것 같은데, 반복되는 패턴을 자동화하는 방법은 없을까요? 생각해보시고 회의실에서 이야기 나눠봅시다.

2022-12-22 08:42 UTC, ryan-son commented on Diary/Controller/DiaryListViewController.swift
> +    }
[P2]
이름은 `스냅샷 구성`인데 디코딩 작업을 포함하고 있네요. 재사용성을 올리고 혼동을 방지하기 위해 메서드를 분리해보는건 어떨까요?

2022-12-22 08:42 UTC, ryan-son commented on Diary/Controller/DiaryViewController.swift
> +    }
[P4]
구현하지 않은 이니셜라이저나 메서드가 있다면 `@available` attribute를 사용해서 사용할 수 없다는 표시를 해두면 좋습니다.

```swift
@available(*, unavailable)
required init?(coder: NSCoder) { ... }
```
![image](https://user-images.githubusercontent.com/69730931/209068876-1df21780-bfd6-44fd-b3b4-96c7b5a274bc.png)


다른 attribute들은 어떤 것이 있는지는 아래 페이지에서 확인해보세요.

- [Attributes - Swift Reference Manual](https://docs.swift.org/swift-book/ReferenceManual/Attributes.html)

2022-12-22 08:42 UTC, ryan-son commented on Diary/Controller/NewDiaryViewController.swift
> +        view.backgroundColor = .systemYellow
[P4]
View controller life cycle에 직접 코드를 작성하는 건 의도를 표현하기 쉽지 않으니 메서드로 감싸서 의도를 표현해주는 것도 좋습니다.

2022-12-22 08:42 UTC, ryan-son commented on Diary/Controller/NewDiaryViewController.swift
> +        let cancelButton = UIBarButtonItem(title: "취소", style: .plain, target: self, action: #selector(cancel))
[target-action 디자인 패턴](https://developer.apple.com/library/archive/documentation/General/Conceptual/Devpedia-CocoaApp/TargetAction.html)의 대안으로 iOS 14.0부터는 [`UIAction`](https://developer.apple.com/documentation/uikit/uiaction)과 [`addAction(_:for:)`](https://developer.apple.com/documentation/uikit/uicontrol/3600490-addaction)을 사용할 수 있습니다. 선호하시는 것으로 사용하세요~

2022-12-22 08:42 UTC, ryan-son commented on Diary/Model/Diary.swift
> +}
[P2]
지금은 계층이라는 개념이 없지만, 같은 타입이더라도 목적에 따라 타입을 달리 만들어 사용하시는 방법도 있습니다. 객체지향 관점에서 역할을 가지고 스스로 책임지는 자율적인 타입을 만드는 데 효과적입니다. 이번 프로젝트에서 한 번 경험해보시는 걸 권해드려요.

- Data Transfer Object(DTO): 네트워크, 로컬 파일과 같이 데이터를 받아올 때
- Domain:  통상적으로 앱 내부에서 다룰 때
- Persistence: 디바이스에 저장하는 등 영속성 기능을 다룰 때(예: CoreData)

```swift
struct DiaryResponseDTO: Decodable { ... }       // Network layer
struct Diary: Hashable { ... }                   // Domain layer
final class DiaryEntity: NSManagedObject { ... } // Persistence layer
```

이후에 계층에 대한 개념이 생기신다면 `경계 간 매핑 전략`, `Mapping Between Boundaries`와 같은 키워드로 검색해보세요.

2022-12-22 08:42 UTC, ryan-son commented on Diary/View/DiaryListCell.swift
> +    }
1. 아래 코드는 동작하나요? 왜 그럴까요?
2. 모든 셀 타입에서 동일한 코드를 이용해도 된다면 이걸 확장할 수 있는 방법도 있을까요?

```swift
static var reuseIdentifier: String {
    return String(describing: self)
}
```

2022-12-22 08:42 UTC, ryan-son commented on DiaryTests/JSONDecodingTest.swift
> +    }
1. `~지` 보다는 `~일때~하면~된다/한다`와 같이 문장형으로 작성해보는 건 어떨까요? 상황(Given), 이벤트(When), 결과(Then)가 보다 더 잘 드러날 것 같아요.
2. 14, 19 라인에서 옵셔널 바인딩에 실패하면 실패 없이 탈출하는데, 이런 경우 테스트는 성공한 것으로 판단합니다. [`XCTFail(_:file:line:)`](https://developer.apple.com/documentation/xctest/1500970-xctfail) 메서드로 테스트가 어떤 이유로 실패했는지 표현해주세요.
3. 애플이 제공하는 프레임워크에서는 예외 처리가 된 메서드의 실패 이유를 자세히 알려줍니다. `try?` 보다 `try`를 사용하는 건 어떨까요? 테스트 메서드에서는 다행히 `do-catch` 대신 메서드 자체를 `throws` 키워드를 통해 throwing function으로 만들 수 있습니다.

2022-12-22 08:42 UTC, ryan-son commented on Diary/Controller/NewDiaryViewController.swift
> +final class NewDiaryViewController: UIViewController {
동일한 디자인을 가진 화면이라도 작동해야할 로직이 다르거나 향후 유연성을 위해 별도의 ViewController로 구성할 수 있지만, 개인적으로는 유연한 구조는 필요할 때 만드는 것이 좋다고 생각합니다. 여러분은 어떤 이유로 읽기/쓰기 ViewController를 별도로 구성하셨나요?

2022-12-22 09:02 UTC, ryan-son commented on Diary/View/DiaryListCell.swift
> +    }()
마지막 줄이나 return 이전 라인은 띄우는 컨벤션인 것 같았는데, 정확한 정책은 무엇인가요?

2022-12-23 06:35 UTC, Gundy93 commented on .gitignore
> +Pods/
아직 버전에 대한 공유가 필요하지 않다고 생각해서 Podfile만 git으로 관리하도록 하겠습니다 😃

2022-12-23 06:54 UTC, Gundy93 commented on .swiftlint.yml
> +  - trailing_whitespace
`Including whitespace-only lines` 체크 및 `isabled_rules`에서 `trailing_whitespace`를 삭제하였습니다 😃

2022-12-23 06:55 UTC, Gundy93 commented on .swiftlint.yml
> +  - trailing_comma
저희도 라이언의 의견과 같습니다!

2022-12-23 06:55 UTC, Gundy93 commented on .swiftlint.yml
> +  - Diary/SceneDelegate.swift
해당 부분 린트 무시 대상에서 제외하고 린트를 맞추게끔 수정하였습니다 😃

2022-12-23 07:38 UTC, yuvinrho commented on Diary/App/Assets.xcassets/sample.dataset/Contents.json
> +}
<img src = "https://i.imgur.com/yQHhWj1.png" height=400>
라이언~ 어제 꿀팁 알려주셔서 감사합니다!
프리뷰 폴더에 샘플 json데이터를 넣고 Development Assets 에 넣어주었습니다~

2022-12-23 07:53 UTC, yuvinrho commented on Diary/View/DiaryListCell.swift
> +    }
아래와 같은 프로토콜을 생성하여 커스텀셀에 채택하는 방법으로 해결해보았습니다~

```swift
protocol ReusableCell {
    static var reuseIdentifier: String { get }
}

extension ReusableCell {
    static var reuseIdentifier: String {
        return String(describing: self)
    }
}

```

2022-12-23 08:02 UTC, Hashswim commented on Diary/App/Info.plist
> -					<string>Main</string>
기능 명세서 대로 programmatically 하게 작성했습니다.
장단점은 이야기 나누어 본대로 변경사항에 대한 확인과 시각적으로 확인하는 부분 등 여러가지에 대해 알아보았습니다..!

2022-12-23 08:07 UTC, Hashswim commented on Diary/Controller/DiaryListViewController.swift
> +    }()
계산비용이 클 때 메모리가 낭비될 수 있기 때문에 나중에 해당 프로퍼티가 필요할 경우에 사용하면 좋을것 같습니다.

2022-12-23 08:20 UTC, Gundy93 commented on Diary/Controller/DiaryListViewController.swift
> +    private var sampleDiaryList: [Diary] = []
해당 프로퍼티의 이름을 `diaryList`로 수정하였습니다

2022-12-23 08:21 UTC, yuvinrho commented on Diary/Controller/DiaryListViewController.swift
> +            }
ReusableCell 프로토콜을 생성하여 기본 구현하는 방식으로 해결해주었습니다~

2022-12-23 08:23 UTC, Gundy93 commented on Diary/Controller/DiaryListViewController.swift
> +    }
해당 부분을 분리해 `decodeSampleData`메서드를 생성하여 호출하도록 하였습니다

2022-12-23 08:26 UTC, Gundy93 commented on Diary/Controller/DiaryListViewController.swift
> +    }
`presentNewDiaryView`로 네이밍 변경하였습니다!

2022-12-26 05:05 UTC, Hashswim commented on Diary/Controller/DiaryListViewController.swift
> +    private var dataSource: DiaryDataSource!
암시적 옵셔널 해제를 사용하지 않고 lazy 키워드를 사용해 나중에 값을 할당하는 것으로 변경했습니다.

2022-12-26 05:09 UTC, Hashswim commented on Diary/Controller/DiaryListViewController.swift
> +    }
`configureNavigationBar()`로 명확하게 메서드 네이밍을 수정했습니다.

2022-12-26 05:19 UTC, yuvinrho commented on Diary/Controller/DiaryViewController.swift
> +    }
알려주셔서 감사합니다 라이언~ 구현하지 않은 이니셜라이저에 @available attribute를 추가해주었습니다~
*는 모든 플랫폼을 뜻하고, unavailable은 사용할 수 없다를 뜻하는 것으로 이해했습니다!

2022-12-26 05:23 UTC, yuvinrho commented on Diary/Controller/NewDiaryViewController.swift
> +        view.backgroundColor = .systemYellow
아래와 같은 메서드를 만들어서 호출해주었습니다~

```swift 
private func configureView() {
   view.backgroundColor = .systemYellow
   configureNavigationBar()
}
```

2022-12-26 05:40 UTC, yuvinrho commented on Diary/Controller/NewDiaryViewController.swift
> +        let cancelButton = UIBarButtonItem(title: "취소", style: .plain, target: self, action: #selector(cancel))
기존 objc 메서드를 이번기회에 addAction으로 리팩토링 하였습니다~

2022-12-26 06:01 UTC, Gundy93 commented on Diary/Model/Diary.swift
> +}
현재 스텝에서는 코어 데이터에 저장하지 않으므로 `DiaryResponseDTO`와 `Diary`로 모델을 분리하였습니다. 추후 스텝 2에서 `DiaryEntity` 모델도 생성할 것으로 생각합니다.

2022-12-26 06:18 UTC, Hashswim commented on DiaryTests/JSONDecodingTest.swift
> +    }
알려주신 형식에 맞게 아래와 같이 수정했습니다.
```swift
func test_JSON_sample_data를_DiaryResponseDTO_타입으로_decoding하면_Nil이_아닌값_반환한다() throws {
        guard let path = Bundle.main.path(forResource: "sample", ofType: "json") else {
            return XCTFail("sample data 경로 오류")
        }

        let data = try Data(contentsOf: URL(fileURLWithPath: path))
        let decodedData = try JSONDecoder().decode([DiaryResponseDTO].self, from: data)

        XCTAssertNotNil(decodedData)
    }
```

2022-12-26 06:22 UTC, yuvinrho commented on Diary/Controller/NewDiaryViewController.swift
> +final class NewDiaryViewController: UIViewController {
처음 구현을 했을때 커스텀뷰를 만들어서 재사용하자 라고 생각을 했습니다.
라이언의 의견을 듣고보니 많은 뷰의 변화가 필요하지 않을경우 뷰컨이 두개가 필요하지 않을 수도 있다고 생각이 바뀌었습니다.
이 부분은 스텝2를 진행하면서 해보도록 하겠습니다~

2022-12-26 06:40 UTC, Hashswim commented on Diary/View/DiaryListCell.swift
> +    }()
return 이전 라인은 개행 하는게 맞습니다. 이 부분은 저희가 빠뜨린것 같아 수정했습니다..
추가로 부모 클래스의 메서드를 가져오는 부분 또한 개행을 하는 등의 컨벤션이 있습니다..!

2022-12-26 17:27 UTC, ryan-son approved these changes
고생 많으셨습니다~ 새로운 코멘트 읽어보시고, 필요한 게 있으시면 취하시면 되겠습니다.

궁금한 것이 있으시면 언제든지 물어보세요. 그럼 다음 스텝에서 뵙겠습니다~! 😄

2022-12-26 17:27 UTC, ryan-son commented on Podfile
> +  pod 'SwiftLint'
버전을 명시하지 않으셨네요. 이 경우에 `pod install`을 수행하면 어떤 버전의 의존성을 가져올까요? 팀원 간 `Podfile.lock`을 공유하지 않은 상태이므로 팀에서 어떤 버전의 의존성을 사용하고 있는지 알 수 있는 방법이 없어졌습니다. 팀에서 사용 중인 의존성 버전을 대략적으로나마 일치시킬 수 있도록 버전을 명시하시거나 `Podfile.lock`을 git으로 공유하는 방법을 사용해볼 수 있어요. 아래 문서를 읽어보세요.

- [Specifying pod versions - CocoaPods.org](https://guides.cocoapods.org/using/the-podfile.html#specifying-pod-versions)

2022-12-26 17:27 UTC, ryan-son commented on .gitignore
> +Pods/
Podfile에 남겨둔 새로운 코멘트를 참고해보세요.

2022-12-26 17:27 UTC, ryan-son commented on .swiftlint.yml
> +  - trailing_whitespace
기존에 존재하던 trailing whitespace는 어떻게 제거해주셨나요?

2022-12-26 17:27 UTC, ryan-son commented on Diary/App/Assets.xcassets/sample.dataset/Contents.json
> +}
앱 크기를 늘리는 것 뿐만이 아니라 외부에 공개될 필요 없는 내용을 내보내지 않기 위한 과정이기도 하니 신경써봅시다~!

2022-12-26 17:27 UTC, ryan-son commented on Diary/Controller/DiaryListViewController.swift
> +    private var dataSource: DiaryDataSource!
[P3]
lazy 키워드를 자주 사용하면 코드의 작동 순서를 읽기 어려워지는 이슈가 있습니다. 별다른 목적이 없다면 지연 초기화를 하기 보다는 옵셔널 처리를 하고 view controller life cycle의 메서드에서 인스턴스를 주입해주는 형식으로 작성한다면 이런 이슈에서 자유로울 수 있을거에요.

2022-12-26 17:27 UTC, ryan-son commented on Diary/Controller/DiaryListViewController.swift
> +            }
아래처럼도 가능할까요?
```swift
let cell = tableView.dequeueReusableCell(cellType: DiaryListCell.self, for: indexPath)
...
```

2022-12-26 17:27 UTC, ryan-son commented on Diary/Controller/DiaryListViewController.swift
> +    }
[P4]
새로 만든 메서드는 로드와 디코드를 동시에 수행하고 있네요. 이것도 이름이 애매한 것 같기도 하네요.

2022-12-26 17:27 UTC, ryan-son commented on Diary/Controller/DiaryViewController.swift
> +    }
deprecated 처리를 하거나, 이름이 바뀐 메서드 이름을 알려주는 데도 사용할 수 있으니 필요할 때 해당 문서를 더 찾아보시면 됩니다~

2022-12-26 17:27 UTC, ryan-son commented on Diary/Controller/NewDiaryViewController.swift
> +        let cancelButton = UIBarButtonItem(title: "취소", style: .plain, target: self, action: #selector(cancel))
어떤 차이가 있었나요? 여러분은 어떤 게 더 좋으셨나요?

2022-12-26 17:27 UTC, ryan-son commented on DiaryTests/JSONDecodingTest.swift
> +    }
[P3]
`nil이 아닌 값을 반환한다`가 무엇을 의미하는지를 작성하면 메서드가 어떤 것을 테스트하고 싶어하는지 더 명확해질 것 같네요.

2022-12-26 17:29 UTC, merged

2022-12-27 00:22 UTC, Gundy93 commented on .swiftlint.yml
> +  - trailing_whitespace
`command + b`를 통해 빌드를 계속 돌리면서 린트 에러가 나는 부분으로 점프해가면서 지웠습니다!

2022-12-27 01:12 UTC, yuvinrho commented on Diary/Controller/DiaryListViewController.swift
> +    private var dataSource: DiaryDataSource!
lazy 키워드를 삭제하고 옵셔널로 처리해주었습니다~ 코드의 작동 순서를 읽기 어려워진다는 이슈 알려주셔서 감사합니다~

2022-12-27 01:35 UTC, Gundy93 commented on Diary/Controller/DiaryListViewController.swift
> +            }
`UITableView`를 extension하여 해당 메서드를 구현하였습니다! 옵셔널이 아니게 되어서 완전 좋네요!

2022-12-27 01:47 UTC, Hashswim commented on Diary/Controller/DiaryListViewController.swift
> +    }
데이터를 로드 하는 부분과 디코딩 하는 부분을 다른 메서드로 분리 했습니다.

2022-12-27 01:51 UTC, yuvinrho commented on Diary/Controller/NewDiaryViewController.swift
> +        let cancelButton = UIBarButtonItem(title: "취소", style: .plain, target: self, action: #selector(cancel))
@objc와 #selector를 안써도 된다는 점과 이니셜라이저에 primaryAction 파리미터에 바로 액션을 넣어줘도 된다는 점에서 살짝 간소해진 느낌이 들어서 좋았습니다 하지만 ios14 버전부터 사용가능한 점에서 버전이 높다라는 생각이 들긴했습니다~

2022-12-27 02:14 UTC, yuvinrho commented on DiaryTests/JSONDecodingTest.swift
> +    }
라이언 아래와 같이 테스트코드를 수정해보았는데 저희가 라이언의 말을 잘 이해했을까요?ㅠㅠ

```swift
func test_JSON_sample_data를_decoding하면_DiaryResponseDTO배열타입을_반환해야한다() throws {
        guard let path = Bundle.main.path(forResource: "sample", ofType: "json") else {
            return XCTFail("sample data 경로 오류")
        }

        let data = try Data(contentsOf: URL(fileURLWithPath: path))
        let decodedData = try JSONDecoder().decode([DiaryResponseDTO].self, from: data)

        XCTAssertEqual("Array<DiaryResponseDTO>", String(describing: type(of: decodedData)))
    }
```

2022-12-27 02:25 UTC, ryan-son commented on .swiftlint.yml
> +  - trailing_whitespace
SwiftLint에는 auto correct 기능을 수행해주는 스크립트 명령 옵션이 있습니다. 빌드를 했을 때 린트에 나타나는 게 trailing whitespace밖에 없다면 `swiftlint --fix` 명령을 사용해볼 수 있어요.

- [Auto-correct - realm/SwiftLint](https://github.com/realm/SwiftLint#auto-correct)

2022-12-27 02:27 UTC, ryan-son commented on Diary/Controller/DiaryListViewController.swift
> +            }
제네릭을 잘 활용하면 성능과 편의성 측면에서 이점이 있으니 항상 제네릭으로 문제를 해결할 수 있는지 생각해보면 좋습니다.

2022-12-27 02:28 UTC, Gundy93 commented on .swiftlint.yml
> +  - trailing_whitespace
거의 50개 이상의 trailing whitespace 찾아다니며 수정했는데...그렇군요 감사합니다 😂

2022-12-27 02:50 UTC, ryan-son commented on DiaryTests/JSONDecodingTest.swift
> +    }
결과가 `notNil`을 판단하는 것이어도 괜찮은데, 그 의미가 `[DiaryResponseDTO] 타입을 반환한다`보다 `해당 타입으로 디코딩 된다`가 여러분이 의도한 목적을 더 잘 설명할 수 있지 않을까 싶었어요.