일기장  [STEP1] 써니쿠키, LJ
yagom-academy/ios-diary pull request #68
Opened 2022-12-21 14:07 UTC by sunny-maeng

@uuu1101
안녕하세요 태태! 🙇🏻‍♀️🙇🏻‍♀️
Step1 PR드립니다.
잘부탁드립니다..!

## 📝 STEP 진행 중 경험하고 배운 것
- 스토리보드없이 코드로만 View구현하기
	 - [X] 스토리보드를 삭제하고 SceneDelegate를 수정해 navigationController가 embeded된 View를 구현했습니다.
- swiftLint 라이브러리 사용하기
	 - [X] pod 을 이용해 라이브러리를 적용했습니다.
	 - [X] `swiftLint` 라이브러리로 코드컨벤션을 통일했습니다. 
- modernCollectionView를 이용한 List구현
	 - [X] `UICollectionViewCompositionalLayout.list`를 이용해 ListView 구현했습니다.
     - [X] DiffableDataSource, snapShot을 이해하고 적용했습니다.
- readableContentGuide 사용하기
     - [X] app adaptivity 및 가로모드의 레이아웃에 readableContentGuide를 사용했습니다.

## ⚒️ 코드 구현내용 
### 1️⃣ DiaryListViewController
- 일기장 목록화면인 DiaryListView를 담당하는 뷰컨트롤러입니다.
- setupNavigationBar() : 내비게이션바를 정의하는 메서드입니다.
- collectionView(collectionView:didSelectItemAt:) : UICollectionViewDelegate프로토콜을 채택하여 목록 중 하나의 항목을 선택했을 때 다음화면으로 전환하는 메서드입니다.
- ModernCollectionView로 일기장목록을 구현하였습니다.
    - convertDiaryData() : JSON파일을 Data타입으로 디코드 후 Diary요소를 갖는 배열타입으로 저장합니다.
    - configureDiaryListDataSource() : 정의해놓은 커스텀셀인 DiaryCell을 등록합니다.
    - snapShot() : 변경된 데이터를 스냅샷형태로 저장한 후 apply()메서드로 뷰에 다시 그려달라 요청합니다.
    - Section 열거형 : diaryListView의 Section을 열거하고, 하나의 main case를 갖습니다.
    
### 2️⃣ DiaryDetailViewController
- 일기장 목록 중 하나의 일기상세화면인 DiaryDetailView를 담당하는 뷰컨트롤러입니다.
- 이전화면(일기목록화면)에서 현재화면(일기상세화면)으로 데이터를 전달받기 위해 diary 변수를 선언하였습니다.
- configureDiary() : 일기상세화면에 제목,내용,일자 각각 항목별 데이터를 바인딩하는 메서드입니다.
- setupNotification() : 키보드가 보이거나 숨겨질 때의 노티피케이션에 Observer를 추가해서 controlKeyboard() 메서드를 호출합니다.
- controlKeyboard(_:): 키보드 보이기와 숨기기시 키보드 높이만큼 ScrollView의 Bottom에 inset을 추가/삭제 합니다.

### 3️⃣ Diary
- JSON파일(sample.json)을 decode하기위한 DTO(데이터전송객체) 입니다.
- CodingKey 프로토콜을 채택하였고, DataFormat 양식을 따르기 위한 createDate 연산프로퍼티를 갖고 있습니다.

### 4️⃣ DiaryCell
- 일기장목록화면 `DiaryListView`에서 항목 하나를 정의하는 클래스입니다.
- configureDiaryCellLayout() : `stack view`에 넣을 뷰를 `addArrangedSubview()`메서드를 이용하여 `embed`해주는 메서드입니다.

### 5️⃣ DecodeManager
- JSON형식의 데이터를 decode하는 클래스입니다. do-catch문을 이용해 에러처리를 해주었습니다.

### 6️⃣ CustomUI
- CustomLabel
    - 일기장목록화면 `DiaryListView`에서 Label들이 공통으로 갖는 서식 코드가 중복된다는 문제가 있었습니다. 코드의 중복을 줄이기 위해 초기화 할 때 공통 서식을 부여해주는 클래스입니다.
- CustomTextView
    - 일기상세화면 `DiaryDetailView`에서 공통 서식을 부여하여 초기화하는 클래스입니다.

---

## 💭 고민한 부분
### DiffableDataSource사용할 때, Value값이 똑같은 데이터로 인한 오류 해결
- 프로젝트에 포함된 견본 JSON 데이터를 사용해 List Cell을 구성할 때, 값이 같은 데이터가있어 오류가 있었습니다.
	- 원인: Diffable datasource를 사용하려면 `ItemIdentifier`가 각각 고유한 Hash값을 갖고 있어야하는데 아래 캡쳐 화면 처럼 value가 완전히 같을 때는 두 개가 같은 Hash값을 갖기 때문입니다.
	![](https://i.imgur.com/PpWdKev.jpg)
	
	- 👉 해결: DTO에 `UUID`를 생성해 각 value들이 각각 고유한 Hash값을 갖도록 했습니다.
		```swift
		struct Diary: Decodable, Hashable {
			let title: String
			let body: String
			let createdAt: Double
			let id = UUID() // 👈
			// ...
		}
		```
		
### 키보드가 보여지고 사라질 때, 컨텐츠를 가리지않도록 하는 방법
- 키보드가 보여질 때는 키보드 뒤에 가려진 컨텐츠를 스크롤 해서 볼 수 있도록 ScrollView로 구현했습니다. TextView에도 Scroll기능이 있지만, title과 body가 같이 스크롤 될 수 있도록 따로 ScrollView에 title과 body의 TextView를 담았습니다.
- 키보드가 보여지고/사라질 때 ScrollView의 Bottom방향으로 키보드 높이만큼 Inset을 추가/삭제해서 컨텐츠가 가려지지 않도록 구현했습니다.
- 입력 완료 후 키보드를 내리는 방법으로 UIScrollView의 keyboardDismissMode 속성을 사용해 사용자가 스크롤하여 키보드를 다시 내릴 수 있도록 구현했습니다.

---
## 🧐 조언을 얻고 싶은 부분
### 👉 DiaryCell 이 MVC에서 View인지 / Model인지 궁금합니다.
DiaryCell은 UICollectionViewListCell을 상속 받고, 이어서 상속받는 클래스를 보면 UIView가 최상위 클래스입니다. 
UICollectionViewListCell ⬅️ UICollectionViewCell ⬅️ UICollectionReusableView ⬅️ UIView
그렇기에 MVC 중 View에 해당된다고 이해했습니다.
Cell타입은 View가 담당하는 UI요소 중 하나이고, Cell의 내용을 채울 데이터는 Controller에서 정해준다고 이해한 것이 맞을까요?

---

2022-12-22 11:01 UTC, uuu1101 requested changes
안녕하세요 @sunny-maeng , @lj-7-77  🙌
STEP1 진행하시느라 고생많으셨습니다 :)
몇가지 코멘트 남겨두었으니 확인부탁드려요 ! 

> ### 🧐 조언을 얻고 싶은 부분
> 👉 DiaryCell 이 MVC에서 View인지 / Model인지 궁금합니다.
DiaryCell은 UICollectionViewListCell을 상속 받고, 이어서 상속받는 클래스를 보면 UIView가 최상위 클래스입니다.
UICollectionViewListCell ⬅️ UICollectionViewCell ⬅️ UICollectionReusableView ⬅️ UIView
그렇기에 MVC 중 View에 해당된다고 이해했습니다.
Cell타입은 View가 담당하는 UI요소 중 하나이고, Cell의 내용을 채울 데이터는 Controller에서 정해준다고 이해한 것이 맞을까요?

>> 네 맞습니다.다만 조금 더 명확하게 하기 위해서 아래 내용들을 한번 고민해보시면 좋을것 같아요
 MVC는 어떻게 나누어 지나요? Model / View / Controller 의 역할이 무엇일까요 ?!
화면에서 User Input을 View가 받았을때 어떠한 일들이 일어나면서 화면이 보여질까요?
View - ? - Controller -? - Model - ? - View 이런 구조로 한 사이클이 진행이 될텐데 (?)에는 어떠한 작업들이 필요할까요?

## **UI 관련하여서** 
1. 리스트에서 디테일로 진입 후 다시 리스트로 돌아오더라도 셀이 선택되어져 있는것 처럼 보이는 것 
2. 디테일 화면에서 키보드를 올렸다 내렸다 반복하면 ScrollView가 끝까지 Scroll 되지 않는 이슈

## **Localization**
1. Localization 관련하여 지역에 따라 생성일자 Format을 변경하는 법 

위 내용들도 한번 고민해보시면 좋을 것 같습니다 ! 
고생하셨어요👍👍👍

2022-12-22 11:01 UTC, uuu1101 commented on Diary/Model/DecodeManager.swift
> +    }
Error Case에 대해서 분류를 해주신 부분 👍
하지만, 한가지 고민해봐야할 사항이 있을것 같아요.
해당 앱 사용자가 `DecodingError`를 마주했을때 어떻게 될까요? 
print문을 앱 사용자가 확인할 수 있나요 ?
print문은 무엇을 위해 존재하는걸까요 ?
프로젝트를 진행하면서 Error에 대한부분들을 콘솔창으로 확인하기 위해서 작성하셨을텐데, 제가 드린 질문에 대해서도 한번 생각해보시면 좋을 것 같습니다 !

2022-12-22 11:01 UTC, uuu1101 commented on Diary/View/CustomUI.swift
> +    }
해당 코드는 왜 필수로 구현해주어야 할까요?

2022-12-22 11:01 UTC, uuu1101 commented on Diary/View/DiaryDetailView.swift
> +    private func diaryDetailLayout() {
메서드명이라고 잘 느껴지지 않는 것 같아요 👀
네이밍을 조금 더 고민해볼까요..?!

2022-12-22 11:01 UTC, uuu1101 commented on Diary/ViewController/DiaryDetailViewController.swift
> +                self.diaryDetailView.diaryTextScrollView.contentInset.bottom -= keyboardHeight
contentOffset과 contentInset은 어떤역할을 할까요? 👀

2022-12-24 06:15 UTC, sunny-maeng commented
> MVC는 어떻게 나누어 지나요?
> Model / View / Controller 의 역할이 무엇일까요 ?! 
- Model / View / Controller 의 역할
    - Model:  앱에서 사용하는 데이터와 데이터 처리 로직(Logic)을 갖고있습니다. View(화면)와 무관합니다.
    - View: 보여지는 화면 구성(뷰 요소, 레이아웃, 사용자와의 interaction)
    - Controller: View의 입력에 대해 Model의 Logic을 사용해 처리
- MVC가 나뉘는 기준
	- 객체의 역할을 고려하여 모델과 뷰를 나누는것을 중점으로(= 관심사의 분리, 분업) 나뉘어집니다. (모델과 뷰는 서로 알지못해야하고, 중간의 컨트롤러가 둘 사이의 관계를 중재(?)합니다) 뷰는 컨트롤러에게 화면에서 일어난 이벤트를 컨트롤러에게 어떻게 처리할지 확인받은 후 처리합니다.
 
> 화면에서 User Input을 View가 받았을때 어떠한 일들이 일어나면서 화면이 보여질까요? View - ? - Controller -? - Model - ? - View 이런 구조로 한 사이클이 진행이 될텐데 (?)에는 어떠한 작업들이 필요할까요?
- 공식문서에 첨부되어있는 M-V-C 관계는 아래와 같습니다.
	<Img width = 300, src = "https://i.imgur.com/jAwJrZl.png">
	UserInput을 받으면 View ➡️ [UserAction 전달] ➡️ Controller ➡️  [Modedl Update] ➡️ Model ➡️ [업데이트된 모델 노티 ➡️ Controller ➡️ 업데이트된 모델을 갖고 View업데이트] ➡️ View

2022-12-24 07:35 UTC, lj-7-77 commented on Diary/View/CustomUI.swift
> +    }
- UI요소들은 NSCoding프로토콜을 채택하고있는데 이 프로토콜의 요구사항중 하나로 `init?(coder: NSCoder)`이 있습니다. 그래서 이 프로토콜을 채택한 UI요소들은 `required init?(coder: NSCoder)`를 필수적으로 구현해야합니다. 
- 예외상황을 설명하면, 상속 후 `지정 이니셜라이저 새로 구현`/`기존 이니셜라이저를 override`하는 상황이 아니라면 required이니셜라이저를 구현하지않아도 자동으로 상속받게 되서 구현하지 않아도 됩니다.
-  저희 프로젝트에서는 UIView를 상속받은 CustomLabel, CustomTextView, Custom한 UIView들에서 새로운 지정이니셜라이저를 구현했거나 상속받은 이니셜라이저를 override 하고있습니다. 때문에 required이니셜라이저를 자동상속을 받지못하게 되어 필수로 `required init?(coder: NSCoder)`구현해주어야 합니다.
- `conveniece 이니셜라이저`로 만들어 `required init?(coder: NSCoder)`을 자동상속 받거나, 구현부에 `fatalError`대신 `super.init(coder: coder)`로 구현할 수도 있습니다. 다만 저희는 스토리보드를 삭제하고, 코드로만 뷰를 구현해야하는 요구사항이 있었기 때문에 xib/스토리보드로 UI를 구성할 때 사용되는 이 이니셜라이저를 사용할 일이 없을 것 같아서 새로운 지정이니셜라이저/override로 구현했고, required 이니셜라이저에서는 `fatalError`를 사용했습니다.

2022-12-24 07:44 UTC, sunny-maeng commented on Diary/Model/DecodeManager.swift
> +    }
- print문은 앱사용자가 확인할 수 없고, 단지 저희가 개발하면서 디버깅을 하기 위한 수단으로 사용했습니다. 사용자도 앱에 오류가 있다는 걸 알 수 있도록 Alert처리를 할 수 있을 것 같습니다. 다만, 생각해보니 다음스텝으로 넘어가면 CoreData를 사용하고 디코딩 할 일이 없을 것 같아 리팩토링을 진행하진않았습니다..!

2022-12-24 07:57 UTC, sunny-maeng commented on Diary/View/DiaryDetailView.swift
> +    private func diaryDetailLayout() {
아..기본적인 실수를...😂
DiaryListView와, DiaryDetailView의 네이밍을 통일하기 위해서 `configureDetailLayout`로 수정했습니다. [3485a3a](https://github.com/yagom-academy/ios-diary/pull/68/commits/3485a3a74abd4e45c29740a309e3e5df5d8d4a78)

2022-12-24 09:17 UTC, sunny-maeng commented on Diary/ViewController/DiaryDetailViewController.swift
> +                self.diaryDetailView.diaryTextScrollView.contentInset.bottom -= keyboardHeight
<img width = 300, src = "https://i.imgur.com/Oqc2oAM.png">
contentInset과 ContentOffSet을 그려 보았습니다.

저희 코드에서 contentInset은 키보드 높이만큼 Bottom 방향으로 추가되어 뷰가 키보드 뒤에 가려지는 것을 방지해주는 역할을합니다.
contentOffset은 키보드가 올라왔을 때 화면에 보이는 컨텐츠의 위치를 다시 잡아줘야할 것같아 구현해 놓았는데, 추가 작동테스트에서 offset에 문제가 있어서 더 공부해보았습니다.
알고보니 ScrollView에서 Inset을 변경하면 offset을 자동으로 조정해준다고 하네요.. 실제로 Offset을 코드로 잡아주지 않아도 자동으로 offset이 변하는 것도 확인했습니다. 
 ( 여러 검색을 하면서 [`contentInsetAdjustmentBehavior`](https://developer.apple.com/documentation/uikit/uiscrollview/2902261-contentinsetadjustmentbehavior) 이 offset 자동조정과 관련이 있는것같아 보이는데 코드로 속성값을 `.never`로 바꿔도 offset이 자동변화가 일어납니다.. 그렇다면 누가..😱 힌트 주시면 더 공부해보겠습니다..)

2022-12-25 11:07 UTC, uuu1101 commented
고생하셨습니다 ! 
코멘트 남긴 부분들에 대해서 많이 찾아보셨네요 👍

2022-12-25 11:07 UTC, merged