일기장 [ Step 1 ] woong, jeremy
yagom-academy/ios-diary pull request #70
Opened 2022-12-22 13:19 UTC by yjjem

🤩 안녕하세요 @junbangg 
woong, jeremy 입니다.
Step1 완료하여 PR드립니다.

### 🤔 고민한 부분

#### 📎 키보드가 텍스트를 가리지 않도록 설정
- 키보드 `Hide`, `Show` 상태에 따라 다른 액션을 취하도록 하기위해 `NotificationCenter`를 활용하였습니다.
- `Notification` 구조체 내부의 인스턴스인 `userInfo`의 `KeyboardFrame`을 전달받아 키보드의 높이 값을 얻어 낼 수 있었고,
- `textView`의 `bottom` 제약의 `Constant`에 전달받은 키보드의 높이값를 설정하는 것으로 문제를 해결 할 수 있었습니다. 

#### 📎 textView에서 title과 body를 나누는 로직 구현

`서론` 
- 아이폰의 메모장 앱을 참고하여 textView를 하나만 활용하면서 Diary title과 body를 구분할 수 있는 로직을 구현했습니다.

`본론` 
1. `title`과 `body`를 무엇을 기준으로 나눌지 고민이었는데 `textView`에 `title`과 `body`를 합치면서 사용하는
     `\n\n` 을 기준으로 나누는 것으로 문제를 해결할 수 있었습니다.
     
    ```swift
    // DetailViewController.swift

    private func configureView() {
        ...
        self.detailTextView.text = "\(data.title)\n\n\(data.body)"
    }
    ```
2. 하지만 유저가 `title`과 `body`를 나누지 않고 하나의 문단으로 작성하는 경우도 고려해야 했습니다.
- 이 과정에서 고려해본 형태는 아래와 같습니다.

    | <center> A </center>| <center> B </center> |
    | -------- | -------- |
    | <center><img src="https://i.imgur.com/3dWUO7V.png" height="500px"/> </center>   |<center> <img src="https://i.imgur.com/SoiWpUU.png" height="500px"/> </center>   |
    |문단이 있고 components로 </br>확실하게 나눌 수 있는 형태|문단이 하나이고 `title`과 `body`를 </br> 명확히 나눌 수 없는 형태|

- 문단이 나뉘어있는 경우 `componenets(separatedBy:)` 메서드를 활용하여 배열의 첫 요소를 `title`로 지정하도록 했고 문단이 하나뿐이라면 문자열의 앞 20자가 `title` 그리고 나머지가 `body`가 되도록 했습니다.

`결론`
- `textView`를 여러개를 사용하면 편했겠지만 재미있는 시도였던 것 같습니다.
- 아직은 완성되지 않은 기능인 것 같습니다. 고려해보지 않은 케이스들도 몇가지 떠오릅니다.
- `String index`에 대해 알아볼 수 있는 좋은 경험이었습니다.

### ⁉️ 궁금한 점

앱 타겟 버전에 따라 사용할 수 있는 기술들이 각기 다를 것 같습니다. 저희 프로젝트의 경우 14버전인데 `tableview`를 사용하느냐 `collectioView`를 활용하여 `list`형태를 구현하느냐가 고민입니다. 일기장의 경우 단순한 앱이라 `collectionView`를 사용하는 것은 오버엔지니어링이 아닐까 그리고 추후에 `tableView`가 사라질거라는 이야기를 들은 것 같아 오히려 `collectionView`를 사용해야하지않을까라는 생각이 같이 드네요

`궁금한 점 요약`
- 가능하면 최신 기술을 활용해야하는 것인가
- 앱 타겟 14에서 `collectionView`는 오버엔지니어링인가
- `tableView`가 사라질거라는 이야기를 들은 것 같은데 이제는 떠나보내야하는가

> 위의 3가지에 대해서 알라딘은 어떻게 생각하시는지 궁금합니다!

2022-12-25 14:55 UTC, junbangg requested changes
수고하셨습니다!! 코드도 잘 정돈 되어있고 가독성도 좋아요! 
댓글 확인해주세요!

질문주신 내용에 대한 답을 드리자면!
```
가능하면 최신 기술을 활용해야하는 것인가
```
> 가능하면 최신 기술..! 음...개인적으로 앱의 최소지원 버전에 의한 제약이 없으면 최신 기술을 사용하는건 좋은것 같아요!!  굳이 필요 없는데 최신 기술을 쓰는건 뭐..의미가 크게는 없겠지만! 뭐든 설명할 수 있는 근거만 있다면 👍👍 그냥 "최신" 이라는 이유 때문이라면 좀 그렇겠죠!
```
앱 타겟 14에서 collectionView는 오버엔지니어링인가
```
오버엔지니어링...까진지는 잘 모르겠지만ㅎㅎ
굳이 collectionView 의 기능이 필요 없이 충분히 tableView로 가능해서 생기는 고민이겠지요..?
그렇다면 확장성을 생각하면 좋을것 같아요! collectionView 가 꼭 필요해서 tableView 다 걷어내고 collectionView로 다시 구현해야되는 일이 생길 일은 없는지/??? 고런걸 한번 생각해보면 좋을것 같아요.
```
tableView가 사라질거라는 이야기를 들은 것 같은데 이제는 떠나보내야하는가
```
음 떠나보내기보다는~ 둘다 알고 있는건 좋은것 같아요!! 위 질문이랑 이어지는 내용이긴한데.. collectionView를 사용하면 좋은 이유가 하나라도 있다면 고걸로 가면 될것 같습니다:)

2022-12-25 14:55 UTC, junbangg commented on Diary/Controller/DetailViewController.swift
> +    @IBOutlet weak private var detailTextView: UITextView!
`IBOutlet` 을 weak 으로 하신 이유가 있나요???

2022-12-25 14:55 UTC, junbangg commented on Diary/Controller/DetailViewController.swift
> +        guard let data = diaryData else { return }
언래핑할때 `diaryData` 를 `data` 로 바꾸신 이유가 있나요??

2022-12-25 14:55 UTC, junbangg commented on Diary/Controller/DetailViewController.swift
> +        delegate?.sendData(title: data.title,
`delegate`는 언래핑 안한 이유가 있나요?!

2022-12-25 14:55 UTC, junbangg commented on Diary/Controller/DiaryViewController.swift
> +
불필요한 줄바꿈이 있네요!

2022-12-25 14:55 UTC, junbangg commented on Diary/Controller/DiaryViewController.swift
> +
의도된 줄바꿈인가요?!

2022-12-25 14:55 UTC, junbangg commented on Diary/Controller/DiaryViewController.swift
> +                           body: sampleData[indexPath.row].body)
`sampleData[indexPath.row]` 를 한방에 넣지 않고 프로퍼티를 따로따로 뽑아서 넣기로 하신 이유가 있나요??(틀렸다는건 아닙니당)

2022-12-25 14:55 UTC, junbangg commented on Diary/Controller/DiaryViewController.swift
> +
의도된 줄바꿈인가요?!

2022-12-25 14:55 UTC, junbangg commented on Diary/View/DiaryTableViewCell.swift
> +    @IBOutlet weak var bodyLabel: UILabel!
`private` 이 가능할것 같습니다~!

2022-12-25 14:55 UTC, junbangg commented on Diary/View/DiaryTableViewCell.swift
> +        self.accessoryType = .disclosureIndicator
요 친구만 왜 `self` 를 붙여주신건가요??

2022-12-25 14:55 UTC, junbangg commented on Diary/Controller/AddViewController.swift
> +}
요 친구는 미리 추가해두신건가요??

2022-12-25 14:55 UTC, junbangg commented on Diary/Controller/DetailViewController.swift
> +
의도된 줄바꿈인가요?!

2022-12-25 14:55 UTC, junbangg commented on Diary/Utilities/Ext + String.swift
> +        if components.count > 1 {
`guard` vs `if` 를 사용하는 기준(?)이 어떻게 되는지 궁금합니다:)

2022-12-25 14:55 UTC, junbangg commented on Diary/View/DiaryTableViewCell.swift
> +
의도된 줄바꿈인가요?!

2022-12-25 14:55 UTC, junbangg commented on Diary/Controller/DiaryViewController.swift
> +    private func tableViewAttribute() {
메서드의 내용을 봐서는 `tableView` 를 세팅하는 역할인것 같은데 메서드명만 봐서는 알기 힘든것 같아요!
`setTableViewAttributes` 또는 `setTableView` 는 어떠신가요?

2022-12-25 14:55 UTC, junbangg commented on Diary/Controller/DetailViewController.swift
> +    weak var delegate: DetailViewControllerDelegate?
요 친구들은 `private` 이 불가능한가요!

2022-12-25 14:55 UTC, junbangg commented on Diary/Controller/DiaryViewController.swift
> +
의도된 줄바꿈일까요??? 위 익스텐션에서는 줄바꿈이 없어서요!

2022-12-25 14:55 UTC, junbangg commented on Diary/Controller/DiaryViewController.swift
> +        guard let detailView: DetailViewController = self.storyboard?.instantiateViewController(withIdentifier: "DetailView") as? DetailViewController else { return }
`detailViewController` 로 안하신 이유가 있을까욥!?

2022-12-25 14:55 UTC, junbangg commented on Diary/Controller/DiaryViewController.swift
> +
의도된 줄바꿈인가요????

2022-12-25 14:55 UTC, junbangg commented on Diary/Utilities/Ext + String.swift
> +    func parseData(titleWordsLimit: Int) -> (title: String, body: String) {
요거 익스텐션으로 하신 이유가 궁금합니다!

2022-12-26 07:03 UTC, yjjem commented on Diary/Controller/DetailViewController.swift
> +    @IBOutlet weak private var detailTextView: UITextView!
### **IBOutlet을 weak으로 설정한 이유**
- Default가 weak이라서 기본값을 따랐습니다.

### **만약, 이것을 strong으로 바꿔도 작동하는가?**
- 정상적으로 작동합니다. 하지만, 아래와 같은 차이가 있습니다.
```swift
// weak를 사용했을 때

final class DetailViewController: UIViewController {
    
    @IBOutlet weak private var detailTextViewBottomConstraint: NSLayoutConstraint!
    @IBOutlet weak private var detailTextView: UITextView!
    var diaryData: SampleData?
    var indexPath: IndexPath?
    weak var delegate: DetailViewControllerDelegate?
```
viewDidLoad를 시작하는 시점에서
weak를 활용했을 때, detailTextView의 RC는 3이 됩니다.


```swift
// strong을 사용했을 때

final class DetailViewController: UIViewController {
    
    @IBOutlet private var detailTextViewBottomConstraint: NSLayoutConstraint!
    @IBOutlet private var detailTextView: UITextView!
    var diaryData: SampleData?
    var indexPath: IndexPath?
    weak var delegate: DetailViewControllerDelegate?
```
viewDidLoad를 시작하는 시점에서
strong을 활용했을 때, detailTextView의 RC는 4가 됩니다.

> weak를 활용했을 때에는 RC가 증가하지않게되므로 나타나는 결과입니다.

### 이해가지 않는 부분: 
##### strong으로 지정해줬을 때, 왜 viewdidLoad가 시작되는 시점에서 detailTextView의 RC는 4인가?

>RC1: view가 detailTextView를 강한참조(소유)하므로 
RC2: Interface Builder에서 가장 상위 View가 detailTextView를 소유하므로
RC3: vc에서 detailTextView가 strong
RC4: ???

##### 기본적으로 프로젝트를 생성하면 view에 대한 RC 가 3인 것을 확인했습니다. StoryBoard를 삭제하면 RC - 1 이 되는 이유..

##### strong을 활용해야하는 경우

정말로 필요할 때, IBOutlet에 Strong을 써야 하는 경우가 있다고 합니다.
하지만, 아래 내용이 이해가 가지않네요...
아래는 블로그 글을 발췌하여 요약하였습니다.

> - 복잡한 뷰 Hierarchy를 가진 경우에는 Weak 대신 Strong을 써야만 하는 경우도 존재함
> - 깊은 뷰 Hierarchy 구조에서 모든 Connection이 Weak라고 한다면 중간쯤 있는 View가 어느 이유에서인지 dealloc이 된다면? 그 하위뷰들도 함께 dealloc이 됨
> - 만약 복잡한 뷰 Hierechy 구조상에서 subview의 subview를 사용해야 하는 경우. 의도치 않은 nil을 경험할 수도 있습니다. 일반적이지는 않지만 충분히 겪을 수 있음

2022-12-26 07:05 UTC, iOS-Woong commented on Diary/Controller/DetailViewController.swift
> +        guard let data = diaryData else { return }
의도는 없습니다.
컨벤션을 따로 지정해주지 않아서 `data`로 썼습니다.
guard문으로 옵셔널을 풀어줄 때, 기존의 변수명과 동일하게 이름을 지어주는 것으로 컨벤션을 맞췄습니다.
수정하여 반영했습니다!

2022-12-26 07:29 UTC, yjjem commented on Diary/Controller/DetailViewController.swift
> +        delegate?.sendData(title: data.title,
별다른 이유는 없었지만 언래핑을 하여 얻는 것이 무엇이 있을까 고민해봤을 때
변경사항이 반영되지 않을 것이라는 알림을 띄우거나 콘솔에 에러메세지를 띄우는 것이 있을 것 같습니다.
delegate는 꼭 언래핑이 되어야하는 건가요???

2022-12-26 07:32 UTC, yjjem commented on Diary/Controller/DiaryViewController.swift
> +
return은 개행을 해주는 것으로 컨벤션을 맞췄습니다.

2022-12-26 07:52 UTC, iOS-Woong commented on Diary/Utilities/Ext + String.swift
> +    func parseData(titleWordsLimit: Int) -> (title: String, body: String) {
위 비즈니스로직을 처리할 때, 
1. detailView.text에서의 접근이 쉬워서 extension으로 구현했습니다.
2. 가장 좋지 않은 방법은 뷰컨트롤러 내부에서 함수를 만들어서 처리해주는 케이스가 가장 좋지 않다고 판단했습니다. 
(뷰컨의 역할은 View + Controller 이므로) 위 비즈니스로직의 경우에는 뷰컨트롤러 이외의 별도의 구간에서 처리해주어야 한다고 판단했습니다.

2022-12-26 08:01 UTC, yjjem commented on Diary/Utilities/Ext + String.swift
> +    func parseData(titleWordsLimit: Int) -> (title: String, body: String) {
다시 생각해보면 DetailViewController에서만 사용되는 익스텐션이라 파일 내부에 nest하여 filePrivate 지정해줄 수 있을 것 같습니다.
위에서 웅이 말한 것 처럼 ViewController가 할 일은 아닌 것 같고 그렇다고 SampleData에서 해줄 일 도 아닌 것 같아서 String extension으로 분리를 하였습니다. 
코드가 간결해지고 사용하기 쉽다는 것이 가장 큰 이유였던 것 같습니다.

String이 아니더라도 TextView의 extension으로도 만들어볼 수 있었을 것 같네요.
> 이렇게 extension 메서드를 활용하는 것은 좋은 방법일까요 알라딘?

2022-12-26 08:01 UTC, iOS-Woong commented on Diary/Controller/AddViewController.swift
> +}
네 맞습니다. 
버튼을 통해 화면이동을 하는 부분이 요구사항에 있었습니다.
하지만, AddVC에 대한 내부구현은 없어서 미리 추가해두기만 했습니다!

2022-12-26 08:29 UTC, yjjem commented on Diary/Controller/DiaryViewController.swift
> +                           body: sampleData[indexPath.row].body)
```swift
// 방법 1
cell.titleLabel.text = sampleData[indexPath.row].title
cell.bodyLabel.text = sampleData[indexPath.row].body
cell.createdAtLabel.text = sampleData[indexPath.row].createdAt.convertData()
```
```swift
// 방법 2        
cell.configureCell(title: sampleData[indexPath.row].title,
                   createdAt: sampleData[indexPath.row].createdAt,
                   body: sampleData[indexPath.row].body)
```

```swift
//방법 3
cell.configureCell(sampleData: sampleData[indexPath.row])
```

위와 같이 제일 간단하게는 3가지 방법을 생각해볼 수 있을 것 같아요. configureCell 메서드를 활용하여 sampleData를 통째로 넘겨 메서드 내에서 알아서 처리하도록 할 수 있었지만 VC가 무엇을 무엇과 연결하는지 보여주고 싶어서 방법 2를 채택했었습니다. 하지만 다시금 생각해보니 오히려 방법 1이 더 많은 것을 보여주네요 😬

알라딘은 이에 대해 어떻게 생각하시는지 궁금합니다.

2022-12-26 08:41 UTC, iOS-Woong commented on Diary/View/DiaryTableViewCell.swift
> +        self.accessoryType = .disclosureIndicator
꼭 필요한 경우가 아니라면 self. 는 생략하는 컨벤션으로 하겠습니다!

2022-12-26 08:47 UTC, yjjem commented on Diary/Controller/DetailViewController.swift
> +    weak var delegate: DetailViewControllerDelegate?
위의 tableViewCell의 상황과 같이 private을 지정할 수 있지만 detailViewController에 별도의 메서드를 정의해야 할 것 같아요.
무엇이 더 좋고 옳은지는 잘 판단이 서지 않네요.

2022-12-26 08:52 UTC, yjjem commented on Diary/View/DiaryTableViewCell.swift
> +    @IBOutlet weak var bodyLabel: UILabel!
ebdba4d
private 지정했습니다 🤠

2022-12-26 09:01 UTC, yjjem commented on Diary/Controller/DiaryViewController.swift
> +    private func tableViewAttribute() {
9764725
setTableView로 수정했습니다 !

2022-12-26 09:21 UTC, yjjem commented on Diary/Utilities/Ext + String.swift
> +        if components.count > 1 {
1. guard는 에러를 처리하거나 early exit을 위해 사용하고 if는 다중 구문을 처리할 일이 있을 떄 많이 사용했던 것 같습니다.
2. 위의 상황일 떄에는 사실 고민이 많이 되는 부분입니다. if를 쓰나 guard를 쓰나 큰 차이점은 없다고 생각했었습니다.

2022-12-26 15:03 UTC, junbangg commented on Diary/Utilities/Ext + String.swift
> +        if components.count > 1 {
큰 차이가 없다면 개인적으로 edge case 성을 띄는 로직을 `guard` 처리 할것 같아요!
꼭 그렇게 하실 필요는 없습니다👍

2022-12-26 15:04 UTC, junbangg commented on Diary/Utilities/Ext + String.swift
> +        if components.count > 1 {
그리고 이건 저번에 댓글 다는걸 깜빡했던 내용인데 .. 이 `parseData` 라는 메서드는 extension으로 하신 이유가 있나요??
extension으로 빼는 기준이 뭔지 궁금합니다!

2022-12-26 15:06 UTC, junbangg commented on Diary/Controller/AddViewController.swift
> +}
이후 PR 에 추가해야되는 코드가 있다면 `TODO: ` 로 주석 달아놓는것도 좋은것 같아요 개인적으로!!
주석은 지양하는게 맞지만 이런식으로 필요할때는 써주는것도 좋은것 같아요:)

2022-12-26 15:10 UTC, junbangg commented on Diary/Controller/DetailViewController.swift
> +    @IBOutlet weak private var detailTextView: UITextView!
아주 제대로 공부하셨군요!!👍👍👍👍
한번 고민 해보시면 좋을것 같아서 짚어봤습니다!

2022-12-26 15:28 UTC, junbangg commented on Diary/Controller/DiaryViewController.swift
> +                           body: sampleData[indexPath.row].body)
음 개인적인 생각을 말씀 드리면 저는 방법 3
```
let data = sampleData[indexPath.row]
cell.configureCell(with: data)
```
요런 느낌으로 갈것 같습니다! 
근거는 다음과 같아요 ( 그냥 개인적인 생각들)

1. 객체의 프로퍼티에 직접 접근하여 변경하지 않고, 메서드를 통해 변경하는 것이 OOP 의 기본 원칙 중의 하나라고 생각합니다👍
왜 그런건지 한번 고민해보시는것도 좋을것 같습니다:)

2. 방법 2도 나쁘지 않지만, 만약에 넣어야되는 데이터의 프로퍼티가 10개, 20개, 그 이상이 되면 어떨까요?🤔 또한, 계속 추가되면 어떨까요?? 그런 경우에는 데이터로 묶어서 하는게 좋을 수 있을것 같습니다!

2022-12-26 15:33 UTC, junbangg commented on Diary/Controller/DetailViewController.swift
> +    weak var delegate: DetailViewControllerDelegate?
별도의 메서드라면 `set___` 메서드 인거죠??
위에 제가 댓글 단거랑 이야기 똑같긴하네요!! :)

2022-12-26 15:36 UTC, junbangg commented on Diary/Utilities/Ext + String.swift
> +    func parseData(titleWordsLimit: Int) -> (title: String, body: String) {
오.. 제가 말씀 드리고 싶었던 부분들을 두분이서 그냥 다 이야기 해주신것 같아요!
저는 전역적으로 특정 비즈니스 로직에 디펜던시가 없을때 이런식으로 extension을 활용하는 편입니다~
다만 지금 같은 경우는 비즈니스 로직에 디펜던시가 있는 상태죠! 말씀해주신것 처럼 그래서 저는 꼭 extension으로 사용하고 싶으면
`fileprivate` 으로 할것 같네요!

2022-12-26 15:40 UTC, junbangg commented on Diary/Utilities/Ext + String.swift
> +    func parseData(titleWordsLimit: Int) -> (title: String, body: String) {
흠 근데 비즈니스로직을 ViewController 에서 떼어내려고 하는건 이유가 무엇인가요???(물론 틀렸다는건 아니지만..)
여쭤보는 이유는 만약에 지금보다 비즈니스 로직이 훨씬 많아서 어쩔 수 없이 ViewController에 넣어야된다면 어떻게 하실건가요??🤔
다 extension으로 뺄 수도 없을텐데 말이죠..!

2022-12-26 15:41 UTC, merged

2022-12-27 06:51 UTC, iOS-Woong commented on Diary/Utilities/Ext + String.swift
> +    func parseData(titleWordsLimit: Int) -> (title: String, body: String) {
**VC에 비즈니스 로직이 많아지는 경우**
만약, 비즈니스 로직이 너무 많아진다면 별도의 모델을 구성하여 관리하는 편이 좋을 것 같다는 생각이 드네요.
VC파일에 VC 클래스 이외 불필요한 코드도 줄이고 extension을 활용한느 것보다 가독성이 좋을 수 도 있겠다는 생각도 듭니다.

**현재 프로젝트의 비즈니스로직을 어떻게 처리할 것인가?**
1. 비즈니스로직에 디펜던시가 있는 상태이므로 해당 기능을 활용하는 뷰컨트롤러에서 fileprivate extension을 구성하려고 합니다.
(왜? 단지 하나의 로직을 처리하려고 별도의 모델을 생성하는 것은 그리 좋은 방법이 아니라는 생각에 위 방법을 선택했습니다.)
2. VC에 비즈니스 로직이 많아질 때는 위의 답과 동일하게 모델구성하여 대처하려합니다.

2022-12-27 07:23 UTC, yjjem commented on Diary/Controller/DiaryViewController.swift
> +                           body: sampleData[indexPath.row].body)
> 방법 2도 나쁘지 않지만, 만약에 넣어야되는 데이터의 프로퍼티가 10개, 20개, 그 이상이 되면 어떨까요?🤔 또한, 계속 추가되면 어떨까요?? 그런 경우에는 데이터로 묶어서 하는게 좋을 수 있을것 같습니다!
확실히 말씀해주신 대로 프로퍼티가 늘어나면 오히려 가독성이 떨어질 수 있겠군요. 

92fa18e
수정했습니다!