일기장 [STEP2] Ayaan, zhilly
yagom-academy/ios-diary pull request #72
Opened 2022-12-28 12:30 UTC by oneStar92

안녕하세요, 하비(@havilog)🙇🏻‍♂️🙇🏻! [Ayaan🦖](https://github.com/oneStar92), [zhilly🔥](https://github.com/zhilly11)입니다!
이번 스텝도 잘 부탁드립니다!!😁
Coredata 어렵네요...😭

# 📍고민했던 부분 

## ObjectID 사용
- CoreData의 Object에서 UUID를 id로 사용하여 관리할지 제공되는 ObjectID를 이용할지를 고민했습니다.
- UUID를 사용하면 특정 object를 얻으려면 fetch작업을 따로 정의해서 사용해야 하는 단점이 있었습니다.
- objectID를 사용하면 context의 메서드를 이용해서 update, delete를 손쉽게 사용할 수 있기 때문에 objectID를 사용했습니다.

## CoreDataStack 구현
- CRUD를 구현하기 위해서 CoreData의 Container를 이용해야했습니다.
- AppDelegate에 구현을 해두면 사용할 때마다 AppDelegate에서 가져오고 언래핑하고 할당해주는 번거로움이 있었습니다.
- 따라서 CRUD의 역할을 해주는 CoreDataStack 이라는 싱글톤 객체로 만들어서 사용했습니다.

## 모델
- CoreData로 사용하는 모델 하나로 구현을 해야할까, 아니면 앱에서 실질적으로 사용하는 모델 타입 하나를 추가로 만들어 두개의 모델로 구현을 해야할 까 고민했습니다.
- 한 개로 하면 CoreData 모델이 비즈니스 로직을 담당할 수는 있겠지만, CoreData 모델의 역할이 많아진다고 판단했습니다.
- 그렇다고 ViewController에서 비즈니스 로직을 담당하는 것도 아키텍처 관점에서 어긋난다고 생각했습니다.
- 따라서 실질적으로 사용하는 모델 타입을 만들어 비즈니스 로직을 처리하게 하여 이를 해결하였습니다.

<br>

# 📍해결하지 못한 부분

## **TemploryID(미해결)**
- NSFetchedResultsController를 이용하여 CoreData가 수정될때마다 자동으로 Diary List가 갱신되도록 구현했습니다.
- NSFetchedResultsController에서 받아오는 Snapshot은 TemploryID값이 포함되어 전달되는 문제가 발생했습니다.
- (TemploryID가 생성되는 이유는 아직 저장되지 않은 경우 개체 ID는 개체가 저장될 때 변경되는 임시 값입니다. [참고](https://developer.apple.com/documentation/coredata/nsmanagedobject/1506848-objectid))
- 처음 생성된 임시 objectID
`<x-coredata:///Task/tE1C5A230-A419-42D5-AF78-3327A09D13BD2>`
- 앱을 종료후 실행시킨 뒤 objectID
`<x-coredata://D6703834-ECB4-487B-84F8-330A215E16B7/Task/p13>`
- 해당 문제를 해결하는 방법을 찾지 못해서 NSFetchedResultsController를 사용하지 않고 Diary List를 갱신하도록 구현했습니다.
- havi는 혹시 이 현상을 해결하는 방법을 알고 계신가요???

<br>

# 📍조언을 얻고 싶은 부분

조언을 얻고 싶은 부분은 코멘트로 남겨놓았습니다!!

2022-12-28 12:42 UTC, oneStar92 commented on Diary/Source/ViewController/DiaryViewController.swift
> +            self?.showShareActivityView()
제 생각에는 1번 Alert이 present된 후 handler로 지정해준 코드블럭에서 2번 Alert을 present 하게되면 2번 Alert을 present되고 2번 Alert에서 작업을 진행 한 후 이어서 1번 Alert의 나머지 코드블럭을 진행할 것 같았습니다.
하지만 1번 Alert이 present된 후 handler로 지정해준 코드블럭에서 2번 Alert을 present 하게되면 1번 Alert 코드블럭이 끝난후 1번 Alert이 dismiss되고 이어서 2번 Alert이 present되는데 그 이유가 궁금합니다.

2022-12-29 13:26 UTC, havilog requested changes
고생하셨어요!

> DiaryCell을 모두 지운 후 +버튼을 클릭하게 되면 아래와 같은 AutoLayout 오류가 발생합니다.

요거는 일단 `DiaryViewController`의 `contentTextView` 제약조건이 깨지는거 같은데,
제약조건을 안깨지게 수정하기 보다 다이어리 로직의 개편이 있어야할 거 같아요!
디코에서 얘기해보시져 ㅎㅎ

2022-12-29 13:26 UTC, havilog commented on Diary/Source/Extension/NotificationName+Extension.swift
> +    static let didEnterBackground = Notification.Name("didEnterBackground")
LGTM 👍

2022-12-29 13:26 UTC, havilog commented on Diary/Source/Common/DiaryCoreDataStack.swift
> +final class DiaryCoreDataStack {
1. `DiaryCoreDataStack`은 어떤 의도로 만들어진건지 궁금합니다. `DiaryDataManager`와 어떤 차별점을 두려고 만드셨을까요?
2. 해당 앱에서 일기가 아니라, 코어 데이터에 저장해야할 객체가 여러개일 경우에 어떻게 처리하려고 고민하셨는지 궁금해요
3. 데이터매니저는 뷰컨에서 주입해주고, 데이터 스택은 싱글톤으로 구현하신 이유가 뭘까요?
4. save나 load에 실패했을 때 에러처리는 어떻게하는게 적절할까요?

2022-12-29 13:26 UTC, havilog commented on Diary/Source/Common/DiaryDataManager.swift
> +        }
난 분명 일기가 10개 저장되어있었는데, 로드에 실패해서 빈 다이어리를 보여준다면 혼란스러울 수도 있을거 같은데, 빈 배열로 리턴하신 이유가 있을까요?

2022-12-29 13:26 UTC, havilog commented on Diary/Source/Protocol/DiaryManageable.swift
> +}
프로토콜의 기능으로,
프로토콜로 해당 객체의 기능 명시
프로토콜로 공통 기능 재사용
추상화로 인한 의존성 역전
등이 있을텐데,

이 DiaryManageable프로토콜을 구현해주실 때 어떤 의도로 구현해주신건지 궁금합니다.

2022-12-29 13:26 UTC, havilog commented on Diary/Source/ViewController/DiaryListViewController.swift
> +        loadDiary()
다이어리 로드 시점을 viewDidAppear로 잡아주신 이유가 궁금해요~

2022-12-29 13:26 UTC, havilog commented on Diary/Source/ViewController/DiaryViewController.swift
> +    @available(*, unavailable)
요 코드의 의미는 무엇인가요?

2022-12-29 13:26 UTC, havilog commented on Diary/Source/ViewController/DiaryViewController.swift
> +        }
뷰의 상태에 직접 접근하기 보다는, contentTextView의 텍스트를 핸들링하는 프로퍼티 or 객체를 생성해주는 방법도 고민해보면 좋을 것 같아요.

2022-12-29 13:26 UTC, havilog commented on Diary/Source/ViewController/DiaryViewController.swift
> +            alert.addAction(action)
```suggestion
[cancelAction, deleteAction].forEach(alert.addAction)
```

2022-12-29 13:26 UTC, havilog commented on Diary/Source/ViewController/DiaryListViewController.swift
>  }
다이어리를 로드하는거랑, 스냅샷에 어플라이하는거랑은 역할 분리가 필요해보여요.

2022-12-30 04:36 UTC, zhilly11 commented on Diary/Source/ViewController/DiaryViewController.swift
> +            alert.addAction(action)
이렇게도 쓸 수 있군요 대박
수정했습니다~

[fbadf03](https://github.com/yagom-academy/ios-diary/pull/72/commits/fbadf03c215c7882fc6ab55fe086c0c2dc00ea80)

2022-12-30 04:57 UTC, oneStar92 commented on Diary/Source/ViewController/DiaryViewController.swift
> +    @available(*, unavailable)
해당 init을 프로젝트에서 사용할 수 없다를 명시해주는 것으로 알고있습니다

2023-01-02 13:29 UTC, zhilly11 commented on Diary/Source/ViewController/DiaryListViewController.swift
>  }
[9088c0b](https://github.com/yagom-academy/ios-diary/pull/72/commits/9088c0bcd384db5c53005db87fefbf5fd1def7ac)

역학 분리 완료했습니당~

2023-01-02 13:31 UTC, oneStar92 commented on Diary/Source/Common/DiaryCoreDataStack.swift
> +final class DiaryCoreDataStack {
[47bb8fe](https://github.com/yagom-academy/ios-diary/pull/72/commits/47bb8fed437ab912c5aa4723f23596034e96359d) 디스코드에서 이야기 나눈 방향으로 적용해 봤습니다!!

2023-01-02 13:32 UTC, zhilly11 commented on Diary/Source/ViewController/DiaryViewController.swift
> +        }
[f7dd478](https://github.com/yagom-academy/ios-diary/pull/72/commits/f7dd478b2500ac40e9130f64eb78e2b7eb9fbf67)

View의 상태를 직접 접근해서 하는 방식에서 하비의 조언대로 프로퍼티나 객체를 선언해 주는 방식으로 생각을 해보았었는데 아이디어가 잘 떠오르지 않아서, model의 상태를 사용해 보는 방식으로 수정해 보았습니다!

2023-01-02 13:32 UTC, oneStar92 commented on Diary/Source/Common/DiaryDataManager.swift
> +        }
rethorw를 통해 사용하는 곳에서 에러를 핸들링하도록 구현했습니다.

2023-01-02 13:33 UTC, oneStar92 commented on Diary/Source/Protocol/DiaryManageable.swift
> +}
[47bb8fe](https://github.com/yagom-academy/ios-diary/pull/72/commits/47bb8fed437ab912c5aa4723f23596034e96359d) 이 부분도 디스코드에서 이야기 나눈 방향으로 수정했습니다.

2023-01-02 13:34 UTC, zhilly11 commented on Diary/Source/ViewController/DiaryListViewController.swift
> +        loadDiary()
viewWillAppear에서 했을 때에는 뷰컨트롤러의 Life Cycle 때문에 상위 뷰가 사라지기 전에 진행되는 시점의 문제 때문에 로드 시점을 viewDidAppear로 잡아주었습니다!

2023-01-03 14:26 UTC, havilog commented on Diary/Source/ViewController/DiaryViewController.swift
> +    @available(*, unavailable)
fatalError를 찍어주는데 available로 이중(?)으로 해주는건 처음본거 같아서 질문드렸어요 ㅎㅎ
fatalError 대신 super를 호출해주는 사람들도 있더라구요 ! 참고만 하세요 ㅎㅎ

2023-01-03 14:30 UTC, havilog approved these changes
두 분 모두 수고하셨어요!
다음 스탭을 진행하세요 : )

2023-01-04 14:15 UTC, merged