일기장 [STEP-2] 하모, 미니
yagom-academy/ios-diary pull request #73
Opened 2022-12-28 13:26 UTC by lxodud

@junbangg
알라딘 행복한 연말 보내고 계신가요??
월요일에 올라온 프로젝트에 맞춰서 계획을 세우고 프로젝트를 진행했습니다.

## 📝 STEP 진행 중 경험하고 배운 것
- `Core Data`
- `UIActivityViewController`
- `UISwipeActionsConfiguration`
- `UIAlertController ActionSheet`
- `UIContextualAction`

## 💭 고민한 부분

### `CoreDataManager`의 구성

코어데이터 매니저를 구성하는 데 있어서 고민한 부분이 있었습니다. 앱 전역적으로 사용해야 하는 것이기 때문에 싱글턴을 사용해도 될까 라는 고민을 하게 되었습니다. 또한, 코어데이터 매니저에 대해서 유닛 테스트를 적용하는 것에 대해서도 고민하게 되었습니다. 

코어 데이터의 유닛 테스트를 진행하기 위해서는 In-Memory 특성을 가지는 PersistentContainer를 이용하여 Stub한 코어 데이터 매니저를 구현할 수 있어야 합니다. 즉, 코어 데이터 매니저를 싱글톤 패턴으로 구현하지 못하고, initalizer를 가지고 있어야 하는 상황이 발생한 것입니다. 위와 같이 트레이드 오프한 상황에 대처하기 위해서 각각의 장점을 표로 정리하고 함께 토론 하면서 어떤 점을 중점으로 앱을 개발하는 것이 중요한가에 대해서 함께 고민하였습니다.

| 싱글톤 | 유닛 테스트 |
| --- | --- |
| 앱이 전반적으로 코어 데이터에 접근할 수 있다. | 앱이 전반적으로 코어 데이터에 접근할 수는 없지만, 코드가 의도한 대로 동작하는 지 확인하기 용이하다. |

위와 같은 표에서 싱글톤을 사용하는 것이 더 좋은 장점을 가지고 있다고 판단하였습니다.

### `UIContextualAction`의 `Completion`
SwipeAction을 구현하기 위해서는 UIContextualAction 타입을 구현해야 합니다. UIContextualAction타입은 사용자가 테이블 행을 스와이프할 때 표시할 동작으로 completionHandler를 가지고 있으며, 이를 통해서 액션이 정상적으로 동작하였는지에 대한 값을 반환해 주고 있습니다.
요구 사항에 따르면, 삭제 버튼을 누를 경우에는 다시 삭제에 대한 핸들러 내부에서 다음 동작을 할 수 있도록 구현하여야 합니다. 이에 대해서 많은 고민을 하게 되었습니다. 많은 컴플리션 핸들러를 통해서 코드의 가독성이 많이 떨어지기 때문입니다. 아래와 같이 completionHandler와 동일한 형식의 함수를 구성하고 그 내부에서 다음동작을 할 수 있도록 하였습니다. 또한, 많은 정보를 줄 수 없는 init를 대체하기 위해서 convenience init를 구성하고 이를 활용하여서 컴플리션 핸들러를 줄였습니다.

```swift
let handler: UIContextualAction.Handler = { [weak self] _, _, handler in
    let alert = UIAlertController(
        title: NSLocalizedString("DeleteTitle", comment: "삭제 Alert 제목"),
        message: NSLocalizedString("DeleteMessage", comment: "삭제 Alert 본문"),
        preferredStyle: .alert
    )
    
	let deleteAction = UIAlertAction(type: .delete) { [weak self] _ in
	    guard let self = self else { return }
	    
	    let result = self.deleteSnapshot(item: item)
	    handler(result)
	}
            
    let cancelAction = UIAlertAction(type: .cancel) { [weak self] _ in
        handler(false)
    }
            
    alert.addAction(deleteAction)
    alert.addAction(cancelAction)            
    self?.present(alert, animated: true)
}
        
let handler: UIContextualAction.Handler = { [weak self] _, _, handler in
    guard let self = self else { return }
    
    let alert = UIAlertController(
        title: LocalizedConstant.AlertController.deleteTitle,
        message: LocalizedConstant.AlertController.deleteMessage,
        diary: item,
        deleteCompletion: { [weak self] _ in
            guard let self = self else { return }
            
            let result = self.deleteSnapshot(item: item)
            handler(result)
        },
        cancelCompletion: { _ in
            handler(false)
        }
    )
    
    self.present(alert, animated: true)
}

```

### 지역화에 맞춘 앱 구성시 앱의 상수를 관리하는 방법
앱에 대해서 지역화를 구성하기 위해서 각 문자열에 대해서 고민하게 되었습니다. 많은 NSLocalizedString 타입을 직접적인 문자열을 활용하여서 구성하는 것이 다른 코더가 보았을 때, 수정해도 되는 문자열이라고 착각할 수 있을 것 같다는 생각이 들었습니다. 그래서 앱 전체에서 사용되는 지역화된 문자열 상수를 LocalizedConstant 타입으로 묶어서 관리하였습니다. 그래서 다음과 같이 앱에 필요한 상수들을 한개의 enum타입에서 모두 관리할 수 있도록 하였습니다.

```swift
let alert = UIAlertController(
    title: NSLocalizedString("DeleteTitle", comment: "삭제 Alert 제목"),
    message: NSLocalizedString("DeleteMessage", comment: "삭제 Alert 본문"),
    ...
```

```swift
let alert = UIAlertController(
    title: LocalizedConstant.AlertController.deleteTitle,
    message: LocalizedConstant.AlertController.deleteMessage,
        ...
```

## 🤔 조언을 얻고 싶은 부분
### 많은 `guard let`의 사용
`DiaryDetailViewController`에서 textField, textView의 text를 다루는데 해당 프로퍼티의 타입이 optional이기 때문에 각 메서드들에서 두 text프로퍼티를 옵셔널 바인딩하는 코드가 중복되어서 나타났습니다. textField와 textView에 아무런 입력이 없을 때 text 프로퍼티는 nil이 아닌 빈 문자열을 가지고 있기 때문에 UITextField와 UITextView를 extension하여 text의 옵셔널을 해제하여 리턴하는 프로퍼티를 정의하여 `DiaryDetailViewController`에서 중복되는 옵셔널 바인딩을 줄여보았습니다. 이러한 방식을 활용하여서 `guard let` 구문을 줄이는 것이 적절한 지 알라딘의 생각이 궁금합니다. (물론...정답은 없겠지만...)

### 코어데이터의 Response와 앱에서 사용할 데이터의 분리
코어 데이터를 데이터 베이스와 동일한 측면으로 생각하게 되면, 네트워킹을 통해서 받아오는 원천 데이터로 생각하였습니다. 원천 데이터를 직접적으로 뷰에 보여주는 것을 적절하지 않고 의도치 않은 수정이 바로 반영이 될 수 있는 점에서 위험하다고 생각하였습니다. 그래서 코어 데이터를 통해서 받아오는 데이터를 가공하여서 뷰에 보여줄 데이터를 따로 구성하였습니다. 또한, 위와 같이 구성하면서 모든 타입이 옵셔널을 사용할 수 없도록 하였습니다.
알라딘은 위와 같은 상황에서 네트워크를 통해서 받아오는 객체를 직접적으로 사용하는 것에 대해서 어떻게 생각하시나요?

### 추가적인 기능 구현 - 사용자 선택에 따른 정렬 기준
앱을 구성하다 보니 사용자의 입장에서 사용자 기준이 아닌 일별로 내림차순을 하는 것이 적절한지에 대해서 생각해보았고, 이에 대해서 직접적으로 선택할 수 있는 것에 대해서 생각해보았습니다. 추가적인 기능 구현이라서 아직 구현을 하지는 않았습니다. 혹시 이런 부분을 추가적으로 구현해도 괜찮을까요?

2022-12-31 09:05 UTC, junbangg requested changes

2022-12-31 09:05 UTC, junbangg commented on .swiftlint.yml
> +    error: 120
오..!

2022-12-31 09:05 UTC, junbangg commented on Diary/Sources/Controller/DiaryDetailViewController.swift
> +    private func bindKeyboardObserver() {
오 메서드명에 `bind` 를 넣은 이유가 있나요??

2022-12-31 09:05 UTC, junbangg commented on Diary/Sources/Controller/DiaryDetailViewController.swift
> +    private var item: Diary?
`Diary` 타입을 `item` 으로 정한 이유가 있나요?? 
`item` 에 여러 종류의 타입이 들어갈 수 있는게 아니라면 조금 더 구체적인 이름도 괜찮을것 같습니다.

2022-12-31 09:05 UTC, junbangg commented on Diary/Sources/Controller/DiaryDetailViewController.swift
> +    private func createContents(
지금 `item`, `Diary`, `Contents` 등 다양한 네이밍을 사용해주고있는데, 조금 더 통일 시키는건 어떨까요??
가독성 지금도 엄청 좋은 편인데 조금 더 좋아질것 같습니다👍

위에서 `createContents()` 가 호출되는걸 보면, `item` 뿐만 아니라 `UI` 가 전체적으로 구성이 될것 같은 느낌이 들어요 개인적으로는🙋‍♂️

2022-12-31 09:05 UTC, junbangg commented on Diary/Sources/Controller/DiaryDetailViewController.swift
> +    private func didTappedDeleteButton(_ action: UIAlertAction) {
`didTap` == `tapped` 이기 때문에 `didTapDeleteButton` 이 알맞을것 같아요!!

2022-12-31 09:05 UTC, junbangg commented on Diary/Sources/Controller/DiaryDetailViewController.swift
> +    private func didTappedShareButton(_ action: UIAlertAction) {
여기도요!

2022-12-31 09:05 UTC, junbangg commented on Diary/Sources/Controller/DiaryDetailViewController.swift
> +        if !isNotEmpty {
`!isNotEmpty` 도 좋지만 `isNotEmpty == false` 는 어떠신가요??
조금 더 직관적이고 자연스럽게 읽힌다는 개인적인 생각입니다 :) 
꼭 따르실 필요는 물론 없습니다 이런것은👍

2022-12-31 09:05 UTC, junbangg commented on Diary/Sources/Controller/DiaryDetailViewController.swift
> +
불필요한 줄바꿈이 있네요!

2022-12-31 09:05 UTC, junbangg commented on Diary/Sources/Controller/DiaryDetailViewController.swift
> +    private var item: Diary?
`DiaryListViewController` 에서 `[Diary]` 는 이름이 `diaries` 네요!

2022-12-31 09:05 UTC, junbangg commented on Diary/Sources/CoreDataManager.swift
> +extension DiaryEntity {
오 `Entity` 는 굉장히 멋진 네이밍인데🤔
`Entity` 로 지으신 이유가 궁금합니다~!

2022-12-31 09:05 UTC, junbangg commented on Diary/Sources/Model/Utility/LocalizedConstant.swift
> +enum LocalizedConstant {
코멘트 주신거 읽어봤는데 굉장히 바람직한(?) 고민을 하셨었네요👍👍👍

2022-12-31 09:05 UTC, junbangg commented on Diary/Sources/View/DiaryListViews/DiaryListCellContentView.swift
> +        setupSubviews()
👍👍👍👍👍👍

2023-01-02 02:16 UTC, lxodud commented on .swiftlint.yml
> +    error: 120
다음과 같은 코드를 작성하다가 저희가 정한 컨벤션이 무너지고 swiftLint 오류가 발생해서 변경하였습니다(시적허용? 허허허) 
```swift
        guard let rootViewController = window?.rootViewController as? UINavigationController,
              let topViewController = rootViewController.topViewController as? DiaryDetailViewController
        else {
            return
        }
```
알라딘은 같이 타입캐스팅이 길어지면 어떤 컨벤션을 사용하시나요?!!

2023-01-02 02:19 UTC, leegyoungmin commented on Diary/Sources/Controller/DiaryDetailViewController.swift
> +    private func bindKeyboardObserver() {
음... 정확하게 바인딩을 하는 작업은 아니지만, 키보드가 올라오는 것을 관찰하고 있기 때문에 바인드라는 용어를 사용하였습니다.
추가적으로 바인딩을 하는 방법에는 `rxSwift`, `Combine` 등과 같은 라이브러리를 사용하는 방법과 `Observer` 타입을 따로 구현하여 활용하는 방법 등이 있습니다.

2023-01-02 02:36 UTC, lxodud commented on Diary/Sources/Controller/DiaryDetailViewController.swift
> +    private func didTappedDeleteButton(_ action: UIAlertAction) {
잘못된 문법을 사용하고 있었네요 ㅠㅠ
수정 완료했습니다!!

2023-01-02 02:43 UTC, leegyoungmin commented on Diary/Sources/Controller/DiaryDetailViewController.swift
> +        if !isNotEmpty {
조금 더 구문을 읽다보니 다른 사람이 읽었을 경우에 이해가 안될 수 있는 문법과 필요없는 설정을 하는 부분이 발생하여서 `if item == nil` 이라는 구문으로 변경하였습니다. [6852a0f](https://github.com/yagom-academy/ios-diary/pull/73/commits/6852a0fb421d80dcc8e2de8eeb306abbfe671d01)

2023-01-02 02:43 UTC, leegyoungmin commented on Diary/Sources/Controller/DiaryDetailViewController.swift
> +    private func didTappedShareButton(_ action: UIAlertAction) {
위와 동일하게 변경하였습니다.

2023-01-02 02:44 UTC, lxodud commented on Diary/Sources/Controller/DiaryDetailViewController.swift
> +
수정 완료했습니다!!!!!

2023-01-02 02:46 UTC, leegyoungmin commented on Diary/Sources/CoreDataManager.swift
> +extension DiaryEntity {
네트워킹을 하는 것은 아니지만, 데이터 베이스 상에서 데이터를 가져오는 작업을 하는 타입이라고 생각했습니다.
그래서 이에 대해서 실질적으로 뷰에 보여지는 데이터와 구분 지을 필요가 있다고 생각해서 Entitiy라는 이름을 활용하여서 뷰에 전달 되는 데이터가 아닌, 코어 데이터 베이스에 저장되는 데이터라는 의미를 지니기 위해서 활용하였습니다.

2023-01-02 02:57 UTC, leegyoungmin commented on Diary/Sources/Controller/DiaryDetailViewController.swift
> +    private func createContents(
다시 코드를 읽다보니까 그런 느낌이 들긴하네용...
그래서 다시 한번 코드를 살펴 보면서 네이밍을 통일할 수 있도록 했습니다!

2023-01-02 02:57 UTC, lxodud commented on Diary/Sources/Controller/DiaryDetailViewController.swift
> +    private var item: Diary?
알라딘의 의견에 동의합니다 ㅎㅎㅎㅎ
diary로 프로퍼티 네이밍 변경하였습니다!!

2023-01-02 08:57 UTC, merged

2023-01-08 07:10 UTC, junbangg commented on .swiftlint.yml
> +    error: 120
음..사실 ㅋㅋ저런건 어쩔 수 없이 그냥 두는 편입니다ㅎㅎㅎㅎ