일기장 [STEP 2] 애런, 로빈, 건디
yagom-academy/ios-diary pull request #74
Opened 2022-12-29 02:49 UTC by Gundy93

![](https://i.imgur.com/FZ21nXs.png)

@ryan-son
안녕하세요 라이언~ 애런, 로빈, 건디입니다! 이번 스텝에 대해서도 지도 부탁드립니다!

## 🤔 고민했던 점
막상 프로젝트를 진행할 때는 고민을 무척 많이 한 것 같은데 이제와서 보니 사소한 것들 뿐이라 미처 다 적을 수가 없네요 😅...아래는 중점적으로 고민한 사항들입니다.

### 재사용
```swift!
private func showDeleteActionAlert() {
    ...
}

private func showActivityViewController(diary: Diary) {
     ...
}
```
삭제 알림창을 띄워 주는 부분과 액티비티 창을 띄워주는 부분이 `DiaryListViewContoller`와 `DiaryViewController`에 중복되어 사용됩니다. 
수정화면의 더보기에서 접근 하는 루트와 테이블뷰에서 스와이프 해서 접근하는 루트가 있는데 해당 중복 되는 부분을 반복해서 사용하지 않기 위해 고민해 보았지만 약간의 차이와 전역적으로 선언할 위치가 고민되어 각 뷰컨트롤러 마다 함수를 따로 선언해 두었습니다. 이렇게 중복되는 메서드가 있을때 라이언은 어떤식으로 처리하시는지 궁금합니다~

### 하나의 뷰컨트롤러를 통해 편집과 추가 화면 동시 사용
step1 에서는 새로운 일기를 생성할 때 `NewDiaryViewController`으로 이동하게 하였는데, 기존일기 편집과 새로작성하는 뷰가 같아서 굳이 새로운 뷰컨트롤러가 필요할까라는 생각을 했습니다. 그래서 `DiaryViewController` 하나로 사용하는 것으로 결정하였습니다. 하지만 아직 저장하지 않은 다이어리에 대해서 삭제를 시도하는 것을 방지하고자 신규 작성의 경우 `rightBarButtonItem`을 넣어주지 않는 방향으로 진행하였습니다.

### UIMenu
프로젝트 명세서에서는 일기장화면에서 더보기 버튼을 누르면 `ActionSheet`이 나오도록 되어있었지만, `UIMenu`를 사용하여 구현하였습니다. HIG에서 `ActionSheet`를 공부해 보았을때 `ActionSheet`는 삭제, 내용편집, 되돌리기와 같이 결과물에 지장을 주는 작업이 이기때문에 이를 알려주기 위한 경고창으로 이해했고, 작업과 관련하여 추가적인 선택사항(일기장에서는 공유기능이라고 생각했습니다)을 제공하지 않는다는 것을 보고, `UIMenu`를 선택해서 공유기능과 삭제기능을 제공하도록 구현하였습니다. 

![](https://i.imgur.com/1zP4Nsf.png)

## 🧑‍🏫 조언을 얻고 싶은 부분

### 경로를 변경했음에도 기존의 데이터가 나오는 현상
코어 데이터 설정을 마친 이후에도 기존의 샘플 데이터가 출력되는 이슈가 있었습니다.
`/Users/sy/Library/Developer/CoreSimulator/Devices/`
조금 찾아보니 해당 위치에서 시뮬레이터의 데이터를 삭제하니 정상적으로 작동했지만 왜 이런 현상이 발생하는지 원인은 알 수 없었습니다. 혹시 해당 이슈에 대해 경험해 보신 적이 있으실까요?

### AppDelegate vs CoreDataManager
프로젝트를 생성할 때 CoreData를 사용하면 `AppDelegate` 내부에 CoreData와 관련된 코드가 추가됩니다. 저희는 따로 `CoreDataManager`라는 타입을 만들어서 그 역할을 주었는데, 보통 이런 경우 `AppDelegate`에서 해당 로직을 구현해야 하는 것일까요?

### 현재 화면의 뷰컨트롤러 판독
```swift
func sceneWillResignActive(_ scene: UIScene) {
    let rootViewController = UIApplication.shared.keyWindow?.rootViewController
    if let topViewController = UIApplication.topViewController(rootViewController) as?
DiaryViewController {
        topViewController.updateCoreDataIfNeeded()
    }
}
```
앱이 백그라운드에 진입할 때 작성/편집 중이던 일기를 저장해야 합니다. 하지만 백그라운드로 들어갈 때마다 저장 기능을 호출한다면 자원이 그만큼 낭비되리라 생각합니다. 다이어리의 상세화면에서만 백그라운드 진입시 저장을 할 수 있도록 현재 보여지는 `topViewController`를 구하는 로직을 `sceneWillResignActive` 내부에 넣어, 해당 뷰컨트롤러가 `DiaryViewController`일 때만 저장할 수 있도록 하였습니다.
하지만 이 방법 외에도 특정 뷰컨트롤러에서 백그라운드 진입시 작업을 진행시킬 수 있는 더욱 효율적인 방법이 있는지 알고싶습니다.

### UUID vs ObjectID
ObjectID를 사용하면 CoreData에 저장된 특정 Object에 접근하여 Context를 수정할 수 있고, UUID보다 속도적인 측면 등에서도 이점이 있었습니다. 하지만 저희는 샘플데이터를 받아오기 위한 모델인 `DiaryResponseDTO`에서 `toDomain`을 실행할 때, ObjectID를 할당해줄 수 없는 문제가 있어 UUID를 통한 방법으로 사용하였습니다. 이러한 상황에서 ObjectID를 활용할 적절한 방법이 있을까요?

2022-12-31 06:21 UTC, ryan-son requested changes
애런, 로빈, 건디, Step 2도 고생 많으셨습니다~

>삭제 알림창을 띄워 주는 부분과 액티비티 창을 띄워주는 부분이 `DiaryListViewContoller`와 `DiaryViewController`에 중복되어 사용됩니다. 
> 수정화면의 더보기에서 접근 하는 루트와 테이블뷰에서 스와이프 해서 접근하는 루트가 있는데 해당 중복 되는 부분을 반복해서 사용하지 않기 위해 고민해 보았지만 약간의 차이와 전역적으로 선언할 위치가 고민되어 각 뷰컨트롤러 마다 함수를 따로 선언해 두었습니다. 이렇게 중복되는 메서드가 있을때 라이언은 어떤식으로 처리하시는지 궁금합니다~

상속이나 프토토콜 기본구현을 이용해볼 수도, 얼럿을 띄울 ViewController를 전달 받아 얼럿을 띄워줄 메서드를 만들어볼 수도 있습니다. 여러 방법으로 만들어보시고 어떤 방식이 좋았는지 서로 이야기 나눠보시면 좋겠네요.

>## 🧑‍🏫 조언을 얻고 싶은 부분

>### 경로를 변경했음에도 기존의 데이터가 나오는 현상
>코어 데이터 설정을 마친 이후에도 기존의 샘플 데이터가 출력되는 이슈가 있었습니다.
>`/Users/sy/Library/Developer/CoreSimulator/Devices/`
조금 찾아보니 해당 위치에서 시뮬레이터의 데이터를 삭제하니 정상적으로 작동했지만 왜 이런 현상이 발생하는지 원인은 알 수 없었습니다. 혹시 해당 이슈에 대해 경험해 보신 적이 있으실까요?

코드와 함께 보지 않으면 정확한 상황을 파악하기는 어렵네요. 혹시 당시의 코드를 보여주실 수 있으실까요?

>### AppDelegate vs CoreDataManager
>프로젝트를 생성할 때 CoreData를 사용하면 `AppDelegate` 내부에 CoreData와 관련된 코드가 추가됩니다. 저희는 따로 `CoreDataManager`라는 타입을 만들어서 그 역할을 주었는데, 보통 이런 경우 `AppDelegate`에서 해당 로직을 구현해야 하는 것일까요?

아뇨. 객체지향 프로그래밍 개념에 따라 구분되는 역할이 있다면 타입을 구분하는 편이 유연한 구조를 만들기에 더 도움이 됩니다. 타입을 분리하고 의존성 주입을 누가 하는 것이 좋을지를 고려하다보면, `@main`과 가까운 타입은 Composition Root로서 의존성 주입을 담당하게 됩니다.

>### 현재 화면의 뷰컨트롤러 판독
>앱이 백그라운드에 진입할 때 작성/편집 중이던 일기를 저장해야 합니다. 하지만 백그라운드로 들어갈 때마다 저장 기능을 호출한다면 자원이 그만큼 낭비되리라 생각합니다. 다이어리의 상세화면에서만 백그라운드 진입시 저장을 할 수 있도록 현재 보여지는 `topViewController`를 구하는 로직을 `sceneWillResignActive` 내부에 넣어, 해당 뷰컨트롤러가 `DiaryViewController`일 때만 저장할 수 있도록 하였습니다.
하지만 이 방법 외에도 특정 뷰컨트롤러에서 백그라운드 진입시 작업을 진행시킬 수 있는 더욱 효율적인 방법이 있는지 알고싶습니다.

특정 뷰 컨트롤러인지의 여부에 따라 저장 로직이 실행되기보다, `CoreDataManager`과 같은 타입이 스스로 저장을 해야할지 여부를 가지고 있고, 이 여부에 따라 `sceneWillResignActive`와 같은 이벤트가 발생될 때 선택적으로 저장 로직을 실행하는 편이 좋을 것 같네요. 특정 로직이 특정 뷰에 의존하기보다 타입이 스스로 자신을 책임질 수 있는 방법은 없는지 방법을 생각해보세요.

>### UUID vs ObjectID
>ObjectID를 사용하면 CoreData에 저장된 특정 Object에 접근하여 Context를 수정할 수 있고, UUID보다 속도적인 측면 등에서도 이점이 있었습니다. 하지만 저희는 샘플데이터를 받아오기 위한 모델인 `DiaryResponseDTO`에서 `toDomain`을 실행할 때, ObjectID를 할당해줄 수 없는 문제가 있어 UUID를 통한 방법으로 사용하였습니다. 이러한 상황에서 ObjectID를 활용할 적절한 방법이 있을까요?

백엔드가 있다고 생각한다면, `Diary`를 서버에 post할 때 id값을 포함해 요청할 것이고, ResponseDTO로 받을 때도 id값이 포함되어 있을 거라고 생각해 볼 수 있습니다. 이 id에 UUID를 사용해볼 수도 있고, ObjectID를 사용해볼 수도 있습니다. 여러 방안을 생각해보고 어떤 방향이 좋을지 논의해보시면 좋을 것 같네요.

고생 많으셨습니다. 궁금하신 점이 있으시면 말씀해주세요~!

2022-12-31 06:21 UTC, ryan-son commented on Diary/Controller/DiaryListViewController.swift
> +        diaryList = items.reversed()
1. [P3] `Array.reversed()` 메서드를 두 번 연산하는 것보다 지역변수로 할당해서 한 번만 연산할 수 있게 해주면 좋을 것 같아요.
2. [P3] `Array.reversed()`를 하는 이유와 어떤 결과를 원하고 이 동작을 수행하는지를 알려줄 수 있으면 좋겠어요. 첫번째 방법은 지역변수 이름을 지어보는 것, 두번째는 구현 주석(//)으로 의도한 내용을 남기는 것을 고려해볼 수 있습니다.

2022-12-31 06:21 UTC, ryan-son commented on Diary/Controller/DiaryViewController.swift
>      }
`isExistDiary`는 현재 존재하는 일기인지 여부를 의미하는 걸로 추정되는데, 확신을 가지기는 어렵네요. 이름을 명확하게 짓는 걸 가장 먼저 고려해봐야겠지만, 어렵다면 문서화 주석이나 구현 주석을 남기는 것도 좋습니다.

2022-12-31 06:21 UTC, ryan-son commented on Diary/Controller/DiaryViewController.swift
> +                          children: [shareAction, deleteAction, cancelAction])
`UIMenu`에서 취소 액션을 제공하는 것도 좋아보이네요. 빈 공간을 탭해서 메뉴를 비활성화시키는 UX에 더해서 취소 액션을 제공하면서 고려하셨던 부분이 있으셨나요?

2022-12-31 06:21 UTC, ryan-son commented on Diary/Controller/DiaryViewController.swift
> +    private func makeMenu() -> UIMenu {
[P4] 어떤 메뉴를 만드나요? 메서드 이름을 통해 의도를 명확하게 알려주시면 좋겠습니다.

2022-12-31 06:21 UTC, ryan-son commented on Diary/CoreData/CoreDataManager.swift
> +    }
`NSManagedObjectContext`는 어떤 역할을 수행하나요? 여러분이 만들지 않았지만 `viewContext`라는 것이 존재하는 군요. `viewContext`는 어떤 특징을 가지고 있나요?

2022-12-31 06:21 UTC, ryan-son commented on Diary/CoreData/CoreDataManager.swift
> +            try context.save()
`viewContext`는 특정 스레드와 관련있는 context이므로 변화가 있는 경우에만 저장 메서드를 수행하는 것이 좋습니다. 아래 문서를 참고해보세요.
- [hasChanges - Apple Developer](https://developer.apple.com/documentation/coredata/nsmanagedobjectcontext/1506954-haschanges)

2022-12-31 06:21 UTC, ryan-son commented on Diary/CoreData/CoreDataManager.swift
> +    }
`CoreDataManager`는 지금 `Diary`와 관련된 타입을 다루고 있죠. 하지만 다른 타입을 다루게 될 때 기존 메서드 이름을 변경하기보다 평소에 자신이 수행하는 로직을 이름을 통해 더 설명해두는 것이 더 좋을 수 있습니다.

2022-12-31 06:21 UTC, ryan-son commented on Diary/CoreData/CoreDataManager.swift
> +        return diaryList
[P5] map으로 처리해볼 수도 있겠네요~ 그런데 `Diary` 타입으로 변환하는 역할을 `CoreDataManager`와 `ViewController` 중 누가 수행하는 게 어울릴까요?

2022-12-31 06:21 UTC, ryan-son commented on Diary/CoreData/CoreDataManager.swift
> +        } else {
`filter` -> `isEmpty`은 `contains`, `filter` -> `first`는 `first(where:)`를 고려해보세요.

2022-12-31 06:21 UTC, ryan-son commented on Diary/CoreData/CoreDataManager.swift
> +        }).isEmpty {
가능하다면 프로퍼티가 같다는 것을 비교하기보다 인스턴스 자체를 비교할 수 있도록 수단을 마련하는 것이 좋습니다.

2022-12-31 06:21 UTC, ryan-son commented on Diary/Extension/UITableView+.swift
> +    }
👍

2022-12-31 06:21 UTC, ryan-son commented on Diary/Model/Diary.swift
> +import UIKit
`UIKit`은 `Foundation` 프레임워크를 포함하고 있어요.

2022-12-31 06:21 UTC, ryan-son commented on DiaryTests/JSONDecodingTest.swift
> +        XCTAssertEqual("Array<DiaryResponseDTO>", String(describing: type(of: decodedData)))
타입을 String으로 변환해서 비교하기보다 `notNil`이 더 안정적으로 보이네요.

2023-01-02 10:40 UTC, Hashswim commented on Diary/Controller/DiaryListViewController.swift
> +        diaryList = items.reversed()
reversed()를 사용한 이유는 사용자가 일기를 추가 할 때 최신의 일기를 리스트의 위쪽으로 가도록 보여주기 위함이였습니다.

'let sortedByLatestItems: [Diary] = CoreDataManager.shared.readDiaryList().reversed()'
items를 할당할 때 reversed()를 동시에 실행하도록 수정했습니다.
또 해당 변수의 네이밍을 좀더 명확하도록 수정했습니다..!

2023-01-02 10:43 UTC, Hashswim commented on Diary/Controller/DiaryViewController.swift
>      }
처음 의도했던 것은 `coreData`에 해당 다이어리가 존재하는지 체크하기 위함이였습니다.
새로 다이어리를 생성할 때 true인지 체크하는 로직으로 변경하면서 `isNewDiary`로 좀더 의미가 명확하게 변수명을 수정했습니다..!

2023-01-02 10:45 UTC, Hashswim commented on Diary/Controller/DiaryViewController.swift
> +    private func makeMenu() -> UIMenu {
더보기 메뉴를 만드는 메서드입니다.
`makeEllipsisMenu()`로 명확하게 메서드 명을 수정했습니다..!

2023-01-02 10:46 UTC, Hashswim commented on Diary/Model/Diary.swift
> +import UIKit
앗...😅

2023-01-02 11:21 UTC, Gundy93 commented on Diary/Controller/DiaryViewController.swift
> +                          children: [shareAction, deleteAction, cancelAction])
UIMenu는 iOS 13 버전에 나온 기능으로 익숙하지 않은 사용자가 분명히 있을 것이라고 생각했습니다. 제가 지금껏 읽어온 HIG는 사용자에게 더 나은 경험을 제공하기 위한 가이드 라인이었고, 빈 공간을 탭해서 비활성하는 방식에 익숙하지 않은 사용자에겐 취소 버튼의 존재가 더 좋은 경험으로 다가갈 것이라 생각했습니다.

2023-01-02 11:22 UTC, Hashswim commented on Diary/CoreData/CoreDataManager.swift
> +    }
`readDiaryList`로 `coreData`에서 데이터를 읽어 오는 메서드의 의미를 명확하게 수정했습니다.
`generic`으로 어떤 데이터를 읽어 올지 판단하는 방법도 고민해 보았지만, 읽어 오는 데이터 마다 다른 `Entity`를 가져와야 해서 매번 다른 메서드를 사용하는 것이 더 수월하다고 생각했습니다..!

2023-01-02 12:24 UTC, Gundy93 commented on Diary/CoreData/CoreDataManager.swift
> +        return diaryList
`DiaryEntity` 타입을 `extension`하여 `Diary` 타입으로 변화시켜주는 `toDomain` 메서드를 만들어서 `map`을 통해 처리해주었습니다. 해당 메서드의 위치는 뷰컨트롤러로 이동하였습니다.

2023-01-02 12:27 UTC, Gundy93 commented on Diary/CoreData/CoreDataManager.swift
> +        } else {
`filter` -> `isEmpty`는 `contain(where:)`로, `filter` -> `[0]`은 `first(where:)`를 사용하는 것으로 수정하였습니다. `contain(where:)`의 경우, 로직이 변했기 때문에 if문 내부로직과 else문 내부로직을 서로 바꿔주었습니다.

2023-01-02 12:27 UTC, yuvinrho commented on Diary/CoreData/CoreDataManager.swift
> +            try context.save()
아래 코드와 같이 hasChanges 로직을 추가해주었습니다~

```swift
private func saveContext() {
    if !context.hasChanges {
        return
    }

    do {
        try context.save()
    } catch {
        print(error.localizedDescription)
    }
}
```

2023-01-02 12:30 UTC, Gundy93 commented on Diary/CoreData/CoreDataManager.swift
> +        }).isEmpty {
이번 리팩토링에서 DiaryEntity 타입의 toDomain 메서드를 만든데에는 인스턴스를 직접 비교할 수 있도록 하기위함도 있었는데요, 생각해보니 수정을 한 경우에는 `diaryEntity.toDomain() == diary`는 무조건 false가 될 것이라고 생각해 `UUID`의 비교를 하는 것으로 결정하였습니다.

2023-01-02 12:32 UTC, yuvinrho commented on DiaryTests/JSONDecodingTest.swift
> +        XCTAssertEqual("Array<DiaryResponseDTO>", String(describing: type(of: decodedData)))
감사합니다~
테스트 명을 `func test_JSON_sample_data를_decoding하면_nil이_아니어야_한다()`
`XCTAssertNotNil(decodedData)` 로 수정하였습니다!

2023-01-02 12:42 UTC, yuvinrho commented on Diary/CoreData/CoreDataManager.swift
> +    }
`NSManagedObjectContext`는 관리 객체에 대한 변경 사항을 커밋하고 추적하는 역할을 수행합니다. 
`viewContext`는 NSManagedObjectContext를 참조하고, `persistentContainer` 초기화의 일부로 자동으로 생성됩니다.

코어데이터 너무 어렵습니다.ㅠㅠ 공부를 더 해오겠습니다..

2023-01-04 02:11 UTC, ryan-son commented on Diary/CoreData/CoreDataManager.swift
> +    }
천천히 알아가시면 됩니다. 공식문서를 적극 활용해보세요~

- [viewContext - Apple Developer](https://developer.apple.com/documentation/coredata/nspersistentcontainer/1640622-viewcontext)

2023-01-04 02:12 UTC, ryan-son commented on Diary/CoreData/CoreDataManager.swift
> +        }).isEmpty {
[`Equatable`](https://developer.apple.com/documentation/swift/equatable) 프로토콜을 활용하는 방법도 있을까요?

2023-01-04 02:14 UTC, ryan-son commented on DiaryTests/JSONDecodingTest.swift
> +        XCTAssertEqual("Array<DiaryResponseDTO>", String(describing: type(of: decodedData)))
`nil이 아니어야 한다` 보다 `~ 타입으로 디코딩 된다` 같은 문구가 여러분이 테스트를 만든 의도를 더 잘 설명할 수 있을까요?

2023-01-04 02:15 UTC, merged

2023-01-05 03:31 UTC, Gundy93 commented on Diary/CoreData/CoreDataManager.swift
> +        }).isEmpty {
`Equatable`을 통해 `==`을 `return lhs.uuid == res.uuid`로 설정해줬었는데요! 결국 같은 로직이지 않나 하는 생각이 들었습니다...

2023-01-05 03:36 UTC, Gundy93 commented on DiaryTests/JSONDecodingTest.swift
> +        XCTAssertEqual("Array<DiaryResponseDTO>", String(describing: type(of: decodedData)))
라이언의 말씀대로 `~타입으로 디코딩 된다` 등의 문구가 적절할 것 같은데, `XCTAssert`에서 호출하는 메서드가 무엇인지와 테스트 이름의 상관관계도 있을 것이라고 생각해서 저희가 이렇게 리팩토링하게 된 것 같습니다...! 조금 더 알맞게 수정할 수 있도록 하겠습니다