일기장 [STEP 2] 써니쿠키, LJ
yagom-academy/ios-diary pull request #79
Opened 2022-12-29 12:03 UTC by sunny-maeng

@uuu1101
안녕하세요 태태! 🙇🏻‍♀️🙇🏻‍♀️
Step2 PR드립니다..! 

## 📝 STEP 진행 중 경험하고 배운 것
- CoreData 사용하기 
	 - [X] CoreData 모델을 생성했습니다.
	 - [X] CRUD 메서드를 구현했습니다.
	 - [X] 코어데이터를 다루는 모델을 싱글톤으로 구현했습니다.
- 상속으로 등록/수정 과정의 공통기능을 구현.
	 - [X] VC1와 공통기능을 갖는 VC2를 Class상속을 통해 구현했습니다.
- 컬렉션뷰 리스트에서 스와이프를 액션 구현
	 - [X] 테이블뷰에서 스와이프로 데이터를 공유/삭제합니다.
- Text View Delegate의 활용
	 - [X] TextView의 변화를 감지해 PlaceHolder를 설정합니다.

## ⚒️ 코드 구현내용 
### 1️⃣ CoreDataManager
- CRUD
    - `save(diaryPage:)` : Create
    - `fetchDiaryPages()` : Read
    - `update(diaryPage:)` : Update
    - `delete(diaryPage:)` : Delete
    - `deleteAllDiary()` : 계속되는 테스트로 쌓인 데이터를 초기화하는 메서드입니다.
- `deleteAllNoDataDiaries()` : 새로운 일기 생성 후 아무것도 입력하지 않았을 경우, 저장 후 fetch해올 때 삭제합니다.
- `searchDiary(id:)` : 수정 시 해당 일기만 찾아 데이터를 가져옵니다.
- `saveContext()` : 수정 또는 삭제 후 최종버전을 저장합니다. 중복코드를 줄이기위한 메서드입니다.

### 2️⃣ RegisterDiaryViewController
- 새로운 일기 생성화면을 담당합니다.
- 비어있는 `DiaryDetailView`를 보여줍니다.
- `UITextViewDelegate`
    - `textViewDidChange(textView:)` : 텍스트뷰에 변화가 감지되면 PlaceHolder를 제거합니다.
    - `textViewDidEndEditing(textView:)` : 텍스트뷰의 편집이 끝나면 PlaceHolder를 보여줍니다.
- `setupNotification()` : 입력상태에 따라 키보드를 보여주거나 숨깁니다.
    - `controlKeyboard(notification:)` : 텍스트뷰가 키보드로인해 가려지지 않도록 높이를 조정합니다.
    
### 3️⃣ DiaryDetailViewController
- 일기 상세화면인 `DiaryDetailView`를 담당합니다.
- 이미 작성한 일기가 입력되어있는 `DiaryDetailView`를 보여줍니다.
- `RegisterDiaryViewController`를 상속받은 후 초기화 시 뷰만 `DiaryDetailView`로 재정의한 컨트롤러입니다.
- `configureDiary()` : 일기제목과 내용을 구성합니다.
- `setupNavigationBar()` : 내비게이션바에 공유버튼을 구성합니다.
- `showActionSheet()` : 공유, 삭제옵션을 가진 액션시트를 뷰 하단에 띄웁니다.
    - `showActivityView()` : 공유 선택 시 `CustomActivityViewController`가 담당하는 뷰를 보여줍니다.
    - `showDeleteAlert()` : 삭제 선택 시 한번 더 확인받는 Alert를 띄웁니다.

### 4️⃣ CustomActivityViewController
- 공유 시 뷰 하단에서 올라오는 `ActivityView`를 담당하는 컨트롤러입니다.
- 공유할 채널(메일,문자,메모,카톡,기타SNS 등)에 포함시킬 것과 제외할 것을 정해줍니다.

---

## 💭 고민한 부분
### 1️⃣ 상속으로 공통기능 구현시, 주요 프로퍼티에 접근제어(private)를 설정해주기 위해 이니셜라이저에서 데이터를 갈아끼우는 로직 구현
- `RegisterDiaryViewController`(다이어리 등록화면 VC)를 상속받는 `DiaryDetailViewController`(다이어리 수정화면 VC)를 구현하면서 필수로 private을 설정해주어야 할 프로퍼티들에 접근제어를 설정할 수 없는 문제가 있었습니다. VC 두 개가 똑같이 `diaryPageView`, `diaryPage` 데이터를 갖고있는데 외부에서 접근할 수 없게 Private설정을 해주어야 했습니다.
- 상속받은 프로퍼티를 사용하지 않고 새로운 프로퍼티를 생성해서 사용하게되면, 이 프로퍼티들을 사용하는 메서드들을 모두 `override`해서 새로 생성한 프로퍼티를 사용하도록 모두 `override`후 재구현 해야했습니다.
- 결론적으론 접근제어설정과, 메서드 `override` 없이 상속받은 메서드를 사용할 수 있도록 이니셜라이저에서 데이터를 갈아끼우는 로직을 구현했습니다

### 2️⃣ 텍스트뷰 PlaceHolder
- `PlaceHolder`를 `TextView`에 입력한 채로 구현해보니 아무것도 입력하지 않았을 때 `PlaceHolder`의 텍스트를 입력값으로 인식하여 `PlaceHolder`로만 구성된 일기가 생성되는 문제가 있었습니다.
- `CustomLabel`타입으로 된 `titlePlaceHolder`와 `bodyPlaceHolder`를 만들고 `text`속성에 `PlaceHolder` 내용을 담았습니다.
- 텍스트뷰의 내용이 없을때만 `PlaceHolder`를 보여주는 `removePlaceHolder()` 메서드를 `DiaryDetailView`에 구현하였습니다.

### 3️⃣ 데이터가 없는 페이지는 자동 삭제되는 로직
- 처음엔 다이어리 등록 시 작성내용이 있는지 확인한 후 저장을 결정하는 로직을 구현하려했는데, 그러면 저장할때도 확인해야하고, 한글자를 써서 이미 저장이 된 데이터들에 대해서는 업데이트시 확인 후 삭제해야하고, 등록화면 뿐 아니라 이미 저장된 다이어리를 보는 화면에서도 내용을 모두 지우면 업데이트가 아닌 삭제를 해야하는데, 이곳저곳에서 계속 확인하느니 일단 저장 후 `fetch`해 올 때(저장된 리스트를 보여줄 때) 빈 값의 데이터를 자체적으로 삭제한 후 `fetch`하는 로직으로 구현했습니다.

---
## 🧐 조언을 얻고 싶은 부분
### 👉 CoreDataManager를 싱글톤 VS CoreData CRUD 메서드 Unit Test
CoreDataManager는 객체가 하나만 생성될 수 있도록 싱글톤으로 구현했는데, 싱글톤으로 구현하니 상속기능을 사용할 수 없어 Mock을 사용하기도 힘들고, coreData의 persistentContainer를 테스트용 컨테이너로 바꿔서 사용할 수가 없어서 CRUD 메서드들에 대한 unit Test를 할 수가 없었습니다...
많은 문서들을 찾아보고 참고해보려했는데 싱글톤생성의 단점이 Unit Test가 어려워진다는 점이라고해서 그럼 이제 선택차이겠구나 싶었습니다.
유닛테스트가 중요하다고 생각되면 싱글톤 작성을 풀고 유닛테스트를 작성하면되고, CoreDataManager의 유일성이 중요하다면 유닛테스트를 포기해야겠구나! 로 정리했는데
혹시 태태라면 CoreDataManager의 싱글톤 VS CRUE 유닛테스트 중 어떤걸 선택하셨을지 개인적인 의견이 궁금합니다..!

### 👉 CoreData의 Diary타입이 있는데 DiaryPage라는 DTO를 따로 두어야할 지 궁금합니다
코어데이터의 Attribute종류와 타입, DTO의 프로퍼티와 타입이 완벽히 동일하고, CoreData의 codagen도 Class Definition을 선택해 내부적으로 타입을 갖고있는 상황에서
DTO 사용해서 눈에 보이는 모델로 보인다는 장점 외에는 다른 장점을 찾지 못하겠는데 삭제하고 코어데이터의 Diary타입만 사용해도 될지 궁금합니다.. 🤔

### 👉 fetchResultController를 사용하고 싶은데요..
현재 로직은 리스트를 보여줄 때, 코어데이터의 모든 데이터들을 **모두** 가져온 후 저장한 후 보여주는 로직인데, 다이어리 데이터가 아주 많~아졌을 때는 리스트에서는 당장 20개만 보이면 될 것을 굳이 모두 갖고와 저장하고 있을 필요가 있을까 싶었습니다.. `nsfetchedresultscontroller`를 사용해서 가져올 데이터의 양을 batchSize로 정할 수 있고 delegate를 이용해 리스트에 보이는 셀의 갯수만큼씩 가져와 리스트로 보여줄 수 있다고해서 적용을 해보려했는데.... 결과적으론 실패했습니다...ㅎㅎ(다시 도전해볼 예정이고... 이걸 사용하면 DiaryDTO 모델을 사용하지 않고, 오히려 사용하려면 코드 구현이 더 까다로워져서 위의 질문이 생긴 이유이기도합니다) 그래서 혹시나 `nsfetchedresultscontroller` 사용 외에 다른 방식으로 코어데이터를 조금씩 가져오는 방법이 있는지 궁금합니다.

2022-12-31 09:11 UTC, uuu1101 requested changes
안녕하세요 @sunny-maeng ,@lj-7-77 🙌
올해 마지막 리뷰네요 :) 

## 🧐 조언을 얻고 싶은 부분
 > 👉 CoreDataManager를 싱글톤 VS CoreData CRUD 메서드 Unit Test
CoreDataManager는 객체가 하나만 생성될 수 있도록 싱글톤으로 구현했는데, 싱글톤으로 구현하니 상속기능을 사용할 수 없어 Mock을 사용하기도 힘들고, coreData의 persistentContainer를 테스트용 컨테이너로 바꿔서 사용할 수가 없어서 CRUD 메서드들에 대한 unit Test를 할 수가 없었습니다...
많은 문서들을 찾아보고 참고해보려했는데 싱글톤생성의 단점이 Unit Test가 어려워진다는 점이라고해서 그럼 이제 선택차이겠구나 싶었습니다.
유닛테스트가 중요하다고 생각되면 싱글톤 작성을 풀고 유닛테스트를 작성하면되고, CoreDataManager의 유일성이 중요하다면 유닛테스트를 포기해야겠구나! 로 정리했는데
혹시 태태라면 CoreDataManager의 싱글톤 VS CRUE 유닛테스트 중 어떤걸 선택하셨을지 개인적인 의견이 궁금합니다..!
- 싱글톤 VS CRUD Unit Test
캠퍼때 프로젝트를 하면서 많이 사용했는데, 일을 시작하고 나서는 거의 사용하지 않았던것 같아요. 현재는 Unit Test를 선택할 것 같습니다. 물론.. 테스트 코드 작성하는것은 정말... 😭

> 👉 CoreData의 Diary타입이 있는데 DiaryPage라는 DTO를 따로 두어야할 지 궁금합니다
코어데이터의 Attribute종류와 타입, DTO의 프로퍼티와 타입이 완벽히 동일하고, CoreData의 codagen도 Class Definition을 선택해 내부적으로 타입을 갖고있는 상황에서
DTO 사용해서 눈에 보이는 모델로 보인다는 장점 외에는 다른 장점을 찾지 못하겠는데 삭제하고 코어데이터의 Diary타입만 사용해도 될지 궁금합니다.. 🤔

 - CoreData의 Diary 타입으로 충분하다면 사용하는게 좋겠지만, 확장성이나 추후 추가 될 프로퍼티가 있다면, DTO로 작성해두는게 추후 확장성을 고려했을때 더 좋지 않을까요? 라는 생각을 해보았어요

> 👉 코어데이터 일정량 fetch하기
현재 로직은 리스트를 보여줄 때, 코어데이터의 모든 데이터들을 모두 가져온 후 저장한 후 보여주는 로직인데, 다이어리 데이터가 아주 많~아졌을 때는 리스트에서는 당장 20개만 보이면 될 것을 굳이 모두 갖고와 저장하고 있을 필요가 있을까 싶었습니다.. nsfetchedresultscontroller를 사용해서 가져올 데이터의 양을 batchSize로 정할 수 있고 delegate를 이용해 리스트에 보이는 셀의 갯수만큼씩 가져와 리스트로 보여줄 수 있다고해서 적용을 해보려했는데.... 결과적으론 실패했습니다...ㅎㅎ(다시 도전해볼 예정이고... 이걸 사용하면 DiaryDTO 모델을 사용하지 않고, 오히려 사용하려면 코드 구현이 더 까다로워져서 위의 질문이 생긴 이유이기도합니다) 그래서 혹시나 nsfetchedresultscontroller 사용 외에 다른 방식으로 코어데이터를 조금씩 가져오는 방법이 있는지 궁금합니다.
- 스크롤을 할때 일정량을 가져오게 할 것 같고, CoreData의 NSFetchRequest 의 [fetchBatchSize](https://developer.apple.com/documentation/coredata/nsfetchrequest/1506558-fetchbatchsize)를 참고해보면 좋을 것 같다는 생각입니다.

한해 마무리 잘하시고 새해 복 많이 받으세요 ! 🙇🏻‍♂️

2022-12-31 09:11 UTC, uuu1101 commented on Diary/Model/CoreDataManager.swift
> +        let container = NSPersistentContainer(name: "Diary")
String Raw값을 사용하는 것은 실수를 발생시킬 수 있으니,
한곳에서 관리하거나, 명시적으로 작성되면 더 좋을 것 같아요 :)

2022-12-31 09:11 UTC, uuu1101 commented on Diary/Model/DiaryPage.swift
> +struct DiaryPage: Hashable {
DiaryInfo 의 네이밍은 어떠신가요? 
물론 지금의 네이밍도 충분히 좋다고 생각합니다.
앱을 먼저 실행해보거나 요구사항들을 알지 못한다면 정말 Page(?)라고 느껴질것 같아요.
해당 부분 피드백이 조금 이해하는데 명확하게 제가 작성을 하지 못한것 같은데, 혹시나 이해가 안되신다면 DM주세요 :)

2022-12-31 09:11 UTC, uuu1101 commented on Diary/View/CustomUI.swift
👍

2022-12-31 09:11 UTC, uuu1101 commented on Diary/ViewController/DiaryListViewController.swift
> +        diary = CoreDataManager.shared.fetchDiaryPages()
모델 네이밍이 DiaryPage 이다보니, fetchDiaryPages()라는 메서드명이 나왔을텐데요.
뭔가 Diary를 Fetch해주는 느낌보다 저는 다음 페이지나 여러 페이지들을 Fetch 해주는 느낌을 받아서, 모델의 네이밍을 수정해보는 의견을 드렸어요.

2023-01-02 11:57 UTC, lj-7-77 commented on Diary/Model/CoreDataManager.swift
> +        let container = NSPersistentContainer(name: "Diary")
네! 파일 별 네임스페이스 정리 하였습니다 :)

2023-01-02 12:14 UTC, lj-7-77 commented on Diary/Model/DiaryPage.swift
> +struct DiaryPage: Hashable {
말씀주신대로 Page를 다이어리를 모아놓은 페이지로 해석될 가능성도 있어보입니다! DiaryInfo로 수정하고, 그에 따른 변수명도 함께 수정하였습니다 😁
[175f21c](https://github.com/yagom-academy/ios-diary/pull/79/commits/175f21cd056945f96d2eab9a645adbe45d07ad01)

2023-01-02 12:16 UTC, sunny-maeng commented on Diary/ViewController/DiaryListViewController.swift
> +        diary = CoreDataManager.shared.fetchDiaryPages()
모델명을 DiaryPage >> DiaryInfo 수정하면서 같이 수정했습니다 Info라는 네이밍이 훨씬 깔끔하게 느껴지네요 감사합니다 👍🏻
커밋: [175f21c](https://github.com/yagom-academy/ios-diary/pull/79/commits/175f21cd056945f96d2eab9a645adbe45d07ad01)

2023-01-02 13:53 UTC, uuu1101 commented
Step2 고생하셨어요 :) 
새해 복 많이 받으세요 !! 😊

2023-01-02 13:53 UTC, merged