다이어리 [STEP 2] 썸캣, 솜
yagom-academy/ios-diary pull request #80
Opened 2022-12-29 13:07 UTC by dev-summer

안녕하세요, 올라프(@1consumption)! 
다이어리 Step 2 구현이 완료되어 PR 보냅니다.

## 고민했던 점

### 1. CoreData의 Entity와 데이터 모델이 별개로 존재

CoreData의 Entity(`Diary`)와 별개로 데이터 모델(`DiaryModel`)을 만든 이유는 앱에 추가적인 기능을 구현할 때 둘을 분리해서 관리할 필요가 생길 수 있다고 판단해서입니다. 예를 들어 `DiaryModel`의 프로퍼티가 갖는 값을 enum을 사용해 제한하고 싶을 경우 등이 있습니다.

**`CoreData의 Entity`의 변경 사항이 데이터 모델에 반영이 되지 않은 이슈**
```swift
func fetchAllDiaryModels() -> [DiaryModel] {
    var diaryModels: [DiaryModel] = []
    let fetchedResults = fetchAllDiaries()
        
    for result in fetchedResults {
        let diary = DiaryModel(id: result.objectID,
                               title: result.title ?? Namespace.emptyString,
                               body: result.body ?? Namespace.emptyString,
                               createdAt: result.createdAt ?? Date())
        diaryModels.append(diary)
    }
        
    return diaryModels
}
```
그래서 위와 같은 코드처럼 Entity의 정보를 데이터 모델에 할당하는 메서드를 추가적으로 구현하게 되었습니다. 

### 2. 일기 상세 화면에서 일기를 삭제하는 로직 구현

일기 상세 화면에서 일기를 삭제 시 일기 리스트 화면으로 돌아가도록 구현하고자 했습니다.
하지만 CoreData에 삭제 요청을 보낸 이후 일기 상세 화면 뷰컨을 pop할 때, CoreData에 저장을 요청하는 `save()` 메서드가 호출되어 뷰컨의 `titleTextView`와 `bodyTextView`의 텍스트를 `title`, `body`로 갖는 일기를 새로 생성하여 저장하는 side effect가 발생했습니다.
이를 해결하기 위해 CoreData에 삭제 요청을 보내기 전에 해당 뷰컨의 `titleTextView`와 `bodyTextView`의 텍스트를 비워주고, `title`과 `body`가 모두 비어 있는 일기의 생성을 막는 로직을 추가했습니다.

### 3. 뷰(와 뷰 컨트롤러)에서 로직 분리하기

코어데이터의 `CRUD`를 관리하는 객체(`CoreDataManager`)와 뷰가 직접적으로 소통하게 되면서 뷰에 로직이 많아지게 되었습니다. 올라프의 조언을 토대로, 저희도 뷰가 로직을 가지고 있지 않아야 하며, 화면에 띄우는 용도로만 생각해야 한다는 결론을 내리게 되었습니다.
두 객체 사이를 관리하는 `Manager` 객체를 만들어 뷰에 있던 로직을 분리하였습니다.

---

## 조언을 얻고 싶은 부분

### 1. `fetchID(of: )`가 실패할 경우 새로운 일기를 생성하는 문제

CoreData에서 일기를 가져오거나 CoreData에 일기를 업데이트 할 때 `objectID`를 사용하고 있는데, 이 `objectID`는 CoreData에 데이터가 insert 된 후에 생성됩니다. 따라서 생성된 `objectID`를 가져오는 `fetchID(of: )` 함수를 별도로 구현해서 CoreData에 저장된 Entity로부터 `objectID`를 가져와 데이터 모델에 할당하도록 했습니다. 

```swift
final class DiaryItemManager {
    var diaryItem: DiaryModel?
    
    ...
    
    func saveDiaryWith(title: String, body: String) {
        updateDiaryTo(title: title, body: body)

        if CoreDataManager.shared.fetchDiary(with: diaryItem?.id) == nil {
            generateDiary()

            if diaryItem?.title == Namespace.empty,
               diaryItem?.body == Namespace.empty { return }

            CoreDataManager.shared.insertDiary(diaryItem)
            let id = CoreDataManager.shared.fetchID(of: diaryItem)
            diaryItem?.id = id
        } else {
            CoreDataManager.shared.updateDiary(diaryItem)
        }
    }
}
```

이 과정에서 `fetchID`가 실패할 경우 `diaryItem`에 `nil`을 할당하게 됩니다. 그 상태에서 뒤로가기를 누르면 리스트 화면으로 갈 때 `saveDiaryWith`가 호출되고, `diaryItem`의 `id`가 `nil`이기 때문에 로직에서 새로운 일기로 판단해 새로운 일기를 `insert`하게 되는 문제가 있습니다.
`saveDiaryWith`의 로직을 변경해서 해결해보려고 했지만 결국 해결하지 못해 조언을 구해봅니다 😥

### 2. `CoreDataManager`의 `error`를 어떤 방식으로 뷰에 전달하면 좋을까요?

현재 저희는 `AlertManager`를 통해 `CoreDataManager`의 에러를 받아 `NotificationCenter`를 통해 뷰에게 `post`하는 방식으로 구현했습니다. `NotificationCenter`로 `observing`하는 것보다 더 효율적인 방법이 있을 거 같은데, 지금으로서는 떠오르지 않아 이 부분에 대해 여쭤보고 싶습니다.

### 3. 커스텀 뷰의 활용

`DiaryItemVC`에는 `mainStackView`, `titleStackView`, `bodyStackView` 세 가지의 뷰가 있습니다. 이 뷰들을 포함하는 하나의 커스텀 뷰를 별도로 생성하고, 그 커스텀 뷰를 `DiaryItemVC`에서 사용하는 방법도 있다고 생각합니다.
저희가 그렇게 하지 않은 이유는 해당 커스텀뷰가 하는 역할이 뷰를 담는 역할 외에 없으며, 추가적인 기능을 하지 않을 것이라고 생각했기 때문입니다. 올라프의 생각은 어떤지 궁금합니다.

2023-01-01 10:33 UTC, 1Consumption requested changes
고생하셨습니다. @dev-summer @jsa0224 

커밋이 정말 잘 나눠져 있네요. 👍 

코드 변경사항이 정말 많습니다. 고생하셨어요.
그만큼 코멘트도 많네요. 잘 읽어보고 반영해주세요.

----------------------------------------------------------------------
### 1. `fetchID(of: )`가 실패할 경우 새로운 일기를 생성하는 문제

CoreData에서 일기를 가져오거나 CoreData에 일기를 업데이트 할 때 `objectID`를 사용하고 있는데, 이 `objectID`는 CoreData에 데이터가 insert 된 후에 생성됩니다. 따라서 생성된 `objectID`를 가져오는 `fetchID(of: )` 함수를 별도로 구현해서 CoreData에 저장된 Entity로부터 `objectID`를 가져와 데이터 모델에 할당하도록 했습니다. 

```swift
final class DiaryItemManager {
    var diaryItem: DiaryModel?
    
    ...
    
    func saveDiaryWith(title: String, body: String) {
        if CoreDataManager.shared.fetchDiary(with: diaryItem?.id) == nil {
            generateDiary()
            updateDiaryTo(title: title, body: body)
            
            if !validate(diaryItem: diaryItem) { return }
            
            CoreDataManager.shared.insertDiary(diaryItem)
            let id = CoreDataManager.shared.fetchID(of: diaryItem)
            diaryItem?.id = id
        } else {
            updateDiaryTo(title: title, body: body)
            CoreDataManager.shared.updateDiary(diaryItem)
        }
    }
}
```

이 과정에서 `fetchID`가 실패할 경우 `diaryItem`에 `nil`을 할당하게 됩니다. 그 상태에서 뒤로가기를 누르면 리스트 화면으로 갈 때 `saveDiaryWith`가 호출되고, `diaryItem`의 `id`가 `nil`이기 때문에 로직에서 새로운 일기로 판단해 새로운 일기를 `insert`하게 되는 문제가 있습니다.
`saveDiaryWith`의 로직을 변경해서 해결해보려고 했지만 결국 해결하지 못해 조언을 구해봅니다 😥

> `fetchID`가 실패할 경우 만 검사하지말고, 변경사항이 없으면 저장하지 않는다 라는 로직을 추가하면 어떨까요?

### 2. `CoreDataManager`의 `error`를 어떤 방식으로 뷰에 전달하면 좋을까요?

현재 저희는 `AlertManager`를 통해 `CoreDataManager`의 에러를 받아 `NotificationCenter`를 통해 뷰에게 `post`하는 방식으로 구현했습니다. `NotificationCenter`로 `observing`하는 것보다 더 효율적인 방법이 있을 거 같은데, 지금으로서는 떠오르지 않아 이 부분에 대해 여쭤보고 싶습니다.

> 코멘트에 남겼습니다.

### 3. 커스텀 뷰의 활용

`DiaryItemVC`에는 `mainStackView`, `titleStackView`, `bodyStackView` 세 가지의 뷰가 있습니다. 이 뷰들을 포함하는 하나의 커스텀 뷰를 별도로 생성하고, 그 커스텀 뷰를 `DiaryItemVC`에서 사용하는 방법도 있다고 생각합니다.
저희가 그렇게 하지 않은 이유는 해당 커스텀뷰가 하는 역할이 뷰를 담는 역할 외에 없으며, 추가적인 기능을 하지 않을 것이라고 생각했기 때문입니다. 올라프의 생각은 어떤지 궁금합니다.

> 음.. 어떤걸 물어보고싶은지 잘 모르겠어요. 저는 지금도 괜찮아보입니다.

2023-01-01 10:33 UTC, 1Consumption commented on Diary.xcodeproj/xcshareddata/xcschemes/Diary.xcscheme
> +</Scheme>
이 변경사항은 뭘 의미하나요?

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Common/AlertManager.swift
> +}
정확히 어떤 역할을 하는지 모르겠습니다. 이 객체가 필요한 이유는 무엇인가요? 그리고 싱글톤인 이유도 궁금합니다.

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Common/DiaryItemManager.swift
> +    static let shared = DiaryItemManager()
이 객체는 왜 싱글톤인가요?

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Common/DiaryItemManager.swift
> +        if CoreDataManager.shared.fetchDiary(with: diaryItem?.id) == nil {
반환값이 nil이냐 아니냐를 가지고 판단하는게 이상합니다. 실제로 이 데이터를 사용하지 않는데 왜 `Diary`를 반환하나요? 이런 경우는  Bool이 더 적합해보입니다. 메소드 이름도 `존재하냐`가 포함되면 좋겠어요.

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Common/DiaryItemManager.swift
> +    }
근데 이 객체에서 왜 `diaryItem`을 들고 있나요? 사실 계속 들고있지 않아도 될거같은데요.

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Common/DiaryItemManager.swift
> +            updateDiaryTo(title: title, body: body)
update가 무조건 실행되는 코드라면 if문 밖으로 보내는게 어떨까요?

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Common/DiaryItemManager.swift
> +            if !validate(diaryItem: diaryItem) { return }
`diaryItem`이 valid 하냐 아니냐에 따라 위에서 실행되는 작업(15-17라인)과 아래(21-23라인)에서 실행되는 작업의 차이는 뭔가요? 정책이 조금 애매한듯하네요.
그리고 이경우는 `func isValid(_ diaryItem: DiaryItem?) -> Bool`라는 메소드 이름이 더 적합해보여요.

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Common/DiaryItemManager.swift
> +            diaryItem?.id = id
제가 봤을 때 `id`는 `diaryItem`에 꼭 필요한 변수 같고, 절대 변하지 않을 변수 같아요. 그렇다면 이 경우에는 해당 변수를 생성자로 받고 let으로 선언하는게 남이 코드를 읽을 때 더 도움이 되지 않을까요?

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Common/DiaryItemManager.swift
> +    func saveDiaryWith(title: String, body: String) {
```suggestion
    func saveDiary(with title: String, body: String) {
```

with을 메소드이름에 포함하지말고 매개변수 레이블로 빼는게 조금 더 swift 스럽다고 생각합니다.

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Common/DiaryItemManager.swift
> +    }
음.. 이건 개인의 취향 차이 일수도 있는데, 저는 잘 안읽히네요.
아래와 같이 바꾸면 어떨까요?
```suggestion
    private func isValid(_ diaryItem: DiaryModel?) -> Bool {
        return isTitleValid(diaryItem?.title) && isBodyValid(diaryItem?.body)
    }
    
    private func isTitleValid(_ title: String?) -> Bool {
        return title != Placeholder.title && title != Namespace.empty
    }
    
    private func isBodyValid(_ body: String?) -> Bool {
        return body != Placeholder.body && body != Namespace.empty
    }
```

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Common/DiaryItemManager.swift
> +    }
메소드 이름엡 붙는 create와 generate의 차이는 뭔가요? 둘다 뭔가를 `만든다` 라는 느낌인데... 어디는 반환값이 있고 어디는 없네요.

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Common/Namespace.swift
> +}
전역적으로 사용될 값이 아니라 지역적으로 사용될 값이라면 해당 객체에 속하는게 좋아보입니다.

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +    private var hasTitle: Bool = false
이거도 어떻게보면 로직이죠. `DiaryItemViewController`의 로직을 담당할 객체가 필요해보입니다.

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +    private var diaryItemManager = DiaryItemManager.shared
얘는 왜 var인가요?

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +    private lazy var activityViewController = UIActivityViewController(diaryItemManager: diaryItemManager)
`diaryItemManager`에서 관리하는 `diaryItem`에 대한 정보가 필요해서 여기에 넘긴가요? 이러면 코드 추적하기가 어려워요. 저라면 알러트가 필요할 때만 `diaryItem`을 알러트 띄우는 객체에 보내겠어요.

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +        configureMainStackView()
여기를 `view를 configure한다` 라는 메소드 이름으로 한번 더 추상화 하면 좋겠어요.

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +    }
view를 가지고 분기를 치는건 좋지 못하다고 생각해요. 차라리 `titleTextView`, `bodyTextView` 각각 다루는 메소드 두개를 만들면 좋겠습니다. 더 나아가 내부 로직을 다른 객체로 빼면 더 좋겠지만 이 부분은 참고만 해주세요.

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +        title = (title == nil ? DateFormatterManager().formatDate(date) : title)
```suggestion
        title = title ?? DateFormatterManager().formatDate(date)
```
로 바꾸는게 더 가독성이 좋아보이네요.

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +                                               object: nil)
저는 꼭 필요한 경우가 아니면 NotificationCenter 사용을 지양하는 편입니다. 코드가 중간에 끊겨서 따라가기 어려워요. 
그런데 여기는 coreData관련 에러를 관찰하고 있네요. `DiaryItemManager`를 이 뷰컨이 알고 있으니 `DiaryItemManager`에서 에러를 던지게하고, 이 뷰컨에서 해당 에러를 처리(알러트 띄우기)하는건 어떨까요?

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +        if textView.textColor == .systemGray3 {
`textView.textColor == .systemGray3` 이 경우가 어떤 상황인가요? 상수로 이름을 지어주면 좋겠습니다.

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +        }
```suggestion
        isOversized = titleTextViewHeight > LayoutConstant.titleTextViewMaxHeight
```
컨디션에 따라 Bool 변수의 값이 바뀐다면 컨디션 자체를 넣어서 이렇게 바꿀수도 있어요.

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +        }
여기에 들어가는 로직도 다른 객체로 빠지고, 뷰는 반영만 하면 좋겠습니다. 너무 어렵다면 참고만 해주시거나, 다시 질문을 해주시면 좋겠습니다.

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Controller/DiaryListViewController.swift
> +
불필요한 변경사항 같습니다.

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Model/CoreDataManager.swift
> +            if let error = error as NSError? {
왜 NSError로 형변환을 해야하나요?

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Model/CoreDataManager.swift
> +    }
여기서 catch를 하지말고 그냥 에러를 던지는게 어떨까요? 사용하는 곳에서 에러 핸들링을 하는거죠.
내부에서 해당 메소드를 사용하는 곳에서도 에러를 던지기만 하면 좋겠습니다.

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Model/CoreDataManager.swift
> +        let context = persistentContainer.viewContext
`viewContext` 라는 프로퍼티가 있으니 해당 프로퍼티를 사용하는게 좋아보입니다.

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Model/CoreDataManager.swift
> +        return object
```suggestion
        return id?.flatMap(viewContext.object(with:)) as? Diary
```
이렇게 바꿀수도 있겠네요.

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Model/CoreDataManager.swift
> +final class CoreDataManager {
여기에 포함된 `Diary` 관련 정보는 `DiaryItemManager`로 옮기는게 더 역할에 맞아보입니다.

2023-01-01 10:33 UTC, 1Consumption commented on Diary/Resource/Model/CoreDataManager.swift
> +        }
```suggestion
    return result?.first?.objectID
```
굳이 옵셔널 체크를 할 필요는 없어보여요. 꼭 옵셔널 바인딩한 값이 필요한게 아니라면 저는 안하는 편입니다.

2023-01-03 01:55 UTC, jsa0224 commented on Diary/Resource/Common/DiaryItemManager.swift
> +        if CoreDataManager.shared.fetchDiary(with: diaryItem?.id) == nil {
저희가 이 부분을 놓치고 있었네요! `Bool` 타입을 반환하는 `isExistingDiaryID` 메서드로 수정하였습니다! [34d01c6](https://github.com/yagom-academy/ios-diary/pull/80/commits/34d01c635ce7d1710566a35b3af32aa07a17fefc)

2023-01-03 02:41 UTC, dev-summer commented on Diary/Resource/Common/DiaryItemManager.swift
> +    func saveDiaryWith(title: String, body: String) {
![image](https://user-images.githubusercontent.com/98260324/210293637-c5030568-eb62-4d3d-a8e3-df15f03532c4.png)

`body`와 `title`이 하나의 일기를 이루는 요소이기 때문에 represent parts of a single abstraction인 경우에 해당된다고 생각해서 `with`를 메서드 이름으로 빼주었습니다.

2023-01-03 07:48 UTC, dev-summer commented on Diary/Resource/Common/DiaryItemManager.swift
> +        if CoreDataManager.shared.fetchDiary(with: diaryItem?.id) == nil {
`diaryItem`을 가지고 있는 객체를 `diaryItemVC`로 변경하면서 저장/업데이트에 관한 로직이 전반적으로 변경되었습니다.
변경하게 된 이유는 코멘트에 기재하겠습니다.

2023-01-03 07:48 UTC, dev-summer commented on Diary/Resource/Common/DiaryItemManager.swift
> +    }
`diaryItem`을 가지고 있는 객체를 `diaryItemVC`로 변경하면서 저장/업데이트에 관한 로직이 전반적으로 변경되었습니다.
변경하게 된 이유는 코멘트에 기재하겠습니다.

2023-01-03 07:48 UTC, dev-summer commented on Diary/Resource/Common/DiaryItemManager.swift
> +            updateDiaryTo(title: title, body: body)
`diaryItem`을 가지고 있는 객체를 `diaryItemVC`로 변경하면서 저장/업데이트에 관한 로직이 전반적으로 변경되었습니다.
변경하게 된 이유는 코멘트에 기재하겠습니다.

2023-01-03 07:48 UTC, dev-summer commented on Diary/Resource/Common/DiaryItemManager.swift
> +            if !validate(diaryItem: diaryItem) { return }
`diaryItem`을 가지고 있는 객체를 `diaryItemVC`로 변경하면서 저장/업데이트에 관한 로직이 전반적으로 변경되었습니다.
변경하게 된 이유는 코멘트에 기재하겠습니다.

validity를 체크하는 메서드 이름은 추천해주신대로 변경했습니다! 감사합니다.

2023-01-03 07:50 UTC, dev-summer commented on Diary/Resource/Common/DiaryItemManager.swift
> +            diaryItem?.id = id
새 일기 추가 버튼을 통해 `diaryItemVC`를 init할 때, entity를 먼저 생성한 후 entity의 ID값을 이용해서 `diaryItem`을 init하도록 변경했습니다.

2023-01-03 08:05 UTC, dev-summer commented
처음에 `diaryItem`을 `DiaryItemManager` 객체에 두었지만, 올라프의 리뷰를 보고 수정하게 되었습니다. 
어디에 구현하는 것이 적절할까? 에 대한 고민 후, `diaryItemVC`에 두기로 결정하였습니다. 하나의 `DiaryItemVC`가 init되는 상황은 `1. 새로운 일기를 생성`하거나 `2. 기존 일기를 불러오는 상황`이기 때문에 **항상 하나의 일기를 보여주고 있습니다**. 따라서 `DiaryItemVC를` init할 때 `diaryItem`을 주입받도록 하고, 관련된 추가/변경/삭제 기능을 `DiaryItemManager`에 구현하는 것이 적절하다고 판단하였습니다.

2023-01-03 08:32 UTC, dev-summer commented on Diary/Resource/Common/DiaryItemManager.swift
> +    }
create는 보통 하나의 결과물이 있을 때 결과물에 초점을 맞추어 사용하고, generate는 생성해내는 결과물이 셀 수 없을 때(countable 하지 않을 때) 사용한다고 합니다([출처](https://www.ukentry.com/produce-create-generate-difference.html)).
프로젝트를 전반적으로 리팩토링 하면서 메서드 이름을 `create`로 통일하였고, 모두 반환값을 갖도록 했습니다.

2023-01-03 08:43 UTC, jsa0224 commented on Diary/Resource/Common/Namespace.swift
> +}
[ac69cdd](https://github.com/yagom-academy/ios-diary/pull/80/commits/ac69cdd4517df2fabe88f95b08049c3d235b2a4e)

넵 해당 부분 수정했습니다!

2023-01-03 08:45 UTC, jsa0224 commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +    private var diaryItemManager = DiaryItemManager.shared
원래 let으로 선언하는 것이 맞는데, 실수로 var로 선언한 거 같습니다. 
그리고 해당 객체가 싱글톤이기 때문에, VC에서 변수로 들고 있을 필요가 없어 해당 부분 삭제했습니다!

2023-01-03 08:47 UTC, jsa0224 commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +    private lazy var activityViewController = UIActivityViewController(diaryItemManager: diaryItemManager)
이 부분도 `diaryItem`을 `VC`가 직접 들고 있도록 변경하여 해당 부분 삭제했습니다.

2023-01-03 08:55 UTC, jsa0224 commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +        configureMainStackView()
[f9a52f9](https://github.com/yagom-academy/ios-diary/pull/80/commits/f9a52f91e0b79234511cf4d62ae17978597adf1e)
`configureUI`라는 하나의 메서드로 정리했습니다!

2023-01-03 09:01 UTC, jsa0224 commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +        }
필요 없는 기능이라 삭제했습니다.

2023-01-03 11:29 UTC, jsa0224 commented on Diary/Resource/Model/CoreDataManager.swift
> +final class CoreDataManager {
[04216a3](https://github.com/yagom-academy/ios-diary/pull/80/commits/04216a30dbeb0608861c8e10607a86a3aac8dfe0)
`Diary` 관련 정보를 `fetch`하는 메서드를 `DiaryItemManager`로 위치 수정했습니다!

2023-01-03 11:31 UTC, jsa0224 commented on Diary/Resource/Model/CoreDataManager.swift
> +        let context = persistentContainer.viewContext
[86e9d18](https://github.com/yagom-academy/ios-diary/pull/80/commits/86e9d18eca38ccf70ce513e6e6db80902355977c)
해당 프로퍼티도 `persistentContainer.viewContext`를 리턴하고 있어, 삭제하고 `persistentContainer.viewContext` 자체로 구현했습니다.

2023-01-03 11:33 UTC, jsa0224 commented on Diary/Resource/Model/CoreDataManager.swift
> +            if let error = error as NSError? {
죄송합니다. 사죄합니다.. 
저희가 코드를 참고할 때 이 부분을 신경 쓰지 못 했습니다. 다시 한 번 사죄드립니다.🙇‍♀️

2023-01-04 07:12 UTC, jsa0224 commented on Diary.xcodeproj/xcshareddata/xcschemes/Diary.xcscheme
> +</Scheme>
스키마를 변경하면서 생긴 거 같습니다. 앞으로는 커밋 시에 변경 사항을 꼼꼼히 확인해보겠습니다!

2023-01-04 07:19 UTC, jsa0224 commented on Diary/Resource/Common/AlertManager.swift
> +}
[d2d377d](https://github.com/yagom-academy/ios-diary/pull/80/commits/d2d377d03629dc878f05ba3436903f2183116b27)
이전에는 역할을 정확히 정의하지 못 해 불분명했지만, `alert`을 생성하고 반환하는 기능을 가지고 있는 `AlertManager`로 재구현했습니다.

2023-01-04 07:22 UTC, dev-summer commented on Diary/Resource/Common/DiaryItemManager.swift
> +    static let shared = DiaryItemManager()
처음에는 itemVC와 listVC에서 공통적으로 사용하는 메서드를 담고 있어 싱글톤으로 선언한 후 재활용을 하기 위해 싱글톤으로 선언했습니다. 하지만 앞의 이유가 싱글톤 패턴을 사용하는 목적과는 어긋난다는 것을 인지하고 싱글톤이 아닌 것으로 변경했습니다.
싱글톤 패턴을 사용하는 것은 싱글톤 객체의 **상태**를 전역적으로 공유하기 위함인데,
- ItemManager가 diaryItem이라는 상태를 가지고 있을 경우, 각 일기마다 diaryItem이 변경되어야 하기 때문에 상태를 공유하는 것이 적절하지 못하며,
- ItemManager가 diaryItem이라는 상태를 가지고 있지 않을 경우, 공유하는 상태가 없기 때문에 싱글톤 패턴을 채택할 이유가 없어집니다.
위와 같은 이유로 싱글톤 객체가 아닌 일반 객체로 변경해주었습니다.

2023-01-04 07:24 UTC, jsa0224 commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +    private var hasTitle: Bool = false
[2990723](https://github.com/yagom-academy/ios-diary/pull/80/commits/2990723359e6fa6c8a232cfb2aa605a55a50239a) | [07ac66e](https://github.com/yagom-academy/ios-diary/pull/80/commits/07ac66edcdf7daf60b672a95ac870a73d1638a69)

위와 같이 `DiaryItemManager` 객체에 해당 로직을 이동시켰습니다.

2023-01-04 07:28 UTC, jsa0224 commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +                                               object: nil)
[86e9d18](https://github.com/yagom-academy/ios-diary/pull/80/commits/86e9d18eca38ccf70ce513e6e6db80902355977c)
위와 같이 NotificationCenter을 제거하고 VC까지 throw하여 alert을 띄우게끔 수정했습니다.

2023-01-04 07:29 UTC, dev-summer commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +        if textView.textColor == .systemGray3 {
[bc85249](https://github.com/yagom-academy/ios-diary/pull/80/commits/bc8524972799c0fc08c7636a6479c525c4f36853)

"Placeholder인가?"라는 의미의 `isPlaceholder`라는 이름으로 상수화 해주었습니다.
더 나은 네이밍이 생각나면 추가로 수정해보겠습니다.

2023-01-04 07:35 UTC, dev-summer commented on Diary/Resource/Model/CoreDataManager.swift
> +    }
[86e9d18](https://github.com/yagom-academy/ios-diary/pull/80/commits/86e9d18eca38ccf70ce513e6e6db80902355977c)

CoreDataManager에서 발생한 에러를 DiaryItemManager로 던지고, 다시 뷰컨으로 던져서 뷰컨에서 알럿으로 보여주도록 변경했습니다.

2023-01-04 07:49 UTC, jsa0224 commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +        }
[2990723](https://github.com/yagom-academy/ios-diary/pull/80/commits/2990723359e6fa6c8a232cfb2aa605a55a50239a) | [07ac66e](https://github.com/yagom-academy/ios-diary/pull/80/commits/07ac66edcdf7daf60b672a95ac870a73d1638a69) 

텍스트뷰 자체는 다른 객체에서 뷰를 처리하는 것이 적절하지 않다고 판단되어, 일부 로직은 `bool` 타입으로 반환하여, `VC` 자체에 로직을 넣는 방향으로 진행하였습니다.

2023-01-04 08:03 UTC, jsa0224 commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +    }
[2990723](https://github.com/yagom-academy/ios-diary/pull/80/commits/2990723359e6fa6c8a232cfb2aa605a55a50239a) | [07ac66e](https://github.com/yagom-academy/ios-diary/pull/80/commits/07ac66edcdf7daf60b672a95ac870a73d1638a69) | [99a5175](https://github.com/yagom-academy/ios-diary/pull/80/commits/99a5175afbdeff69b240da6df9505477cca35303)

넵, 올라프 말씀대로 뷰로 분기처리를 하는 것이 적절하지 않다고 생각하였고, 로직을 다른 객체로 이동시키면서 뷰를 분기처리하지 않는 방향으로 수정했습니다. 

---
아래 코멘트와 통일성이 맞지 않는 부분이 있어 추가로 남깁니다!
이 부분은 textView의 상태(Bool값)에 따라 textView를 조작하는 부분이기 때문에, textView를 DiaryItemManager로 넘기지 않으면 뷰컨에 Bool값을 이용한 로직을 작성해야 해서 textView를 DiaryItemManager에 전달해 처리하게 되었습니다. 

`view`를 모델에 넘기는 것도 적절하지 않다고 생각되고, `view`에서 로직을 가지고 있는 것도 적절하지 않다고 생각되는데 어떻게 하면 좋을까요?

2023-01-05 12:08 UTC, 1Consumption commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +    let diaryItemManager: DiaryItemManager?
internal, optional 이어야하나요?

2023-01-05 12:08 UTC, 1Consumption commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +        diaryItemManager?.removePlaceholder(textView: textView)
`isPlaceholder` 만 로직으로 빼고 view를 건드리는건 view에서 하는게 역할에 맞아보여요.

2023-01-05 12:08 UTC, 1Consumption commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +        let tappedEnter = diaryItemManager.enter(from: titleTextView.text)
흠.. tuple을 반환하는거랑 메소드를 두개 만드는거랑 어떤게 더 나을까요?

2023-01-05 12:08 UTC, 1Consumption commented on Diary/Resource/Model/CoreDataManager.swift
> +    var persistentContainer: NSPersistentContainer { get }
외부에서는 이 변수가 아니라 CRUD하는 작업을 알아야하지 않을까요?

2023-01-05 12:08 UTC, 1Consumption commented on Diary/Resource/Model/CoreDataManager.swift
> +            }
이 guard문이 의미하는건 뭘까요? error가 있던 없던 별 다른 동작을 하지 않네요.

2023-01-05 14:13 UTC, dev-summer commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +    let diaryItemManager: DiaryItemManager?
[f25ab65](https://github.com/yagom-academy/ios-diary/pull/80/commits/f25ab6508866901d615e9267156ce3bfc17b8aff)

처음에는 `private let diaryItemManager = DiaryItemManager()`와 같이 뷰컨트롤러가 초기화 될 때 diaryItemManager도 초기화되어 새로운 일기의 생성을 위해 받아온 아이디나 받아온 기존 일기 정보가 날아가버리는 문제가 있었습니다. 이를 해결하기 위해 리스트 뷰컨에서 diaryItemManager를 주입해준 후 해당 변수에 직접 접근해 새 일기를 생성하거나 정보를 전달했었습니다.
아이템 뷰컨의 이니셜라이저 내에서 주입받은 diaryItemManager를 사용해 일기를 생성하거나 정보를 받아오는 메서드를 호출하도록 수정해보았습니다.

2023-01-05 14:16 UTC, jsa0224 commented on Diary/Resource/Model/CoreDataManager.swift
> +            }
[ca1e927](https://github.com/yagom-academy/ios-diary/pull/80/commits/ca1e92763842046b0cc626f6f2369877c0cfb0b8)
해당 부분은 NSPersistentContainer가 로드되지 않았을 때의 에러 처리를 하는 부분입니다. 이 부분의 얼럿을 띄우기 위해 테스트해본 결과, DiaryListViewController에서 viewDidAppear에서 코어데이터를 패치가 안 될 경우 띄우는 얼럿이 나왔기 때문에 그냥 넘어갔던 거 같습니다. 올라프가 말씀해주신 부분을 참고하여 alert을 delegate을 통해 띄우는 방향으로 수정했습니다.

2023-01-05 14:17 UTC, dev-summer commented on Diary/Resource/Model/CoreDataManager.swift
> +    var persistentContainer: NSPersistentContainer { get }
[0469f3f](https://github.com/yagom-academy/ios-diary/pull/80/commits/0469f3fa3c7d86368c6f203c0aa2b08e18ebc413)

저희가 "무엇을 테스트하고 싶은가?"를 명확히 정의내리지 못해서 생겼던 문제인 것 같습니다.
무엇을, 어떻게 테스트해야 할 지 몰라서 Core Data Unit Test 라는 키워드로 구글링해본 결과, 대부분의 자료가 `inMemoryStorage`를 이용해 실제로 임시적인 저장소에 CRUD가 되는지를 테스트하는 방법을 알려주고 있었습니다 (로직만을 검증하는 것이 아닌...).
하지만 올라프가 설명해주신 방법대로 테스팅 해보는 것도 필요하다고 생각해서 로직을 검증해야 하는 메서드만 `CoreDataManageable` 프로토콜에서 가지고 있을 수 있도록 변경했습니다.

2023-01-05 14:19 UTC, jsa0224 commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +        let tappedEnter = diaryItemManager.enter(from: titleTextView.text)
[5f12c3b](https://github.com/yagom-academy/ios-diary/pull/80/commits/5f12c3b0063cabba31a4cab731f822fe66ce62de)
이 부분은 기능 분리가 안 되었던 거 같아, 2개의 메서드로 기능 분리하는 방향으로 수정했습니다.

2023-01-05 14:20 UTC, jsa0224 commented on Diary/Resource/Controller/DiaryItemViewController.swift
> +        diaryItemManager?.removePlaceholder(textView: textView)
[d9caad9](https://github.com/yagom-academy/ios-diary/pull/80/commits/d9caad9b7af2bb9c753c907ca7492b63e5a2cddf)
넵! 해당 객체에서 텍스트뷰를 조정하지 않도록 수정했습니다.

2023-02-02 02:29 UTC, closed without merging