일기장 [STPE 2] 준호, 망디
yagom-academy/ios-diary pull request #81
Opened 2022-12-30 07:43 UTC by MangDi-L

@Monsteel  안녕하세요 토니!  
STEP 2 PR 입니다.  
`Core Data`를 사용한 프로젝트는 처음이라 시간이 좀 걸렸습니다.  
연말 잘 보내시고 리뷰 잘 부탁드립니다.

## 🤔 고민했던 점

- 데이터 등록 시 NSDiaryModelObject의 SubClass를 사용하여 인스턴스 초기화
    처음엔 `entity(forEntityName:in:)` 메서드로 Entity(DiaryModelObject) 를 찾은 뒤,  
찾은 Entity를 가지고 `NSManagedObject` 의 `init(entity:insertInto:)` 이니셜라이저로 인스턴스를 만들었습니다.  
`entity` 메서드 `EntityName` 와 `setValue` 메서드의 `forKey` 에 직접 문자열을 입력하기 때문에 잘못된 문자열 입력으로 인해 휴먼 에러가 발생할 가능성이 있습니다.  
또한 에러를 컴파일 단계에서 확인하지 못 하기 때문에 런타임 에러가 발생할 수 있습니다.  
따라서 `NSManagedObject`의 subClass 인 `DiaryModelObject` 의 `init(context:)` 이니셜라이저를 사용해 인스턴스를 만들도록 했습니다.
    
```swift
    // 수정 전
    func insertDiary(_ diary: Diary) {
        guard let entity = NSEntityDescription.entity(forEntityName: "DiaryModelObject", 
                                                      in: persistentContainer.viewContext) else { return }
        let diaryModelObejct = NSManagedObject(entity: entity,
                                               insertInto: persistentContainer.viewContext)
        diaryModelObejct.setValue(diary.id, forKey: "id")
        diaryModelObejct.setValue(diary.title, forKey: "title")
        diaryModelObejct.setValue(diary.body, forKey: "body")
        diaryModelObejct.setValue(diary.createdAt, forKey: "createdAt")
        persistentContainer.saveContext()
    }

    // 수정 후
    func insertDiary(_ diary: Diary) {
        let diaryModelObejct = DiaryModelObject(context: persistentContainer.viewContext)
        diaryModelObejct.id = diary.id
        diaryModelObejct.title = diary.title
        diaryModelObejct.body = diary.body
        diaryModelObejct.createdAt = diary.createdAt
        persistentContainer.saveContext()
    }
```

---

## 🙏 조언을 얻고 싶은 부분

- 일기장 상세 화면에서 목록 화면 데이터 갱신
일기장 상세 화면이 닫히고 목록 화면이 열릴 때 목록 화면 컬렉션 뷰의 데이터를 업데이트하기 위해 `delegate` 대신 `escaping cclosure` 를 사용했습니다.  
`(Diary, Action) -> Void` 타입의 클로저를 상세 화면의 이니셜라이저를 통해 전달하여, 상세 화면이 닫힐 때 목록 화면에서 어떤 `Diary`의 정보가 수정/삭제 되었는 지 목록 화면에서 확인할 수 있도록 했습니다.  
`Delegate` 를 사용하여 비슷하게 기능을 구현할 수 있을거 같습니다. 이번 프로젝트에서는 두 가지 파라미터만 전달받으면 된다고 생각하여 클로저를 사용해보았습니다.  
토니께서는 이를 어떻게 생각하시는 지 궁금합니다.  

```swift
    let diaryDetailViewController = DiaryDetailViewController(diary: newDiary) { [weak self] diary, action in
        switch action {
        case .update:
            self?.update(diary: diary)
            self?.updateSnapshot([diary.id])
        case .delete:
            self?.delete(diary: diary)
            self?.updateSnapshot()
        }
    }
    navigationController?.pushViewController(diaryDetailViewController, animated: true)
    }
```

- UIActivityViewController를 커스텀하는방법
공유하기버튼을 눌러서 액티비티 뷰를 띄울때 Title은 일기장의 제목을, Text부분은 일기장의 내용을, ImageView는 간단한 일기장이모지를, 이렇게 커스텀해서 넣어주고 싶었습니다.  
그런데 공식문서를 봐도 관련된 프로퍼티가 안보이고 구글링으로 알려주는 블로그가 있나 찾아봤는데 찾질 못했습니다..  
혹시 이부분에 대해 알고계신 정보가 있으시다면 알려주시면 감사합니다!

|구현하고자 하는 화면|현재 구현 화면|
|:--:|:--:|
|<img src="https://i.imgur.com/t8o0QWE.png" width="300">|<img src="https://i.imgur.com/Dd97LSz.png" width="300">|

2023-01-03 00:37 UTC, Monsteel requested changes
안녕하세요 준호 망디! 👍 
새해 복 많이 받으세요 🙇🏻‍♂️ 이번 스텝도 고생 많으셨습니다!
간단한 코멘트 몇가지 남겨보았고 조언 구하고 싶은 내용 남겨주신 부분 답변 드릴 수 있도록 하겠습니다!
리뷰가 늦어서 죄송해요 🙏

### Delegate vs Closure
[delegate 와 closure 비교해놓은 글](https://itnext.io/delegates-vs-closure-callbacks-f36f9029217d) 이 있어서 요거 한번 읽어보시면 좋을것 같아요.

공감되는 포인트가 있으신지 체크하시면서 읽어보시면 좋을것 같아요. 잘 비교해 둔것 같네요ㅎㅎ

==

사실 이 영역은 각 상황마다 합리적인 방법을 도출하기 까지는 여러 상황들을 경험해보는게 중요하다고 생각하는데요, 그래서 그 경험을 바탕으로 어떤 방법이 이 상황에 보다 합리적인 선택지인지 판단하실 수 있을것 같습니다.

**하지만, 우리가 여러 케이스를 당장 경험할 수 없으니, 여러 사람들의 경험이나 고민 생각을 간접적으로 경험해보시면서 여러분들의 생각을 정리해보시는걸 추천드리는데요~**

경험의 영역이라는게 단순히 한사람의 경험만 가지고 판단하시는것 보단, 여러 사람일수록 좋습니다.
그래서 우선 그 첫 시작으로 앞서 남겨드린 링크를 보고 시작해보셨으면 좋겠습니다.

==
### 2. UIActivityViewController custom

공식문서를 한번 찾아봤는데 뭔가 원하시는 정보가 있는것 같아요.

[UIActivityViewController의 공식 문서](https://developer.apple.com/documentation/uikit/uiactivityviewcontroller) 내의
[생성자](https://developer.apple.com/documentation/uikit/uiactivityviewcontroller/1622019-init) 부분을 한번 살펴보시겠어요 ? 원하는 값이 어떤 객체에 감싸져 있는 형태로 title이 존재하고 있는것 같습니다 👀

==

궁금하신점은 언제든 DM이나 pr comment로 남겨주시구요,
PR merege준비되시면 말씀 부탁립니다 👍 

새해 복 많이 받으세요!

2023-01-03 00:37 UTC, Monsteel commented on Diary/Controllers/DiaryListViewController.swift
> +            switch action {
enum 을 통해 분기처리를 해주셨군요! 👍  좋습니다.
이렇게 되면 case가 추가되었을 때 추가된 case에 대한 구현부가 구현되지 않으면 컴파일 오류로 알려줘서 humanerror를 줄일 수 있어 선호하는 편입니다.

2023-01-03 00:37 UTC, Monsteel commented on Diary/Controllers/DiaryDetailViewController.swift
> +        guard bodyTextView.isFirstResponder,
개인적으로 gurad문 조건을 하나로 유지하려고 합니다. 가독성 때문인데요, 분리하신 것 vs 합치신것 비교해보시고 편하신 방법으로 처리해주시면 좋을것 같네요 :)

2023-01-03 00:37 UTC, Monsteel commented on Diary/Models/Diary.swift
> +    private(set) var id: UUID = UUID()
개인적으로 선언부와 Initializer 두 곳에서 중복으로 값을 초기화하는 방향을 선호하지 않습니다.
두 코드가 중복된 의미를 가지기도 하고, 이후 기본 값을 변경해야 할 때 두 곳을 모두 체크해야 한다는 점 때문입니다.

Initializer의 parameter에 노출시키지 않으면서 초기화 하고 싶을때 에도 Initializer 안에서 parameter없이 초기화 하는 방향을 선호합니다.

2023-01-03 00:37 UTC, Monsteel commented on Diary/SupportFiles/ko.lproj/Localizable.strings
> +"Really?" = "진짜요?";
Really? 🤣 재미있네요!

2023-01-03 05:41 UTC, MangDi-L commented on Diary/Models/Diary.swift
> +    private(set) var id: UUID = UUID()
선언부를 수정해서 중복으로 초기화하는방식을 수정했습니다!
이니셜라이저에서 수정을 하지않은 이유는 코어데이터에서 데이터를 받고 Diary형식으로 치환할 때, id를 기준으로 하기때문에 이와같이 수정하였습니다.
[c6ebe3f](https://github.com/yagom-academy/ios-diary/pull/81/commits/c6ebe3f75492b982ef7b1eb279af77fa052ae979)

2023-01-03 05:42 UTC, junho15 commented on Diary/Controllers/DiaryDetailViewController.swift
> +        guard bodyTextView.isFirstResponder,
[190c61f](https://github.com/yagom-academy/ios-diary/pull/81/commits/190c61fdae595ad6ea6c5b88bd837d4972b659f2) 에서 guard 문 조건을 분리했습니다. `guard let` 과 `guard` 를 분리하는 게 더 가독성이 좋네요. 감사합니다.

2023-01-04 00:19 UTC, Monsteel approved these changes
수고하셨습니다 :) ⚡️⚡️

2023-01-04 00:19 UTC, merged