일기장 [STEP 3] 애런, 로빈, 건디
yagom-academy/ios-diary pull request #84
Opened 2023-01-05 04:45 UTC by Hashswim

![](https://i.imgur.com/FZ21nXs.png)
@ryan-son
안녕하세요 라이언~ 애런, 로빈, 건디(a.k.a.로켓단)입니다! 드디어 마지막 스텝이네요... 라이언이랑 벌써 헤어지게 되어서 너무 슬픕니다ㅠㅠ 이번 스텝에 대해서도 지도 부탁드립니다!

## 🤔 고민했던 점

### NetworkManager의 `fetch` 기능 재사용
기존에는 `WeatherResponseDTO` 타입을 받아오는 `fetchWeather()`와 날씨 아이콘을 받아오는 `fetchWeatherIcon()` 메서드를 만들어 주었는데, 내부 dataTask 코드가 똑같아서 어떻게하면 중복된 코드를 줄일 수 있을까 고민하였습니다.
아래와 같이 `NetworkManager`에 `fetchData()` 하나만 구현해서 데이터를 컴플리션 핸들러로 넘겨준 다음, 뷰 컨트롤러 쪽에서 필요한 데이터를 가공해서 사용하는 방법을 사용했습니다.

```swift
// NetworkManager
func fetchData(url: URL?, completion: @escaping (Result<Data, Error>) -> Voi
    guard let url = url else {
        completion(.failure(NetworkError.invalidURL))
        return
    }
    let dataTask = URLSession.shared.dataTask(with: url) { data, response, e
        if let error = error {
            completion(.failure(error))
            return
        }
        guard let httpResponse = response as? HTTPURLResponse,
              (200...299).contains(httpResponse.statusCode) else {
            completion(.failure(NetworkError.responseError))
            return
        }
        guard let data = data else {
            completion(.failure(NetworkError.invalidData))
            return
        }
        completion(.success(data))
    }
    dataTask.resume()
}

// DiaryListViewController
private func configureWeatherIconImage(cell: DiaryListCell, _ icon: String) {
    let url = NetworkManager.shared.weatherIconURL(icon: icon)
    NetworkManager.shared.fetchData(url: url) { result in
        switch result {
        case .success(let data):
            guard let weatherIconImage = UIImage(data: data) else {
                return
            }
            DispatchQueue.main.async {
                cell.weatherIconImageView.image = weatherIconImage
            }
        case .failure(let error):
            print(error.localizedDescription)
        }
    }
}
```

### 유저 위치권한 허용 요청 시점
유저로부터 위치정보를 받기 위해 권한허용 요청을 보내는 것을 언제 할 지에 대해서 고민했었습니다.
앱을 처음 키는 시점에 요청을 보낼지 `DiaryViewController`가 생성되는 시점에 보낼지 생각해 보았고 일기장 앱은 시작될 때 요청을 받는 것이 사용자 입장에서 더 좋을 것이라 판단되어 처음 시작될 때 요청을 보내도록 구현했습니다.
```swift
 override func viewDidLoad() {
        super.viewDidLoad()

        requestLocationAuthorization()
        ...
    }
}
    ...
extension DiaryListViewController {
    private func requestLocationAuthorization() {
        locationManager.requestWhenInUseAuthorization()
    }
}
```
### 유저가 위치권한을 허용하지 않았을 때의 레이아웃
유저가 개인 정보에 관련된 작업을 허용하지 않더라도 앱은 정상적으로 작동되어야 할 것입니다. 하지만 허용할 때와 허용하지 않을 때 화면에 보여지는 것은 다를 수 있을 것입니다. 그렇더라도 비슷한 경험을 할 수 있게끔 만드는 것이 좋을 것이라 생각했습니다.
|전체 레이아웃|확대|
|:-:|:-:|
|<img src="https://i.imgur.com/ezNL3T8.png" height="400"/>|<img src="https://i.imgur.com/rHOyUoo.png" height="400"/>|

위 이미지에서 `111111`과 `22222` 일기의 경우 유저의 위치권한을 허용하지 않은 상태로 작성한 다이어리이기 때문에 위치에 따른 날씨정보를 포함하지 않습니다. 하지만 위치권한이 있는 일기의 경우 날짜와 미리보기 사이에 아이콘이 들어가기 때문에 만약 날씨 정보가 없을 경우 딱 붙고, 날씨정보가 있을 경우에만 아이콘만큼 떨어진다면 일정한 경험을 주지 못할 것이라고 생각해 위치권한이 없는 경우에도 같은 간격을 가질 것을 고려하였습니다.

## 🧑‍🏫 조언을 얻고 싶은 부분

### 실패시 적절한 오류 핸들링
fatalError의 경우 앱이 죽어버릴텐데 앱은 어떠한 경우에도 죽지 않게끔 설계하는 것이 좋을 것 같습니다. 그렇다고 제대로 수행 되지 않을 때마다 얼럿을 사용하는 것은 적절한 얼럿의 사용인지도 고민이 됩니다. 기능이 제대로 수행되지 않았을 때 사용자에게 알리는 것이 바람직 할텐데, 사용자에게 기능이 잘 수행되지 않았음을 어떻게 알려야할까요?
```swift
// Core Data 저장 실패시
do {
    try context.save()
} catch {
    // 오류 처리
}
```

```swift
// Result가 failure일시
case .failure(let error):
    // 오류 처리
}
```

### 시뮬레이터 내부 설정 앱에서 위치 권한 등을 보는 방법
실제 핸드폰은 설정에서 각 앱마다 권한을 설정하는 기능이 있는데, 시뮬레이터에서는 권한 설정하는 기능이 보이지 않습니다.ㅠㅠ 그래서 매번 권한을 설정할 때 마다 앱을 삭제하고 다시 설치해야 되는지 궁금합니다!

### 코어데이터 migration vs relation
weather와 관련된 데이터를 코어 데이터에 저장하게 되면서 기존의 `DiaryEntity`에 weather관련 데이터를 추가하면서 migration을 할지 weatherEntity를 생성해 relation을 정의해 사용할지에 대해서 고민했습니다.

이번 기회에 migration을 공부해 보기 위해 migration으로 구현했지만 relation으로 구현하는 방법은 어떨지, relation으로 정의해도 문제가 없는지 조언을 얻고 싶습니다..! 애플에서는 단방향 relation에 대해 지양하는 것 같아서 여쭤보고 싶었습니다.

|migration|relation|
|:--:|:--:|
|![](https://i.imgur.com/K2AiYcB.png)|![](https://i.imgur.com/h0NJI6e.png)|

2023-01-08 17:58 UTC, ryan-son requested changes
여러분 고생 많으셨습니다. 이번 프로젝트도 재미있으셨죠?

이번에는 생각해볼 만한 내용이 꽤 있을 것 같네요. 코드에 개별 코멘트 남겨두었으니 확인해보세요.

>## 🧑‍🏫 조언을 얻고 싶은 부분

>### 실패시 적절한 오류 핸들링
>fatalError의 경우 앱이 죽어버릴텐데 앱은 어떠한 경우에도 죽지 않게끔 설계하는 것이 좋을 것 같습니다. 그렇다고 제대로 수행 되지 않을 때마다 얼럿을 사용하는 것은 적절한 얼럿의 사용인지도 고민이 됩니다. 기능이 제대로 수행되지 않았을 때 사용자에게 알리는 것이 바람직 할텐데, 사용자에게 기능이 잘 수행되지 않았음을 어떻게 알려야할까요?

사용자가 에러를 해결할 수 있는 경우와 개발자가 문제를 해결해야하는 상황으로 나누어볼 수 있을 것 같네요. 전자의 경우에는 사용자가 해당 행동을 쉽게 할 수 있도록 얼럿 또는 토스트를 띄워주는 게 좋을 것이고, 후자의 경우에는 개발자가 에러를 인식할 수 있도록 개발자가 확인할 수 있는 공간으로 로그를 보내는 것이 좋아보이네요. 이런 구조를 택하게 될 경우에는 아래와 같이 사용자의 데이터가 진단에 이용된다는 것을 앱스토어 제품 페이지에 고지하여야 합니다.

![image](https://user-images.githubusercontent.com/69730931/211211359-38b72bc1-c619-43c3-8049-f40c97a35b8e.png)

>### 시뮬레이터 내부 설정 앱에서 위치 권한 등을 보는 방법
>실제 핸드폰은 설정에서 각 앱마다 권한을 설정하는 기능이 있는데, 시뮬레이터에서는 권한 설정하는 기능이 보이지 않습니다.ㅠㅠ 그래서 매번 권한을 설정할 때 마다 앱을 삭제하고 다시 설치해야 되는지 궁금합니다!

[커뮤니티](https://developer.apple.com/forums/thread/693317)에서도 버그라고 보고 있고, 해결되어야 한다는 입장이네요.

>### 코어데이터 migration vs relation
>weather와 관련된 데이터를 코어 데이터에 저장하게 되면서 기존의 `DiaryEntity`에 weather관련 데이터를 추가하면서 migration을 할지 weatherEntity를 생성해 relation을 정의해 사용할지에 대해서 고민했습니다.

>이번 기회에 migration을 공부해 보기 위해 migration으로 구현했지만 relation으로 구현하는 방법은 어떨지, relation으로 정의해도 문제가 없는지 조언을 얻고 싶습니다..! 애플에서는 단방향 relation에 대해 지양하는 것 같아서 여쭤보고 싶었습니다.

이번 피드백을 보시고 구현해보시면서 방향이 잡힐 수 있다고 생각합니다. 양방향으로 relation을 정의할 수 있는 방법은 없나요? 기존의 `Diary` 타입과 피드백을 통해 변경될 DTO 타입을 살펴보시면 될 것 같습니다.

2023-01-08 17:58 UTC, ryan-son commented on Diary/App/Info.plist
> +	<string></string>
[P1]
권한을 요청하는 시점이 중요한 것처럼 권한이 필요한 이유를 설명하는 것도 마찬가지로 중요합니다. 왜 권한이 필요하고, 어떤 기능에 사용되는지 사용자에게 알려주세요.

2023-01-08 17:58 UTC, ryan-son commented on Diary/Controller/DiaryListViewController.swift
>      }
👍

2023-01-08 17:58 UTC, ryan-son commented on Diary/Controller/DiaryListViewController.swift
> +            self.configureCell(cell: cell, diary: diary)
[P5]
cell이라는 단어가 중복되니 메서드 이름이나 파라미터 이름 둘 중에 하나만 써도 될 것 같네요.

2023-01-08 17:58 UTC, ryan-son commented on Diary/Controller/DiaryListViewController.swift
> +        NetworkManager.shared.fetchData(url: url) { result in
[P2]
`shared` 인스턴스를 사용할 것을 강제하고 있네요. 응집도와 결합도 중 결합도가 높은 경우라고 볼 수 있어요.
휴대폰의 배터리가 회로기판에 용접되어 있다면, 배터리만 교체하기 쉽지 않을거에요. 하지만 USB 규격처럼 동일한 인터페이스만 지킨다면 어떤 형태의 배터리도 연결될 수 있기 때문에 동일한 프로토콜을 준수하는 인스턴스를 교체할 수 있는거죠. 사용자가 어떤 인스턴스를 사용할 수 있을지 결정할 수 있게 만들어주시면 좋을 것 같네요.

2023-01-08 17:58 UTC, ryan-son commented on Diary/Controller/DiaryListViewController.swift
> +            }
[P2]
날씨 아이콘을 네트워크로부터 받아와서 사용할 일이 cell에서 사용하는 것밖에 없어 지금은 이대로 괜찮습니다. 하지만 두 곳 이상에서 사용된다면 `날씨 아이콘을 네트워크로부터 받아온다`라는 행동을 위해 분리를 시도하게 되겠네요. 학습을 하고 계시니 메서드의 재사용성에 대해서도 고려해보면 좋을 것 같아요.

2023-01-08 17:58 UTC, ryan-son commented on Diary/Controller/DiaryListViewController.swift
> +        }
셀을 선택할 때 날씨 아이콘을 셀에 설정하는 정책이네요. 일기를 작성할 때가 아니라 이 때 설정해주기로 한 이유는 무엇이었나요?

2023-01-08 17:58 UTC, ryan-son commented on Diary/Controller/DiaryViewController.swift
>      }
[P2]
객체지향 프로그래밍의 관점에서 `타입의 변경 이유는 하나인 것이 좋다`라는 의미의 예시로 들기 좋네요.
`DiaryViewController`는 `CoreLocation` 프레임워크로 사용자의 위치 권한 허용 여부를 이니셜라이저로 전달받아 `UIKit` 프레임워크로 UI를 그리는 역할을 동시에 수행하고 있네요. 이미 안정적인 프레임워크인 `CoreLocation`은 그럴 가능성이 적으므로 이런 형태의 설계를 시도해볼 수 있습니다.
DiaryViewController가 `CoreLocation`과 같이 안정적인 프레임워크가 아니라 서드파티 프레임워크 또는 여러분이 만든 커스텀 타입에 의존하는 경우 의존하는 곳에서 변경이 생길 경우 관계 없는 DiaryViewController까지 변경을 전파받습니다. 응집도와 결합도 중 응집도가 낮다는 의미입니다. 현재 상태에서 예를 들면, `CLAuthorizationStatus `에 새로운 상태가 추가되거나 변경되거나 제거되는 경우, 또는 `CLAuthorizationStatus`라는 타입 이름 자체가 변경된 경우, 120, 122, 123 라인에 있는 타입 이름 또는 케이스 이름이 함께 변경되어야 할 것입니다. DiaryViewController에는 아무런 기능상 변경이 없는데 말이죠.
`타입이 여러가지 이유로 변경되는 일이 없게 만드는 것`이 바로 `응집도가 높은 구조`를 만드는 일입니다. 안정적인 프레임워크 또는 타입에 의존하는 경우 이런 구조를 고려해볼 수 있으나, 학습하는 입장에서는 한 번 생각해볼만한 주제이니 팀원 분들과 논의해보셨으면 좋겠습니다.

2023-01-08 17:58 UTC, ryan-son commented on Diary/Controller/DiaryViewController.swift
> +            }
직전 코멘트와 같은 맥락에서 생각해볼만한 주제입니다. 네트워킹 기능만 변경하고 싶어도 변경은 `DiaryViewController`에서 이루어져야 합니다. 예를 들어, `fetchData(url:completionHandler:)` 메서드 이름이 변경되거나 파라미터 타입이 변경되더라도 그 변경사항이 `DiaryViewController`에 전파됩니다.

2023-01-08 17:58 UTC, ryan-son commented on Diary/Model/Diary.swift
> +    let weatherIcon: String?
[P2]
데이터를 원격 서버에 저장해두고 받아오는 형태가 된다면, weather에 대한 정보는 앞으로 얼마든지 변경될 수 있을 것 같네요. 날씨를 얻은 도시, 강수량, 자외선 지수 등등의 정보가 포함된다면 `DiaryResponseDTO`는 그때마다 변경되어야 할거에요. 그보다는 `Diary`처럼 날씨에 대한 사항을 새로운 DTO에 캡슐화 시켜보시면 날씨 타입의 프로퍼티에 변경이 생겨도 영향을 받지 않을 수 있습니다. 심지어 프로퍼티 이름이 바뀌어도요.

2023-01-08 17:58 UTC, ryan-son commented on Diary/Model/Weather.swift
> +}
이 친구의 프로퍼티는 어떤 이유로 배열이 되었나요? 그리고 첫번째 날씨가 `Weather`로 그대로 변환될 수 있는 이유는 무엇인가요?

2023-01-08 17:58 UTC, ryan-son commented on Diary/Model/Weather.swift
> +}
캡슐화 잘 하셨습니다👍. 기왕 DTO와 도메인 타입을 분리한 김에 도메인 타입의 프로퍼티는 의미를 더 잘 이해할 수 있도록 `main`보다는 더 나은 이름으로 지어볼 수도 있겠군요.

2023-01-08 17:58 UTC, ryan-son commented on Diary/Network/NetworkManager.swift
> +}
[P5]
`Foundation` 프레임워크의 `LocalizedError`를 이용하면 다양한 상황에서 에러를 표현해줄 수 있습니다. 물론 지금 상태에서도 커스텀하게 에러를 제공해줄 수는 있겠지만요.

2023-01-08 17:58 UTC, ryan-son commented on Diary/Network/NetworkManager.swift
> +    static let shared = NetworkManager()
이니셜라이저를 사용할 수 있게 만든 것으로 보아 싱글톤 패턴을 따른다기보다 `URLSession`처럼 특정 설정을 미리 해두어 편하게 사용할 수 있도록 만든 공유 인스턴스라고 보였는데, 막상 구현을 보니 이 인스턴스가 특별한 설정을 해두었거나 하는 동작은 없어보이는군요. 공유 인스턴스를 만든 이유가 궁금합니다. 사용할 곳에서 인스턴스를 만들어 사용할 수도 있었을텐데, 이런 결정을 한 이유는 무엇이었나요?

2023-01-08 17:58 UTC, ryan-son commented on Diary/Network/NetworkManager.swift
> +final class NetworkManager {
[P2]
네트워크 매니저라는 이름인데, 날씨와 관련된 동작이 포함된 것으로 보이네요. 동료 개발자의 혼란을 방지하려면 타입의 이름을 변경하거나 날씨와 관련된 기능은 다른 타입으로 분리해주는 것이 좋아보입니다.

2023-01-08 17:58 UTC, ryan-son commented on Diary/Network/NetworkManager.swift
> +    }
[P2]
Weather API 키를 가져오는 동작은 (앞으로 만드신다면) weather 네트워킹이 필요한 타입에 모아두는 편이 좋을 것 같네요.

2023-01-08 17:58 UTC, ryan-son commented on Diary/Network/NetworkManager.swift
> +    }
1. [P2] 네트워킹 타입에서 `CoreLocation` 프레임워크에 의존하고 있군요. 관련된 이야기는 앞서 많은 내용을 말씀드렸으니 생각해보셨을 것 같네요. 
2. `fatalError` 보다 온건한 탈출을 할 수는 없을까요? 시뮬레이터에서는 동작시켜보기 어렵네요.

2023-01-08 17:58 UTC, ryan-son commented on Diary/Network/NetworkManager.swift
> +    }
[P2]
날씨 네트워킹과 관련된 기능은 다른 곳에 모아봅시다~

2023-01-08 17:58 UTC, ryan-son commented on Diary/Network/NetworkManager.swift
> +    }
`NetworkManager` 이름과 가장 어울리는 메서드네요. 이 메서드를 이용한다면 dataTask에 관련된 코드를 중복해서 작성하지 않을 수 있겠어요. 아래 내용에 대해서는 조금 더 생각해보시면 좋겠습니다.
1. `dataTask`에서 반환된 task를 단순히 resume 해주고 있는데, 실행 중 필요없게 될 때도 있습니다. 이를 위해 타입의 인스턴스 프로퍼티로 할당해두었다 `cancel`하는 방식을 고려해볼 수 있어요. 물론 cancel 상태에 따라 61~76번 라인의 컴플리션 핸들러에서 빠른 탈출과 같이 어떤 동작을 할지 코드가 추가되어야 합니다.
2. 타겟 OS 버전이 iOS 15.0인만큼 `async/await` 메서드를 고려해볼 수 있겠네요. iOS 13.0~iOS 14.x라면 컴플리션 핸들러를 가진 메서드를 `withCheckedContinuation(_:)`으로 래핑하는 방식도 고려해볼 수 있고, iOS 15.0부터는 `URLSession`의 `data(for:)` 메서드를 활용해 볼 수도 있습니다. 너무 어렵다면 다음번에 공부해보셔도 괜찮습니다. 다른 방법이 있다는 것만 알아두세요.

2023-01-08 17:58 UTC, ryan-son commented on Diary/View/DiaryListCell.swift
> +        label.setContentHuggingPriority(.init(1000), for: .vertical)
1000값을 가지는 priority의 이름은 [`UILayoutPriority.required`](https://developer.apple.com/documentation/uikit/uilayoutpriority/1622241-required) 입니다. 케이스가 있다면 RawValue 보다는 이름을 사용해보면 좋습니다.

2023-01-08 17:58 UTC, ryan-son commented on Diary/View/DiaryListCell.swift
> +        label.setContentCompressionResistancePriority(.defaultLow, for: .horizontal)
`UILayoutPriority.defaultLow`는 RawValue로 수치가 얼마나 되나요?

2023-01-10 01:53 UTC, Gundy93 commented on Diary/Controller/DiaryListViewController.swift
> +        }
아! 이 부분은 반대로 셀을 선택해서 상세 화면으로 전환할 때 title 부분에 위치한 이미지뷰에 이미지를 설정하는 부분입니다.

<img width="75" alt="스크린샷 2023-01-10 오전 10 52 27" src="https://user-images.githubusercontent.com/106914201/211443875-283dee85-7729-4038-9738-c2133c9451cb.png">

일기를 작성할 때는 네트워킹을 통해 이미지를 받아와서 설정하고, 기존의 일기의 경우에만 셀의 아이콘 이미지를 다음화면의 뷰컨트롤러로 전달해주고 있습니다.

2023-01-10 02:01 UTC, Gundy93 commented on Diary/Model/Weather.swift
> +}
해당 API가 제공하는 JSON 데이터 내부의 프로퍼티중 weather는 배열로 제공되기 때문이고, 해당 배열의 count는 1로 제공해주고 있어서 첫 번째를 사용하였습니다.

<img width="347" alt="스크린샷 2023-01-10 오전 11 00 45" src="https://user-images.githubusercontent.com/106914201/211444915-1739cc36-e7fd-4f93-ac18-51b72f8e3c29.png">

2023-01-10 02:16 UTC, Gundy93 commented on Diary/View/DiaryListCell.swift
> +        label.setContentCompressionResistancePriority(.defaultLow, for: .horizontal)
<img width="642" alt="스크린샷 2023-01-10 오전 11 11 56" src="https://user-images.githubusercontent.com/106914201/211446194-497b22e2-5c0d-4504-b9d6-1b5f0c525f83.png">

250 이었습니다. 
<img width="111" alt="스크린샷 2023-01-10 오전 11 14 19" src="https://user-images.githubusercontent.com/106914201/211446490-ea39fcae-3e78-4d51-9221-3c8a2f6fe0bc.png">
`required`, `high`, `low`의 경우에는 스토리보드의 인스펙터에서도 확인할 수 있었습니다. 숙지하도록 하겠습니다 😅

2023-01-10 02:18 UTC, Gundy93 commented on Diary/View/DiaryListCell.swift
> +        label.setContentHuggingPriority(.init(1000), for: .vertical)
이번 기회에 모든 케이스의 RawValue에 대해 정리해보는 기회가 되었습니다. 앞으로는 특정 케이스가 있는지 체크 후에 원시값을 사용하도록 하겠습니다! 😃

2023-01-10 05:28 UTC, Hashswim commented on Diary/App/Info.plist
> +	<string></string>
위치 데이터가 어떻게 사용되는지에 대해서 짧은 설명을 추가했습니다.

2023-01-10 05:29 UTC, Hashswim commented on Diary/Controller/DiaryListViewController.swift
> +            self.configureCell(cell: cell, diary: diary)
`configureCell(_ cell: DiaryListCell, with diary: Diary)`로 메서드 명을 수정했습니다..!

2023-01-10 06:24 UTC, Gundy93 commented on Diary/Controller/DiaryListViewController.swift
> +        NetworkManager.shared.fetchData(url: url) { result in
`Networkable` 프로토콜을 타입으로 사용하여 결합도 약화를 꾀했습니다!

2023-01-10 07:20 UTC, Gundy93 commented on Diary/Network/NetworkManager.swift
> +    }
2. 타입을 옵셔널로 변경하여 else 문 내부에서는 nil을 반환하도록 하였습니다! 모든 시뮬레이터에서 실험해본 것은 아니지만 되는 시뮬레이터가 있고 안되는 시뮬레이터가 있는 걸로 보아 Xcode 버그라고 생각이 드는데...대표적으로 13mini에서는 되지않고 Pro나 ProMax에서는 정상동작을 하였습니다.

2023-01-10 07:21 UTC, Hashswim commented on Diary/Controller/DiaryListViewController.swift
> +            }
UI에 반영하는 부분을 escaping closure로 받아와서 범용성 있게 동작하도록 수정했습니다..!
```swift
private func fetchWeatherIconImage(_ icon: String, _ completion: @escaping (UIImage) -> Void) {
        let url = WeatherAPIProvider.weatherIcon(icon: icon).url

        networkManager.fetchData(url: url) { result in
            switch result {
            case .success(let data):
                guard let weatherIconImage = UIImage(data: data) else {
                    return
                }
                completion(weatherIconImage)
            case .failure(let error):
                print(error)
            }
        }
    }
```

2023-01-10 08:17 UTC, yuvinrho commented on Diary/Controller/DiaryViewController.swift
>      }
권한 허용 여부를 Bool 값으로 받아서 체크하도록 아래와 같이 수정해주었습니다~
`init(diary: Diary, isAuthorizationAllow: Bool = false)`

2023-01-10 08:33 UTC, Gundy93 commented on Diary/Network/NetworkManager.swift
> +    }
1. `Coordinate` 타입 생성을 통해 `CoreLocation` 프레임워크에 의존하지 않도록 수정하였습니다.

2023-01-10 08:34 UTC, Gundy93 commented on Diary/Network/NetworkManager.swift
> +final class NetworkManager {
WeatherAPIProvider 타입 생성으로 날씨와 관련된 동작을 분리하였습니다.

2023-01-10 08:38 UTC, Gundy93 commented on Diary/Network/NetworkManager.swift
> +    }
WeatherAPIProvider 타입에 Weather API 키를 가져오는 동작도 같이 모아두었습니다.
또한 해당 부분 `fatakError`는 `assertionFailure`로 변경하였습니다.

```swift
private var apiKey: String? {
    guard let filePath = Bundle.main.path(forResource: "Info", ofType: "plist") else {
        assertionFailure("plist를 찾을 수 없습니다.")
        return nil
    }
    let plist = NSDictionary(contentsOfFile: filePath)
    guard let value = plist?.object(forKey: "Open Weather API KEY") as? String else {
        assertionFailure("Open Weather API KEY를 찾을 수 없습니다.")
        return nil
    }
    return value
}
```

혹시 이게 아니라 해당 네트워킹이 필요한 (가령 현재는 뷰컨트롤러) 타입에 모아두라는 의미일까요?
잘 이해했는지 모르겠어요 😅

2023-01-10 08:39 UTC, Gundy93 commented on Diary/Network/NetworkManager.swift
> +    }
해당 기능 WeatherAPIProvider 에 분리하였습니다! 또한 APIProvidable을 채택시켜 사용자는 url에 대해서만 접근하도록 하였습니다.

2023-01-10 08:46 UTC, Gundy93 commented on Diary/Controller/DiaryViewController.swift
> +            }
해당 부분은 프로토콜을 통해 의존성을 낮춰주었는데, 만약 NetworkManager에서 기능변경을 하고 싶다면 Networkable을 준수하기 위해 생성하는 `fetchData`메서드 내부에서, 다른 메서드를 호출하는 방향으로 수정할 수 있지않을까요?

쉽지 않은 주제네요...

2023-01-10 09:04 UTC, Hashswim commented on Diary/Model/Diary.swift
> +    let weatherIcon: String?
Diary 에서 아래와 같이 Weather 관련 프로퍼티를 캡슐화 했습니다..!
```swift
struct DiaryResponseDTO: Decodable {
    let title: String
    let body: String
    let createdAt: Double
    let weather: WeatherResponseDTO
    ...
}
```

2023-01-10 09:05 UTC, Hashswim commented on Diary/Model/Weather.swift
> +}
`맑음`, `흐림` 등의 `String` 값인 `main`을  `description`으로 수정했습니다!

2023-01-10 09:08 UTC, Hashswim commented on Diary/Network/NetworkManager.swift
> +    static let shared = NetworkManager()
이니셜라이저를 `private`으로 접근을 제한했습니다..!
Network관련 동작을 수행하는 객체를 하나만 설정하기 위해서 싱글톤 패턴으로 구현하고자 하였습니다.

2023-01-10 09:43 UTC, yuvinrho commented on Diary/Network/NetworkManager.swift
> +}
아래와 같이 에러메시지를 설정해 주었습니다~

```swift
enum NetworkError: LocalizedError {
    case responseError
    case invalidData
    case invalidURL
    case decodingError
    case unknownError

    var errorDescription: String {
        switch self {
        case .responseError:
            return "서버 응답이 없습니다."
        case .invalidData:
            return "유효하지 않은 데이터입니다."
        case .invalidURL:
            return "유효하지 않은 URL입니다."
        case .decodingError:
            return "JSON 디코딩 실패 했습니다."
        case .unknownError:
            return "알 수 없는 에러입니다."
        }
    }
}

//NetworkManager
func fetchData(url: URL?, completion: @escaping (Result<Data, NetworkError>) -> Void)
```

2023-01-10 09:46 UTC, Gundy93 commented on Diary/Network/NetworkManager.swift
> +    }
말씀해 주신 부분에 대해 유념하고 더 공부하도록 하겠습니다! 현재로는 이해가 부족해서 적용이 쉽지 않네요 😢
감사합니다 라이언 😃

2023-01-11 16:43 UTC, ryan-son approved these changes
여러분, 고생 많으셨습니다.

코멘트 남긴 내용을 회의실에서 모두 다루었으니 머지하겠습니다.

고생 많으셨습니다. 다음에 또 만나요~!

2023-01-11 16:44 UTC, merged