일기장 [STEP 3] inho, Dragon
yagom-academy/ios-diary pull request #85
Opened 2023-01-05 10:01 UTC by FlameYG

안녕하세요, 쿠마(@leejun6694)🙇‍🙇‍♀️!
[inho🐶](https://github.com/inho-98), [Dragon🐉](https://github.com/FlameYG)입니다!
이번 스텝은 URLSession을 통해 이미지 불러오는 것과 CoreData Migration이 중점적이였다고 생각됩니다!
많이 부족한 코드이지만 구조가 적절했는지 꼼꼼히 봐주시면 감사하겠습니다!👍 그리고 마지막 스텝 리뷰인데 그동안 리뷰 감사했습니다~!😀

## 실행화면
|<img src=https://i.imgur.com/V4LqSxa.png width=200>|<img src=https://i.imgur.com/zJL28f0.png width=200>|
|:-:|:-:|
|날씨 정보 구현 전 일기 마이그레이션|사용자 위치 기반의 날씨정보|

## 📍고민했던 부분 
### 이전 데이터를 가져오기 위한 `Lightweight Migration`
- 일기 엔티티에 날씨 정보를 추가하면서, 기존의 코어데이터의 정보를 가져오기 위해 `migration`을 했습니다. 기존 `entity`에 새로운 버전을 추가하고, 매핑 모델을 이용하여 두 엔티티를 연결하였습니다.
- `Diary`모델 타입에 추가된 `icon` 프로퍼티에는 새로 작성되는 일기에 대해서 받아오는 날씨 정보의 아이콘 정보를 저장하고, 기존 엔티티에는 빈 문자열을 저장합니다.
- 기존 엔티티 중에 업데이트 되는 일기가 있으면, 그 시점의 날씨를 기반으로 프로퍼티를 업데이트하고, 날씨 정보를 추가해 줍니다.

### 사용자의 위치를 받기 위한 `Core Location`활용
- 사용자의 위치를 알기 위해 `CLLocationManager`타입과 타입의 메서드를 활용해서 필요한 기능을 구현하였습니다.
- 앱에서 필요한 위치 정보는 사용자의 위치를 추적하는 것이 아닌 사용자의 현재 위치를 한번만 조회하면 되어서 `requestLocation()`메서드를 활용했습니다.

### 구조체에서 프로토콜로의 변경
- STEP2에서 `Alert`와 `Activity`를 관리해주는 모델 파일을 어떻게 구현할지 고민하였습니다.
- 그리고 STEP2에서 `ControllerManager구조체`를 생성하여 관리를 하고자 하였지만, 
`UIViewController`에서만 사용가능한 `Present메서드`를 사용할 수 없어 사용성에서 유연함이 떨어지는 코드를 구현했었습니다.
- 기존의 구조체는 프로퍼티를 가지고 있지 않았고, 인스턴스의 필요성도 분명하지 않아 리뷰를 통해 얻은 조언에서 `Protocol`을 사용하여 `UIViewController`만이 채택 가능하도록 설정하고
`Present메서드`를 사용할 수 있게 되어 사용성에서 유연해지는 코드를 구현할 수 있었습니다.

## 📍조언을 얻고싶은 부분
### `WeatherAPI & Weather DTO` 
- 날씨 `API`의 `JSON`형식에 맞게 필요한 데이터를 가져오기 위해 위 두가지 `DTO`를 구현하였습니다. 필요한 `JSON`형식에서는 아래와 같이 중첩되어 있는 구조였습니다.
    ```swift
    {
      ...
      "weather": [
        {
          "id": 501,
          "main": "Rain",
          "description": "moderate rain",
          "icon": "10d"
        }
      ],
        ...
    }
    ```
- 현재 코드에서는 한번의 중첩만 있어서 내부 `Weather`타입을 만들고 데이터를 받아주었는데, 중첩이 많은 `JSON`데이터가 있고, 내부의 데이터를 받아올때 그 구조 그대로 구현을 해야하는지 고민되었습니다..! 🧐

2023-01-05 16:42 UTC, leejun6694 commented on Diary/Source/Model/Diary.swift
> +    let icon: String
`icon` 이라고 하면 image 가 먼저 떠오르는데, `iconName` 등의 이름은 어떨까요? (type 이 String 이여서요~)

2023-01-05 16:53 UTC, leejun6694 requested changes
@inho-98 @FlameYG 안녕하세요 : )
step 2 에 리뷰 드렸던 내용도 반영을 성공하셔서 기분이 매우 좋네요~~!
step 3 는 리뷰 내용이 많진 않지만, API 호출 관련해서 얘기를 좀 더 나누면 좋을 것 같습니다.
고생하셨습니다 !!

2023-01-05 16:53 UTC, leejun6694 commented on Diary/Source/Model/Diary.swift
> +    let icon: String
icon 이라고 하면 image 가 먼저 떠오르는데, iconName 등의 이름은 어떨까요? (type 이 String 이여서요~)

2023-01-05 16:53 UTC, leejun6694 commented on Diary/Source/Model/NetworkManager.swift
> +struct NetworkManager {
요것도 좀 고민을 해볼까요? struct 가 class, enum 등의 다른 방법보다 어떤 장점이 있을지??

2023-01-05 16:53 UTC, leejun6694 commented on Diary/Source/Model/NetworkManager.swift
> +            }
지금은 하나의 guard 문으로 관리해도 괜찮겠네요~?
(추후 각기 다른 에러 처리를 하게되면, 지금처럼 구분이 필요해보입니다.)

2023-01-05 16:53 UTC, leejun6694 commented on Diary/Source/Model/NetworkManager.swift
> +            }
👍

2023-01-05 16:53 UTC, leejun6694 commented on Diary/Source/Model/Protocol/ActivityPresentable.swift
> +protocol ActivityPresentable: UIViewController {
🥇

2023-01-05 16:53 UTC, leejun6694 commented on Diary/Source/Model/Weather/WeatherAPI.swift
> +struct WeatherAPI: Decodable {
모델 이름을 좀 더 고민해볼까요?
Weather 와 관련된 API 가 여려개 있다고 생각해서요~!

2023-01-05 16:53 UTC, leejun6694 commented on Diary/Source/Model/Weather/WeatherManager.swift
> +private enum URL {
URL 은 이미 기본 type 으로 정의되어 있습니다.
다른 네이밍은 어떨까요?

2023-01-05 16:53 UTC, leejun6694 commented on Diary/Source/Controller/DiaryFormViewController.swift
> +                self.weather = weather
`self.weather` 값 변경 후, ui refresh 는 따로 필요 없을까요?

2023-01-06 05:41 UTC, inho-98 commented on Diary/Source/Model/Diary.swift
> +    let icon: String
말씀해주신 대로 이미지에 가까운 이름이어서 `iconName`으로 수정하였습니다! 🙂

2023-01-06 05:42 UTC, inho-98 commented on Diary/Source/Model/NetworkManager.swift
> +            }
추후에 각각의 경우에 대한 에러처리를 추가할 예정이어서 그대로 유지하였습니다..!

2023-01-06 05:43 UTC, FlameYG commented on Diary/Source/Model/Weather/WeatherManager.swift
> +private enum URL {
`URLAddress`로 수정하였습니다! 😃

2023-01-06 05:43 UTC, inho-98 commented on Diary/Source/Model/Weather/WeatherAPI.swift
> +struct WeatherAPI: Decodable {
다른 API를 사용할 수도 있고, 현재 사용한 API내에도 많은 종류의 API가 있는걸 알게 되어서
해당 정보를 나타내는 `CurrentWeatherData`로 수정하였습니다..! 🙂

2023-01-06 05:46 UTC, FlameYG commented on Diary/Source/Controller/DiaryFormViewController.swift
> +                self.weather = weather
STEP3 요구사항에서는 `Weather UI`는 `MainViewController`에서만 `TableViewCell`에 띄워주기 때문에, `DiaryFormViewController`에서는 `UI Refresh` 동작이 필요하지 않다고 생각됩니다...! 🤔

2023-01-06 05:54 UTC, inho-98 commented on Diary/Source/Model/NetworkManager.swift
> +struct NetworkManager {
이 구조체 역시 지난번에 고민했던 대로 인스턴스가 필요하지 않고, 현재 단계에서는 `data`를 가져오는 함수로만 구현하고 사용하고 있어서 `Networkable`이란 프로토콜로 변경하고, `WeatherManager`에 채택하여 사용하도록 수정했습니다!

수정하면서 고민되었던 점은, `WeatherManager`도 현재 코드에서는 프로퍼티를 가지고 있지 않고, 인스턴스가 반드시 필요해 보이진 않아서 역시 프로토콜로 변경하는게 좋을까 싶었습니다. 
그런데 구조체를 프로토콜로 변경하는게 항상 좋은지에 대한 확신이 없어서 고민중에 있습니다🥲

2023-01-08 12:33 UTC, leejun6694 approved these changes
리뷰 내용을 반영하느라 고생 많으셨습니다!
Network 관련 코드는 제가 의도했던 것과는 조금 다른 방향으로 진행되어서, 내일 같이 애기 나눠보시죠~!!

2023-01-08 12:33 UTC, merged