일기장 [STEP 1] 쿼카, Taeangel
yagom-academy/ios-diary pull request #9
Opened 2022-06-16 01:50 UTC by Quokkaaa

@wonhee009 
안녕하세요 라쟈냐 😄 
STEP1에서는 기존에 배웠던 내용들이 많아서 작성할게 많이 없던것같아요 ㅎㅎ
잘 부탁드리겠습니다. 

### 고민한점
**가로 길이가 모호하다는 에러에 대해서**
[공식문서](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/AutolayoutPG/AmbiguousLayouts.html)를 확인해보니 뷰의 위치와 크기를 정해주지않았을때, 동일한 우선순위를 가진 뷰가 존재할때 발생하는것으로 확인하였습니다. 저의 에러같은경우 후자 문제였고
horizontal stackView내에 두개의 UILabel이 존재하는데 이 두 레이블의 길이의 우선도를 정해줌으로써 해결할 수 있었습니다.
`label.setContentCompressionResistancePriority(.required, for: .horizontal)`

**키보드의 동적인 스크롤 설정**
키보드의 높이만큼 contentInset을 올려주도록 설정하는 방식으로 구현이되는데 이에 필요한 contentInset과 contentOffset의 차이점에대해서 간단하게 알아보았습니다.

**tableView를 구현하는 방법에대해서**
UITableViewController를 상속받아서 구현하는 방법 vs UIViewController를 상속받아서 tableView프로퍼티를 만들어 구현하는 방법이 있었습니다.

STEP1 내용으로만 보면 UITableViewController을 상속받아서 구현해도 전혀 무리가 없어보였습니다. 그런데 다음 STEP과 다른 기능들을 추가하는 확장성을 고려해보니 tableView 프로퍼티를 따로 만들어서 사용하는게 유연할것같아 후자로 구현하였습니다

**파일분리**
기존에 MVC패턴으로 view와 controller와 model폴더를 각각 만들어서 파일을 관리했었습니다. 그런데 코드를 수정하게될때 특정 화면을 찾아가서 수정하기에는 번거로움이있었습니다. 그래서 Scene별로 폴더를 구분하여 관리를 해주었습니다.

### 궁금한점

![](https://i.imgur.com/JQ8LhpV.png)

위 사진과 같이 cell이 계단형식으로 나오는 문제가 발생하여 계속 찾아보았는데요 문제가 cell이 겹치는 것이 문제라 생각했습니다 그래서 문제를 해결 하려고 cell안에 폰트를 변경하였는데 문제를 해결한것 같지는 않았습니다. 이렇게 cell이 겹치는 경우 해결할 다른방법이 있을까요?

조언부탁드립니다

2022-06-16 13:40 UTC, wonhee009 requested changes
스텝1 수고하셨습니다 👍 
커밋이 잘 나눠져 있었고, 이슈 만들어서 커밋 메시지에 이슈 태깅도 좋았습니다. (어떤 단위로 이슈들을 쪼갰는지 확인하기 좋았습니다.)

몇몇 코멘트와 질문들 남겨두었으니 확인 부탁드립니다. 🙏 

<img width="30%" alt="image" src="https://user-images.githubusercontent.com/30456206/174072780-a46544e9-c909-495a-ac7d-3b94c5ec9cc7.png">

- 이 친구는 현재 필요한 친구인가요?

<img width="30%" alt="image" src="https://user-images.githubusercontent.com/30456206/174072925-cc9cf3a4-4806-402d-bdac-0bd27adcb481.png">

- 이 친구들도 현재 아무런 값이 없는거로 보이는데요. 필요한 친구들인가요?

- diff에 40개가 넘는 파일들이 잡히는데요. gitignore가 설정되어 있지 않은거 같습니다.

- view hierachy에서 cell이 계단식으로 보이는게 문제라는 말씀이실까요? 시뮬에 돌려봤을 때 화면상으로는 문제 없는거 같아 질문 드립니다.

2022-06-16 13:40 UTC, wonhee009 commented on Diary/Model/PassorManager.swift
> +struct PassorManager {
`PassorManager`는 어떤 의미인가요? (혹시.. ParserManager?)
위의 주석도 구조체와 이름 맞춰주세요 :)

해당 파일이 Model의 하위에 있는게 맞을까요?
Model의 하위에는 어떤 파일이 어울릴까요?
해주는 역할을 보면 좀 더 Util에 가깝지 않을까요?

2022-06-16 13:40 UTC, wonhee009 commented on Diary/MainScene/Controller/MainViewController.swift
> +    self.view.backgroundColor = .systemBackground
`MainView`에서 지정해줘도 되는 값으로 보이는데요.
여기서 지정해주는 이유가 있을까요?
(UI적 요소이고, 이후에 변경될 일이 없는 값이여서 질문 드립니다.)

2022-06-16 13:40 UTC, wonhee009 commented on Diary/MainScene/Controller/MainViewController.swift
> +    let detailVC = WriteViewController()
`detailVC`보다는 `detailViewController`로 풀어서 사용하는건 어떤가요? :)

2022-06-16 13:40 UTC, wonhee009 commented on Diary/MainScene/Controller/MainViewController.swift
> +            as? MainTableViewCell,
여기 줄바꿈이 좀 가독성이 낮은거 같은데 
```swift
) as? MainTableViewCell
```
은 어떤가요?

2022-06-16 13:40 UTC, wonhee009 commented on Diary/Model/Diary.swift
> +  let body: String
`body`보다 좀 더 특성을 나타낼 수 있는 이름 어떤가요?
`description`이나 `subTitle` 같은...?

2022-06-16 13:40 UTC, wonhee009 commented on Diary/MainScene/View/MainView.swift
> +final class MainView: UIView {
`MainView`보다는 좀 더 어떤 역할의 View인지 알 수 있으면 좋을거 같습니다.
`DiaryView`라던지...
(+ MainViewController, MainTableViewCell도 마찬가지입니다.)

2022-06-16 13:40 UTC, wonhee009 commented on Diary/MainScene/View/MainView.swift
> +  }()
현재 MainViewController에서 `MainTableViewCell`, `EmptyTableViewCell`을 register해주고 있는데요.
tableView 생성 시점에 register 불가능한가요?

2022-06-16 13:40 UTC, wonhee009 commented on WriteScene/Controller/WriteViewController.swift
> +}
extension으로 나누는 기준이 있을까요?
`viewWillDisappear` 같은 UI Cycle 메서드도 extension으로 빠져 있어 질문 드립니다.

2022-06-16 13:40 UTC, wonhee009 commented on WriteScene/Controller/WriteViewController.swift
> +  }
`self`를 사용하는 기준이 있을까요?

2022-06-16 13:40 UTC, wonhee009 commented on WriteScene/Controller/WriteViewController.swift
> +  }
`viewDidLoad`에서 Notification을 세팅해주고 `viewWillDisappear`에서 Notification을 해제해주고 있는데요.
`viewDidLoad`와 `viewWillDisappear`는 언제 호출되고 둘의 호출 빈도는 어떤가요?
deinit 시점에 Notification 해제를 해줘야 하지 않나요?

2022-06-16 13:40 UTC, wonhee009 commented on Diary/Utils/Extension/TimeInterval+.swift
> +  }
해당 메서드가 `TimeInterval`의 extension으로 정의한 이유가 있을까요?

만일 "MM월 dd일", "yyyy년 MM월", "yyyy.MM.dd"의 데이터형식이 추가되야 한다면 `TimeInterval`에 무한정으로 추가될거 같은데요.
모든 `TimeInterval` 타입이 해당 데이터 형식의 메서드를 알고 있어야 할까요?

2022-06-16 13:40 UTC, wonhee009 commented on Diary/Model/PassorManager.swift
> +    let diaryData = try? Json.decoder.decode([Diary].self, from: jsonData)
`Json.decoder`가 싱글톤 형식으로 되어 있는데요.
현재 구조상 디코딩은 `PassorManager`를 통할거 같은데요.
```swift
let diaryData = try? JSONDecoder().decode([Diary].self, from: jsonData)
```
로 해도 될거 같은데 싱글톤으로 정의한 이유가 궁금합니다.

2022-06-17 06:02 UTC, Taeangel commented on Diary/Utils/Extension/UIStackView+.swift
> +//  UIStackView+.swift
저희생각은 이미 Extension이라는 폴더안에 존재하는 파일이라 UIStackView+Extension으로하면 Extension이 중복된다 생각해서 Extionsion을 생략했는데 Extension 폴더 안에 있어도 UIStackView+Extension 하는게 좋을까요?

2022-06-17 06:07 UTC, Quokkaaa commented on Diary/Model/PassorManager.swift
> +struct PassorManager {
네이밍에 오탈자가 있었네요 ㅜㅜ 수정했습니다. 👍 

그리고 해당파일이 Model하위에 있는게 맞을지에대해 고민해보았는데 Model은 뼈구조만 잡는 구조라고 보았을때
Utils 에 두는것이 적절하다고 판단하여 옮겨주었습니다.

궁금한점이 현업에서는 Utils폴더를 어떤의미로 두고있나요 ?? 아직 어떤 추상적인 개념인지 잘 와닿지가 않아서요 ㅜㅜ

2022-06-17 06:27 UTC, Taeangel commented on Diary/MainScene/Controller/MainViewController.swift
> +    self.view.backgroundColor = .systemBackground
self.view.backgroundColor = .systemBackground를 MainView에서 지정해주고 컨트롤러에서 지우지 않았네요;;

2022-06-17 06:34 UTC, Quokkaaa commented on Diary/MainScene/Controller/MainViewController.swift
> +    let detailVC = WriteViewController()
detailViewConteoller로 수정하였습니다.

2022-06-17 06:35 UTC, Taeangel commented on Diary/MainScene/Controller/MainViewController.swift
> +            as? MainTableViewCell,
`) as? MainTableViewCell,` 변경하였습니다.

2022-06-17 06:51 UTC, Quokkaaa commented on Diary/Model/Diary.swift
> +  let body: String
description으로 수정하였습니다

2022-06-17 06:55 UTC, Taeangel commented on Diary/MainScene/View/MainView.swift
> +final class MainView: UIView {
MainView는 어떤 뷰인지 알 수 없을것 같아 LIstView로 네이밍을 변경하였습니다. Diary라는 이름은 이 프로젝트 이름이 Diary이기 때문에 중복이 될것같아 ListView로 변경하였습니다.

2022-06-17 07:01 UTC, Quokkaaa commented on Diary/MainScene/View/MainView.swift
> +  }()
가능한것으로 알고있습니다.
그런데 Cell을 등록하는 것은 뷰컨의 역할이라고 생각해서 뷰컨 등록을 해주었는데
@wonhee009  라자냐의 생각은 어떠신가요 ?

2022-06-17 07:09 UTC, Quokkaaa commented on WriteScene/Controller/WriteViewController.swift
> +}
키보드 처럼 굵직한 기능들은 extension으로 빼우는게 가독성이 좋다고 한단하여 작성하고있는데요
UICycle관련메서드는 viewDidLoad아래에 순서에 넣는게 더 자연스럽다고 생각합니다.
위 내용대로 수정하였습니다.

2022-06-17 07:16 UTC, Taeangel commented on WriteScene/Controller/WriteViewController.swift
> +  }
내부프로퍼티를 편하게 파악할수 있도록 대부분적어주었고 함수의 매개변수로 사용할 경우에는 붙여주지 않았습니다.

2022-06-17 09:24 UTC, Taeangel commented on Diary/Utils/Extension/TimeInterval+.swift
> +  }
TimeInterval의 extension할 필요는 없을 것 이라 생각해서 Date extension으로 변경하였습니다.  "MM월 dd일", "yyyy년 MM월", "yyyy.MM.dd" 과 같은 날짜 형식을 타입으로 만들어 파라미터로 받도록 변경하였습니다.

2022-06-17 09:48 UTC, Quokkaaa commented on Diary/Model/PassorManager.swift
> +    let diaryData = try? Json.decoder.decode([Diary].self, from: jsonData)
`let diaryData = try? JSONDecoder().decode([Diary].self, from: jsonData)`
이와 같이 사용하면 JSONDecoder를 할때마다 생성하게되어서 싱글톤으로 한번만 생성하여 계속 사용하기 위해 싱글톤으로 구현하였는데 정확하게 얼만큼의 차이가 있는지 잘 모르겠습니다. 🤔

2022-06-17 12:09 UTC, Quokkaaa commented on WriteScene/Controller/WriteViewController.swift
> +  }
확인해본결과 크게 다르지않았습니다. viewDidLoad, viewWillDisappear, deinit 모두 각 한번씩만 호출되었고 deinit이 가장 마지막에 호출되었습니다.
얼핏보기에는  deinit이나 viewWillDisappear 모두 화면이 사라지기직전에 호출시키는거라서 크게 상관없지않을까 라고 생각했어요!

deinit에 호출해주는게 좋을까요 ??

2022-06-17 12:16 UTC, Quokkaaa commented
@wonhee009 
코멘트 달아주신대로 궁금한점 질문추가로 드리고 전반적인 리펙토링은 완료하였습니다. 😄 

`이 친구들도 현재 아무런 값이 없는거로 보이는데요. 필요한 친구들인가요?`
=> DiaryXCModel파일과 Asset파일은 이번STEP에서는 사용하지않기떄문에 삭제해주었습니다.

`diff에 40개가 넘는 파일들이 잡히는데요. gitignore가 설정되어 있지 않은거 같습니다.`
=> swiftlint추가하면서 생긴 pod 관련된 파일을 gitignore설정 해두었습니다!!

`view hierachy에서 cell이 계단식으로 보이는게 문제라는 말씀이실까요? 시뮬에 돌려봤을 때 화면상으로는 문제 없는거 같아 질문 드립니다.`
=> 네 계단식으로 보이는게 저의가 봤을때는 정상적인지 잘모르겠어서 드린 질문이었습니다! 혹시 이게 문제가 될 부분은 아닐까요 ?

2022-06-18 08:53 UTC, wonhee009 commented on Diary/Utils/Extension/UIStackView+.swift
> +//  UIStackView+.swift
작업 하다 보면 `cmd+space` 눌러서 파일 검색을 자주할 텐데요.
파일명만 보고 어떤 역할을 아는지 알기 어려울거 같습니다.

2022-06-18 09:06 UTC, wonhee009 commented on Diary/Model/PassorManager.swift
> +struct PassorManager {
프로젝트 전반적으로 사용하는 기능들을 유틸에 넣어두고 있습니다:)

2022-06-18 09:54 UTC, wonhee009 commented on WriteScene/Controller/WriteViewController.swift
> +  }
`self`도 의미를 생각하며 사용해야한다고 생각하는데요.

```swift
private let a: Int
private let b: Int

init(a: Int, b: Int) {
   self.a = a
   self.b = b
}
```
여기서는 `self.a`를 통해 전역 프로퍼티임을 명시해주기 위해 사용하고 있고
클로저 내부에서 사용하는 `self` 또한 비슷한 이유죠.

그렇다면 현재 코멘트 남긴 코드에서 `self`를 사용할 필요(전역 프로퍼티 혹은 메서드임을 명시할 필요)가 있을까요?
저는 `self` 없이도 충분히 알 수 있다고 생각합니다 :)

2022-06-18 09:59 UTC, wonhee009 commented on WriteScene/Controller/WriteViewController.swift
> +  }
[ViewController](https://developer.apple.com/documentation/uikit/uiviewcontroller) 생명주기 한 번 보는 것도 좋을거 같습니다:)
`viewWillDisappear`가 언제 불리는지 WriteViewController에서 이동하는 다른 화면이 있다면 어떻게 될지 생각해보면 좋을거 같습니다.
해당 코멘트는 이후 스텝에서 다시 얘기해보도록 해요:)

2022-06-18 10:28 UTC, wonhee009 commented on Diary/MainScene/View/MainView.swift
> +  }()
테이블뷰에서 사용하려고 register 하는거라고 생각해서 View의 역할이라고 생각하는데요.
VC에서는 테이블에 대해서는 최대한 모르는게 좋다고 생각했습니다.

2022-06-18 10:42 UTC, wonhee009 commented on Diary/Model/PassorManager.swift
> +    let diaryData = try? Json.decoder.decode([Diary].self, from: jsonData)
static 메서드는 호출 이후부터는 앱이 종료될 때까지 메모리에서 안 내려가는데요.
해당 메서드 호출 이후에는 `JSONDecoder()`를 생성하면 같이 메모리에서 안 내려간다고 생각했습니다.

2022-06-18 10:43 UTC, wonhee009 commented
하이라키에 대해서는 문제 없다고 생각하는데요.
계단실으로 보이는 정확한 이유는 모르겠으나 셀이 겹친건 아닌거로 보입니다.

2022-06-18 10:43 UTC, wonhee009 approved these changes
수고하셨습니다.
코멘트에 대한 답변 남겨두었으니 확인하시고 다음 스텝에서 마저 반영 혹은 얘기 나누면 좋을거 같습니다:)

2022-06-18 10:44 UTC, merged