일기장 [STEP 1]
yagom-academy/ios-diary pull request #91
Opened 2023-04-25 03:29 UTC by sehoong0429

# 일기장 step1, step1-2 
@havilog 
안녕하세요 하비! 세홍입니다.
step1, step1-2 첫 PR올립니다. 

3주동안 잘 부탁드리겠습니다!!🙇🏻‍♀️

## 구현한 내용 
- homebrew를 이용하여 swiftLint 적용 
- 테이블 뷰를 사용하여 일기장 리스트 화면 구현  
- 작성일자는 사용자의 지역 포맷에 맞게 표현 
- 일기장 상세화면 화면 이동 및 레이아웃 구성
- 일기장 영역 텍스트가 키보드에 가리지 않도록 구현
    1. 처음에는 Notification등록 후 키보드가 사라지거나 나타날때 입력 영역의 아래 여백을 키보드 높이만큼 조정하는 방식으로 구현했었으나
    2. iOS15버전부터는 UIView프로퍼티인 UIKeyboardLayoutGuide 사용하여 UIkeyboardLayoutGuide의 topAnchor를 사용해서 뷰를 업데이트 할 수 있습니다. 최종적으로 iOS15버전으로 수정 후 간단하게 키보드가 올라올때 화면에 대응할 수 있도록 구현했습니다.
    ```swift
    diaryDetailStackView.bottomAnchor.constraint(equalTo: view.keyboardLayoutGuide.topAnchor)
    ```

## 🔗 참고링크
- [Adaptivity and Layout](https://developer.apple.com/design/human-interface-guidelines/foundations/layout/)
- [DateFormatter](https://developer.apple.com/documentation/foundation/dateformatter)
- [UITextView](https://developer.apple.com/documentation/uikit/uitextview)
- [static과 class method, property 효과적으로 사용하기](https://sujinnaljin.medium.com/swift-static과-class-method-property-효과적으로-사용하기-b336311a923c)
- [UITableView의 Separator](https://minzombie.github.io/ios/separator/)
- [TableView 셀 높이 설정](https://hongjeongseob82.medium.com/ios-uikit-tableview-cell-self-sizing-%EC%85%80-%EB%86%92%EC%9D%B4-%EC%84%A4%EC%A0%95-%EC%82%BD%EC%A7%88x100-db30fcec8a2f)
- [키보드가 화면을 가릴 때 해결방법](https://icksw.tistory.com/87)
- [콘솔창 에러메세지](https://www.notion.so/59878c94630e4e43aae4af1529a37cfe) 
- [Your guide to keyboard layout](https://developer.apple.com/videos/play/wwdc2021/10259/)

2023-04-26 01:02 UTC, havilog requested changes
빠른 피알 감사하구 고생하셨어요 세홍~

제목과 내용 레이아웃 안맞는것도 수정해주세요~!

<img width="514" alt="image" src="https://user-images.githubusercontent.com/57659933/234439564-924c1c1b-db94-4532-8cf7-405407f43bfe.png">

2023-04-26 01:02 UTC, havilog commented on Diary/.swiftlint.yml
> +disabled_rules:
야믈파일은 보통 깃에 안올린다고 알고있어요!

2023-04-26 01:02 UTC, havilog commented on Diary/.swiftlint.yml
> +disabled_rules:
요건 개인적인 생각인데,
린트와 컨벤션을 지키는 건 좋은데,
너무 린트에 강박하면 스트레스가 생기더라구요 ㅎㅎ
팀바팀 사바사겠지만, 기본적인 컨벤션은 지키되
사람의 취향은 존중하면서 린팅하는게 좋은거 같아요 ㅎㅎ

2023-04-26 01:02 UTC, havilog commented on Diary/App/AppDelegate.swift
>          // Override point for customization after application launch.
안쓰이는 주석두 지우면 깔끔해질거 같아요

2023-04-26 01:02 UTC, havilog commented on Diary/Controller/DiaryViewController.swift
> +    private lazy var diaryListTableView: UITableView = {
사실 lazy var는 안 쓸 수 있으면 안쓰는게 좋아요

누군가가 나중에 실수로
diaryListTableView = .init()
과 같이 프로퍼티 자체를 바뀌버릴 수도 있어서요

datasource와 delegate를 설정하는 부분을 viewdidload로 빼면 어떨까요?

2023-04-26 01:02 UTC, havilog commented on Diary/Controller/DiaryViewController.swift
> +            action: #selector(tappedCreateDiary)
어떤 것을 탭했는지에 대한 주어가 빠져있어요
createDiaryButtonTapped와 같이 component명을 명시해주면 더 읽기 좋을거 같아요

2023-04-26 01:02 UTC, havilog commented on Diary/Controller/DiaryViewController.swift
> +        cell.configureCellData(diaryItem: diaryItems[indexPath.row])
diaryItems배열에 바로 인덱스로 접근하면 크래시가 발생할 수 있어요.
safe subscript를 사용하는 습관을 기르는게 좋아보여요

2023-04-26 01:02 UTC, havilog commented on Diary/Model/Diary.swift
> +struct Diary: Decodable {
Decodable인데 코딩키가 없네요!
cmd클릭 하면 이런 기가막힌 기능이 있어요
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/57659933/234437912-00c49407-d170-498a-bda9-c4f069ab3d45.png">

2023-04-26 01:02 UTC, havilog commented on Diary/Model/Diary.swift
> +extension Diary {
스태틱으로 목객체를 만들어준거 좋아보여요 ㅎㅎ 👍

2023-04-26 01:02 UTC, havilog commented on Diary/Model/Namespace.swift
> +enum Namespace {
보통 네임스페이스는 이런식으로는 사용하지 않는거 같아요

뷰컨에 한정된 상수는 뷰컨에 두고,
plusIcon이나 sample은 (개인적으로) 굳이 안잡아줘도 괜찬을거 같아요

보통 네임스페이스라는 단어는

홈, 세팅, 계정 등이 있을 때

HomeNameSpace안에
Home.Model.Something
Home.API.requestSomething
이런식으로 잡아주려고 쓰는거 같아요
(요것도 팀바팀)

2023-04-26 01:02 UTC, havilog commented on Diary/Util/DateFormatter .swift
> +enum Formatter {
Formatter라는 네이밍은 어떤 걸 어떻게 포맷하는지 유추하기 힘들어요.
다른 개발자가 이건 이 역할을 하기 위해 만들었구나!를 잘 알 수 있는 네이밍을 고민할 필요가 있을거 같다는 생각이 드네요 ㅎㅎ

2023-04-26 01:02 UTC, havilog commented on Diary/Util/JsonConverter.swift
> +enum JsonConverter {
이런 객체를 만드는 역할 분리는 좋습니다 👍 
다만 이 객체가 앱 전역에서 접근할 필요가 있는지는 고민해봐야할 거 같아요.
한 객체나, 특정 기능에서만 쓰인다면 그쪽에서만 접근 가능하도록 접근제어를 해보는걸 고민해보시면 좋을 거 같아요

2023-04-26 01:02 UTC, havilog commented on Diary/Util/JsonConverter.swift
> +        guard let result = try? jsonDecoder.decode([Diary].self, from: dataAsset.data) else { return nil }
nil이 아니라 throw시키고, 오류가 났을 때 핸들링 하는 방법은 고려해보셨을까요??

2023-04-26 01:02 UTC, havilog commented on Diary/View/DiaryTableViewCell.swift
> +    static let identifier = "DiaryTableViewCell"
셀 같은 경우는 프로토콜로 모든 UITableViewCell 에 identifier를 다는 꼼수가 있는데 찾아보시는거 추천

2023-04-26 01:02 UTC, havilog commented on Diary/View/DiaryTableViewCell.swift
> +    func configureCellData(diaryItem: Diary) {
```suggestion
    func configure(with diary: Diary) {
```

2023-04-26 01:02 UTC, havilog commented on Diary/View/DiaryTableViewCell.swift
> +        dateLabel.text = Formatter.changeToString(from: diaryItem.createdAt)
아까 코멘트에서 말했듯이 이런 스태틱한 함수들이 사용할 때는 편한데,
유지보수가 테스터빌리티가 떨어지긴 해요

2023-04-26 01:02 UTC, havilog commented on DiaryTests/DiaryTests.swift
> +}
테스트는 기능 다 되고 볼게요
이건 제 개인적인 생각인데, TDD를 할게 아니면 지금시점에서 테스트는 의미 없다고 생각해서 ㅎㅎ..

2023-04-26 05:05 UTC, sehoong0429 commented
> 제목과 내용 레이아웃 안맞는것도 수정해주세요~!

해당부분은 contentInset을 zero로 설정하여 내부여백을 없애는 방식을 적용해봤으나 내부 여백을 동일하게 설정하는데 더 일관성있는 방식을 찾아서 titleField를 사용하지않고 textView를 사용하여 레이아웃을 맞춰주었습니다. 
하지만 이후에는 제목의 길이가 body처럼 길어지는걸 대비해서 제목의 글자수를 제한하는 등의 기능이 필요할거라고 생각됩니다. 이부분은 조금 더 생각하고 추가적으로 수정해보겠습니다. [5b39c58](https://github.com/yagom-academy/ios-diary/pull/91/commits/5b39c584c2d30e9d398b623f5b78dce543f9e459)

2023-04-26 05:11 UTC, sehoong0429 commented on Diary/.swiftlint.yml
> +disabled_rules:
감사합니다! 처음알았던 부분입니다.
해당 파일은 프로젝트내의 설정을 저장하고 있기때문에 공유해야하는 파일이라고 생각했는데, 
팀원들과 공유가 되지 않는다면 일관성을 유지하면서 관리를 어떻게 할 수 있을까요? 
각자가 개별적으로 파일을 들고 관리하게 된다면 오히려 효율적이지 못할 것 같아서요!

2023-04-26 05:11 UTC, sehoong0429 commented on Diary/.swiftlint.yml
> +disabled_rules:
참고하겠습니다! 
간단하게 정말 지켜줘야 할 기본적인 컨벤션을 함께 논의해서 사용할 수 있도록 하겠습니다!

2023-04-26 05:15 UTC, sehoong0429 commented on Diary/App/AppDelegate.swift
>          // Override point for customization after application launch.
[8083579](https://github.com/yagom-academy/ios-diary/pull/91/commits/808357957d8b35e35acaa6540e2158ecd1f4264f) 불필요한 주석은 삭제해주었습니다!

2023-04-26 05:18 UTC, sehoong0429 commented on Diary/Controller/DiaryViewController.swift
> +    private lazy var diaryListTableView: UITableView = {
[0ac74b7](https://github.com/yagom-academy/ios-diary/pull/91/commits/0ac74b700bf18111bfb7bf30396109a71384a4fa) 
조언 해주신대로 lazy var를 사용하지 않고 setupTableView 함수를 만들어서 해당 부분 분리해주었습니다!

2023-04-26 05:21 UTC, sehoong0429 commented on Diary/Controller/DiaryViewController.swift
> +            action: #selector(tappedCreateDiary)
[e4150c7](https://github.com/yagom-academy/ios-diary/pull/91/commits/e4150c7d2d59f884ae06d4c3cfcc5585a944dd8e)
추천해주신대로 명확하게 변경해주었습니다! 감사합니다

2023-04-26 05:39 UTC, sehoong0429 commented on Diary/Controller/DiaryViewController.swift
> +        cell.configureCellData(diaryItem: diaryItems[indexPath.row])
말씀해주신 부분을 https://stackoverflow.com/questions/25329186/safe-bounds-checked-array-lookup-in-swift-through-optional-bindings/30593673#30593673 자료를 참고하여, [42746be](https://github.com/yagom-academy/ios-diary/pull/91/commits/42746be9f81f007a9a75185614950951ed68d994) 수정해주었습니다. 
extension Array를 만들어서 안전하게 배열에 접근할 수 있도록 해주었습니다!

2023-04-26 05:45 UTC, sehoong0429 commented on Diary/Model/Diary.swift
> +struct Diary: Decodable {
오 완전 신기하네요 ㅎㅎ 처음 봤어요! 
```swift
    private enum CodingKeys: String, CodingKey {
        case title
        case body
        case createdAt = "created_at"
    }
```
이렇게 만들어줄수도 있지만  jsonConverter에서 아래와 같이 Snake-case를 Camel-case로 변환해주고 있는데 따로 codingKey를 작성해주어야하는지 궁금합니다! 

```swift
jsonDecoder.keyDecodingStrategy = .convertFromSnakeCase 
```

2023-04-26 05:54 UTC, sehoong0429 commented on Diary/Model/Namespace.swift
> +enum Namespace {
알려주셔서 감사합니다! namespace는 삭제하고 각 파일에 선언해주었습니다! [26ee61d](https://github.com/yagom-academy/ios-diary/pull/91/commits/26ee61d3d54a6f1ad3b73caf25c92552e793cc7f)

2023-04-26 05:58 UTC, sehoong0429 commented on Diary/Util/DateFormatter .swift
> +enum Formatter {
[ed4ddb4](https://github.com/yagom-academy/ios-diary/pull/91/commits/ed4ddb4dc9a81f00ecdf03e97358810d84107428)
정말 맞는 말인 것 같습니다ㅜㅜ 조금 더 생각해서 네이밍해보도록 하겠습니다!

2023-04-26 06:02 UTC, sehoong0429 commented on Diary/Util/JsonConverter.swift
> +enum JsonConverter {
감사합니다. 
그러면 아래 코드를 DiarylistViewController에 넣는다면 괜찮을까요?
```swift
private enum JsonConverter {
        
        private static let jsonDecoder = JSONDecoder()
        
        static func decode() -> [Diary]? {
            jsonDecoder.keyDecodingStrategy = .convertFromSnakeCase
            guard let dataAsset = NSDataAsset(name: "sample") else { return nil }
            guard let result = try? jsonDecoder.decode([Diary].self, from: dataAsset.data) else { return nil }
            
            return result
        }
        
    }
```

2023-04-26 06:33 UTC, sehoong0429 commented on Diary/Util/JsonConverter.swift
> +        guard let result = try? jsonDecoder.decode([Diary].self, from: dataAsset.data) else { return nil }
[bed83ac](https://github.com/yagom-academy/ios-diary/pull/91/commits/bed83ac62ef7438358c7a3e80900fe5b6e7991ae)
에러타입을 만들고, 에러가 발생했을때 콘솔창에 print, 유저에게는 alert를 띄워서 에러발생을 알릴 수 있도록 만들어주었습니다. 에러처리를 잊고있었는데 감사합니다!

2023-04-26 07:00 UTC, sehoong0429 commented on Diary/View/DiaryTableViewCell.swift
> +    static let identifier = "DiaryTableViewCell"
[f7957d6](https://github.com/yagom-academy/ios-diary/pull/91/commits/f7957d6b0b24d897c53db329947e0f03d4ca57be)
 아래 자료를 참고하여 구현했는데 .이런 꼼수가 맞을까요? ㅠ 

https://swieeft.github.io/2021/01/21/SimpleToUseTableViewCell.html

2023-04-26 07:03 UTC, sehoong0429 commented on Diary/View/DiaryTableViewCell.swift
> +    func configureCellData(diaryItem: Diary) {
[8938109](https://github.com/yagom-academy/ios-diary/pull/91/commits/8938109ddc61d0c12bb57cb31d612147cba3ae93)
알려주신부분 수정했습니다!

2023-04-26 07:04 UTC, sehoong0429 commented on DiaryTests/DiaryTests.swift
> +}
ㅎㅎ감사합니다! 참고해서 구현하겠습니다!

2023-04-26 09:35 UTC, sehoong0429 commented on Diary/View/DiaryTableViewCell.swift
> +        dateLabel.text = Formatter.changeToString(from: diaryItem.createdAt)
구조체로 사용하는게 더 좋을까요? 
```swift
struct DateToStringFormatter {
    
    private let dateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateStyle = .long
        formatter.locale = Locale.current
        formatter.timeZone = TimeZone.current
        return formatter
    }()
    
    func changeToString(from timeInterval: TimeInterval) -> String {
        let date = Date(timeIntervalSince1970: timeInterval)
        return dateFormatter.string(from: date)
    }

}
```

2023-04-26 13:32 UTC, havilog commented on Diary/.swiftlint.yml
> +disabled_rules:
제가 있었던 회사들은 전부 린트를 안쓰고 개발자의 개성을 존중하는 편이라 정확한건 잘 모르겠지만,
로컬에서 관리해준다고 알고있어요!
저도 주워들은거라 구글링이 더 빠를거 같아요 ㅎㅎ

2023-04-26 13:34 UTC, havilog commented on Diary/Controller/DiaryViewController.swift
> +        cell.configureCellData(diaryItem: diaryItems[indexPath.row])
여기까지는 좀 오바일 수 있지만.. safe에서 꺼내오지 못하거나, idenfier를 못찾았을 때 에러 상황에서 보여줄만한 내용을 고민해보는 것도 좋을거 같아요!
수정까지는 안하셔도 될거 같고 고민만 해보시면 좋을 듯 합니다 ㅎㅎ

2023-04-26 13:35 UTC, havilog commented on Diary/Model/Diary.swift
> +struct Diary: Decodable {
안해줘도 괜찮을거 같아요~

2023-04-26 13:36 UTC, havilog commented on Diary/Model/Namespace.swift
> +enum Namespace {
틀린건 아닌데, 보통 저런 상수들은 static으로 많이 사용하는 거 같아요!
```swift
private enum Constant {
    static let something: String = ""
    // ...
}
```

2023-04-26 13:38 UTC, havilog commented on Diary/Util/JsonConverter.swift
> +enum JsonConverter {
이건 정답은 없는 부분인데, 특정 피쳐에서만 사용한다면 그 피쳐에만 국한되게 사용할 수도 있고,
범용성이 크다면 그냥 인터널로 써도되고,
특장 파일에서만 쓴다면 객체를 굳이 안만들고 fileprivate으로 써도 괜찮을거 같아요.
포인트는 해당 역할이 어디까지 일지 고민하고, 그에 맞는 접근 제어를 했느냐가 중요한거 같습니다

2023-04-26 13:39 UTC, havilog commented on Diary/Util/JsonConverter.swift
> +        guard let result = try? jsonDecoder.decode([Diary].self, from: dataAsset.data) else { return nil }
알고 계실지 모르겠지만,
print함수는 프로덕션 코드에는 포함되면 안될거 같아요.
#if Debug로 전처리를 해주는게 좋을거 같습니다

2023-04-26 13:41 UTC, havilog commented on Diary/View/DiaryTableViewCell.swift
> +    static let identifier = "DiaryTableViewCell"
요약하자면 요런거에요
<img width="694" alt="image" src="https://user-images.githubusercontent.com/57659933/234594030-76b092c2-c17c-475d-9256-0367b96f5527.png">

2023-04-26 13:42 UTC, havilog commented on Diary/View/DiaryTableViewCell.swift
> +        dateLabel.text = Formatter.changeToString(from: diaryItem.createdAt)
구조체의 문제라기보다는 의존성의 문제라서요
Dependency injection에 대해 공부해보시면 좋을듯 합니다 ㅎㅎ
부끄럽지만 제 블로그.. 를 읽어보시고 키워드 찾고 그 키워드로 다시 검색해보세영
https://velog.io/@hansangjin96/Swinject-%EC%9D%98%EC%A1%B4%EC%84%B1-%EA%B4%80%EB%A6%AC%EB%9E%80

2023-04-27 01:11 UTC, sehoong0429 commented on Diary/View/DiaryTableViewCell.swift
> +    static let identifier = "DiaryTableViewCell"
[4e2f40d](https://github.com/yagom-academy/ios-diary/pull/91/commits/4e2f40d4f82302d0b8acfe9efbc88bc6c20f0aac)
정말 감사합니다 기존코드에서 보완해주었습니다!

2023-04-28 06:09 UTC, sehoong0429 commented on Diary/Model/Namespace.swift
> +enum Namespace {
[ffc139c](https://github.com/yagom-academy/ios-diary/pull/91/commits/ffc139c898e9917397a0afdfd90d310569a2bc4c) 수정해주었습니다! 감사합니다 ㅎㅎ

2023-04-28 06:10 UTC, sehoong0429 commented on Diary/Util/JsonConverter.swift
> +enum JsonConverter {
감사합니다. 참고해서 구현해보도록 하겠습니다.

2023-04-28 08:25 UTC, sehoong0429 commented on Diary/View/DiaryTableViewCell.swift
> +        dateLabel.text = Formatter.changeToString(from: diaryItem.createdAt)
어떤 부분이 의존성 문제가 생긴다고 하시는 건지 이해가 잘 가지 않습니다.
만약에 DateFormatter를 주입받으라고 하시는거라면, DateFormatter는 Foundation에서 기본적으로 제공해주는 클래스로 테스트가 불필요하다고 생각합니다.

2023-04-30 12:32 UTC, merged