일기장 [STEP 1] 혜모리, kokkilE
yagom-academy/ios-diary pull request #94
Opened 2023-04-25 13:19 UTC by kokkilE

@1Consumption

안녕하세요 올라프! 코낄이, 혜모리 인사드립니다. 🙇🏻‍♂️🙇🏻‍♀️
3주간 리뷰 잘 부탁드리겠습니다. :smile: 

## 고민했던 점

### 1️⃣ 키보드가 편집중인 텍스트를 가리지 않도록 처리
키보드가 나타날 때 편집중인 텍스트를 가리지 않도록 하기 위해 두 가지 방법을 찾아 고려하였습니다.
- 키보드가 나타날 때 `textView`의 오토레이아웃을 변경하는 방법으로 구현
- 키보드가 나타날 때 `textView.contentInset`을 변경하는 방법으로 구현

두 방법 모두 Notification을 활용하여 구현하는 방법을 고려하였고 약간의 딜레이가 느껴졌습니다.
다만 오토레이아웃을 변경하는 방법으로 구현할 경우, 다음과 같이 딜레이 시간동안 키보드가 내려감에도 채워지지 않는 레이아웃이 어색하게 느껴졌습니다.

<img src="https://i.imgur.com/WKsu9Hb.gif" width=200>

<br>

따라서 상대적으로 자연스럽다고 생각되는 `textView.contentInset`을 변경하는 방법으로 구현하였습니다.

### 2️⃣ Attributed String 사용

각 Table View Cell에 2번째 줄에는 작성일자와 내용이 들어가는데 예시로 제공된 화면에서 날짜와 내용의 폰트 크기가 달랐습니다.
따로 두 개의 Label을 둘지, Attributed String을 사용하여 하나의 Label에서 폰트 크기를 다르게 줄지 고민해 보았습니다.
프로젝트 부가 경험에 포함되어있고 Contents의 데이터를 단순히 보여주기만 하는 역할을 하고 있어 하나의 Label에서 보여주는 것으로 결정하였습니다.

``` swift
fileprivate extension UILabel {
    func applyAttribute(targetString: String) {
        guard let fullText = text else { return }
        
        let attributedString = NSMutableAttributedString(string: fullText)
        let range = (fullText as NSString).range(of: targetString)

        attributedString.addAttribute(.font,
                                      value: UIFont.preferredFont(forTextStyle: .body),
                                      range: range)
        attributedText = attributedString
    }
}
```

UILabel의 extension으로 구현해 보았는데 우선 해당 부분에만 적용될 기능이라 판단해 `ContentsTableViewCell` 파일에 두었습니다.

### 3️⃣ 작성일자 형식 변경

사용자의 언어에 따라 작성일자의 형식이 다르게 보이도록 적용해 보았습니다.
아이폰 단말기 설정의 선호하는 언어를 `.preferredLanguages`로 불러올 수 있었습니다.

``` swift
extension Date {
    func translateLocalizedFormat() -> String {
        let formatter = DateFormatter()
        
        formatter.locale = Locale(identifier: Locale.preferredLanguages.first ?? Locale.current.identifier)
        formatter.dateStyle = .long
        
        return formatter.string(from: self)
    }
}
```

2023-04-25 15:07 UTC, 1Consumption requested changes
고생하셨습니다.
스텝이 작아 별 다른 코멘트는 없습니다.

2023-04-25 15:07 UTC, 1Consumption commented on Diary/Application/AppDelegate.swift
> +class AppDelegate: UIResponder, UIApplicationDelegate {
final을 붙여주세요.

2023-04-25 15:07 UTC, 1Consumption commented on Diary/Application/AppDelegate.swift
> +    }
CoreData가 왜 AppDelegate에 있나요? 이유가 있을까요?
또한 CoreData에 대한 요구사항은 없는 것으로 아는데... 추가한 이유가 있을까요?

2023-04-25 15:07 UTC, 1Consumption commented on Diary/Application/AppDelegate.swift
> +                fatalError("Unresolved error \(nserror), \(nserror.userInfo)")
error가 발생하면 앱이 죽는데, 의도한 바가 맞을까요?
어떠한 상황에도 앱은 죽으면 안됩니다.

2023-04-25 15:07 UTC, 1Consumption commented on Diary/Application/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
이 코드는 어떤 역할을 하나요? 설명해주시겠어요?

2023-04-25 15:07 UTC, 1Consumption commented on Diary/Controller/DiaryDetailViewController.swift
> +    }
override method인데 super를 호출하지 않았네요.

2023-04-25 15:07 UTC, 1Consumption commented on Diary/Controller/DiaryDetailViewController.swift
> +    }
이 동작을 수행하는 이유가 있을까요?

2023-04-25 15:07 UTC, 1Consumption commented on Diary/Controller/DiaryDetailViewController.swift
> +    }
https://developer.apple.com/documentation/uikit/keyboards_and_input/adjusting_your_layout_with_keyboard_layout_guide
이 아티클을 참고해보세요.

2023-04-25 15:07 UTC, 1Consumption commented on Diary/Controller/DiaryDetailViewController.swift
> +            textView.text = .none
none 보다는 nil이 더 명확할듯합니다.

2023-04-25 15:07 UTC, 1Consumption commented on Diary/Controller/DiaryListViewController.swift
> +    }
이 정보들은 view에서 알 필요가 없을 것 같습니다.
이 동작을 다른 객체로 분리해서 view가 해당 객체를 호출하도록 바꾸면 어떨까요?

2023-04-25 15:07 UTC, 1Consumption commented on Diary/Controller/DiaryListViewController.swift
> +            print(error.localizedDescription)
print는 좋은 에러처리가 아닙니다. 사용자가 알 수 있는 방법을 고려해보세요.

2023-04-25 15:07 UTC, 1Consumption commented on Diary/View/ContentsTableViewCell.swift
> +fileprivate extension UILabel {
fileprivate과 private은 어떻게 다른가요? private으로 바꿔도 빌드가 되나요? 된다면 왜 그럴까요?

2023-04-26 07:42 UTC, hyemory commented on Diary/Application/AppDelegate.swift
> +class AppDelegate: UIResponder, UIApplicationDelegate {
`AppDelegate`, `SceneDelegate`에 final 키워드 추가하였습니다!

2023-04-26 07:43 UTC, kokkilE commented on Diary/Application/AppDelegate.swift
> +    }
해당 코드는 프로젝트 생성 시 Core Data 사용 프로젝트로 생성하여 자동생성된 코드라고 생각됩니다.
이번 스텝에서는 CoreData에 대한 요구사항이 없지만, 추후 CoreData를 사용하게 될 것이라 생각해서 해당 코드를 삭제하지 않았습니다!

2023-04-26 07:45 UTC, hyemory commented on Diary/Controller/DiaryDetailViewController.swift
> +    }
해당 부분 KeyBoard 관련 기능을 추천해주신 [아티클](https://developer.apple.com/documentation/uikit/keyboards_and_input/adjusting_your_layout_with_keyboard_layout_guide) 기준으로 수정하여 현재는 notification을 삭제하였습니다.
이후 override 시 super 호출하는 부분 잘 체크하겠습니다.

2023-04-26 07:47 UTC, hyemory commented on Diary/Controller/DiaryDetailViewController.swift
> +    }
버전 타겟을 iOS 15로 올려 수정해 보았습니다. 감사합니다!
f6369c3c20099cb1a6bc515294c8bfddaf199a0a

``` swift
// ...
view.keyboardLayoutGuide.followsUndockedKeyboard = true

NSLayoutConstraint.activate([
    view.keyboardLayoutGuide.topAnchor.constraint(equalTo: textView.bottomAnchor),
    
    // ...
    textView.bottomAnchor.constraint(equalTo: view.keyboardLayoutGuide.topAnchor)
])
```

2023-04-26 07:48 UTC, hyemory commented on Diary/Controller/DiaryListViewController.swift
> +    }
`DecodeManager` 타입에서 디코드할 수 있도록 분리해 보았습니다.
411eb4705c988096dc4f75562cddddd162def05e

2023-04-26 07:54 UTC, hyemory commented on Diary/View/ContentsTableViewCell.swift
> +fileprivate extension UILabel {
`fileprivate`는 같은 소스파일 내에서, `private`는 같은 scope 내에서 접근이 가능한 제어자입니다.
ContentsTableViewCell 타입과 UILabel extension이 같은 scope에 있어 private로 변경해도 문제없이 빌드되었습니다. 감사합니다.

2023-04-26 07:55 UTC, hyemory commented on Diary/Application/AppDelegate.swift
> +                fatalError("Unresolved error \(nserror), \(nserror.userInfo)")
추후 스텝에서 core data를 다루는 부분이 있다고 하는데, 그 부분을 구현할 때 core data 에러처리를 함께 구현해보겠습니다!

2023-04-26 07:57 UTC, kokkilE commented on Diary/Application/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
`UIWindow`는 VC를 포함한 View들을 담는 객체입니다.

- `makeKeyAndVisible`는 window를 보여주고, 해당 `window`를 key window로 만듭니다.
- key window는 키보드 이벤트나 각종 non-touch-related event들을 수신하는 window이고, 앱 내에서 하나의 key window만 존재할 수 있습니다.

2023-04-26 07:59 UTC, kokkilE commented on Diary/Controller/DiaryDetailViewController.swift
> +            textView.text = .none
의견 반영하여 `nil`로 수정하였습니다. 😄

2023-04-26 08:00 UTC, kokkilE commented on Diary/Controller/DiaryListViewController.swift
> +            print(error.localizedDescription)
`AlertManager` 객체를 구현하고, 에러가 발생했을 때 사용자가 알 수 있도록 Alert 처리 하였습니다.

2023-04-26 08:05 UTC, kokkilE commented on Diary/Controller/DiaryDetailViewController.swift
> +    }
removeObserver는 추가된 Observer를 제거하여 더 이상 필요하지 않은 알림 수신을 방지할 수 있어 메모리 누수를 예방할 수 있습니다.
그러나 앱이 iOS 9.0 이상이면 해당 동작을 수행하지 않아도 된다고 합니다.
[removeObserver(_:)](https://developer.apple.com/documentation/foundation/notificationcenter/1413994-removeobserver)
현재는 해당 코드 삭제되었습니다.

2023-04-27 01:10 UTC, 1Consumption commented on Diary/Application/AppDelegate.swift
> +    }
자동생성이 되었더라도 커밋한 사람은 여러분입니다. 이유가 있으면 좋겠습니다. 여기 있을 이유가 없다면 여기 있으면 안되겠죠.

또한 아직 사용하지 않는데 나중에 사용할 것 같다고 추가하는 것은 좋지않습니다. 필요할 때 추가해주세요.

2023-04-27 01:11 UTC, 1Consumption commented on Diary/Application/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
UIWindow의 역할을 물어본게 아니라 코드의 역할을 물어본거였습니다.

2023-04-27 01:12 UTC, 1Consumption commented on Diary/Controller/DiaryDetailViewController.swift
> +    }
removeObserver의 기능이 아니라 이 코드를 작성하게된 배경이 궁금한거였습니다.

2023-04-27 01:16 UTC, 1Consumption approved these changes
고생하셨습니다. 기존 코멘트에 달아주신 의견에도 코멘트를 달았어요.

그리고 하나의 커밋이 하나의 역할만 하고있지는 않네요. 하나의 역할만 하도록 신경써주세요.

2023-04-27 01:16 UTC, 1Consumption commented on Diary/Model/DiaryError.swift
> +
LocalizedError를 활용해보세요.

2023-04-27 01:16 UTC, merged