일기장 [STEP 1] kaki, 레옹아범
yagom-academy/ios-diary pull request #97
Opened 2023-04-26 06:26 UTC by kak1x

# 일기장 [STEP 1] kaki, 레옹아범
@havilog
안녕하세요 하비! kaki, 레옹아범 입니다🙂
앞으로 3주동안 진행될 일기장 프로젝트 리뷰 잘 부탁드리겠습니다🙇🏻

## 구현내용
### 리스트 화면 구현
- 낮은 버전에서도 사용할 수 있도록 `UICollectionLayoutListConfiguration`를 활용하지 않고 기존의  `TableView`를 사용하여 화면을 구현해주었습니다.

### 키보드에 `Done` 버튼 추가
- TextView에서 키보드를 내리는 기능을 추가하기 위해 `Done` 버튼을 추가하여 구현해주었습니다.
- TextView의 Extension으로 Done 버튼을 추가할 수 있게 하였고, 이를 추가하는 곳에서 `endEditing` 기능을 버튼과 연결해주었습니다.

### 키보드의 Frame을 통해 TextView 이동시키기
* keyboard가 올라오는 것을 확인하기 위해 `UIResponder`의 프로퍼티인 `keyboardWillShowNotification` Notification Name을 사용하였습니다.
* 해당 `Notification`은 `userInfo`딕셔너리로 키보드의 프레임을 CGRect를 포함하는 NSValue로 보내주기 때문에 guard문을 통해 곧바로 CGRect로 타입캐스팅 하였습니다.
* [KeyboardWillShowNotification](https://developer.apple.com/documentation/uikit/uiresponder/1621576-keyboardwillshownotification)을 참조한 결과 키보드의 현재 프레임이 스플릿 뷰와 같은 상태에서 일치하지 않는 경우가 있으므로 현재 뷰에서 `convert`를 사용하여 지금 화면 프레임에 맞도록 다시 설정해주었습니다.
* 최종적으로 받아온 키보드의 높이를 `textView`의 `contentInset.bottom`에 부여하여 현재 화면에 맞도록 구현하였습니다.

2023-04-26 14:07 UTC, havilog requested changes
두 분 모두 수고하셨습니다~

댓글 단 부분 생각, 수정해주시고,
수정된 부분은 일본 갔다 와서 다음 주 월요일에 볼게요~
스탭2는 이 수정 후 이 브랜치 기반으로 파서 작업하시면 될 듯 합니다~

2023-04-26 14:07 UTC, havilog commented on .swiftlint.yml
> +disabled_rules: # Default Rules에서 비활성화할 규칙
정확하게 왜때문인지는 기억안나는데.. 제가 공부할 때는 야믈파일은 깃에 안올리는게 좋다는걸 본거 같은데 한 번 검색해보시면 좋을 거 같아요!

2023-04-26 14:07 UTC, havilog commented on Diary/Controller/DetailViewController.swift
> +    private var textView: UITextView = {
이 친구가 variable인 이유가 있나요??

2023-04-26 14:07 UTC, havilog commented on Diary/Controller/DetailViewController.swift
> +    private var textView: UITextView = {
어떤 역할을 하는 textView인지에 대한 프리픽스가 있으면 읽기 더 좋을 것 같아요

2023-04-26 14:07 UTC, havilog commented on Diary/Controller/DetailViewController.swift
> +    private var diaryItem: DiaryModel?
diaryItem은 반드시 옵셔널이어야할 지 고민해보셨을까요?
일기가 없다면, 새 일기를 만드는 방법은 고민해보셨을 지 궁금해요

2023-04-26 14:07 UTC, havilog commented on Diary/Controller/DetailViewController.swift
> +    private var textView: UITextView = {
요구사항에 제목을 적는 뷰가 하나 더 있는거로 봤는데 확인해주시면 좋을거 같아요

2023-04-26 14:07 UTC, havilog commented on Diary/Controller/DetailViewController.swift
> +    }
Notification을 등록하는 로직을 viewDidAppear시점으로 잡으신 이유가 궁금합니다. viewDidAppear는 언제 언제 불릴까요?

2023-04-26 14:07 UTC, havilog commented on Diary/Controller/DetailViewController.swift
> +        textView.scrollIndicatorInsets = textView.contentInset
keyboardlayoutguide라는게 있는데 혹시 알고 계실까요?

2023-04-26 14:07 UTC, havilog commented on Diary/Controller/DetailViewController.swift
> +    @objc private func tapDone(sender: Any) {
```suggestion
    @objc private func doneButtonTapped(sender: Any) {
```

2023-04-26 14:07 UTC, havilog commented on Diary/Controller/DiaryViewController.swift
> +    private var tableView: UITableView = UITableView()
요 아이도 variable일 필요는 없을 것 같아요

2023-04-26 14:07 UTC, havilog commented on Diary/Controller/DiaryViewController.swift
> +        view.backgroundColor = .systemBackground
UI를 configure해주는 함수 하나로 빼도 좋을 것 같아요

2023-04-26 14:07 UTC, havilog commented on Diary/Controller/DiaryViewController.swift
> +    }
유저에게 어떻게 알려줄지 고민해보셨는지 궁금합니다~

2023-04-26 14:07 UTC, havilog commented on Diary/Controller/DiaryViewController.swift
> +    private func pushDetailViewController(_ item: DiaryModel?) {
```suggestion
    private func pushDiaryDetailViewController(with diary: Diary?) {
```
로 쓰면 읽기 더 명확해질 거 같아요

2023-04-26 14:07 UTC, havilog commented on Diary/Etc/ArrayExtension.swift
> +}
LGTM 👍

2023-04-26 14:07 UTC, havilog commented on Diary/Etc/Identifying.swift
> +protocol Identifying {
```suggestion
protocol ReuseIdentifiable {
```
요건 취향이니 무시하셔도 됩니다ㅎ

2023-04-26 14:07 UTC, havilog commented on Diary/Etc/TextViewExtension.swift
> +extension UITextView {
이런 범용적인 extension을 만들 때에는 과연 정말 다들 이 extension을 쓰고, 모든 텍스트 뷰에 필요할지에 대한 고민이 필요해요.
그렇지 않으면 다른 개발자들이 이 코드의 존재를 몰라 레거시가 될 확률이 높고, 해당 파일에서만 쓴다면 fileprivate으로 접근제어를 할 수도 있어요

2023-04-26 14:07 UTC, havilog commented on Diary/Model/DiaryModel.swift
> +    var date: Int
이 아이들이 변경될 일이 있는지 고민해보시고 variable로 선언하셨는지 궁금합니다.

2023-04-26 14:07 UTC, havilog commented on Diary/Model/DiaryModel.swift
> +    enum CodingKeys: String, CodingKey {
```suggestion
    private enum CodingKeys: String, CodingKey {
```

2023-04-26 14:07 UTC, havilog commented on Diary/View/DiaryInfoTableViewCell.swift
> +
prepareForReuse가 없는데,
해당 함수의 역활과
왜 필요한지 설명해주시면 좋을 것 같습니다.

2023-04-26 14:07 UTC, havilog commented on Diary/View/DiaryInfoTableViewCell.swift
> +        stackView.spacing = 5
stackView에 setCustomSpacing이라는 함수가 있는거 알고 계신지 궁금해요~
또한 그냥 stackView와 mainStackView라는 변수명은 이게 무슨 스택뷰인지 유추하기가 힘드네요

2023-04-26 14:07 UTC, havilog commented on Diary/Model/DiaryModel.swift
> +struct DiaryModel: Decodable {
보통 모델 뒤에 모델이라는 suffix는 잘 안쓰는거 같아요

2023-04-27 05:27 UTC, kak1x commented on Diary/Controller/DetailViewController.swift
> +    private var textView: UITextView = {
요구사항에는 따로 제목을 적는 뷰가 있어야 한다는 말이 없어서 구현하지 않았습니다.
title과 body를 따로 구현해주게 되면, 스크롤을 위해 스크롤뷰를 추가해주고 레이아웃을 잡아주는 과정도 추가되어야 하기에 이를 조금 더 간단하게 구현할 수 있게 현재와 같이 하나의 텍스트뷰에 내용을 합쳐주는 방식을 선택하였습니다.
나중에 title과 body는
```swift
let title = textView.text.split(separator: "\n")[0]
let body = textView.text.split(separator: "\n")[1...].joined(separator: "\n\n")
```
위와 같은 방식을 통해 구분해줄 예정이었습니다!

2023-04-27 05:28 UTC, fatherLeon commented on Diary/Controller/DetailViewController.swift
> +    private var textView: UITextView = {
`let`상수로 수정하였습니다
추가로 `tableView` 역시 `let`으로 수정하였습니다!!

2023-04-27 05:28 UTC, kak1x commented on Diary/Controller/DetailViewController.swift
> +    private var textView: UITextView = {
다이어리의 제목과 내용을 포함하기 때문에 `diaryTextView`로 변경해주었습니다.

2023-04-27 05:51 UTC, fatherLeon commented on Diary/Controller/DetailViewController.swift
> +    private var diaryItem: DiaryModel?
기존에 존재하는 일기인 경우와 새로만드는 일기를 구별하기 조금 더 수월하다고 생각하였습니다.

말씀들어보니 새로 만드는 일기장의 경우 `diaryItem`프로퍼티가 사용되지 않는것 같아 옵셔널을 제거하고 빈 문자열을 가지는 `diaryItem`을 주는 방향으로 구현하였습니다.

2023-04-27 06:02 UTC, fatherLeon commented on Diary/Controller/DetailViewController.swift
> +    }
`viewDidAppear` 뷰가 보이기 이전에 호출되는 메소드입니다.

기존 `becomeFirstResponder`메소드를 사용하여 처음 화면으로 들어섰을 때 곧바로 키보드가 보이게 했었는데 그럴 경우 키보드가 부자연스럽게 동작하여 `viewDidAppear`쪽에서 호출시켰었는데 현재는 `becomeFirstResponder`를 사용하지 않기 때문에 `viewDidLoad`시점으로 해당 메소드를 옮겼습니다

2023-04-27 06:12 UTC, kak1x commented on Diary/Controller/DiaryViewController.swift
> +        view.backgroundColor = .systemBackground
`configureUI` 함수로 빼주었습니다~!

2023-04-27 06:20 UTC, kak1x commented on Diary/Controller/DiaryViewController.swift
> +    }
`showFailAlert` 메서드를 구현하여 실패시 유저에게 Alert을 보여주도록 수정하였습니다!

2023-04-27 06:35 UTC, fatherLeon commented on Diary/Etc/TextViewExtension.swift
> +extension UITextView {
다른곳에서 추가적으로 사용될 일은 없다고 생각하여
말씀하신대로 `fileprivate`로 접근제어자를 설정하여 뷰 컨트롤러 파일 내에 추가하였습니다.

2023-04-27 06:36 UTC, kak1x commented on Diary/Model/DiaryModel.swift
> +    var date: Int
추후에 데이터를 수정하게 되면 `title, body, date` 모두 변경이 가능해야 한다고 생각되어 `variable`로 선언해주었습니다.

2023-04-27 06:41 UTC, fatherLeon commented on Diary/View/DiaryInfoTableViewCell.swift
> +
셀이 재사용되는 시점에서 특정 동작을 할 수 있도록 만들어주는 역할을 합니다.
특정 데이터가 없는 경우 이전의 데이터가 들어갈 우려가 있으므로 추가 구현했습니다.

2023-04-27 06:47 UTC, kak1x commented on .swiftlint.yml
> +disabled_rules: # Default Rules에서 비활성화할 규칙
.yml 파일에 공개하면 안되는 DB 관련 정보등 민감한 정보가 포함되어 있을 경우 `.gitIgnore`를 통해 이를 깃에 올리지 않을 수 있습니다.
그러나 `SwiftLint를 활용하여 코드 스타일을 일관성있게 유지합니다`의 요구사항을 위해 `.swiftlint.yml` 파일은 공유되어야 한다고 생각되는데 하비의 의견은 어떠신가요?

2023-04-27 06:59 UTC, kak1x commented on Diary/Controller/DetailViewController.swift
> +        textView.scrollIndicatorInsets = textView.contentInset
오 이런 것도 있었네요! 되게 간단하게 설정해줄 수 있어서 좋은 것 같습니다😀
알려주신 keyboardLayoutGuide를 사용하기 위해 최소 버전을 15.0으로 설정해주고 이를 사용하여 구현해주었습니다!

2023-04-27 07:07 UTC, fatherLeon commented on Diary/View/DiaryInfoTableViewCell.swift
> +        stackView.spacing = 5
stackView -> dateAndBodyStackView
mainStackView -> diaryStackView로 변경하였습니다.

`setCustomSpacing`은 스택 뷰 전체 spacing을 주는 것이 아닌 특정 뷰 다음의 spacing을 주는 메소드입니다.
하지만 저희 스택뷰의 경우 2개의 뷰만 존재하기 때문에 굳이 사용할 필요는 없다고 생각하여 spacing을 주었습니다

2023-04-27 07:08 UTC, fatherLeon commented on Diary/Model/DiaryModel.swift
> +struct DiaryModel: Decodable {
`Diary`라는 이름이 프로젝트명과 같아서 `Model`을 붙였는데 이런 경우 하비는 주로 어떤 방식으로 네이밍을 해주시나요???

2023-04-30 12:33 UTC, havilog commented on .swiftlint.yml
> +disabled_rules: # Default Rules에서 비활성화할 규칙
전 사실 린트를 별로 안좋아해서..ㅎㅎㅎ
컨벤션은 개인 취향이라 팀에서 결정하는게 베스트일거 같은데,
팀 전체가 린트로 코드관리를 빡빡하게 하기로 결정한거라면 뭐 올려도 상관없을거 같기도 하네요~

2023-04-30 12:36 UTC, havilog commented on Diary/Controller/DetailViewController.swift
> +    private var diaryItem: DiaryModel?
새 일기와, 기존 일기를 구분하는 로직을 만든 뒤에,
그 무언가를 가지고 디테일에 진입하는게 더 자연스러울거 같아요!
static var가 될 수도 있고, enum이 될 수도 있고, 말씀하신것처럼 빈 문자열이 될 수도 있을거 같구요

일기의 상세에 들어갔는데 일기가 없는게 조금 의아했었어요 ㅎㅎ 정답은 없습니다

2023-04-30 12:39 UTC, havilog commented on Diary/Controller/DetailViewController.swift
> +    private var textView: UITextView = {
음 근데 이건 기획이 확실하게 안정해져 있어서 그런거 같긴한데,
레이아웃을 잡아주는게 저렇게 줄바꿈으로 파싱해서 넣어주는것보다 안전할거 같아요.

파싱해서 넣어주면,
1. 이상한 문자열이 들어왔을 때 [1...]에 아무것도 없을 수 있고,
2. 타이틀과 바디가 제대로 분리가 안될 수도 있고,
3. 서브스크립트로 잘못 접근하다가 크래시가 날 수도 있어서
굳이 저런 방식으로 위험도를 증가시키는게 좋을지 잘 모르겠는데,

두 분 생각은 어떠신가요?

2023-04-30 12:41 UTC, havilog commented on Diary/Controller/DetailViewController.swift
> +    }
노티를 등록해주는건, 한 번만 해주면 될거같은데,
뷰디드어피어에서 저 로직이 들어가면,
인스턴스가 하나인데 노티가 5번 등록되어 동작이 이상해질 수도 있을거 같다는 생각이 들었어요!

2023-04-30 12:42 UTC, havilog commented on Diary/Controller/DetailViewController.swift
> +        textView.scrollIndicatorInsets = textView.contentInset
최소 15라서 현업에서 사용하실 수 있으실지 모르겠지만,
이걸 꼭 쓰라는 얘기는 아니었고, 존재만 알고 가셔도 좋을거 같아요!

2023-04-30 12:45 UTC, havilog commented on Diary/Model/DiaryModel.swift
> +    var date: Int
그렇다면 혹시 Diary는 Struct라서 title을 바꾸면 객체가 재할당 될 거 같은데,
새 구조체를 만드는 것과, 기존의 것을 바꾸는 것 중에 바꾸는 방법을 선택한 이유와,
둘이 어떤차이가 있는지 설명해주세요~

2023-04-30 12:47 UTC, havilog commented on Diary/Model/DiaryModel.swift
> +struct DiaryModel: Decodable {
이건.. 프로젝트 명이 너무 포멀해서.. 인거 같은데 ㅋㅋ
저라면 그냥 프로젝트 명이랑 모델이랑 똑같이 쓸거 같아요

2023-05-01 09:12 UTC, kak1x commented on Diary/Controller/DetailViewController.swift
> +    private var diaryItem: DiaryModel?
DiaryState 열거형 타입을 구현해주었습니다.
이를 통해 새 일기를 만들 경우 create 케이스를, 기존 일기에 접근하는 경우 edit 케이스를 가질 수 있도록 해주었습니다.

2023-05-02 09:56 UTC, merged